taiga-family/taiga-ui

README.md, projects/cdk/README.md
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> docs(readme): add

projects/cdk/classes/test/validation-error.spec.ts, projects/cdk/utils/browser/test/browsers.spec.ts, projects/cdk/utils/format/test/px.spec.ts, projects/cdk/utils/miscellaneous/test/ease-in-out-quad.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> chore(tests): add some new tests

projects/cdk/abstract/control.ts, projects/cdk/decorators/pure.ts, projects/cdk/decorators/test/pure.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat(cdk): `Pure` add access to `this`

projects/cdk/utils/dom/test/get-actual-target.spec.ts, projects/cdk/utils/dom/test/is-current-target.spec.ts, projects/cdk/utils/focus/tests/is-native-focused-in.spec.ts, projects/cdk/utils/focus/tests/is-native-mouse-focusable.spec.ts, projects/cdk/utils/focus/tests/move-focus.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> chore(all): add some tests

projects/cdk/utils/dom/test/contains-or-after.spec.ts, projects/cdk/utils/dom/test/get-clipboard-data-text.spec.ts, projects/cdk/utils/dom/test/get-document-or-shadow-root.spec.ts, projects/cdk/utils/dom/test/get-element-offset.spec.ts, projects/cdk/utils/dom/test/get-scrollable-parent.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> chore(all): add some more tests

projects/cdk/components/portal-host/test/portal-host.component.spec.ts, projects/cdk/components/portal-host/test/portal.service.spec.ts, projects/cdk/observables/test/watch.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> chore(all): add new tests

projects/cdk/classes/assert.ts, projects/cdk/date-time/day.ts, projects/cdk/date-time/month.ts, projects/cdk/date-time/test/month.spec.ts, projects/cdk/enums/assert-level.ts, projects/cdk/enums/index.ts, projects/cdk/enums/month-number.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor(cdk): remove unused assertion level

projects/cdk/observables/test/replay-control-value-changes.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> chore(tests): add

projects/cdk/date-time/test/month.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> chore(tests): increase TuiMonth coverage to 100%

projects/cdk/abstract/control.ts, projects/cdk/abstract/interactive.ts, projects/cdk/classes/assert.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor(cdk): small refactors

projects/cdk/date-time/time.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(cdk): `TuiTime` fix currentLocal at 0:00

projects/cdk/utils/dom/test/get-element-obscurers.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> chore(tests): add getElementObscurers tests

projects/cdk/utils/focus/set-native-focused.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat(cdk): remove preventScroll polyfill

projects/cdk/observables/test/drag-and-drop.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> chore(tests): add drag-and-drop tests

projects/cdk/directives/let/test/let-context.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> chore(tests): add let-context tests

projects/cdk/services/test/directive-styles.service.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> chore(tests): add directive-styles tests

projects/cdk/utils/focus/tests/get-closest-keyboard-focusable.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> chore(cdk): get-closest-keyboard tests

karma.conf.js, projects/cdk/directives/pressed/test/pressed.directive.spec.ts, projects/cdk/observables/pressed-observable.ts, projects/cdk/observables/stop-propagation.ts, projects/cdk/observables/test/prevent-default.spec.ts, projects/cdk/observables/test/stop-propagation.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat(observables): `stopPropagation` add operator

projects/cdk/date-time/time.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> refactor(cdk): improvement time conversion

projects/cdk/directives/overscroll/overscroll.directive.ts, projects/cdk/types/event-with.ts, projects/cdk/utils/dom/can-scroll.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor(types): fix types for `TuiEventWith`

projects/cdk/services/test/resize.service.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> chore(tests): fix resize service tests

package-lock.json, package.json, projects/cdk/abstract/control.ts, projects/cdk/ng-package.json, projects/cdk/package.json
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat(cdk): add @ng-web-apis/mutation-observer

projects/cdk/abstract/control.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(cdk): `Control` fix typing

projects/cdk/constants/matcher.ts, projects/cdk/directives/focus-trap/focus-trap.directive.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(cdk): `FocusTrap` blur manually to prevent ExpressionChanged error

projects/cdk/constants/matcher.ts, projects/cdk/directives/focus-trap/focus-trap.directive.ts, tsconfig.json
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> Focus trap

projects/cdk/date-time/date-fillers.ts, projects/cdk/date-time/date-time.ts, projects/cdk/date-time/day-range.ts, projects/cdk/date-time/test/date-fillers.spec.ts, projects/cdk/date-time/test/day-range.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat(cdk): i18n for date fillers

projects/addon-mobile/ng-package.json, projects/addon-mobile/scripts/copy-less.js, projects/core/ng-package.json, projects/core/scripts/copy-less.js
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): include styles as library asset

projects/core/providers/mode.provider.ts, projects/core/utils/miscellaneous/mode-factory.ts, projects/demo/src/modules/components/input-file/input-file.module.ts, projects/demo/src/modules/components/input-file/input-file.template.html, projects/kit/components/input-file/file/file.style.less, projects/kit/components/input-file/input-file.component.ts, projects/kit/components/input-file/input-file.style.less, projects/kit/components/input-file/input-file.template.html, projects/kit/components/line-clamp/line-clamp.component.ts, projects/kit/components/tabs/tab/tab.style.less, projects/kit/components/tabs/underline/underline.style.less
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat(kit): `InputFile` add mode support

projects/cdk/observables/zone-free.ts, projects/core/components/scroll-controls/scroll-controls.component.ts, projects/core/components/scroll-controls/scroll-controls.template.html, projects/demo/src/modules/app/app.providers.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(cdk): `tuiZoneOptimized` fix re-entering the zone

projects/core/styles/taiga-ui-theme.less, projects/core/styles/theme/wrapper.less, projects/demo/src/index.html
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix theme less import syntax for StackBlitz

CHANGELOG.md, package-lock.json, package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-editor/package.json, projects/addon-mobile/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/cdk/package.json, projects/core/package.json, projects/icons/package.json, projects/kit/package.json, projects/testing/package.json
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> chore(release): 2.1.1

projects/kit/components/data-list-wrapper/data-list-group-wrapper.template.html, projects/kit/components/data-list-wrapper/data-list-wrapper.template.html
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(kit): `DataListWrapper` fix `emptyContent` not working

projects/core/styles/mixins/mixins.less
closes #90
-   [x] Bugfix
Issue Number: #90 
TuiActionComponent transition became smoother
-   [ ] Yes
-   [x] No
=> fix: add will-change for smooth transition

projects/kit/components/input-date-range/input-date-range.component.ts, projects/kit/components/input-date-range/input-date-range.template.html, projects/kit/components/input-date-time/input-date-time.component.ts, projects/kit/components/input-date-time/input-date-time.template.html, projects/kit/components/input-date/input-date.component.ts, projects/kit/components/input-date/input-date.template.html
-   [ ] Bugfix
Issue Number: #100
-   [ ] Yes
-   [ ] No
=> fix(kit): `InputDate` fix mobile calendar

projects/core/styles/markup/tui-text.less, projects/core/styles/mixins/text.less, projects/demo/src/modules/markup/typography/typography.template.html
-   [ ] Bugfix
The documentation for the typography contains a bunch of errors (wrong class names, etc)
Documentation errors have been fixed
-   [ ] Yes
-   [x] No
=> docs(typography): fix typography documentation errors

projects/demo/src/modules/markup/icons/icons.component.ts, projects/demo/src/modules/markup/icons/icons.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> refactor(demo): icons page

projects/addon-commerce/components/input-CVC/test/input-CVC.component.spec.ts, projects/addon-commerce/components/input-card/test/input-card.component.spec.ts, projects/addon-commerce/components/input-expire/test/input-expire.component.spec.ts, projects/addon-commerce/validators/test/luhn.validator.spec.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> chore(addon-commerce): translate few tests

projects/kit/components/select/select.template.html
-   [x] Bugfix
Closes #115
-   [ ] Yes
-   [x] No
=> fix(kit): `Select` fix template for falsy values

projects/addon-tablebars/components/table-bars-host/table-bars-host.style.less, projects/kit/components/tabs/tabs-with-more/tabs-with-more.providers.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): `TabsWithMore` fix freezing on resize loop

projects/core/components/primitive-checkbox/primitive-checkbox.component.ts, projects/core/tokens/checkbox-appearance.ts, projects/core/tokens/index.ts, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/home/home.template.html, projects/demo/src/modules/app/pages.ts, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/radio/radio.component.ts, projects/kit/components/tag/tag.style.less, projects/kit/tokens/index.ts, projects/kit/tokens/tag-status.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> feat(kit): add tokens to customize `Checkbox`, `Radio` and `InputTag`

projects/addon-commerce/components/input-CVC/input-CVC.component.ts, projects/addon-commerce/components/input-expire/input-expire.component.ts, projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/core/mask/index.ts, projects/core/mask/with-text-mask.ts, projects/demo/src/modules/components/input-copy/input-copy.component.ts, projects/demo/src/modules/components/input-copy/input-copy.template.html, projects/demo/src/modules/components/input-inline/input-inline.component.ts, projects/demo/src/modules/components/input-inline/input-inline.template.html, projects/kit/components/input-copy/input-copy.component.ts, projects/kit/components/input-copy/input-copy.module.ts, projects/kit/components/input-copy/input-copy.template.html, projects/kit/components/input-count/input-count.component.ts, projects/kit/components/input-inline/input-inline.component.ts, projects/kit/components/input-inline/input-inline.module.ts, projects/kit/components/input-inline/input-inline.template.html, projects/kit/components/input-inline/test/input-inline.component.spec.ts, projects/kit/components/input/input.component.ts, projects/kit/components/input/input.module.ts, projects/kit/components/input/input.template.html, projects/kit/components/input/test/input.component.spec.ts
…`InputCopy`
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> feat(kit): allow setting mask directly on `Input`, `InputInline` and `InputCopy`

projects/demo/src/modules/components/breadcrumbs/examples/1/index.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> docs: fix a typo

projects/cdk/directives/media/media.directive.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(cdk): `Media` fix stuttering in Safari

projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less, projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html
-   [ ] Bugfix
Closes #102
-   [ ] Yes
-   [x] No
=> chore(kit): `TabsWithMore` make class less generic to avoid collision

projects/cdk/utils/browser/is-IE.ts, projects/cdk/utils/browser/is-edge-older-than.ts, projects/cdk/utils/browser/is-edge.ts, projects/cdk/utils/browser/is-firefox.ts, projects/cdk/utils/browser/test/browsers.spec.ts
-   [X] Bugfix
Closes #156 
`isFirefox` check now works as expected
-   [ ] Yes
-   [X] No
=> fix(cdk): fix isFirefox check

projects/addon-editor/components/editor-socket/editor-socket.component.ts, projects/addon-editor/directives/design-mode/design-mode.directive.ts, projects/cdk/tokens/sanitizer.ts, projects/core/components/svg/svg.component.ts, projects/core/components/svg/test/svg.component.spec.ts, projects/core/services/svg.service.ts, projects/core/tokens/index.ts, projects/core/tokens/sanitizer.ts
-   [x] Bugfix
Closes #143
-   [ ] Yes
-   [x] No
=> fix(core): `Svg` properly use Angular `Sanitizer`

projects/demo/src/modules/info/related/related.template.html
=> "highly" typo

projects/kit/components/avatar/avatar.module.ts, projects/kit/components/avatar/avatar.template.html
-   [ ] Bugfix
Closes #62
All avatar images are loaded lazily
-   [ ] Yes
-   [x] No
=> feat(kit): use lazy loading strategy in avatar component

projects/core/components/button/button.component.ts
-   [x] Bugfix
The size of a loader in XL button is `s`
The size of a loader in XL button is `m`
-   [ ] Yes
-   [n] No
=> fix(button): fix button loader size for XL

projects/demo/src/modules/markup/spaces/examples/1/index.html, projects/demo/src/modules/markup/spaces/examples/1/index.style.less, projects/demo/src/modules/markup/spaces/examples/2/index.html, projects/demo/src/modules/markup/spaces/examples/2/index.style.less, projects/demo/src/modules/markup/spaces/spaces.module.ts, projects/demo/src/modules/markup/typography/typography.template.html
-   [ ] Bugfix
Closes #197
-   [ ] Yes
-   [x] No
=> docs(common): copy spaces styles on click

projects/core/components/dialog/dialog.component.ts, projects/core/components/dialog/dialog.style.less, projects/core/components/dialog/dialog.template.html
-   [x] Bugfix
https://user-images.githubusercontent.com/4103756/106378669-e903e680-63a6-11eb-86bc-57f2edffb457.mp4
Closes #148 
https://user-images.githubusercontent.com/4103756/106378675-f1f4b800-63a6-11eb-8a69-9907bcfaa5e3.mp4
-   [ ] Yes
-   [x] No
=> fix(core): dialog not closing due to transparent border, closes #148

projects/core/components/dialog/dialog.component.ts, projects/core/components/dialog/dialog.style.less, projects/core/components/dialog/dialog.template.html, projects/core/types/dialog-size.ts, projects/demo/src/modules/services/dialogs/dialogs.component.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> New size for dialogs

projects/cdk/directives/active-zone/active-zone.directive.ts, projects/core/components/svg/svg.style.less, projects/core/services/svg.service.ts, projects/core/utils/dom/process-icon.ts
-   [x] Bugfix
Closes #107 
-   [ ] Yes
-   [x] No
=> fix(core): `Svg` fix custom icons processing

projects/addon-commerce/enums/currency-code.ts, projects/addon-commerce/enums/currency.ts, projects/addon-commerce/utils/get-currency-symbol.ts
-   [ ] Bugfix
UAH was missing from currencies in money component
Closes #
New currency UAH (Ukrainian hryvnia) has been added.
-   [ ] Yes
-   [x] No
=> feat(addon-commerce): add UAH currency

projects/core/styles/markup/tui-space.less
-   [ ] Bugfix
Currently there is no class to reset the margin of an element to 0 px. This, however, can be very useful if one wants to reset the margin of an element that has margin by default.
A zero space option has been added to the space classes.
-   [ ] Yes
-   [x] No
=> feat(core): added a zero space-option to space classes

projects/kit/components/tabs/tab/tab.providers.ts, projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts, projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less, projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): `Tabs` clicking on external links will not update active index

projects/addon-commerce/components/money/test/money.component.spec.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.providers.ts, projects/addon-mobile/directives/ripple/ripple.providers.ts, projects/addon-mobile/tokens/loaded.ts, projects/core/components/data-list/data-list-dropdown-manager.directive.ts, projects/core/components/dialog/dialog.providers.ts, projects/core/services/router-link-active.service.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> refactor(all): all rxjs NEVERs are EMPTY when possible

projects/core/components/dialog/dialog.component.ts, projects/core/components/dialog/dialog.providers.ts
=> fix(core): `Dialog` fix closing non-dismissible dialog by clicking on border

projects/core/components/link/link.component.ts, projects/core/components/link/link.style.less, projects/demo/src/modules/components/link/examples/3/index.html, projects/demo/src/modules/components/link/link.template.html
=> fix(core): `Link` properly handle various modes

projects/core/components/link/link.style.less
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(core): fixed underline button link

projects/addon-table/components/table/directives/cell.directive.ts, projects/addon-table/components/table/directives/row.directive.ts, projects/addon-table/components/table/tbody/tbody.component.ts, projects/addon-table/components/table/tbody/tbody.template.html, projects/addon-table/components/table/tr/tr.component.ts, projects/addon-table/components/table/tr/tr.template.html, projects/addon-table/interfaces/index.ts, projects/addon-table/interfaces/package.json, projects/addon-table/interfaces/row-context.ts, projects/demo/src/modules/tables/table/examples/1/index.html, projects/demo/src/modules/tables/table/examples/2/index.html, projects/demo/src/modules/tables/table/examples/3/index.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore(addon-table): quickly fix API

projects/kit/components/toggle/toggle.style.less
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): fix loader in toggle size m (#261)

projects/cdk/utils/browser/index.ts, projects/cdk/utils/browser/is-safari.ts, projects/core/components/loader/loader.component.ts, projects/core/components/loader/loader.template.html, projects/core/utils/mask/create-auto-corrected-money-pipe.ts
=> chore(core, kit): try to fix caret input-number in Safari

projects/demo/src/modules/components/radio/examples/import/define-options.txt, projects/demo/src/modules/components/radio/radio.component.ts, projects/demo/src/modules/components/radio/radio.template.html, projects/kit/components/radio/index.ts, projects/kit/components/radio/radio-options.ts, projects/kit/components/radio/radio.component.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> chore(kit): data comes from the token

projects/cdk/abstract/multiple-control.ts, projects/cdk/abstract/nullable-control.ts, projects/core/abstract/abstract-dropdown.ts
=> chore(cdk): give you up, let you down, run around and desert you

projects/core/components/loader/loader.component.ts, projects/core/components/loader/loader.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(core): `Loader` fix form freezing in Safari

projects/addon-doc/src/components/demo/demo.template.html, projects/demo/src/modules/components/abstract/dropdown-controller-documentation/dropdown-controller-documentation.template.html, projects/demo/src/modules/components/abstract/hint-controller-documentation/hint-controller-documentation.template.html, projects/demo/src/modules/components/abstract/textfield-controller-documentation/textfield-controller-documentation.template.html, projects/demo/src/modules/components/input-tag/input-tag.template.html, projects/demo/src/modules/components/input/examples/5/template.html, projects/demo/src/modules/components/input/input.template.html, projects/demo/src/modules/components/link/examples/1/index.html, projects/demo/src/modules/components/link/examples/3/index.html, projects/demo/src/modules/components/link/link.template.html, projects/demo/src/modules/components/loader/loader.template.html, projects/demo/src/modules/components/marker-icon/marker-icon.template.html, projects/demo/src/modules/components/primitive-textfield/primitive-textfield.template.html, projects/demo/src/modules/directives/dropdown-controller/dropdown-controller.template.html, projects/demo/src/modules/directives/dropdown-controller/examples/1/index.html, projects/demo/src/modules/services/dialogs/dialogs.template.html, projects/demo/src/modules/services/notifications/notifications.template.html
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(demo): fix routing

projects/kit/components/input-tag/input-tag.style.less
-   [x] Bugfix
-   [ ] Yes
-   [x] No
I'm not sure but this definitely needs a review because other places of the layout may be affected (very small chance, but...).
=> fix(kit): `input-tag` change layout to fix moved error-icon

projects/addon-mobile/directives/sidebar/sidebar.component.ts, projects/addon-mobile/directives/sidebar/sidebar.directive.ts, projects/addon-mobile/directives/sidebar/sidebar.style.less, projects/addon-mobile/directives/sidebar/sidebar.template.html
-   [ ] Bugfix
Sidebar has fixed width
With autoWidth=true sidebar width will depend on content width.
-   [ ] Yes
-   [x] No
=> feat(addon-mobile): add width:auto option for sidebar

projects/addon-doc/src/components/main/main.component.ts, projects/kit/components/input-password/input-password.component.ts, projects/kit/components/input-password/input-password.template.html
-   [x] Bugfix
Closes #288 
-   [ ] Yes
-   [x] No
=> fix(kit): fix change detection

projects/cdk/directives/active-zone/active-zone.directive.ts, projects/cdk/directives/focus-trap/focus-trap.directive.ts, projects/kit/components/input-password/input-password.component.ts
fix(cdk): `FocusTrap` fix ExpressionChanged error
-   [x] Bugfix
Closes #278
Closes #251
-   [ ] Yes
-   [ ] No
=> fix(cdk): `ActiveZone` stay in zone if focused element removed

projects/cdk/services/hovered.service.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): fix hovered service on mobile safari 12

projects/addon-editor/components/toolbar/toolbar.style.less, projects/addon-editor/components/toolbar/toolbar.template.html
-   [x] Bugfix
Closes #310
The correct colors are displayed and applied
-   [ ] Yes
-   [x] No
=> fix(addon-editor): font & highlight displayed colors

projects/kit/components/tabs/tabs/tabs.component.ts, projects/kit/components/tabs/underline/underline.component.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): `Tabs` fix extra change detection ticks

projects/kit/components/text-area/text-area.component.ts, projects/kit/components/text-area/text-area.style.less
-   [x] Bugfix
Closes #295 
-   [ ] Yes
-   [x] No
=> fix(kit): fix style of textarea

CHANGELOG.md, package-lock.json, package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-editor/package.json, projects/addon-mobile/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/cdk/package.json, projects/core/constants/version.ts, projects/core/package.json, projects/i18n/package.json, projects/icons/package.json, projects/kit/package.json, projects/testing/package.json
=> chore(release): 2.7.0

projects/cdk/tokens/is-ios.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): fix apple device detection

projects/kit/components/multi-select/multi-select.style.less
-   [x] Bugfix
Closes #330
-   [ ] Yes
-   [x] No
=> fix(multi-select): improve arrow rotation

projects/kit/components/input-number/input-number.component.ts
-   [ ] Bugfix
Closes #232
-   [ ] Yes
-   [ ] No
=> fix(kit): `InputNumber` fix caret for zeroes in decimal part

projects/addon-editor/constants/default-editor-styles.ts, projects/addon-editor/directives/design-mode/design-mode.directive.ts, projects/addon-editor/styles/editor-socket.css, projects/core/components/hints-host/hint-box/hint-box.component.ts, projects/core/components/label/label.style.less
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(addon-editor): `Editor` fix scroll jumping on edits

projects/addon-editor/components/editor/editor.component.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(addon-editor): open links in a new tab

projects/addon-editor/components/editor/editor.component.ts, projects/addon-editor/components/toolbar/toolbar.component.ts, projects/addon-editor/components/toolbar/toolbar.style.less, projects/addon-editor/directives/design-mode/design-mode.directive.ts, projects/core/components/scroll-controls/scroll-controls.component.ts, projects/core/components/scroll-controls/scrollbar.directive.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(addon-editor): `Editor` fix scrollbar

projects/kit/components/stepper/step/step.style.less
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): fix disabled step on stepper

projects/demo/src/modules/components/input-count/examples/1/index.html, projects/demo/src/modules/components/input-count/examples/1/index.ts, projects/kit/components/input-count/input-count.component.ts, projects/kit/components/input-count/input-count.template.html, projects/kit/components/input-count/test/input-count.component.spec.ts
-   [x] Bugfix
Closes #336 
-   [ ] Yes
-   [x] No
=> fix(input-count): correct work with negative values

ROADMAP.md
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix: ROADMAP.md typos correction

projects/demo/src/modules/components/data-list/data-list.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(demo): add notification about import tuiMiltiSelect

projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.providers.ts, projects/addon-mobile/directives/touchable/touchable.directive.ts, projects/cdk/constants/matcher.ts, projects/cdk/directives/overscroll/overscroll.directive.ts, projects/cdk/observables/drag-and-drop-from.ts, projects/cdk/services/hovered.service.ts, projects/demo/src/modules/tables/table/examples/4/index.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(cdk): use passive event listeners

projects/cdk/services/scroll.service.ts
-   [x] Bugfix
Closes #354 
-   [ ] Yes
-   [x] No
=> fix(cdk): fix NullInjectorError in scrollService

projects/core/components/label/label.style.less, projects/demo/src/modules/components/tabs/examples/3/index.ts, projects/demo/src/modules/components/tabs/examples/4/index.ts, projects/demo/src/modules/components/tabs/examples/5/index.ts, projects/demo/src/modules/components/tabs/examples/7/index.html, projects/demo/src/modules/components/tabs/examples/7/index.ts, projects/demo/src/modules/components/tabs/tabs.component.ts, projects/demo/src/modules/components/tabs/tabs.module.ts, projects/demo/src/modules/components/tabs/tabs.template.html, projects/kit/components/tabs/tab/tab.component.ts, projects/kit/components/tabs/tab/tab.providers.ts, projects/kit/components/tabs/tab/tab.template.html, projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts, projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less, projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html, projects/kit/components/tabs/tabs.module.ts, projects/kit/components/tabs/underline/underline.style.less
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> feat(kit): `TabsWithMore` always show active tab

projects/cdk/services/scroll.service.ts, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/input-tag/input-tag.template.html
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(kit): fix fixed scrolling with arrows in input-tag

projects/cdk/directives/active-zone/active-zone.directive.ts, projects/kit/components/multi-select/hide-selected.pipe.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore: small refactors

projects/addon-editor/directives/design-mode/design-mode.directive.ts, projects/cdk/directives/focus-trap/focus-trap.directive.ts, projects/cdk/utils/focus/get-closest-keyboard-focusable.ts, projects/cdk/utils/focus/set-native-mouse-focused.ts, projects/core/components/dropdown-box/dropdown-box.component.ts, projects/core/components/hosted-dropdown/hosted-dropdown.component.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/hosted-dropdown/examples/4/index.html, projects/demo/src/modules/components/hosted-dropdown/examples/4/index.less, projects/demo/src/modules/components/hosted-dropdown/examples/4/index.ts, projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.component.ts, projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.module.ts, projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.template.html, projects/demo/src/modules/components/tabs/examples/5/index.html, projects/demo/src/modules/components/tabs/examples/5/index.less, projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts, projects/kit/directives/dropdown-hover/dropdown-hover.directive.ts, projects/kit/directives/dropdown-hover/dropdown-hover.module.ts, projects/kit/directives/dropdown-hover/index.ts, projects/kit/directives/dropdown-hover/package.json, projects/kit/directives/index.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> feat(kit): `DropdownHover` add new directive

projects/demo/src/modules/pipes/filter/examples/1/component.ts, projects/demo/src/modules/pipes/filter/examples/1/template.html, projects/demo/src/modules/pipes/filter/filter.component.ts, projects/demo/src/modules/pipes/filter/filter.module.ts, projects/demo/src/modules/pipes/filter/filter.template.html, projects/demo/src/modules/pipes/mapper/examples/1/component.ts, projects/demo/src/modules/pipes/mapper/examples/1/template.html, projects/demo/src/modules/pipes/mapper/examples/2/component.ts, projects/demo/src/modules/pipes/mapper/examples/2/template.html, projects/demo/src/modules/pipes/mapper/mapper.component.ts, projects/demo/src/modules/pipes/mapper/mapper.module.ts, projects/demo/src/modules/pipes/mapper/mapper.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> docs(demo): examples are written for mapperPipe and filterPipe

CHANGELOG.md, package-lock.json, package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-editor/package.json, projects/addon-mobile/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/cdk/package.json, projects/core/constants/version.ts, projects/core/package.json, projects/i18n/package.json, projects/icons/package.json, projects/kit/package.json, projects/ng-add/package.json, projects/testing/package.json
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore(release): 2.8.1

CHANGELOG.md, package-lock.json, package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-editor/package.json, projects/addon-mobile/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/cdk/package.json, projects/core/constants/version.ts, projects/core/package.json, projects/i18n/package.json, projects/icons/package.json, projects/kit/package.json, projects/ng-add/package.json, projects/testing/package.json
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore(release): 2.8.2

projects/kit/components/input-date-time/input-date-time.component.ts
-   [x] Bugfix
Closes #375 
-   [ ] Yes
-   [x] No
=> fix(kit): update native value on day click in input-date-time

projects/core/components/primitive-textfield/primitive-textfield.template.html, projects/core/components/tooltip/tooltip.component.ts, projects/core/components/tooltip/tooltip.template.html, projects/core/directives/hint-controller/hint-controller.directive.ts, projects/core/directives/hint/hint.directive.ts, projects/core/directives/pointer-hint/pointer-hint.directive.ts, projects/demo/src/modules/components/tooltip/tooltip.component.ts, projects/demo/src/modules/components/tooltip/tooltip.template.html, projects/demo/src/modules/directives/hint-controller/hint-controller.component.ts, projects/demo/src/modules/directives/hint-controller/hint-controller.template.html, projects/demo/src/modules/directives/hint/hint.component.ts, projects/demo/src/modules/directives/hint/hint.template.html, projects/demo/src/modules/directives/pointer-hint/pointer-hint.component.ts, projects/demo/src/modules/directives/pointer-hint/pointer-hint.template.html, projects/kit/components/input-slider/input-slider.template.html, projects/kit/components/input-tag/input-tag.template.html, projects/kit/components/text-area/text-area.template.html
-   [ ] Bugfix
Closes #202 
Copy of #205 with implementation of review notes
-   [ ] Yes
-   [x] No
=> feat(core): tooltip show hide delay

projects/demo/src/modules/components/badge/badge.component.ts, projects/demo/src/modules/components/badge/badge.module.ts, projects/demo/src/modules/components/badge/badge.template.html, projects/demo/src/modules/components/badge/examples/4/index.html, projects/demo/src/modules/components/badge/examples/4/index.less, projects/kit/components/badge/badge.component.ts, projects/kit/components/badge/badge.style.less, projects/kit/components/badge/test/badge.component.spec.ts
-   [ ] Bugfix
You can't use icons in badge
You can pass custom template in badge
-   [ ] Yes
-   [x] No
=> feat(kit): badge with icon

projects/demo/src/modules/customization/icon-set/icon-set.component.ts
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(demo): remove duplicated icons

projects/kit/components/badge/badge.style.less
-   [x] Bugfix
Color of icon is not the same as text of badge in onLight mode
Closes #
Icon color is the same as text color by default
-   [ ] Yes
-   [x] No
=> fix(kit): fix icon color of badge in onLight mode

projects/kit/components/tabs/tab/tab.style.less, projects/kit/components/tabs/underline/underline.style.less
-   [x] Bugfix
Closes #410 
-   [ ] Yes
-   [ ] No
=> fix(kit): fix tabs color in tuiMode=onLight

projects/demo/src/modules/components/badged-content/badged-content.component.ts, projects/demo/src/modules/components/breadcrumbs/breadcrumbs.module.ts, projects/demo/src/modules/components/breadcrumbs/examples/1/index.html, projects/demo/src/modules/components/breadcrumbs/examples/1/index.ts, projects/demo/src/modules/components/breadcrumbs/examples/import/insert-template.txt, projects/kit/components/breadcrumbs/breadcrumb.directive.ts, projects/kit/components/breadcrumbs/breadcrumbs-wrapper.component.ts, projects/kit/components/breadcrumbs/breadcrumbs-wrapper.style.less, projects/kit/components/breadcrumbs/breadcrumbs-wrapper.template.html, projects/kit/components/breadcrumbs/breadcrumbs.component.ts, projects/kit/components/breadcrumbs/breadcrumbs.module.ts, projects/kit/components/breadcrumbs/index.ts, projects/kit/components/breadcrumbs/test/breadcrumbs-wrapper.component.spec.ts
-   [ ] Bugfix
Closes #388
-   [ ] Yes
-   [x] No
=> Implement new breadcrumbs component

projects/addon-table/utils/default-sort.ts
-   [X] Bugfix
Closes #424
-   [ ] Yes
-   [ ] No
I tried adding a test. But struggled to run single test to ensure it works
=> fix(addon-table): defaultSorter ignore case

projects/addon-doc/src/utils/inspect.ts, projects/demo/src/locale/messages.xlf, projects/demo/src/modules/components/abstract/textfield-controller-documentation/textfield-controller-documentation.template.html, projects/demo/src/modules/components/editor/editor.template.html, projects/demo/src/modules/components/primitive-textfield/primitive-textfield.module.ts, projects/demo/src/modules/decorators/pure/pure.template.html, projects/demo/src/modules/directives/active-zone/active-zone.template.html, projects/demo/src/modules/directives/let/let.template.html, projects/demo/src/modules/directives/mode/mode.template.html, projects/demo/src/modules/directives/present/present.template.html, projects/demo/src/modules/directives/textfield-controller/examples/1/index.html, projects/demo/src/modules/directives/textfield-controller/examples/import/insert-template.txt, projects/demo/src/modules/directives/textfield-controller/textfield-controller.component.ts, projects/demo/src/modules/directives/textfield-controller/textfield-controller.module.ts, projects/demo/src/modules/directives/textfield-controller/textfield-controller.template.html, projects/demo/src/modules/directives/validator/validator.template.html, projects/demo/src/modules/services/destroy/destroy.template.html, projects/demo/src/modules/utils/dom/dom.template.html, projects/demo/src/modules/utils/miscellaneous/miscellaneous.template.html
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> docs(demo): write API-docs about textfield-controller

projects/addon-charts/components/bar-chart/bar-chart.component.ts, projects/addon-charts/components/bar-chart/bar-chart.module.ts, projects/addon-charts/components/bar-chart/bar-chart.template.html, projects/addon-charts/components/bar-chart/test/bar-chart.component.spec.ts, projects/demo/src/modules/charts/bar-chart/bar-chart.component.ts, projects/demo/src/modules/charts/bar-chart/bar-chart.module.ts, projects/demo/src/modules/charts/bar-chart/bar-chart.template.html, projects/demo/src/modules/charts/bar-chart/examples/2/index.html, projects/demo/src/modules/charts/bar-chart/examples/2/index.less, projects/demo/src/modules/charts/bar-chart/examples/2/index.ts
-   [x] Bugfix
height not summed when collapsed=true
Closes #
height is summed when collapsed=true
-   [ ] Yes
-   [x] No
=> fix(addon-charts): fix bar-chart height in collapsed mode

projects/demo/src/locale/messages.xlf, projects/demo/src/modules/components/calendar/examples/1/index.html, projects/demo/src/modules/components/calendar/examples/2/index.html, projects/demo/src/modules/components/calendar/examples/3/index.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(docs): fix types

projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/directives/described-by/described-by.component.ts, projects/demo/src/modules/directives/described-by/described-by.module.ts, projects/demo/src/modules/directives/described-by/described-by.template.html, projects/demo/src/modules/directives/described-by/examples/1/index.html, projects/demo/src/modules/directives/described-by/examples/1/index.ts, projects/demo/src/modules/directives/described-by/examples/import/import-module.txt, projects/demo/src/modules/directives/described-by/examples/import/insert-template.txt
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(demo): write doc about described-by directives

projects/core/modules/notifications/notification-alert/Notification-alert.ts, projects/core/modules/notifications/notification-alert/notification-alert.component.ts, projects/core/modules/notifications/notification-alert/test/notification-alert.component.spec.ts, projects/core/modules/notifications/notification-options.ts, projects/demo/src/modules/services/notifications/notifications.component.ts, projects/demo/src/modules/services/notifications/notifications.template.html
-   [ ] Bugfix
Closes #253 
-   [ ] Yes
-   [ ] No
=> feat(core): make the autoClose timeout of TuiNotificationsService configurable 

projects/demo/src/modules/components/range/range.component.ts, projects/demo/src/modules/components/range/range.template.html, projects/demo/src/modules/components/slider/slider.component.ts, projects/demo/src/modules/components/slider/slider.template.html, projects/kit/abstract/slider/slider.ts, projects/kit/components/range/range.component.ts, projects/kit/components/range/test/range.component.spec.ts, projects/kit/components/slider/slider.component.ts, projects/kit/components/slider/test/slider.component.spec.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> feat(kit): add quantum property to slider

projects/demo/src/modules/decorators/pure/pure-function.component.ts, projects/demo/src/modules/decorators/pure/pure-getter.component.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> Fix `Pure` pipe example and Fibonacci number calculation

projects/kit/components/text-area/text-area.style.less
-   [x] Bugfix
Closes #443 
-   [ ] Yes
-   [x] No
=> fix(kit): multiline placeholder in textArea

projects/core/components/tooltip/tooltip.component.ts
-   [ ] Bugfix
Closes #442 
-   [ ] Yes
-   [x] No
=> feat(cdk, kit): do not focus input when clicking on hint on mobile

projects/addon-charts/components/line-chart/line-chart-hint.directive.ts, projects/addon-charts/components/line-days-chart/line-days-chart-hint.directive.ts, projects/cdk/directives/auto-focus/autofocus.directive.ts, projects/cdk/services/obscured.service.ts, projects/cdk/services/resize.service.ts, projects/core/components/dropdown-box/dropdown-box.component.ts, projects/core/components/scroll-controls/scroll-controls.component.ts, projects/core/components/scroll-controls/scrollbar.directive.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> refactor(all): switch intervals to throttled ANIMATION_FRAME to make polling configurable

CHANGELOG.md, projects/core/components/data-list/option/option.style.less, projects/core/components/primitive-checkbox/primitive-checkbox.style.less, projects/demo/src/modules/components/data-list/examples/4/custom-list/custom-list.template.html, projects/demo/src/modules/components/input-date-range/input-date-range.component.ts, projects/demo/src/modules/components/input-date-range/input-date-range.template.html, projects/kit/components/multi-select-option/multi-select-option.style.less, projects/kit/components/select-option/select-option.style.less
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): `Select`, `ComboBox`, `MultiSelect` cut overflown items with ellipsis

projects/demo/src/modules/components/tabs/tabs.template.html, projects/kit/components/tabs/tab/tab.providers.ts, projects/kit/components/tabs/tabs/tabs.component.ts
-   [x] Bugfix
doesn't update active router link tab index when tabs change
Closes #431 
update activatedRouterLink active index
-   [ ] Yes
-   [x] No
=> [BUGFIX] update active tab index

projects/demo/src/modules/app/stackblitz/project-files/src/app/app.module.ts.txt, projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> chore(demo): exact version of the polymorpheus package for stackblitz

.github/workflows/deploy.yml
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore(ci): deploy demo only on releases

projects/demo/src/modules/components/text-area/text-area.component.ts, projects/demo/src/modules/components/text-area/text-area.template.html, projects/kit/components/input-time/input-time.template.html, projects/kit/components/text-area/index.ts, projects/kit/components/text-area/text-area.component.ts, projects/kit/components/text-area/text-area.providers.ts, projects/kit/components/text-area/text-area.style.less
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): `TextArea` properly react to night mode

projects/addon-charts/components/bar-set/test/bar-set.component.spec.ts, projects/kit/components/input-password/input-password-options.ts, projects/kit/components/tabs/tabs/tabs.component.ts, projects/kit/components/text-area/text-area.providers.ts, projects/kit/directives/lazy-loading/lazy-loading.directive.ts, scripts/check-dist.js
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): `LazyLoading` clear background after load event

projects/kit/components/tabs/tab/tab.providers.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): `Tabs` fix provider issue for standalone tab

.github/workflows/deploy.yml, projects/demo/src/modules/components/combo-box/combo-box.component.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore(ci, demo): add example and  manual trigger

projects/demo/src/modules/components/input/examples/8/index.ts, projects/kit/components/combo-box/combo-box.component.ts, projects/kit/components/input/input.component.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(kit): scroll to the end of the input on select option

projects/core/components/data-list/data-list-dropdown-manager.directive.ts
-   [x] Bugfix
Closes #421 
-   [ ] Yes
-   [x] No
=> fix(core): fix animation retrigger in submenu

projects/demo/src/modules/pipes/filter-by-input/examples/2/index.html, projects/demo/src/modules/pipes/filter-by-input/examples/2/index.ts, projects/demo/src/modules/pipes/filter-by-input/examples/3/index.html, projects/demo/src/modules/pipes/filter-by-input/examples/3/index.ts, projects/demo/src/modules/pipes/filter-by-input/filter-by-input.component.ts, projects/demo/src/modules/pipes/filter-by-input/filter-by-input.module.ts, projects/demo/src/modules/pipes/filter-by-input/filter-by-input.template.html, projects/kit/pipes/filter-by-input/filter-by-input-with.pipe.ts, projects/kit/pipes/filter-by-input/filter-by-input.base.ts, projects/kit/pipes/filter-by-input/filter-by-input.module.ts, projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts, projects/kit/pipes/filter-by-input/index.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> feat(kit): `filterByInputWith` add new pipe to filter with custom stringify

CHANGELOG.md, package-lock.json, package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-editor/package.json, projects/addon-mobile/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/cdk/package.json, projects/core/constants/version.ts, projects/core/package.json, projects/i18n/package.json, projects/icons/package.json, projects/kit/package.json, projects/kit/pipes/filter-by-input/filter-by-input-with.pipe.ts, projects/kit/pipes/filter-by-input/filter-by-input.base.ts, projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts, projects/ng-add/package.json, projects/testing/package.json
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore(release): 2.11.2

projects/core/components/link/link.component.ts, projects/core/components/link/link.style.less
-   [x] Bugfix
Closes #500 
-   [ ] Yes
-   [x] No
=> fix(core): fix tuiLink mode

projects/cdk/abstract/dialog.service.ts, projects/cdk/components/dialog-host/dialog-host.component.ts, projects/cdk/interfaces/aria-dialog-context.ts
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(cdk): `TuiDialogHostComponent` opening many different types dialogs together

projects/core/components/primitive-checkbox/primitive-checkbox.component.ts
-   [x] Bugfix
Closes #498 
-   [ ] Yes
-   [x] No
=> fix(core): fix checkbox transition from indeterminate to false state

projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/editor/editor.module.ts, projects/demo/src/modules/components/editor/editor.template.html, projects/demo/src/modules/components/svg/svg.module.ts, projects/demo/src/modules/components/svg/svg.template.html, projects/demo/src/modules/customization/icon-set/examples/sanitizer/sanitizer.txt, projects/demo/src/modules/customization/icon-set/icon-set.component.ts, projects/demo/src/modules/customization/icon-set/icon-set.template.html, projects/demo/src/modules/markup/icons/icons.template.html
-   [ ] Bugfix
Closes #454 
-   [ ] Yes
-   [x] No
=> chore(demo): add sanitizer info to icons page

projects/addon-doc/src/components/navigation/navigation.component.ts, projects/addon-doc/src/components/navigation/navigation.template.html
-   [ ] Bugfix
Closes #189 
https://user-images.githubusercontent.com/28801957/109461210-e1516380-7a72-11eb-9867-577c7270218f.mov
https://user-images.githubusercontent.com/28801957/109461235-eadacb80-7a72-11eb-93b8-7058969b5275.mov
-   [ ] Yes
-   [x] No
=> feat(addon-doc): sync navigation panel link with opened page

projects/kit/components/calendar-range/calendar-range.component.ts, projects/kit/components/input-date-range/input-date-range.template.html
-   [ ] Bugfix
Closes #483
-   [ ] Yes
-   [ ] No
=> feat(kit): `CalendarRange` add `value` input and output

projects/addon-doc/src/components/navigation/navigation.component.ts, projects/addon-doc/src/components/navigation/navigation.module.ts, projects/addon-doc/src/components/navigation/navigation.style.less, projects/addon-doc/src/components/navigation/navigation.template.html, projects/addon-doc/src/directives/scroll-into-view/scroll-into-view.directive.ts, projects/addon-doc/src/directives/scroll-into-view/scroll-into-view.module.ts, projects/addon-doc/src/public-api.ts, projects/core/components/link/link.component.ts, projects/kit/components/input-phone/input-phone.component.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> refactor(demo): refactor navigation sync

projects/kit/components/multi-select/hide-selected.pipe.ts, projects/kit/pipes/filter-by-input/filter-by-input-with.pipe.ts, projects/kit/pipes/filter-by-input/filter-by-input.base.ts, projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts, projects/kit/utils/miscellaneous/index.ts, projects/kit/utils/miscellaneous/is-flat.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> feat(kit): `FilterByInput` support `null` and 2D arrays

.github/workflows/build.yml, projects/core/pipes/calendar-sheet/utils.ts, projects/core/tokens/ordered-short-week-days.ts, projects/ng-add/package.json
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore(ci): return builds in PR

projects/i18n/enums/package.json, projects/i18n/interfaces/language.ts, projects/i18n/languages/dutch/core.ts, projects/i18n/languages/english/countries.ts, projects/i18n/languages/english/index.ts, projects/i18n/languages/french/core.ts, projects/i18n/languages/german/core.ts, projects/i18n/languages/russian/countries.ts, projects/i18n/languages/spanish/core.ts, projects/i18n/languages/turkish/core.ts, projects/i18n/languages/ukrainian/core.ts, projects/kit/components/input-phone-international/const/countries.ts, projects/kit/tokens/i18n.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore: fix build

projects/demo/src/modules/tables/table/examples/4/index.ts
Fix table demo - example 4. When hide table column and show again its order broken and column goes to last index.
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(demo): correct order after table column show/hide

projects/i18n/languages/russian/index.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore(build): fix it

projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore(demo): add dependencies for stackbliz

projects/demo/src/modules/components/input-file/input-file.component.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> chore(demo): add accept attribute example

projects/kit/components/input-count/input-count.style.less
-   [x] Bugfix
Closes #530 
-   [ ] Yes
-   [x] No
Button sizes used to be overwritten by button component styles
=> fix(kit): fix input-count buttons size

projects/core/styles/theme/variables.less, projects/demo/src/modules/markup/typography/typography.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(core): change the typography of headings

projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts, projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less, projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(addon-commerce): prevent scrolling in input-card-grouped

projects/cdk/observables/zone-free.ts, projects/demo/src/modules/directives/dropdown/examples/3/index.ts, projects/kit/components/checkbox-labeled/checkbox-labeled.style.less, projects/kit/components/radio-labeled/radio-labeled.style.less, projects/kit/directives/lazy-loading/lazy-loading.directive.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): `CheckboxLabeled`, `RadioLabeled` fix night theme color

projects/core/mask/text-mask-options.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(core): interface `TuiTextMaskOptions` update js-doc links

projects/core/utils/format/format-phone.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-phone-international/input-phone-international.module.ts, projects/kit/components/input-phone-international/input-phone-international.template.html, projects/kit/components/input-phone-international/test/international-input-phone.component.spec.ts, projects/kit/utils/files/format-size.ts, projects/kit/utils/files/test/format-size.spec.ts
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> feat(kit): `InputPhoneInternational` autoselect country code on paste

projects/demo/src/modules/components/combo-box/combo-box.component.ts, projects/demo/src/modules/components/combo-box/combo-box.module.ts, projects/demo/src/modules/components/combo-box/combo-box.template.html, projects/demo/src/modules/components/combo-box/examples/4/index.html, projects/demo/src/modules/components/combo-box/examples/4/index.ts, projects/kit/pipes/filter-by-input/filter-by-input.base.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): `FilterByInput` disable filtering on strict match

projects/addon-doc/schematics/schematics-particles/add-field-doc-page.ts, projects/demo/src/modules/components/input/examples/4/template.html
-   [ ] Bugfix
-   [X] Refactoring (no functional changes, no api changes)
Fix some minor typos that I found :)
-   [ ] Yes
-   [X] No
=> fix(core): fix some typos

README.md
-   [ ] Bugfix
Misspelled library name in README.md
-
-   [ ] Yes
-   [x] No
=> docs: correct typo in README.md

projects/kit/components/breadcrumbs/breadcrumbs-wrapper.template.html
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [ x] No
=> fix(kit): async breadcrumbs update 

projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts, projects/cdk/directives/auto-focus/autofocus.directive.ts, projects/cdk/directives/focus-trap/focus-trap.directive.ts, projects/cdk/directives/overscroll/overscroll.directive.ts, projects/cdk/utils/dom/get-document-or-shadow-root.ts, projects/cdk/utils/dom/get-element-offset.ts, projects/cdk/utils/focus/blur-native-focused.ts, projects/cdk/utils/focus/get-closest-keyboard-focusable.ts, projects/cdk/utils/focus/is-native-keyboard-focusable.ts, projects/cdk/utils/miscellaneous/is-element-editable.ts, projects/core/components/data-list/data-list-dropdown-manager.directive.ts, projects/core/components/dialog/dialog.providers.ts, projects/core/components/hosted-dropdown/hosted-dropdown.component.ts, projects/kit/components/input-file/file/file.component.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/input-time/input-time.component.ts, projects/kit/directives/dropdown-selection/dropdown-selection.directive.ts, projects/kit/validators/unfinished.validator.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(cdk): fix dropdowns in ShadowDom inside iframe

projects/demo/src/modules/components/data-list/examples/2/index.html, projects/demo/src/modules/components/data-list/examples/2/index.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> feat(demo): `DataList` submenu example update (close dropdown)

projects/kit/components/input-date-time/input-date-time.component.ts, projects/kit/components/input-date-time/input-date-time.template.html, projects/kit/components/input-date-time/test/input-date-time.component.spec.ts
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(kit): `InputDateTime` fix case with losing not finished time chars on the first blur

projects/cdk/tokens/index.ts, projects/cdk/tokens/is-cypress.ts, projects/demo/src/modules/app/app.providers.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> feat(demo): disable animation if app is running under Cypress (via `TUI_ANIMATIONS_DURATION`)

projects/demo/src/modules/components/abstract/textfield-controller-documentation/textfield-controller-documentation.template.html, projects/demo/src/modules/components/input-tag/examples/3/index.html, projects/demo/src/modules/components/input-tag/input-tag.component.ts, projects/demo/src/modules/components/multi-select/examples/3/index.html, projects/demo/src/modules/components/multi-select/multi-select.component.ts, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/input-tag/input-tag.style.less, projects/kit/components/input-tag/input-tag.template.html, projects/kit/components/multi-select/multi-select.component.ts, projects/kit/components/multi-select/multi-select.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> feat(kit): `MultiSelect` + `InputTag` size `s`

projects/cdk/directives/media/media.directive.ts
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(cdk): `TuiMediaDirective` fix freezes in mobile safari

projects/kit/components/field-error/field-error.component.ts, projects/kit/components/field-error/field-error.module.ts, projects/kit/components/field-error/field-error.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(kit): `FieldError` fix change detection for OnPush nesting

projects/demo/src/modules/components/button/button.component.ts, projects/demo/src/modules/components/label/examples/3/index.ts, projects/demo/src/modules/components/label/label.component.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> feat(demo): `Button` and `Label` update docs

.github/workflows/demo-integrations.yml, projects/kit/enums/status.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore(ci): fix screenshot workflow

projects/demo/src/modules/components/input-phone-international/examples/1/index.html, projects/demo/src/modules/components/input-phone-international/examples/2/index.html, projects/demo/src/modules/components/input-phone-international/input-phone-international.template.html, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-phone-international/input-phone-international.module.ts, projects/kit/components/input-phone-international/input-phone-international.template.html, projects/kit/components/input-phone-international/test/international-input-phone.component.spec.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> feat(kit): `InputPhoneInternational` add countryIsoCode output

projects/demo/src/modules/app/home/home.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> chore(demo): update getting-started page

angular.json, projects/cdk/tokens/active-element.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(cdk): `ActiveZone` fix for shadow DOM

projects/cdk/tokens/active-element.ts
-   [ ] Bugfix
Closes #594
-   [ ] Yes
-   [ ] No
=> fix(cdk): `ActiveZone` ignore focus loss due to disable

projects/demo/src/modules/markup/colors/colors.constants.ts
=> Fix grammar mistake, from 'hedings' to 'headings'

projects/cdk/tokens/removed-element.ts, projects/core/components/button/button.component.ts
-   [ ] Bugfix
Closes #457
-   [ ] Yes
-   [ ] No
=> fix(core): `Button` fix expression changed for `showLoader`

projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/kit/components/input-phone/input-phone.component.ts, projects/kit/components/input-phone/input-phone.template.html
-   [x] Bugfix
Closes #508
-   [ ] Yes
-   [x] No
=> fix(core): make input phone prefix cleanable #508

projects/kit/components/toggle/toggle.style.less
-   [x ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [x ] Bugfix
Closes #
-   [ ] Yes
-   [x ] No
=> fix(kit): tui-toggle loading position

projects/cdk/components/dialog-host/dialog-host.style.less
-   [x] Bugfix
Closes **UIKIT-5374**
-   [ ] Yes
-   [x] No
=> fix(cdk): `DialogHost` fix background color of overlay in dialogs

projects/core/components/theme-night/theme-night.style.less, projects/core/styles/mixins/mixins.less, projects/core/styles/mixins/textfield.less, projects/core/styles/theme/variables.less
-   [x] Bugfix
Closes #540 
-   [ ] Yes
-   [x] No
=> fix(core): `textfield` fix autofill colors in dark mode

projects/demo/src/modules/components/input-phone-international/examples/1/index.html, projects/demo/src/modules/components/input-phone-international/examples/2/index.html, projects/demo/src/modules/components/input-phone-international/input-phone-international.component.ts, projects/demo/src/modules/components/input-phone-international/input-phone-international.template.html, projects/kit/components/input-phone-international/input-phone-international.style.less, projects/kit/components/input-phone-international/input-phone-international.template.html
-   [ ] Bugfix
Closes #549 
-   [ ] Yes
-   [x] No
=> feat(kit): `InputPhoneInternational` add `labelOutside` support + `cursor:pointer`

projects/addon-commerce/components/input-card-grouped/input-card-grouped.providers.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(addon-commerce): `InputCardGroup` fix dynamic localization

projects/core/styles/markup/tui-form.less
-   [x] Bugfix
Additional classes for form header do not work on mobile devices
Closes #
-   [ ] Yes
-   [x] No
=> fix(core): fixed styles for form header

projects/core/components/scrollbar/scrollbar.component.ts
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(core): hide extra scrollbar on ios

projects/demo/src/modules/components/text-area/examples/4/index.html, projects/demo/src/modules/components/text-area/examples/4/index.less, projects/kit/components/text-area/text-area.style.less
-   [X] Bugfix
Closes #638 
-   [ ] Yes
-   [X] No
=> fix(kit): fix extra characters highlight in `TextArea` with hint

projects/kit/components/input-count/input-count.style.less
-   [X] Bugfix
Closes #555
-   [ ] Yes
-   [X] No
=> fix(kit): `InputCount` controllers (+/-) overlapping (#555)

projects/addon-table/components/table-pagination/table-pagination.component.ts, projects/addon-table/components/table-pagination/table-pagination.template.html
-   [X] Bugfix
Closes UIKIT-5453
-   [ ] Yes
-   [X] No
=> fix(addon-table): `TablePagination` fix attribute title === `undefined`

projects/taiga-schematics/schematics/ng-add/constants/versions.ts, projects/taiga-schematics/schematics/ng-add/index.ts, projects/taiga-schematics/schematics/ng-add/tests/ng-add.spec.ts
-   [x] Bugfix
Closes #637 
-   [ ] Yes
-   [x] No
=> fix(shematics): install `@types/dompurify` when "add sanitizer" option is selected

projects/i18n/languages/index.ts, projects/kit/components/input-date-time/input-date-time.component.ts, projects/kit/components/input-date-time/test/input-date-time.component.spec.ts
-   [X] Bugfix
Closes #645
-   [ ] Yes
-   [X] No
=> fix(kit): `InputDateTime` apply min/max time restrictions if date was changed via calendar

projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/core/components/primitive-textfield/primitive-textfield.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> chore(core): update tuiPrimitiveTextfield table view mode

projects/demo/src/modules/components/input-date-time/input-date-time.component.ts, projects/demo/src/modules/components/input-date-time/input-date-time.template.html, projects/kit/components/input-date-time/input-date-time.component.ts
-   [ ] Bugfix
Closes #646
-   [ ] Yes
-   [X] No
=> feat(demo): `InputDateTime` update docs about `defaultActiveYearMonth`

projects/core/pipes/pluralize/pluralize.module.ts, projects/core/pipes/pluralize/pluralize.pipe.ts, projects/core/utils/format/index.ts, projects/core/utils/format/pluralize-to-icu.ts, projects/demo/src/modules/components/input-range/input-range.component.ts, projects/demo/src/modules/components/input-range/input-range.template.html, projects/demo/src/modules/components/input-slider/input-slider.component.ts, projects/demo/src/modules/components/input-slider/input-slider.module.ts, projects/demo/src/modules/components/input-slider/input-slider.template.html, projects/demo/src/modules/components/range/range.component.ts, projects/demo/src/modules/components/range/range.module.ts, projects/demo/src/modules/components/range/range.template.html, projects/demo/src/modules/components/slider/slider.component.ts, projects/demo/src/modules/components/slider/slider.module.ts, projects/demo/src/modules/components/slider/slider.template.html, projects/demo/src/modules/pipes/pluralize/pluralize.module.ts, projects/demo/src/modules/pipes/pluralize/pluralize.template.html, projects/kit/abstract/input-slider.ts, projects/kit/abstract/slider/slider.common.style.less, projects/kit/abstract/slider/slider.common.template.html, projects/kit/abstract/slider/slider.ts, projects/kit/components/input-range/input-range.module.ts, projects/kit/components/input-range/input-range.template.html, projects/kit/components/input-slider/input-slider.module.ts, projects/kit/components/input-slider/input-slider.template.html, projects/kit/components/range/range.module.ts, projects/kit/components/slider/slider.module.ts, projects/kit/components/slider/test/slider.component.spec.ts
-   [ ] Bugfix
Closes #258
-   [ ] Yes
-   [x] No
=> feat(kit):  switch to angular `i18nPlural` pipe

projects/addon-doc/src/components/main/main.style.less, projects/addon-doc/src/components/main/main.template.html
-   [x] Bugfix
Closes #669
"Night mode" label cursor is now correctly set to `pointer`.
-   [ ] Yes
-   [x] No
=> fix(addon-doc): fix "Night mode" label cursor

projects/addon-doc/src/components/example/example.component.ts, projects/addon-doc/src/components/example/example.module.ts, projects/addon-doc/src/components/example/example.style.less, projects/addon-doc/src/components/example/example.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> feat(addon-doc): polymorpheusify `TuiDocExampleComponent`

projects/demo/src/modules/components/mobile-calendar/examples/import/import-module.txt, projects/demo/src/modules/components/mobile-calendar/mobile-calendar.template.html
-   [ ] Bugfix
-   [x] Other: docs update
The [docs](https://taiga-ui.dev/components/mobile-calendar) for `TuiMobileCalendar` are unclear about the requirements for the component to work, leading to a difficult setup experience if one has never used Taiga UI.
Closes #663.
With the changes proposed, the docs explicitly state to add `TuiDialogModule` in order for …
=> Better mobile calendar setup explanation

projects/addon-mobile/internal/primitive-calendar-mobile/primitive-calendar-mobile.component.ts, projects/addon-mobile/internal/primitive-calendar-mobile/primitive-calendar-mobile.template.html, projects/core/components/hints-host/hint-box/hint-box.component.ts, projects/core/components/hints-host/hints-host.template.html, projects/core/components/primitive-calendar/primitive-calendar.component.ts, projects/core/components/primitive-calendar/primitive-calendar.style.less, projects/core/components/primitive-calendar/primitive-calendar.template.html, projects/core/components/primitive-calendar/test/primitive-calendar.component.spec.ts, projects/core/pipes/calendar-sheet/calendar-sheet.pipe.ts, projects/i18n/tools/extract-i18n.ts, projects/kit/components/multi-select/multi-select.component.ts, projects/kit/components/multi-select/multi-select.template.html, projects/kit/components/tabs/tab/tab.component.ts
-   [ ] Bugfix
Closes #666
-   [ ] Yes
-   [ ] No
=> fix(kit): `MultiSelect` fix dropdown when wrapped in label

angular.json
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> chore(ci): fix taiga-schematics build

projects/addon-mobile/components/theme-android/theme-android.style.less, projects/addon-mobile/components/theme-ios/theme-ios.style.less
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(addon-mobile): fix user-select for contenteditable

projects/addon-commerce/components/input-card-grouped/input-card-grouped.providers.ts, projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less, projects/addon-doc/src/components/code/code.style.less, projects/addon-doc/src/components/demo/demo.style.less, projects/addon-doc/src/components/documentation/documentation.style.less, projects/addon-doc/src/components/example/example.style.less, projects/addon-doc/src/components/main/main.style.less, projects/addon-doc/src/components/page/page.style.less, projects/addon-doc/src/internal/header/header.style.less, projects/core/components/dialog/dialog.style.less, projects/core/constants/media.ts, projects/core/modules/notifications/notifications-host/notifications-host.style.less, projects/core/styles/markup/tui-container.less, projects/core/styles/markup/tui-form.less, projects/core/styles/markup/tui-group.less, projects/core/styles/markup/tui-mobile-only.less, projects/core/styles/markup/tui-row.less, projects/core/styles/variables/media.less, projects/core/styles/variables/media.scss, projects/demo/src/modules/app/app.style.less, projects/demo/src/modules/app/logo/logo.style.less, projects/demo/src/modules/components/checkbox-block/checkbox-block.template.html, projects/demo/src/modules/components/text-area/examples/4/index.less, projects/demo/src/modules/markup/grid/examples/1/index.html, projects/demo/src/modules/markup/grid/examples/1/index.less, projects/demo/src/modules/markup/grid/examples/2/index.html, projects/demo/src/modules/markup/grid/grid.template.html, projects/demo/src/modules/services/dialogs/examples/5/index.less
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> feat(core): update media breakpoints

projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/core/styles/mixins/mixins.less, projects/core/styles/mixins/textfield.less
-   [x] Bugfix
Closes #692
Border's autofill color will be the same
-   [ ] Yes
-   [x] No
=> fix(core): autofill border color

projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/core/components/primitive-textfield/primitive-textfield.template.html
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(core): fix primitive-texfield padding

projects/core/components/primitive-textfield/primitive-textfield.template.html, projects/demo/src/modules/components/combo-box/examples/2/index.ts, projects/demo/src/modules/components/input-card-grouped/examples/2/index.ts, projects/demo/src/modules/components/select/examples/2/index.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> fix(core): fix textfield right padding

.gitignore
What is an IML file?
An IML file is a module settings file created by IntelliJ IDEA, an Integrated Development Environment (IDE) used to develop Java applications. It stores information about a development module, which is a Java, Plugin, Android, or Maven component of a Java application. IML files store a module’s type, paths, dependencies, and other settings.
-   [ ] Bugfix
-   [ ] Refactoring (no functional changes, no …
=> chore: prevent added .iml files for git

projects/core/styles/mixins/mixins.less, projects/core/styles/mixins/mixins.scss, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/progress-bar/progress-bar.component.less, projects/demo/src/modules/components/progress-bar/progress-bar.module.ts, projects/demo/src/modules/components/progress-circle/examples/1/index.html, projects/demo/src/modules/components/progress-circle/examples/1/index.ts, projects/demo/src/modules/components/progress-circle/examples/2/index.html, projects/demo/src/modules/components/progress-circle/examples/2/index.less, projects/demo/src/modules/components/progress-circle/examples/2/index.ts, projects/demo/src/modules/components/progress-circle/examples/3/index.html, projects/demo/src/modules/components/progress-circle/examples/3/index.less, projects/demo/src/modules/components/progress-circle/examples/3/index.ts, projects/demo/src/modules/components/progress-circle/examples/4/index.html, projects/demo/src/modules/components/progress-circle/examples/4/index.less, projects/demo/src/modules/components/progress-circle/examples/4/index.ts, projects/demo/src/modules/components/progress-circle/examples/import/import-module.txt, projects/demo/src/modules/components/progress-circle/examples/import/insert-template.txt, projects/demo/src/modules/components/progress-circle/progress-circle.component.ts, projects/demo/src/modules/components/progress-circle/progress-circle.module.ts, projects/demo/src/modules/components/progress-circle/progress-circle.style.less, projects/demo/src/modules/components/progress-circle/progress-circle.template.html, projects/kit/components/progress/index.ts, projects/kit/components/progress/progress-circle/progress-circle.component.ts, projects/kit/components/progress/progress-circle/progress-circle.style.less, projects/kit/components/progress/progress-circle/progress-circle.template.html, projects/kit/components/progress/progress-label/progress-label.style.less, projects/kit/components/progress/progress-label/progress-label.template.html, projects/kit/components/progress/progress.module.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [X] No
=> feat(kit): new component `ProgressCircle`

.github/workflows/test.yml, package.json
-   [ ] Bugfix
Failed jobs
Try skip not available api  
-   [ ] Yes
-   [x] No
=> ci: skip coveralls when api not available

projects/core/styles/markup/tui-container.less
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> chore(core): change container box-sizing

projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/progress-circle/examples/2/index.html, projects/demo/src/modules/components/progress-circle/examples/4/index.html, projects/demo/src/modules/components/progress-segmented/examples/1/index.html, projects/demo/src/modules/components/progress-segmented/examples/1/index.less, projects/demo/src/modules/components/progress-segmented/examples/1/index.ts, projects/demo/src/modules/components/progress-segmented/examples/2/index.html, projects/demo/src/modules/components/progress-segmented/examples/2/index.less, projects/demo/src/modules/components/progress-segmented/examples/2/index.ts, projects/demo/src/modules/components/progress-segmented/examples/3/index.html, projects/demo/src/modules/components/progress-segmented/examples/3/index.less, projects/demo/src/modules/components/progress-segmented/examples/3/index.ts, projects/demo/src/modules/components/progress-segmented/examples/4/index.html, projects/demo/src/modules/components/progress-segmented/examples/4/index.less, projects/demo/src/modules/components/progress-segmented/examples/4/index.ts, projects/demo/src/modules/components/progress-segmented/examples/import/import-module.txt, projects/demo/src/modules/components/progress-segmented/examples/import/insert-template.txt, projects/demo/src/modules/components/progress-segmented/progress-segmented.component.ts, projects/demo/src/modules/components/progress-segmented/progress-segmented.module.ts, projects/demo/src/modules/components/progress-segmented/progress-segmented.style.less, projects/demo/src/modules/components/progress-segmented/progress-segmented.template.html, projects/kit/components/progress/index.ts, projects/kit/components/progress/progress-segmented/progress-segmented.component.ts, projects/kit/components/progress/progress-segmented/progress-segmented.style.less, projects/kit/components/progress/progress-segmented/progress-segmented.template.html, projects/kit/components/progress/progress.module.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [X] No
=> feat(kit): new component `ProgressSegmented`

projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/core/components/primitive-textfield/primitive-textfield.template.html, projects/demo/src/modules/components/select/examples/4/index.ts
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(core): fix primitive-texfield template

projects/demo/src/modules/components/progress-circle/examples/import/insert-template.txt, projects/demo/src/modules/components/progress-segmented/examples/import/insert-template.txt, projects/kit/components/progress/progress-label/progress-label.style.less, projects/kit/components/progress/progress-label/progress-label.template.html
-   [ ] Bugfix
-   [X] Refactoring (no functional changes, no api changes)
Closes #
-   [ ] Yes
-   [X] No
=> chore: `Progress` micro cosmetic changes

projects/kit/components/input-phone-international/input-phone-international.template.html
**Before:**
**After:**
-   [X] Bugfix
Closes #
-   [ ] Yes
-   [X] No
=> fix(kit): `InputPhoneInternational` correction of disabled state

projects/addon-mobile/components/mobile-calendar/tests/mobile-calendar.component.spec.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> chore(addon-mobile): fix test

.github/workflows/autoupdate.yml
-   [ ] Bugfix
Closes #726
Auto update branches
-   [ ] Yes
-   [x] No
=> ci: add auto-update job to pipelines

.github/workflows/autoupdate.yml
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> ci: set dry-run for auto-update job

.github/workflows/autoupdate.yml, .github/workflows/build.yml, .github/workflows/demo-integrations.yml, .github/workflows/lint.yml, .github/workflows/schematic-test.yml, .github/workflows/test.yml
-   [ ] Bugfix
-   [x] Other... Please describe: x
No reactions when bot pushed new changes
Trigger ci jobs
-   [ ] Yes
-   [x] No
=> ci: trigger jobs when pushed changes to branch

projects/addon-commerce/utils/is-card-length-valid.ts, projects/addon-commerce/utils/test/is-card-length-valid.spec.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> feat(addon-commerce): add length check

projects/demo-integrations/cypress/support/commands.ts, projects/demo-integrations/cypress/support/hide-header.util.ts, projects/demo-integrations/cypress/tests/core/calendars/calendars.spec.ts, projects/demo-integrations/cypress/tests/deep/deep.spec.ts, projects/demo-integrations/cypress/tests/demo/demo.spec.ts
-   [ ] Bugfix
-   [X] Cypress tests
-   [ ] Yes
-   [X] No
=> feat(demo-integrations): more deep cypress tests

projects/demo/src/modules/directives/dropdown/dropdown.template.html
-   [x] Bugfix
Closes #737
-   [ ] Yes
-   [x] No
=> fix(demo): fix link to hosted dropdown component

.github/workflows/autorebase.yml
-   [ ] Bugfix
Developers can add broken code to the main branch.
Closes #726
After merged to the main branch all targeted branches receive new changes.
-   [ ] Yes
-   [x] No
=> ci: add auto-rebase job

projects/demo/src/modules/components/input-copy/input-copy.template.html, projects/demo/src/modules/components/input-password/input-password.template.html
-   [ ] Bugfix
Closes #733 #720 
-   [ ] Yes
-   [x] No
=> chore(demo): add missed tuiTextfieldCleaner

projects/demo-integrations/cypress/tests/core/dropdown/dropdown.spec.ts, projects/demo-integrations/cypress/tests/core/hint/hint.spec.ts, projects/demo-integrations/cypress/tests/core/notifications-service/notifications-service.spec.ts, projects/demo-integrations/cypress/tests/kit/field-error/field-error.spec.ts
-   [ ] Bugfix
-   [X] Other... Please describe:
Closes #
-   [ ] Yes
-   [X] No
=> chore(demo-integrations): cypress tests from proprietary repo

projects/addon-doc/src/components/documentation/documentation.template.html, projects/demo-integrations/cypress/tests/deep/deep.spec.ts
-   [ ] Bugfix
-   [X] Other... Please describe:
-   [ ] Yes
-   [X] No
=> chore(addon-doc): `Documentation` add `automation-id` for property

.github/workflows/test.yml
-   [ ] Bugfix
```
core,kit,addon-charts,addon-commerce,addon-editor,addon-mobile,addon-table
```
```
cdk,i18n,core,taiga-schematics,kit,icons,addon-charts,addon-commerce,addon-mobile,addon-tablebars,addon-table,addon-editor,addon-doc,testing
```
-   [ ] Yes
-   [x] No
=> ci: expose all libraries for testing

projects/demo-integrations/cypress/support/go-to-demo-page.util.ts, projects/demo-integrations/cypress/support/stub-external-icons.util.ts, projects/demo-integrations/cypress/tests/addon-tablebars/table-bars-service/table-bars-service.spec.ts, projects/demo-integrations/cypress/tests/core/calendars/calendars.spec.ts, projects/demo-integrations/cypress/tests/core/dialogs/dialogs.spec.ts, projects/demo-integrations/cypress/tests/deep/deep.spec.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> chore(demo-integrations): `cypress` pictures stubs + wait fonts loading

projects/demo/src/modules/app/stackblitz/project-files/src/app/app.module.ts.txt
-   [X] Bugfix
Closes #753
-   [ ] Yes
-   [X] No
=> fix(demo): add `Progress`, `DropdownContext`, `Editor` modules to stackblitz starter

.github/workflows/autorebase.yml
-   [ ] Bugfix
This should actually was worked, but I will still consult with the developer.
Skip failed job
-   [ ] Yes
-   [x] No
=> ci: continue on error when auto-rebase job is failed

package.json
-   [ ] Bugfix
-   [X] Other... Please describe:
-   [ ] Yes
-   [X] No
=> ci: change order of cypress tests launches

projects/taiga-schematics/schematics/ng-add/constants/versions.ts
-   [ ] Bugfix
Closes #768 
Packages will be installed with ^
-   [ ] Yes
-   [x] No
=> feat(schematics): make all packages upgradable

projects/demo-integrations/cypress/support/commands.ts, projects/demo-integrations/cypress/tests/core/dialogs/dialog-browser-back.spec.ts
-   [ ] Bugfix
-   [X] Other... fix tests on `main` branch
-   [ ] Yes
-   [X] No
=> fix(demo-integrations): fix dialogs tests

projects/core/directives/textfield-controller/textfield-autocomplete.directive.ts, projects/core/directives/textfield-controller/textfield.controller.ts
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> chore(core): change default autocomplete value

.github/workflows/test.yml
-   [ ] Bugfix
Now the coveralls job is waiting for the completion of parallel steps, you can skip this and immediately send the results
-   [ ] Yes
-   [x] No
=> ci: remove coveralls finish job

projects/kit/components/input-file/input-file.component.ts, projects/kit/components/input-file/test/input-file.component.spec.ts
-   [x] Bugfix
Closes #772 
-   [ ] Yes
-   [x] No
=> fix(kit): `InputFile`  trim whitespaces in accept list

.github/workflows/test.yml
-   [ ] Bugfix
-   [x] Other... Please describe: revert
=> revert "ci: remove coveralls finish job"

.github/ISSUE_TEMPLATE/3-docs-bug.yml
-   [ ] Bugfix
-   [x] Other... Please describe: docs
Users can only create a bug or feature, they do not have the ability to specify what type of bug or feature they would like
It will be convenient for users to fill out forms on the site
-   [ ] Yes
-   [x] No
=> ci: use issue forms for issue creation

projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/core/components/primitive-textfield/primitive-textfield.template.html
-   [x] Bugfix
Closes #755 
-   [ ] Yes
-   [x] No
=> fix(core): fix updating dynamic ng-content in `TuiPrimitiveTextfield`

.github/ISSUE_TEMPLATE/3-docs-bug.yml, .github/workflows/assign-project.yml
-   [ ] Bugfix
A new form with auto assign that issue to project
-   [ ] Yes
-   [x] No
=> ci: improved documentation workflow for project

.github/ISSUE_TEMPLATE/1-bug-report.yml, .github/ISSUE_TEMPLATE/2-feature-request.yml, .github/ISSUE_TEMPLATE/3-docs-bug.yml
-   [ ] Bugfix
-   [x] Other... Please describe: docs
=> docs: improved form issues

projects/core/components/scroll-controls/scroll-controls.style.less
-   [X] Bugfix
Closes #664
-   [ ] Yes
-   [X] No
=> fix(core): change min-height of `ScrollControls`'s bar to fix `TextArea`

.github/workflows/assign-project.yml, .github/workflows/autorebase.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/demo-integrations.yml, .github/workflows/deploy-next.yml, .github/workflows/deploy.yml, .github/workflows/firebase-hosting-pull-request.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/schematic-test.yml, .github/workflows/test.yml
-   [ ] Bugfix
-   [x] Other... Please describe: CI
if you push to branch several times, then on the CI unnecessary pipeline starts for each commit
Cancel an already running jobs 
https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idconcurrency
-   [ ] Yes
-   [x] No
=> ci: cancel an already running jobs

projects/core/components/primitive-calendar/primitive-calendar.style.less, projects/core/components/primitive-calendar/primitive-calendar.template.html, projects/core/components/primitive-calendar/test/primitive-calendar.component.spec.ts, projects/core/components/primitive-year-picker/primitive-year-picker.style.less, projects/core/components/primitive-year-picker/primitive-year-picker.template.html, projects/core/styles/mixins/picker.less, projects/core/styles/mixins/picker.scss, projects/demo-integrations/cypress/tests/addon-mobile/mobile-calendar/mobile-calendar.spec.ts, projects/demo/src/modules/components/mobile-calendar/examples/1/index.html, projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts, projects/kit/components/calendar-month/calendar-month.style.less, projects/kit/components/calendar-month/calendar-month.template.html
-   [x] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> fix(addon-mobile): fix mobile calendar style

projects/kit/components/input-date-range/input-date-range.component.ts
-   [x] Bugfix
Closes #616 
-   [ ] Yes
-   [x] No
=> fix(kit): fix filler appearing in `InputDateRange`

projects/icons/all.ts, projects/icons/src/tuiIconHeartFilled.svg, projects/icons/src/tuiIconHeartFilledLarge.svg, projects/icons/src/tuiIconStarFilled.svg, projects/icons/src/tuiIconStarFilledLarge.svg
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat(icons): add new filled icons

projects/demo/src/modules/components/marker-icon/examples/1/index.html, projects/demo/src/modules/components/marker-icon/examples/2/index.html, projects/demo/src/modules/components/marker-icon/examples/3/index.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> chore(demo): use common icon for markerIcon example

.github/workflows/assign-project.yml, .github/workflows/autorebase.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/demo-integrations.yml, .github/workflows/deploy-next.yml, .github/workflows/deploy.yml, .github/workflows/firebase-hosting-pull-request.yml, .github/workflows/lint.yml, .github/workflows/schematic-test.yml, .github/workflows/test.yml
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
=> ci: humanize job names

projects/core/abstract/abstract-hint.ts, projects/core/components/hints-host/hints-host.module.ts, projects/core/components/hints-host/hints-host.template.html, projects/core/directives/hint/hint.directive.ts, projects/core/directives/manual-hint/manual-hint.directive.ts, projects/core/directives/pointer-hint/pointer-hint.directive.ts
-   [ ] Bugfix
Closes # 
-   [ ] Yes
-   [ ] No
=> fix(core): make hint part of current active zone

projects/cdk/directives/index.ts, projects/cdk/directives/zoom/index.ts, projects/cdk/directives/zoom/package.json, projects/cdk/directives/zoom/test/zoom.directive.spec.ts, projects/cdk/directives/zoom/zoom.directive.ts, projects/cdk/directives/zoom/zoom.module.ts, projects/cdk/interfaces/index.ts, projects/cdk/interfaces/zoom.ts, projects/cdk/services/index.ts, projects/cdk/services/zoom.service.ts, projects/cdk/tokens/index.ts, projects/cdk/tokens/zoom-options.ts, projects/cdk/utils/miscellaneous/distance-between-touches.ts, projects/cdk/utils/miscellaneous/index.ts, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/svg/examples/1/index.html, projects/demo/src/modules/directives/pan/examples/1/index.ts, projects/demo/src/modules/directives/zoom/examples/1/index.html, projects/demo/src/modules/directives/zoom/examples/1/index.less, projects/demo/src/modules/directives/zoom/examples/1/index.ts, projects/demo/src/modules/directives/zoom/examples/import/component.txt, projects/demo/src/modules/directives/zoom/examples/import/import-module.txt, projects/demo/src/modules/directives/zoom/examples/import/insert-template.txt, projects/demo/src/modules/directives/zoom/zoom.component.ts, projects/demo/src/modules/directives/zoom/zoom.module.ts, projects/demo/src/modules/directives/zoom/zoom.style.less, projects/demo/src/modules/directives/zoom/zoom.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [x] No
=> feat(cdk): add `TuiZoom` directive

projects/addon-mobile/components/mobile-calendar/mobile-calendar.style.less, projects/addon-mobile/internal/primitive-calendar-mobile/primitive-calendar-mobile.style.less, projects/core/styles/mixins/mixins.less
-   [ ] Bugfix
Closes #958
-   [ ] Yes
-   [X] No
=> feat(addon-mobile): `MobileCalendar` add dark mode support

projects/demo/src/modules/app/utils/example-content-processor/typescript-processor.ts
-   [X] Bugfix
-   [ ] Yes
-   [X] No
=> chore(demo): `stackblitz` remove unnecessary `ChangeDetectionStrategy` import

projects/addon-doc/src/components/navigation/navigation.style.less, projects/addon-editor/components/editor-new/editor-new.style.less, projects/addon-editor/components/editor/editor.style.less, projects/addon-editor/components/toolbar-tools/table-size-selector/table-size-selector.style.less, projects/addon-mobile/components/mobile-calendar/mobile-calendar.style.less, projects/core/components/data-list/option/option.style.less, projects/core/components/dialog/dialog.style.less, projects/core/components/link/link.style.less, projects/core/styles/basic/main.less, projects/core/styles/markup/tui-autofill.less, projects/core/styles/mixins/mixins.less, projects/core/styles/theme/wrapper/table.less, projects/kit/components/input-range/input-range.style.less, projects/kit/components/input-slider/input-slider.style.less
-   [ ] Bugfix
compatibility with
```
"meowtec/no-px": [
true,
{
"ignore": [
"-5px",
"-4px",
"-3px",
"-2px",
"-1px",
"0px",
"1px",
"2px",
"3px",
"4px",
"5px"
]
}
]
```
-   [ ] Yes
-   [x] No
=> refactor: compat with stylelint rules

projects/demo/src/modules/markup/typography/typography.template.html
-   [ ] Bugfix
-   [x] Documentation content changes
Closes # 
-   [ ] Yes
-   [x] No
=> chore(demo): add vars on typography page

projects/core/components/hosted-dropdown/hosted-dropdown.component.ts, projects/core/components/hosted-dropdown/test/hosted-dropdown.component.spec.ts
-   [x] Bugfix
Closes #622  
-   [ ] Yes
-   [x] No
=> fix(core): fix event propagation on esc

projects/demo-integrations/cypress/support/shared.entities.ts, projects/demo-integrations/cypress/tests/kit/multi-select/multi-select.spec.ts, projects/kit/components/multi-select/multi-select.component.ts, projects/kit/components/multi-select/multi-select.template.html, projects/kit/constants/icon-blank.ts, projects/kit/constants/index.ts
-   [X] Bugfix
-   [ ] Yes
-   [X] No
=> fix(kit): `MultiSelect` arrow icon overflow (by many tags)

projects/core/utils/mask/create-number-mask.ts, projects/demo/src/modules/components/input-number/examples/4/index.html, projects/demo/src/modules/components/input-number/examples/4/index.ts, projects/demo/src/modules/components/input-number/input-number.component.ts, projects/demo/src/modules/components/input-number/input-number.module.ts, projects/demo/src/modules/components/input-number/input-number.template.html, projects/kit/components/input-number/input-number.component.ts
-   [x] Bugfix
Closes #888  
-   [ ] Yes
-   [x] No
=> fix(kit): `TuiInputNumber` fix custom formatting

projects/demo/src/modules/components/pagination/pagination.component.ts, projects/demo/src/modules/components/pagination/pagination.template.html
-   [ ] Bugfix
-   [x] Documentation content changes
Closes # 
-   [ ] Yes
-   [x] No
=> chore(demo): add `activePadding` and `sidePadding` for tui-pagination

.github/workflows/test.yml, karma.config.js
-   [ ] Bugfix
-   [x] Build or CI related changes
=> ci: remove redundant logs for ng test

projects/addon-commerce/components/card/card.component.ts, projects/addon-commerce/components/card/card.style.less, projects/addon-commerce/components/card/card.template.html, projects/demo/src/modules/components/card/examples/2/index.less
-   [ ] Bugfix
Closes # 
-   [ ] Yes
-   [ ] No
=> chore: fix card style according to design

projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts, projects/cdk/abstract/control.ts, projects/cdk/abstract/interactive.ts, projects/cdk/utils/miscellaneous/fallback-value.ts
-   [ ] Bugfix
Closes # 
-   [ ] Yes
-   [x] No
=> refactor: replace `fallbackValue` with `??`

projects/addon-doc/src/components/documentation/documentation-property-connector.directive.ts, projects/addon-doc/src/components/documentation/documentation.component.ts, projects/addon-doc/src/components/documentation/documentation.module.ts, projects/addon-doc/src/components/documentation/documentation.style.less, projects/addon-doc/src/components/documentation/documentation.template.html, projects/demo/src/modules/components/calendar-range/calendar-range.template.html, projects/demo/src/modules/components/notification/notification.component.ts, projects/demo/src/modules/components/notification/notification.template.html
-   [ ] Bugfix
-   [x] Documentation content changes
Empty table cell.
Closes # 
Flashing notification when emitting an event.
-   [ ] Yes
-   [x] No
=> feat(addon-doc): output visualization

projects/addon-commerce/components/money/money.style.less, projects/addon-commerce/components/money/money.template.html, projects/addon-commerce/components/money/test/money.component.spec.ts
-   [ ] Bugfix
Need changes before upgrade to #988
-   [ ] Yes
-   [x] No
=> refactor(addon-commerce): use html whitespace sensitive for prettier

projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts, projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less, projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
-   [ ] Bugfix
Closes #995 
-   [ ] Yes
-   [ ] No
=> fix(addon-commerce): `InputCardGrouped` fix for long numbers and small screens

projects/kit/components/badge/badge.template.html, projects/kit/components/filter/test/filters.component.spec.ts
-   [ ] Bugfix
Need changes before upgrade to #988
-   [ ] Yes
-   [x] No
=> refactor(kit): use html whitespace sensitive for prettier

projects/demo/src/modules/components/progress-bar/examples/2/index.ts
-   [ ] Bugfix
https://github.com/TinkoffCreditSystems/taiga-ui/pull/821
Updated the screenshot for better see better how many sections with flowers there can be.
-   [ ] Yes
-   [x] No
=> refactor(demo): add more color gradations for e2e testing

projects/demo/src/modules/components/progress-bar/examples/2/index.html, projects/kit/components/progress/index.ts, projects/kit/components/progress/pipes/abstract-color-segments.ts, projects/kit/components/progress/pipes/progress-color-segments-async.pipe.ts, projects/kit/components/progress/pipes/progress-color-segments.pipe.ts, projects/kit/components/progress/progress.module.ts
-   [ ] Bugfix
https://github.com/TinkoffCreditSystems/taiga-ui/pull/821
Get offsetWidth correctly
-   [ ] Yes
-   [x] No
=> feat(kit): add TuiProgressColorSegmentsAsyncPipe

projects/core/constants/regexp.ts, projects/core/utils/mask/create-number-mask.ts, projects/kit/components/input-number/test/input-number.component.spec.ts
-   [X] Bugfix
https://github.com/TinkoffCreditSystems/taiga-ui/issues/984
fix bug
-   [] Yes
-   [X] No
=> fix: fix number mask bug with wrong position of thousand separator

projects/core/components/button/button-options.ts, projects/core/components/button/button.component.ts, projects/core/components/button/index.ts, projects/demo/src/modules/components/button/button.component.ts, projects/demo/src/modules/components/button/button.module.ts, projects/demo/src/modules/components/button/button.template.html, projects/demo/src/modules/components/button/examples/5/index.html, projects/demo/src/modules/components/button/examples/5/index.ts, projects/demo/src/modules/components/button/examples/import/define-options.txt
-   [ ] Bugfix
Closes #133 
-   [ ] Yes
-   [x] No
=> feat(core): allow configuration of default button options

projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
-   [x] Bugfix
Closes #1023
-   [ ] Yes
-   [x] No
=> fix(addon-commerce): fix problem with autofill card

projects/cdk/tokens/active-element.ts, projects/core/components/hosted-dropdown/hosted-dropdown.component.ts, projects/core/components/hosted-dropdown/hosted-dropdown.template.html
-   [ ] Bugfix
Closes # 
-   [ ] Yes
-   [ ] No
=> fix(cdk): `ActiveZone` fix for shadow DOM clicks

projects/demo/src/modules/app/app.component.ts, projects/demo/src/modules/app/app.style.less, projects/demo/src/modules/app/app.template.html, projects/demo/src/styles.less
-   [ ] Bugfix
Closes # 
-   [ ] Yes
-   [ ] No
=> chore: improve shadow dom on demo

.eslintrc.js, projects/kit/directives/dropdown-selection/dropdown-selection.directive.ts
-   [ ] Bugfix
-   [x] Build or CI related changes
-   [ ] Yes
-   [x] No
=> ci: support no-case-declarations

projects/demo-integrations/cypress/tests/addon-preview/addon-preview.spec.ts
-   [ ] Bugfix
Closes # 
-   [ ] Yes
-   [ ] No
=> chore(demo-integrations): remove broken test

projects/addon-table/components/table/th/th.style.less
-   [x] Bugfix
broken styles in safari
-   [ ] Yes
-   [x] No
=> fix(addon-table): fix arrow visibility in safari

projects/demo/src/modules/components/money/examples/5/index.html, projects/demo/src/modules/components/money/examples/5/index.ts, projects/demo/src/modules/components/money/money.component.ts, projects/demo/src/modules/components/money/money.module.ts, projects/demo/src/modules/components/money/money.template.html
-   [ ] Bugfix
Closes # 
-   [ ] Yes
-   [ ] No
=> chore(demo): `Money` add format example

projects/core/components/hints-host/hint-box/hint-box.component.ts
-   [ ] Bugfix
Closes #1054
-   [ ] Yes
-   [ ] No
=> fix(core): `Hint` fix positioning for small screens

projects/demo-integrations/cypress/support/exclusions.ts, projects/demo-integrations/cypress/support/wait-kit-dialog.ts, projects/demo-integrations/cypress/tests/addon-preview/addon-preview.spec.ts
-   [ ] Bugfix
Closes # 
-   [ ] Yes
-   [ ] No
=> chore(demo-integrations): fix flaky test

projects/addon-preview/components/preview-dialog/preview-dialog.component.ts, projects/addon-preview/components/preview/preview.component.ts, projects/demo/src/modules/components/preview/examples/1/index.html, projects/demo/src/modules/components/preview/examples/1/index.ts, projects/demo/src/modules/components/preview/preview.template.html
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix(addon-preview): close preview on esc event

package-lock.json, package.json
-   [x] Bugfix
https://github.com/prettier/prettier-vscode/issues/2259
Support vscode
-   [ ] Yes
-   [x] No
=> ci: support format by prettier in vscode

.github/workflows/auto-label-merge-conflicts.yml
-   [ ] Bugfix
-   [x] Build or CI related changes
-   [ ] Yes
-   [x] No
=> ci: add label when pr has conflicts

projects/addon-tablebars/components/table-bars-host/table-bars-host.component.ts, projects/addon-tablebars/components/table-bars-host/table-bars-host.style.less, projects/addon-tablebars/components/table-bars-host/table-bars-host.template.html, projects/demo/src/modules/services/table-bar/examples/1/index.ts, projects/icons/all.ts, projects/icons/src/tuiIconClose.svg
-   [ ] Bugfix
Closes #931 
-   [ ] Yes
-   [x] No
=> feat(addon-tablebars): add adaptive for `TableBars`

CHANGELOG.md, package-lock.json, package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-editor/package.json, projects/addon-mobile/package.json, projects/addon-preview/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/cdk/package.json, projects/core/constants/version.ts, projects/core/package.json, projects/i18n/package.json, projects/icons/package.json, projects/kit/package.json, projects/taiga-schematics/package.json, projects/testing/package.json
-   [ ] Bugfix
Closes # 
-   [ ] Yes
-   [ ] No
=> chore(release): 2.26.0

projects/core/styles/theme/wrapper/icon.less, projects/core/styles/theme/wrapper/outline.less, projects/core/styles/theme/wrapper/primary.less, projects/core/styles/theme/wrapper/secondary.less, projects/core/styles/theme/wrapper/whiteblock.less, projects/demo/src/modules/components/button/examples/2/index.html
-   [ ] Bugfix
Closes #1034
-   [ ] Yes
-   [ ] No
=> fix(core): `Button` add visual indication for clicks on mobile

.github/workflows/test.yml, karma.config.js, nx.json
-   [ ] Bugfix
-   [x] Build or CI related changes
-   [ ] Yes
-   [x] No
=> ci: show only errors and final result

projects/addon-mobile/components/sheet/components/sheet/sheet.component.ts, projects/addon-mobile/components/sheet/components/sheet/sheet.style.less, projects/addon-mobile/components/sheet/directives/sheet-close/sheet-close.directive.ts, projects/core/components/primitive-checkbox/primitive-checkbox.component.ts, projects/core/components/primitive-checkbox/primitive-checkbox.template.html
-   [ ] Bugfix
Closes #1013 #905
-   [ ] Yes
-   [ ] No
=> fix(addon-mobile): `Sheet` fix closeable and swipe down

projects/demo/src/modules/app/app.component.ts, projects/demo/src/modules/components/pdf-viewer/examples/1/index.html, projects/demo/src/modules/components/pdf-viewer/examples/1/index.ts, projects/demo/src/modules/components/pdf-viewer/pdf-viewer.module.ts, projects/kit/components/pdf-viewer/pdf-viewer.component.ts, projects/kit/components/pdf-viewer/pdf-viewer.service.ts, projects/kit/components/pdf-viewer/pdf-viewer.template.html
=> fix(kit): `PdfViewer` add `SafeResourceUrl` support

projects/demo/src/modules/components/accordion/accordion.component.ts, projects/demo/src/modules/components/accordion/accordion.module.ts, projects/demo/src/modules/components/accordion/accordion.template.html, projects/demo/src/modules/components/accordion/examples/4/index.html, projects/demo/src/modules/components/accordion/examples/4/index.less, projects/demo/src/modules/components/accordion/examples/4/index.ts, projects/kit/components/accordion/accordion-item/accordion-item-content.directive.ts, projects/kit/components/accordion/accordion-item/accordion-item-eager-content.directive.ts, projects/kit/components/accordion/accordion-item/accordion-item.component.ts, projects/kit/components/accordion/accordion-item/accordion-item.template.html, projects/kit/components/accordion/accordion.module.ts, projects/kit/components/accordion/index.ts
-   [ ] Bugfix
Closes [#816](https://github.com/TinkoffCreditSystems/taiga-ui/issues/816)
-   [ ] Yes
-   [X] No
=> feat(kit): add support for eager content for accordion-item

projects/kit/components/input-number/input-number.component.ts, projects/kit/components/input-number/test/input-number.component.spec.ts
-   [ ] Bugfix
Closes #824
-   [ ] Yes
-   [ ] No
=> fix(kit): `InputNumber` fix updating the value and limits at the same time

projects/kit/components/combo-box/combo-box.component.ts, projects/kit/components/combo-box/test/combo-box.component.spec.ts, projects/kit/components/input-date-range/input-date-range.component.ts, projects/kit/components/input-date-range/test/input-date-range.component.spec.ts, projects/kit/components/input-date-time/input-date-time.component.ts, projects/kit/components/input-date-time/test/input-date-time.component.spec.ts, projects/kit/components/input-date/input-date.component.ts, projects/kit/components/input-month-range/input-month-range.component.ts, projects/kit/components/input-month-range/test/input-month-range.component.spec.ts, projects/kit/components/input-month/input-month.component.ts
-   [x] Bugfix
Closes #621
dropdown doesn't open by clicking on the cleaner
dropdown opens by clicking on the cleaner
-   [ ] Yes
-   [x] No
=> fix(kit): `Combobox`  open dropdown on cleaner click

projects/addon-editor/extensions/image-editor/image-editor.component.ts
=> chore(addon-editor): `ImageEditor` fix case with the first drag of image

projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less, projects/kit/components/input-tag/input-tag.style.less, projects/kit/components/text-area/text-area.style.less
Closes #https://github.com/TinkoffCreditSystems/taiga-ui/issues/1096
=> fix(kit): cross browser support hiding placeholder

projects/addon-mobile/styles/tinkoff-ui-angular-mobile.less, projects/core/enums/appearance.ts, projects/core/styles/theme/variables.less, projects/core/styles/theme/wrapper.less, projects/core/styles/theme/wrapper/accent.less, projects/demo/src/modules/app/landing/landing.style.less, projects/demo/src/modules/app/landing/landing.template.html, projects/demo/src/modules/components/button/button.component.ts, projects/demo/src/modules/components/button/examples/2/index.html
There is no way to easily use the `accent` defined in figma and variables.
It is possible to easily use the "accent" defined in figma and variables. At least in the button and wrapper.
=> Accent appearance

projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/core/components/primitive-textfield/primitive-textfield.template.html, projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts, projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less
=> fix(core): fix expanding inputs based on content

projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less
=> fix(core): disable pointer events on value decorator

package-lock.json, package.json
=> ci: support parse html by eslint

projects/addon-editor/components/editor-new/editor-new.component.ts
```html
<tui-editor
new
class="editor"
[formControl]="control"
[tools]="builtInTools"
[exampleText]="'312312'"
></tui-editor>
```
=> fix(addon-editor): fix readonly inputs in `Editor[new]`

projects/icons/scripts/convert-all-compile-file-to-all-file.ts
=> fix(icons): prevent lead to memory leaks

projects/cdk/utils/miscellaneous/identity.ts, projects/core/components/svg/svg.component.ts, projects/core/components/svg/test/svg-src-proccessor.component.spec.ts, projects/core/tokens/index.ts, projects/core/tokens/svg-src-processor.ts
=> feat(core): add source processor for svg component

projects/demo/src/modules/components/field-error/examples/5/index.html, projects/demo/src/modules/components/field-error/examples/5/index.ts, projects/kit/components/field-error/field-error.component.ts, projects/kit/components/field-error/field-error.template.html, projects/kit/tokens/validation-errors.ts
=> feat(kit): `TUI_VALIDATION_ERRORS` add ability to work with Observable

projects/i18n/languages/italian/addon-preview.ts, projects/i18n/languages/italian/countries.ts
=> fix(i18n): fix italian translations for addon-preview, countries

projects/kit/components/multi-select/multi-select.template.html
=> fix(kit): fix pseudoHovered, pseudoFocused in multiselect

.eslintrc.js, projects/addon-doc/src/components/example/example-get-tabs.pipe.ts, projects/core/components/notification/notification.component.ts, projects/core/modules/notifications/notification-alert/notification-alert.component.ts, projects/core/modules/notifications/notification-alert/test/notification-alert.component.spec.ts, projects/core/modules/notifications/notifications.service.ts, projects/kit/components/input-count/input-count.component.ts, projects/kit/components/input-password/input-password.component.ts, projects/kit/components/progress/pipes/abstract-color-segments.ts, projects/kit/components/toggle/toggle.component.ts, projects/kit/pipes/stringify/stringify.pipe.ts
=> ci: support explicit-member-accessibility

projects/demo/src/modules/markup/icons/icons.component.ts
=> refactor(demo): support custom groups in icons page

projects/addon-mobile/directives/ripple/ripple.providers.ts, projects/cdk/tokens/index.ts, projects/cdk/tokens/touch-supported.ts
=> feat(cdk): `TUI_TOUCH_SUPPORTED` add new token

angular.json, projects/addon-charts/components/arc-chart/arc-chart.component.ts, projects/addon-charts/components/arc-chart/arc-chart.module.ts, projects/addon-charts/components/arc-chart/arc-chart.style.less, projects/addon-charts/components/arc-chart/arc-chart.template.html, projects/addon-charts/components/arc-chart/index.ts, projects/addon-charts/components/arc-chart/package.json, projects/addon-charts/components/index.ts, projects/addon-doc/src/components/main/main.style.less, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/charts/arc-chart/arc-chart.component.ts, projects/demo/src/modules/charts/arc-chart/arc-chart.module.ts, projects/demo/src/modules/charts/arc-chart/arc-chart.style.less, projects/demo/src/modules/charts/arc-chart/arc-chart.template.html, projects/demo/src/modules/charts/arc-chart/examples/1/index.html, projects/demo/src/modules/charts/arc-chart/examples/1/index.less, projects/demo/src/modules/charts/arc-chart/examples/1/index.ts, projects/demo/src/modules/charts/arc-chart/examples/2/index.html, projects/demo/src/modules/charts/arc-chart/examples/2/index.less, projects/demo/src/modules/charts/arc-chart/examples/2/index.ts, projects/demo/src/modules/charts/arc-chart/examples/import/import-module.txt, projects/demo/src/modules/charts/arc-chart/examples/import/insert-template.txt, projects/demo/src/modules/components/pdf-viewer/pdf-viewer.template.html, projects/demo/src/modules/customization/i18n/i18n.component.ts, projects/demo/src/modules/customization/i18n/i18n.template.html, projects/demo/src/typings.d.ts, projects/i18n/README.md
=> feat(addon-charts): `ArcChart` add new component

projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less, projects/addon-preview/components/preview/preview.style.less, projects/addon-tablebars/components/table-bars-host/table-bars-host.style.less, projects/core/components/dialog/dialog.style.less, projects/core/components/root/root.component.ts, projects/core/modules/notifications/notifications-host/notifications-host.style.less, projects/core/providers/index.ts, projects/core/providers/is-mobile-resolution.provider.ts, projects/core/tokens/index.ts, projects/core/tokens/is-mobile-resolution.ts
=> chore(core,kit): make components dependent on token instead of media 

.eslintrc.js, projects/addon-editor/components/editor/editor.component.ts, projects/addon-editor/components/toolbar-tools/table-row-column-manager/table-row-column-manager.component.ts, projects/addon-editor/extensions/tiptap-node-view/component-render.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.strategy.ts, projects/addon-tablebars/components/table-bars-host/table-bars-host.component.ts, projects/cdk/services/obscured.service.ts, projects/cdk/services/static-request.service.ts, projects/core/components/expand/expand.component.ts, projects/core/components/hosted-dropdown/hosted-dropdown.component.ts, projects/core/components/primitive-calendar/primitive-calendar.component.ts, projects/core/components/primitive-year-picker/primitive-year-picker.component.ts, projects/demo/src/modules/components/combo-box/combo-box.component.ts, projects/demo/src/modules/components/field-error/examples/4/index.ts, projects/demo/src/modules/components/multi-select/examples/4/index.ts, projects/demo/src/modules/components/scrollbar/examples/3/component.ts, projects/demo/src/modules/components/select/select.component.ts, projects/demo/src/modules/services/notifications/examples/3/index.ts, projects/demo/src/modules/services/notifications/examples/4/index.ts, projects/demo/src/modules/services/notifications/examples/5/index.ts, projects/demo/src/modules/services/table-bar/table-bar.component.ts, projects/kit/abstract/slider/slider.ts, projects/kit/components/checkbox-block/checkbox-block.component.ts, projects/kit/components/checkbox-labeled/checkbox-labeled.component.ts, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/directives/lazy-loading/lazy-loading.service.ts, projects/testing/src/utils/native-input.page-object.ts, tsconfig.eslint.json
=> ci: support @typescript-eslint/prefer-readonly

CHANGELOG.md, projects/addon-charts/components/pie-chart/index.ts, projects/addon-charts/components/pie-chart/pie-chart.component.ts, projects/addon-charts/components/pie-chart/pie-chart.directive.ts, projects/addon-charts/components/pie-chart/pie-chart.module.ts, projects/addon-charts/components/pie-chart/pie-chart.template.html, projects/cdk/utils/miscellaneous/ease-in-out-quad.ts, projects/demo/src/modules/charts/ring-chart/ring-chart.component.ts, projects/demo/src/modules/components/multi-select/multi-select.template.html
=> feat(addon-doc): `PieChart`/`RingChart` add animations

projects/taiga-schematics/schematics/ng-add/index.ts, projects/taiga-schematics/schematics/ng-add/schema.json, projects/taiga-schematics/schematics/ng-add/steps/add-taiga-styles.ts, projects/taiga-schematics/schematics/ng-add/tests/ng-add.spec.ts
=> chore(taiga-schematics): ng add improvements

projects/core/components/link/link.style.less, projects/core/components/svg/svg.component.ts, projects/core/utils/mask/create-auto-corrected-money-pipe.ts, projects/kit/abstract/input-slider.ts, projects/kit/components/input-number/input-number.component.ts
=> chore: small fixes

projects/kit/components/input-inline/input-inline.style.less, projects/kit/components/input-inline/input-inline.template.html
=> fix(kit): `InputInline` fix hiding first charcter in safari

projects/demo/src/modules/app/home/examples/addons.txt, projects/demo/src/modules/app/home/examples/main.txt
=> chore(demo): add addons description

projects/addon-charts/components/legend-item/legend-item.component.ts, projects/addon-charts/components/legend-item/legend-item.style.less, projects/addon-charts/components/legend-item/legend-item.template.html, projects/addon-charts/components/pie-chart/pie-chart.component.ts, projects/addon-charts/components/pie-chart/pie-chart.style.less, projects/addon-charts/components/pie-chart/pie-chart.template.html, projects/addon-charts/components/ring-chart/ring-chart.component.ts, projects/addon-charts/components/ring-chart/ring-chart.template.html, projects/addon-charts/utils/describe-sector.ts, projects/demo/src/modules/charts/legend-item/examples/1/index.html, projects/demo/src/modules/charts/legend-item/examples/2/index.html, projects/demo/src/modules/charts/legend-item/examples/2/index.less, projects/demo/src/modules/charts/legend-item/examples/2/index.ts, projects/demo/src/modules/charts/legend-item/legend-item.component.ts, projects/demo/src/modules/charts/legend-item/legend-item.module.ts, projects/demo/src/modules/charts/legend-item/legend-item.template.html, projects/demo/src/modules/charts/pie-chart/pie-chart.component.ts, projects/demo/src/modules/components/input-inline/examples/2/style.less
=> feat(addon-doc): `LegendItem` add checkbox support

.eslintrc.js, projects/addon-doc/src/components/documentation/documentation-property-connector.directive.ts, projects/demo/server.ts, projects/demo/src/main.browser.ts, projects/demo/src/modules/components/button/examples/1/index.ts, projects/demo/src/modules/components/dialog/examples/2/index.ts, projects/demo/src/modules/components/link/examples/3/index.ts, projects/demo/src/modules/components/pagination/examples/1/index.ts, projects/demo/src/modules/components/preview/examples/1/index.ts, projects/demo/src/modules/components/preview/examples/3/index.ts, projects/demo/src/modules/components/primitive-textfield/primitive-textfield.component.ts, projects/demo/src/modules/directives/dropdown-context/examples/3/index.ts, projects/demo/src/modules/directives/manual-hint/manual-hint.component.ts, projects/demo/src/modules/directives/swipe/examples/2/index.ts, projects/demo/src/modules/services/destroy/examples/1/component.ts, projects/demo/src/modules/tables/table/examples/4/index.ts, scripts/release.js
=> ci: restrict console.log/debug in production code

projects/addon-doc/src/components/navigation/navigation.style.less
-   [ ] Bugfix
Closes [#648](https://github.com/TinkoffCreditSystems/taiga-ui/issues/648)
-   [ ] Yes
-   [X] No
=> feat(addon-doc): truncate link content

projects/demo/src/modules/components/select/select.component.ts, projects/demo/src/modules/components/select/select.style.less, projects/demo/src/modules/components/select/select.template.html, projects/kit/components/select/select.style.less, projects/kit/components/select/select.template.html
=> fix(kit): overflow content in select

projects/cdk/date-time/date-separator.ts, projects/cdk/date-time/index.ts, projects/demo/src/modules/components/input-date/examples/4/index.html, projects/demo/src/modules/components/input-date/examples/4/index.less, projects/demo/src/modules/components/input-date/examples/4/index.ts, projects/demo/src/modules/components/input-date/input-date.component.ts, projects/demo/src/modules/components/input-date/input-date.module.ts, projects/demo/src/modules/components/input-date/input-date.template.html, projects/kit/components/input-date-time/input-date-time.component.ts, projects/kit/components/input-date/input-date.component.ts, projects/kit/components/input-date/test/input-date.component.spec.ts, projects/kit/constants/masks.ts, projects/kit/utils/mask/create-auto-corrected-date-pipe.ts, projects/kit/utils/mask/create-auto-corrected-date-time-pipe.ts, projects/kit/utils/mask/create-date-mask.ts, projects/kit/utils/mask/index.ts, projects/kit/utils/mask/test/create-date-mask.spec.ts
=> feat(kit): `InputDate` add full support of `TUI_DATE_FORMAT`

projects/cdk/services/destroy.service.ts
Closes https://github.com/Tinkoff/taiga-ui/pull/1025
=> feat(cdk): use ReplaySubject for TuiDestroyService

projects/demo/src/modules/components/input-date-time/examples/3/index.html, projects/demo/src/modules/components/input-date-time/examples/3/index.less, projects/demo/src/modules/components/input-date-time/examples/3/index.ts, projects/demo/src/modules/components/input-date-time/input-date-time.component.ts, projects/demo/src/modules/components/input-date-time/input-date-time.module.ts, projects/demo/src/modules/components/input-date-time/input-date-time.template.html, projects/kit/components/input-date-time/input-date-time.component.ts, projects/kit/components/input-date-time/test/input-date-time.component.spec.ts
It is a part of https://github.com/Tinkoff/taiga-ui/issues/954
=> feat(kit): `InputDateTime` add full support of `TUI_DATE_FORMAT`

angular.json
=> ci: workspace config file cannot be loaded

.eslintrc.js, tsconfig.eslint.json
=> ci: compatibility for proprietary git submodule

angular.json, projects/cdk/date-time/day-range.ts, projects/cdk/date-time/test/day-range.spec.ts, projects/cdk/date-time/test/day.spec.ts, projects/demo/src/modules/components/input-date-range/examples/3/index.html, projects/demo/src/modules/components/input-date-range/examples/3/index.ts, projects/demo/src/modules/components/input-date-range/input-date-range.component.ts, projects/demo/src/modules/components/input-date-range/input-date-range.module.ts, projects/demo/src/modules/components/input-date-range/input-date-range.template.html, projects/kit/components/input-date-range/input-date-range.component.ts, projects/kit/components/input-date-range/test/input-date-range.component.spec.ts, projects/kit/constants/masks.ts, projects/kit/utils/mask/create-auto-corrected-date-pipe.ts, projects/kit/utils/mask/create-auto-corrected-date-range-pipe.ts, projects/kit/utils/mask/create-date-range-mask.ts, projects/kit/utils/mask/index.ts, projects/kit/utils/mask/test/create-auto-corrected-date-range-pipe.spec.ts, projects/kit/utils/mask/test/create-date-range-mask.spec.ts
=> feat(kit): `InputDateRange` add full support of `TUI_DATE_FORMAT`

.eslintrc.js, projects/icons/scripts/rollup-svgo.ts
=> ci: support @typescript-eslint/no-inferrable-types

projects/demo/src/modules/components/accordion/accordion.component.ts
Closes #https://github.com/Tinkoff/taiga-ui/issues/1167
Shows TS file when TS tab is clicked on.
=> docs: fix accordion TS link to file

projects/demo/src/modules/components/combo-box/examples/1/index.html, projects/demo/src/modules/components/combo-box/examples/1/index.ts, projects/demo/src/modules/components/input-tag/examples/3/index.ts, projects/demo/src/modules/components/multi-select/examples/2/index.less, projects/demo/src/modules/components/multi-select/examples/3/index.html, projects/demo/src/modules/components/multi-select/examples/6/index.html, projects/kit/components/input-tag/input-tag.style.less
=> fix(kit): `InputTag` broken layout of `tuiTextfieldCleaner` (size = s, m)

projects/demo/src/modules/charts/line-days-chart/examples/1/index.html, projects/demo/src/modules/charts/line-days-chart/examples/1/index.ts, projects/demo/src/modules/charts/line-days-chart/examples/2/index.html, projects/demo/src/modules/charts/line-days-chart/examples/2/index.less, projects/demo/src/modules/charts/line-days-chart/examples/2/pipe.ts, projects/demo/src/modules/charts/line-days-chart/line-days-chart.component.ts, projects/demo/src/modules/charts/line-days-chart/line-days-chart.template.html
=> fix(demo): line days chart labels visibility

projects/addon-preview/components/preview-dialog/preview-dialog.service.ts, projects/addon-preview/components/preview/preview.module.ts, projects/demo/src/modules/app/app.browser.module.ts, projects/demo/src/modules/app/app.providers.ts, projects/demo/src/modules/components/preview/examples/import/component.txt, projects/demo/src/modules/components/preview/preview.template.html
=> fix(addon-preview): add providers to `TuiPreviewModule`

projects/cdk/components/dialog-host/dialog-host.style.less, projects/core/components/dialog/dialog.style.less, projects/core/styles/taiga-ui-theme.less, projects/core/styles/theme/dialog.less
=> fix(core): fix unnecessary scroll in fullsize dialogs on mobile

projects/demo/src/modules/markup/grid/examples/1/index.less
=> chore(demo): change grid preview

projects/addon-mobile/components/sheet/components/sheet/sheet.style.less, projects/demo/src/modules/components/data-list/data-list.component.ts, projects/demo/src/modules/components/data-list/data-list.template.html, projects/demo/src/modules/components/select/select.component.ts, projects/demo/src/modules/components/select/select.template.html, projects/demo/src/modules/components/tree/tree.component.ts, projects/demo/src/modules/components/tree/tree.template.html, projects/kit/components/tree/components/tree/tree.component.ts, projects/kit/components/tree/components/tree/tree.template.html, projects/kit/components/tree/tree.module.ts
=> fix(kit): `Tree` fix change detection in async children

projects/addon-editor/components/color-selector/color-edit/color-edit.style.less, projects/addon-editor/components/color-selector/color-selector.style.less, projects/addon-editor/components/color-selector/palette/palette.style.less, projects/demo-integrations/cypress/tests/addon-editor/color-picker.spec.ts, projects/demo/src/modules/components/color-picker/examples/2/index.html
=> fix(addon-editor): change width for the opacity block

projects/addon-doc/src/components/code/parse-code-block.ts, projects/addon-doc/src/components/code/test/try-parse-markdown.spec.ts
=> fix(addon-doc): extract only `fence` type content from markdown

projects/addon-commerce/enums/currency-code.ts
TuiCurrencyCode enum contains no description about the currencies.
TuiCurrencyCode enum now contains the description about currencies.
Maybe it's not nice that it's in Russian, and some info is redundant and should be cut.
Let's discuss in this PR.
=> feat(addon-commerce): provide descriptions for `TuiCurrencyCode`

CHANGELOG.md, package-lock.json, package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-editor/package.json, projects/addon-mobile/package.json, projects/addon-preview/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/cdk/package.json, projects/core/constants/version.ts, projects/core/package.json, projects/i18n/package.json, projects/icons/package.json, projects/kit/package.json, projects/taiga-schematics/package.json, projects/testing/package.json
=> chore(release): 2.30.0

projects/kit/components/calendar-month/calendar-month.component.ts, projects/kit/components/calendar-month/test/month.component.spec.ts
=> fix(kit): `CalendarMonth` fix incorrect state in range

projects/demo/src/modules/components/button/examples/import/define-options.txt
The demo example to provide `TUI_BUTTON_OPTIONS` uses `itemSize`, which does not exist in [`ButtonOptions`](https://github.com/Tinkoff/taiga-ui/blob/main/projects/core/components/button/button-options.ts#L5-L9).
The demo example to provide `TUI_BUTTON_OPTIONS` uses `size`.
=> fix(demo): fix TUI_BUTTON_OPTIONS example

projects/demo/src/modules/components/field-error/examples/import/import-module.txt
Cannot find name 'TuiContentModule'.
Remove 'TuiContentModule'.
=> chore(demo): remove TuiContentModule at FieldError docs

projects/kit/components/arrow/arrow.style.less, projects/kit/components/input-date-range/input-date-range.template.html, projects/kit/components/input-date-time/input-date-time.style.less, projects/kit/components/input-date-time/input-date-time.template.html, projects/kit/components/input-date/input-date.template.html
=> fix(kit): fix cursor pointer in `Combobox` and date-controls

projects/i18n/languages/index.ts
Italian language cannot be used.
Italian language can be used.
=> fix: add italian to i18n index

projects/addon-tablebars/components/table-bars-host/table-bars-host.template.html, projects/addon-tablebars/components/table-bars-host/test/table-bars-host.component.spec.ts
=> fix(addon-tablebars): fix light mode class

projects/demo-integrations/cypress/support/shared.entities.ts, projects/demo-integrations/cypress/tests/kit/select/select.spec.ts, projects/kit/components/arrow/arrow.style.less, projects/kit/components/combo-box/combo-box.style.less, projects/kit/components/combo-box/combo-box.template.html
=> chore(kit): fix select icon

projects/kit/directives/lazy-loading/test/lazy-loading.directive.spec.ts
Closes https://github.com/Tinkoff/taiga-ui/issues/776
When I turn off my internet this test fails. In this case tests are flaky and depend on network availability
=> fix: exclude network troubles when testing

.github/workflows/auto-author-assign.yml, .github/workflows/firebase-hosting-pull-request.yml, .github/workflows/label-approved-pull-request.yml, .github/workflows/lint.yml
=> ci: ignore credentials for dependabot

projects/addon-charts/components/line-days-chart/line-days-chart.component.ts
=> fix(addon-charts): fix axis hints

projects/demo/src/modules/components/input-range/input-range.component.ts, projects/demo/src/modules/components/input-slider/input-slider.component.ts, projects/demo/src/modules/components/slider/slider.component.ts, projects/kit/abstract/input-slider.ts, projects/kit/utils/miscellaneous/get-precision.ts, projects/kit/utils/miscellaneous/index.ts
=> fix(kit): `InputSlider` fix decimal limit

.eslintrc.js, projects/addon-table/components/table/providers/stuck.provider.ts, projects/core/providers/mode.provider.ts, projects/demo/src/hmr.ts, projects/demo/src/modules/components/field-error/examples/5/index.ts, projects/kit/components/carousel/carousel-scroll.directive.ts
=> ci: support no-return-assign

projects/core/styles/variables/media.less, projects/demo/src/modules/markup/grid/grid.template.html
=> chore(core): change min mobile width

projects/addon-commerce/enums/currency-code.ts, projects/addon-commerce/enums/currency.ts
Lack of description of currencies.
`TuiCurrency` now contains descriptions about contained currencies.
=> feat(addon-commerce): currency codes description

.eslintrc.js, projects/kit/components/filter/test/filters.component.spec.ts, projects/kit/components/input-date-range/test/input-date-range.component.spec.ts, projects/kit/components/input-date-time/test/input-date-time.component.spec.ts, projects/kit/components/input-date/test/input-date.component.spec.ts
=> ci: support no-implicit-coercion

projects/kit/components/input-number/input-number.component.ts, projects/kit/components/input-number/test/input-number.component.spec.ts
=> fix(kit): `InputNumber` fix max length

projects/addon-doc/src/components/demo/demo.component.ts, projects/addon-doc/src/components/documentation/documentation-property-connector.directive.ts, projects/addon-doc/src/public-api.ts, projects/addon-doc/src/utils/coerce-value.ts, projects/addon-doc/src/utils/test/coerce-value.spec.ts
Closes https://github.com/Tinkoff/taiga-ui/issues/1011
https://user-images.githubusercontent.com/12021443/150551892-22f32dd4-b8ef-46d1-b6f8-f0d487379599.mov
=> fix(addon-doc): support coercing value from query params

projects/kit/components/input-phone-international/const/countries.ts, projects/kit/components/input-phone-international/index.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-phone-international/tokens/countries-masks.ts, projects/kit/components/input-phone-international/utils/extract-value-from-event.ts
Closes https://github.com/Tinkoff/taiga-ui/issues/1226
Support override countries masks
=> feat(kit): add TUI_COUNTRIES_MASKS token

projects/addon-doc/src/components/code/code.style.less, projects/addon-doc/src/components/demo/demo.style.less, projects/addon-doc/src/components/documentation/documentation.style.less, projects/addon-doc/src/components/example/example.style.less, projects/addon-doc/src/components/main/main.style.less, projects/addon-doc/src/components/page/page.style.less, projects/demo/src/modules/app/app.style.less, projects/demo/src/modules/app/logo/logo.style.less, projects/demo/src/modules/components/carousel/examples/4/index.less, projects/demo/src/modules/components/dialog/examples/5/index.less, projects/demo/src/modules/components/text-area/examples/4/index.less, projects/demo/src/modules/markup/grid/examples/1/index.less
=> feat(addon-doc): use `host-context` instead of `@media @mobile-m`

projects/demo/src/modules/app/stackblitz/project-files/src/app/app.module.ts.txt
Closes #1237 
Stackblitz for Tree component examples now opens correctly.
=> fix(docs): import TuiTreeModule into the Stackblitz example

.github/workflows/build.yml, .npmrc, projects/icons/scripts/prepare-all-to-compile-file.ts, projects/icons/svg.d.ts, projects/icons/tsconfig.lib.json
=> fix(icons): cannot find svg module

projects/demo/src/modules/components/tag/examples/4/index.html, projects/demo/src/modules/components/tag/examples/4/index.less, projects/demo/src/modules/components/tag/examples/4/index.ts, projects/demo/src/modules/components/tag/tag.component.ts, projects/demo/src/modules/components/tag/tag.module.ts, projects/demo/src/modules/components/tag/tag.template.html
Closes #614 
Added new example to show how to organize removable tags.
=> feat(tag): added the example with editing and removing tags

projects/addon-commerce/components/money/money.style.less, projects/addon-commerce/components/money/money.template.html, projects/demo/src/modules/components/money/examples/4/index.html
=> fix(addon-commerce): remove empty space around currency

projects/demo/src/modules/app/logo/logo.module.ts, projects/demo/src/modules/app/logo/logo.style.less, projects/demo/src/modules/app/logo/logo.template.html
https://user-images.githubusercontent.com/12021443/151136439-2d2e234f-4401-4bf2-bb11-56994f495aaf.mov
=> chore(demo): improved UX for logo, navigate to home

projects/demo/src/modules/app/logo/logo.template.html
=> chore(demo): remove redundant square brackets

projects/core/components/link/link.style.less, projects/core/components/link/link.template.html
=> refactor(core): use `t-` prefix in template

projects/core/styles/mixins/textfield.less
https://user-images.githubusercontent.com/12021443/151166025-f7cb97e9-fa9b-4465-b3b6-4624fefc8129.mov
=> fix(core): don't use `font-size` animation for safari

projects/kit/components/arrow/arrow-options.ts, projects/kit/components/arrow/arrow.style.less, projects/kit/components/arrow/arrow.template.html, projects/kit/components/combo-box/combo-box.component.ts, projects/kit/components/multi-select/multi-select.component.ts, projects/kit/components/multi-select/multi-select.style.less, projects/kit/components/multi-select/multi-select.template.html, projects/kit/components/multi-select/test/custom-arrow-mode.component.spec.ts, projects/kit/components/multi-select/test/multi-select.component.spec.ts, projects/kit/components/multi-select/test/multi-select.helpers.ts, projects/kit/components/select/select.component.ts
=> feat(kit): add `TUI_ARROW_MODE` token

projects/core/utils/mask/create-number-mask.ts
Closes [#1273](https://github.com/Tinkoff/taiga-ui/issues/1273)
=> fix(core): fix decimal limit condition in tui-slider

.github/actions/nodejs/action.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/demo-integrations.yml, .github/workflows/deploy-next.yml, .github/workflows/deploy.yml, .github/workflows/firebase-hosting-pull-request.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml
=> ci: reuse github action for setup node.js

projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/core/components/primitive-textfield/primitive-textfield.template.html
=> fix(core): hide placeholder when use value from autocomplete

projects/addon-mobile/components/sheet/components/sheet/sheet.component.ts
=> iOS and Sheet

.github/ISSUE_TEMPLATE/1-bug-report.yml, .github/ISSUE_TEMPLATE/2-feature-request.yml, .github/ISSUE_TEMPLATE/3-docs-bug.yml, .github/ISSUE_TEMPLATE/4-dev-infra-request.yml
For new issues that are not prioritized
=> ci: add `state: need triage` for issues without priority label

projects/cdk/date-time/date-separator.ts, projects/cdk/date-time/test/date-separator.spec.ts
=> fix(kit): fix cyrillic filler in date-components

.eslintrc.js, package-lock.json, package.json
=> ci: eslint rule enforce-module-boundaries

projects/addon-doc/ng-package.json, projects/addon-doc/package.json
=> fix(addon-doc): use correct dependencies

projects/cdk/abstract/control.ts, projects/cdk/abstract/interactive.ts, projects/demo/src/modules/components/input-inline/examples/3/component.ts, projects/demo/src/modules/components/input-inline/examples/3/style.less, projects/demo/src/modules/components/input-inline/examples/3/template.html, projects/demo/src/modules/components/input-inline/input-inline.component.ts, projects/demo/src/modules/components/input-inline/input-inline.module.ts, projects/demo/src/modules/components/input-inline/input-inline.template.html, projects/kit/components/input-inline/input-inline.component.ts, projects/kit/components/input-inline/input-inline.style.less, projects/kit/components/input-inline/input-inline.template.html
Closes #1220
https://user-images.githubusercontent.com/12021443/151378473-5477c994-8081-4bc5-b3ef-24d0bc62efd6.mov
=> fix(kit): remove `HostBinding` in `input-inline`

projects/demo/src/modules/components/input-time/examples/3/index.ts, projects/demo/src/modules/components/input-time/examples/4/index.html, projects/demo/src/modules/components/input-time/examples/4/index.ts, projects/demo/src/modules/components/input-time/examples/5/index.html, projects/demo/src/modules/components/input-time/examples/5/index.ts, projects/demo/src/modules/components/input-time/input-time.component.ts, projects/demo/src/modules/components/input-time/input-time.module.ts, projects/demo/src/modules/components/input-time/input-time.template.html, projects/kit/components/input-time/input-time-options.ts, projects/kit/components/input-time/input-time.component.ts, projects/kit/components/input-time/input-time.template.html, projects/kit/constants/index.ts, projects/kit/constants/max-time-values.ts, projects/kit/types/index.ts, projects/kit/types/time-format-parts.ts, projects/kit/utils/mask/create-auto-corrected-time-pipe.ts, projects/kit/utils/mask/create-time-mask.ts, projects/kit/utils/mask/test/create-time-mask.spec.ts
Issue #270 is not fully implemented.
Issue #1229 is not fully implemented.
Partial implementation of #270.
Workaround implementation of #1229.
=> feat(kit): configurable maxValues for input-time

CHANGELOG.md, package-lock.json, package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-editor/package.json, projects/addon-mobile/package.json, projects/addon-preview/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/cdk/package.json, projects/core/constants/version.ts, projects/core/package.json, projects/i18n/package.json, projects/icons/package.json, projects/kit/package.json, projects/taiga-schematics/package.json, projects/testing/package.json, scripts/release.js
=> chore(release): 2.32.0

projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-phone-international/test/international-input-phone.component.spec.ts
=> fix(kit): `InputPhoneInternational` fix paste/drop without plus

projects/demo/src/modules/app/stackblitz/stackblitz-deps.constants.ts
stackblitz examples don't work
stackblitz examples work
=> chore: fix ng-web-apis/common version for stackblitz

projects/demo-integrations/cypress/support/commands.ts
=> ci: improved diff threshold for e2e

.eslintrc.js, .github/workflows/lint.yml, scripts/eslint/nx.js
=> ci: decomposition eslint config

package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-mobile/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/core/package.json, projects/kit/package.json
=> ci: use strict range of peerDependencies for yarn

.github/workflows/demo-integrations.yml
=> ci: rebase before compare snapshots

projects/demo/src/modules/components/input-phone-international/examples/1/index.html, projects/demo/src/modules/components/input-phone-international/examples/1/index.ts, projects/demo/src/modules/components/input-phone-international/input-phone-international.module.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-phone-international/test/international-input-phone.component.spec.ts
=> fix(kit): `InputPhoneInternational` fix wrong model update

projects/demo-integrations/cypress.json, projects/demo-integrations/cypress/support/commands.ts, projects/demo-integrations/cypress/support/go-to-demo-page.util.ts, projects/demo-integrations/cypress/support/shared.entities.ts, projects/demo-integrations/cypress/support/wait-requests.util.ts, projects/demo-integrations/cypress/tests/addon-editor/color-picker.spec.ts, projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts, projects/demo-integrations/cypress/tests/addon-editor/toolbar-new.spec.ts, projects/demo-integrations/cypress/tests/addon-mobile/mobile-calendar/mobile-calendar.spec.ts, projects/demo-integrations/cypress/tests/addon-preview/addon-preview.spec.ts, projects/demo-integrations/cypress/tests/addon-tablebars/table-bars-service/table-bars-service.spec.ts, projects/demo-integrations/cypress/tests/core/calendars/calendars.spec.ts, projects/demo-integrations/cypress/tests/core/dialogs/dialog-browser-back.spec.ts, projects/demo-integrations/cypress/tests/deep/deep.spec.ts, projects/demo-integrations/cypress/tests/demo/demo.spec.ts, projects/demo-integrations/cypress/tests/kit/dropdown-context/dropdown-context.spec.ts, projects/demo-integrations/cypress/tests/kit/multi-select/multi-select.spec.ts, projects/demo-integrations/cypress/tests/kit/select/select.spec.ts
=> ci: change default options for skip flaky tests

scripts/sync-versions.js
Versions synchronization will now refer to Taiga packages with the caret (`^`) instead of locked versions, which should ease the update process on npm 7+.
=> chore(script): fixed version synchronization

projects/addon-editor/extensions/background-color.ts, projects/addon-editor/extensions/font-color.ts, projects/addon-editor/extensions/indent-outdent.ts
Updated tiptap extensions to eliminate deprecatio warnings
Closes #1290
=> fix(addon-editor): updated extensions

.github/workflows/demo-integrations.yml
=> ci: correctly check e2e tests on fail

projects/addon-commerce/types/currency-variants.ts
=> feat(addon-commerce): add type inference for currency

projects/addon-mobile/components/sheet/components/sheet/sheet.style.less, projects/core/components/dialog/dialog.style.less, projects/core/components/dropdown-box/dropdown-box.style.less, projects/core/components/theme-night/theme-night.style.less, projects/core/styles/markup/tui-island.less, projects/core/styles/theme/variables.less
new css vars for background of elevated elements
=> feat(core): add elevation css vars

projects/core/components/tooltip/tooltip.style.less, projects/demo-integrations/cypress/tests/core/hint/hint.spec.ts, projects/demo/src/modules/components/tooltip/examples/1/index.html
=> fix(core): fix tooltip position

projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-editor/package.json, projects/addon-mobile/package.json, projects/addon-preview/package.json, projects/addon-table/package.json, projects/core/package.json, projects/kit/package.json, scripts/sync-versions.js
=> ci: correctly bump peer dependencies after release

package-lock.json, package.json, projects/core/package.json, projects/taiga-schematics/schematics/ng-add/tests/ng-add.spec.ts
=> fix(core): add `@taiga-ui/i18n` as dependency

package-lock.json, package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-editor/package.json, projects/addon-mobile/package.json, projects/cdk/package.json, projects/core/package.json, projects/kit/package.json
=> ci: could not resolve dependency for `@ng-web-apis/common`

projects/demo/src/modules/components/multi-select/examples/3/index.ts, projects/kit/components/input-tag/input-tag.template.html, projects/kit/components/tag/tag.component.ts
=> fix(kit): prevent redundant space in input-tag

projects/cdk/directives/active-zone/active-zone.directive.ts, projects/core/abstract/abstract-dropdown.ts, projects/core/directives/dropdown/dropdown.directive.ts, projects/core/directives/dropdown/test/dropdown.directive.spec.ts, projects/demo-integrations/cypress/plugins/index.js, projects/demo-integrations/cypress/tests/core/data-list/data-list.spec.ts, projects/demo/src/modules/components/data-list/data-list.component.ts, projects/demo/src/modules/components/data-list/data-list.module.ts, projects/demo/src/modules/components/data-list/data-list.template.html, projects/demo/src/modules/components/data-list/examples/5/index.html, projects/demo/src/modules/components/data-list/examples/5/index.less, projects/demo/src/modules/components/data-list/examples/5/index.ts
=> fix(core): prevent multiple call `markForCheck` in dropdown

projects/demo/src/modules/components/select/examples/9/account/my-account.component.html, projects/demo/src/modules/components/select/examples/9/account/my-account.component.less, projects/demo/src/modules/components/select/examples/9/account/my-account.component.ts, projects/demo/src/modules/components/select/examples/9/index.html, projects/demo/src/modules/components/select/examples/9/index.less, projects/demo/src/modules/components/select/examples/9/index.ts, projects/demo/src/modules/components/select/select.component.ts, projects/demo/src/modules/components/select/select.module.ts, projects/demo/src/modules/components/select/select.template.html, projects/kit/components/select/select.style.less
=> fix(kit): prevent content overflow in select

.github/workflows/release.yml, CHANGELOG.md, package-lock.json, package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-editor/package.json, projects/addon-mobile/package.json, projects/addon-preview/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/cdk/package.json, projects/core/constants/version.ts, projects/core/package.json, projects/i18n/package.json, projects/icons/package.json, projects/kit/package.json, projects/taiga-schematics/package.json, projects/testing/package.json
=> chore(release): 2.33.0

scripts/shared/check-import-with-src.ts, scripts/shared/check-private-exports.ts, scripts/shared/check-require-with-src.ts, scripts/shared/grep-by-pattern.ts
=> ci: show line code for debug when run check dist files

projects/demo/src/modules/components/input-inline/input-inline.component.ts
=> fix(demo): fixed input-inline tabs

.github/workflows/demo-integrations.yml
=> ci: add explicit info about which step failed

.github/workflows/demo-integrations.yml
=> ci: prevent race condition when load cypress.json

projects/demo/src/modules/components/input-tag/examples/6/index.html, projects/demo/src/modules/components/input-tag/examples/6/index.less, projects/demo/src/modules/components/input-tag/examples/6/index.ts, projects/demo/src/modules/components/input-tag/input-tag.component.ts, projects/demo/src/modules/components/input-tag/input-tag.module.ts, projects/demo/src/modules/components/input-tag/input-tag.template.html, projects/kit/components/input-tag/index.ts, projects/kit/components/input-tag/input-tag-options.ts, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/input-tag/input-tag.template.html, projects/kit/components/input-tag/test/input-tag.component.spec.ts, projects/kit/components/tag/tag.component.ts
only unique tags with comma or comma/space separator
ability to input non-unique tags with custom string/RegExp separator
=> feat(kit): `InputTag` allow non-unique tags and custom separators

.eslintrc.js
=> ci: support no-unnecessary-type-constraint

projects/addon-doc/schematics/doc-page/files/examples/__samples@dasherize__/index.html
=> fix(addon-doc): translate word in schematics

codecov.yml
=> ci: skip coverage analyse

.eslintrc.js, scripts/preprocess-icons.ts
=> ci: support require-await

.eslintrc.js, projects/icons/scripts/rollup-svgo.ts
=> ci: support await-thenable

projects/demo/src/modules/components/multi-select/examples/1/index.html, projects/demo/src/modules/components/multi-select/examples/2/index.html, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/input-tag/test/input-tag.component.spec.ts
=> fix(kit): show example text when opened dropdown in multi-select

projects/cdk/decorators/pure.ts, projects/cdk/decorators/test/pure.spec.ts
=> feat(cdk): support no arguments' function decorated by tuiPure

codecov.yml
=> ci: ignore check coverage by codecov

.github/workflows/release.yml
=> chore: temporary fix release workflow

.github/workflows/demo-integrations.yml, projects/demo-integrations/cypress/support/commands.ts
=> ci: use ssim algorithm for e2e

projects/demo/src/modules/components/line-clamp/examples/3/index.html, projects/demo/src/modules/components/line-clamp/examples/3/index.less, projects/demo/src/modules/components/line-clamp/examples/3/index.ts, projects/demo/src/modules/components/line-clamp/line-clamp.component.ts, projects/demo/src/modules/components/line-clamp/line-clamp.module.ts, projects/demo/src/modules/components/line-clamp/line-clamp.template.html, projects/kit/components/line-clamp/line-clamp.component.ts, projects/kit/components/line-clamp/line-clamp.template.html
=> fix(kit): prevent expression changed exception in `line-clamp`

projects/demo-integrations/cypress/support/shared.entities.ts, projects/demo-integrations/cypress/tests/kit/slider/slider.spec.ts, projects/demo/src/modules/components/slider/examples/3/index.html, projects/demo/src/modules/components/slider/examples/3/index.ts, projects/demo/src/modules/components/slider/slider.component.html, projects/demo/src/modules/components/slider/slider.component.ts, projects/kit/components/slider/slider.component.ts
=> fix(kit): `Slider` approximation bug with float `fillPercentage` (webkit)

projects/demo-integrations/cypress.json, projects/demo-integrations/cypress/plugins/index.js
=> ci: support `high-dpi-support` for e2e

codecov.yml
=> ci: another way for disable codecov/patch check

projects/demo/src/modules/animations/animations.component.ts, projects/demo/src/modules/animations/animations.module.ts, projects/demo/src/modules/animations/animations.style.less, projects/demo/src/modules/animations/animations.template.html, projects/demo/src/modules/animations/examples/fade-in/index.html, projects/demo/src/modules/animations/examples/fade-in/index.less, projects/demo/src/modules/animations/examples/fade-in/index.ts, projects/demo/src/modules/animations/examples/height-collapse/index.html, projects/demo/src/modules/animations/examples/height-collapse/index.less, projects/demo/src/modules/animations/examples/height-collapse/index.ts, projects/demo/src/modules/animations/examples/scale-in/index.html, projects/demo/src/modules/animations/examples/scale-in/index.less, projects/demo/src/modules/animations/examples/scale-in/index.ts, projects/demo/src/modules/animations/examples/width-collapse/index.html, projects/demo/src/modules/animations/examples/width-collapse/index.less, projects/demo/src/modules/animations/examples/width-collapse/index.ts, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/directives/dropdown/dropdown.template.html, projects/demo/src/modules/markup/skeleton/examples/2/index.html
-   [ ] Bugfix
new page `/animations`
-   [ ] Yes
-   [X] No
=> chore(demo): new demo page `Animations` (#684)

projects/core/styles/mixins/textfield.less, projects/kit/components/text-area/text-area.style.less
=> fix(core): provide fallback value for border-width

projects/core/styles/markup/tui-form.less
=> fix(core): fix form-header style

projects/cdk/services/parents-scroll.service.ts, projects/cdk/services/test/parent-scroll.service.spec.ts
Dropdown in nested scroll area starts to lag when reopens
Closes #1389
Dropdown in nested scroll area doesn't lag
=> fix(cdk): fix overwriting variable nativeElement

projects/core/components/root/root.component.ts, projects/core/tokens/index.ts, projects/core/tokens/theme.ts
=> chore(core): `TUI_THEME` add new token

projects/demo-integrations/cypress/plugins/index.js, projects/demo-integrations/cypress/support/commands.ts, projects/demo-integrations/cypress/tests/demo/demo.spec.ts
=> ci: set `0.0004%` threshold for e2e

projects/demo-integrations/cypress/tests/kit/slider/slider.spec.ts
=> ci: fix flaky e2e test

.eslintrc.js, .github/workflows/lint.yml, package.json, tsconfig.eslint.json
=> ci: run `eslint` before `prettier` in lint-staged

.github/workflows/demo-integrations.yml
=> ci: fix unexpected input(s)

projects/addon-commerce/components/money/index.ts, projects/addon-commerce/components/money/money-options.ts, projects/addon-commerce/components/money/money.component.ts, projects/addon-commerce/components/money/test/money-options.spec.ts
=> feat(addon-commerce): support options in money component

.eslintrc.js, projects/kit/components/slider/test/slider.spec.ts, projects/kit/directives/dropdown-context/test/dropdown-context.directive.spec.ts
=> ci: support `require-await`

projects/demo-integrations/cypress/tests/kit/multi-select/multi-select.spec.ts, projects/kit/components/input-tag/input-tag.component.ts
=> fix(kit): track openChange when clear value in multi-select

projects/cdk/directives/auto-focus/autofocus.directive.ts, projects/cdk/directives/auto-focus/test/auto-focus.directive.spec.ts
=> fix(cdk): `Autofocus` wait for Angular animations to finish before focusing

.eslintrc.js
```sh
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: projects/demo/src/modules/components/slider/examples/5/index.less.
The extension for the file (.less) is non-standard. You should add "parserOptions.extraFileExtensions" to your config
```
=> chore: `eslint` add `.less`, `.md` to `ignorePatterns`

projects/demo-integrations/cypress/tests/kit/multi-select/multi-select.spec.ts, projects/kit/components/multi-select/multi-select.component.ts, projects/kit/components/multi-select/multi-select.style.less
=> fix(kit): correct icons' alignment in multi-select

projects/core/directives/described-by/described-by.providers.ts, projects/demo-integrations/cypress/tests/core/primitive-textfield/primitive-textfield.spec.ts
desribedBy directive removes hint first time due to blur event
Closes #1287 
desribedBy directive removes hint on blur event only after focus from keyboard
=> fix(core): `DescribedByDirective` fix hint visibility

projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/demo/src/modules/components/mobile-calendar/examples/2/index.html, projects/demo/src/modules/components/mobile-calendar/examples/2/index.less, projects/demo/src/modules/components/mobile-calendar/examples/2/index.ts, projects/demo/src/modules/components/mobile-calendar/mobile-calendar.component.ts, projects/demo/src/modules/components/mobile-calendar/mobile-calendar.module.ts, projects/demo/src/modules/components/mobile-calendar/mobile-calendar.template.html
=> fix(addon-mobile): support late rendering

.github/workflows/create-release.yml, .github/workflows/demo-integrations.yml
=> ci: fix release workflow

projects/demo/src/modules/components/slider/examples/3/index.html, projects/demo/src/modules/components/slider/examples/3/index.ts
The example was not fully correct. We had contradiction between visual part and `formControl`.
Also, it demonstrates now how to use native property `step`.
=> chore(demo): `Slider` change example to demonstrate `step` property

projects/demo-integrations/cypress.json, projects/demo-integrations/cypress/plugins/index.js, projects/demo-integrations/cypress/support/exclusions.ts, projects/demo-integrations/cypress/support/go-to-demo-page.util.ts, projects/demo-integrations/cypress/support/shared.entities.ts, projects/demo-integrations/cypress/tests/addon-editor/color-picker.spec.ts, projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts, projects/demo-integrations/cypress/tests/addon-editor/toolbar-new.spec.ts, projects/demo-integrations/cypress/tests/addon-mobile/mobile-calendar/mobile-calendar.spec.ts, projects/demo-integrations/cypress/tests/core/data-list/data-list.spec.ts, projects/demo-integrations/cypress/tests/core/dialogs/dialogs.spec.ts, projects/demo-integrations/cypress/tests/deep/deep.spec.ts, projects/demo-integrations/cypress/tests/demo/demo.spec.ts, projects/demo/src/modules/app/app.style.less
Part of https://github.com/Tinkoff/taiga-ui/issues/1371
=> ci: investigate some problem with E2E

.npmrc
=> ci: increase `--max-old-space-size` to 12gb

projects/kit/components/slider/index.ts, projects/kit/components/slider/slider-options.ts, projects/kit/components/slider/slider.component.ts, projects/kit/components/slider/slider.style.less
These changes primary required for `InputSlider`
=> feat(kit): `TUI_SLIDER_OPTIONS` (make `Slider` more customizable)

projects/addon-editor/directives/design-mode/design-mode.directive.ts, projects/kit/components/combo-box/combo-box.component.ts, projects/kit/components/line-clamp/line-clamp.directive.ts, projects/kit/directives/dropdown-selection/dropdown-selection.directive.ts
=> fix(kit): `ComboBox` fix initial `search` emit

projects/core/components/primitive-textfield/primitive-textfield.module.ts, projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/core/components/primitive-textfield/primitive-textfield.template.html, projects/core/styles/mixins/textfield.less, projects/demo/src/modules/components/dialog/dialog.module.ts, projects/demo/src/modules/components/dialog/examples/6/index.html, projects/demo/src/modules/components/dialog/examples/6/index.ts, projects/kit/components/accordion/test/accordion.component.spec.ts, projects/kit/components/input-range/input-range.style.less, projects/kit/components/input-range/input-range.template.html, projects/kit/components/input-slider/input-slider.style.less, projects/kit/components/input-slider/input-slider.template.html, projects/kit/components/input-tag/input-tag.style.less, projects/kit/components/input-tag/input-tag.template.html, projects/kit/components/text-area/text-area.style.less, projects/kit/components/text-area/text-area.template.html
=> fix(core): `PrimitiveTextfield` fix styles collision with Bootstrap

projects/addon-editor/components/toolbar-new/toolbar-new.component.ts, projects/addon-editor/components/toolbar-new/toolbar-new.style.less, projects/addon-editor/components/toolbar-new/toolbar-new.template.html, projects/addon-editor/components/toolbar-tools/font-style/font-style.component.ts
=> feat(addon-editor): add `box-shadow` for toolbar panel

projects/demo/src/modules/animations/animations.style.less, projects/demo/src/modules/components/slider/examples/3/index.less, projects/demo/src/modules/components/slider/examples/5/index.less, projects/kit/components/slider/slider.component.ts, projects/kit/components/slider/slider.style.less
Ticks was not correctly positioned.
Everything is ok now
=> fix(kit): `Slider` fix ticks position

projects/demo/src/modules/animations/animations.style.less, projects/demo/src/modules/components/slider/examples/3/index.less, projects/demo/src/modules/components/slider/examples/5/index.less
My mistake from the previous PR.
**No changes are required for `kit`-package**
=> chore(demo): `Slider` fix demo examples

projects/core/styles/mixins/slider.less, projects/core/styles/mixins/slider.scss, projects/core/styles/taiga-ui-local.less, projects/core/styles/taiga-ui-local.scss, projects/demo/src/modules/animations/animations.style.less, projects/demo/src/modules/components/slider/examples/3/index.html, projects/demo/src/modules/components/slider/examples/3/index.less, projects/demo/src/modules/components/slider/examples/5/index.html, projects/demo/src/modules/components/slider/examples/5/index.less, projects/demo/src/modules/components/slider/slider.component.html, projects/demo/src/modules/components/slider/slider.module.ts, projects/kit/components/slider/slider.style.less
=> feat(core): new mixin `tui-slider-ticks-labels`

.eslintrc.js, package-lock.json, package.json, prettier.config.js
=> ci: cleanup

.github/workflows/demo-integrations.yml, projects/demo/src/modules/app/app.style.less
=> ci: hide only `tui-scroll-controls` for e2e

projects/cdk/tokens/tests/is-ios.spec.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-phone-international/test/international-input-phone.component.spec.ts
=> fix(kit): InputPhoneInternational fix drop/paste handler

projects/core/styles/mixins/slider.less, projects/core/styles/mixins/slider.scss, projects/demo/src/modules/components/input-slider/examples/2/index.html, projects/demo/src/modules/components/input-slider/examples/2/index.less, projects/demo/src/modules/components/input-slider/examples/2/index.ts, projects/demo/src/modules/components/input-slider/examples/3/index.html, projects/demo/src/modules/components/input-slider/examples/3/index.less, projects/demo/src/modules/components/input-slider/examples/3/index.ts, projects/demo/src/modules/components/input-slider/input-slider.component.ts, projects/demo/src/modules/components/input-slider/input-slider.module.ts, projects/demo/src/modules/components/input-slider/input-slider.template.html, projects/kit/abstract/input-slider.ts, projects/kit/components/input-range/input-range.template.html, projects/kit/components/input-slider/input-slider.component.ts, projects/kit/components/input-slider/input-slider.module.ts, projects/kit/components/input-slider/input-slider.style.less, projects/kit/components/input-slider/input-slider.template.html, projects/kit/components/slider/slider-key-steps.directive.ts, projects/kit/components/slider/slider-options.ts, projects/kit/components/slider/slider.module.ts
=> feat(kit): `InputSlider` use new `Slider` inside

.eslintrc.js, projects/addon-doc/src/components/page/page.providers.ts, projects/addon-editor/components/color-selector/color-selector.component.ts, projects/addon-editor/components/toolbar/toolbar.component.ts, projects/addon-editor/directives/design-mode/design-mode.directive.ts, projects/addon-table/components/reorder/reorder.component.ts, projects/cdk/pipes/filter/test/filter.pipe.spec.ts, projects/cdk/tokens/is-ios.ts, projects/core/utils/mask/create-auto-corrected-money-pipe.ts, projects/core/utils/miscellaneous/is-editing-key.ts, projects/demo/src/modules/components/combo-box/examples/1/index.ts, projects/demo/src/modules/components/data-list/examples/4/index.ts, projects/demo/src/modules/components/hosted-dropdown/examples/3/index.ts, projects/demo/src/modules/components/input-file/examples/3/index.ts, projects/demo/src/modules/components/input-tag/examples/2/index.ts, projects/demo/src/modules/components/input-tag/examples/4/index.ts, projects/demo/src/modules/components/multi-select/examples/2/index.ts, projects/demo/src/modules/components/tabs/examples/5/index.ts, projects/kit/components/accordion/accordion.component.ts, projects/kit/components/input-file/input-file.component.ts, projects/kit/components/input-number/input-number.component.ts, projects/testing/src/utils/page-object.ts
=> ci: support `@typescript-eslint/prefer-includes`

projects/core/utils/mask/create-number-mask.ts, projects/core/utils/mask/enable-auto-correct-decimal-symbol.ts, projects/core/utils/mask/index.ts, projects/demo/src/modules/components/input-range/examples/2/index.html, projects/demo/src/modules/components/input-range/examples/2/index.less, projects/demo/src/modules/components/input-range/examples/2/index.ts, projects/demo/src/modules/components/input-range/input-range.component.ts, projects/demo/src/modules/components/input-range/input-range.module.ts, projects/demo/src/modules/components/input-range/input-range.template.html, projects/kit/abstract/input-slider.ts, projects/kit/components/input-range/input-range.component.ts
=> fix(kit): correct handling the `thousandSeparator` for InputRange

projects/demo/src/modules/app/stackblitz/project-files/src/app/app.module.ts.txt
=> chore(demo): `TuiInputColorModule` add import for stackblitz

projects/demo/src/modules/pipes/field-error/examples/6/index.ts, projects/demo/src/modules/pipes/field-error/field-error.module.ts, projects/kit/pipes/field-error/field-error-content-pipe.ts, projects/kit/pipes/field-error/test/field-error-content-pipe.spec.ts
pipe can't work with error-functions
pipe can do this
=> feat(kit): `FieldErrorContent` add ability to work with function

projects/core/utils/format/format-number.ts, projects/core/utils/mask/create-auto-corrected-money-pipe.ts, projects/kit/components/input-number/input-number.component.ts, projects/kit/components/input-number/test/input-number-format.spec.ts, projects/kit/components/input-number/test/input-number.component.spec.ts, projects/kit/components/input-phone/input-phone.component.ts
=> fix(core): backward compatibility for separators

projects/core/components/notification/notification.component.ts, projects/core/modules/notifications/notification-alert/notification-alert.component.ts, projects/core/modules/notifications/notification-alert/test/notification-alert.component.spec.ts, projects/core/modules/notifications/notifications-host/notifications-host.component.ts, projects/core/modules/notifications/notifications-host/notifications-host.style.less, projects/core/modules/notifications/notifications-host/notifications-host.template.html, projects/core/modules/notifications/notifications.service.ts, projects/core/tokens/notification-options.ts, projects/demo/src/modules/components/dialog/dialog.template.html, projects/demo/src/modules/services/notifications/method.md, projects/demo/src/modules/services/notifications/notifications.component.ts, projects/demo/src/modules/services/notifications/notifications.template.html
=> feat(core): expose `TuiNotificationDefaultOptions`

projects/core/components/button/button.component.ts, projects/core/components/button/button.style.less, projects/core/components/button/button.template.html
=> fix(core): `Button` fix icon margins

.github/actions/nodejs/action.yml
=> ci: upgrade to node.js 14

.github/workflows/demo-integrations.yml
=> ci: health check before run e2e tests

projects/kit/components/input-count/input-count.component.ts
=> fix(kit): `InputCount` fix extra space when using max property

projects/core/components/button/button-options.ts
=> feat(core): add type inference to `appearance` for button

projects/kit/components/input-tag/input-tag.style.less
Closes #1507
https://user-images.githubusercontent.com/12021443/157835152-8792832a-25ae-4235-8860-22c1f5e585bb.mov
=> fix(kit): correct display of a comma when opened dropdown

projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/demo-integrations/cypress/support/shared.entities.ts, projects/demo-integrations/cypress/tests/kit/input/input.spec.ts, projects/demo/src/modules/components/abstract/control.ts, projects/demo/src/modules/components/primitive-textfield/primitive-textfield.component.ts
=> fix(core): `PrimitiveTextfield` long custom content overflow

projects/core/components/dropdown-box/dropdown-box.component.ts
=> fix(core): fix broken import

projects/core/styles/theme/wrapper.less, projects/core/styles/theme/wrapper/accent.less, projects/core/styles/theme/wrapper/base.less, projects/core/styles/theme/wrapper/icon.less, projects/core/styles/theme/wrapper/outline.less, projects/core/styles/theme/wrapper/primary.less, projects/core/styles/theme/wrapper/secondary.less, projects/core/styles/theme/wrapper/table.less, projects/core/styles/theme/wrapper/textfield.less, projects/core/styles/theme/wrapper/whiteblock.less
=> chore: simplify wrapper

package-lock.json, package.json, projects/demo-integrations/cypress/support/go-to-demo-page.util.ts, projects/demo-integrations/cypress/support/stub-metrics.ts, projects/demo/src/environments/environment.hmr.ts, projects/demo/src/environments/environment.prod.ts, projects/demo/src/environments/environment.ts, projects/demo/src/modules/app/app.browser.module.ts, projects/demo/src/modules/app/app.component.ts
=> chore(demo): add analytics

projects/core/styles/theme/variables.less, projects/demo/src/modules/components/slider/examples/2/index.less, projects/kit/components/slider/slider.style.less
=> chore(kit): `Slider` update color-customization method

projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/demo-integrations/cypress/tests/kit/input/input.spec.ts, projects/demo/src/modules/components/abstract/control.ts, projects/demo/src/modules/components/input/input.component.ts, projects/demo/src/modules/components/input/input.template.html
=> fix(core): `PrimitiveTextfield` built-in icons inside `tuiTextfieldCustomContent`

projects/demo/src/modules/markup/colors/colors.constants.ts
=> chore(demo): add new colors

.nxignore, angular.json, projects/cdk/package.json, projects/cdk/schematics/collection.json, projects/cdk/schematics/migration.json, projects/cdk/schematics/ng-add/constants/modules.ts, projects/cdk/schematics/ng-add/constants/packages.ts, projects/cdk/schematics/ng-add/constants/versions.ts, projects/cdk/schematics/ng-add/index.ts, projects/cdk/schematics/ng-add/schema.json, projects/cdk/schematics/ng-add/schema.ts, projects/cdk/schematics/ng-add/setup-project.ts, projects/cdk/schematics/ng-add/steps/add-taiga-icons.ts, projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts, projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts, projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts, projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts, projects/cdk/schematics/ng-update/index.ts, projects/cdk/schematics/tsconfig.spec.json, projects/cdk/schematics/utils/get-project-target-options.ts, projects/cdk/schematics/utils/get-project.ts, projects/cdk/test.ts, tsconfig.schematics.json
=> chore: move schematics, prepare for ng-update

.github/workflows/create-release.yml
=> chore(ci): add creating gh releases

projects/core/styles/theme/wrapper/textfield.less, projects/demo/src/modules/app/landing/landing.style.less, projects/demo/src/modules/charts/legend-item/examples/2/index.less, projects/demo/src/modules/components/carousel/examples/2/index.less, projects/demo/src/modules/components/sheet/examples/6/index.less
=> fix(core): fix textfield transition

projects/addon-tablebars/components/table-bars-host/table-bars-host.style.less
=> fix(addon-tablebar): fix adaptive container

projects/demo/src/modules/app/app.style.less
=> ci: fix flaky e2e tests

projects/demo/src/modules/components/multi-select/examples/4/index.ts
=> chore(demo): show preview text instead of empty space

projects/kit/components/slider/slider.component.ts, projects/kit/components/slider/slider.style.less
=> fix(kit): `Slider` distorted right border-radius

projects/cdk/components/dialog-host/dialog-host.component.ts, projects/demo-integrations/cypress/tests/core/dialogs/dialog-browser-back.spec.ts, projects/demo/src/modules/app/app.providers.ts, projects/demo/src/modules/components/dialog/dialog.template.html, projects/demo/src/modules/components/dialog/examples/import/dialogClosesOnBackToken.txt
=> chore(cdk): token `TUI_DIALOG_CLOSES_ON_BACK` change default value to `false`

projects/addon-doc/src/components/example/example-capitalize.pipe.ts, projects/addon-doc/src/components/example/example.module.ts, projects/addon-doc/src/components/example/example.style.less, projects/addon-doc/src/components/example/example.template.html, projects/core/utils/format/capitalize-first-letter.ts, projects/core/utils/format/index.ts, projects/core/utils/format/test/capitalize-first-letter.spec.ts
=> fix(addon-doc): ability to highlight with first letter in safari

projects/demo-integrations/cypress/tests/kit/input/input-tag.spec.ts, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/input-tag/input-tag.template.html
=> fix(kit): correct handling of color theme in `input-tag`

projects/demo-integrations/cypress/tests/kit/slider/slider.spec.ts, projects/kit/components/slider/slider.component.ts, projects/kit/components/slider/test/slider.spec.ts
=> fix(kit): `Slider` incorrect behaviour for `min` !== 0

.github/workflows/deploy-next.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy.yml
=> ci: cleanup deploy jobs

.github/workflows/deploy-next.yml, .github/workflows/deploy.yml
=> ci: fix tag name

.github/workflows/deploy-next.yml, .github/workflows/deploy.yml
=> ci: add PAT for check problems

.github/workflows/deploy-next.yml, .github/workflows/deploy.yml
=> ci: clean gh-pages when need deploy all files

.github/workflows/create-release.yml
=> chore(ci): fix release-action inputs

.gitignore, angular.json, package.json
=> ci: generate ssl certificate before serve https server

projects/core/utils/mask/create-auto-corrected-money-pipe.ts, projects/kit/components/input-number/input-number.component.ts
=> fix(kit): `InputNumber` apply caret fix for ios

projects/demo/src/modules/app/app.routes.ts
=> refactor: support IDE autocompletion

projects/cdk/components/dropdown-host/test/dropdown-portal.service.spec.ts, projects/cdk/observables/test/replay-control-value-changes.spec.ts
=> refactor: exclude tests which have no expectations

projects/demo/src/modules/app/app.browser.module.ts, projects/demo/src/modules/app/app.component.ts
Now, with local development, every time you go to any page, requests are sent to the metric
Enabled only for `https://taiga-ui.dev/*`
=> ci: analyze metrics for production only

projects/core/constants/regexp.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-phone-international/test/international-input-phone.component.spec.ts, projects/kit/components/input-phone/input-phone.component.ts
Closes #1571 
paste value with current code if no code found from value
=> feat(kit): `InputPhoneInternational` allow paste/drop without code

projects/addon-charts/components/line-chart/line-chart-hint.directive.ts, projects/addon-charts/components/line-chart/line-chart.component.ts, projects/addon-charts/components/line-chart/line-chart.template.html, projects/addon-charts/interfaces/index.ts, projects/addon-charts/interfaces/line-chart-hint-context.ts, projects/demo/src/modules/charts/line-chart/examples/4/index.html
Closes #1579
index added to context
=> feat(addon-charts): `LineChart` add index to hint context

projects/kit/components/input-slider/input-slider.module.ts
=> chore(kit): `InputSlider` remove redundant imports

projects/demo/src/modules/components/dialog/examples/4/index.less
=> fix: bad colors in dialog when using dark theme

projects/core/components/hints-host/hint-box/hint-box.component.ts, projects/core/components/hints-host/hint-box/hint-box.style.less, projects/core/types/direction.ts, projects/demo/src/modules/components/abstract/control.ts, projects/demo/src/modules/components/abstract/hint.ts, projects/demo/src/modules/components/abstract/inherited-documentation/inherited-documentation.component.ts, projects/demo/src/modules/components/primitive-textfield/primitive-textfield.component.ts, projects/demo/src/modules/components/tooltip/tooltip.component.ts, projects/demo/src/modules/directives/hint-controller/hint-controller.component.ts
Added middle position of top and bottom directions of hints
=> feat(hint): add middle position of top and bottom directions of hints

projects/demo/src/modules/components/tag/examples/5/index.html, projects/demo/src/modules/components/tag/examples/5/index.ts, projects/demo/src/modules/components/tag/examples/import/define-options.md, projects/demo/src/modules/components/tag/examples/import/import-module.md, projects/demo/src/modules/components/tag/examples/import/insert-template.md, projects/demo/src/modules/components/tag/examples/import/insert-template.txt, projects/demo/src/modules/components/tag/tag.component.ts, projects/demo/src/modules/components/tag/tag.module.ts, projects/demo/src/modules/components/tag/tag.template.html, projects/kit/components/tag/index.ts, projects/kit/components/tag/tag-options.ts, projects/kit/components/tag/tag.component.ts, projects/kit/components/tag/test/tag-options.spec.ts, projects/kit/tokens/tag-status.ts
Partially implements https://github.com/Tinkoff/taiga-ui/issues/133
Default tag options can be set via a provider. This is a partial implementation of https://github.com/Tinkoff/taiga-ui/issues/133
=> feat(kit): `TUI_TAG_OPTIONS` default options configuration for `Tag`

projects/core/components/group/group.module.ts
=> fix(core): compatible `TuiGroupModule` with `ViewEngine`

projects/demo-integrations/cypress/tests/addon-charts/addon-charts.spec.ts
=> chore: prevent flaky e2e test

.eslintrc.js, package-lock.json, package.json
=> ci: fix problem with precommit

package-lock.json, package.json, projects/addon-editor/styles/editor-socket.css, stylelint.config.js
=> ci: upgrade stylelint

projects/demo-integrations/cypress/tests/kit/range/range.spec.ts
=> chore(demo-integrations): `Range` change `goToDemoPage` to `tuiVisit`

.github/actions/nodejs/action.yml, .github/workflows/demo-integrations.yml, .npmrc
=> ci: move critical `env(s)` before upgrade to npm 8

projects/kit/components/range/range.module.ts, projects/kit/components/range/range.template.html
it is not existing bug yet (there were no releases after it had appeared).
That is why PR has prefix `chore(..)` (it should not appears in change log).
=> chore(kit): `Range` prevent sliders from focus if `focusable=false`

projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/input-tag/input-tag.template.html
=> fix(kit): provide default status when async pipe isn't emitted

angular.json
Closes #1607
This is not necessary, as there are places where they don't even pay attention to it.
=> ci: remove `anyComponentStyle` as redundant

.github/actions/cypress/action.yml, .github/actions/nodejs/action.yml, .github/workflows/demo-integrations.yml, .npmrc
=> ci: cleanup e2e job

projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less, projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html
=> Fix TabsWithMore

.nxignore, scripts/eslint/nx.js
=> ci: enable `enforce-module-boundaries`

projects/core/styles/theme/wrapper/whiteblock.less
Closes https://github.com/Tinkoff/taiga-ui/issues/1614
The border color for a CheckBox component has been changed from `tui-base-03` to `tui-base-04`.
=> fix(core): change color from tui-base-03 to tui-base-04

projects/core/components/alert/alert.module.ts
=> fix(core): `TuiNotificationsModule` is not a class value to reference

.github/workflows/auto-approve.yml
=> ci: auto approve tinkoff bot

projects/addon-doc/src/components/example/example.component.ts, projects/addon-doc/src/components/example/example.template.html, projects/addon-doc/src/interfaces/code-editor.ts, projects/addon-doc/src/tokens/code-editor.ts, projects/cdk/schematics/ng-update/constants/types.ts, projects/demo/src/modules/app/app.providers.ts, projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
=> refactor: add `TuiCodeEditor` interface

projects/kit/components/combo-box/combo-box.template.html, projects/kit/components/combo-box/test/combo-box.component.spec.ts
hint icon aligned wrong if no arrow provided
=> fix(kit): `Combobox` fix arrow in readonly state

projects/addon-preview/components/preview/preview.style.less, projects/cdk/directives/zoom/zoom.directive.ts, projects/demo/src/modules/directives/zoom/examples/1/index.less
=> fix(cdk): `Zoom` invalid css-property name `touch-action`

package-lock.json, package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-editor/package.json, projects/addon-mobile/package.json, projects/addon-preview/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/cdk/package.json, projects/core/ng-package.json, projects/core/package.json, projects/i18n/package.json, projects/icons/ng-package.json, projects/icons/package.json, projects/kit/package.json, projects/taiga-schematics/package.json
=> ci: support `sort-package-json` prettier plugin

projects/kit/tokens/i18n.ts
**Pagination**
**Preview**
**Pagination**
**Preview**
=> fix(kit): `Pagination` & `Preview` show `undefined` for `title`

.eslintrc.js, projects/addon-doc/src/components/example/example.component.ts, projects/addon-editor/components/editor-new/editor-new.providers.ts, projects/addon-editor/directives/design-mode/design-mode.directive.ts, projects/addon-editor/tokens/tiptap-editor.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.providers.ts, projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts, projects/addon-mobile/directives/ripple/ripple.directive.ts, projects/cdk/directives/overscroll/overscroll.directive.ts, projects/cdk/observables/focus-visible-observable.ts, projects/cdk/observables/prevent-default.ts, projects/cdk/observables/test/replay-control-value-changes.spec.ts, projects/cdk/observables/zone-free.ts, projects/cdk/services/pan.service.ts, projects/cdk/services/resize.service.ts, projects/cdk/services/scroll.service.ts, projects/cdk/services/static-request.service.ts, projects/cdk/services/zoom.service.ts, projects/cdk/tokens/active-element.ts, projects/cdk/tokens/window-height.ts, projects/core/components/alert/alert.component.ts, projects/core/components/data-list/data-list-dropdown-manager.directive.ts, projects/core/components/scroll-controls/scrollbar.directive.ts, projects/demo/src/modules/components/combo-box/examples/2/request.service.ts, projects/demo/src/modules/components/input-file/examples/3/index.ts, projects/demo/src/modules/components/multi-select/examples/4/index.ts
https://github.com/cartant/eslint-plugin-rxjs
=> ci: support rxjs eslint plugin

projects/addon-editor/components/editor-new/editor-new.component.html, projects/addon-editor/constants/default-editor-styles.ts, projects/addon-editor/constants/tiptap-editor-styles.ts, projects/addon-editor/styles/editor-socket.css, projects/demo-integrations/cypress/tests/addon-editor/link.spec.ts
Part of https://github.com/Tinkoff/taiga-ui/pull/1581
=> feat(addon-editor): improved ux for links

projects/cdk/coercion/coerce-boolean-property.ts, projects/cdk/coercion/index.ts, projects/cdk/coercion/package.json, projects/cdk/coercion/test/coerce-boolean-property.spec.ts, projects/cdk/index.ts
=> feat(cdk): new util `tuiCoerceBooleanProperty`

projects/demo/src/modules/components/input-phone-international/input-phone-international.template.html
=> chore: fix typo `contries` to `countries`

.github/workflows/build.yml, scripts/check-dist.ts
=> ci: refactor the `check-dist` utils for compat with proprietary repo

scripts/release.js
=> ci: skip branch already exists, it cannot create a new one

projects/demo/src/modules/markup/typography/typography.template.html
=> chore: fix typo

scripts/check-dist.ts, scripts/shared/argv.utils.ts, scripts/shared/check-import-with-src.ts, scripts/shared/check-incorrect-imports.ts, scripts/shared/check-private-exports.ts, scripts/shared/check-require-with-src.ts
=> ci: support custom flag for `check-dist`

.eslintrc.js, projects/demo/src/main.browser.ts, projects/demo/src/modules/app/app.component.ts, projects/demo/src/modules/app/app.providers.ts, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/components/editor-new/examples/2/index.ts, projects/kit/components/input-date-time/test/input-date-time.component.spec.ts, projects/kit/directives/dropdown-context/test/dropdown-context.directive.spec.ts
Requires any function or method that returns a Promise to be marked async.
Requires any function or method that returns a Promise to be marked async. Ensures that each function is only capable of:
returning a rejected promise, or
throwing an Error object.
In contrast, non-async Promise - returning functions are technically capable of either. Code that handles the results of those functions will often need to handle both cases, which can get complex. This rule's practice removes a requirement for creating code to handle both cases.
=> ci: support `promise-function-async`

projects/core/providers/mode.provider.ts, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/input-tag/input-tag.template.html, projects/kit/components/input-tag/test/input-tag-no-mode.component.spec.ts
=> fix(kit): emit null from mode provider instead cancel stream

projects/kit/components/text-area/text-area.style.less
=> fix(kit):  prevent display none when the textarea is not the last-child

scripts/shared/bump-tui-deps.ts, scripts/shared/sync-versions.ts
in proprietary repo
```
syncVersions('./projects', version, ['@taiga-ui/proprietary-tds-icons'])
```
=> ci: support ignore list when bumping version

angular.json
=> ci: fix running `cdk` tests in IDEA

projects/cdk/directives/index.ts, projects/cdk/directives/portal/index.ts, projects/cdk/directives/portal/package.json, projects/cdk/directives/portal/portal.directive.ts, projects/cdk/directives/portal/portal.module.ts, projects/cdk/directives/portal/test/portal.directive.spec.ts, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/directives/portal/examples/1/index.html, projects/demo/src/modules/directives/portal/examples/1/index.less, projects/demo/src/modules/directives/portal/examples/1/index.ts, projects/demo/src/modules/directives/portal/examples/import/import-module.md, projects/demo/src/modules/directives/portal/examples/import/insert-template.md, projects/demo/src/modules/directives/portal/portal.component.ts, projects/demo/src/modules/directives/portal/portal.module.ts, projects/demo/src/modules/directives/portal/portal.style.less, projects/demo/src/modules/directives/portal/portal.template.html
=> feat(cdk): `Portal` add new directive

projects/addon-table/components/table/directives/sortable.directive.ts
=> fi(addon-table): cannot access `TuiSortByDirective` before initialization

projects/cdk/classes/assert.ts
=> fix(cdk): correct assert for `svg` and `document` elements

projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
=> fix(addon-commerce): hide clear button when doesn't exist card number

scripts/postbump.ts, scripts/shared/sync-versions.ts, tsconfig.json
=> ci: synchronous update of `*/package.json` files

scripts/shared/bump-tui-deps.ts, scripts/shared/bump-tui-version-in-package-json.ts, scripts/shared/is-tui-package-name.ts, scripts/shared/sync-versions.ts
=> ci: refactor `sync-versions` script

.eslintrc.js, projects/cdk/coercion/coerce-boolean-property.ts, projects/icons/scripts/rollup-svgo.ts
=> ci: support `@typescript-eslint/no-base-to-string`

projects/cdk/date-time/day.ts, projects/cdk/date-time/test/day.spec.ts, projects/cdk/date-time/test/month.spec.ts
Closes #1694
`TuiDay` class has `static currentUtc()` method.
=> feat(cdk): add `currentUtc` in TuiDay

projects/demo-integrations/cypress/tests/kit/select/select.spec.ts
=> chore(demo-integrations): fix `Select` test with click on Arrow

package-lock.json, projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less, projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html, projects/core/styles/mixins/textfield.less, projects/demo-integrations/cypress/support/commands.ts, projects/demo-integrations/cypress/support/index.ts, projects/demo-integrations/cypress/tests/addon-commerce/input-card-grouped.spec.ts, projects/demo-integrations/package.json
Closes #1679
https://user-images.githubusercontent.com/12021443/165838470-cd31e93d-7259-46d8-aef2-a223bf0e687a.mov
https://user-images.githubusercontent.com/12021443/165838673-b1a77d90-f426-49de-a346-343111739468.mov
=> fix(addon-commerce): fix problem with `InputCardGrouped` in safari

projects/cdk/classes/assert.ts, projects/cdk/decorators/default-prop.ts
=> feat(cdk): use `unknown` instead `any` for `tuiDefaultProp`

projects/addon-editor/components/edit-link/edit-link.component.ts, projects/demo-integrations/cypress/tests/addon-editor/link.spec.ts
Part of #1302
https://user-images.githubusercontent.com/12021443/164423056-f6f7ba98-dd76-49b1-8aca-c36b8ee3bb0e.mov
https://user-images.githubusercontent.com/12021443/164423335-6bb914a4-b1a7-4383-aa51-25c23e40bc26.mov
=> fix(addon-editor): reopen dropdown when clicked another link

projects/testing/cypress/snapshot/plugin.ts
```
1) MobileCalendar
works:
Error: ENOENT: no such file or directory, rename
'.../screenshots/addon-mobile/mobile-calendar/mobile-calendar.spec.ts/mobile-calendar.png'
->
'.../screenshots/addon-mobile/==new==mobile-calendar/mobile-calendar.spec.ts/mobile-calendar.png'
```
No error
=> chore(testing): `Snapshot`-plugin fix

projects/kit/components/input-tag/test/input-tag.component.spec.ts
=> test: arguments will be treated as an error in a future release

projects/kit/components/input-month-range/input-month-range.component.ts, projects/kit/components/input-month-range/test/input-month-range.component.spec.ts
=> fix(kit): returns a full of stringified range when state is readonly

.eslintrc.js, projects/cdk/coercion/coerce-boolean-property.ts, projects/cdk/coercion/test/coerce-boolean-property.spec.ts
=> ci: use the type-safe equality operators

projects/demo-integrations/cypress/tests/kit/combo-box/combo-box.spec.ts, projects/kit/components/combo-box/combo-box-strict.directive.ts
=> fix(kit): combobox is cleared when you enter same value

projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts, projects/demo-integrations/cypress/tests/kit/input-date-range/input-date-range.spec.ts, projects/demo-integrations/cypress/tests/kit/input-date/input-date.spec.ts, projects/demo/src/modules/components/input-date/examples/2/index.html, projects/testing/utils/input/placeholder.unit-common.ts
=> fix(core): correct filler display for size `S` and `M`

.eslintrc.js, package-lock.json, package.json, projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts, projects/addon-commerce/components/input-card/input-card.component.ts, projects/addon-commerce/components/input-expire/input-expire.component.ts, projects/addon-commerce/utils/create-auto-corrected-expire-pipe.ts, projects/addon-commerce/utils/get-payment-system.ts, projects/addon-doc/src/components/documentation/documentation.component.ts, projects/addon-doc/src/components/example/example.component.ts, projects/addon-editor/components/edit-link/edit-link.component.ts, projects/addon-editor/utils/get-gradient-data.ts, projects/addon-editor/utils/parse-gradient.ts, projects/cdk/tokens/is-mobile.ts, projects/cdk/utils/svg/svg-linear-gradient-processor.ts, projects/core/utils/dom/process-icon.ts, projects/core/utils/format/get-fractional-part-padded.ts, projects/core/utils/mask/create-number-mask.ts, projects/demo/src/modules/directives/dropdown-selection/examples/2/index.ts, projects/icons/scripts/process-icons.ts, projects/kit/components/avatar/avatar.component.ts, projects/kit/components/input-phone/input-phone.component.ts, projects/kit/utils/dom/get-word-range.ts, projects/kit/utils/mask/create-auto-corrected-time-pipe.ts
=> refactor: replace deprecated `String.prototype.substr()`

package-lock.json, projects/addon-charts/components/arc-chart/arc-chart.component.ts, projects/addon-charts/components/arc-chart/arc-chart.style.less, projects/addon-charts/components/arc-chart/arc-chart.template.html, projects/demo/src/modules/charts/arc-chart/arc-chart.component.ts, projects/demo/src/modules/charts/arc-chart/arc-chart.module.ts, projects/demo/src/modules/charts/arc-chart/arc-chart.template.html, projects/demo/src/modules/charts/arc-chart/examples/1/index.html, projects/demo/src/modules/charts/arc-chart/examples/1/index.less, projects/demo/src/modules/charts/arc-chart/examples/1/index.ts
=> feat(addon-charts): `ArcChart` add `activeItemIndex`

projects/addon-charts/components/line-chart/line-chart.style.less
dots and lines are shown on hover
Closes #1578 
dots and lines are shown on hover
=> fix(addon-charts): fix line-chart dot style

.github/workflows/create-release.yml, .gitignore, package.json, scripts/postbump.ts, scripts/postchangelog.ts
=> ci: add `postchangelog` and fix some issues

projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/core/styles/theme/wrapper/secondary.less, projects/demo/src/modules/components/action/action.component.ts, projects/demo/src/modules/components/action/action.template.html, projects/demo/src/modules/components/action/examples/1/index.less, projects/kit/components/action/action.component.ts, projects/kit/components/action/action.style.less, projects/kit/components/marker-icon/marker-icon.component.ts, projects/kit/components/marker-icon/marker-icon.style.less
=> feat(kit): `Action` make icon color customizable

package-lock.json, projects/demo/package.json, projects/demo/src/polyfills.ts
=> ci: remove `classlist.js` for IE10 and IE11

.github/ISSUE_TEMPLATE/1-bug-report.yml
=> ci: improved issue template

projects/cdk/components/dialog-host/dialog-host.style.less, projects/cdk/components/dialog-host/dialog-host.template.html, projects/cdk/utils/focus/set-native-focused.ts, projects/demo/src/modules/components/dialog/dialog.component.ts, projects/demo/src/modules/components/dialog/dialog.module.ts, projects/demo/src/modules/components/dialog/dialog.template.html, projects/demo/src/modules/components/dialog/examples/7/index.html, projects/demo/src/modules/components/dialog/examples/7/index.ts, projects/demo/src/modules/components/dialog/examples/7/search-example/search-dialog-example.component.less, projects/demo/src/modules/components/dialog/examples/7/search-example/search-dialog-example.component.ts, projects/demo/src/modules/components/dialog/examples/7/search-example/search-dialog-example.template.html, projects/demo/src/modules/components/dialog/examples/7/search-example/search-dialog.module.ts, projects/demo/src/modules/components/dialog/method.md
=> chore: add example for catch bug on iOS

projects/demo/src/modules/components/input-date-range/input-date-range.template.html, projects/demo/src/modules/components/input-date/input-date.template.html
Closes #1715
MobileCalendar information is added to InputDate and InputDateRange documentation.
=> docs(kit): add MobileCalendar information to InputDate and InputDateRange

projects/addon-table/components/table-pagination/table-pagination.module.ts, projects/addon-table/components/table-pagination/table-pagination.style.less, projects/addon-table/components/table-pagination/table-pagination.template.html, projects/demo-integrations/cypress/tests/addon-table/table-pagination/table-pagination.spec.ts
Closes UIKIT-5784
<br />
<br />
<br />
=> fix(addon-table): `TablePagination` show checkmark for selected `[size]`

.gitignore
=> ci: ignore tsbuildinfo file after schematics compilation

projects/core/components/hints-host/hint-box/hint-box.component.ts, projects/core/components/hints-host/hint-box/hint-box.module.ts, projects/core/components/hints-host/hint-box/hint-box.style.less, projects/core/components/hints-host/hint-box/hint-box.template.html, projects/core/components/hints-host/hints-host.component.ts, projects/core/components/hints-host/hints-host.module.ts, projects/core/components/hints-host/hints-host.style.less, projects/core/components/hints-host/hints-host.template.html
=> chore(core): `HintBox` abstract away to lay grounds for custom hints

projects/addon-table/components/table-pagination/index.ts, projects/addon-table/components/table-pagination/table-pagination-options.ts, projects/addon-table/components/table-pagination/table-pagination.component.ts, projects/addon-table/components/table-pagination/table-pagination.module.ts, projects/addon-table/components/table-pagination/table-pagination.template.html, projects/demo-integrations/cypress/tests/addon-table/table-pagination/table-pagination.spec.ts, projects/demo/src/modules/tables/table-pagination/examples/2/index.html, projects/demo/src/modules/tables/table-pagination/examples/2/index.ts, projects/demo/src/modules/tables/table-pagination/table-pagination.component.ts, projects/demo/src/modules/tables/table-pagination/table-pagination.module.ts, projects/demo/src/modules/tables/table-pagination/table-pagination.template.html
Closes #UIKIT-5784
**2-[sizeOptionContent]-dropdown.snap.png:**
=> feat(addon-table): add token `TUI_TABLE_PAGINATION_OPTIONS` with property `sizeOptionContent`

projects/cdk/directives/auto-focus/autofocus.directive.ts, projects/cdk/directives/auto-focus/autofocus.options.ts, projects/cdk/directives/auto-focus/handlers/abstract.handler.ts, projects/cdk/directives/auto-focus/handlers/default.handler.ts, projects/cdk/directives/auto-focus/handlers/ios.handler.ts, projects/cdk/directives/auto-focus/index.ts, projects/cdk/directives/auto-focus/test/auto-focus.directive.spec.ts, projects/cdk/tokens/index.ts, projects/cdk/tokens/is-apple.ts, projects/cdk/tokens/is-ios.ts, projects/cdk/tokens/tests/is-ios.spec.ts, projects/cdk/utils/index.ts, projects/cdk/utils/os/index.ts, projects/cdk/utils/os/is-apple.ts, projects/cdk/utils/os/is-ios.ts, projects/cdk/utils/os/package.json
=> refactor: decompose the autofocus directive by handlers

projects/addon-mobile/components/mobile-calendar/tests/mobile-calendar.component.spec.ts, projects/addon-mobile/directives/elastic-sticky/test/elastic-sticky.directive.spec.ts, projects/addon-tablebars/components/table-bars-host/test/table-bars-host.component.spec.ts, projects/cdk/observables/test/drag-and-drop.spec.ts, projects/cdk/services/test/resize.service.spec.ts, projects/core/components/calendar/test/calendar.component.spec.ts, projects/core/components/expand/test/expand.component.spec.ts, projects/core/components/primitive-calendar/test/primitive-calendar.component.spec.ts, projects/core/components/primitive-spin-button/test/primitive-spin-button.component.spec.ts, projects/core/components/primitive-year-picker/test/primitive-year-picker.component.spec.ts, projects/core/components/svg/test/svg.component.spec.ts, projects/core/observables/test/smart-search.spec.ts, projects/kit/components/input-month/test/input-month.component.spec.ts, projects/kit/components/input-phone-international/test/international-input-phone.component.spec.ts, projects/kit/directives/lazy-loading/test/lazy-loading.directive.spec.ts
=> ci: refactor some unit tests

projects/kit/components/tag/tag.style.less, projects/kit/components/tag/tag.template.html
=> fix(kit): `Tag` has incorrect behavior of `text-overflow` in Safari

projects/core/components/link/link.style.less
=> chore(core): `Link` update underline color

projects/demo/src/modules/components/avatar/avatar.component.ts, projects/demo/src/modules/components/avatar/avatar.template.html, projects/demo/src/modules/components/avatar/examples/2/index.html, projects/demo/src/modules/components/avatar/examples/2/index.less, projects/demo/src/modules/components/avatar/examples/2/index.ts, projects/kit/components/avatar/avatar.style.less
=> feat(kit): `Avatar` add color customization with CSS vars

projects/addon-mobile/components/sheet/components/sheet/sheet.style.less, projects/core/providers/is-mobile-resolution.provider.ts, projects/core/tokens/is-mobile-resolution.ts
=> feat(core): `TUI_IS_MOBILE_RES` add new token

projects/kit/components/slider/slider.style.less
=> fix(kit): `Slider` blinking cursor in Firefox

projects/core/tokens/is-mobile-resolution.ts
=> chore: fix token

projects/demo/src/modules/components/dialog/dialog.module.ts, projects/demo/src/modules/components/dialog/examples/6/index.html, projects/demo/src/modules/components/dialog/examples/6/index.ts
```html
<form>
<input >
<button type="submit">Click</button> // reload page on click
</form>
```
Closes #1803
No page reload
=> chore(demo): `Dialog` example with unexpected page reload

projects/demo-integrations/cypress/tests/kit/stepper/stepper.spec.ts, projects/demo/src/modules/components/stepper/stepper.template.html, projects/kit/components/stepper/stepper.component.ts, projects/kit/components/stepper/stepper.style.less
https://user-images.githubusercontent.com/35179038/170248378-f6334e06-746d-4569-8026-f78ed75b4416.mov
Closes #1655
https://user-images.githubusercontent.com/35179038/170248399-93b8f85d-2c19-4015-ae2c-12e8ad4ef31d.mov
=> feat(kit): `Stepper` scroll internal scrollable area to active/focused step

projects/demo-integrations/cypress/tests/core/data-list/data-list.spec.ts, projects/demo/src/modules/components/data-list/data-list.component.ts, projects/demo/src/modules/components/data-list/data-list.module.ts, projects/demo/src/modules/components/data-list/data-list.template.html, projects/demo/src/modules/components/data-list/examples/2/index.html, projects/demo/src/modules/components/data-list/examples/2/index.ts, projects/demo/src/modules/components/data-list/examples/3/index.html, projects/demo/src/modules/components/data-list/examples/6/index.html, projects/demo/src/modules/components/data-list/examples/6/index.ts
New example includes this bug #1687.
I make this separate PR to catch any possible bug after trying to fix it.
=> chore(demo-integrations): `DataList` more tests

projects/cdk/schematics/ng-update/constants/consts.ts, projects/cdk/schematics/ng-update/constants/enums.ts, projects/cdk/schematics/ng-update/constants/types.ts, projects/cdk/schematics/ng-update/constants/warnings.ts, projects/cdk/schematics/ng-update/index.ts, projects/cdk/schematics/ng-update/steps/replace-deep-import.ts, projects/cdk/schematics/ng-update/steps/show-warnings.ts, projects/cdk/schematics/ng-update/tests/schematic-warnings.spec.ts
=> chore(cdk): `schematics` add deprecation warnings

projects/cdk/directives/for-async/for-async.directive.ts, projects/cdk/directives/for-async/for-async.module.ts, projects/cdk/directives/for-async/index.ts, projects/cdk/directives/for-async/package.json, projects/cdk/directives/for-async/test/for.directive.spec.ts, projects/cdk/directives/index.ts, projects/demo/src/modules/markup/icons/icons-group/icons-group.template.html, projects/demo/src/modules/markup/icons/icons.module.ts
When we try to navigate to a page with icons, the page consumes a lot of rendering resources
We have 45-58/60 fps (we lose about 13-15 frames)
https://user-images.githubusercontent.com/12021443/169708312-e645461f-0a70-464c-a7dc-3bf7ebb28b17.mov
https://user-images.githubusercontent.com/12021443/169708465-08a45190-2ed4-4d67-8cc9-0b94ae469bfc.mov
We have 57-58/60 fps
https://user-images.githubusercontent.com/12021443/169708337-394d68d0-6554-4fb8-bd63-34738736bb22.mov
https://user-images.githubusercontent.com/12021443/169708383-eb43ed88-fb27-43e9-a3de-b9e2e0efc9de.mov
=> feat(cdk): add directive for lazy rendering

projects/cdk/schematics/ng-update/constants/types.ts, projects/cdk/schematics/ng-update/tests/schematic-rename-types.spec.ts
=> chore(cdk): schematic `InputCountOptions`,`InputPasswordOptions`,`InputTimeOptions`,`ToggleOptions`

projects/cdk/tokens/tests/is-ios.spec.ts, projects/cdk/utils/os/index.ts, projects/cdk/utils/os/is-apple-platform.ts, projects/cdk/utils/os/is-ios.ts
Closes #1809
Supported in Android
=> fix(cdk): handle navigator platform for detect iOS

projects/cdk/schematics/ng-update/constants/types.ts, projects/cdk/schematics/ng-update/steps/rename-types.ts, projects/cdk/schematics/ng-update/tests/schematic-rename-types.spec.ts
=> chore(cdk): `migrations` remove deprecated interfaces

package-lock.json, package.json
=> ci: upgrade tslib

projects/demo/src/modules/components/rating/rating.component.ts
=> chore: compat with proprietary demo

projects/cdk/directives/for-async/for-async.directive.ts
=> fix(cdk): update template view inside angular zone

projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts
=> chore: fix flaky test

projects/cdk/schematics/ng-update/constants/services.ts, projects/cdk/schematics/ng-update/index.ts, projects/cdk/schematics/ng-update/steps/replace-services.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-services.spec.ts
=> chore(cdk): `migration` replace some services

projects/cdk/schematics/ng-update/constants/types.ts, projects/cdk/schematics/ng-update/steps/rename-types.ts, projects/cdk/schematics/ng-update/steps/replace-const.ts, projects/cdk/schematics/ng-update/steps/replace-enums.ts, projects/cdk/schematics/ng-update/steps/replace-services.ts, projects/cdk/schematics/ng-update/tests/schematic-rename-types.spec.ts, projects/cdk/schematics/utils/import-manipulations.ts, projects/core/interfaces/notification-options.ts
=> chore(cdk): migrations for interfaces `notification` => `alert`

projects/cdk/schematics/ng-update/constants/consts.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-consts.spec.ts
=> chore(cdk): `migrations` migrate TuiNotificationsModule

projects/cdk/schematics/ng-update/constants/consts.ts, projects/cdk/schematics/ng-update/constants/enums.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-consts.spec.ts
=> chore(cdk): `migrations` identity, TuiInputMode

projects/cdk/schematics/ng-update/constants/consts.ts, projects/cdk/schematics/ng-update/constants/enums.ts, projects/cdk/schematics/ng-update/constants/services.ts, projects/cdk/schematics/ng-update/constants/warnings.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-services.spec.ts
=> chore(cdk): `migrations` `TUI_SHEET_OFFSET`, `TuiCodeEditor`, `TuiTouchMode`, `TUI_SANITIZER`

projects/cdk/schematics/ng-update/constants/consts.ts, projects/cdk/schematics/ng-update/constants/types.ts, projects/cdk/schematics/ng-update/constants/warnings.ts, projects/cdk/schematics/ng-update/tests/schematic-rename-types.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-consts.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-warnings.spec.ts
=> chore(cdk): `schematics` for `COUNTRIES`, `COUNTRIES_MASKS`, `Country`, `TuiCountryIsoCode`

package-lock.json, scripts/shared/bump-tui-deps.ts
=> ci: update fields in `requires` into package-lock.json

projects/demo/src/modules/components/input-count/input-count.template.html, projects/demo/src/modules/components/input-number/input-number.template.html, projects/demo/src/modules/components/input-range/input-range.template.html, projects/demo/src/modules/components/input-slider/input-slider.template.html, projects/demo/src/modules/components/money/money.template.html, projects/demo/src/modules/pipes/format-number/format-number.template.html, projects/demo/src/modules/utils/tokens/examples/4/index.html, projects/demo/src/modules/utils/tokens/examples/5/index.html, projects/demo/src/modules/utils/tokens/examples/8/index.html, projects/demo/src/modules/utils/tokens/tokens.component.ts
=> chore(demo): improve `Tokens` documentation page

projects/demo/src/polyfills.ts
=> chore(demo): don't override Prisma reference

projects/addon-editor/constants/tiptap-editor-styles.ts, projects/addon-editor/extensions/details/summary.extension.ts
cursor in "summary" is invisible in some cases
cursor is visible
=> fix(addon-editor): fix cursor visibility in summary extension

projects/addon-editor/extensions/details/details.extension.ts
details can set as content only current node when created
Closes # 
details can set as content any selected nodes
=> feat(addon-editor): add selected content into details

projects/kit/components/multi-select/hide-selected.pipe.ts
=> fix(kit): use correct return type when passing an argument

.github/PULL_REQUEST_RELEASE_TEMPLATE.md, .github/workflows/create-release.yml
=> ci: remove redundant job step

.github/workflows/create-release.yml
=> ci: revert line

.github/workflows/deploy.yml, .gitignore, projects/demo/src/modules/app/version-manager/versions.constants.ts, scripts/build-all-demo-snapshots.ts, scripts/shared/clone-pre-built-snapshots.ts, scripts/shared/make-publishable-versions-map.ts
=> ci: upload old snapshots from branch

projects/cdk/package.json
ng-morph and angular-devkit/schematic moved from devDependencies to dependencies
=> chore(cdk): fix dependency for schematics

.eslintrc.js, projects/addon-editor/components/toolbar-tools/table-row-column-manager/table-row-column-manager.component.ts
=> ci: enable prefix for exported enums

projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/pipes/field-error/field-error.template.html
1. Go to https://taiga-ui.dev/pipes/field-error
2. Press button 
404 error
=> chore(demo): `FieldError`-pipe invalid link to source code

projects/addon-mobile/components/mobile-calendar/tests/mobile-calendar.component.spec.ts
=> refactor: prevent flaky unit test

projects/addon-commerce/components/money/money.component.ts, projects/cdk/schematics/ng-update/constants/types.ts, projects/core/interfaces/number-format-settings.ts, projects/core/pipes/format-number/format-number.pipe.ts, projects/core/tokens/number-format.ts, projects/core/utils/mask/enable-auto-correct-decimal-symbol.ts, projects/demo/src/modules/directives/copy-processor/examples/1/index.ts, projects/demo/src/modules/utils/tokens/examples/8/index.ts, projects/kit/components/input-count/input-count.component.ts, projects/kit/components/input-number/input-number.component.ts
=> feat(core): new `TuiNumberFormatSettings` instead of deprecated `NumberFormatSettings`

projects/cdk/schematics/ng-update/constants/consts.ts, projects/cdk/schematics/ng-update/constants/services.ts, projects/cdk/schematics/ng-update/constants/warnings.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-consts.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-services.spec.ts
=> chore(cdk): a little bit of migrations

projects/demo-integrations/cypress/support/scroll-into-view.ts, projects/demo-integrations/cypress/tests/demo/demo.spec.ts
=> ci: use `tuiScrollIntoView`

projects/addon-commerce/components/money/money.component.ts, projects/addon-commerce/enums/money-sign.ts, projects/cdk/constants/unicode-chars.ts, projects/core/pipes/format-phone/format-phone.pipe.ts, projects/core/utils/format/format-number.ts, projects/core/utils/format/format-phone.ts, projects/core/utils/mask/create-auto-corrected-money-pipe.ts, projects/core/utils/mask/create-number-mask.ts, projects/core/utils/mask/masked-money-value-is-empty.ts, projects/kit/components/input-month-range/input-month-range.component.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/constants/masks.ts
These are 3 different sign:
1. `-` (hyphen)
2. `–` (en-dash)
3. `—` (em-dash)
It is easy to confuse them.
And I even have found some places of possible wrong usage of these symbols (they will be fixed in a separate PR).
=> feat(cdk): constants `CHAR_HYPHEN` | `CHAR_EN_DASH` | `CHAR_EM_DASH` | `CHAR_PLUS`

.eslintrc.js, projects/demo-integrations/cypress/plugins/index.ts
[Array#push()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push) accepts multiple arguments. Multiple calls should be combined into one.
**Fail**
foo.push(1);
foo.push(2, 3);
**Pass**
foo.push(1, 2, 3);
const length = foo.push(1);
foo.push(2);
----
foo.push(1);
bar();
foo.push(2);
=> ci: support `no-array-push-push`

.eslintrc.js, projects/kit/utils/files/format-size.ts
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/require-number-to-fixed-digits-argument.md
=> ci: support `require-number-to-fixed-digits-argument`

.eslintrc.js
=> ci: support `no-empty-file`

.eslintrc.js
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-useless-spread.md
=> ci: support `no-useless-spread`

projects/cdk/directives/for-async/for-async.directive.ts, projects/cdk/directives/for-async/test/for.directive.spec.ts
=> feat(addon-doc): support index in `tuiForAsync`

.eslintrc.js, projects/cdk/constants/unicode-chars.ts, projects/icons/scripts/process-icons.ts, projects/icons/scripts/rollup-svgo.ts, projects/testing/cypress/snapshot/plugin.ts, scripts/postbuild-demo.ts, scripts/preprocess-icons.ts, scripts/shared/cleanup-dist-demo-directory.ts, scripts/shared/clone-pre-built-snapshots.ts, scripts/shared/log-dist-directory.ts, scripts/shared/make-publishable-versions-map.ts, scripts/shared/sync-versions.ts
=> ci: support `escape-case`

projects/cdk/schematics/ng-update/constants/modules.ts, projects/cdk/schematics/ng-update/constants/warnings.ts, projects/cdk/schematics/ng-update/index.ts, projects/cdk/schematics/ng-update/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/steps/remove-module.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-consts.spec.ts, projects/cdk/schematics/utils/templates/elements.ts, projects/cdk/schematics/utils/templates/ng-component-input-manipulations.ts
=> chore(cdk): `migrations` TuiResizableColumnModule, TuiColorHandler, add utils from cdk

projects/kit/pipes/field-error/field-error-pipe.ts
=> refactor(kit): `FieldError`-pipe remove redundant code

.eslintrc.js, projects/addon-charts/components/pie-chart/pie-chart.component.ts, projects/demo-integrations/cypress/support/visit.ts, projects/testing/utils/configure-test-suite.ts
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/dot-notation.md
=> ci: support `dot-notation`

projects/demo/src/modules/app/app.browser.module.ts
http://localhost:3333/changelog
http://localhost:3333/changelog
=> chore(demo): ignore redundant sanitizing for markdown plugin

package-lock.json, projects/cdk/package.json
=> chore(cdk): fix deps

projects/core/components/dialog/dialog.component.ts, projects/core/components/dialog/dialog.style.less, projects/core/types/dialog-size.ts, projects/demo/src/modules/components/dialog/dialog.component.ts
=> feat(core): `Dialog` add `auto` size

package-lock.json, projects/demo-integrations/package.json, projects/testing/package.json
=> ci: broken run of cypress v10.1

projects/core/styles/theme/wrapper/icon.less, projects/demo-integrations/cypress/tests/core/button/button.spec.ts, projects/demo/src/modules/components/button/button.template.html
See this PR after https://github.com/Tinkoff/taiga-ui/pull/1941
part of #1939
=> chore(demo-integrations): `IconButton` check `hovered`-state with `onDark`-mode

angular.json
=> ci: use `demo` as default project

projects/addon-table/components/table/directives/sortable.directive.ts, projects/demo/src/modules/tables/table/examples/4/index.ts
=> fix(addon-table): `Table` fix changing initial direction with server-side sorting

projects/core/styles/theme/wrapper/base.less, projects/core/styles/theme/wrapper/icon.less
broken style for hover and active state
Closes #1939
=> fix(core): `tuiWrapper` fix icon appearance

projects/kit/components/input-phone-international/const/countries.ts, projects/kit/components/input-phone-international/index.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-phone-international/input-phone-international.options.ts, projects/kit/components/input-phone-international/test/international-input-phone.component.spec.ts, projects/kit/components/input-phone/index.ts, projects/kit/components/input-phone/input-phone.component.ts, projects/kit/components/input-phone/input-phone.options.ts
=> fix(kit): use correct mask for `RU`-phone number

projects/cdk/schematics/ng-update/constants/consts.ts, projects/cdk/schematics/ng-update/index.ts, projects/cdk/schematics/ng-update/steps/replace-functions.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-functions.spec.ts, projects/kit/pipes/filter-by-input/filter-by-input-with.pipe.ts, projects/kit/pipes/filter-by-input/filter-by-input.base.ts, projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts
=> chore(cdk): `migrations` migrate some utils

projects/core/components/data-list/data-list.component.ts, projects/demo/src/modules/components/combo-box/combo-box.component.ts, projects/demo/src/modules/components/combo-box/combo-box.module.ts, projects/demo/src/modules/components/combo-box/combo-box.template.html, projects/demo/src/modules/components/combo-box/examples/5/index-change.directive.ts, projects/demo/src/modules/components/combo-box/examples/5/index.html, projects/kit/components/tabs/tabs-with-more/tabs-with-more.providers.ts
=> chore(demo): add virtual scroll fix

projects/kit/components/input-slider/input-slider.component.ts, projects/kit/components/input-slider/test/input-slider-new.component.spec.ts
=> fix(kit): `InputSlider` property `[quantum]` does not properly work on blur

projects/cdk/schematics/ng-add/steps/add-taiga-icons.ts, projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts, projects/cdk/schematics/utils/get-project.ts, projects/taiga-schematics/schematics/ng-add/steps/add-taiga-icons.ts, projects/taiga-schematics/schematics/ng-add/steps/add-taiga-styles.ts, projects/taiga-schematics/schematics/utils/get-project.ts
ng add doesn't work with angular 14
updateWorkspace overload with only workspace arg has been removed
https://github.com/angular/angular-cli/commit/b07ccfbb1b2045d285c23dd4b654e1380892fcb2#diff-2740741169dc6046fa1273c3841fcf3812646f415c89a1f7c485165f6b74e8aaL34
Closes #1909
ng add works with angular 14
=> fix(cdk): support ng-add for ng14

projects/addon-editor/components/editor-new/editor-new.style.less, projects/addon-editor/components/toolbar-new/toolbar-new.style.less, projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts, projects/demo-integrations/cypress/tests/addon-editor/link.spec.ts, projects/demo-integrations/cypress/tests/addon-editor/toolbar-new.spec.ts
=> feat(addon-editor): use wrap lines for tools when overflow of container

.eslintrc.js, projects/addon-doc/src/interfaces/code-editor.ts, projects/cdk/schematics/ng-update/constants/types.ts, projects/cdk/schematics/ng-update/tests/schematic-rename-types.spec.ts, projects/cdk/tokens/is-cypress.ts, projects/core/interfaces/number-format-settings.ts, projects/demo/src/modules/app/version-manager/version-manager.component.ts, projects/demo/src/modules/app/version-manager/version-manager.providers.ts, projects/demo/src/modules/app/version-manager/versions.constants.ts, projects/demo/src/modules/customization/dialogs/examples/1/prompt/prompt.component.ts, projects/i18n/interfaces/language.ts, projects/icons/scripts/rollup-svgo.ts, projects/kit/components/input-phone-international/interfaces/country.ts, projects/kit/interfaces/with-date-mask-pipe-config.ts, scripts/eslint/naming-convention.js
=> ci: checking `Tui` prefix as required for exported interfaces

package-lock.json, package.json, projects/demo-integrations/package.json, projects/testing/package.json
=> ci: pin cypress 10.0.3

projects/cdk/schematics/ng-update/constants/templates.ts, projects/cdk/schematics/ng-update/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
=> chore(cdk): breadcrumbs migration

projects/cdk/services/directive-styles.service.ts, projects/demo/src/modules/directives/present/examples/1/index.html, projects/kit/directives/present/present-styles.component.ts, projects/kit/directives/present/present.directive.ts, projects/kit/directives/present/present.module.ts, projects/kit/directives/present/present.style.less
=> refactor(kit): `tuiPresentChange`-directive use component approach for styles

projects/addon-mobile/components/theme-android/theme-android.style.less, projects/addon-mobile/components/theme-ios/theme-ios.style.less
=> fix(addon-mobile): fix overscroll for android

karma.config.js, package-lock.json, package.json, projects/addon-editor/components/toolbar-tools/table-size-selector/table-size-selector.component.ts, projects/addon-tablebars/components/table-bars-host/table-bars-host.component.ts, projects/cdk/utils/dom/get-viewport-height.ts, projects/cdk/utils/dom/get-viewport-width.ts, projects/cdk/utils/dom/index.ts, projects/cdk/utils/dom/test/get-viewport.spec.ts, projects/core/components/dialog/dialog.providers.ts, projects/core/components/dropdown-box/dropdown-box.component.ts, projects/core/components/hints-host/hint-box/hint-box.component.ts, projects/core/tokens/is-mobile-resolution.ts, projects/core/utils/index.ts, projects/core/utils/mobile/index.ts, projects/core/utils/mobile/is-mobile.ts, projects/core/utils/mobile/package.json
=> fix(core): cross-browser viewport width for mobile

projects/cdk/schematics/ng-update/steps/migrate-sliders/index.ts, projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-range.ts, projects/cdk/schematics/ng-update/tests/schematic-migrate-sliders.spec.ts
=> chore(cdk): `InputRange` migrations for `minLabel` and `maxLabel`

projects/addon-editor/components/editor-new/editor-new.component.html, projects/addon-editor/components/editor-new/editor-new.module.ts, projects/addon-editor/components/editor-new/editor-new.providers.ts, projects/addon-editor/components/editor-new/index.ts, projects/addon-editor/components/editor-new/portal/editor-portal-host.component.ts, projects/addon-editor/components/editor-new/portal/editor-portal-host.style.less, projects/addon-editor/components/editor-new/portal/editor-portal.service.ts, projects/demo-integrations/cypress/support/editor/helpers.ts, projects/demo-integrations/cypress/tests/addon-editor/editor-new-dropdown.spec.ts, projects/demo-integrations/cypress/tests/addon-editor/link.spec.ts
Part of #1302
Closes #Jira/UIKIT-5113
https://user-images.githubusercontent.com/12021443/174117814-3695e928-45d9-4427-9e1f-795861762fda.mov
https://user-images.githubusercontent.com/12021443/174117929-076bb5f4-fa07-465f-92c9-f211046a3c8c.mov
=> fix(addon-editor): dropdown shouldn't visible outside of editor area

projects/addon-doc/src/components/documentation/documentation.component.ts, projects/addon-doc/src/components/documentation/documentation.template.html, projects/core/components/link/link.style.less, projects/demo-integrations/cypress/tests/kit/line-clamp/line-clamp.spec.ts, projects/demo/src/modules/components/line-clamp/line-clamp.component.ts, projects/demo/src/modules/components/line-clamp/line-clamp.template.html, projects/kit/components/line-clamp/line-clamp.style.less
**03-[linesLimit=1]-longWord**:
**03-[linesLimit=1]-longWord**:
**Diff:**
=> fix(kit): `LineClamp` very long word + `[linesLimit]=1`

projects/addon-editor/components/editor-new/editor-new.component.html, projects/addon-editor/components/editor-new/editor-new.module.ts, projects/addon-editor/components/editor-new/editor-new.providers.ts, projects/addon-editor/components/editor-new/index.ts, projects/addon-editor/components/editor-new/portal/editor-portal-host.component.ts, projects/addon-editor/components/editor-new/portal/editor-portal-host.style.less, projects/addon-editor/components/editor-new/portal/editor-portal.directive.ts, projects/addon-editor/components/editor-new/portal/editor-portal.service.ts, projects/demo-integrations/cypress/support/editor/helpers.ts, projects/demo-integrations/cypress/tests/addon-editor/editor-new-dropdown.spec.ts, projects/demo-integrations/cypress/tests/addon-editor/link.spec.ts
=> fix(addon-editor): dropdown shouldn't visible outside editor area

projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-range.ts, projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-slider.ts
```
saveActiveProject();
setActiveProject(createProject(fileSystem.tree, '/', '**/**'));
```
These commands are very expensive operations.
We should not call them on every template iteration.
=> chore(cdk): `schematics` improve performance of migration for sliders

projects/cdk/schematics/ng-update/index.ts, projects/cdk/schematics/ng-update/steps/migrate-progress.ts, projects/cdk/schematics/ng-update/tests/schematic-migrate-progress.spec.ts
=> chore(cdk): `ProgressBar` migrations for deprecated pipes

.github/screenshot-bot.config.toml
=> ci: `screenshot-bot.config.toml` ignore `release/*`-branches

projects/cdk/directives/copy-processor/copy-processor.directive.ts, projects/cdk/utils/dom/get-selected-text.ts, projects/cdk/utils/dom/index.ts, projects/cdk/utils/dom/is-form-field.ts, projects/demo/src/modules/directives/copy-processor/examples/1/index.html, projects/demo/src/modules/directives/copy-processor/examples/1/index.ts
=> fix(cdk): correct selection from textfield in firefox

projects/cdk/schematics/ng-update/constants/templates.ts, projects/cdk/schematics/ng-update/index.ts, projects/cdk/schematics/ng-update/steps/migrate-progress.ts, projects/cdk/schematics/ng-update/steps/migrate-sliders/index.ts, projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-range.ts, projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-slider.ts, projects/cdk/schematics/ng-update/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/steps/replace-services.ts, projects/cdk/schematics/ng-update/tests/schematic-migrate-sliders.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts, projects/cdk/schematics/utils/colored-log.ts
=> chore(cdk): migrations optimization, logs

.eslintrc.js, package-lock.json, package.json, projects/addon-doc/src/components/navigation/navigation.template.html, projects/demo-integrations/cypress/support/commands.ts, projects/demo-integrations/cypress/support/hide-version-manager.ts, projects/demo-integrations/cypress/support/visit.ts, projects/demo-integrations/cypress/tests/demo/navigation.spec.ts, scripts/eslint/cypress.js
=> chore(demo): fix class name for active link in navigation

projects/cdk/schematics/ng-update/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
=> chore(cdk): `migrations` add editor providers

package-lock.json, package.json
Regression:
https://github.com/cypress-io/cypress/issues/22451
=> ci: fix regression in cypress 10.2.0

projects/core/utils/dom/tests/get-viewport.spec.ts, projects/core/utils/mobile/is-mobile.ts, projects/demo-integrations/cypress/tests/demo/getting-started.spec.ts
=> fix(core): wrong detection of viewport for mobile device width

scripts/eslint/naming-convention.js
=> ci: compat eslint rules with proprietary files

.github/workflows/release.yml
=> chore: skip publish for investigate alpha release

.github/workflows/create-release.yml, scripts/release.ts, scripts/shared/bump-version.ts, scripts/shared/release-mode.ts, scripts/shared/run-standard-verion.ts
=> ci: support prerelease

projects/cdk/schematics/ng-update/index.ts, projects/cdk/schematics/ng-update/steps/migrate-date-time.ts, projects/cdk/schematics/ng-update/steps/miscellaneous.ts, projects/cdk/schematics/ng-update/tests/schematic-date-time.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-miscellaneous.spec.ts, projects/cdk/schematics/utils/insert-todo.ts
=> chore(cdk): date time related migrations

projects/cdk/schematics/ng-update/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/steps/replace-services.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts, projects/cdk/schematics/utils/templates/elements.ts
=> chore(cdk): `schematics` migration for `tuiHideSelected`-pipe

projects/core/components/primitive-textfield/test/primitive-textfield.component.spec.ts, projects/core/components/primitive-textfield/value-decoration/value-decoration.template.html, projects/demo-integrations/cypress/tests/kit/input-number/input-number.spec.ts, projects/demo/src/modules/components/input-number/examples/5/index.html, projects/demo/src/modules/components/input-number/examples/5/index.ts, projects/demo/src/modules/components/input-number/input-number.component.ts, projects/demo/src/modules/components/input-number/input-number.module.ts, projects/demo/src/modules/components/input-number/input-number.template.html, projects/kit/components/input-range/test/input-range.component.spec.ts
=> fix(core): preserve whitespaces in postfix for value-decoration

.github/workflows/create-release.yml, scripts/release.ts
=> ci: support dry-run for release

projects/demo/src/modules/components/accordion/accordion.component.ts, projects/demo/src/modules/components/accordion/accordion.template.html, projects/kit/components/accordion/accordion-item/accordion-item.style.less, projects/kit/components/accordion/accordion-item/accordion-item.template.html
Closes #2027
https://user-images.githubusercontent.com/46284632/176466878-72be3165-85f2-4eb9-b6f8-f3050b2e742d.mov
=> fix(kit): fix disableHover input in `AccordionItem`

projects/demo-integrations/cypress/tests/addon-doc/navigation.spec.ts, projects/demo/src/modules/app/utils/ready-to-scroll-factory.ts
https://user-images.githubusercontent.com/35179038/176865399-4f5eebfe-e561-4633-a0ba-dc6400df1ee1.mov
https://user-images.githubusercontent.com/35179038/176865517-2536a729-8d02-415d-b1e1-d5849b0ee9f8.mov
=> chore(demo): also wait loading of `tui-doc-code` before scroll

projects/demo-integrations/cypress/tests/addon-doc/viewport.spec.ts
=> ci: fix flaky e2e

.github/workflows/create-release.yml
=> ci: correct processing of `dry-run` mode or `rc` mode

projects/demo/src/modules/components/group/examples/1/index.html, projects/demo/src/modules/components/group/examples/1/index.ts, projects/demo/src/modules/components/group/group.module.ts, projects/kit/components/multi-select/multi-select.style.less
=> fix(kit): `MultiSelect` inside `Group` border-radius problem

projects/demo-integrations/cypress/tests/addon-doc/viewport.spec.ts
=> ci: choose another page for testing viewport in e2e

.github/workflows/create-release.yml, .github/workflows/deploy.yml, .github/workflows/release.yml
=> ci: don't create github release when is `dry-run`

projects/demo/src/modules/directives/sidebar/sidebar.template.html
=> docs: fix typo

projects/cdk/schematics/ng-update/constants/templates.ts, projects/cdk/schematics/ng-update/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/tests/schematic-textfield-icon.spec.ts, projects/cdk/schematics/utils/templates/ng-component-input-manipulations.ts
=> chore(cdk): textfield icons migration

projects/demo-integrations/cypress/tests/kit/tabs/tabs.spec.ts, projects/kit/components/tabs/tab/tab.style.less, projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less, projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html, projects/kit/components/tabs/tabs/tabs.style.less, projects/kit/components/tabs/tabs/tabs.template.html
=> fix(kit): `Tab` redundant space after the last tab

projects/cdk/schematics/ng-update/constants/deprecated-functions.ts, projects/cdk/schematics/ng-update/constants/types.ts, projects/cdk/schematics/ng-update/steps/replace-functions.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-consts.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-deprecated-functions.spec.ts, projects/cdk/utils/format/pad-start.ts, projects/core/utils/miscellaneous/color-fallback.ts
=> chore: add migration for deprecated functions

.github/workflows/autorebase.yml
=> ci: autorebase for marked pull request

projects/addon-charts/components/bar-set/bar-set.template.html, projects/addon-charts/components/pie-chart/pie-chart.template.html, projects/addon-doc/src/components/demo/demo.template.html, projects/addon-doc/src/components/documentation/documentation.template.html, projects/addon-doc/src/components/example/example.template.html, projects/addon-doc/src/components/page/page.template.html, projects/addon-table/components/table/th/th.template.html, projects/core/components/expand/expand.template.html, projects/demo-integrations/cypress/tests/addon-charts/line-chart.spec.ts, projects/demo-integrations/cypress/tests/addon-charts/pie-chart.spec.ts, projects/demo/src/modules/components/tree/examples/5/content.ts, projects/demo/src/modules/directives/dropdown-context/dropdown-context.component.html, projects/kit/components/action/action.template.html, projects/kit/components/breadcrumbs/breadcrumbs-wrapper.template.html, projects/kit/components/files/file/file.template.html, projects/kit/components/input-file/file/file.template.html, projects/kit/components/input-tag/input-tag.template.html, projects/kit/components/multi-select-option/multi-select-option.template.html, projects/kit/components/select-option/select-option.template.html, projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html, projects/kit/components/tree/components/tree-item-content/tree-item-content.template.html
=> fix(addon-charts): use ng-container[ngTemplateOutlet] instead of structural directive

.github/actions/nodejs/action.yml
=> ci: add additional logs for improve debugging

.github/workflows/e2e.yml
=> ci: skip e2e for v3.x branch

projects/demo/src/modules/app/stackblitz/project-files/configs.md, projects/demo/tsconfig.app.json, tsconfig.json
=> feat!: enable ivy by default

.github/workflows/deploy-next.yml
=> ci: save demo-next for pre-release branch and main

.github/screenshot-bot.config.toml
=> ci: ignore v3+ branches for screenshot bot

projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less, projects/core/components/primitive-textfield/value-decoration/value-decoration.template.html, projects/demo-integrations/cypress/tests/kit/input-time/input-time.spec.ts, projects/kit/components/input-number/input-number.component.ts, projects/kit/components/input-number/test/input-number.component.spec.ts
=> fix(core): align to baseline value decoration postfix

projects/addon-doc/src/public-api.ts, projects/addon-editor/components/toolbar-tools/details/index.ts
=> fix!: exported from the top-level library entrypoint for compat ivy

.github/workflows/autorebase.yml
=> ci: autorebase to dependent branches

projects/core/components/link/link.style.less, projects/demo/src/modules/components/link/examples/4/index.html, projects/demo/src/modules/components/link/examples/4/index.less, projects/demo/src/modules/components/link/examples/4/index.ts, projects/demo/src/modules/components/link/link.component.ts, projects/demo/src/modules/components/link/link.module.ts, projects/demo/src/modules/components/link/link.template.html
=> fix(core): `tuiLink` mustn't break inline model for anchors

.github/actions/nodejs/action.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-release.yml, .github/workflows/deploy-next.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml
=> ci: fix concurrency problem

.github/actions/rebase/action.yml, .github/workflows/autorebase-v3.yml
=> ci: decomposition rebase

projects/addon-editor/styles/editor-socket.css, projects/demo-integrations/cypress/support/editor/helpers.ts, projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts
=> fix(addon-editor): customize text color in dark/light mode

projects/addon-editor/components/toolbar-tools/font-size/font-size.component.ts, projects/addon-editor/components/toolbar-tools/font-size/font-size.template.html, projects/addon-editor/interfaces/editor-font-option.ts
Closes #2075 
improved ui for display headers
=> fix(addon-editor): improve ui/ux for font-size component

projects/addon-editor/constants/tiptap-editor-styles.ts, projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts, projects/demo/src/modules/components/editor-new/examples/1/index.html, projects/demo/src/modules/components/editor-new/examples/1/index.ts
=> fix(addon-editor): support styles without paragraph for lists

.github/workflows/build.yml, .github/workflows/lint.yml
=> ci: support some workflows when target is any bases branch

projects/demo-integrations/cypress/support/shared.entities.ts, projects/demo-integrations/cypress/support/visit.ts, projects/demo-integrations/cypress/tests/kit/input-tag/input-tag.spec.ts
See https://github.com/Tinkoff/taiga-ui/pull/2119
=> chore(demo-integrations): improve stability of cypress tests

.github/workflows/build.yml
=> ci: fix problem with build workflow

projects/cdk/schematics/ng-update/index.ts, projects/cdk/schematics/ng-update/steps/migrate-date-time.ts, projects/cdk/schematics/ng-update/steps/migrate-progress.ts, projects/cdk/schematics/ng-update/steps/migrate-sliders/index.ts, projects/cdk/schematics/ng-update/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/steps/miscellaneous.ts, projects/cdk/schematics/ng-update/steps/remove-module.ts, projects/cdk/schematics/ng-update/steps/rename-types.ts, projects/cdk/schematics/ng-update/steps/replace-const.ts, projects/cdk/schematics/ng-update/steps/replace-deep-import.ts, projects/cdk/schematics/ng-update/steps/replace-enums.ts, projects/cdk/schematics/ng-update/steps/replace-functions.ts, projects/cdk/schematics/ng-update/steps/replace-services.ts, projects/cdk/schematics/utils/colored-log.ts
=> ci: improve logs for schematics

projects/demo-integrations/cypress/tests/kit/input-number/input-number.spec.ts, projects/demo/src/modules/components/input-number/input-number.component.ts, projects/demo/src/modules/components/input-number/input-number.template.html
=> chore: add example for aligning content to API page

projects/demo-integrations/cypress/support/visit.ts, projects/demo-integrations/cypress/tests/addon-table/table-pagination/table-pagination.spec.ts, projects/demo-integrations/cypress/tests/kit/input-number/input-number.spec.ts, projects/demo-integrations/cypress/tests/kit/input/input.spec.ts, projects/demo-integrations/cypress/tests/kit/line-clamp/line-clamp.spec.ts
=> ci: use `encodeURI` by default in `tuiVisit`

projects/kit/components/line-clamp/index.ts, projects/kit/components/line-clamp/line-clamp-options.ts, projects/kit/components/line-clamp/line-clamp.component.ts
=> feat(kit): `LineClamp` add `showHint` input add `overflowChange` output

projects/demo-integrations/cypress/tests/core/dialogs/dialog-browser-back.spec.ts, projects/demo-integrations/cypress/tests/kit/line-clamp/line-clamp.spec.ts, scripts/eslint/cypress.js
=> chore(eslint): use `tuiVisit` instead of `visit` (cypress tests)

projects/addon-editor/abstract/editor-adapter.abstract.ts, projects/addon-editor/components/toolbar-tools/list-configs/list-configs.component.ts, projects/addon-editor/components/toolbar-tools/list-configs/list-configs.template.html, projects/addon-editor/constants/tiptap-editor-styles.ts, projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts, projects/addon-editor/extensions/indent-outdent.ts, projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts, projects/demo/src/modules/components/editor-new/examples/1/index.html, projects/demo/src/modules/components/editor-new/examples/1/index.ts
=> fix(addon-editor): support nested bullet list

projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.style.less, projects/addon-mobile/components/mobile-calendar/mobile-calendar.style.less, projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.style.less, projects/addon-mobile/directives/sidebar/sidebar.style.less, projects/addon-mobile/internal/primitive-calendar-mobile/primitive-calendar-mobile.style.less, projects/cdk/components/dialog-host/dialog-host.style.less, projects/core/components/dialog/dialog.style.less, projects/demo/src/modules/components/preview/examples/2/index.less, projects/demo/src/modules/components/sheet/examples/5/index.less, stylelint.config.js
=> fix(core): changed `vw/vh` to `percentage` for correct ensure viewport in safari

projects/demo/src/modules/markup/icons/icons.tokens.ts, projects/kit/components/line-clamp/line-clamp.component.ts
=> chore(demo): improved ux for icons page

projects/cdk/schematics/constants/taiga-styles.ts, projects/cdk/schematics/ng-add/steps/add-taiga-icons.ts, projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts, projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts, projects/cdk/schematics/ng-update/index.ts, projects/cdk/schematics/ng-update/tests/schematic-date-time.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-migrate-progress.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-migrate-sliders.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-miscellaneous.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-rename-types.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-consts.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-deep-imports.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-deprecated-functions.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-enums.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-functions.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-replace-services.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-textfield-icon.spec.ts, projects/cdk/schematics/ng-update/tests/schematic-warnings.spec.ts, projects/cdk/schematics/utils/add-styles.ts, projects/cdk/schematics/utils/create-angular-json.ts, projects/core/styles/taiga-ui-fonts.less, projects/core/styles/taiga-ui-theme.less, projects/demo/src/modules/app/app.style.less, projects/demo/src/modules/app/home/examples/angular-json-styles.md
=> refactor!: move fonts to separate file

projects/core/components/root/root.style.less, projects/core/styles/mixins/wrapper.less, projects/kit/components/tabs/tab/tab.style.less
=> chore: small style changes

projects/demo/src/modules/app/utils/example-content-processor/less-processor.ts
=> chore(demo): fix Less-files in examples

package.json
=> ci: should throw error instead of fix on CI

projects/addon-editor/abstract/editor-adapter.abstract.ts, projects/addon-editor/components/toolbar-tools/font-size/font-size.component.ts, projects/addon-editor/components/toolbar-tools/font-size/font-size.template.html, projects/addon-editor/constants/default-font-options-handler.ts, projects/addon-editor/constants/index.ts, projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts, projects/addon-editor/extensions/default-editor-extensions.ts, projects/addon-editor/extensions/font-size.ts, projects/addon-editor/extensions/index.ts, projects/addon-editor/tokens/editor-options.ts, projects/demo-integrations/cypress/tests/addon-editor/editor-new.spec.ts, projects/i18n/interfaces/language.ts, projects/i18n/languages/dutch/addon-editor.ts, projects/i18n/languages/english/addon-editor.ts, projects/i18n/languages/french/addon-editor.ts, projects/i18n/languages/german/addon-editor.ts, projects/i18n/languages/italian/addon-editor.ts, projects/i18n/languages/polish/addon-editor.ts, projects/i18n/languages/portuguese/addon-editor.ts, projects/i18n/languages/russian/addon-editor.ts, projects/i18n/languages/spanish/addon-editor.ts, projects/i18n/languages/turkish/addon-editor.ts, projects/i18n/languages/ukrainian/addon-editor.ts, projects/i18n/languages/vietnamese/addon-editor.ts
=> feat(addon-editor): support customization font-size

projects/core/components/dialog/dialog.template.html, projects/demo-integrations/cypress/support/wait-kit-dialog.ts, projects/demo-integrations/cypress/tests/core/dialogs/dialogs.spec.ts, projects/demo/src/modules/components/dialog/examples/1/index.html, projects/demo/src/modules/components/dialog/examples/1/index.ts, projects/kit/components/line-clamp/line-clamp.component.ts
=> feat(core): customization default text to button in dialog

projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.style.less
=> fix(addon-mobile): replaced `percentages` to `vh` for prevent regression

.eslintrc.js, package-lock.json, package.json, projects/demo/src/modules/components/select/examples/9/account/my-account.component.ts, scripts/eslint/decorators.js
=> ci: each decorator will be on a different line

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-release.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/test.yml
=> ci: use `ref_name` instead `head_ref`

projects/demo-integrations/cypress/tests/kit/tabs/tabs.spec.ts, projects/demo/src/modules/components/tabs/examples/5/index.less, projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
=> fix(kit): clamp activeIndex for `tabs-with-more`

projects/demo-integrations/cypress/tests/addon-doc/code.spec.ts
=> chore(demo-integrations): new cypress tests for code blocks
