taiga-family/taiga-ui

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/create-release.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
This reverts commit 580c6de2ab5524f1533b8f3d46ffc271227befc6.
> Revert "ci: use `ref_name` instead `head_ref` (#2155)"

- angular.json
- package-lock.json
- package.json
- projects/addon-doc/src/utils/raw-load.ts
- projects/demo/src/modules/app/utils/example-content-processor/less-processor.ts
- projects/demo/src/modules/components/group/group.component.ts
- projects/demo/src/typings.d.ts
- projects/demo/webpack.config.ts
> refactor(demo): replace `raw-loader` with Webpack 5 asset modules

- projects/demo-integrations/cypress/support/commands.ts
- projects/demo-integrations/cypress/support/wait-code-highlight.ts
- projects/demo-integrations/cypress/tests/addon-doc/code.spec.ts
> chore: flaky cypress tests

- projects/cdk/schematics/ng-update/steps/migrate-polymorpheus.ts
- projects/cdk/schematics/ng-update/steps/migrate-templates.ts
- projects/cdk/schematics/ng-update/tests/schematic-migrate-polymorpheus.spec.ts
- projects/cdk/schematics/utils/replace-tag.ts
- projects/cdk/schematics/utils/templates/elements.ts
> chore(cdk): polymorpheus migrations

- projects/addon-preview/components/preview/zoom/preview-zoom.component.ts
- projects/addon-preview/components/preview/zoom/preview-zoom.style.less
- projects/addon-preview/components/preview/zoom/preview-zoom.template.html
- projects/demo/src/modules/app/landing/landing.template.html
- projects/demo/src/modules/directives/media/examples/2/index.html
- projects/demo/src/modules/directives/media/examples/3/index.html
> refactor(addon-preview): `PreviewZoom` replace legacy `Slider` with new one

- .github/workflows/lint.yml
> ci: prevent override sha of commits

- projects/cdk/schematics/ng-add/constants/modules.ts
- projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts
- projects/taiga-schematics/schematics/ng-add/constants/modules.ts
- projects/taiga-schematics/schematics/ng-add/tests/ng-add.spec.ts
> fix(cdk, schematics): add BrowserAnimationsModule before TuiRootModule

- projects/addon-doc/src/components/example/example.component.ts
https://user-images.githubusercontent.com/12021443/180395147-da64ecd8-3761-4b6a-8475-56737066d9a8.mov
> feat(addon-doc): set fragment to url when copy link

- projects/core/components/button/button.style.less
> fix(core): add more customization for `font-size` in buttons

- angular.json
> ci: fix dependency graph for testing package

- projects/demo/src/typings.d.ts
> chore: missing changes after rebasing

- projects/kit/components/input-files/input-files.module.ts
> chore(kit): export files module from input-files

- projects/cdk/schematics/ng-update/constants/consts.ts
- projects/cdk/schematics/ng-update/constants/modules.ts
- projects/cdk/schematics/ng-update/constants/templates.ts
- projects/cdk/schematics/ng-update/constants/warnings.ts
Part of https://github.com/Tinkoff/taiga-ui/issues/1764
> chore(cdk): `schematics` proprietary migrations

- projects/core/components/alert/alert.style.less
> fix(core): redundant width by `desktop-m-min` for alerts

- projects/i18n/languages/chinese/addon-commerce.ts
- projects/i18n/languages/chinese/addon-editor.ts
- projects/i18n/languages/chinese/addon-preview.ts
- projects/i18n/languages/chinese/addon-table.ts
- projects/i18n/languages/chinese/chinese.ts
- projects/i18n/languages/chinese/core.ts
- projects/i18n/languages/chinese/kit.ts
> chore(i18n): use actual types

- .github/workflows/autorebase-v3.yml
- .github/workflows/autorebase.yml
- projects/i18n/languages/chinese/countries.ts
- projects/i18n/languages/chinese/index.ts
> ci: should be fail if it has conflicts

- projects/addon-commerce/components/money/money.component.ts
- projects/addon-commerce/components/money/test/money.component.spec.ts
- projects/addon-commerce/components/money/utils/format-sign-symbol.ts
- projects/addon-commerce/types/money-sign.ts
- projects/cdk/constants/unicode-chars.ts
- projects/kit/components/input-month-range/input-month-range.component.ts
- projects/kit/components/input-month-range/test/input-month-range.component.spec.ts
> fix(addon-commerce): incorrect punctuation marks

- projects/demo/src/modules/components/range/examples/3/index.html
- projects/demo/src/modules/components/range/examples/4/index.html
- projects/demo/src/modules/components/range/range.component.ts
- projects/demo/src/modules/components/range/range.template.html
- projects/kit/components/range/range.component.ts
- projects/kit/components/range/range.module.ts
- projects/kit/components/range/range.style.less
- projects/kit/components/range/range.template.html
> feat!: `Range` remove deprecated API for labels of segments

- projects/i18n/enums/country-iso-code.ts
- projects/i18n/languages/dutch/countries.ts
- projects/i18n/languages/english/countries.ts
- projects/i18n/languages/french/countries.ts
- projects/i18n/languages/italian/countries.ts
- projects/i18n/languages/polish/countries.ts
- projects/i18n/languages/portuguese/countries.ts
- projects/i18n/languages/russian/countries.ts
- projects/i18n/languages/spanish/countries.ts
- projects/i18n/languages/vietnamese/countries.ts
- projects/kit/components/input-phone-international/const/countries.ts
> feat(i18n): add `Republic of Kosovo` code

- projects/i18n/languages/chinese/countries.ts
> chore: fix failure build

- projects/i18n/languages/russian/addon-editor.ts
> fix(i18n): translated some fields for `addon-editor`

- projects/demo/src/modules/app/pages.ts
```
AssertionError:
Timed out retrying after 10000ms: expected 'http://localhost:3333/' to include 'components/toolbar'
```
> chore: fix cypress tests (toolbar page problem)

- projects/demo/src/modules/components/hosted-dropdown/examples/4/index.html
- projects/demo/src/modules/components/hosted-dropdown/examples/4/index.less
- projects/demo/src/modules/components/hosted-dropdown/examples/4/index.ts
- projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.module.ts
> chore(demo): add example in `hosted-dropdown`

- projects/demo/src/typings.d.ts
- projects/demo/webpack.config.ts
> chore(demo): `?raw` fix typings

- projects/demo/src/modules/tables/table-filters/table-filters.component.ts
- projects/demo/src/modules/tables/table-filters/table-filters.module.ts
[Failed job](https://github.com/Tinkoff/taiga-ui/runs/7539669040?check_suite_focus=true)
> chore(demo): fix build

- projects/addon-editor/components/editor-new/editor-new.component.ts
- projects/addon-editor/tokens/editor-processor.ts
- projects/addon-editor/tokens/index.ts
- projects/addon-editor/utils/index.ts
- projects/addon-editor/utils/legacy-converter.ts
- projects/addon-editor/utils/test/legacy-converter.spec.ts
- projects/demo/src/modules/components/editor-new/editor-new.component.ts
- projects/demo/src/modules/components/editor-new/editor-new.module.ts
- projects/demo/src/modules/components/editor-new/editor-new.template.html
- projects/demo/src/modules/components/editor-new/examples/5/index.html
- projects/demo/src/modules/components/editor-new/examples/5/index.less
- projects/demo/src/modules/components/editor-new/examples/5/index.ts
> feat(addon-editor): add `TUI_EDITOR_CONTENT_PROCESSOR`

- projects/cdk/directives/auto-focus/autofocus.options.ts
`useClass` doesn't work for this case
> chore: remove redundant `TODO`

- projects/addon-editor/extensions/default-editor-extensions.ts
- projects/addon-editor/extensions/index.ts
- projects/addon-editor/extensions/starter-kit/index.ts
- projects/addon-editor/extensions/starter-kit/package.json
- projects/addon-editor/extensions/starter-kit/starter-kit.ts
- projects/demo/src/modules/components/editor-new/examples/2/index.ts
- projects/demo/src/modules/components/editor-new/examples/3/index.ts
- projects/demo/src/modules/components/editor-new/examples/4/index.ts
> chore(addon-editor): move starter-kit extension

- .github/workflows/create-release.yml
> chore(ci): fix workflow

- scripts/shared/check-changelog-before-push.ts
> chore(ci): fix script type

- scripts/shared/overwrite-version.ts
> ci: compat for eslint

- projects/cdk/schematics/ng-update/constants/services.ts
- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/steps/migrate-templates.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-services.spec.ts
- projects/cdk/schematics/utils/add-import-to-closest-module.ts
- projects/cdk/schematics/utils/add-styles.ts
- projects/cdk/schematics/utils/templates/ng-component-input-manipulations.ts
> chore(cdk): some schematic fixes

- projects/demo-integrations/cypress/tests/kit/input-slider/input-slider.spec.ts
- projects/kit/components/input-slider/input-slider.component.ts
- projects/kit/components/input-slider/input-slider.template.html
- projects/kit/components/input-slider/test/input-slider.component.spec.ts
See https://github.com/Tinkoff/taiga-ui/pull/2225
> chore(kit): `InputSlider` sync `main` and `v3.x` branches

- projects/addon-editor/components/edit-link/edit-link.component.ts
- projects/addon-editor/components/editor/editor.component.html
- projects/addon-editor/components/editor/editor.component.ts
- projects/addon-editor/components/editor/editor.style.less
- projects/addon-editor/tokens/index.ts
- projects/cdk/utils/dom/index.ts
- projects/cdk/utils/dom/is-element.ts
- projects/kit/directives/dropdown-selection/dropdown-selection.directive.ts
> chore(addon-editor): `editor` sync `main` and `v3.x` branches

- CHANGELOG.md
- scripts/shared/overwrite-version.ts
> chore: sync `v2.56.0` with `main` branch

- projects/cdk/schematics/ng-add/steps/add-taiga-icons.ts
- projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts
- projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts
- projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts
- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/steps/replace-functions.ts
- projects/cdk/schematics/utils/add-styles.ts
- projects/cdk/schematics/utils/get-project.ts
> chore(cdk): some more schematic fixes

- projects/demo-integrations/cypress/support/editor/helpers.ts
- projects/demo-integrations/cypress/support/visit.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-new-links.spec.ts
- projects/demo-integrations/cypress/tests/addon-icons/customization-icons.spec.ts
- projects/demo-integrations/cypress/tests/core/hint/hint.spec.ts
> ci: prevent flaky tests

- .github/workflows/create-release.yml
> chore: remove redundant line in main branch

- projects/addon-charts/components/bar-chart/bar-chart.component.ts
- projects/addon-charts/components/line-chart/line-chart.component.ts
- projects/addon-commerce/components/card/card.component.ts
- projects/cdk/directives/media/media.directive.ts
- projects/kit/components/pagination/pagination.component.ts
- projects/kit/components/progress/progress-segmented/progress-segmented.component.ts
> refactor!: remove redundant exports of internal functions (reduction of public API)

- projects/demo-integrations/cypress/tests/kit/line-clamp/line-clamp.spec.ts
- projects/demo/src/modules/components/line-clamp/line-clamp.component.ts
- projects/demo/src/modules/components/line-clamp/line-clamp.template.html
- projects/kit/components/line-clamp/line-clamp.module.ts
- projects/kit/components/line-clamp/line-clamp.style.less
- projects/kit/components/line-clamp/line-clamp.template.html
> fix(kit): use `break-all` for `LineClamp`

- nx.json
- package-lock.json
- package.json
> ci: back is Nx Cloud

- .github/workflows/build.yml
- .github/workflows/deploy-next.yml
- .github/workflows/deploy.yml
- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
> ci: token for Nx Cloud

- projects/demo/src/modules/app/classes/ts-file-component.parser.ts
Open stackblitz of any example.
For example:
https://taiga-ui.dev/components/input-slider#base
Error:
```
Import error, can't find file:
./index.html
```
No error
> chore(demo): `stackblitz` add `backtick` support

- projects/kit/components/slider/helpers/slider-key-steps.directive.ts
- projects/kit/components/slider/helpers/tokens.ts
- projects/kit/components/slider/slider.component.ts
> fix(kit): `Slider` incorrect calculations with `[ngModel]` + `[keySteps]`

- projects/core/styles/mixins/mixins.less
- projects/demo/src/modules/components/input-card-grouped/examples/2/index.html
- projects/demo/src/modules/components/input-card-grouped/examples/2/index.ts
> fix(core): card number overlay after autofill in dark theme

- projects/cdk/schematics/ng-update/constants/consts.ts
- projects/cdk/schematics/ng-update/constants/templates.ts
- projects/cdk/schematics/ng-update/steps/migrate-templates.ts
- projects/cdk/schematics/ng-update/tests/schematic-migrate-hints.spec.ts
> chore(cdk): add hint migration

- projects/core/components/primitive-textfield/primitive-textfield.style.less
- projects/core/components/primitive-textfield/primitive-textfield.template.html
- projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts
> fix(cdk): correct autofill value for input controls

- projects/cdk/directives/autofilled/autofilled.style.less
- projects/core/enums/appearance.ts
- projects/core/styles/theme/wrapper.less
- projects/core/styles/theme/wrapper/secondary-destructive.less
- projects/demo/src/modules/components/button/button.component.ts
- projects/demo/src/modules/components/button/examples/2/index.html
> feat(core): `Button` add `secondary-destructive` appearance

- projects/demo/src/modules/app/app.providers.ts
- projects/demo/src/modules/app/app.tabs.ts
> chore(demo): prevent compile `i18n/esm2015/*` in proprietary

- projects/core/styles/markup/tui-table.less
- projects/demo/src/modules/markup/tables/examples/1/index.html
> feat(core): add round corners to paddingless tables

- projects/demo-integrations/cypress/support/commands.ts
- projects/demo-integrations/cypress/support/hide-doc-page.ts
- projects/demo-integrations/cypress/tests/addon-doc/code.spec.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-new-groups.spec.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-new-img.spec.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-new-links.spec.ts
- projects/demo-integrations/cypress/tests/addon-table/table-pagination/table-pagination.spec.ts
> ci: fix e2e flaky again

- projects/addon-commerce/enums/currency-code.ts
- projects/addon-commerce/enums/currency.ts
- projects/cdk/constants/unicode-chars.ts
> feat: new unicode symbols + add description for Mexican peso

- projects/i18n/index.ts
> chore: forgot add export for some i18n tokes

- .github/actions/cypress/action.yml
- .github/workflows/e2e.yml
- nx.json
> ci: improved e2e workflow

- projects/i18n/switch/language-switcher.providers.ts
- projects/i18n/switch/language-switcher.service.ts
- projects/i18n/tokens/index.ts
- projects/i18n/tokens/language.ts
- projects/i18n/tools/extract-i18n.ts
- projects/i18n/tools/index.ts
> refactor!: move some i18n tokens to secondary package

- projects/addon-doc/src/components/navigation/navigation.template.html
- projects/cdk/date-time/day.ts
- projects/cdk/date-time/month.ts
- projects/cdk/date-time/test/day.spec.ts
- projects/cdk/date-time/test/month.spec.ts
- projects/cdk/date-time/test/year.spec.ts
- projects/cdk/date-time/year.ts
- projects/cdk/directives/auto-focus/autofocus.directive.ts
- projects/cdk/directives/auto-focus/test/auto-focus.directive.spec.ts
- projects/core/components/data-list/option/option.component.ts
- projects/core/pipes/calendar-sheet/utils.ts
- projects/core/styles/theme/variables.less
- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/kit/constants/max-day-range-length-mapper.ts
- projects/kit/interfaces/bread-crumbs-item.ts
- projects/kit/interfaces/index.ts
> refactor!: remove deprecated entities

- projects/demo-integrations/cypress/support/editor/helpers.ts
- projects/demo-integrations/cypress/support/shared.entities.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-new-api.spec.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-new-groups.spec.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-new-links.spec.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-new-toolbar.spec.ts
> ci: refactor some e2e tests for prevent flaky behaviour

- angular.json
- scripts/publish.ts
- scripts/shared/run-standard-verion.ts
> ci: add publish script

- projects/addon-mobile/directives/sidebar/sidebar.directive.ts
- projects/cdk/abstract/portal-host.ts
- projects/cdk/abstract/portal-service.ts
- projects/cdk/components/dropdown-host/test/dropdown-portal.service.spec.ts
- projects/core/abstract/abstract-dropdown.ts
- projects/core/directives/dropdown/dropdown.directive.ts
- projects/demo/src/typings.d.ts
- projects/kit/directives/dropdown-context/dropdown-context.directive.ts
- projects/kit/directives/dropdown-selection/dropdown-selection.directive.ts
- projects/kit/directives/project-class/project-class.directive.ts
> feat(cdk)!: PortalService switch to using PolymorpheusComponent

- projects/kit/components/input-slider/input-slider.template.html
- projects/kit/components/slider/helpers/slider-key-steps.directive.ts
- projects/kit/types/test/key-steps.spec.ts
> refactor(kit)!: `Slider[keySteps]` update control value on `input` event (+ delete `keyStepsInput`)

- projects/demo-integrations/cypress/tests/kit/dropdown-selection/dropdown-selection.spec.ts
- projects/kit/directives/dropdown-selection/dropdown-selection.directive.ts
> fix(kit): current range must be a text node only

- projects/demo/src/modules/info/changelog/changelog.style.less
> chore(demo): `Changelog` fix header font + small customization upgrade

- projects/demo-integrations/cypress/tests/addon-editor/editor-new-api.spec.ts
> ci: prevent flaky

- projects/core/components/data-list/data-list.module.ts
- projects/core/components/data-list/index.ts
- projects/demo/src/modules/components/data-list/data-list.module.ts
- projects/demo/src/modules/components/data-list/data-list.template.html
- projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts
- projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.module.ts
- projects/kit/directives/data-list-dropdown-manager/index.ts
- projects/kit/directives/data-list-dropdown-manager/package.json
- projects/kit/directives/index.ts
> feat(kit)!: `DataListDropdownManager` move into separate module

- projects/addon-commerce/components/money/pipes/integer-part.pipe.ts
- projects/cdk/schematics/ng-update/steps/migrate-templates.ts
- projects/cdk/schematics/ng-update/steps/replace-functions.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-functions.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
- projects/cdk/schematics/utils/insert-todo.ts
- projects/core/constants/default-number-format.ts
- projects/core/constants/index.ts
- projects/core/interfaces/number-format-settings.ts
- projects/core/pipes/format-number/format-number.pipe.ts
- projects/core/tokens/number-format.ts
- projects/core/utils/format/format-number.ts
- projects/core/utils/format/test/format-number.spec.ts
- projects/demo/src/modules/pipes/format-number/examples/1/index.html
- projects/demo/src/modules/pipes/format-number/format-number.component.ts
- projects/demo/src/modules/pipes/format-number/format-number.template.html
- projects/demo/src/modules/utils/format/examples/6/index.ts
- projects/kit/components/input-count/input-count.component.ts
- projects/kit/components/input-number/input-number.component.ts
**Utility:**
```ts
function tuiFormatNumber(
value: number,
decimalLimit: number | null = null,
decimalSeparator: string = `,`,
thousandSeparator: string = CHAR_NO_BREAK_SPACE,
zeroPadding: boolean = true,
): string;
```
**Pipe:**
```html
<p>Formatted number: {{ 10500.33 | tuiFormatNumber: 4:'.' }}</p>
```
**Utility:**
```ts
function tuiFormatNumber(
value: number,
{
decimalLimit = null,
decimalSeparator = `,`,
thousandSeparator = CHAR_NO_BREAK_SPACE,
zeroPadding = true,
}: Partial<TuiNumberFormatSettings> = {},
): string
```
**Pipe:**
```html
<p>Formatted number: {{ 10500.33 | tuiFormatNumber: {decimalLimit: 4, decimalSeparator: '.'} }}</p>
```
> refactor(core)!: `tuiFormatNumber(value, configs)` new function signature

- projects/core/styles/markup/tui-skeleton.less
> fix(core): replace hardcoded skeleton color with css variable

- projects/cdk/package.json
> chore(cdk): add proprietary package to ng-update package group

- package.json
> ci: prevent some problems when use proprietary workspace

- projects/addon-editor/components/toolbar-tools/align-content/align-content.template.html
- projects/addon-editor/components/toolbar-tools/font-style/font-style.module.ts
- projects/addon-editor/components/toolbar-tools/font-style/font-style.template.html
- projects/addon-editor/components/toolbar-tools/list-configs/list-configs.template.html
- projects/addon-editor/components/toolbar-tools/table-merge-cells/table-merge-cells.template.html
- projects/kit/components/input-password/input-password.module.ts
- projects/kit/components/input-password/input-password.template.html
> fix: prevent emit `null` for editor

- projects/kit/directives/lazy-loading/lazy-loading.directive.ts
- projects/kit/directives/lazy-loading/test/lazy-loading.directive.spec.ts
> fix(kit): support dark-theme for `TuiLazyLoadingDirective`

- .github/workflows/e2e.yml
- projects/demo/project.json
- projects/demo/tsconfig.app.json
- projects/demo/tsconfig.server.json
Run
```
nx serve-ssr demo
```
it produces error and fails
See this issue.
Closes #2323
No build failure.
> chore(demo): ssr build errors

- projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
- projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less
- projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html
> fix(kit): `Tabs` fix opening dropdown on clicking margin area

- projects/core/styles/theme/wrapper.less
- projects/core/styles/theme/wrapper/mono.less
- projects/demo/src/modules/components/button/button.component.ts
> feat(core): `Button` add `mono` style

- projects/cdk/schematics/ng-update/steps/migrate-progress.ts
- projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-range.ts
- projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-slider.ts
- projects/cdk/schematics/ng-update/steps/replace-deep-import.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-deep-imports.spec.ts
- projects/cdk/schematics/utils/angular/ng-module.ts
> fix(cdk): don't override deep imports inside less files

- projects/demo/src/modules/app/app.routes.ts
> chore(demo): fix import

- package-lock.json
- projects/cdk/package.json
- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/steps/migrate-progress.ts
- projects/cdk/schematics/ng-update/steps/migrate-sliders/index.ts
- projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-range.ts
- projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-slider.ts
- projects/cdk/schematics/ng-update/steps/migrate-templates.ts
- projects/cdk/schematics/utils/angular/ng-component.ts
- projects/cdk/schematics/utils/angular/ng-module.ts
- projects/cdk/schematics/utils/templates/get-component-templates.ts
- projects/cdk/schematics/utils/templates/ng-component-input-manipulations.ts
- projects/cdk/schematics/utils/templates/template-resource.ts
- projects/taiga-schematics/package.json
> chore: bump ng-morph

- projects/demo-integrations/cypress/support/shared.entities.ts
- projects/demo-integrations/cypress/tests/addon-doc/viewport.spec.ts
- projects/demo/src/modules/markup/breakpoints/examples/1/index.less
- projects/demo/src/modules/markup/breakpoints/examples/1/index.ts
**01-breakpoints-767-900-mobile-viewport:**
**02-breakpoints-768-900-tablet-viewport:**
**03-breakpoints-1023-900-tablet-viewport:**
**04-breakpoints-1024-900-desktop-s-viewport:**
**05-breakpoints-1279-900-desktop-s-viewport:**
**06-breakpoints-1280-900-desktop-m-viewport:**
> chore(demo): `Breakpoints` documentation page updates

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
- projects/core/styles/mixins/mixins.less
> fix(core): set transparent of autofill only for bank cards

- scripts/shared/bump-tui-deps.ts
- scripts/shared/sync-versions.ts
- scripts/shared/update-package-json-structure.ts
> ci: prevent override range in peerDependencies

- projects/core/styles/variables/media-old.less
- projects/core/styles/variables/media.less
- projects/core/styles/variables/media.scss
> fix(core): css media breakpoints correction (edge cases)

- package.json
- scripts/nx/decorate-angular-cli.ts
- scripts/postinstall.ts
> ci: add `nx` facade for `ng` cli

- projects/demo-integrations/cypress/support/hide-header.ts
- projects/demo-integrations/cypress/support/hide-language-switcher.ts
- projects/demo-integrations/cypress/support/hide-navigation.ts
- projects/demo-integrations/cypress/support/hide-version-manager.ts
- projects/demo-integrations/cypress/support/visit.ts
- projects/demo/src/modules/app/abstract.app.ts
- projects/demo/src/modules/app/app.component.ts
- projects/demo/src/modules/app/theme.service.ts
> chore(demo): reuse app logic for proprietary demo

- projects/addon-commerce/enums/currency-code.ts
- projects/addon-commerce/enums/currency.ts
ЗАДАЧА(И): #RKOACCOUNTS-565
- [ +] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ +] Feature
Не хватает кодов валют
Closes # 
Хватает кодов валют
- [ +] No
> feat(addon-commerce): added `UZS`, `KGS`, `AED`

- projects/taiga-schematics/project.json
> ci: improved cache processing for taiga-schematics project

- projects/addon-tablebars/components/table-bars-host/table-bars-host.template.html
- projects/cdk/constants/parent-animation.ts
> fix(cdk): `ParentAnimation` properly query direct child

- projects/cdk/schematics/constants/file-globs.ts
- projects/cdk/schematics/constants/index.ts
- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/steps/migrate-progress.ts
- projects/cdk/schematics/ng-update/steps/migrate-sliders/index.ts
- projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-range.ts
- projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-slider.ts
- projects/cdk/schematics/ng-update/steps/migrate-templates.ts
- projects/cdk/schematics/ng-update/steps/replace-deep-import.ts
- projects/cdk/schematics/ng-update/steps/replace-enums.ts
- projects/cdk/schematics/ng-update/steps/show-warnings.ts
- projects/cdk/schematics/utils/angular/ng-module.ts
- projects/cdk/schematics/utils/get-named-import-references.ts
- projects/cdk/schematics/utils/templates/get-component-templates.ts
> chore(cdk): `schematics` backtick problem + exclude schematic and typing-files

- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/steps/migrate-date-time.ts
- projects/cdk/schematics/ng-update/steps/migrate-templates.ts
- projects/cdk/schematics/utils/get-execution-time.ts
- projects/cdk/schematics/utils/progress.ts
> chore(cdk): `schematics` more logs

- projects/cdk/schematics/ng-update/constants/warnings.ts
- projects/core/components/alert/alert.component.ts
- projects/core/components/alert/alert.template.html
- projects/demo/src/modules/services/alerts/alerts.template.html
- projects/demo/src/modules/services/alerts/examples/3/alert-example/alert-example.component.ts
- projects/demo/src/modules/services/alerts/examples/4/alert-example-with-data/alert-example-with-data.component.ts
- projects/demo/src/modules/services/alerts/examples/5/alert-example-with-custom-label/alert-example-with-custom-label.component.ts
- projects/demo/src/modules/services/alerts/examples/import/custom-alert.md
> refactor!: `AlertComponent` use new context

- projects/demo-integrations/cypress/tests/core/data-list/data-list.spec.ts
- projects/demo-integrations/cypress/tests/core/dialogs/dialogs.spec.ts
- projects/demo-integrations/cypress/tests/kit/tabs/tabs.spec.ts
> chore: flaky

- projects/i18n/languages/chinese/countries.ts
- projects/i18n/languages/dutch/countries.ts
- projects/i18n/languages/english/countries.ts
- projects/i18n/languages/french/countries.ts
- projects/i18n/languages/italian/countries.ts
- projects/i18n/languages/polish/countries.ts
- projects/i18n/languages/portuguese/countries.ts
- projects/i18n/languages/russian/countries.ts
- projects/i18n/languages/spanish/countries.ts
- projects/i18n/languages/vietnamese/countries.ts
- projects/kit/components/input-phone-international/const/countries.ts
https://github.com/Tinkoff/taiga-ui/issues/2177
> fix(i18n): rename `Republic of Kosovo` to `Kosovo`

- projects/demo-integrations/cypress.config.ts
> ci: expose config for proprietary repo

- .github/workflows/move-opened-issue.yml
> ci: move new issues into Triage

- projects/demo-integrations/cypress/tests/addon-doc/navigation.spec.ts
> ci: fix flaky

- projects/i18n/README.md
- projects/i18n/interfaces/language-names.ts
- projects/i18n/interfaces/language.ts
> fix(i18n): support typings for custom languages

- projects/cdk/schematics/ng-update/steps/migrate-date-time.ts
- projects/cdk/schematics/ng-update/tests/schematic-date-time.spec.ts
> chore(cdk): `schematics` v3.x migration `RangeError`

- projects/demo/src/modules/info/browsers/browsers.template.html
> feat!: update supported browser versions (bump supported `Safari` to `12.1+`)

- projects/demo/src/modules/components/badge/badge.component.ts
- projects/demo/src/modules/components/badge/examples/2/index.html
- projects/kit/components/badge/badge.component.ts
- projects/kit/components/badge/badge.style.less
- projects/kit/components/badged-content/badged-content.component.ts
- projects/kit/components/badged-content/badged-content.style.less
- projects/kit/components/badged-content/badged-content.template.html
> feat(kit): `Badge` add new `xs` size

- projects/demo-integrations/cypress.config.ts
- projects/demo-integrations/cypress/plugins/index.ts
- projects/demo-integrations/cypress/support/shared.entities.ts
- projects/demo-integrations/cypress/support/visit.ts
- projects/demo-integrations/cypress/tests/addon-preview/addon-preview.spec.ts
- projects/demo-integrations/cypress/tests/core/dialogs/dialog-browser-back.spec.ts
- projects/demo-integrations/cypress/tests/core/dialogs/dialogs.spec.ts
- projects/demo-integrations/cypress/tests/kit/dropdown-context/dropdown-context.spec.ts
- projects/demo-integrations/cypress/tests/kit/multi-select/multi-select.spec.ts
> ci: increase timeout for slow jobs

- projects/cdk/schematics/ng-update/constants/templates.ts
> chore(cdk): `FeedItem` migration

- projects/core/components/primitive-calendar/primitive-calendar.template.html
- projects/core/components/primitive-textfield/value-decoration/value-decoration.template.html
- projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
- projects/kit/components/input-date-time/test/input-date-time.component.spec.ts
- projects/kit/components/input-date/test/input-date.component.spec.ts
- projects/kit/components/input-tag/input-tag.template.html
- projects/kit/components/input-tag/test/input-tag.component.spec.ts
- projects/kit/components/multi-select/test/multi-select.component.spec.ts
> fix(core): use `textContent` instead of `innerText`

- projects/demo/src/modules/app/stackblitz/stackblitz-resources-loader.ts
1. Open https://taiga-ui.dev/components/calendar#base
2. Press button "Edit on stackblitz"
3. Stackblitz throws error:
```py
Error in src/app/styles/theme/wrapper.less (12:0)
Could not import wrapper/mono.less from /~/src/app/styles/taiga-ui-stackblitz.less
```
No error
> chore(demo): `stackblitz` fix error `Could not import wrapper/mono.less`

- projects/cdk/schematics/ng-update/steps/replace-functions.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-deprecated-functions.spec.ts
> chore(cdk): `schematics` migration v3.x code comments causes `Manipulation error`

- scripts/nx/decorate-angular-cli.ts
> ci: npm ci error SyntaxError: Cannot use import statement outside a module

- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/steps/migrate-taiga-proprietary-icons.ts
- projects/cdk/schematics/ng-update/tests/schematic-migrate-tds.spec.ts
> chore(cdk): add schematic for migrate `tds` icons

- projects/core/components/primitive-textfield/primitive-textfield.style.less
- projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less
- projects/core/components/primitive-textfield/value-decoration/value-decoration.template.html
- projects/demo-integrations/cypress/tests/kit/input/input.spec.ts
> fix(core): character descenders overflow the line

- .github/workflows/add-to-project.yml
> ci: fix typo

- projects/cdk/project.json
- projects/cdk/schematics/collection.json
- projects/cdk/schematics/constants/file-globs.ts
- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/schema.json
- projects/taiga-schematics/project.json
- tsconfig.schematics.json
```console
nx postbuild cdk && schematics ./dist/cdk:updateToV3 --allow-private
```
It will run "dry"-mode (you can check that schematics really works but cant see changes).
To see these changes you can run not-dry mode
```console
nx postbuild cdk && schematics ./dist/cdk:updateToV3 --allow-private --dry-run false
```
In most cases you don't need to replace all deep imports (e.g., `@taiga-ui/kit/utils/dom`) inside your libraries.
Use this command:
```console
nx postbuild cdk && schematics ./dist/cdk:updateToV3 --allow-private --dry-run false --skip-deep-imports
```
This command
```console
nx postbuild cdk && schematics ./dist/cdk:updateToV3 --allow-private --skip-deep-imports --dry-run false
```
produces this output
<details>
<summary>Expand very long logs</summary>
```sh
Debug mode …
```
> ci: run schematics via `schematics ./dist/cdk:updateToV3 --allow-private --skip-deep-imports`

- projects/cdk/pipes/index.ts
- projects/cdk/pipes/keys/index.ts
- projects/cdk/pipes/keys/keys.module.ts
- projects/cdk/pipes/keys/keys.pipe.ts
- projects/cdk/pipes/keys/package.json
- projects/demo/src/modules/markup/icons/icons-group/icons-group.component.ts
- projects/demo/src/modules/markup/icons/icons-group/icons-group.directive.ts
- projects/demo/src/modules/markup/icons/icons-group/icons-group.module.ts
- projects/demo/src/modules/markup/icons/icons-group/icons-group.style.less
- projects/demo/src/modules/markup/icons/icons-group/icons-group.template.html
- projects/demo/src/modules/markup/icons/icons.component.ts
- projects/demo/src/modules/markup/icons/icons.module.ts
- projects/demo/src/modules/markup/icons/icons.style.less
- projects/demo/src/modules/markup/icons/icons.template.html
- projects/demo/src/modules/markup/icons/icons.tokens.ts
- projects/demo/src/modules/markup/icons/pipes/icon-highlight.pipe.ts
> chore(demo): improved search in icons page

- projects/cdk/schematics/ng-update/constants/templates.ts
- projects/demo/src/modules/components/stepper/examples/1/index.html
- projects/demo/src/modules/components/stepper/stepper.template.html
- projects/kit/components/stepper/step/step.component.ts
> refactor!: `Stepper` rename `state` input to avoid collision with `routerLink`

- projects/demo-integrations/cypress/tests/kit/dropdown-context/dropdown-context.spec.ts
> chore: remove legacy cypress test

- projects/cdk/constants/index.ts
- projects/cdk/constants/version.ts
- projects/cdk/project.json
- projects/cdk/schematics/ng-add/constants/versions.ts
- projects/core/components/root/root.component.ts
- projects/core/constants/version.ts
- projects/demo/src/modules/app/version-manager/versions.constants.ts
- projects/taiga-schematics/package.json
- projects/taiga-schematics/project.json
- projects/taiga-schematics/schematics/ng-add/constants/versions.ts
- projects/taiga-schematics/tsconfig.schematics.json
- scripts/postbump.ts
- scripts/shared/overwrite-version.ts
- tsconfig.schematics.json
Closes #2413
```
$ rm -rf dist
$ nx test-schematics cdk
```
> feat(cdk): schematics shouldn't be a direct depended on cdk

- projects/demo-integrations/cypress/support/demo-paths.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/info/testing/jest/examples/jest-config-js.md
- projects/demo/src/modules/info/testing/jest/examples/package-json.md
- projects/demo/src/modules/info/testing/jest/examples/setup-jest-js.md
- projects/demo/src/modules/info/testing/jest/jest.component.ts
- projects/demo/src/modules/info/testing/jest/jest.module.ts
- projects/demo/src/modules/info/testing/jest/jest.template.html
Addresses https://github.com/Tinkoff/taiga-ui/issues/2337
I am not sure about the `keywords` part, I saw there was Russian there, I deleted it, I added what I thought could help people Googling the issue to find this page.
There's no documentation for using Jest with Taiga UI
> chore(demo): new Jest setup documentation

- projects/addon-editor/components/toolbar/toolbar-navigation-manager.directive.ts
- projects/cdk/directives/focus-trap/focus-trap.directive.ts
- projects/cdk/schematics/ng-update/constants/deprecated-functions.ts
- projects/cdk/schematics/ng-update/steps/replace-functions.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-consts.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-functions.spec.ts
- projects/cdk/utils/focus/get-closest-focusable.ts
- projects/cdk/utils/focus/index.ts
- projects/cdk/utils/focus/tests/get-closest-keyboard.spec.ts
- projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
- projects/core/directives/dropdown/dropdown.component.ts
- projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
- projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts
> feat(cdk)!: add configuration to `tuiGetClosestFocusableElement`

- projects/cdk/schematics/ng-update/constants/consts.ts
- projects/cdk/schematics/ng-update/constants/templates.ts
- projects/cdk/schematics/ng-update/steps/migrate-templates.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
> chore(cdk): `schematics` v3.x migrations for dropdowns

- scripts/postinstall.ts
> ci: use postinstall script in proprietary repo

- projects/demo/src/modules/markup/icons/icons-group/icons-group.template.html
> chore(demo): provide icon group key

- scripts/postinstall.ts
> ci: fixup postinstall script in proprietary repo

- projects/cdk/schematics/constants/taiga-styles.ts
- projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts
- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/tests/schematic-date-time.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-migrate-hints.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-migrate-polymorpheus.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-migrate-progress.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-migrate-sliders.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-migrate-tds.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-miscellaneous.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-rename-types.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-consts.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-deep-imports.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-deprecated-functions.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-enums.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-functions.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-services.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-styles.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-textfield-icon.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-warnings.spec.ts
- projects/cdk/schematics/utils/add-styles.ts
> chore(cdk): fix migration for global styles

- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/utils/add-styles.ts
> chore: one more migration fix

- projects/cdk/schematics/constants/taiga-styles.ts
- projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts
- projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts
- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/steps/replace-styles.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-deep-imports.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-styles.spec.ts
- projects/demo/src/modules/app/app.style.less
- projects/demo/src/modules/app/home/examples/styles.less.md
- projects/demo/src/modules/app/home/home.component.ts
- projects/demo/src/modules/app/home/home.template.html
- projects/styles/taiga-ui-global.less
- projects/taiga-schematics/schematics/ng-add/steps/add-taiga-styles.ts
- projects/taiga-schematics/schematics/ng-add/tests/ng-add.spec.ts
> chore: update schematics for global styles

- projects/demo-integrations/cypress.config.ts
- projects/demo-integrations/cypress/support/commands.ts
- projects/demo-integrations/cypress/support/hide-doc-page.ts
- projects/demo-integrations/cypress/support/hide-header.ts
- projects/demo-integrations/cypress/support/hide-language-switcher.ts
- projects/demo-integrations/cypress/support/hide-navigation.ts
- projects/demo-integrations/cypress/support/hide-version-manager.ts
- projects/demo-integrations/cypress/support/visit.ts
- projects/demo-integrations/cypress/tests/demo/landing.spec.ts
- projects/demo-integrations/cypress/tests/kit/button/button.spec.ts
- projects/demo-integrations/cypress/tests/kit/combo-box/combo-box.spec.ts
- projects/testing/cypress/commands/wait-all-img-inside.command.ts
- projects/testing/cypress/index.ts
- projects/testing/cypress/snapshot/command.ts
> ci: wait load images inside subject before screenshot

- projects/cdk/schematics/ng-update/steps/migrate-polymorpheus.ts
- projects/cdk/schematics/ng-update/tests/schematic-migrate-polymorpheus.spec.ts
> chore(cdk): fix polymorpheus migration

- projects/cdk/schematics/ng-update/constants/enums.ts
- projects/demo/src/modules/components/dialog/examples/7/search-example/search-dialog-example.template.html
- projects/demo/src/modules/components/select/examples/7/index.html
- projects/demo/src/modules/directives/highlight/examples/1/index.html
- projects/demo/src/modules/directives/highlight/highlight.module.ts
- projects/demo/src/modules/markup/form/example/index.html
- projects/demo/src/modules/pipes/field-error/examples/2/index.html
- projects/demo/src/modules/pipes/format-number/format-number.module.ts
- projects/demo/src/modules/pipes/format-number/format-number.template.html
> refactor(demo): delete some legacy code

- projects/addon-charts/components/pie-chart/pie-chart.component.ts
- projects/demo/src/modules/charts/pie-chart/examples/2/index.html
- projects/demo/src/modules/charts/pie-chart/pie-chart.module.ts
- projects/demo/src/modules/charts/pie-chart/pie-chart.template.html
We already have this test:
https://github.com/Tinkoff/taiga-ui/blob/d26a2e1fbf8c6a2d03f5c4496b7404b527e1b56e/projects/demo-integrations/cypress/tests/addon-charts/pie-chart.spec.ts#L6
`PieChart` behaves in the same way as other charts.
See https://github.com/Tinkoff/taiga-ui/pull/2273
> chore(addon-charts): `PieChart` add `tuiHintContent`-directive support

- projects/cdk/schematics/ng-update/constants/consts.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-proprietary-consts.spec.ts
> chore: add schematics for migrate `proprietary-banking`

- projects/core/components/button/button.component.ts
- projects/core/components/button/button.template.html
> chore(core): `Button` allow dynamic switch of appearance with DI

- package-lock.json
- projects/addon-tablebars/services/table-bars.service.ts
- projects/cdk/observables/index.ts
- projects/cdk/observables/is-observed.ts
- projects/core/components/notification/notification.component.ts
- projects/core/pipes/format-date/format-date.module.ts
- projects/core/pipes/format-date/format-date.pipe.ts
- projects/core/pipes/format-date/index.ts
- projects/core/pipes/format-date/package.json
- projects/core/pipes/index.ts
- projects/core/services/format-date.service.ts
- projects/core/services/index.ts
- projects/demo/package.json
- projects/demo/src/modules/app/app.browser.module.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/pipes/format-date/examples/1/index.html
- projects/demo/src/modules/pipes/format-date/examples/1/index.ts
- projects/demo/src/modules/pipes/format-date/examples/1/service.ts
- projects/demo/src/modules/pipes/format-date/examples/import/import-module.md
- projects/demo/src/modules/pipes/format-date/examples/import/insert-template.md
- projects/demo/src/modules/pipes/format-date/examples/import/provide-service.md
- projects/demo/src/modules/pipes/format-date/format-date.component.ts
- projects/demo/src/modules/pipes/format-date/format-date.module.ts
- projects/demo/src/modules/pipes/format-date/format-date.template.html
- projects/demo/src/modules/pipes/format-number/format-number.template.html
- projects/demo/src/modules/pipes/format-phone/format-phone.template.html
- projects/kit/components/files/file/file.component.ts
> feat(cdk): `FormatDate` add new pipe

- projects/core/components/button/button-options.ts
- projects/core/components/button/button.component.ts
- projects/demo/src/modules/components/button/examples/1/index.ts
> chore: fix button default appearance

- projects/cdk/schematics/ng-update/constants/templates.ts
- projects/demo/src/modules/components/action/action.component.ts
- projects/demo/src/modules/components/action/action.template.html
- projects/demo/src/modules/components/action/examples/1/index.html
- projects/demo/src/modules/components/action/examples/1/index.less
- projects/demo/src/modules/components/action/examples/import/insert-template.md
- projects/kit/components/action/action.component.ts
- projects/kit/components/action/action.style.less
- projects/kit/components/action/action.template.html
> refactor(kit)!: `Action` refactor to `button[tuiAction], a[tuiAction]`

- projects/addon-editor/extensions/image-editor/image-editor.component.html
- projects/addon-editor/extensions/image-editor/image-editor.component.ts
- projects/demo/src/environments/environment.prod.ts
- projects/demo/src/environments/environment.ts
- projects/demo/src/modules/components/editor-new/editor-new.component.ts
- projects/demo/src/modules/components/editor-new/editor-new.module.ts
- projects/demo/src/modules/components/editor-new/editor-new.template.html
- projects/demo/src/modules/components/editor-new/examples/2/index.ts
- projects/demo/src/modules/components/editor-new/examples/7/image-loader.ts
- projects/demo/src/modules/components/editor-new/examples/7/imgbb.service.ts
- projects/demo/src/modules/components/editor-new/examples/7/index.html
- projects/demo/src/modules/components/editor-new/examples/7/index.less
- projects/demo/src/modules/components/editor-new/examples/7/index.ts
Closes #2363
https://user-images.githubusercontent.com/12021443/186888345-a08b830e-c11c-43c4-b974-140bccae39aa.mov
> feat(addon-editor): add `TUI_EDITOR_MAX_IMAGE_WIDTH` token

- projects/cdk/schematics/ng-update/steps/migrate-taiga-proprietary-icons.ts
> chore: fix assets migration for tds icons

- projects/cdk/schematics/ng-update/constants/templates.ts
> chore(cdk): add hover/focus/active button migration

- projects/cdk/schematics/ng-update/constants/templates.ts
- projects/cdk/schematics/ng-update/constants/tui-interactive-selectors.ts
- projects/cdk/schematics/ng-update/steps/migrate-templates.ts
- projects/cdk/schematics/ng-update/steps/migrate-textfield-controller.ts
- projects/cdk/schematics/ng-update/tests/schematic-migrate-textfields.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-textfield-icon.spec.ts
- projects/cdk/schematics/utils/templates/elements.ts
> chore(cdk): add textfield-controller migration

- projects/demo/src/modules/components/push/push.component.ts
- projects/demo/src/modules/info/testing/disable-animation/disable-animation.component.ts
- projects/demo/src/modules/info/testing/jest/jest.component.ts
- projects/demo/src/modules/info/testing/screenshot-github-bot/screenshot-github-bot.component.ts
- projects/demo/src/modules/pipes/format-date/format-date.component.ts
> chore(demo): delete usage of `raw-loader`

- projects/cdk/schematics/ng-update/constants/modules.ts
- projects/cdk/schematics/ng-update/constants/templates.ts
> chore(cdk): tuiHintDescribe migration

- projects/cdk/schematics/ng-add/index.ts
> chore: remove `taiga-ui` package after ng-add

- projects/addon-mobile/components/mobile-dialog/mobile-dialog.service.ts
- projects/cdk/abstract/dialog.service.ts
- projects/core/components/alert/alert.service.ts
- projects/demo/src/modules/customization/dialogs/examples/1/index.ts
- projects/demo/src/modules/customization/dialogs/examples/1/prompt/prompt.service.ts
- projects/kit/components/push/push.service.ts
> fix(cdk): support to override return type in compile time for dialogs

- projects/addon-charts/components/line-chart/line-chart.component.ts
- projects/addon-editor/components/toolbar-tools/align-content/align-content.template.html
- projects/addon-editor/components/toolbar-tools/highlight-color/highlight-color.template.html
- projects/addon-editor/components/toolbar-tools/list-configs/list-configs.template.html
- projects/addon-editor/components/toolbar-tools/table-cell-color/table-cell-color.template.html
- projects/addon-editor/components/toolbar-tools/table-row-column-manager/table-row-column-manager.template.html
- projects/cdk/components/dialog-host/dialog-host.template.html
- projects/cdk/directives/let/let.directive.ts
- projects/core/components/scroll-controls/scroll-controls.template.html
- projects/demo/src/modules/components/input-phone/examples/3/index.html
- projects/demo/src/modules/components/input/examples/4/index.html
- projects/demo/src/modules/components/input/examples/8/index.html
- projects/demo/src/modules/tables/table/examples/4/index.html
- projects/kit/components/input-date-range/input-date-range.template.html
- projects/kit/components/input-date/input-date.template.html
- projects/kit/components/line-clamp/line-clamp.template.html
> fix(cdk)!: the `tuiLet` directive can possibility emit of null

- projects/demo/project.json
> ci: small fix for concurrency problem

- .github/workflows/add-to-project.yml
> ci: link any issues to taiga-ui project

- projects/cdk/schematics/ng-update/constants/consts.ts
- projects/cdk/schematics/ng-update/constants/enums.ts
> chore(cdk): migration for some types

- projects/cdk/types/index.ts
- projects/cdk/types/injection-token-type.ts
- projects/core/components/scrollbar/scrollbar.component.ts
> fix(core): prevent injection conflict with CSS global interface

- projects/addon-commerce/components/input-card/input-card.directive.ts
- projects/cdk/schematics/ng-update/constants/consts.ts
- projects/cdk/schematics/ng-update/tests/schematic-rename-types.spec.ts
- projects/core/abstract/abstract-driver.directive.ts
- projects/core/abstract/abstract-textfield-host.ts
- projects/core/abstract/driver.ts
- projects/core/abstract/position-accessor.ts
- projects/core/abstract/rect-accessor.ts
- projects/core/abstract/vehicle.ts
- projects/core/components/primitive-textfield/primitive-textfield.directive.ts
- projects/kit/components/combo-box/combo-box.directive.ts
- projects/kit/components/input-copy/input-copy.directive.ts
- projects/kit/components/input-count/input-count.directive.ts
- projects/kit/components/input-date-range/input-date-range.directive.ts
- projects/kit/components/input-date-time/input-date-time.directive.ts
- projects/kit/components/input-date/input-date.directive.ts
- projects/kit/components/input-month-range/input-month-range.directive.ts
- projects/kit/components/input-month/input-month.directive.ts
- projects/kit/components/input-number/input-number.directive.ts
- projects/kit/components/input-password/input-password.directive.ts
- projects/kit/components/input-phone/input-phone.directive.ts
- projects/kit/components/input/input.directive.ts
- projects/kit/components/select/select.directive.ts
- projects/kit/components/text-area/text-area.directive.ts
- scripts/eslint/naming-convention.js
> feat(cdk)!: rename `TuiAbstractTextfieldHost` to `AbstractTuiTextfieldHost`

- projects/cdk/schematics/utils/templates/elements.ts
> chore(cdk): fix parsing utf-8 with BOM

- .eslintrc.js
- projects/core/components/scrollbar/scrollbar.component.ts
> chore: eslint errors

- .github/workflows/e2e.yml
> chore: enable e2e for `v3.x`-branch

- .github/workflows/e2e.yml
> ci: disable autorebase before e2e for `v3.x`-branch

- scripts/shared/bump-version.ts
> ci: fixup bump version

- projects/core/directives/dropdown/dropdown-context.directive.ts
- projects/demo-integrations/cypress/tests/kit/dropdown-context/dropdown-context.spec.ts
- projects/demo/src/modules/components/island/island.template.html
> fix(core): `DropdownContext` close previous dropdown after new one is opened

- projects/cdk/constants/empty.ts
- projects/cdk/tokens/is-webkit.ts
- projects/cdk/utils/dom/point-to-client-rect.ts
- projects/core/utils/dom/get-word-range.ts
- projects/kit/directives/highlight/highlight.directive.ts
> refactor: compat with TypeScript 4.6+

- projects/demo/webpack.config.ts
> chore(demo): `webpack.config.ts` add `css`-files with `?raw`-query to webpack assets modules

- projects/demo/src/modules/components/text-area/text-area.template.html
> chore(demo): fix texarea API tab

- projects/cdk/schematics/ng-update/steps/migrate-textfield-controller.ts
- projects/cdk/schematics/ng-update/tests/schematic-migrate-textfields.spec.ts
> fix(cdk): `schematics` fix 3.0-migration for `tuiTextfieldInputMode`

- projects/cdk/schematics/utils/get-project.ts
> chore(cdk): add fallback project in schematic

- projects/demo/src/modules/app/abstract.app.ts
- projects/demo/src/modules/app/app.component.ts
- projects/demo/src/modules/app/version-manager/version-manager.component.ts
- projects/demo/src/modules/app/version-manager/version-manager.providers.ts
- projects/demo/src/modules/app/version-manager/version-manager.template.html
- projects/demo/src/modules/app/version-manager/versions.constants.ts
- scripts/postbuild-demo.ts
> ci: fix relative base href

- .github/workflows/build.yml
- .github/workflows/test.yml
> ci: trigger build/test when have changes in `testing`

- projects/cdk/schematics/constants/file-globs.ts
- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/steps/migrate-progress.ts
- projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-range.ts
- projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-slider.ts
- projects/cdk/schematics/ng-update/tests/schematic-migrate-textfields.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-functions.spec.ts
> chore(cdk): `schematics` fix file globs patterns for migration 3.0

- projects/demo/test/bump.spec.ts
- scripts/shared/bump-version.ts
> ci: correct bump version

- .github/workflows/v2-cherry-pick.yml
> ci: add cherry pick

- projects/demo/src/modules/app/abstract.app.ts
- projects/demo/src/modules/app/app.component.ts
- projects/demo/src/modules/app/version-manager/version-manager.component.ts
- projects/demo/src/modules/app/version-manager/version-manager.providers.ts
- projects/demo/src/modules/app/version-manager/version-manager.template.html
- projects/demo/src/modules/app/version-manager/versions.constants.ts
- scripts/postbuild-demo.ts
(cherry picked from commit 9c085853861bf5b354d38406f53c36d301003a65)
> ci: fix relative base href (#2546)

- projects/demo/src/modules/utils/tokens/examples/7/index.html
- projects/demo/src/modules/utils/tokens/examples/7/index.ts
- projects/demo/src/modules/utils/tokens/tokens.template.html
> chore(demo): add `TUI_IS_MOBILE_RES` example

- .github/workflows/save-snapshots.yml
> ci: save snapshots when changed files into version branches

- projects/core/components/dialog/dialog.component.ts
- projects/core/components/dialog/dialog.template.html
- projects/core/interfaces/dialog-options.ts
> feat(core): add dialog header type

- projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-range.ts
- projects/cdk/schematics/ng-update/steps/migrate-sliders/migrate-input-slider.ts
- projects/cdk/schematics/ng-update/steps/migrate-templates.ts
- projects/cdk/schematics/utils/colored-log.ts
- projects/cdk/schematics/utils/progress.ts
> chore(cdk): `schematics` more logs for migration v3.0

- projects/core/components/primitive-textfield/textfield/textfield.component.ts
> chore(core): remove forgotten exampleText

- projects/demo/project.json
> chore: fix demo serve configuration

- package-lock.json
- projects/cdk/package.json
This PR is an investigation that `optionalDependencies` correctly integrates with migrations for 3.0.
Part of https://github.com/Tinkoff/taiga-ui/issues/2569
> chore(cdk): `parse5` & `ng-morph` should be `optionalDependencies`

- projects/addon-table/components/table-pagination/table-pagination-options.ts
- projects/addon-table/components/table-pagination/table-pagination.template.html
- projects/demo/src/modules/tables/table-pagination/examples/3/index.html
- projects/demo/src/modules/tables/table-pagination/examples/3/index.ts
- projects/demo/src/modules/tables/table-pagination/table-pagination.component.ts
- projects/demo/src/modules/tables/table-pagination/table-pagination.module.ts
- projects/demo/src/modules/tables/table-pagination/table-pagination.template.html
Closes #2467
It's possible to toggle a `pages` label.
> feat(addon-table): add `showPages` option

- .github/workflows/build.yml
- .github/workflows/create-release.yml
- .github/workflows/deploy.yml
- package.json
- projects/addon-charts/project.json
- projects/addon-commerce/project.json
- projects/addon-doc/project.json
- projects/addon-editor/project.json
- projects/addon-mobile/project.json
- projects/addon-preview/project.json
- projects/addon-table/project.json
- projects/addon-tablebars/project.json
- projects/cdk/project.json
- projects/core/project.json
- projects/demo/project.json
- projects/i18n/project.json
- projects/icons/project.json
- projects/kit/project.json
- projects/styles/project.json
- projects/taiga-schematics/project.json
- scripts/postinstall.ts
- scripts/shared/post-build-all-version.ts
- tsconfig.json
- tsconfig.tools.json
> ci: remove redundant exec script

- projects/demo/src/modules/app/stackblitz/project-files/configs.md
- projects/demo/src/modules/app/stackblitz/project-files/src/app/app.module.ts.md
> chore(demo): `stackblitz` fix import of non-existing entities

- .github/actions/nodejs/action.yml
> ci: don't persist local cache in github

- .github/workflows/save-snapshots.yml
(cherry picked from commit 6276c40f19eaaeab1b5698610d2b35c335ae5aab)
> ci: save snapshots when changed files into version branches (#2555)

- projects/kit/components/input-number/input-number.component.ts
- projects/kit/components/input-number/test/input-number.component.spec.ts
> fix(kit): `InputNumber` fix positive min/negative max clipping

- .github/workflows/deploy-next.yml
- .github/workflows/save-snapshots.yml
> ci: publish snapshots into different job

- projects/kit/components/input-number/input-number.component.ts
- projects/kit/components/input-number/test/input-number.component.spec.ts
> fix(kit): InputNumber fix positive min/negative max clipping

- .github/workflows/deploy-next.yml
- .github/workflows/save-snapshots.yml
> ci: publish snapshots into different job (#2591)

- .github/workflows/deploy.yml
- .github/workflows/e2e.yml
> ci: correct deploy

- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/steps/replace-styles.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-deep-imports.spec.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-styles.spec.ts
- projects/demo/src/modules/app/home/home.template.html
> chore(cdk): show warning in less file after migration

- projects/kit/components/badge/test/badge.component.spec.ts
- projects/testing/core/badge/badge.harness.ts
- projects/testing/core/index.ts
> feat(testing): add component harness test for badge component

- projects/core/components/svg/test/svg.component.spec.ts
- projects/testing/core/index.ts
- projects/testing/core/svg/svg.harness.ts
> feat(testing): SVG component harness tests

- projects/core/components/primitive-textfield/primitive-textfield.style.less
- projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less
- projects/core/components/primitive-textfield/value-decoration/value-decoration.template.html
> Revert "fix(core): character descenders overflow the line (#2387)"

- package-lock.json
- projects/cdk/package.json
See https://github.com/Tinkoff/ng-polymorpheus/pull/56
> fix: add compatibility with TypeScript 4.8

- projects/kit/components/carousel/carousel.directive.ts
> fix(kit): `Carousel` reset autoscroll timer when index changes

- scripts/publish.ts
> ci: use lts tag for prev versions

- .github/workflows/deploy.yml
- nx.json
- package.json
- projects/demo/project.json
- projects/demo/src/modules/app/abstract.app.ts
- projects/demo/src/modules/app/app.component.ts
- projects/demo/src/modules/app/version-manager/version-manager.component.ts
- projects/demo/src/modules/app/version-manager/version-manager.providers.ts
- projects/demo/src/modules/app/version-manager/versions.constants.ts
- projects/icons/scripts/delete-all-to-compile-file.ts
- scripts/compile-icons.ts
- scripts/postbuild-demo.ts
- scripts/shared/argv.utils.ts
- scripts/shared/build-demo.ts
- scripts/shared/make-publishable-versions-map.ts
> ci: prevent build greater versions

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
> fix(addon-commerce): `InputCardGrouped` fix dropdown width

- nx.json
> ci: correct implicit dependencies

- projects/demo/src/modules/app/stackblitz/stackblitz-deps.constants.ts
1. Open https://taiga-ui.dev/v2/components/action#links
2. Press "Edit on Stackblitz"
Opens stackblitz with the same major version as documentation.
> chore(demo): fix stackblitz

- projects/demo/src/modules/app/stackblitz/stackblitz-deps.constants.ts
Partially solves https://github.com/Tinkoff/taiga-ui/issues/2541
> chore(cdk) `Stackblitz` use the same major taiga-version as selected documentation

- projects/core/styles/mixins/text.less
- projects/core/styles/theme/variables.less
> chore(core): `styles` mark TODOs for 4.0

- .github/workflows/build.yml
- .github/workflows/deploy-next.yml
- .github/workflows/save-snapshots.yml
- nx.json
- projects/addon-charts/project.json
- projects/addon-commerce/project.json
- projects/addon-doc/project.json
- projects/addon-editor/project.json
- projects/addon-mobile/project.json
- projects/addon-preview/project.json
- projects/addon-table/project.json
- projects/addon-tablebars/project.json
- projects/cdk/project.json
- projects/cdk/schematics/utils/colored-log.ts
- projects/core/project.json
- projects/i18n/project.json
- projects/icons/project.json
- projects/icons/scripts/delete-all-to-compile-file.ts
- projects/kit/project.json
- projects/taiga-schematics/project.json
- scripts/compile-icons.ts
- scripts/postbuild-demo.ts
- scripts/publish.ts
- scripts/shared/argv.utils.ts
- scripts/shared/build-demo.ts
> ci: fix build problem

- .github/actions/nodejs/action.yml
- .github/workflows/deploy-next.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/deploy.yml
- .github/workflows/e2e.yml
- .github/workflows/save-snapshots.yml
- projects/addon-charts/project.json
- projects/addon-commerce/project.json
- projects/addon-doc/project.json
- projects/addon-editor/project.json
- projects/addon-mobile/project.json
- projects/addon-preview/project.json
- projects/addon-table/project.json
- projects/addon-tablebars/project.json
- projects/cdk/project.json
- projects/core/project.json
- projects/demo/project.json
- projects/i18n/project.json
- projects/icons/project.json
- projects/kit/project.json
- projects/taiga-schematics/project.json
- projects/testing/project.json
> ci: fix build

- .github/workflows/deploy-next.yml
- .github/workflows/deploy.yml
- .github/workflows/save-snapshots.yml
- nx.json
- scripts/postbuild-demo.ts
- scripts/publish.ts
- scripts/shared/build-demo.ts
- scripts/shared/get-all-versions.ts
- scripts/shared/get-last-major-version.ts
- scripts/shared/make-publishable-versions-map.ts
(cherry picked from commit 892fdcbe311f442947ab367f33e33b0dd31f579d)
> chore: incorrect build relative base-href

- projects/addon-editor/components/editor/editor.component.html
- projects/demo-integrations/cypress/tests/addon-editor/editor-img.spec.ts
- projects/demo-integrations/cypress/tests/addon-table/table/table.spec.ts
> fix(addon-editor): using editor-socket inside editor to fix editor styles

- projects/demo-integrations/cypress/tests/addon-editor/editor-api.spec.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-img.spec.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-toolbar.spec.ts
- projects/demo/src/modules/components/editor/editor.template.html
> chore: fix editor e2e

- .github/workflows/e2e.yml
- projects/demo/project.json
> ci: compare only production mode

- projects/demo/project.json
> ci: disable optimization to scripts for prevent flaky e2e tests

- projects/cdk/schematics/ng-update/constants/consts.ts
- projects/demo/src/modules/components/input-files/input-files.template.html
> chore(cdk): `schematics` forgotten migration for `TuiInputFileModule` => `TuiInputFilesModule`

- projects/cdk/services/destroy.service.ts
> chore: add additional description for help

- projects/demo/src/modules/info/testing/jest/examples/setup-jest-js.md
> chore(demo): improve documentation for jest

- .github/workflows/create-release.yml
> chore: fix workflow

- projects/addon-table/components/table/directives/head.directive.ts
- projects/addon-table/components/table/directives/row.directive.ts
- projects/addon-table/components/table/directives/sort-by.directive.ts
- projects/addon-table/components/table/directives/sortable.directive.ts
- projects/addon-table/components/table/directives/table.directive.ts
- projects/addon-table/components/table/pipes/table-sort.pipe.ts
- projects/addon-table/components/table/tbody/tbody.component.ts
- projects/addon-table/components/table/th-group/th-group.component.ts
- projects/addon-table/components/table/th/th.component.ts
- projects/addon-table/components/table/tr/tr.component.ts
- projects/addon-table/components/table/tr/tr.template.html
> fix(addon-table): type string is not assignable to type keyof T

- package-lock.json
- scripts/shared/sync-versions.ts
> ci: improved logs

- .github/workflows/create-release.yml
> chore: ci remove redundant step

- .github/workflows/autorebase.yml
- .github/workflows/build.yml
- .github/workflows/deploy-next.yml
- .github/workflows/release.yml
- .github/workflows/save-snapshots.yml
- .github/workflows/validate-tag.yml
> ci: refactor jobs

- README.md
- projects/addon-charts/README.md
- projects/addon-commerce/README.md
- projects/addon-editor/README.md
- projects/addon-mobile/README.md
- projects/addon-preview/README.md
- projects/addon-table/README.md
- projects/addon-tablebars/README.md
- projects/cdk/README.md
- projects/core/README.md
- projects/demo/src/modules/components/carousel/examples/1/index.html
- projects/demo/src/modules/utils/dom/dom.template.html
- projects/i18n/README.md
- projects/icons/README.md
- projects/kit/README.md
- projects/taiga-schematics/README.md
Documentation is rarely updated
> docs: remove redundant wiki references

- projects/cdk/schematics/ng-update/steps/migrate-taiga-proprietary-icons.ts
- projects/cdk/schematics/utils/angular-json-manipulations.ts
- projects/cdk/schematics/utils/get-project.ts
> fix(cdk): `schematics` migration 3.x `Error: Cannot determine project target configuration`

- .eslintrc.js
- .github/workflows/deploy-gh-pages.yml
- .github/workflows/snapshots.yml
> ci: refactor snapshots (#2678)

- projects/demo/src/404.html
- projects/demo/src/modules/app/abstract.app.ts
> ci: replace only `next` or `v.x` subpath of route

- projects/demo-integrations/cypress/support/visit.ts
- projects/demo/src/404.html
- projects/demo/src/modules/app/abstract.app.ts
(cherry picked from commit 0b4fa65a9c30afda4d6e4d3b7a7ded6c813d567e)
> chore(demo): don't use logic in app component (#2696)

- CHANGELOG.md
> chore: cut CHANGELOG.md

- README.md
- projects/addon-charts/README.md
- projects/addon-commerce/README.md
- projects/addon-editor/README.md
- projects/addon-mobile/README.md
- projects/addon-preview/README.md
- projects/addon-table/README.md
- projects/addon-tablebars/README.md
- projects/cdk/README.md
- projects/core/README.md
- projects/demo/src/modules/components/carousel/examples/1/index.html
- projects/demo/src/modules/utils/dom/dom.template.html
- projects/i18n/README.md
- projects/icons/README.md
- projects/kit/README.md
- projects/taiga-schematics/README.md
(cherry picked from commit 154206469c3c9dacdcb961a7449e49c0505103d3)
> docs: remove redundant wiki references (#2655)

- .eslintrc.js
- projects/cdk/directives/for/test/for.directive.spec.ts
- projects/demo/src/modules/services/destroy/examples/1/component.ts
- projects/eslint-plugin/index.js
- projects/eslint-plugin/prefer-inject-decorator.js
- projects/kit/components/rating/tests/rating.component.spec.ts
Closes #2662
ESLint forces to use Inject() for Dependency Injection.
> feat(eslint-plugin): create prefer-inject-decorator

- .github/workflows/deploy-gh-pages.yml
> ci: final fixes

- .github/workflows/deploy-gh-pages.yml
> ci: use checkout before deploy

- .github/workflows/deploy-gh-pages.yml
> ci: use checkout before deploy (#2703)

- .eslintrc.js
Repository of this project can be cloned with any name (not only default `taiga-ui`; for example, `taiga-fork` and etc.).
That is why i remove this prefix.
Closes #
> chore: update configs of `@taiga-ui/no-deep-imports`-rule

- CHANGELOG.md
> chore(demo): update `Changelog` for `3.0.0`-release

- projects/core/styles/mixins/mixins.scss
- projects/core/styles/mixins/picker.scss
- projects/core/styles/mixins/slider.scss
- projects/core/styles/mixins/text.scss
- projects/core/styles/mixins/textfield.scss
- projects/core/styles/mixins/wrapper.scss
- projects/core/styles/variables/media.scss
Most `.scss`-files is not well-maintained and sometimes contains broken selectors.
`.scss`-files have the same content as `.less`-files.
> fix(core): `styles` sync `.scss`-files with `.less`-files

- projects/kit/components/multi-select/test/multi-select.component.spec.ts
> chore: skip flaky unit test

- projects/demo-integrations/cypress/support/editor/helpers.ts
- projects/demo/src/modules/components/editor/editor.template.html
Closes #2677
Uses correct hint for maxheight parameter
> docs(addon-editor): `Editor` fix `max-height`-description (API-page)

- projects/demo/src/modules/directives/highlight/examples/import/import-module.md
> docs(kit): change TuiHighlightModule import from core to kit

- projects/demo/src/modules/components/svg/svg.module.ts
- projects/demo/src/modules/components/svg/svg.template.html
> chore(demo): `Svg` improve documentation

- projects/kit/components/island/test/island.component.spec.ts
- projects/testing/core/index.ts
- projects/testing/core/island.harness.ts
> feat(testing): add harness for island

- projects/core/styles/theme/dialog.less
- projects/core/styles/theme/wrapper/accent.less
- projects/core/styles/theme/wrapper/base.less
- projects/core/styles/theme/wrapper/icon.less
- projects/core/styles/theme/wrapper/mono.less
- projects/core/styles/theme/wrapper/outline.less
- projects/core/styles/theme/wrapper/primary.less
- projects/core/styles/theme/wrapper/secondary-destructive.less
- projects/core/styles/theme/wrapper/secondary.less
- projects/core/styles/theme/wrapper/table.less
- projects/core/styles/theme/wrapper/textfield.less
- projects/core/styles/theme/wrapper/whiteblock.less
- projects/demo/src/modules/app/stackblitz/project-files/src/stackblitz.less.md
- projects/demo/src/modules/app/stackblitz/stackblitz-resources-loader.ts
- projects/demo/src/modules/app/stackblitz/utils.ts
- projects/styles/taiga-ui-global.less
The vast majority of components have problems with styles inside Stackblitz.
**Some examples:**
https://taiga-ui.dev/components/input#modes
____
https://taiga-ui.dev/components/button#appearance
___
https://taiga-ui.dev/components/input-slider#base
https://taiga-ui.dev/components/input#modes
___
https://taiga-ui.dev/components/button#appearance
___
https://taiga-ui.dev/components/input-slider#base
**The global styles will be fixed later!**
> fix(demo): `Stackblitz` broken styles

- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/steps/migrate-date-time.ts
- projects/cdk/schematics/ng-update/steps/replace-styles.ts
Closes #2743
Add `Node.js < 16`-support
> fix(cdk): `schematics` add `Node.js < 16`-support

- CHANGELOG.md
Also, update https://github.com/Tinkoff/taiga-ui/releases/tag/v3.0.0
> chore: `CHANGELOG` add `Migration guide` for `3.0.0`-release

- projects/core/directives/hint/hint.component.ts
- projects/testing/core/badge.harness.ts
> fix(core): `Hint` fix offscreen position on small devices

- projects/kit/components/input-time/input-time.component.ts
- projects/kit/components/input-time/input-time.module.ts
- projects/kit/components/input-time/input-time.template.html
> feat(kit): `InputTime` add checkmark near selected time

- projects/cdk/components/alert-host/alert-host.component.ts
- projects/cdk/components/dialog-host/dialog-host.component.ts
- projects/core/components/dialog/dialog.component.ts
- projects/core/components/hints-host/hints-host.component.ts
- projects/core/components/root/root.component.ts
> feat(core): `Dialog` allow `Default` change detection strategy to work

- projects/demo/project.json
- projects/demo/src/modules/app/home/home.component.ts
`nx serve-default demo` and `nx serve-shadow demo` returns 404
> chore(demo): fix commands `nx serve-default demo` and `nx serve-shadow demo`

- projects/addon-doc/src/utils/raw-load.ts
- projects/demo/src/modules/app/stackblitz/stackblitz-resources-loader.ts
- projects/demo/src/modules/app/stackblitz/utils.ts
> refactor(demo): `Stackblitz` drop legacy code

- projects/kit/components/input-number/input-number.component.ts
- projects/kit/components/input-number/test/input-number.component.spec.ts
Closes # https://github.com/Tinkoff/taiga-ui/issues/2421
> fix(kit): introduce safe integers for min/max props in number input

- projects/demo/src/modules/app/stackblitz/project-files/src/app/@stackblitz/README.md
- projects/demo/src/modules/app/stackblitz/project-files/src/stackblitz.less.md
https://taiga-ui.dev/components/button#appearance
https://taiga-ui.dev/components/button#appearance
> fix(demo): `Stackblitz` enable `taiga-ui-global.less`

- projects/addon-commerce/components/card/test/card.component.spec.ts
- projects/testing/core/card.harness.ts
- projects/testing/core/index.ts
Introduces ComponentHarness for card component.
> feat(testing): card component harness test

- projects/core/components/hints-host/hint-box/hint-box.template.html
> fix(core): `LineClamp` fix arrow on mobile

- projects/addon-charts/components/bar-set/bar-set.style.less
- projects/addon-charts/components/bar-set/bar-set.template.html
- projects/demo/src/modules/charts/bar-set/bar-set.module.ts
- projects/demo/src/modules/charts/bar-set/bar-set.template.html
- projects/demo/src/modules/charts/bar-set/examples/5/index.html
- projects/demo/src/modules/charts/bar-set/examples/5/index.less
- projects/demo/src/modules/charts/bar-set/examples/5/index.ts
- projects/kit/components/input-count/input-count-options.ts
> feat(addon-charts): `BarSet` add label

- projects/demo/src/modules/markup/grid/grid.template.html
> fix(demo): fixed description for tui-container_adaptive

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
> fix(addon-commerce): show caret color when filling in input card group value

- projects/demo/src/modules/components/abstract/inherited-documentation/inherited-documentation.template.html
from AbstractTuiInteractive docs
- Some of the properties that have been renamed or removed due to deprecation are still seen in documentation (ie. button component)
Closes #2665 
- Updates the documentation for AbstractTuiInteractive, renaming or removing deprecated properties
> chore(demo): rename and remove deprecated properties 

- projects/addon-editor/components/editor/editor.component.ts
- projects/addon-editor/utils/index.ts
- projects/addon-editor/utils/safe-link-range.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-links.cy.ts
Closes #2721
https://user-images.githubusercontent.com/12021443/193824358-0bf1539e-ec88-427f-8a12-931eacb484b6.mov
https://user-images.githubusercontent.com/12021443/193824586-8f17388e-cced-4f39-a1ed-7e20eba12695.mov
> fix(addon-editor): edit link modal shouldn't overlap content

- projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
- projects/demo/src/modules/app/stackblitz/utils.ts
1. Open https://taiga-ui.dev/dialogs#custom-dialog
2. Press Edit on Stackblitz
3. Press button inside stackblitz's example
Broken example
Example works
> chore(demo): `Stackblitz` broken examples with additional modules

- projects/demo-integrations/cypress/support/visit.ts
- projects/demo/src/modules/app/app.style.less
- projects/demo/src/modules/app/cypress.less
> ci: override waitRenderedFont in runtime for proprietary demo

- projects/core/directives/hint/hint.component.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/components/avatar/avatar.component.ts
- projects/demo/src/modules/components/avatar/avatar.module.ts
- projects/demo/src/modules/components/avatar/avatar.template.html
- projects/demo/src/modules/components/avatar/examples/4/index.html
- projects/demo/src/modules/components/avatar/examples/4/index.less
- projects/demo/src/modules/components/avatar/examples/4/index.ts
- projects/kit/components/avatar/avatar.style.less
> feat(kit): `Avatar` add stacking option

- projects/demo-integrations/cypress/support/visit.ts
- projects/demo/src/modules/app/app.style.less
- projects/demo/src/modules/app/cypress.less
> ci: override waitRenderedFont in runtime for proprietary demo (#2810)

- .github/screenshot-bot.config.toml
> ci: update `screenshot-bot.config.toml`

- projects/addon-editor/components/editor-new/editor-new.component.ts
- projects/addon-editor/constants/default-editor-styles.ts
- projects/addon-editor/constants/tiptap-editor-styles.ts
- projects/addon-editor/styles/editor-socket.css
- projects/addon-editor/utils/index.ts
- projects/addon-editor/utils/safe-link-range.ts
- projects/demo/src/modules/components/editor-new/editor-new.component.ts
- projects/demo/src/modules/components/editor-new/editor-new.styles.less
> chore: backports from main branch

- projects/demo/src/modules/components/dialog/dialog.component.ts
1. Open https://taiga-ui.dev/next/components/dialog#mobile-fullscreen
2. Press "Edit on Stackblitz"
```console
Error in src/app/search-dialog.module.ts (6:44)
Cannot find module './search-dialog-example.component' or its corresponding type declarations.
```
Example works
> chore(demo): `Stackblitz` fix `Fullscreen mobile dialog with autofocus`-example

- projects/demo/src/modules/components/avatar/avatar.component.ts
- projects/demo/src/modules/components/avatar/avatar.module.ts
- projects/demo/src/modules/components/avatar/avatar.template.html
- projects/demo/src/modules/components/avatar/examples/5/index.html
- projects/demo/src/modules/components/avatar/examples/5/index.ts
- projects/kit/components/avatar/avatar.component.ts
- projects/kit/components/avatar/avatar.module.ts
- projects/kit/components/avatar/avatar.style.less
- projects/kit/components/avatar/avatar.template.html
> feat(kit): `Avatar` allow Taiga UI icons

- projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
- projects/cdk/schematics/utils/templates/get-component-templates.ts
> fix(cdk): `schematics` error `Cannot read property 'getInitializer' of undefined`

- .github/actions/announce/action.yml
- .github/workflows/create-release.yml
- .github/workflows/publish.yml
> chore: announce notifier

- projects/cdk/utils/dom/get-element-obscurers.ts
> fix(cdk): `tuiGetElementObscures` SSR error `TypeError: getBoundingClientRect is not a function`

- projects/demo/src/modules/components/text-area/examples/4/index.html
> chore(demo): `TextArea` fix example

- projects/addon-doc/src/components/documentation/documentation.style.less
- projects/addon-doc/src/components/documentation/documentation.template.html
> chore(demo): misaligned column fix

- projects/core/components/data-list/data-list.style.less
- projects/kit/components/multi-select/multi-select.style.less
> fix(kit): `MultiSelect` fix overflow issues

- .github/actions/announce/action.yml
- .github/workflows/create-release.yml
- .github/workflows/publish.yml
(cherry picked from commit aa73a610ebb84c9ac9105e06d3d15699ce9c338e)
> chore: announce notifier (#2827)

- .github/workflows/deploy-gh-pages.yml
> ci: use another gp deploy action

- projects/kit/components/radio-labeled/radio-labeled.style.less
- projects/kit/components/radio-labeled/radio-labeled.template.html
Closes https://github.com/Tinkoff/taiga-ui/issues/2841
> fix(kit): add disabled styled to label

- .github/workflows/snapshots.yml
> ci: deploy only production mode

- .github/workflows/snapshots.yml
> ci: add explicit flag for production build

- projects/core/components/root/root.component.ts
- projects/core/components/root/root.style.less
- projects/core/components/root/root.template.html
- projects/styles/basic/main.less
> fix(styles): move required styles from `styles` package to tui-root

- projects/demo-integrations/cypress/support/visit.ts
> ci: fix typings for helpers in proprietary

- projects/demo/src/modules/app/home/home.template.html
> chore(demo): add install/update info for nx users

- projects/core/components/data-list/data-list.style.less
- projects/demo/src/modules/components/data-list/examples/3/index.html
> fix(core): `DataList` fix first label padding

- package-lock.json
- projects/cdk/date-time/test/month.spec.ts
- projects/eslint-plugin/project.json
- projects/i18n/project.json
- projects/icons/project.json
- projects/kit/components/input-count/input-count.directive.ts
- projects/kit/components/input-count/test/input-count.component.spec.ts
- projects/testing/package.json
- projects/testing/project.json
- projects/testing/utils/native-input.page-object.ts
- tsconfig.schematics.json
> chore: fix comments

- projects/demo-integrations/cypress/support/exclusions.ts
- projects/demo/src/modules/components/progress-bar/examples/6/index.html
- projects/demo/src/modules/components/progress-bar/examples/6/index.less
- projects/demo/src/modules/components/progress-bar/examples/6/index.ts
- projects/demo/src/modules/components/progress-bar/progress-bar.component.html
- projects/demo/src/modules/components/progress-bar/progress-bar.component.ts
- projects/demo/src/modules/components/progress-bar/progress-bar.module.ts
- projects/kit/components/progress/progress-bar/progress-bar.component.less
> feat(kit): `ProgressBar` add `:indeterminate`-state

- projects/core/directives/hint/hint-position.directive.ts
> fix(core): `Hint` fix mobile offscreen overflow

- .github/workflows/bundle-size-check.yml
- .github/workflows/deploy-preview.yml
> chore: move bundlemon to separate workflow

- projects/demo-integrations/cypress/tests/addon-icons/customization-icons.cy.ts
- projects/demo/src/modules/markup/icons/icons.component.ts
- projects/demo/src/modules/markup/icons/icons.module.ts
- projects/demo/src/modules/markup/icons/icons.template.html
- projects/demo/src/modules/markup/icons/inline-svg/inline-svg.component.ts
- projects/demo/src/modules/markup/icons/inline-svg/inline-svg.style.less
> docs: update example with `TUI_SANITIZER`

- projects/demo/src/modules/components/input-files/examples/1/index.html
- projects/demo/src/modules/components/input-files/examples/1/index.ts
> chore(demo): add request imitation to TuiFiles example

- projects/addon-table/components/table/tr/tr.component.ts
- projects/demo/src/modules/tables/table/examples/1/index.html
> fix(addon-table): `Table` don't render column with unspecified template

- .github/workflows/deploy-preview.yml
> ci: firebase

- projects/kit/components/push/push-alert.component.ts
> revert: no-cycle

- projects/demo/src/modules/components/text-area/examples/2/index.html
- projects/demo/src/modules/components/text-area/examples/2/index.less
- projects/kit/components/text-area/text-area.component.ts
- projects/kit/components/text-area/text-area.style.less
> fix(kit): `TextArea` add ability to override minHeight when using maxLength

- projects/demo/src/modules/app/pages.ts
- projects/kit/components/push/push-alert.directive.ts
- projects/kit/components/push/push.service.ts
> chore: fix comment

- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
- projects/demo/src/modules/app/stackblitz/starter/files/app.component.html.md
- projects/demo/src/modules/app/stackblitz/starter/files/app.component.ts.md
- projects/demo/src/modules/app/stackblitz/starter/files/index.html.md
- projects/demo/src/modules/app/stackblitz/starter/files/styles.less.md
- projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.component.ts
- projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.module.ts
- projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.style.less
- projects/demo/src/modules/app/stackblitz/utils.ts
- projects/kit/components/push/push-alert.directive.ts
- projects/kit/components/push/push.service.ts
https://user-images.githubusercontent.com/35179038/195892745-03ce32e0-e2e2-4438-8c35-1aeb258a3c18.mov
> feat(demo): stackblitz starter available via `https://taiga-ui.dev/stackblitz`

- projects/kit/components/multi-select/multi-select.component.ts
- projects/kit/components/multi-select/multi-select.style.less
- projects/kit/components/multi-select/multi-select.template.html
- projects/kit/components/multi-select/test/multi-select.component.spec.ts
- projects/kit/constants/icon-blank.ts
- projects/kit/constants/index.ts
> fix(kit): `MultiSelect` fix sanitizer warnings

- projects/demo/src/modules/components/scrollbar/scrollbar.template.html
- [ OK ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ OK ] Tests for the changes have been added (for bug fixes / features)
- [ OK ] Docs have been added / updated (for bug fixes / features)
- [ *] Documentation content changes
Closes # https://github.com/Tinkoff/taiga-ui/issues/2886
- [* ] No
> fix(documentation): typo on scrollbar page

- CONTRIBUTING.md
- package.json
- projects/demo/project.json
> build: add 10% faster serve build

- projects/core/abstract/abstract-textfield-host.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/components/input-year/examples/1/index.html
- projects/demo/src/modules/components/input-year/examples/1/index.ts
- projects/demo/src/modules/components/input-year/examples/2/index.html
- projects/demo/src/modules/components/input-year/examples/2/index.ts
- projects/demo/src/modules/components/input-year/examples/import/declare-form.md
- projects/demo/src/modules/components/input-year/examples/import/import-module.md
- projects/demo/src/modules/components/input-year/examples/import/insert-template.md
- projects/demo/src/modules/components/input-year/input-year.component.ts
- projects/demo/src/modules/components/input-year/input-year.module.ts
- projects/demo/src/modules/components/input-year/input-year.template.html
- projects/kit/components/index.ts
- projects/kit/components/input-year/index.ts
- projects/kit/components/input-year/input-year.component.ts
- projects/kit/components/input-year/input-year.directive.ts
- projects/kit/components/input-year/input-year.module.ts
- projects/kit/components/input-year/input-year.style.less
- projects/kit/components/input-year/input-year.template.html
- projects/kit/components/input-year/ng-package.json
- projects/kit/components/input-year/test/input-year.component.spec.ts
- projects/kit/pipes/index.ts
- projects/kit/pipes/to-year/index.ts
- projects/kit/pipes/to-year/ng-package.json
- projects/kit/pipes/to-year/to-year.module.ts
- projects/kit/pipes/to-year/to-year.pipe.spec.ts
- projects/kit/pipes/to-year/to-year.pipe.ts
> feat(kit): `InputYear` add new component

- projects/core/components/button/button.style.less
- projects/demo/src/modules/components/button/button.component.ts
- projects/demo/src/modules/components/button/button.module.ts
- projects/demo/src/modules/components/button/button.template.html
- projects/demo/src/modules/components/button/examples/5/index.ts
- projects/demo/src/modules/components/button/examples/6/index.html
- projects/demo/src/modules/components/button/examples/6/index.less
- projects/demo/src/modules/components/button/examples/6/index.ts
- projects/demo/src/modules/components/hosted-dropdown/examples/4/index.html
- projects/demo/src/modules/components/hosted-dropdown/examples/4/index.ts
- projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.component.ts
- projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.module.ts
- projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.template.html
- projects/demo/src/modules/components/radio-block/examples/4/index.html
- projects/demo/src/modules/components/radio-block/examples/4/index.less
- projects/demo/src/modules/components/radio-block/examples/4/index.ts
- projects/demo/src/modules/components/radio-block/radio-block.component.ts
- projects/demo/src/modules/components/radio-block/radio-block.module.ts
- projects/demo/src/modules/components/radio-block/radio-block.template.html
> feat(core): `Button` add padding customization

- projects/demo/src/modules/components/input-tag/input-tag.template.html
- projects/kit/components/input-tag/input-tag.component.ts
- projects/kit/components/input-tag/input-tag.template.html
> fix(kit): `InputTag` fix pasting behaviour

- projects/kit/components/toggle/test/toggle.component.spec.ts
- projects/testing/core/index.ts
- projects/testing/core/toggle.harness.ts
Introduces ComponentHarness for card component.
> feat(testing): add harness class for toggle component

- README.md
> chore: fixup README.md

- .github/actions/nodejs/action.yml
- .github/workflows/create-release.yml
- .github/workflows/e2e.yml
- .github/workflows/publish.yml
- .github/workflows/validate-tag.yml
> ci: remove deprecated api

- projects/core/components/notification/notification.style.less
> fix(core): fix notification padding and background color 

- projects/core/components/data-list/option/option.style.less
- projects/core/directives/dropdown/dropdown.style.less
- projects/core/directives/hint/hint.style.less
- projects/core/styles/mixins/mixins.less
- projects/core/styles/mixins/mixins.scss
> feat(core): update shadows styles

- projects/addon-doc/src/components/documentation/documentation.component.ts
- projects/addon-doc/src/components/documentation/documentation.module.ts
- projects/addon-doc/src/components/documentation/documentation.template.html
- projects/addon-doc/src/components/documentation/pipes/inspect.pipe.ts
- projects/addon-doc/src/public-api.ts
- projects/demo/project.json
> ci: enable full optimization for correct detect problems on E2E

- .github/actions/nodejs/action.yml
- .github/workflows/create-release.yml
- .github/workflows/e2e.yml
- .github/workflows/publish.yml
- .github/workflows/validate-tag.yml
> ci: fixup syntax

- projects/demo-integrations/cypress/tests/core/text-area/text-area.cy.ts
- projects/kit/components/text-area/text-area.style.less
> fix(kit): use static height instead of dynamic calculate height in `tui-text-area`

- projects/demo-integrations/cypress/tests/core/marker-icon/marker-icon.cy.ts
- projects/demo/src/modules/components/marker-icon/examples/2/index.html
- projects/kit/components/marker-icon/marker-icon.component.ts
- projects/kit/components/marker-icon/marker-icon.style.less
> fix(kit): hover state from MarkerIcon should only anchor elements

- .github/workflows/create-release.yml
> ci: fix PR body

- projects/cdk/services/scroll.service.ts
- projects/core/components/scrollbar/scrollbar.component.ts
> feat(cdk): `ScrollService` support `Window`

- projects/core/types/size.ts
- projects/core/utils/miscellaneous/size-bigger.ts
- projects/demo/src/modules/components/avatar/avatar.component.ts
- projects/demo/src/modules/components/avatar/avatar.template.html
- projects/demo/src/modules/components/avatar/examples/5/index.html
- projects/demo/src/modules/components/marker-icon/examples/3/index.html
- projects/demo/src/modules/components/marker-icon/marker-icon.component.ts
- projects/demo/src/modules/components/marker-icon/marker-icon.template.html
- projects/kit/components/avatar/avatar-options.ts
- projects/kit/components/avatar/avatar.style.less
- projects/kit/components/marker-icon/marker-icon.component.ts
- projects/kit/components/marker-icon/marker-icon.style.less
> feat(kit): `Avatar`, `MarkerIcon` synchronize sizes

- projects/cdk/schematics/ng-update/steps/replace-styles.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-styles.spec.ts
> fix(cdk): add wrapper style migration

- projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
- projects/demo-integrations/cypress/support/demo-paths.ts
- projects/demo-integrations/cypress/support/exclusions.ts
- projects/demo-integrations/cypress/support/shared.entities.ts
- projects/demo-integrations/cypress/tests/demo/demo.cy.ts
- projects/demo-integrations/cypress/tests/kit/select/select.cy.ts
> ci: fix flaky tests

- projects/cdk/schematics/ng-update/tests/schematic-replace-styles.spec.ts
> chore: fix test

- projects/demo/src/modules/utils/tokens/examples/7/index.html
- projects/demo/src/modules/utils/tokens/examples/7/index.ts
- projects/demo/src/modules/utils/tokens/tokens.template.html
Closes #2813
The missing token (TUI_IS_MOBILE_RES) is added to the documentation page.
> docs: add TUI_IS_MOBILE_RES to tokens page

- .github/actions/nodejs/action.yml
(cherry picked from commit 06e78d1dbe9a7f8d77f0f65496ddd98b2a13e908)
> ci: fix typo (#2982)

- projects/demo/src/modules/components/color-picker/color-picker.component.ts
- projects/demo/src/modules/components/color-picker/color-picker.module.ts
- projects/demo/src/modules/components/color-picker/color-picker.template.html
- projects/demo/src/modules/components/color-picker/examples/3/index.html
- projects/demo/src/modules/components/color-picker/examples/3/index.ts
> chore(demo): add `Palette` example

- projects/demo/src/modules/utils/tokens/examples/7/index.html
See https://github.com/Tinkoff/taiga-ui/pull/2976#discussion_r1008063330.
The example with the stream is added. People can see this token in action.
> docs: add example to show TUI_IS_MOBILE_RES stream value

- projects/demo-integrations/cypress/support/editor/helpers.ts
- projects/demo-integrations/cypress/support/exclusions.ts
- projects/demo/src/modules/components/abstract/interactive.ts
- projects/demo/src/modules/components/action/action.template.html
- projects/demo/src/modules/components/editor/editor.template.html
- projects/demo/src/modules/components/input-copy/input-copy.template.html
- projects/demo/src/modules/components/input-count/input-count.template.html
- projects/demo/src/modules/components/input-date-range/input-date-range.template.html
- projects/demo/src/modules/components/input-date-time/input-date-time.template.html
- projects/demo/src/modules/components/input-date/input-date.template.html
- projects/demo/src/modules/components/input-inline/input-inline.template.html
- projects/demo/src/modules/components/input-month-range/input-month-range.template.html
- projects/demo/src/modules/components/input-month/input-month.template.html
- projects/demo/src/modules/components/input-number/input-number.component.ts
- projects/demo/src/modules/components/input-number/input-number.template.html
- projects/demo/src/modules/components/input-password/input-password.template.html
- projects/demo/src/modules/components/input-phone/input-phone.template.html
- projects/demo/src/modules/components/input-tag/input-tag.template.html
- projects/demo/src/modules/components/input-time/input-time.template.html
- projects/demo/src/modules/components/input-year/input-year.template.html
- projects/demo/src/modules/components/input/input.template.html
- projects/demo/src/modules/components/line-clamp/line-clamp.template.html
- projects/demo/src/modules/components/primitive-textfield/primitive-textfield.template.html
- projects/demo/src/modules/components/rating/rating.template.html
> chore(demo): add example for align to right side

- .github/workflows/bundle-size-check.yml
> ci: skip bundlemon when it has network problems

- .eslintrc.js
> ci: enable some rules

- projects/demo/src/modules/components/pdf-viewer/examples/1/index.ts
- projects/demo/src/modules/components/pdf-viewer/examples/2/pdf-content.component.ts
- projects/demo/src/modules/components/pdf-viewer/examples/3/index.html
- projects/demo/src/modules/components/pdf-viewer/examples/3/index.ts
- projects/demo/src/modules/components/pdf-viewer/pdf-viewer.template.html
Closes #https://github.com/Tinkoff/taiga-ui/issues/2973
> chore(demo): add example where use 3rd-party service for mobile pdf

- projects/addon-editor/components/editor-socket/editor-socket.component.less
- projects/addon-editor/extensions/default-editor-extensions/default-editor-extensions.ts
- projects/addon-editor/extensions/index.ts
- projects/addon-editor/extensions/table/index.ts
- projects/addon-editor/extensions/table/ng-package.json
- projects/addon-editor/extensions/table/table.ts
Closes #2731
https://user-images.githubusercontent.com/12021443/198949898-cf376bff-6e8e-4415-9865-5c567d7254bd.mov
> fix(addon-editor): support overflow content of table

- projects/addon-editor/components/color-selector/palette/palette.component.ts
- projects/addon-editor/components/color-selector/palette/palette.style.less
- projects/addon-editor/components/color-selector/palette/palette.template.html
- projects/addon-editor/components/toolbar-tools/tools-common.less
- projects/addon-editor/styles/editor-socket.css
- projects/addon-editor/tokens/editor-options.ts
- projects/demo/src/modules/components/editor-new/editor-new.template.html
- projects/demo/src/modules/components/editor-new/examples/import/editor-options-token.md
> fix(addon-editor): support original order of colors in palette

- projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
- projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html
https://user-images.githubusercontent.com/46284632/199197827-a3c1cfc0-c19a-436a-b4b3-bd723cade3b7.mov
behavior similar to version 3.x
https://user-images.githubusercontent.com/46284632/199197881-312500fd-b06c-45b1-8305-0c99d4cceb67.mov
> fix(kit): `TabsWithMore` fix margin when exposeActive is true

- projects/demo/src/modules/components/editor/examples/8/index.ts
> chore(demo): fix absolute path in example

- .github/workflows/e2e.yml
- projects/demo-integrations/cypress/support/demo-paths.ts
> chore: fix e2e tests

- projects/addon-editor/components/editor-socket/editor-socket.component.less
> feat(addon-editor): support nested counters in ordered list

- projects/core/components/dialog/dialog.style.less
> fix(core): `Dialog` fix padding

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
- projects/addon-commerce/utils/create-auto-corrected-expire-pipe.ts
> fix(addon-commerce): fix safari expire autofill

- projects/addon-editor/components/toolbar/toolbar.component.ts
- projects/addon-editor/extensions/default-editor-extensions/default-editor-extensions.ts
- projects/addon-editor/extensions/link/index.ts
- projects/addon-editor/extensions/link/link.ts
- projects/addon-editor/extensions/link/ng-package.json
- projects/demo-integrations/cypress/tests/desktop/addon-editor/editor-links.cy.ts
- projects/demo/src/modules/components/editor/examples/8/index.ts
Closes #2970 
https://user-images.githubusercontent.com/12021443/200275782-93937375-6ad8-4c54-8177-f1776554d22d.mov
> fix(addon-editor): support write simple text after marked link

- projects/addon-editor/constants/default-editor-styles.ts
- projects/addon-editor/constants/tiptap-editor-styles.ts
- projects/addon-editor/styles/editor-socket.css
> feat(addon-editor): support nested counters in ordered

- .eslintrc.js
- package-lock.json
- package.json
- projects/eslint-plugin/package.json
> ci: support eslint 8

- projects/addon-editor/components/edit-link/edit-link.module.ts
- projects/addon-editor/components/edit-link/index.ts
- projects/addon-editor/extensions/index.ts
> chore: fix exports

- projects/kit/components/input-date-range/input-date-range.component.ts
- projects/kit/components/input-date-range/input-date-range.template.html
- projects/kit/components/input-date-time/input-date-time.template.html
- projects/kit/components/input-date/input-date.component.ts
- projects/kit/components/input-date/input-date.template.html
Closes #2960 
Icon is completely hidden when removed via DI
> fix(kit): icon in date-related components occupies space when hidden

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
- projects/addon-commerce/components/input-expire/input-expire.template.html
https://user-images.githubusercontent.com/46284632/200859151-548e1ae7-0a52-40af-9953-b721b4c607d1.mov
#3013
https://user-images.githubusercontent.com/46284632/200859198-ec36390a-9c1e-4610-a859-b56a550af25c.mov
> fix(addon-commerce): `InputExpire` fix translation in safari

- projects/addon-doc/src/components/navigation/navigation.component.ts
https://user-images.githubusercontent.com/12021443/200812191-e393b813-d574-4b1b-8324-d933aac31ebf.mov
https://user-images.githubusercontent.com/12021443/200811818-ad516970-afc0-4a48-b7d0-b806f2b8e97a.mov
> fix(addon-doc): scroll to last element in DOM if there are several

- projects/demo/src/modules/components/line-clamp/examples/4/index.html
- projects/demo/src/modules/components/line-clamp/examples/4/index.less
- projects/demo/src/modules/components/line-clamp/examples/4/index.ts
- projects/demo/src/modules/components/line-clamp/line-clamp.component.ts
- projects/demo/src/modules/components/line-clamp/line-clamp.module.ts
- projects/demo/src/modules/components/line-clamp/line-clamp.template.html
Closes https://github.com/Tinkoff/taiga-ui/issues/3032
> chore(demo): add new line-clamp example for e2e

- projects/addon-editor/constants/tiptap-editor-styles.ts
> fix(addon-editor): support long words inside bulleted or ordered list

- package-lock.json
- projects/cdk/package.json
- projects/core/components/dialog/dialog.style.less
- projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
- projects/core/components/hosted-dropdown/hosted-dropdown.template.html
- projects/demo/src/modules/components/hosted-dropdown/examples/1/index.html
- projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.component.ts
- projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.template.html
> feat(core): `HostedDropdown` add `sided` input and `close` method to context

- projects/addon-doc/src/components/navigation/navigation.component.ts
> chore(demo): fix navigation

- .github/ISSUE_TEMPLATE/1-bug-report.yml
> chore: update issue template

- projects/cdk/schematics/ng-update/constants/templates.ts
- projects/cdk/schematics/ng-update/steps/migrate-templates.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
- projects/testing/core/accordion-item.harness.ts
- projects/testing/core/accordion.harness.ts
Link: https://github.com/Tinkoff/taiga-ui/pull/3060
> chore(cdk): `tui-hosted-dropdown[tuiDropdownSided]` -> `tui-hosted-dropdown[sided=true]`

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
- projects/cdk/directives/autofilled/autofilled.style.less
- projects/core/components/primitive-textfield/primitive-textfield.style.less
- projects/core/components/primitive-textfield/textfield/textfield.style.less
- projects/core/styles/mixins/mixins.less
> fix(core): hide autofill button for Safari

- README.md
- projects/demo/src/modules/app/app.component.ts
- projects/demo/src/modules/app/app.providers.ts
> ci: add integration with codeflow

- projects/addon-editor/components/color-selector/color-edit/color-edit.template.html
- projects/addon-editor/components/color-selector/color-selector.template.html
- projects/addon-table/components/table-pagination/table-pagination.template.html
- projects/core/components/data-list/data-list.component.ts
- projects/core/components/data-list/data-list.style.less
- projects/core/components/data-list/option/option.component.ts
- projects/core/components/data-list/option/option.style.less
- projects/core/styles/mixins/picker.scss
- projects/demo/src/modules/app/version-manager/version-manager.template.html
- projects/demo/src/modules/components/data-list/data-list.template.html
- projects/demo/src/modules/components/data-list/examples/2/index.html
- projects/demo/src/modules/components/data-list/examples/2/index.ts
- projects/demo/src/modules/components/data-list/examples/3/index.html
- projects/demo/src/modules/components/input-card-grouped/examples/2/index.html
- projects/kit/components/data-list-wrapper/data-list-group-wrapper.component.ts
- projects/kit/components/data-list-wrapper/data-list-group-wrapper.template.html
- projects/kit/components/data-list-wrapper/data-list-wrapper.component.ts
- projects/kit/components/data-list-wrapper/data-list-wrapper.template.html
- projects/kit/components/data-list-wrapper/data-list-wrapper.ts
- projects/kit/components/input-time/input-time.template.html
- projects/kit/components/multi-select-option/multi-select-option.component.ts
- projects/kit/components/select-option/select-option.component.ts
> feat(core): `DataList` add `size` input, deprecate `size` for `Option`

- projects/addon-editor/abstract/editor-adapter.abstract.ts
- projects/addon-editor/components/edit-link/edit-link.style.less
- projects/addon-editor/components/editor-new/editor-new.component.html
- projects/addon-editor/components/editor-new/editor-new.component.ts
- projects/addon-editor/components/toolbar-new/toolbar-new.component.ts
- projects/addon-editor/components/toolbar-new/toolbar-new.style.less
- projects/addon-editor/components/toolbar-new/toolbar-new.template.html
- projects/addon-editor/constants/default-editor-tools.ts
- projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
- projects/addon-editor/directives/tiptap-editor/tiptap-editor.types.ts
- projects/addon-editor/enums/editor-tool.ts
- projects/addon-editor/extensions/default-editor-extensions.ts
- projects/addon-editor/extensions/file-link/file-link.ts
- projects/addon-editor/extensions/file-link/index.ts
- projects/addon-editor/extensions/file-link/ng-package.json
- projects/addon-editor/extensions/index.ts
- projects/addon-editor/index.ts
- projects/addon-editor/interfaces/attached.ts
- projects/addon-editor/interfaces/index.ts
- projects/addon-editor/tokens/files-loader.ts
- projects/addon-editor/tokens/index.ts
- projects/demo/src/environments/environment.prod.ts
- projects/demo/src/modules/components/editor-new/editor-new.component.ts
- projects/demo/src/modules/components/editor-new/editor-new.module.ts
- projects/demo/src/modules/components/editor-new/editor-new.template.html
- projects/demo/src/modules/components/editor-new/examples/9/filesio.service.ts
- projects/demo/src/modules/components/editor-new/examples/9/index.html
- projects/demo/src/modules/components/editor-new/examples/9/index.less
- projects/demo/src/modules/components/editor-new/examples/9/index.ts
> feat(addon-editor): support attach files

- projects/demo/src/modules/app/stackblitz/stackblitz-deps.constants.ts
- projects/demo/src/modules/app/stackblitz/utils.ts
Read more: 
* https://github.com/Tinkoff/taiga-ui/issues/3081
> chore(demo): `Stackblitz` temporary workaround

- projects/kit/components/stepper/stepper.component.ts
> fix(kit): `Stepper` scroll to active step when activeItemIndex changes

- projects/demo/src/modules/app/stackblitz/stackblitz-deps.constants.ts
- projects/demo/src/modules/app/stackblitz/utils.ts
Closes #3081
This reverts commit 854aeb6f4ac4b60ac66f1350c7715ac3d0884f30.
> revert(demo): `Stackblitz` temporary workaround (#3082)

- projects/demo-integrations/cypress/tests/desktop/addon-editor/anchor.cy.ts
- projects/demo-integrations/cypress/tests/desktop/demo/demo.cy.ts
- projects/demo-integrations/cypress/tests/desktop/kit/input-time/input-time.cy.ts
> ci: e2e flaky

- projects/core/directives/dropdown/dropdown-position.directive.ts
> fix(core): `Dropdown` fix direction set with binding

- projects/kit/components/stepper/step/step.style.less
Stepper gap is 2rem (32px) what is different from design
Stepper gap is 1.5rem (24px)
> fix(kit): stepper gap

- .github/workflows/build.yml
- .github/workflows/bundle-size-check.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/create-release.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/snapshots.yml
- .github/workflows/validate-tag.yml
> ci: support `actions/checkout@v3`

- projects/demo-integrations/cypress/tests/desktop/addon-editor/anchor.cy.ts
- projects/demo-integrations/cypress/tests/desktop/addon-editor/editor-api.cy.ts
- projects/demo-integrations/cypress/tests/desktop/core/marker-icon/marker-icon.cy.ts
- projects/demo-integrations/cypress/tests/desktop/core/text-area/text-area.cy.ts
- projects/demo-integrations/cypress/tests/desktop/demo/landing.cy.ts
- projects/demo-integrations/cypress/tests/desktop/kit/button/button.cy.ts
- projects/demo-integrations/cypress/tests/desktop/kit/combo-box/combo-box.cy.ts
- projects/demo-integrations/cypress/tests/desktop/kit/input-date/input-date.cy.ts
- projects/testing/cypress/snapshot/command.ts
> ci: remove redundant prefix for screenshots

- projects/demo-integrations/cypress.config.ts
- projects/demo-integrations/cypress/support/helpers/components-excluded.ts
- projects/demo-integrations/cypress/support/helpers/visit.ts
- projects/demo-integrations/cypress/support/properties/exclusions.ts
- projects/demo-integrations/cypress/tests/desktop/core/primitive-textfield/primitive-textfield.cy.ts
- projects/demo-integrations/cypress/tests/desktop/demo/demo.cy.ts
> ci: fixed time on Cypress

- projects/cdk/schematics/ng-update/constants/templates.ts
- projects/cdk/schematics/ng-update/steps/migrate-templates.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
- projects/core/components/hosted-dropdown/hosted-dropdown.template.html
- projects/core/directives/dropdown/dropdown-position-sided.directive.ts
- projects/demo-integrations/cypress/tests/desktop/kit/input/input.cy.ts
- projects/demo/src/modules/components/input/examples/3/index.html
- projects/demo/src/modules/components/input/input.template.html
> fix(kit): `Input` fix mask

- projects/demo-integrations/cypress/tests/desktop/kit/input-files/input-files.cy.ts
- projects/demo/src/modules/components/input-files/examples/6/index.html
- projects/demo/src/modules/components/input-files/examples/6/index.ts
- projects/demo/src/modules/components/input-files/input-files.component.ts
- projects/demo/src/modules/components/input-files/input-files.module.ts
- projects/demo/src/modules/components/input-files/input-files.template.html
- projects/kit/components/input-files/index.ts
- projects/kit/components/input-files/input-files.component.ts
- projects/kit/components/input-files/input-files.directive.ts
- projects/kit/components/input-files/input-files.module.ts
- projects/kit/components/input-files/input-files.options.ts
- projects/kit/components/input-files/input-files.style.less
- projects/kit/components/input-files/input-files.template.html
Closes #3063
https://user-images.githubusercontent.com/12021443/201700387-295560e2-8eb3-4544-9deb-043ff151dff9.MOV
https://user-images.githubusercontent.com/12021443/201700825-a0f5d4a4-047d-4f97-8524-ba3d547bc67e.MOV
> feat(kit): support capture in input files

- .eslintrc.js
- projects/addon-editor/utils/delete-nodes.ts
- projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
- projects/kit/components/input-date-time/test/input-date-time.component.spec.ts
- scripts/nx/decorate-angular-cli.ts
> ci: add curly rule for eslint

- scripts/eslint/common/cypress.js
> chore: fix pattern

- projects/addon-charts/components/line-chart/line-chart.component.ts
- projects/addon-charts/components/pie-chart/pie-chart.component.ts
- projects/addon-charts/utils/index.ts
- projects/addon-charts/utils/prepare-external-url.ts
> fix(addon-charts): remove location origin from mask

- projects/demo/src/modules/app/pages.ts
> chore(demo): hide `mobile-themes`

- projects/addon-charts/package.json
- projects/addon-commerce/package.json
- projects/addon-doc/package.json
- projects/addon-editor/package.json
- projects/addon-mobile/package.json
- projects/addon-preview/package.json
- projects/addon-table/components/reorder/reorder.component.ts
- projects/addon-table/components/reorder/reorder.module.ts
- projects/addon-table/components/reorder/reorder.style.less
- projects/addon-table/components/reorder/reorder.template.html
- projects/addon-table/package.json
- projects/addon-tablebars/package.json
- projects/cdk/package.json
- projects/core/package.json
- projects/demo/src/modules/components/tiles/examples/1/index.html
- projects/demo/src/modules/components/tiles/examples/2/index.html
- projects/demo/src/modules/components/tiles/examples/2/index.less
- projects/demo/src/modules/components/tiles/examples/2/index.ts
- projects/demo/src/modules/components/tiles/tiles.component.ts
- projects/demo/src/modules/components/tiles/tiles.module.ts
- projects/demo/src/modules/components/tiles/tiles.template.html
- projects/demo/src/modules/tables/reorder/examples/1/index.html
- projects/i18n/package.json
- projects/kit/components/tiles/tile.component.ts
- projects/kit/components/tiles/tiles.component.ts
- projects/kit/components/tiles/tiles.style.less
- projects/kit/package.json
> fix(addon-table): `Reorder` fix wrong order when toggling visibility

- projects/addon-charts/components/bar-set/bar-set.component.ts
- projects/addon-charts/components/bar/bar.component.ts
> fix(addon-charts): invalid getting color inside `bar`, `bar-set`

- projects/demo/src/modules/app/home/examples/nx-add.md
- projects/demo/src/modules/app/home/home.component.ts
- projects/demo/src/modules/app/home/home.template.html
> chore(demo): update nx command

- projects/demo-integrations/cypress/tests/desktop/kit/checkbox/checkbox.cy.ts
> chore: add checkbox screenshots

- projects/demo-integrations/cypress/tests/desktop/kit/input-files/input-files.cy.ts
- projects/kit/components/input-files/input-files.style.less
- projects/kit/components/input-files/input-files.template.html
> fix(kit): fixed label text align for input files

- projects/cdk/schematics/ng-update/steps/replace-styles.ts
> chore(cdk): `schematics` rename deprecated selectors

- projects/kit/components/input-phone/input-phone.component.ts
- projects/kit/components/input-phone/test/input-phone.component.spec.ts
value is truncated before updating control
Closes #3066
> fix(kit): `InputPhone` cut value by max phone length

- projects/demo/src/modules/components/tiles/examples/1/index.html
- projects/demo/src/modules/components/tiles/examples/1/index.less
- projects/demo/src/modules/components/tiles/examples/2/index.html
- projects/demo/src/modules/components/tiles/examples/2/index.less
- projects/demo/src/modules/components/tiles/tiles.template.html
- projects/kit/components/tiles/tile.component.ts
- projects/kit/components/tiles/tiles.component.ts
- projects/kit/components/tiles/tiles.style.less
> fix(kit): `Tiles` remove binding with JS to allow media query control

- projects/addon-table/components/reorder/reorder.component.ts
- projects/addon-table/components/reorder/reorder.template.html
- projects/cdk/abstract/dialog.directive.ts
- projects/demo/src/modules/components/tiles/examples/1/index.html
- projects/demo/src/modules/components/tiles/examples/1/index.less
- projects/demo/src/modules/components/tiles/examples/1/index.ts
- projects/demo/src/modules/components/tiles/examples/2/index.html
- projects/demo/src/modules/components/tiles/examples/2/index.ts
- projects/demo/src/modules/tables/reorder/examples/1/index.html
- projects/kit/components/tiles/tile.component.ts
- projects/kit/components/tiles/tiles.component.ts
- projects/kit/components/tiles/tiles.style.less
> fix(kit): `Tiles` switch to CSS `order` to prevent DOM redraw

- projects/addon-doc/README.md
> chore(addon-doc): update `README.md`

- projects/cdk/utils/svg/svg-linear-gradient-processor.ts
- projects/core/components/svg/svg.component.ts
- projects/core/tokens/svg-content-processor.ts
- projects/core/tokens/svg-src-processor.ts
- projects/demo/src/modules/components/svg/examples/1/index.ts
> feat(cdk): support `SafeHtml` input value in `tui-svg`

- projects/cdk/directives/element/element.directive.ts
> refactor: for investigate problem on stackblitz

- projects/addon-doc/src/components/demo/demo.component.ts
- projects/addon-doc/src/components/documentation/documentation.component.ts
- projects/addon-doc/src/components/documentation/documentation.module.ts
- projects/addon-doc/src/components/documentation/documentation.template.html
- projects/addon-doc/src/components/documentation/pipes/cleaner.pipe.ts
- projects/addon-doc/src/components/documentation/pipes/content-tooltip.pipe.ts
- projects/addon-doc/src/components/documentation/pipes/opacity.pipe.ts
- projects/addon-doc/src/components/documentation/pipes/optional.pipe.ts
- projects/addon-doc/src/components/documentation/pipes/primitive-polymorpheus-content.pipe.ts
- projects/addon-doc/src/components/documentation/pipes/strip-optional.pipe.ts
- projects/addon-doc/src/components/documentation/pipes/сolor.pipe.ts
Closes #3152
https://user-images.githubusercontent.com/12021443/205306328-74c96400-1f5b-4122-b80b-a8e907e21dd4.mov
> ci: support `sandboxWidth`

- projects/demo-integrations/cypress/tests/desktop/core/hint/hint.cy.ts
- projects/demo/src/modules/components/tooltip/examples/3/index.html
> chore: fix hint test, add hint tests with mode

- projects/addon-commerce/components/money/money.template.html
- projects/addon-commerce/components/money/pipes/integer-part.pipe.ts
- projects/addon-commerce/components/money/test/money.component.spec.ts
- projects/addon-commerce/components/money/utils/format-fraction-part.ts
- projects/demo/src/modules/components/money/money.component.ts
> fix(addon-commerce): truncate float values without rounding

- projects/core/directives/hint/hint.providers.ts
- projects/kit/components/line-clamp/line-clamp.component.ts
> refactor: `line-clamp`

- projects/demo/src/modules/components/avatar/avatar.template.html
- projects/kit/components/avatar/avatar.component.ts
- projects/kit/components/avatar/avatar.template.html
- projects/kit/directives/lazy-loading/lazy-loading.directive.ts
- projects/kit/directives/lazy-loading/lazy-loading.service.ts
> feat(kit): avatar now accepts SafeResourceUrl as avatarUrl

- projects/demo-integrations/cypress/support/stubs/stub-external-icons.util.ts
- projects/demo/src/modules/components/combo-box/examples/1/index.ts
- projects/demo/src/modules/components/combo-box/examples/2/database-mock-data.ts
- projects/demo/src/modules/components/input-phone/examples/3/index.ts
- projects/demo/src/modules/components/input/examples/4/index.ts
- projects/demo/src/modules/components/input/examples/8/index.ts
- projects/demo/src/modules/components/multi-select/examples/2/index.ts
- projects/demo/src/modules/components/preview/examples/1/index.ts
- projects/demo/src/modules/components/select/examples/6/index.ts
> chore(demo): failed to load resource by https

- projects/kit/components/input-files/input-files.style.less
> fix(kit): fix encapsulation problem in `input-files`

- projects/demo/src/modules/app/stackblitz/project-files/src/styles.less.md
> ci: hide scrollbar on stackblitz

- projects/demo/src/modules/app/classes/ts-file.parser.ts
- projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
> ci: `import.meta` doesn't support on stackblitz

- projects/demo-integrations/cypress/support/properties/demo-paths.ts
- projects/demo-integrations/cypress/tests/desktop/demo/demo.cy.ts
> ci: fix flaky e2e test on proprietary demo

- projects/cdk/tokens/active-element.ts
- projects/core/directives/dropdown/dropdown.directive.ts
> fix(core): `Dropdown` fix change detection inside dialogs

- .github/workflows/e2e.yml
- projects/addon-tablebars/components/table-bars-host/table-bars-host.style.less
- projects/demo-integrations/cypress/tests/mobile/addon-tablebars/table-bars-service/table-bars-service.cy.ts
> fix(addon-tablebars): fixed close button in table bar

- projects/addon-tablebars/components/table-bars-host/table-bars-host.style.less
- projects/demo-integrations/cypress/tests/addon-tablebars/table-bars-service/table-bars-service.cy.ts
> fix(addon-tablebars): fixed close button in table bar v2x

- projects/cdk/utils/dom/contains-or-after.ts
> test: failed to execute contains on Node parameter 1 is not of type Node on Jest

- projects/core/utils/miscellaneous/size-bigger.ts
> refactor: improve performance for compare the size around `O(1)`

- projects/kit/components/tiles/tile-handle.directive.ts
> fix(kit): `Tiles` fix handle inside Shadow DOM

- projects/addon-table/components/table-pagination/pagination.model.ts
- projects/addon-table/components/table-pagination/table-pagination.component.ts
- projects/addon-table/components/table-pagination/table-pagination.ts
- projects/demo/src/modules/tables/table-pagination/table-pagination.template.html
Closes #2044 
This PR adding an opportunity to subscribe to both of parameters (page and size) at once and let us to prevent behavior from the issue
> feat(addon-table): add paginationChange event

- projects/core/components/data-list/data-list.component.ts
- projects/kit/components/data-list-wrapper/data-list-wrapper.component.ts
> fix(core): `DataList` fix default size

- package-lock.json
- projects/demo/package.json
- projects/demo/src/modules/components/editor/editor.component.ts
- projects/demo/src/modules/components/editor/editor.module.ts
- projects/demo/src/modules/components/editor/editor.template.html
- projects/demo/src/modules/components/editor/examples/10/index.html
- projects/demo/src/modules/components/editor/examples/10/index.less
- projects/demo/src/modules/components/editor/examples/10/index.ts
- projects/demo/src/modules/components/editor/examples/8/index.ts
> chore(demo): add example where we parse markdown in editor

- projects/core/components/primitive-textfield/index.ts
- projects/core/components/primitive-textfield/primitive-textfield-options.ts
- projects/core/components/primitive-textfield/primitive-textfield.component.ts
- projects/core/components/primitive-textfield/primitive-textfield.template.html
- projects/core/directives/textfield-controller/index.ts
- projects/core/directives/textfield-controller/textfield-controller.provider.ts
- projects/core/directives/textfield-controller/textfield-options.ts
- projects/core/directives/textfield-controller/textfield.controller.ts
- projects/demo-integrations/cypress/tests/desktop/kit/input/input.cy.ts
- projects/demo/src/modules/components/primitive-textfield/examples/2/index.ts
- projects/kit/components/input-tag/input-tag.component.ts
- projects/kit/components/input-tag/input-tag.template.html
- projects/kit/components/tag/tag.component.ts
- projects/kit/components/tag/tag.template.html
- projects/kit/components/text-area/text-area.component.ts
- projects/kit/components/text-area/text-area.module.ts
- projects/kit/components/text-area/text-area.template.html
> feat(kit): use `tuiIconClose` for size `s`

- projects/demo-integrations/cypress/tests/desktop/demo/demo.cy.ts
- projects/demo-integrations/cypress/tests/desktop/kit/tabs/tabs.cy.ts
> ci: flaky tiles pages on e2e

- .github/workflows/create-release.yml
> ci: author identity unknown

- projects/demo-integrations/cypress/support/properties/exclusions.ts
> ci: flaky heavy editor page

- projects/demo/src/modules/tables/table/examples/3/index.html
- projects/demo/src/modules/tables/table/examples/3/index.ts
Closes #237 
https://user-images.githubusercontent.com/46284632/207359212-39b2917d-1ef8-4ad7-950f-98ab9fec587a.mov
> chore(demo): add trackBy to table example to prevent focus losing on tab

- projects/core/utils/miscellaneous/size-bigger.ts
> chore: fix by post review

- projects/cdk/services/scroll.service.ts
> feat(cdk): ScrollService support window

- projects/demo-integrations/cypress/tests/desktop/kit/input-number/input-number.cy.ts
> ci: fix flaky on e2e

- scripts/eslint/typescript.js
> ci: compat proprietary

- projects/testing/project.json
> ci: publish for `@taiga-ui/testing`

- projects/kit/components/files/file/file.style.less
> fix(kit): `File` fix background

- projects/demo-integrations/cypress/tests/desktop/kit/input-number/input-number.cy.ts
> ci: again flaky on e2e

- projects/demo/src/modules/components/text-area/examples/3/index.html
- projects/kit/components/text-area/text-area.component.ts
- projects/kit/components/text-area/text-area.style.less
> feat(kit): `TextArea` support `s` size, fix `m` font and padding

- projects/demo/src/modules/directives/active-zone/active-zone.module.ts
- projects/demo/src/modules/directives/active-zone/examples/1/index.html
- projects/demo/src/modules/directives/active-zone/examples/1/index.ts
Closes #3168
Missing `[formControl]` is added.
> docs: add missing formControl directive to fix not injected error

- projects/cdk/schematics/constants/file-globs.ts
> fix(schematics): exclude popular hidden directories

- projects/addon-doc/src/components/code/code.style.less
- projects/addon-doc/src/components/main/main.style.less
- projects/cdk/components/dialog-host/dialog-host.style.less
- projects/core/components/data-list/option/option.style.less
- projects/core/styles/theme/variables.less
- projects/core/styles/theme/wrapper/table.less
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/app/styles-info/styles-info.component.ts
- projects/demo/src/modules/app/styles-info/styles-info.module.ts
- projects/demo/src/modules/components/island/island.module.ts
- projects/demo/src/modules/components/island/island.template.html
- projects/demo/src/modules/markup/form/form.module.ts
- projects/demo/src/modules/markup/form/form.template.html
- projects/demo/src/modules/markup/grid/grid.module.ts
- projects/demo/src/modules/markup/grid/grid.template.html
- projects/demo/src/modules/markup/lists/lists.module.ts
- projects/demo/src/modules/markup/lists/lists.template.html
- projects/demo/src/modules/markup/skeleton/skeleton.module.ts
- projects/demo/src/modules/markup/skeleton/skeleton.template.html
- projects/demo/src/modules/markup/spaces/spaces.module.ts
- projects/demo/src/modules/markup/spaces/spaces.template.html
- projects/demo/src/modules/markup/tables/tables.module.ts
- projects/demo/src/modules/markup/tables/tables.template.html
- projects/demo/src/modules/markup/typography/typography.module.ts
- projects/demo/src/modules/markup/typography/typography.template.html
- projects/kit/components/push/push.style.less
- projects/styles/markup/tui-island.less
> feat(cdk): add `--tui-backdrop` variable for dialog overlay

- projects/addon-doc/src/components/demo/demo.component.ts
- projects/addon-doc/src/components/demo/demo.module.ts
- projects/addon-doc/src/components/demo/demo.style.less
- projects/addon-doc/src/components/demo/demo.template.html
- projects/cdk/directives/drag/drag.directive.ts
- projects/cdk/directives/drag/drag.module.ts
- projects/cdk/directives/index.ts
- projects/cdk/directives/resizer/index.ts
- projects/cdk/directives/resizer/ng-package.json
- projects/cdk/directives/resizer/resizeable.directive.ts
- projects/cdk/directives/resizer/resizer.directive.ts
- projects/cdk/directives/resizer/resizer.module.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/directives/resizer/examples/1/index.html
- projects/demo/src/modules/directives/resizer/examples/1/index.less
- projects/demo/src/modules/directives/resizer/examples/1/index.ts
- projects/demo/src/modules/directives/resizer/examples/import/import-module.md
- projects/demo/src/modules/directives/resizer/examples/import/insert-template.md
- projects/demo/src/modules/directives/resizer/resizer.component.ts
- projects/demo/src/modules/directives/resizer/resizer.module.ts
- projects/demo/src/modules/directives/resizer/resizer.template.html
> feat(cdk): `Resizer` add new directive

- projects/demo-integrations/cypress/tests/desktop/addon-charts/line-chart.cy.ts
- projects/demo-integrations/cypress/tests/desktop/addon-charts/pie-chart.cy.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
> chore(demo): move all `Chart`-pages to the upper level of navigation

- projects/demo/src/modules/components/badged-content/badged-content.template.html
- projects/kit/components/avatar/avatar.style.less
> chore: small fix

- projects/demo-integrations/cypress/support/properties/demo-paths.ts
> chore: exclude markdown from e2e

- .github/workflows/publish-dev.yml
- projects/addon-charts/project.json
- projects/addon-commerce/project.json
- projects/addon-doc/project.json
- projects/addon-editor/project.json
- projects/addon-mobile/project.json
- projects/addon-preview/project.json
- projects/addon-table/project.json
- projects/addon-tablebars/project.json
- projects/cdk/project.json
- projects/core/project.json
- projects/icons/project.json
- projects/kit/project.json
- projects/styles/project.json
- projects/taiga-schematics/project.json
- projects/testing/project.json
- scripts/publish-dev-builds.ts
- scripts/publish.ts
> ci: publish development version

- .github/workflows/publish-dev.yml
> ci: fix syntax error

- .github/workflows/publish-dev.yml
> ci: support trigger manually

- scripts/postbump.ts
- scripts/postinstall.ts
- scripts/publish-dev-builds.ts
- scripts/publish.ts
- scripts/shared/check-prettier-changes.ts
- scripts/shared/execute.ts
- scripts/shared/get-all-versions.ts
- scripts/shared/git-commit-and-push.ts
- scripts/shared/make-release-branch.ts
- scripts/shared/run-standard-version.ts
> ci: correct update custom version

- .github/renovate/renovate.json5
- .github/workflows/renovate.yml
> ci: add renovate bot

- projects/demo/src/modules/directives/mode/mode.template.html
> docs: about `tuiMode`

- projects/addon-table/components/table-pagination/table-pagination-options.ts
- projects/addon-table/components/table-pagination/table-pagination.component.ts
Unable to configure `items` in `TablePagination` component via `TUI_TABLE_PAGINATION_OPTIONS` token
Now we take `items` in `TablePagination` component from `TUI_TABLE_PAGINATION_OPTIONS` token
> feat(addon-table): add items to `TUI_TABLE_PAGINATION_OPTIONS` token

- projects/cdk/schematics/ng-update/utils/get-file-system.ts
- projects/cdk/schematics/ng-update/v3/steps/migrate-progress.ts
- projects/cdk/schematics/ng-update/v3/steps/migrate-sliders/migrate-input-range.ts
- projects/cdk/schematics/ng-update/v3/steps/migrate-sliders/migrate-input-slider.ts
- projects/cdk/schematics/utils/project-root.ts
> feat(cdk): `Schematics` add root path option

- projects/demo/src/modules/components/island/island.template.html
> chore(demo): fix a typo at Island component docs

- .github/workflows/publish-dev.yml
> ci: use token for publish

- projects/core/components/data-list/data-list.style.less
- projects/demo/src/modules/app/home/examples/app-module.md
> chore: fix small size data list padding

- .github/renovate/renovate.json5
> ci: renovate refactor

- .github/renovate/renovate.json5
> ci: renovate config

- projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts
#2959 
https://user-images.githubusercontent.com/46284632/209553281-4ba6b980-e80d-4e3a-bac6-83ec44926e0a.mov
https://user-images.githubusercontent.com/46284632/209553309-6efe20f8-3030-43fa-8d72-07aebdf7243f.mov
> fix(core): fix overlapping prefix and value when resizing textfield

- .github/renovate/renovate.json5
> ci: skip `optionalDependencies`

- projects/demo/src/modules/components/input-month-range/input-month-range.template.html
- scripts/eslint/html.js
> ci: no duplicate attributes

- projects/addon-table/components/table-pagination/index.ts
- projects/addon-table/components/table-pagination/table-pagination.ts
Shortest import before updates:
`import { TuiTablePagination } from '@taiga-ui/addon-table/components/table-pagination/table-pagination'`
Shortest import after updates:
`import { TuiTablePagination } from '@taiga-ui/addon-table'`
> fix(addon-table): export `TuiTablePagination`

- projects/core/components/calendar/test/calendar.component.spec.ts
- projects/core/components/primitive-calendar/primitive-calendar.template.html
- projects/core/components/primitive-spin-button/primitive-spin-button.template.html
- projects/testing/core/calendar.harness.ts
- projects/testing/core/primitive-calender.harness.ts
- projects/testing/core/primitive-year-month-pagination.harness.ts
> fix(testing): skip unavailable cell for calendar

- projects/demo-integrations/cypress/tests/desktop/kit/input-count/input-count.cy.ts
- projects/kit/components/input-count/input-count.component.ts
- projects/kit/components/input-count/test/input-count.component.spec.ts
> feat(kit): support empty value in `InputCount`

- projects/kit/components/input-count/input-count.component.ts
> chore: fix after merged into master

- projects/core/components/calendar/calendar.component.ts
- projects/demo-integrations/cypress/tests/desktop/core/calendars/calendars.cy.ts
https://user-images.githubusercontent.com/12021443/209865177-cd4d4d3f-830a-4c35-bf26-206374db9ef0.mov
https://user-images.githubusercontent.com/12021443/209865462-0522aed3-4928-4fc3-8629-3bcace8cef8f.mov
> feat(core): dynamic switch view of calendar when value changes

- projects/demo/src/modules/components/input-phone-international/input-phone-international.template.html
- projects/kit/components/input-phone-international/input-phone-international.style.less
- projects/kit/components/input-phone-international/input-phone-international.template.html
Closes #3256
`tui-input-phone-international` documentation page supports `tuiTextfieldSize` option.
Set `tuiTextfieldPrefix` and `tuiTextfieldPostfix` to an empty string.
> Input phone international improvements

- projects/demo/src/modules/app/app.style.less
- projects/demo/src/modules/info/browsers/browsers.template.html
- projects/kit/components/accordion/accordion-item/accordion-item.component.ts
- projects/kit/components/accordion/accordion-item/accordion-item.style.less
- projects/kit/components/accordion/accordion-item/accordion-item.template.html
- projects/kit/components/accordion/test/accordion.component.spec.ts
- projects/testing/core/accordion-item.harness.ts
> fix(kit): `Accordion` fix incorrectly focusing item

- projects/kit/components/select/native-select/native-select-group.component.ts
- projects/kit/components/select/native-select/native-select.component.ts
- projects/kit/components/select/native-select/native-select.ts
> fix(kit): `NativeSelect` fix readonly state

- projects/demo/src/modules/components/input-tag/examples/8/index.html
- projects/demo/src/modules/components/input-tag/examples/8/index.less
- projects/demo/src/modules/components/input-tag/examples/8/index.ts
- projects/demo/src/modules/components/input-tag/input-tag.component.ts
- projects/demo/src/modules/components/input-tag/input-tag.module.ts
- projects/demo/src/modules/components/input-tag/input-tag.template.html
- projects/kit/components/input-tag/input-tag.component.ts
- projects/kit/components/input-tag/input-tag.style.less
- projects/kit/components/input-tag/input-tag.template.html
related #3265
new input `rows` added, it limits max number of textfield rows in expandable mode, same as in `Textarea`
> feat(kit): `InputTag` add max number of rows for `expandable` mode

- projects/core/components/expand/expand.component.ts
- projects/core/directives/dropdown/dropdown-position-sided.directive.ts
- projects/core/directives/dropdown/dropdown-position.directive.ts
- projects/core/directives/dropdown/dropdown.component.ts
- projects/kit/directives/present/present.directive.ts
> feat(core): `tuiDropdownSidedOffset` add new input

- projects/core/components/expand/test/expand.component.spec.ts
> chore: fix expand unit

- projects/demo/src/modules/components/input-files/examples/1/index.html
- projects/demo/src/modules/components/input-files/examples/2/index.html
- projects/demo/src/modules/components/input-files/examples/3/index.html
- projects/demo/src/modules/components/input-files/input-files.component.ts
- projects/demo/src/modules/components/input-files/input-files.template.html
- projects/kit/components/files/file/file.component.ts
> feat(kit): add `showDelete` input prop for `TuiFileComponent`

- projects/demo/src/modules/components/abstract/dropdown-documentation/dropdown-documentation.template.html
> docs: fix typo in dropdown component documentation

- projects/addon-mobile/directives/ripple/ripple.directive.ts
> feat(addon-mobile): improve typing for `tuiRipple`

- projects/addon-charts/project.json
- projects/addon-commerce/project.json
- projects/addon-doc/project.json
- projects/addon-editor/project.json
- projects/addon-mobile/project.json
- projects/addon-preview/project.json
- projects/addon-table/project.json
- projects/addon-tablebars/project.json
- projects/cdk/project.json
- projects/core/project.json
- projects/demo/project.json
- projects/eslint-plugin/project.json
- projects/i18n/project.json
- projects/icons/project.json
- projects/kit/project.json
- projects/styles/project.json
- projects/taiga-schematics/project.json
- projects/testing/project.json
> ci: replace deprecated executor

- projects/demo/src/modules/components/input/examples/10/index.html
- projects/demo/src/modules/components/input/examples/10/index.ts
- projects/demo/src/modules/components/input/input.component.ts
- projects/demo/src/modules/components/input/input.module.ts
- projects/demo/src/modules/components/input/input.template.html
- projects/demo/src/modules/pipes/field-error/examples/4/index.html
- projects/kit/components/input-phone-international/input-phone-international.template.html
> fix(kit): use `new-password` as lucky solution for disable autofill of input elements

- projects/demo/src/modules/components/multi-select/multi-select.component.ts
- projects/demo/src/modules/components/multi-select/multi-select.template.html
- projects/kit/components/multi-select/multi-select.component.ts
- projects/kit/components/multi-select/multi-select.template.html
Closes #3265 
new input rows added, it limits max number of textfield rows in expandable mode, same as in Textarea
> feat(kit): `Multiselect` add max number of rows for expandable mode

- projects/kit/components/tabs/tab/tab.component.ts
> fix(kit): `Tabs` SSR-error `TypeError: Cannot read properties of undefined (reading 'type')`

- projects/core/services/router-link-active.service.ts
- projects/kit/components/tabs/tabs.directive.ts
Closes #3393 
SSR returns:
SSR returns:
> fix(kit): `Tabs` can't detect active tab during SSR

- projects/kit/components/input-tag/input-tag.style.less
- projects/kit/components/input-tag/input-tag.template.html
> fix(kit): `InputTag` fix overflow

- projects/demo/src/modules/components/input/examples/10/index.html
> chore: add another solution for help

- projects/addon-doc/src/components/demo/demo.template.html
> ci: improve elements pointer for e2e tests

- projects/demo/src/modules/components/line-clamp/examples/1/index.html
- projects/demo/src/modules/components/line-clamp/examples/1/index.less
- projects/demo/src/modules/components/line-clamp/examples/1/index.ts
- projects/kit/components/line-clamp/line-clamp.component.ts
> fix(kit): update statically `HostBinding` in `line-clamp`

- projects/i18n/enums/country-iso-code.ts
- projects/i18n/languages/chinese/countries.ts
- projects/i18n/languages/dutch/countries.ts
- projects/i18n/languages/english/countries.ts
- projects/i18n/languages/french/countries.ts
- projects/i18n/languages/italian/countries.ts
- projects/i18n/languages/polish/countries.ts
- projects/i18n/languages/portuguese/countries.ts
- projects/i18n/languages/russian/countries.ts
- projects/i18n/languages/spanish/countries.ts
- projects/i18n/languages/vietnamese/countries.ts
- projects/kit/components/input-phone-international/input-phone-international.component.ts
- projects/kit/components/input-phone-international/tokens/countries-masks.ts
People from New Caledonia can't enter their phone number.
New Caledonia phone number mask has been added.
> fix(kit): add missing `TUI_COUNTRIES_MASKS` for New Caledonia

- projects/core/interfaces/data-list-host.ts
- projects/demo-integrations/cypress/tests/desktop/kit/multi-select/multi-select.cy.ts
- projects/kit/components/combo-box/combo-box.component.ts
- projects/kit/components/multi-select-option/multi-select-option.component.ts
- projects/kit/components/multi-select/multi-select.component.ts
- projects/kit/components/select-option/select-option.component.ts
Closes #3386
https://user-images.githubusercontent.com/12021443/211664661-4a8a0b92-74d6-418f-98af-ad9009009514.mov
> fix(kit): support `updateOn` of `blur` and `submit` types for `multi-select` component

- package-lock.json
- package.json
- projects/demo-integrations/cypress/support/e2e.ts
- projects/demo-integrations/cypress/tests/desktop/addon-charts/pie-chart.cy.ts
- projects/demo-integrations/cypress/tests/desktop/core/marker-icon/marker-icon.cy.ts
- projects/demo-integrations/tsconfig.json
> ci: add `realHover`

- projects/demo-integrations/cypress/support/properties/demo-paths.ts
- projects/demo/src/modules/charts/line-days-chart/examples/1/index.ts
- projects/demo/src/modules/charts/line-days-chart/examples/2/index.ts
> ci: charts are generated randomly

- projects/kit/components/input-phone-international/tokens/countries-masks.ts
People from French Polynesia can't enter their phone number.
French Polynesia phone numbers have 8 digits since 2014.
French Polynesia phone number mask has been fixed.
> fix(kit): fix `TUI_COUNTRIES_MASKS` of French Polynesia

- projects/demo/src/modules/components/checkbox-block/examples/1/index.html
- projects/demo/src/modules/components/checkbox-block/examples/2/index.html
- projects/demo/src/modules/components/radio-block/examples/2/index.html
- projects/demo/src/modules/components/radio-block/examples/2/index.ts
> chore(demo): group without indicator

- projects/kit/components/input-date/input-date.component.ts
> fix(kit): revert breaking changes since v3.10

- projects/addon-doc/src/internal/see-also/see-also.template.html
> fix(addon-doc): preserve whitespace between links

- projects/addon-doc/src/components/documentation/documentation-property-connector.directive.ts
- projects/demo-integrations/cypress/tests/desktop/kit/input-phone/input-phone.cy.ts
- projects/demo/src/modules/components/input-phone/input-phone.template.html
> fix(addon-doc): convert number value to string by `documentationPropertyType`

- projects/demo/src/modules/components/color-picker/color-picker.component.ts
> chore(demo): code example is wrong for `example3`

- projects/addon-table/components/table/th/th.component.ts
- projects/addon-table/components/table/th/th.style.less
- projects/addon-table/components/table/th/th.template.html
- projects/demo/src/modules/markup/icons/icons.tokens.ts
- projects/icons/all.ts
- projects/icons/src/tuiIconSortAscending.svg
- projects/icons/src/tuiIconSortDescending.svg
> feat(addon-table): rename icons `tuiIconSortDown/tuiIconSortUp` to `tuiIconSortAscending/Descending`

- projects/cdk/schematics/ng-update/v3/steps/migrate-taiga-proprietary-icons.ts
- projects/cdk/schematics/utils/angular-json-manipulations.ts
- projects/cdk/utils/miscellaneous/index.ts
- projects/cdk/utils/miscellaneous/is-number.ts
- projects/cdk/utils/miscellaneous/is-object.ts
- projects/cdk/utils/miscellaneous/is-string.ts
- projects/cdk/utils/svg/svg-linear-gradient-processor.ts
- projects/demo/webpack.config.ts
- projects/eslint-plugin/configs/all.json
- projects/eslint-plugin/index.js
- projects/eslint-plugin/rules/no-typeof.js
- projects/icons/scripts/process-icons.ts
- projects/kit/components/avatar/avatar.component.ts
- projects/testing/cypress/snapshot/command.ts
- scripts/shared/bump-tui-deps.ts
- scripts/shared/bump-tui-version-in-package-json.ts
- scripts/shared/update-package-json-structure.ts
> feat(eslint-plugin): add `no-typeof` rule

- projects/addon-doc/src/components/documentation/documentation-property-connector.directive.ts
> ci: fix lint

- projects/cdk/schematics/ng-update/v3/constants/types.ts
> fix(cdk): `Schematics` add missing moduleSpecifier

- projects/demo-integrations/cypress/tests/desktop/kit/carousel/carousel.cy.ts
- projects/demo/src/modules/components/carousel/carousel.component.ts
- projects/demo/src/modules/components/carousel/carousel.style.less
- projects/demo/src/modules/components/carousel/carousel.template.html
- projects/kit/components/carousel/carousel.component.ts
- projects/kit/components/carousel/carousel.style.less
> feat(kit): support override padding for items in carousel

- projects/core/styles/taiga-ui-fonts.less
- projects/demo/src/modules/app/stackblitz/project-files/src/styles.less.md
- projects/demo/src/modules/app/stackblitz/starter/files/styles.less.md
- stylelint.config.js
> fix(core): remove quotes inside `url(*)` function in fonts.less

- projects/addon-table/components/table/th/th.style.less
- projects/core/styles/theme/wrapper/table.less
- projects/demo-integrations/cypress/tests/desktop/kit/input/input-table.cy.ts
> fix(core): top border of tuiTable first row's td is not visible

- projects/demo/src/modules/utils/browser/examples/1/index.html
- projects/demo/src/modules/utils/browser/examples/1/index.ts
> chore(demo): safari

- projects/cdk/schematics/ng-update/v3/steps/replace-styles.ts
- projects/cdk/schematics/ng-update/v3/tests/schematic-replace-deep-imports.spec.ts
- projects/cdk/schematics/ng-update/v3/tests/schematic-replace-styles.spec.ts
- projects/core/directives/wrapper/README.md
- projects/demo/src/modules/app/app.style.less
- projects/demo/src/modules/app/home/examples/import-local-less.md
- projects/demo/src/modules/app/home/examples/import-local-scss.md
- projects/demo/src/modules/app/home/examples/styles.less.md
- projects/demo/src/modules/app/home/home.component.ts
- projects/demo/src/modules/app/home/home.template.html
- projects/demo/src/modules/app/utils/example-content-processor/less-processor.ts
- projects/demo/src/modules/customization/wrapper/wrapper.template.html
- projects/demo/src/modules/markup/breakpoints/examples/import/import-taiga-ui-local-less.md
- projects/demo/src/modules/markup/spaces/examples/import/basic-imports-less.md
- projects/demo/src/modules/markup/spaces/examples/import/index-less.md
> feat(cdk): drop `~` imports for all `.less` files

- projects/kit/components/files/file/file-options.ts
- projects/kit/components/files/file/file.component.ts
- projects/kit/components/files/index.ts
> feat(kit): provide custom `formatSize` handler in `TuiFileComponent`

- projects/kit/components/input-slider/input-slider.style.less
> fix(kit): `InputSlider` wrong slider's width in Firefox

- package-lock.json
- projects/addon-editor/abstract/editor-adapter.abstract.ts
- projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
- projects/addon-editor/directives/tiptap-editor/tiptap-editor.types.ts
- projects/addon-editor/extensions/youtube/index.ts
- projects/addon-editor/extensions/youtube/ng-package.json
- projects/addon-editor/extensions/youtube/youtube.ts
- projects/addon-editor/package.json
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/components/editor/embed/editor-embed.component.html
- projects/demo/src/modules/components/editor/embed/editor-embed.component.ts
- projects/demo/src/modules/components/editor/embed/editor-embed.module.ts
- projects/demo/src/modules/components/editor/embed/examples/1/index.html
- projects/demo/src/modules/components/editor/embed/examples/1/index.less
- projects/demo/src/modules/components/editor/embed/examples/1/index.ts
- projects/demo/src/modules/components/editor/embed/examples/1/youtube-tool/youtube-tool.component.ts
- projects/demo/src/modules/components/editor/embed/examples/1/youtube-tool/youtube-tool.module.ts
- projects/demo/src/modules/components/editor/embed/examples/1/youtube-tool/youtube-tool.styles.less
- projects/demo/src/modules/components/editor/embed/examples/1/youtube-tool/youtube-tool.template.html
> feat(addon-editor): add `@tiptap/extension-youtube`

- projects/addon-charts/components/line-chart/line-chart-hint.directive.ts
- projects/addon-charts/components/line-chart/line-chart.component.ts
- projects/addon-charts/components/line-days-chart/line-days-chart-hint.directive.ts
- projects/addon-charts/components/line-days-chart/line-days-chart.component.ts
- projects/addon-doc/src/components/documentation/documentation.component.ts
- projects/addon-table/components/table/tr/tr.component.ts
- projects/cdk/observables/items-query-list-observable.ts
- projects/cdk/observables/test/query-list-changes.spec.ts
- projects/cdk/schematics/ng-update/v3/constants/deprecated-functions.ts
- projects/cdk/schematics/ng-update/v3/tests/schematic-replace-deprecated-functions.spec.ts
- projects/core/components/data-list/data-list.component.ts
- projects/kit/components/accordion/accordion.component.ts
- projects/kit/components/multi-select/multi-select-group/multi-select-group.component.ts
- projects/kit/components/stepper/stepper.component.ts
- projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts
> fix(addon-charts): `LineDaysChart` fix hint circle not disappearing

- package-lock.json
- projects/kit/components/stepper/stepper.component.ts
> chore: fix problem on proprietary repo

- projects/demo-integrations/cypress/tests/desktop/kit/multi-select/multi-select.cy.ts
- projects/kit/components/input-tag/input-tag.component.ts
> fix(kit): `Multiselect` fix scrolling to end

- projects/demo-integrations/cypress/support/properties/demo-paths.ts
- projects/demo-integrations/cypress/tests/desktop/demo/demo.cy.ts
> ci: fix e2e flaky

- projects/kit/components/slider/slider.style.less
> fix(kit): `InputSlider` not working `border-bottom-left-radius` for slider (Firefox)

- projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less
- projects/demo-integrations/cypress/tests/desktop/kit/input-number/input-number.cy.ts
> fix(core): use `nowrap` for content in `value-decoration`

- projects/demo/src/modules/app/app.routes.ts
> 'top'- Sets the scroll position to x = 0, y = 0 on all navigation.
> 'enabled'- Restores the previous scroll position on backward navigation, else sets the position to the anchor if one is provided, or sets the scroll position to [0, 0] (forward navigation). **This option will be the default in the future.**
Read more: https://angular.io/api/router/InMemoryScrollingOptions#scrollPositionRestoration
> chore(demo): set `scrollPositionRestoration: true`

- scripts/shared/bump-tui-deps.ts
- scripts/shared/bump-tui-version-in-package-json.ts
- scripts/shared/update-package-json-structure.ts
> ci: fix problem on release

- projects/demo-integrations/cypress.config.ts
- projects/demo-integrations/cypress/support/helpers/visit.ts
- projects/demo-integrations/cypress/tests/desktop/addon-doc/viewport.cy.ts
> ci: check fonts for some dimensions in proprietary repo

- projects/demo/src/modules/app/stackblitz/starter/files/styles.less.md
> chore(demo): broken stackblitz starter

- projects/core/styles/theme/variables.less
- projects/demo/src/modules/markup/typography/typography.template.html
- projects/styles/markup/tui-text.less
> feat(core): introduce new font variables

- projects/core/directives/dropdown/dropdown-context.directive.ts
Closes #3356 
now it works in ng14+
> fix(core): `DropdownContext` fix closing (ng14)

- projects/demo-integrations/cypress/support/properties/shared.entities.ts
- projects/demo-integrations/cypress/tests/desktop/addon-doc/navigation.cy.ts
- projects/demo-integrations/cypress/tests/desktop/addon-doc/viewport.cy.ts
- projects/demo-integrations/cypress/tests/desktop/core/marker-icon/marker-icon.cy.ts
- projects/demo-integrations/cypress/tests/desktop/demo/demo.cy.ts
> ci: fix some issues for proprietary repo

- projects/kit/components/input-phone-international/input-phone-international.template.html
> chore: remove duplicate `alt`

- projects/demo/src/modules/components/avatar/avatar.component.ts
- projects/demo/src/modules/components/editor/upload-files/editor-upload-files.component.ts
- projects/demo/src/modules/components/editor/uploading-images/editor-uploading-images.component.ts
- projects/demo/src/modules/components/elastic-container/elastic-container.component.ts
- projects/eslint-plugin/configs/all.json
- projects/eslint-plugin/index.js
- projects/eslint-plugin/rules/strict-tui-doc-example.js
Closes #3527
`strict-doc-example-extensions rule` is added.
> feat(eslint-plugin): add strict-doc-example-extensions rule

- projects/demo/src/modules/components/button/button.component.ts
- projects/demo/src/modules/components/button/button.module.ts
- projects/demo/src/modules/components/button/examples/1/index.html
- projects/demo/src/modules/components/button/examples/1/index.less
- projects/demo/src/modules/components/button/examples/1/index.ts
https://user-images.githubusercontent.com/12021443/215071467-23a6d507-37f1-42eb-a8ba-c4ec7beecf1a.mov
> chore(demo): add another example for buttons

- projects/demo/src/modules/components/avatar/avatar.component.ts
> chore(demo): `Avatar` fix `Less`-tab of `Stacking avatars`-example

- projects/demo/src/404.html
1. Use Firefox 60
2. Open https://taiga-ui.dev/browser-support
https://user-images.githubusercontent.com/35179038/215704196-871cac9d-9611-42a0-bb98-9c3d72dbef3c.mov
> chore(demo): `404.html` fix legacy Firefox `SyntaxError: expected expression, got '?'`

- projects/eslint-plugin/rules/strict-tui-doc-example.js
> chore: fix strict-tui-doc plugin

- package-lock.json
- package.json
- projects/demo/package.json
- projects/demo/project.json
Read more https://github.com/jfcere/ngx-markdown/releases/tag/v12.1.0
> chore(demo): bump dep `ngx-markdown` to `12.1.0`

- projects/demo/src/modules/customization/icon-set/icon-set.component.ts
- projects/eslint-plugin/rules/strict-tui-doc-example.js
> chore: fix extension regex

- projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
- projects/core/directives/dropdown/dropdown-hover.directive.ts
- projects/core/directives/dropdown/dropdown.component.ts
- projects/demo/src/modules/directives/dropdown-hover/examples/2/index.html
> fix(core): `DropdownHover` properly reflect state for `HostedDropdown`

- package-lock.json
- package.json
- projects/demo/package.json
- projects/demo/project.json
> chore(demo): downgrade dep `ngx-markdown` to `10.1.1`

- projects/demo/src/modules/app/home/home.component.ts
Open http://localhost:3333/getting-started#styles
> chore(demo): `Getting started`-page fix wrong import

- projects/kit/components/tabs/tabs-options.ts
- projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
> chore: add `minMoreWidth` to tabs options

- package.json
- projects/demo/project.json
- projects/demo/src/emulate/ng-zone-options.coalescing.ts
- projects/demo/src/emulate/ng-zone-options.ts
- projects/demo/src/main.browser.ts
- tsconfig.json
> ci: support debug `ngZoneRunCoalescing/ngZoneEventCoalescing`

- projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
> fix(addon-mobile): wait before update viewport dimension

- package.json
> chore: `lint-staged` remove redundant command

- projects/cdk/schematics/ng-update/v3/constants/templates.ts
- projects/cdk/schematics/ng-update/v3/tests/schematic-replace-html.spec.ts
> fix(cdk): `Schematics` add `tuiDropdownContext` migration

- projects/addon-commerce/utils/get-currency-by-code.ts
- projects/addon-commerce/utils/index.ts
- projects/addon-commerce/utils/test/get-currency-by-code.spec.ts
> feat(addon-commerce): add `tuiGetCurrencyByCode`

- projects/demo/src/modules/components/editor/embed/examples/2/index.ts
> chore(demo): music from Versus waterplea

- projects/demo-integrations/cypress/support/commands/basic.ts
- projects/demo-integrations/cypress/tests/addon-commerce/input-card-grouped.cy.ts
> chore(fix): flaky input-card

- projects/cdk/schematics/utils/angular-json-manipulations.ts
- projects/cdk/schematics/utils/templates/elements.ts
- projects/cdk/schematics/utils/templates/ng-component-input-manipulations.ts
> fix(cdk): `schematics` fix require() of ES modules error

- projects/demo/src/modules/markup/icons/customization/customization-icons.component.ts
> chore(demo): improve docs

- projects/cdk/tokens/tests/is-mobile.spec.ts
> test(cdk): cover `TUI_IS_MOBILE` token

- projects/kit/components/checkbox-labeled/checkbox-labeled.component.ts
- projects/kit/components/radio-labeled/radio-labeled.component.ts
По умолчанию свойство size у компонетов tui-radio-labeled, tui-checkbox-labeled имеет значение 'm'
По умолчанию свойство size у компонетов tui-radio-labeled, tui-checkbox-labeled имеет значение полученное из DI (TUI_RADIO_OPTIONS и TUI_CHECKBOX_OPTIONS)
> fix(kit): use `TUI_CHECKBOX_OPTIONS/TUI_RADIO_OPTIONS` for `checkbox/radio-labeled`

- projects/demo/src/modules/app/home/examples/assets.md
> chore(demo): change `json5` to `json` for assets example

- projects/demo/src/modules/components/editor/embed/examples/2/index.ts
> chore(demo): change slow stackblitz IDE to codepen

- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/components/data-list-wrapper/data-list-wrapper.component.ts
- projects/demo/src/modules/components/data-list-wrapper/data-list-wrapper.module.ts
- projects/demo/src/modules/components/data-list-wrapper/data-list-wrapper.template.html
- projects/demo/src/modules/components/data-list-wrapper/examples/1/index.html
- projects/demo/src/modules/components/data-list-wrapper/examples/1/index.ts
- projects/demo/src/modules/components/data-list-wrapper/examples/2/index.html
- projects/demo/src/modules/components/data-list-wrapper/examples/2/index.ts
- projects/demo/src/modules/components/data-list-wrapper/examples/3/index.html
- projects/demo/src/modules/components/data-list-wrapper/examples/3/index.ts
- projects/demo/src/modules/components/data-list-wrapper/examples/import/import-module.md
- projects/demo/src/modules/components/data-list-wrapper/examples/import/insert-template.md
Closes #2740
`DataListWrapper` documentation page is created.
> docs: add data-list-wrapper page

- package-lock.json
- package.json
- projects/demo/webpack.config.ts
> ci: remove `firebase-tools`

- package-lock.json
- projects/addon-editor/package.json
> fix(addon-editor): explicit provide `@tiptap/extension-blockquote`

- projects/demo/src/modules/app/stackblitz/utils.ts
> ci: skip editor as workaround

- projects/cdk/decorators/default-prop.ts
- projects/cdk/decorators/pure.ts
- projects/cdk/decorators/test/default-prop-and-pure.spec.ts
> fix(cdk): support redefine properties for parent class

- projects/core/components/dialog/dialog.providers.ts
> fix(core): `TUI_DIALOG_CLOSE_STREAM` event targets

- projects/demo/src/modules/components/dialog/examples/import/custom-dialog.md
- projects/demo/src/modules/components/dialog/examples/import/lazy-module.md
- projects/demo/src/modules/components/dialog/examples/import/module.md
- projects/demo/src/modules/components/marker-icon/examples/import/import-module.md
- projects/demo/src/modules/components/preview/examples/import/component.md
- projects/demo/src/modules/components/preview/examples/import/import-module.md
- projects/demo/src/modules/services/alerts/examples/import/module.md
- projects/demo/src/modules/services/table-bar/examples/import/module.md
> chore(demo): change `MyModule` to `AppModule`

- projects/core/directives/dropdown/dropdown-hover-options.directive.ts
- projects/core/directives/dropdown/dropdown-hover.directive.ts
- projects/core/directives/dropdown/index.ts
- projects/demo/src/modules/app/app.providers.ts
> feat(core): support options for dropdown-hover directive

- .github/actions/rebase/action.yml
- .github/workflows/e2e.yml
> ci: abort rebase when merge conflict

- projects/demo/src/modules/app/stackblitz/utils.ts
> chore(demo): fix broken stackblitz

- projects/demo/src/modules/components/island/examples/3/index.html
- projects/demo/src/modules/components/island/examples/3/index.less
- projects/demo/src/modules/components/island/island.module.ts
- projects/styles/markup/tui-island.less
https://user-images.githubusercontent.com/12021443/217771761-48467bea-8b9c-45ff-bad1-b0415b4caf9d.mov
> feat(styles): remove legacy browser clearfix

- projects/demo/src/modules/markup/icons/icons.tokens.ts
> chore: expose public icons in demo

- projects/demo/src/modules/components/editor/images/upload/examples/1/imgbb.service.ts
- projects/demo/src/modules/components/editor/upload-files/examples/1/filesio.service.ts
> chore(demo): compatibility for proprietary-demo

- projects/addon-editor/components/toolbar-tools/font-size/font-size.component.ts
- projects/addon-editor/components/toolbar-tools/font-size/font-size.template.html
- projects/addon-editor/interfaces/editor-font-option.ts
> feat(addon-editor): customize css classes for font-tool in toolbar

- package-lock.json
- projects/eslint-plugin/.npmignore
- projects/eslint-plugin/package.json
- projects/eslint-plugin/project.json
> ci: publish eslint-plugin

- package-lock.json
- projects/addon-editor/package.json
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/components/editor/focus/editor-focus.component.html
- projects/demo/src/modules/components/editor/focus/editor-focus.component.ts
- projects/demo/src/modules/components/editor/focus/editor-focus.module.ts
- projects/demo/src/modules/components/editor/focus/examples/1/index.html
- projects/demo/src/modules/components/editor/focus/examples/1/index.less
- projects/demo/src/modules/components/editor/focus/examples/1/index.ts
> feat(addon-editor): support focus extension

- projects/addon-editor/components/editor-socket/editor-socket.component.less
> feat(addon-editor): add a little bit space between top and bottom in editor

- projects/demo/src/modules/app/classes/ts-file.parser.ts
> chore(demo): don't add entity into import if already exists

- projects/core/components/svg/deprecated-icons.ts
- projects/core/components/svg/svg-options.ts
- projects/core/components/svg/svg.component.ts
- projects/demo/src/modules/components/tabs/examples/1/index.ts
- projects/demo/src/modules/markup/icons/icons.tokens.ts
- projects/icons/project.json
- projects/icons/scripts/index.ts
- projects/icons/scripts/prepare-feather-icons.ts
- projects/kit/components/files/file/file.style.less
- projects/kit/components/files/file/file.template.html
- scripts/compile-icons.ts
- scripts/preprocess-icons.ts
> chore: change to icons for proprietary packages

- package-lock.json
- package.json
> ci: cannot resolve glob

- projects/addon-editor/extensions/image-editor/image-editor.extension.ts
Closes #3600
https://user-images.githubusercontent.com/12021443/217922035-962be349-1513-4895-acab-00161d21e854.mov
> feat(addon-editor): support drop/paste event for resizable

- projects/addon-preview/components/preview/zoom/preview-zoom.template.html
- projects/demo/src/modules/components/input-inline/examples/2/template.html
- projects/demo/src/modules/components/input-range/examples/4/index.html
- projects/demo/src/modules/components/preview/examples/1/index.html
- projects/demo/src/modules/components/preview/examples/import/template.md
- projects/demo/src/modules/components/primitive-textfield/examples/1/index.html
- projects/demo/src/modules/components/primitive-textfield/primitive-textfield.module.ts
- projects/demo/src/modules/components/tabs/examples/4/index.html
- projects/demo/src/modules/pipes/field-error/examples/4/index.html
- projects/demo/src/modules/services/svg/svg.template.html
- projects/demo/src/modules/services/table-bar/examples/1/index.html
- projects/demo/src/modules/tables/table/examples/2/index.html
> chore: fix icons

- .github/workflows/publish.yml
Open https://github.com/Tinkoff/taiga-ui/actions/runs/4112137985
> ci: `publish.yml` job name typo

- projects/demo-integrations/cypress/tests/addon-editor/editor-groups.cy.ts
> ci: refactor `editor-groups.cy.ts`

- projects/core/components/dialog/index.ts
> chore: fix export `TuiDialogCloseService`

- .github/workflows/bundle-size-check.yml
- .github/workflows/e2e.yml
- projects/demo-integrations/cypress/tests/addon-commerce/input-card-grouped.cy.ts
- projects/demo-integrations/cypress/tests/core/dialogs/dialogs.cy.ts
> ci: fix e2e for proprietary repo

- projects/addon-editor/extensions/image-editor/image-editor.extension.ts
> fix(addon-editor): use `imageEditor` extension instead of `image` for copy-paste

- projects/core/components/dialog/dialog.style.less
> chore: fix styles

- projects/addon-table/components/table/tbody/tbody.style.less
- projects/core/components/link/link.style.less
- projects/demo/src/modules/components/dialog/dialog.template.html
- projects/demo/src/modules/components/link/link.component.ts
- projects/demo/src/modules/components/link/link.template.html
> chore: fix some styling issues

- projects/kit/components/input-phone-international/input-phone-international.component.ts
- projects/kit/components/input-phone/input-phone.component.ts
> fix(kit): `InputPhoneInternational` after changing country the mask does not render

- projects/addon-editor/abstract/editor-adapter.abstract.ts
- projects/addon-editor/components/toolbar-tools/font-size/font-size.component.ts
- projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-font.cy.ts
> fix(addon-editor): do not inherit previous text style for heading

- .github/ISSUE_TEMPLATE/1-bug-report.yml
- .github/ISSUE_TEMPLATE/3-docs-bug.yml
> ci: do not skip some fields

- projects/demo-integrations/cypress/tests/demo/demo.cy.ts
- projects/demo-integrations/cypress/tests/kit/line-clamp/line-clamp.cy.ts
> ci: flaky e2e

- projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
> fix(kit): `TabsWithMore` properly calculate overflow

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
- projects/addon-table/components/table/providers/table.providers.ts
- projects/core/components/primitive-textfield/primitive-textfield.component.ts
- projects/core/directives/textfield-controller/index.ts
- projects/core/directives/textfield-controller/textfield-appearance.directive.ts
- projects/core/directives/textfield-controller/textfield-controller.module.ts
- projects/core/directives/textfield-controller/textfield-controller.provider.ts
- projects/core/directives/textfield-controller/textfield.controller.ts
- projects/core/tokens/textfield-appearance.ts
- projects/demo/src/modules/customization/wrapper/examples/1/index.ts
- projects/kit/components/input-count/input-count.component.ts
- projects/kit/components/input-range/input-range.component.ts
- projects/kit/components/input-range/input-range.module.ts
- projects/kit/components/input-tag/input-tag.component.ts
- projects/kit/components/text-area/text-area.component.ts
> feat(core): implement `tuiTextfieldAppearance` directive

- projects/kit/components/tree/components/tree-item/tree-item.component.ts
- projects/kit/components/tree/components/tree/tree.component.ts
- scripts/eslint/typescript.js
Explicit calls to life cycle hooks could be confusing. Invoke life cycle hooks is the responsability of Angular.
> ci: enable `@angular-eslint/no-lifecycle-call: error`

- projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.component.html
- projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.component.ts
- projects/demo/src/modules/app/styles-info/styles-info.component.html
- projects/demo/src/modules/app/styles-info/styles-info.component.ts
- projects/demo/src/modules/components/pdf-viewer/examples/2/actions-content.component.html
- projects/demo/src/modules/components/pdf-viewer/examples/2/actions-content.component.ts
- projects/demo/src/modules/components/pdf-viewer/examples/2/pdf-content.component.html
- projects/demo/src/modules/components/pdf-viewer/examples/2/pdf-content.component.less
- projects/demo/src/modules/components/pdf-viewer/examples/2/pdf-content.component.ts
- projects/demo/src/modules/components/pdf-viewer/pdf-viewer.component.ts
- projects/demo/src/modules/decorators/pure/pure-function.component.html
- projects/demo/src/modules/decorators/pure/pure-function.component.ts
- projects/demo/src/modules/decorators/pure/pure-getter.component.html
- projects/demo/src/modules/decorators/pure/pure-getter.component.ts
- projects/demo/src/modules/decorators/pure/pure.component.ts
- projects/demo/src/modules/markup/icons/icons.component.ts
- projects/demo/src/modules/markup/icons/inline-svg/inline-svg.component.html
- projects/demo/src/modules/markup/icons/inline-svg/inline-svg.component.ts
- scripts/eslint/typescript.js
> ci: enable `@angular-eslint/component-max-inline-declarations: error`

- projects/addon-doc/src/components/language-switcher/language-switcher.component.html
- projects/addon-doc/src/components/language-switcher/language-switcher.component.ts
- projects/addon-doc/src/components/language-switcher/language-switcher.module.ts
- projects/core/pipes/flag/flag.module.ts
- projects/core/pipes/flag/flag.pipe.ts
- projects/core/pipes/flag/index.ts
- projects/core/pipes/flag/ng-package.json
- projects/core/pipes/flag/test/flag.pipe.spec.ts
- projects/core/pipes/index.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/pipes/flag/examples/1/component.ts
- projects/demo/src/modules/pipes/flag/examples/1/template.html
- projects/demo/src/modules/pipes/flag/examples/import/import-module.md
- projects/demo/src/modules/pipes/flag/examples/import/insert-template.md
- projects/demo/src/modules/pipes/flag/flag.component.ts
- projects/demo/src/modules/pipes/flag/flag.module.ts
- projects/demo/src/modules/pipes/flag/flag.template.html
- projects/kit/components/input-phone-international/input-phone-international.component.ts
- projects/kit/components/input-phone-international/input-phone-international.module.ts
- projects/kit/components/input-phone-international/input-phone-international.template.html
- projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
> feat(core): new `tuiFlag` pipe

- projects/addon-doc/src/components/example/example-options.ts
- projects/addon-doc/src/components/example/example.component.ts
- projects/addon-doc/src/public-api.ts
> feat(addon-doc): new `TUI_DOC_EXAMPLE_OPTIONS` DI-token

- projects/demo/src/modules/app/home/examples/nx-migrate.md
- projects/demo/src/modules/app/home/home.component.ts
- projects/demo/src/modules/app/home/home.template.html
> chore(demo): add a command to run Nx migrations

- projects/cdk/schematics/ng-update/v3/constants/warnings.ts
- [] Bugfix
Just some text changes.
> fix(cdk): correct schematics' messages

- README.md
- jest.config.ts
- projects/addon-charts/project.json
- projects/addon-commerce/project.json
- projects/addon-doc/project.json
- projects/addon-editor/project.json
- projects/addon-mobile/project.json
- projects/addon-preview/project.json
- projects/addon-table/project.json
- projects/addon-tablebars/project.json
- projects/cdk/project.json
- projects/core/project.json
- projects/demo/project.json
- projects/eslint-plugin/project.json
- projects/i18n/project.json
- projects/icons/project.json
- projects/kit/project.json
- projects/styles/project.json
- projects/testing/project.json
> ci: compat with WindowsOS

- projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
> fix(kit): `TabsWithMore` sync max index on active index change

- projects/addon-doc/src/components/language-switcher/language-switcher.component.ts
- projects/addon-doc/src/tokens/example-content-processor.ts
- projects/addon-editor/components/toolbar-tools/font-style/font-style.component.ts
- projects/addon-editor/components/toolbar/toolbar.component.ts
- projects/cdk/directives/for-async/test/for.directive.spec.ts
- projects/demo-integrations/cypress/support/helpers/components-excluded.ts
- projects/demo/src/modules/components/combo-box/examples/1/index.ts
- projects/kit/components/arrow/arrow-options.ts
- projects/kit/components/tree/directives/tree-controller.directive.ts
- projects/kit/tokens/i18n.ts
- scripts/eslint/typescript.js
> ci: add typescript-eslint rules

- projects/demo-integrations/cypress/support/stubs/stub-external-icons.util.ts
> ci: stub `raw.github*`

- projects/kit/components/elastic-container/elastic-container.component.html
- projects/kit/components/elastic-container/elastic-container.component.less
> chore: fix small issue with margin collapse

- projects/demo-integrations/cypress/tests/kit/input-date/input-date.mobile.cy.ts
- projects/demo/src/modules/components/input-date/examples/6/index.html
- projects/demo/src/modules/components/input-date/examples/6/index.ts
- projects/demo/src/modules/components/input-date/input-date.component.ts
- projects/demo/src/modules/components/input-date/input-date.module.ts
- projects/demo/src/modules/components/input-date/input-date.template.html
- projects/kit/components/input-date/input-date.component.ts
- projects/kit/components/input-date/input-date.module.ts
- projects/kit/components/input-date/input-date.template.html
- projects/kit/components/input-date/native-date/native-date.component.ts
- projects/kit/components/input-date/native-date/native-date.style.less
- projects/kit/tokens/input-date-options.ts
#1358
https://user-images.githubusercontent.com/46284632/222679235-f8d422c6-c81a-42bb-b027-3e0661ef951f.mov
> feat(kit): `InputDate` add ability to use native date picker on mobile

- projects/kit/components/input-date/input-date.component.ts
- projects/kit/components/input-date/input-date.directive.ts
- projects/kit/components/input-date/native-date/native-date.component.ts
> chore: fix native date reset

- projects/cdk/schematics/ng-update/v3/steps/replace-styles.ts
> fix(cdk): `schematics` fix global-styles migration

- projects/demo-integrations/cypress/support/helpers/visit.ts
- projects/demo-integrations/cypress/tests/kit/multi-select/multi-select.cy.ts
- projects/demo/src/modules/app/cypress.less
> ci: support `_paused-animation` for E2E

- projects/demo-integrations/cypress/support/helpers/visit.ts
- projects/demo-integrations/cypress/tests/kit/multi-select/multi-select.cy.ts
- projects/demo/src/modules/app/cypress.less
> ci: use `_stop-animation` instead `_pause-animation` for E2E

- projects/demo-integrations/cypress/tests/kit/input-tag/input-tag.cy.ts
- projects/demo/src/modules/components/input-tag/input-tag.template.html
- projects/demo/src/modules/components/multi-select/multi-select.template.html
- projects/kit/components/input-tag/input-tag.style.less
> fix(kit): `InputTag`, `Multiselect` fix placeholder

- package-lock.json
- package.json
- projects/demo-integrations/cypress/support/e2e.ts
- projects/demo-integrations/cypress/tests/kit/routable/lazy-routable-dialog.cy.ts
- projects/demo-integrations/cypress/tests/kit/routable/routable-dialog.cy.ts
- projects/demo-integrations/tsconfig.json
- projects/demo/src/modules/customization/routable/eager/examples/2/dialog-content.component.ts
- projects/demo/src/modules/customization/routable/eager/examples/2/page-2.component.html
- projects/demo/src/modules/customization/routable/eager/examples/2/page-2.component.ts
- projects/demo/src/modules/customization/routable/eager/examples/2/page-2.module.ts
- projects/demo/src/modules/customization/routable/eager/routable-dialog.component.ts
- projects/demo/src/modules/customization/routable/eager/routable-dialog.module.ts
- projects/demo/src/modules/customization/routable/eager/routable-dialog.template.html
No documentation how to use routable dialogs with named outlets.
Closes # 
Added example how to use routable dialog with named outlets.
> feat(demo): add example with named outlets

- projects/demo/src/modules/components/input-count/input-count.module.ts
- projects/demo/src/modules/components/input-count/input-count.template.html
- projects/kit/components/input-count/input-count.component.ts
- projects/kit/components/input-count/input-count.directive.ts
- projects/kit/components/input-count/input-count.module.ts
- projects/kit/components/input-count/input-count.template.html
- projects/kit/components/input-count/test/input-count.component.spec.ts
> fix(kit): `InputCount` fix formatting, fix cutting by min value, use `InputNumber` inside

- projects/cdk/directives/for-async/for-async.directive.ts
> fix(cdk): improve type annotation for `tuiForAsync`

- projects/core/components/primitive-spin-button/primitive-spin-button.module.ts
- projects/core/components/primitive-spin-button/primitive-spin-button.style.less
- projects/core/components/primitive-spin-button/primitive-spin-button.template.html
- projects/core/components/primitive-spin-button/test/primitive-spin-button.component.spec.ts
Just a small step in simplifying the way we handle focus-visible
> chore: simplify spin button

- projects/core/components/primitive-textfield/textfield/textfield.style.less
- projects/demo-integrations/cypress/tests/core/text-area/text-area.cy.ts
> fix(core): `Textarea` fix line breaks in disabled/readonly state

- projects/kit/components/pdf-viewer/pdf-viewer.style.less
> fix(kit): use ellipsis for label in `pdf-viewer` when overflow text

- projects/kit/components/input-count/input-count.component.ts
- projects/kit/components/input-count/test/input-count.component.spec.ts
> fix(kit): `InputCount` fix cutting by min

- projects/demo/project.json
> chore: fix `project.json`

- projects/cdk/utils/browser/is-safari.ts
- projects/cdk/utils/browser/test/browsers.spec.ts
> fix(cdk): correct detect that is safari

- .github/workflows/auto-add-to-project.yml
- .github/workflows/auto-author-assign.yml
- .github/workflows/auto-label.yml
- .github/workflows/auto-rebase.yml
- .github/workflows/auto-update-deps-renovate.yml
- .github/workflows/build.yml
- .github/workflows/bundle-size-check.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/create-release.yml
- .github/workflows/deploy-gh-pages.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/publish-dev.yml
- .github/workflows/publish.yml
- .github/workflows/snapshots.yml
- .github/workflows/test.yml
- .github/workflows/validate-tag.yml
> ci: improve titles for workflows

- projects/eslint-plugin/utils/get-decorators.js
> refactor: improved `get-decorators.js`

- projects/kit/components/line-clamp/line-clamp.style.less
> fix(kit): use wrap for non-breaking string in `line-clamp`

- projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
- projects/demo/src/modules/components/editor/images/resizable/examples/1/index.html
- projects/demo/src/modules/components/editor/images/resizable/examples/1/index.ts
Closes #3814
https://user-images.githubusercontent.com/12021443/225297068-b04493cf-0e16-4bbc-bda1-14e9661a5b03.mov
> fix(addon-editor): dispatch `ImageNode` in `viewModel`

- .github/workflows/deploy-gh-pages.yml
> ci: fix trigger

- projects/demo/src/modules/app/abstract.app.ts
- projects/demo/src/modules/app/version-manager/version-manager.component.ts
- projects/demo/src/modules/app/version-manager/version-manager.providers.ts
- projects/demo/src/modules/app/version-manager/versions.constants.ts
> chore: revert some changes

- projects/core/components/dialog/dialog.component.ts
- projects/demo-integrations/cypress/tests/core/dialogs/dialogs.cy.ts
- projects/demo/src/modules/components/dialog/examples/8/index.html
- projects/demo/src/modules/components/dialog/examples/8/index.ts
- projects/kit/index.ts
- projects/kit/services/dialog-form.service.ts
- projects/kit/services/index.ts
- projects/kit/services/ng-package.json
> feat(kit): `DialogForm` add new service

- .github/workflows/auto-add-to-project.yml
- .github/workflows/auto-author-assign.yml
- .github/workflows/auto-label.yml
- .github/workflows/auto-rebase-v3.yml
- .github/workflows/auto-rebase.yml
- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/create-release.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/snapshots.yml
- .github/workflows/test.yml
- .github/workflows/validate-tag.yml
> ci: update workflows

- projects/core/tokens/number-format.ts
- projects/demo/src/modules/components/input-number/examples/4/index.ts
- projects/demo/src/modules/components/input-number/examples/5/index.ts
- projects/demo/src/modules/components/input-range/examples/2/index.ts
- projects/demo/src/modules/components/money/examples/5/index.ts
- projects/kit/components/input-number/test/input-number-format.spec.ts
> feat(core): add helper `tuiNumberFormatProvider`

- projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
- projects/core/components/hosted-dropdown/hosted-dropdown.template.html
- projects/demo-integrations/cypress/tests/core/dropdown/dropdown.cy.ts
> fix(core): escape event doesn't work in Safari

- projects/demo/src/modules/markup/skeleton/examples/1/index.html
- projects/demo/src/modules/markup/skeleton/examples/1/index.less
- projects/demo/src/modules/markup/skeleton/examples/1/index.ts
- projects/demo/src/modules/markup/skeleton/skeleton.module.ts
- projects/demo/src/modules/markup/skeleton/skeleton.template.html
- projects/styles/markup/tui-skeleton.less
> feat(styles): add `--tui-skeleton-radius` for skeleton

- projects/kit/components/input-time/input-time.component.ts
- projects/kit/components/input-time/input-time.template.html
> fix(kit): `InputTime` fix wrong preudofocus state

- scripts/eslint/typescript.js
> ci: support `no-duplicate-enum-values`

- projects/i18n/interfaces/language.ts
- scripts/eslint/typescript.js
> ci: support `consistent-type-definitions`

- scripts/eslint/typescript.js
> ci: support `triple-slash-reference`

- projects/addon-charts/components/legend-item/legend-item.style.less
> fix(addon-charts): `dot` dont shrink to fit own width for `legend-item`

- scripts/eslint/typescript.js
> ci: support `no-non-null-asserted-optional-chain`

- projects/addon-doc/src/utils/inspect.ts
- projects/addon-editor/utils/legacy-converter.ts
- projects/core/directives/dropdown/dropdown.component.ts
- scripts/eslint/typescript.js
> ci: support `switch-exhaustiveness-check`

- renovate.json
> ci: `renovate` should be update `optionalDependencies`

- scripts/eslint/typescript.js
> ci: support `prefer-includes`

- scripts/eslint/typescript.js
> ci: support `ban-types`

- scripts/eslint/typescript.js
> ci: support `no-implied-eval`

- scripts/eslint/typescript.js
> ci: support `no-confusing-non-null-assertion`

- jest.config.ts
- projects/cdk/abstract/theme-switcher.ts
- projects/cdk/components/dropdown-host/test/dropdown-portal.service.spec.ts
- projects/cdk/utils/focus/tests/is-native-focused-in.spec.ts
- projects/demo/src/modules/pipes/field-error/examples/4/index.ts
- projects/kit/components/action/test/action.component.spec.ts
- projects/kit/components/routable-dialog/test/routable-dialog.component.spec.ts
- scripts/eslint/typescript.js
> ci: support `consistent-type-assertions`

- package.json
- projects/addon-mobile/components/sheet/directives/sheet-close/sheet-close.directive.ts
- projects/addon-mobile/components/sheet/ios.hacks.ts
- projects/addon-mobile/components/sheet/sheet.directive.ts
- projects/cdk/abstract/dialog.directive.ts
- projects/cdk/directives/obscured/obscured.directive.ts
- projects/cdk/observables/focus-visible-observable.ts
- projects/cdk/observables/if-map.ts
- projects/cdk/observables/index.ts
- projects/cdk/utils/miscellaneous/index.ts
- projects/cdk/utils/miscellaneous/is-falsy.ts
- projects/demo/src/modules/components/sheet/examples/1/index.ts
- projects/demo/src/modules/pipes/field-error/examples/2/index.ts
- projects/demo/src/modules/tables/table/examples/4/index.ts
- projects/kit/components/carousel/carousel.directive.ts
- projects/kit/components/push/push-alert.directive.ts
> fix(cdk): `tuiIfMap` add operator

- projects/cdk/directives/resizer/resizeable.directive.ts
- projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts
- projects/demo-integrations/cypress/support/commands/basic.ts
- projects/demo-integrations/cypress/support/helpers/type-tab.ts
- projects/demo-integrations/cypress/tests/deep/deep.cy.ts
- projects/demo/src/modules/components/dialog/examples/2/dialog-example/dialog-example.component.ts
- projects/demo/src/modules/components/preview/examples/1/index.ts
- projects/demo/src/modules/components/preview/examples/2/index.ts
- projects/demo/src/modules/components/preview/examples/3/index.ts
- projects/kit/components/push/push-alert.directive.ts
- scripts/eslint/typescript.js
> ci: support `no-unnecessary-type-arguments`

- projects/addon-doc/src/components/navigation/navigation.providers.ts
- projects/demo/src/modules/components/input-slider/examples/2/index.ts
- projects/kit/components/input-files/max-size-rejection-error.pipe.ts
- scripts/eslint/typescript.js
> ci: support `restrict-plus-operands`

- projects/addon-doc/src/internal/see-also/see-also.component.ts
- projects/addon-doc/src/tokens/pages.ts
- projects/addon-doc/src/utils/to-flat-map-pages.ts
- projects/demo/src/modules/app/pages.ts
Find see also route link for every item: `O(n)`
Find see also route link for every item: `O(1)`
> feat(addon-doc): add `TUI_DOC_MAP_PAGES` for cached map pages

- scripts/eslint/typescript.js
> ci: support `no-unnecessary-qualifier`

- nx.json
- projects/addon-charts/project.json
- projects/addon-commerce/project.json
- projects/addon-doc/project.json
- projects/addon-editor/project.json
- projects/addon-mobile/project.json
- projects/addon-preview/project.json
- projects/addon-table/project.json
- projects/addon-tablebars/project.json
- projects/cdk/project.json
- projects/core/project.json
- projects/eslint-plugin/project.json
- projects/i18n/project.json
- projects/icons/project.json
- projects/kit/project.json
- projects/styles/project.json
- projects/taiga-schematics/project.json
> ci: correct graph

- projects/cdk/components/dropdown-host/dropdown-host.component.ts
- projects/cdk/components/dropdown-host/dropdown-host.template.html
- projects/cdk/components/dropdown-host/test/dropdown-host.component.spec.ts
- projects/core/directives/dropdown/dropdown.component.ts
- projects/core/directives/hint/hint.component.ts
- projects/core/services/index.ts
- projects/core/services/visual-viewport.service.ts
https://user-images.githubusercontent.com/46284632/226590315-95dfa1a5-472a-46ef-b31a-5479c28327e6.mov
Closes #3880
https://user-images.githubusercontent.com/46284632/226590424-4047b08d-e898-466f-b669-0339983a9afe.mov
> fix(core): fix `Hint` position on pinch-to-zoom in webkit

- projects/addon-mobile/components/sheet/components/sheet-heading/sheet-heading.style.less
- projects/addon-mobile/components/sheet/components/sheet/sheet.style.less
- projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.style.less
- projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.template.html
- projects/addon-mobile/components/sheet/directives/sheet-wrapper/sheet-wrapper.directive.ts
- projects/addon-mobile/components/sheet/ios.hacks.ts
- projects/cdk/directives/overscroll/overscroll.directive.ts
- projects/core/components/dialog/dialog.style.less
- projects/demo/src/modules/components/sheet/examples/5/index.less
> fix(addon-mobile): `Sheet` disable scroll snap for Firefox

- projects/addon-doc/src/components/example/example.module.ts
- projects/addon-doc/src/components/example/example.template.html
- projects/addon-doc/src/interfaces/code-editor.ts
- projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
- projects/demo/src/modules/app/stackblitz/starter/stackblitz-edit-button.component.ts
- projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.module.ts
> feat(addon-doc): support `icon` for code editor button

- projects/core/components/hosted-dropdown/hosted-dropdown.template.html
- projects/demo/src/modules/components/hosted-dropdown/examples/2/index.html
> fix(core): `HostedDropdown` properly detect size in case of custom host

- .github/workflows/auto-remove-label.yml
> ci: auto remove label on closed issue

- scripts/eslint/typescript.js
> ci: support `prefer-const`

- renovate.json
> ci: grouping taiga packages by renovate

- projects/addon-editor/extensions/table/table.ts
- projects/cdk/abstract/interactive.ts
- projects/demo/src/modules/components/filter/filter.component.ts
- scripts/eslint/typescript.js
> ci: support `prefer-logical-operator-over-ternary`

- projects/demo-integrations/cypress/tests/kit/multi-select/multi-select.cy.ts
- projects/kit/components/multi-select/multi-select-group/multi-select-group.style.less
> fix(kit): align for multiSelectTexts

- projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/components/editor/custom-tool/color-picker/editor-color-picker.component.html
- projects/demo/src/modules/components/editor/custom-tool/color-picker/editor-color-picker.component.ts
- projects/demo/src/modules/components/editor/custom-tool/color-picker/editor-color-picker.module.ts
- projects/demo/src/modules/components/editor/custom-tool/color-picker/examples/1/custom-color-picker/custom-color-picker.component.html
- projects/demo/src/modules/components/editor/custom-tool/color-picker/examples/1/custom-color-picker/custom-color-picker.component.less
- projects/demo/src/modules/components/editor/custom-tool/color-picker/examples/1/custom-color-picker/custom-color-picker.component.ts
- projects/demo/src/modules/components/editor/custom-tool/color-picker/examples/1/custom-color-picker/custom-color-picker.module.ts
- projects/demo/src/modules/components/editor/custom-tool/color-picker/examples/1/index.html
- projects/demo/src/modules/components/editor/custom-tool/color-picker/examples/1/index.ts
> feat(addon-editor): support custom full color picker

- projects/cdk/pipes/index.ts
- projects/cdk/pipes/is-present/index.ts
- projects/cdk/pipes/is-present/is-present.module.ts
- projects/cdk/pipes/is-present/is-present.pipe.ts
- projects/cdk/pipes/is-present/ng-package.json
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/pipes/is-present/examples/1/component.ts
- projects/demo/src/modules/pipes/is-present/examples/1/template.html
- projects/demo/src/modules/pipes/is-present/examples/import/import-module.md
- projects/demo/src/modules/pipes/is-present/examples/import/insert-template.md
- projects/demo/src/modules/pipes/is-present/is-present.component.ts
- projects/demo/src/modules/pipes/is-present/is-present.module.ts
- projects/demo/src/modules/pipes/is-present/is-present.template.html
Closes #3991
Adds a `tuiIsPresent` pipe to v2.
> feat(cdk): implement `tuiIsPresent` pipe in v2

- projects/demo/src/modules/app/abstract.app.ts
- projects/demo/src/modules/app/version-manager/version-manager.component.ts
- projects/demo/src/modules/app/version-manager/version-manager.providers.ts
- projects/demo/src/modules/app/version-manager/versions.constants.ts
> ci: refactor for proprietary-demo

- projects/kit/components/input-tag/input-tag.style.less
- projects/kit/components/input-tag/input-tag.template.html
> fix(kit): `InputTag` remove trailing comma for non editable mode

- projects/demo/src/modules/components/input-files/examples/5/index.html
- projects/demo/src/modules/components/input-files/examples/5/index.less
- projects/demo/src/modules/components/input-files/input-files.module.ts
- projects/kit/components/input-files/input-files.component.ts
- projects/kit/components/input-files/input-files.style.less
- projects/kit/components/input-files/input-files.template.html
> feat(kit): `InputFiles` customize content

- projects/core/styles/theme/variables.less
> fix(core): increase default font size from 15px to 16px to remove iOS zoom

- projects/addon-editor/components/editor-socket/editor-socket.component.less
- projects/addon-editor/components/editor-socket/styles/details.less
- projects/addon-editor/extensions/details/details.extension.ts
- projects/demo-integrations/cypress/support/editor/html.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts
> feat(addon-editor): improve styles for `details` component

- projects/kit/components/text-area/text-area.style.less
> fix(kit): align placeholder

- projects/cdk/directives/resizer/resizer.directive.ts
> fix(cdk): `Resizer` leave irrelevant dimensions untouched

- projects/addon-editor/components/editor/editor.component.ts
- projects/demo-integrations/cypress/support/editor/helpers.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-links.cy.ts
- projects/demo/src/modules/components/editor/images/upload/editor-upload-images.module.ts
- projects/demo/src/modules/components/editor/images/upload/examples/1/image-loader.ts
- projects/demo/src/modules/components/editor/images/upload/examples/1/imgbb.service.ts
- projects/demo/src/modules/components/editor/images/upload/examples/1/index.html
- projects/demo/src/modules/components/editor/images/upload/examples/1/index.ts
> fix(addon-editor): trigger `updateValueAndValidity` after `focus/blur` events in `tui-editor`

- projects/kit/components/stepper/stepper.component.ts
TuiStepperComponent does not change the state on navigate by router.
TuiStepperComponent changes the state on navigate by router.
> fix(kit): TuiStepperComponent - add markForCheck on activate step

- projects/core/components/tooltip/tooltip.component.ts
- projects/core/directives/hint/hint-hover.directive.ts
> feat(core): `Tooltip` close on click

- SECURITY.md
> chore: add `SECURITY.md`

- projects/addon-editor/components/editor-socket/styles/details.less
- projects/demo-integrations/cypress/support/editor/html.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts
> fix(addon-editor): compatibility with legacy html model of previous versions

- projects/addon-editor/components/editor-resizable/editor-resizable.abstract.ts
- projects/cdk/abstract/control.ts
- projects/cdk/abstract/interactive.ts
- projects/cdk/directives/auto-focus/handlers/abstract.handler.ts
- projects/demo/src/modules/app/abstract.app.ts
- projects/kit/components/data-list-wrapper/data-list-wrapper.ts
> fix(cdk): remove `protected` from abstract classes for DI

- .github/PULL_REQUEST_TEMPLATE.md
> docs: change PULL_REQUEST_TEMPLATE.md

- CONTRIBUTING.md
- package.json
> chore: update test command and CONTRIBUTING.md

- projects/demo/src/modules/info/related/related.template.html
> chore(demo): add `Maskito` to `Friendly libraries` documentation page

- projects/kit/package.json
> fix(kit): add missing dependency `@ng-web-apis/resize-observer`

- projects/kit/components/input-slider/input-slider.template.html
https://github.com/Tinkoff/taiga-ui/issues/4028
> fix(kit): `InputSlider` broken disabled state

- projects/demo-integrations/cypress/tests/kit/tree/tree.cy.ts
- projects/kit/components/tree/components/tree/tree.component.ts
> fix(kit): `Tree` fix programmatic control

- .github/ISSUE_TEMPLATE/2-feature-request.yml
> chore: simplify issue template for feature request

- jest.config.ts
> ci: skip redundant ngcc processing before running unit tests

- projects/cdk/utils/svg/svg-linear-gradient-processor.ts
- projects/cdk/utils/svg/tests/svg-linear-gradient-processor.spec.ts
Closes #4045
Fix regexp for svg linear gradient. add some unit tests too.
> fix(cdk): correct extraction of id for processing in svg

- projects/core/components/link/link.style.less
> fix(core): `Link` delete wrong icon opacity

- projects/core/components/error/error.component.ts
- projects/core/components/error/error.style.less
- projects/core/components/error/error.template.html
- projects/core/components/expand/expand.component.ts
- projects/core/components/expand/expand.template.html
- projects/core/components/expand/test/expand.component.spec.ts
> fix(core): `Error` fix animation inside `Expand`

- projects/demo/src/modules/customization/dialogs/examples/1/prompt/prompt.component.ts
> chore: add closing example to custom dialog

- .browserslistrc
> ci: change `.browserslistrc`

- projects/addon-editor/components/color-selector/color-edit/color-edit.template.html
- projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts
- projects/demo/src/modules/components/input-number/examples/1/index.html
- projects/demo/src/modules/components/input-number/examples/2/index.html
- projects/demo/src/modules/components/input-number/examples/4/index.html
- projects/demo/src/modules/components/input-number/examples/5/index.html
- projects/demo/src/modules/components/input-time/examples/5/index.html
- projects/demo/src/modules/markup/form/example/index.html
- projects/demo/src/modules/pipes/currency/currency.module.ts
- projects/demo/src/modules/pipes/currency/currency.template.html
- projects/demo/src/modules/pipes/currency/examples/2/template.html
- projects/demo/src/modules/pipes/field-error/examples/6/index.html
> fix(core): `PrimitiveTextfield` don't show decoration when placeholder is present

- projects/core/styles/theme/wrapper/textfield.less
> feat(core): `Textfield` add unfocused error state

- projects/core/components/hosted-dropdown/accessor-proxy.directive.ts
- projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
- projects/core/components/hosted-dropdown/hosted-dropdown.module.ts
- projects/core/components/hosted-dropdown/hosted-dropdown.template.html
- projects/core/components/hosted-dropdown/index.ts
- projects/demo-integrations/cypress/tests/core/dropdown/dropdown.cy.ts
- projects/demo/src/modules/components/hosted-dropdown/examples/5/accessor.ts
- projects/demo/src/modules/components/hosted-dropdown/examples/5/index.html
- projects/demo/src/modules/components/hosted-dropdown/examples/5/index.less
- projects/demo/src/modules/components/hosted-dropdown/examples/5/index.ts
- projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.component.ts
- projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.module.ts
- projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.template.html
> feat(core): `HostedDropdown` support custom `PositionAccessor` directives

- projects/addon-editor/components/color-selector/color-selector.component.ts
- scripts/eslint/off.js
- scripts/eslint/typescript.js
> ci: enable `require-array-sort-compare`

- projects/demo/src/modules/components/multi-select/examples/1/index.html
- projects/demo/src/modules/components/multi-select/examples/1/index.ts
- projects/demo/src/modules/components/multi-select/multi-select.component.ts
- projects/demo/src/modules/components/multi-select/multi-select.template.html
- projects/kit/components/input-tag/input-tag.component.ts
- projects/kit/components/input-tag/test/input-tag.component.spec.ts
- projects/kit/components/multi-select/multi-select.component.ts
- projects/kit/components/multi-select/multi-select.template.html
> feat(kit): `Multiselect` add tag validator

- projects/core/components/loader/loader.style.less
- projects/core/components/loader/loader.template.html
- projects/core/components/notification/notification.component.ts
- projects/core/components/notification/notification.style.less
- projects/core/directives/textfield-controller/textfield-options.ts
- projects/demo/src/modules/components/tag/tag.component.ts
- projects/kit/components/accordion/accordion-item/accordion-item.component.ts
- projects/kit/components/accordion/accordion-item/accordion-item.style.less
- projects/kit/components/badge/badge.component.ts
- projects/kit/components/badge/badge.style.less
- projects/kit/components/badged-content/badged-content.component.ts
- projects/kit/components/badged-content/badged-content.style.less
- projects/kit/components/checkbox-block/checkbox-block.component.ts
- projects/kit/components/checkbox-block/checkbox-block.style.less
- projects/kit/components/input-tag/test/input-tag-no-mode.component.spec.ts
- projects/kit/components/radio-block/radio-block.component.ts
- projects/kit/components/radio-block/radio-block.style.less
- projects/kit/components/radio-list/radio-list.component.ts
- projects/kit/components/radio-list/radio-list.style.less
- projects/kit/components/tag/tag.component.ts
- projects/kit/components/tag/tag.style.less
- projects/kit/components/tag/tag.template.html
- projects/testing/core/accordion-item.harness.ts
- projects/testing/core/badge.harness.ts
> fix(kit): `Tag` fix padding

- scripts/eslint/off.js
> ci: skip `prettier` for eslint

- projects/cdk/schematics/ng-update/v3/steps/migrate-polymorpheus.ts
- projects/cdk/schematics/ng-update/v3/tests/schematic-migrate-polymorpheus.spec.ts
> fix(schematics): case sensitivity in template from `let-*` instruction not preserved after parsing

- projects/addon-editor/components/color-selector/color-selector.component.ts
- projects/addon-table/components/table/th/th.component.ts
- projects/addon-table/utils/default-sort.ts
- projects/cdk/utils/miscellaneous/default-sort.ts
- projects/cdk/utils/miscellaneous/index.ts
- projects/demo/src/modules/tables/table/examples/3/index.ts
- projects/demo/src/modules/tables/table/examples/4/index.ts
> feat(cdk): move `tuiDefaultSort` from `@taiga-ui/addon-table`

- projects/cdk/abstract/control.ts
- projects/cdk/abstract/interactive.ts
> fix(cdk): remove `protected` from constructors

- .github/workflows/e2e.yml
- nx.json
- package.json
- projects/demo-integrations/package.json
- projects/demo-integrations/project.json
- projects/demo/project.json
> ci: enable memoize e2e command on nx cloud

- projects/addon-doc/src/services/theme.service.ts
> fix(addon-doc): correct detect `Open-source` theme

- projects/addon-commerce/components/money/pipes/integer-part.pipe.ts
- projects/addon-commerce/components/money/test/integer-part.pipe.spec.ts
> fix(addon-commerce): `Money` fix decimal limit in integer part

- projects/demo-integrations/project.json
- projects/demo/src/modules/pipes/field-error/examples/1/index.html
- projects/demo/src/modules/pipes/field-error/examples/1/index.ts
- projects/kit/pipes/field-error/field-error-pipe.ts
> fix(kit): `FieldError` work when nested inside control

- nx.json
- projects/demo-integrations/project.json
> ci: remove `targetDefaults` because hashes are computed incorrectly

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
- projects/addon-commerce/components/input-card-grouped/input-card-grouped.module.ts
- projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
- projects/addon-commerce/components/input-card-grouped/test/input-card-grouped.component.spec.ts
- projects/cdk/directives/auto-focus/autofocus.directive.ts
- projects/cdk/directives/auto-focus/handlers/ios.handler.ts
- projects/cdk/directives/auto-focus/handlers/sync.handler.ts
- projects/cdk/directives/auto-focus/index.ts
> fix(addon-commerce): emulate focus on iOS by `tuiAutoFocus`

- projects/demo/src/modules/components/editor/highlight/text/examples/1/index.less
> chore(demo): change styles for mark

- projects/cdk/directives/control/control.directive.ts
- projects/cdk/directives/control/control.module.ts
- projects/cdk/directives/control/index.ts
- projects/cdk/directives/control/ng-package.json
- projects/cdk/directives/control/test/control.directive.spec.ts
- projects/cdk/directives/index.ts
> feat(cdk): `Control` add new directive

- package.json
- projects/core/services/breakpoint.service.ts
> fix(core): `BreakpointService` replay value for new subscribers

- .github/actions/auto-push/action.yml
- .github/workflows/lint.yml
- projects/addon-mobile/components/tab-bar/tab-bar-item.style.less
> ci: use `auto-push` action

- nx.json
> ci: memoize `stylelint` on cloud

- projects/addon-doc/src/components/demo/demo.component.ts
> fix(addon-doc): resizer shows `NaN` during SSR

- projects/cdk/constants/parent-animation.ts
> feat(cdk): add `@tuiParentStop` animation

- projects/core/components/dialog/dialog.component.ts
- projects/core/components/dialog/dialog.style.less
- projects/core/components/dialog/dialog.template.html
> fix(core): `Dialog` fix close button appearance

- projects/demo/src/modules/components/elastic-container/elastic-container.component.ts
- projects/demo/src/modules/components/elastic-container/elastic-container.module.ts
- projects/demo/src/modules/components/elastic-container/elastic-container.template.html
- projects/demo/src/modules/components/elastic-container/examples/4/index.html
- projects/demo/src/modules/components/elastic-container/examples/4/index.less
- projects/demo/src/modules/components/elastic-container/examples/4/index.ts
- projects/kit/components/elastic-container/elastic-container.component.html
- projects/kit/components/elastic-container/elastic-container.component.less
- projects/kit/components/elastic-container/elastic-container.component.ts
- projects/kit/components/elastic-container/elastic-container.directive.ts
> fix(kit): `ElasticContainer` handle nested height transitions

- projects/core/components/scroll-controls/scroll-controls.style.less
> fix(core): `Scrollbar` fix height in Firefox

- projects/cdk/directives/for-async/for-async.directive.ts
- projects/demo/src/modules/markup/icons/icons-group/icons-group.component.ts
- projects/demo/src/modules/markup/icons/icons-group/icons-group.module.ts
- projects/demo/src/modules/markup/icons/icons-group/icons-group.template.html
Closes #4101
Improve search UX in icons page
https://user-images.githubusercontent.com/12021443/230505476-045fc328-4085-4d34-a6ca-364ec0fa259b.mov
> feat(cdk): clear timeout for `tuiForAsync`

- projects/kit/components/stepper/stepper.component.ts
> chore: fix stepper e2e

- projects/demo/src/modules/components/stepper/examples/3/index.html
- projects/demo/src/modules/components/stepper/examples/3/index.less
- projects/demo/src/modules/components/stepper/examples/3/index.ts
- projects/demo/src/modules/components/stepper/stepper.component.ts
- projects/demo/src/modules/components/stepper/stepper.module.ts
- projects/demo/src/modules/components/stepper/stepper.template.html
- projects/kit/components/stepper/stepper.component.ts
> fix(kit): `Stepper` use `TuiScrollService` instead of scrollIntoView

- projects/core/components/dialog/dialog.template.html
- projects/demo/src/modules/components/dialog/examples/1/index.ts
- projects/demo/src/modules/components/dialog/examples/8/index.ts
- projects/kit/components/prompt/prompt.template.html
> feat(core): `Dialog` support basic HTML as string

- projects/demo/project.json
> ci: serve `https` for other devices by default

- projects/kit/components/prompt/prompt.module.ts
- projects/kit/components/prompt/prompt.template.html
> feat(kit): `Prompt` add autofocus on OK button

- scripts/eslint/angular.js
> ci: include `.pipe.ts` for linting

- projects/core/components/alert/alert.template.html
- projects/core/components/notification/notification.component.ts
- projects/demo/src/modules/components/push/examples/2/index.ts
- projects/demo/src/modules/services/alerts/examples/1/index.ts
- projects/demo/src/modules/services/alerts/examples/2/index.ts
- projects/kit/components/push/push-alert.template.html
- projects/kit/components/push/push.service.ts
> feat(core): `Alert` support basic HTML as string`

- projects/demo-integrations/cypress/tests/kit/input/input.cy.ts
> chore: fix broken e2e

- projects/addon-doc/src/components/documentation/documentation.template.html
- projects/demo-integrations/cypress/support/editor/helpers.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-toolbar.cy.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/components/editor/setup/editor-setup.template.html
> chore(demo): move `API` editor tab to first for preview `Starter Kit`

- projects/eslint-plugin/configs/all.json
- projects/eslint-plugin/index.js
- projects/eslint-plugin/rules/no-assert-without-ng-dev-mode.js
- projects/eslint-plugin/utils/traverse-logical-expression.js
Closes #4150
`no-tui-assert-without-ng-dev-mode` rule is implemented
> feat(eslint-plugin): implement `no-assert-without-ng-dev-mode` rule

- projects/demo/src/modules/app/stackblitz/utils.ts
> chore: fix import

- projects/cdk/schematics/ng-update/v3/constants/deprecated-functions.ts
- projects/cdk/schematics/ng-update/v3/index.ts
- projects/cdk/schematics/ng-update/v3/steps/replace-functions.ts
- projects/cdk/schematics/ng-update/v3/tests/schematic-replace-deprecated-functions.spec.ts
- projects/cdk/schematics/ng-update/v3/tests/schematic-replace-functions.spec.ts
> fix(cdk): `schematics` fix incorrectly processing `setNativeFocused`

- package-lock.json
- projects/demo/package.json
- projects/demo/webpack.config.ts
> ci: cleanup bundle of `taiga-ui.dev`

- projects/core/directives/dropdown/dropdown.component.ts
> fix(core): `Dropdown` fix scroll getting stuck

- .github/workflows/snapshots.yml
- package.json
> ci: remove `--skip-nx-cache`

- projects/addon-editor/components/editor/editor.component.ts
- projects/addon-editor/tokens/editor-processor.ts
- projects/addon-editor/tokens/editor-value-transformer.ts
- projects/addon-editor/tokens/index.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/components/editor/processing/cleanup-html/editor-cleanup-html.component.html
- projects/demo/src/modules/components/editor/processing/cleanup-html/editor-cleanup-html.component.ts
- projects/demo/src/modules/components/editor/processing/cleanup-html/editor-cleanup-html.module.ts
- projects/demo/src/modules/components/editor/processing/cleanup-html/examples/1/index.html
- projects/demo/src/modules/components/editor/processing/cleanup-html/examples/1/index.ts
- projects/demo/src/modules/components/editor/processing/cleanup-html/examples/1/transformer.ts
- projects/demo/src/modules/components/editor/processing/legacy-html/examples/1/index.less
- projects/demo/src/modules/components/editor/processing/legacy-html/examples/1/index.ts
- projects/demo/src/modules/components/editor/processing/legacy-html/examples/1/transformer.ts
Closes #4046 
Closes UIKIT-4801
```
Cut existing html classes when pasting. Now you can copy some code from any site and it will be inserted with classes from this site.
```
> feat(addon-editor): add `TUI_EDITOR_VALUE_TRANSFORMER` token

- projects/demo/src/modules/components/dialog/dialog.template.html
- projects/demo/src/modules/utils/tokens/examples/2/index.html
> chore(demo): fix dialog links

- projects/icons/scripts/prepare-feather-icons.ts
> ci: support custom path for dest where replace feather icons

- projects/core/components/dialog/dialog.component.ts
> fix(core): `Dialog` fix close button appearance on mobile

- projects/core/directives/textfield-controller/textfield-options.ts
- projects/icons/src/tuiIconClose.svg
> fix(core): use `tuiIconClose` for icon cleaner

- projects/addon-mobile/directives/ripple/ripple.providers.ts
- projects/cdk/exceptions/computed-document.exception.ts
- projects/cdk/exceptions/document-selection.exception.ts
- projects/cdk/exceptions/invalid-day.exception.ts
- projects/cdk/exceptions/invalid-month.exception.ts
- projects/cdk/exceptions/invalid-year.exception.ts
- projects/cdk/exceptions/no-host.exception.ts
- projects/cdk/exceptions/owner-document.exception.ts
- projects/cdk/exceptions/pure.exception.ts
- projects/cdk/exceptions/table-sort-key.exception.ts
- projects/cdk/exceptions/ts-parser.exception.ts
- projects/cdk/exceptions/value-changes.exception.ts
- projects/cdk/exceptions/value-present.exception.ts
- projects/cdk/exceptions/xml-parsing.exception.ts
- projects/demo/src/modules/app/app.component.ts
> ci: reduce bundle of `taiga-ui.dev`

- projects/addon-commerce/components/input-expire/test/input-expire.component.spec.ts
- projects/core/components/primitive-textfield/textfield/textfield.component.ts
- projects/core/tokens/index.ts
- projects/core/tokens/legacy-mask.ts
- projects/kit/directives/mask/legacy-mask.ts
> fix(core): `tuiTextfield` don't handle input inside legacy mask

- projects/kit/components/input-phone-international/tokens/countries-masks.ts
> fix(kit): `InputPhoneInternational` change `Gabon` phone pattern

- .github/workflows/auto-update-deps-renovate.yml
> ci: bump renovate version

- projects/core/directives/hint/hint.component.ts
- projects/demo/src/modules/app/stackblitz/starter/stackblitz-edit-button.component.ts
- projects/kit/components/input-files/input-files.directive.ts
- scripts/eslint/angular.js
> ci: skip `max-inline-declaration`

- projects/kit/components/input-files/input-files.directive.ts
> refactor: cleanup returned types

- .github/workflows/build.yml
- nx.json
> ci: predictable build between PRs and main branch

- .npmrc
> ci: fix `bad practices`

- projects/addon-mobile/components/app-bar/app-bar-back.component.ts
- projects/addon-mobile/components/app-bar/app-bar-back.style.less
- projects/addon-mobile/components/app-bar/app-bar.component.ts
- projects/addon-mobile/components/app-bar/app-bar.directive.ts
- projects/addon-mobile/components/app-bar/app-bar.module.ts
- projects/addon-mobile/components/app-bar/app-bar.providers.ts
- projects/addon-mobile/components/app-bar/app-bar.style.less
- projects/addon-mobile/components/app-bar/app-bar.template.html
- projects/addon-mobile/components/app-bar/index.ts
- projects/addon-mobile/components/app-bar/ng-package.json
- projects/addon-mobile/components/index.ts
- projects/core/components/button/button.style.less
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/components/app-bar/app-bar.component.ts
- projects/demo/src/modules/components/app-bar/app-bar.module.ts
- projects/demo/src/modules/components/app-bar/app-bar.template.html
- projects/demo/src/modules/components/app-bar/examples/1/index.html
- projects/demo/src/modules/components/app-bar/examples/1/index.less
- projects/demo/src/modules/components/app-bar/examples/1/index.ts
- projects/demo/src/modules/components/app-bar/examples/import/import-module.md
- projects/demo/src/modules/components/app-bar/examples/import/insert-template.md
- projects/demo/src/modules/components/tab-bar/tab-bar.template.html
> feat(addon-mobile): `AppBar` add new component
