taiga-family/taiga-ui

- projects/cdk/constants/matcher.ts
- projects/cdk/constants/test/matcher.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
> feat(cdk): `TUI_IDENTITY_MATCHER` consider two empty arrays equal

- projects/demo/src/modules/directives/media/examples/2/index.ts
- projects/demo/src/modules/directives/media/examples/3/index.ts
- projects/demo/src/modules/utils/format/examples/3/index.ts
-   [x] Bugfix
The documentation used "tuiIconPlay2Large" and "tuiIconPause2Large" as the play/pause icons, which do not exist.
The correct icons will be used "tuiIconPlayLarge" and "tuiIconPauseLarge"
-   [ ] Yes
-   [x] No
I also added EUR and GBP to the currency Example
> fix(demo): fix play/pause icons, add eur and gbp currency

- projects/cdk/directives/media/media.directive.ts
- projects/demo/src/modules/directives/media/media.component.ts
- projects/demo/src/modules/directives/media/media.template.html
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> feat(cdk): `Media` add `playbackRate` input

- projects/addon-doc/src/internal/header/header.template.html
- projects/addon-mobile/directives/sidebar/sidebar.directive.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/directives/sidebar/examples/1/index.html
- projects/demo/src/modules/directives/sidebar/examples/1/index.less
- projects/demo/src/modules/directives/sidebar/examples/1/index.ts
- projects/demo/src/modules/directives/sidebar/examples/import/component.txt
- projects/demo/src/modules/directives/sidebar/examples/import/import-module.txt
- projects/demo/src/modules/directives/sidebar/examples/import/insert-template.txt
- projects/demo/src/modules/directives/sidebar/sidebar.component.ts
- projects/demo/src/modules/directives/sidebar/sidebar.module.ts
- projects/demo/src/modules/directives/sidebar/sidebar.template.html
-   [ ] Bugfix
-   [x] Yes
-   [ ] No
Since Sidebar wasn't publicly exposed changes to the API are fine this early on
> feat(demo): add page for `Sidebar` directive

- projects/demo/src/modules/app/home/home.template.html
-   [ ] Bugfix
Closes #
-   [ ] Yes
-   [ ] No
> docs: Fix some minor typos in the home template

- projects/core/utils/format/capitalize.ts
- projects/core/utils/format/format-number.ts
- projects/core/utils/format/format-phone.ts
- projects/core/utils/format/pluralize.ts
- projects/core/utils/format/test/capitalize.spec.ts
- projects/core/utils/format/test/format-number.spec.ts
- projects/core/utils/format/test/format-phone.spec.ts
- projects/core/utils/format/test/pluralize.spec.ts
- projects/core/utils/mask/test/masked-number-string-to-number.spec.ts
- projects/core/utils/mask/test/tui-create-auto-corrected-number-pipe.spec.ts
- projects/demo/src/modules/utils/format/examples/6/index.html
- projects/demo/src/modules/utils/format/examples/6/index.less
- projects/demo/src/modules/utils/format/examples/6/index.ts
- projects/demo/src/modules/utils/format/format.component.ts
- projects/demo/src/modules/utils/format/format.module.ts
- projects/demo/src/modules/utils/format/format.template.html
-   [ ] Bugfix
The `formatNumber` function does not support custom thousands separator.
The `formatNumber` function now does support custom thousands separators as last argument. (Example: German uses `,`as decimal separator and `.` as thousands separator)
-   [ ] Yes
-   [x] No
While at it, I translated the formatting tests and …
> feat(format): number formatting supports custom thousands separator

- projects/core/components/button/button.style.less
-   [x] Bugfix
Right aligned margins have wrong margin.
Right aligned margins have correct margin.
-   [ ] Yes
-   [x] No
> fix(button): fix button margin for right aligned icons

- angular.json
- projects/core/styles/mixins/mixins.scss
- projects/core/styles/mixins/picker.scss
- projects/core/styles/mixins/text.scss
- projects/core/styles/mixins/textfield.scss
- projects/core/styles/taiga-ui-local.scss
- projects/core/styles/variables/media.scss
- projects/demo/src/styles.scss
-   [ ] Bugfix
SASS users cant use
```css
@import '~@taiga-ui/core/styles/taiga-ui-local';
```
Closes #164 
SASS users can safely use below
```css
@import '~@taiga-ui/core/styles/taiga-ui-local';
```
-   [ ] Yes
-   [X] No
> feat(core): add scss mixin support

- projects/kit/components/input-count/input-count.style.less
-   [x] Bugfix
Input height can be adjust using a CSS custom property. However, the height of the plus / minus button is hardcoded and thus does not match the total height of the input if the CSS property is changed. This buttons are misaligned.
Buttons scale according to CSS custom properties.
-   [ ] Yes
-   [x] No
> fix(kit): fix wrong button height for customized count inputs

- projects/kit/components/tabs/tabs/tabs.component.ts
-   [ ] Bugfix
Now tabs will update scroll position on activeIndex change. Previously it worked only after click on tab.
-   [ ] Yes
-   [x] No
> feat(kit): update tabs scroll position on activeIndex change

- projects/kit/components/input-range/input-range.component.ts
-   [x] Bugfix
Input-range control won't emit same value on blur.
-   [ ] Yes
-   [x] No
> fix(kit): prevent input-range from emitting same value on blur

- projects/core/components/scrollbar/scrollbar.style.less
-   [x] Bugfix
Height of scrollable content wrapper match to scrollbar viewport. Breaks sticky once scrolled more than on full height of scrollbar viewport.
Closes #269
Adds height intrinsic sizing to scrollbar div.content to match real content size. Now height of scrollable content wrapper match to content height.
-   [x] Yes
- …
> fix(core): fix sticky behavior for tui-scrollbar content

- projects/demo/src/modules/components/checkbox-block/examples/1/index.html
-   [ ] Bugfix
-   [x] Other... Please describe: Fix docs example for checkbox block.
Example 1 of the checkbox block is referencing the same form control for multiple checkboxes. No functional issue, but inconsistent with the component class having 3 controls listed on the form group.
Uses `testValue1`, `testValue2` and `testValue3` form controls for the separate …
> fix(docs/checkbox-block): form control name on example 1

- projects/core/components/primitive-textfield/primitive-textfield.component.ts
- projects/core/directives/textfield-controller/textfield-controller.provider.ts
- projects/kit/components/input-tag/input-tag.component.ts
- projects/kit/components/text-area/text-area.component.ts
-   [ ] Bugfix
-   [x] Other... Please describe: Technically renames an existing injection token, so will cause issues for anywhere people are providing to this token in their own implementations.
The injection token for the text field watched controller is misspelled. 
`TUI_TEXTIFELD_WATCHED_CONTROLLER` has been renamed to `TUI_TEXTFIELD_WATCHED_CONTROLLER`.
- …
> fix(primitive-textfield/controller): token naming

- projects/core/styles/basic/keyframes.less
- projects/core/styles/markup/tui-skeleton.less
- projects/kit/directives/lazy-loading/lazy-loading.directive.ts
- projects/kit/directives/lazy-loading/test/lazy-loading.directive.spec.ts
-   [ ] Bugfix
Skeleton animation uses backgroundColor property which causes page repaint each frame. With lots of content on a page, many lazy loaded images, or heavy tasks in the background, this can cause noticeable performance issue.
[https://developers.google.com/web/fundamentals/performance/rendering/stick-to-compositor-only- …
> feat(core): base skeleton vibe animation on opacity instead of backgroundColor

- projects/core/modules/notifications/notification-alert/notification-alert.component.ts
- projects/core/modules/notifications/notification-alert/notification-alert.template.html
- projects/core/modules/notifications/notification-alert/test/notification-alert.component.spec.ts
-   [ ] Bugfix
Currently notification with auto close feature closes automatically after 3000ms no matter what. This does not allow users to hold the notification and read its content.
Closes https://github.com/TinkoffCreditSystems/taiga-ui/issues/417
Whenever user _mouseover_ over notification, the auto close timer will be …
> feat(core): keep notifications open if hovered

- projects/core/components/calendar/calendar.component.ts
- projects/core/components/calendar/calendar.template.html
- projects/core/components/calendar/test/calendar.component.spec.ts
-   [x] Bugfix
When user selects a date in calendarRange and current range limit exceeds number of days in either left / right side calendars, we do jump on another month.
Closes https://github.com/TinkoffCreditSystems/taiga-ui/issues/418
When user selects a date in calendarRange and current range limit exceeds number of days in …
> fix(core): remove calendar jumps

- projects/demo/src/locale/messages.xlf
- projects/demo/src/modules/components/input-number/input-number.template.html
-   [ ] Bugfix
Right now docs have typos at `InputNumber — is a component to inout numbers` and `InputSlider for inputing with a slider`.
Closes #
These typos were fixed.
-   [ ] Yes
-   [x] No
Before:
After:
> chore(demo): fix typos at InputNumber component docs

- projects/cdk/utils/dom/get-clipboard-data-text.ts
-   [x] Bugfix
https://github.com/TinkoffCreditSystems/taiga-ui/issues/567
Closes #567 
If empty string received for text/html format, `getClipboardDataText` fallbacks to text/plain format
-   [ ] Yes
-   [x] No
> fix(kit): `getClipboardDataText` return text/plain format as fallback

- projects/cdk/utils/miscellaneous/mark-control-as-touched-and-validate.ts
- projects/cdk/utils/miscellaneous/test/mark-control-as-touched-and-validate.spec.ts
-   [x] Bugfix
Currently `markControlAsTouchedAndValidate` is not setting `touched: true` on FormArray or FormGroup with empty controls
Set `touched: true` on empty FormArray or FormGroup
-   [ ] Yes
-   [x] No
> fix(cdk): make `markControlAsTouchedAndValidate` work with empty FormArray and FormGroup

- projects/i18n/languages/german/core.ts
Mon. is wrong. It is Mo.
See: [Duden](https://www.duden.de/rechtschreibung/Mo_)
And normally you put a point behind. But not sure if this is necessary here...
> feat(i18n): Correct abbreviation for Monday in German

- projects/addon-doc/src/components/main/main.style.less
-   [ ] Bugfix
-   [X] Other... Please describe:
1. use any anchor link (for example, https://taiga-ui.dev/getting-started#options)
2. beginning of content overlapped by header
Closes #
No overlapping
-   [ ] Yes
-   [X] No
> fix(addon-doc): fix overlapping by sticky header while using anchor links

- projects/demo/src/modules/components/toggle/examples/2/index.html
- projects/demo/src/modules/components/toggle/examples/2/index.ts
- projects/demo/src/modules/components/toggle/examples/import/define-options.txt
- projects/demo/src/modules/components/toggle/toggle.component.ts
- projects/demo/src/modules/components/toggle/toggle.module.ts
- projects/demo/src/modules/components/toggle/toggle.template.html
- projects/kit/components/toggle/index.ts
- projects/kit/components/toggle/test/toggle.component.spec.ts
- projects/kit/components/toggle/toggle-options.ts
- projects/kit/components/toggle/toggle.component.ts
- projects/kit/components/toggle/toggle.module.ts
- projects/kit/components/toggle/toggle.style.less
- projects/kit/components/toggle/toggle.template.html
-   [ ] Bugfix
Partially implements #133
Default toggle options can be set via a provider. This is a partial implementation of #133
-   [ ] Yes
-   [x] No
> feat(toggle): allow configuration of default options

- projects/addon-table/components/table/providers/table.providers.ts
- projects/core/directives/table-mode/table-mode.directive.ts
- projects/demo/src/modules/components/group/examples/1/index.html
- projects/demo/src/modules/components/group/examples/1/index.ts
- projects/demo/src/modules/components/group/group.module.ts
- projects/demo/src/modules/components/input-count/examples/3/index.html
- projects/demo/src/modules/components/input-count/examples/3/index.ts
- projects/demo/src/modules/components/input-count/examples/import/define-options.txt
- projects/demo/src/modules/components/input-count/input-count.component.ts
- projects/demo/src/modules/components/input-count/input-count.module.ts
- projects/demo/src/modules/components/input-count/input-count.template.html
- projects/demo/src/modules/components/input/examples/6/style.less
- projects/demo/src/modules/components/input/examples/6/template.html
- projects/demo/src/modules/components/input/input.module.ts
- projects/kit/components/input-count/index.ts
- projects/kit/components/input-count/input-count-options.ts
- projects/kit/components/input-count/input-count.component.ts
- projects/kit/components/input-count/input-count.module.ts
- projects/kit/components/input-count/input-count.style.less
- projects/kit/components/input-count/input-count.template.html
- projects/kit/components/input-count/test/input-count.component.spec.ts
-   [ ] Bugfix
Partially implements #133
Default input-count options can be set via a provider. This is a partial implementation of #133
-   [ ] Yes
-   [x] No
> feat(kit): allow configuration of default options for input-count

- .github/workflows/firebase-hosting-pull-request.yml
-   [ ] Bugfix
The reason you are experiencing this behaviour is because the Invite workflow is being triggered by a pull request from a forked repository.
With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
When this happens, the actor of the workflow …
> ci: support PR previews from forks

- projects/kit/components/progress/progress-circle/progress-circle.style.less
-   [X] Bugfix
Angular 9 uses [clean-css](https://github.com/clean-css/clean-css)@4.23 library during prod build of package.
This version of package has problem with single-character properties names ([issue#1021](https://github.com/clean-css/clean-css/issues/1021)).
To keep a CSS fragment intact (to ignore library's "cleaning") …
> fix(kit): `ProgressCircle` keeps css-property `r` while --prod build

- .github/workflows/autorebase.yml
-   [ ] Bugfix
Closes #726
https://github.com/peter-evans/rebase/issues/86
```
@peter-evans
The reason it is null is because the head branch has been deleted in the pull request. See the PR here: TinkoffCreditSystems/taiga-ui#449
To fix it I've released a new version of the action to filter out pull requests where the head …
```
> ci: skip the branch which was deleted in the pull request from fork

- projects/cdk/date-time/day.ts
- projects/core/components/primitive-calendar/primitive-calendar.template.html
- projects/core/components/primitive-calendar/test/primitive-calendar.component.spec.ts
-   [X] Bugfix
```ts
{
provide: TUI_FIRST_DAY_OF_WEEK,
useValue: TuiDayOfWeek.Sunday,
}
```
-   [ ] Yes
-   [X] No
> fix(core): `PrimitiveCalendar` red color for weekends (with custom `TUI_FIRST_DAY_OF_WEEK`)

- projects/addon-doc/src/components/code/code.component.ts
- projects/addon-doc/src/components/code/code.template.html
- projects/addon-doc/src/components/example/example-get-tabs.pipe.ts
- projects/addon-doc/src/components/example/example.component.ts
- projects/addon-doc/src/components/example/example.module.ts
- projects/addon-doc/src/components/example/example.template.html
- projects/addon-doc/src/interfaces/page.ts
- projects/addon-doc/src/tokens/example-content-processor.ts
- projects/addon-doc/src/utils/raw-load-record.ts
- projects/addon-doc/src/utils/raw-load.ts
- projects/addon-doc/src/utils/test/raw-load-utils.spec.ts
- projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
- projects/demo/src/modules/app/stackblitz/utils.ts
- projects/demo/src/modules/components/avatar/avatar.component.ts
-   [ ] Bugfix
```ts
import {default as example1Html} from '!!raw-loader!./examples/1/index.html';
import {default as example1Ts} from '!!raw-loader!./examples/1/index.ts';
import {default as example2Html} from '!!raw-loader!./examples/2/index.html';
import {default as example2Ts} from '!!raw-loader!./examples/2/index.ts';
import …
```
> feat(addon-doc): support Promise content

- projects/kit/components/input-inline/input-inline.component.ts
-   [X] Bugfix
Closes https://github.com/TinkoffCreditSystems/taiga-ui/issues/490
When using change detection default strategy, input-inline is not firing the expression after change error in console.
-   [ ] Yes
-   [X] No
> fix(core): remove input-inline expression change error

- .prettierignore
- package.json
> ci: update lint-staged rule

- projects/cdk/date-time/day.ts
- projects/cdk/date-time/test/day.spec.ts
> chore(cdk): `TuiDay` improvement of localization

- projects/addon-doc/src/components/main/main.style.less
In case when main content area has an overflow and a vertical scrollbar appears, in the lowest position thumb goes beyond the bottom edge of the viewport.
Bottom edge of the thumb stops exactly at the bottom edge of the viewport.
> fix(addon-doc): vertical scrollbar height for root content

- projects/demo/src/modules/app/stackblitz/project-files/src/app/app.module.ts.txt
Part of https://github.com/Tinkoff/taiga-ui/issues/673
Icons in our StackBlitz's examples dont work.
For example, press "Edit on StackBlitz" here:
https://taiga-ui.dev/components/input-phone-international#base
or here
https://taiga-ui.dev/components/input-date#base
Open any StackBlitz's examples from current branch.
Icons work now.
For example,  open `/components/input-phone-international#base` or `/components/input-date#base`.
> chore(demo): `StackBlitz` workaround for icons support

- scripts/postbuild-demo.js
Go to `next`-version of demo app:
https://taiga-ui.dev/next/utils/tokens#is-ios
(or any other url with anchor link) 
**Expected behavior**: scroll to the `TUI_IS_IOS`-token's description.
**Actual behavior**: no scroll.
The same behavior as in the released version of demo app:
https://taiga-ui.dev/utils/tokens#is-ios
> chore(demo): fix `next`-demo anchor links to examples

- projects/demo/src/modules/tables/table/examples/3/index.ts
In some projects with strict checks, the field `updateOn` determines as a string. This is the cause of the TS2322 error because type `string` doesn't match with `FormHooks | undefined`.
`as const` helps to match string `blur` with `FormHooks` type.
> fix(demo): ngModelOptions for table example 3

- projects/kit/components/arrow/arrow-options.ts
- projects/kit/components/arrow/arrow.component.ts
- projects/kit/components/arrow/arrow.module.ts
- projects/kit/components/arrow/arrow.style.less
- projects/kit/components/arrow/arrow.template.html
- projects/kit/components/arrow/index.ts
Issue #133 is not fully implemented.
Partial implementation of #133 for arrow component.
> feat(kit): default options configuration for arrow

- projects/core/components/primitive-textfield/index.ts
- projects/core/components/primitive-textfield/primitive-textfield-options.ts
- projects/core/components/primitive-textfield/primitive-textfield.component.ts
- projects/core/components/primitive-textfield/primitive-textfield.template.html
- projects/demo/src/modules/components/primitive-textfield/examples/2/index.html
- projects/demo/src/modules/components/primitive-textfield/examples/2/index.ts
- projects/demo/src/modules/components/primitive-textfield/primitive-textfield.component.ts
- projects/demo/src/modules/components/primitive-textfield/primitive-textfield.module.ts
- projects/demo/src/modules/components/primitive-textfield/primitive-textfield.template.html
Issue #133 is not fully implemented.
Partial implementation of #133 for primitive-textfield component.
> feat(core): default options configuration for primitive-textfield

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
- projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
- projects/kit/components/input-range/input-range.component.ts
- projects/kit/components/input-range/input-range.template.html
- projects/kit/components/input-slider/input-slider.component.ts
- projects/kit/components/input-slider/input-slider.template.html
Closes #1270
`InputRange`, `InputSlider` and `InputCardGrouped` are using appeareance injection token (`TUI_TEXTFIELD_APPEARANCE`) now, so that it is possible to apply cutom styles to it.
> Use appearance injection token for `InputRange`, `InputSlider` and `InputCardGrouped`

- projects/addon-editor/components/color-selector/color-edit/color-edit.component.ts
Opacity count input doesnt work correctly with opacity below 58%
Closes # 
Opacity count input work correctly
> fix(addon-editor): fix of displaying opacity count below 58%

- projects/addon-commerce/components/money/money.style.less
- projects/demo/src/modules/components/money/examples/5/index.html
- projects/demo/src/modules/components/money/examples/5/index.less
- projects/demo/src/modules/components/money/examples/5/index.ts
> fix(addon-commerce): having redundant padding when currency is empty

- .github/workflows/create-release.yml
- .github/workflows/release.yml
- scripts/release.js
> ci: add manual workflow for release

- projects/demo/src/modules/animations/animations.template.html
- projects/demo/src/modules/components/slider-old/slider-old.template.html
- projects/demo/src/modules/components/slider/examples/1/index.html
- projects/demo/src/modules/components/slider/examples/2/index.html
- projects/demo/src/modules/components/slider/examples/3/index.html
- projects/demo/src/modules/components/slider/examples/4/index.html
- projects/demo/src/modules/components/slider/examples/import/declare-form.md
- projects/demo/src/modules/components/slider/examples/import/insert-template.md
- projects/demo/src/modules/components/slider/slider.component.html
- projects/kit/components/slider/slider.component.ts
- projects/kit/components/slider/test/slider-old.component.spec.ts
- projects/kit/components/slider/test/slider.spec.ts
We should call our component as `<input type="range" tuiSlider ... />` because otherwise built-in angular [RangeValueAccessor](https://github.com/angular/angular/blob/master/packages/forms/src/directives/range_value_accessor.ts#L45) cannot be matched by its CSS selector.
> fix(kit): `Slider` returns `number`-type value

- projects/kit/components/slider/slider.component.ts
The ValueAccessor.writeValue method is called twice on any value accessor during component initialization, when a control is bound using `[(ngModel)]`, first time with a phantom `null` value.
With `changeDetection: ChangeDetectionStrategy.OnPush` the second call of writeValue with real value don't re-render the view.
See this issue https://github.com/angular/angular/issues/14988
> fix(kit): `Slider` change detection problem with `[(ngModel)]`

- projects/addon-editor/abstract/editor-adapter.abstract.ts
- projects/addon-editor/components/toolbar-tools/table-create/table-create.component.ts
- projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
- projects/demo-integrations/cypress/tests/addon-editor/toolbar-new.spec.ts
The table, when created, sticks to the bottom of the component and does not allow you to create a new row after itself
Part of #1302
> fix(addon-editor): add space after table created

- projects/addon-editor/abstract/editor-adapter.abstract.ts
- projects/addon-editor/components/toolbar-tools/font-style/font-style.template.html
- projects/addon-editor/components/toolbar-tools/list-configs/list-configs.template.html
- projects/addon-editor/components/toolbar-tools/table-create/table-create.component.ts
- projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
- projects/demo-integrations/cypress/tests/addon-editor/toolbar-new.spec.ts
> fix(addon-editor): set table without style inheritance

- projects/cdk/tokens/is-ios.ts
- projects/cdk/tokens/tests/is-ios.spec.ts
feat(cdk):  TUI_IS_IOS USER_AGENT add new condition IOS devices
Co-Authored-By: AnteaterKit <ashatilovdev@gmail.com>
TUI_IS_IOS  not return true on some IOS devices 
Closes [https://github.com/Tinkoff/taiga-ui/issues/1451](url)
Correct detect device in Safari from iOS 13
> feat(cdk):  TUI_IS_IOS USER_AGENT add new condition IOS devices

- projects/core/styles/mixins/textfield.less
Closes #1471
The textfield mixins are now using corresponding CSS variables instead of hard coded values.
> feat(core): use CSS variables for font (sizes) on textfields

- projects/core/styles/mixins/textfield.less
- projects/demo-integrations/cypress/tests/core/primitive-textfield/primitive-textfield.spec.ts
TOP of the image – new changes
> chore(core): `PrimitiveTextfield` postfix should be on the same line with input's value

- projects/demo-integrations/cypress/support/shared.entities.ts
- projects/demo-integrations/cypress/tests/kit/input-slider/input-slider.spec.ts
- projects/demo/src/modules/components/input-slider/examples/5/index.html
- projects/demo/src/modules/components/input-slider/examples/5/index.ts
- projects/demo/src/modules/components/input-slider/input-slider.component.ts
- projects/demo/src/modules/components/input-slider/input-slider.template.html
- projects/kit/abstract/input-slider.ts
- projects/kit/components/input-number/input-number.component.ts
- projects/kit/components/input-number/input-number.module.ts
- projects/kit/components/input-number/input-number.template.html
- projects/kit/components/input-range/input-range.component.ts
- projects/kit/components/input-slider/input-slider.component.ts
- projects/kit/components/input-slider/input-slider.module.ts
- projects/kit/components/input-slider/input-slider.style.less
- projects/kit/components/input-slider/input-slider.template.html
- projects/kit/components/input-slider/test/input-slider-new.component.spec.ts
- projects/kit/components/input-slider/test/input-slider.component.spec.ts
`InputSlider` uses `InputNumber` inside itself.
> refactor(kit): `InputSlider` use `InputNumber` inside

- projects/kit/components/slider/slider-key-steps.directive.ts
1. Open `Slider`'s example with `keySteps` https://taiga-ui.dev/components/slider#keySteps
2. Turn on `VoiceOver` (or another screen reader)
3. Screen reader pronounces wrong value (because of key steps)
...
3. Screen reader pronounces correct value
> fix(kit): `Slider` improve a11y for `keySteps`

- projects/kit/components/slider/slider.component.ts
- projects/kit/components/slider/test/slider.spec.ts
Open slider with `max === 0`
https://taiga-ui.dev/components/slider/API?max=0&min=-100 
No bug
> fix(kit): `Slider` input-property `max` can be equal to zero

- projects/core/pipes/format-number/format-number.pipe.ts
- projects/core/utils/format/format-number.ts
- projects/core/utils/format/test/format-number.spec.ts
When zeroPadding flag is disabled zeros are not adding at the end of decimal part.
Also, when zeroPadding flag is disabled trailing zeros in decimal part are deleting and if there are not significant digits at all - with decimal separator.
> feat(format-number): add zeroPadding flag

- projects/kit/components/slider/slider-key-steps.directive.ts
- projects/kit/components/slider/test/slider-key-steps.spec.ts
Open https://taiga-ui.dev/next/components/range/API?min=-10&max=10
> fix(kit): `keySteps` works if `Slider` has `min`-property !== 0

- projects/demo/src/modules/components/avatar/avatar.component.ts
- projects/demo/src/modules/components/avatar/avatar.module.ts
- projects/demo/src/modules/components/avatar/avatar.template.html
- projects/demo/src/modules/components/avatar/examples/3/index.html
- projects/demo/src/modules/components/avatar/examples/3/index.ts
- projects/demo/src/modules/components/avatar/examples/import/define-options.md
- projects/kit/components/avatar/avatar-options.ts
- projects/kit/components/avatar/avatar.component.ts
- projects/kit/components/avatar/index.ts
- projects/kit/components/avatar/tests/avatar-options.spec.ts
Partially implements https://github.com/Tinkoff/taiga-ui/issues/133
Default avatar options can be set via a provider. This is a partial implementation of https://github.com/Tinkoff/taiga-ui/issues/133
> feat(kit): `TUI_AVATAR_OPTIONS` default options configuration for `Avatar`

- projects/kit/components/files/files.component.less
- projects/kit/components/input-files/input-files.style.less
input-files styles conflicts with other component due to encapsulation
> fix(kit): `InputFiles` fix styles

- projects/demo-integrations/cypress/tests/kit/multi-select/multi-select.spec.ts
- projects/demo/src/modules/components/multi-select/examples/9/index.html
- projects/demo/src/modules/components/multi-select/examples/9/index.ts
- projects/demo/src/modules/components/multi-select/multi-select.component.ts
- projects/demo/src/modules/components/multi-select/multi-select.module.ts
- projects/demo/src/modules/components/multi-select/multi-select.template.html
- projects/kit/components/multi-select/multi-select.style.less
Fixes a bug in `multiselect` when the above elements have a `data-size` attribute.
Fixes #1636
Closes #1636
> fix(kit): incorrect alignment of icons in multiselect

- projects/kit/components/input-tag/input-tag.component.ts
- projects/kit/components/input-tag/input-tag.template.html
fix(kit): dropdown content jumping and rerendering multiselect after adding new tags
Fixes #1534
I'm not sure about trackBy because I haven't found any using of it in library. If there is any solution without it I can implement it.
Closes #1534
> fix(kit): dropdown content jumping and rerendering multiselect after adding new tags

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
- projects/addon-table/components/table/directives/sort-by.directive.ts
- projects/addon-table/components/table/directives/sortable.directive.ts
- projects/addon-table/components/table/directives/table.directive.ts
- projects/addon-table/components/table/index.ts
- projects/addon-table/components/table/table.module.ts
- projects/demo/src/modules/tables/table/examples/4/index.html
- projects/demo/src/modules/tables/table/examples/4/index.ts
- projects/demo/src/modules/tables/table/table.template.html
> feat(addon-table): `SortBy` add directive for server-side sorting by column name

- projects/demo/src/modules/components/input-range/examples/5/index.ts
- projects/demo/src/modules/components/range/examples/4/index.html
- projects/demo/src/modules/components/range/examples/4/index.ts
- projects/kit/components/range/range.component.ts
- projects/kit/components/range/range.template.html
- projects/kit/components/range/test/range.component.spec.ts
- projects/kit/components/slider/slider-key-steps.directive.ts
- projects/kit/utils/index.ts
- projects/kit/utils/math/index.ts
- projects/kit/utils/math/key-steps.ts
- projects/kit/utils/math/test/key-steps.spec.ts
> chore(kit): `Range` refactor of `keySteps`

- projects/core/styles/markup/tui-list.less
- projects/demo/src/modules/markup/lists/examples/7/index.html
- projects/demo/src/modules/markup/lists/examples/7/index.ts
- projects/demo/src/modules/markup/lists/lists.component.ts
- projects/demo/src/modules/markup/lists/lists.module.ts
- projects/demo/src/modules/markup/lists/lists.template.html
Tinkoff add new core style for bullet list - it appears as triangle - "◤" but taiga doesn't have it.
Adds new style without changing others. It has same usage as regular linear: `<ul class="tui-list tui-list_triangle">`
> feat(core): `Lists` add triangle bullet list type

- projects/demo-integrations/cypress/tests/core/data-list/data-list.spec.ts
- projects/demo-integrations/cypress/tests/kit/input/input-tag.spec.ts
These test suites take screenshots of the whole page.
It is time-consuming and sometimes in CI (when we have low CPU-performance) the tests can fail.
See [recent example](https://github.com/Tinkoff/taiga-ui/runs/6319429143?check_suite_focus=true#step:10:2287) from the main branch. Or [this example](https://github.com/Tinkoff/taiga-ui/runs/6305554585?check_suite_focus=true#step:10:993).
It was caused by the recent changes [on this line](https://github.com/Tinkoff/taiga-ui/pull/1720/files#diff-ac6ea6a0d601a116bf2b6e2cf157ac8c26487e529b0e3bb41d7eca8a2473fa3eR14).
Increased time of the config for these tests only (the same value as it was before).
It is a default value of [this …
> chore(demo-integrations): fix `InputTag`, `DataList` flaky tests

- projects/demo-integrations/cypress/support/visit.ts
1. Try add artificial delay to fonts loading. For example, you can replace this line
https://github.com/Tinkoff/taiga-ui/blob/73959ffa523edaca6f1e6fd70a767fa641876b58/projects/core/styles/theme/fonts.css#L1
by 
```css
@import 'https://deelay.me/3000/https://fonts.googleapis.com/css2?family=Manrope:wght@500;800&display=swap';
```
2. Launch any cypress test
We have this line inside `tuiVisit`:
https://github.com/Tinkoff/taiga-ui/blob/73959ffa523edaca6f1e6fd70a767fa641876b58/projects/demo-integrations/cypress/support/visit.ts#L73
But it does help to wait fonts loading.
It does not work because at the start of the page loading, `document.fonts.status` already has status `loaded` (and it …
> chore(demo-integrations): `tuiVisit` wait when fonts start and finish loading

- projects/cdk/date-time/month.ts
- projects/cdk/date-time/test/day.spec.ts
- projects/cdk/date-time/test/month.spec.ts
- projects/cdk/date-time/test/time.spec.ts
- projects/cdk/date-time/test/year.spec.ts
- projects/cdk/date-time/time.ts
- projects/cdk/date-time/year.ts
- projects/demo-integrations/cypress/tests/kit/input-time/input-time.spec.ts
Closes #1729
`valueOf` and `Symbol.toPrimitive` are added to TuiDay, TuiMonth, TuiYear and TuiTime
> feat(cdk): add valueOf and Symbol.toPrimitive to TuiDay, TuiMonth, TuiYear and TuiTime 

- projects/core/styles/mixins/slider.less
- projects/kit/components/range/range.style.less
- projects/kit/components/slider/slider.style.less
Use Angular 13
```
.some-class {
.tui-slider-ticks-labels();
^
Operation on an invalid type
Error in .../.../app.component.less
```
See [Less documentation](https://lesscss.org/usage/#less-options-math):
> In order to cause fewer conflicts with CSS, which now liberally uses the / symbol between values, there is now a math mode that only requires parentheses for division. (This is now the default in Less 4.) "Strict math" has also been tweaked to operate more intuitively, although the legacy behavior is supported.
> fix(core): `tui-slider-ticks-labels` error `Operation on an invalid type`

- projects/cdk/schematics/ng-add/constants/modules.ts
- projects/cdk/schematics/ng-add/schema.json
- projects/cdk/schematics/ng-add/schema.ts
- projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts
- projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts
- projects/taiga-schematics/schematics/ng-add/constants/modules.ts
- projects/taiga-schematics/schematics/ng-add/schema.json
- projects/taiga-schematics/schematics/ng-add/schema.ts
- projects/taiga-schematics/schematics/ng-add/steps/add-taiga-modules.ts
- projects/taiga-schematics/schematics/ng-add/tests/ng-add.spec.ts
1. Type command:
```
ng add taiga-ui
```
2. Agree to add notifications
3. Schematic adds deprecated module.
Use not-deprecated module
> chore(cdk): `schematics` replace deprecated `TuiNotificationsModule` by `TuiAlertModule`

- projects/kit/components/select-option/select-option.component.ts
<details>
<summary>HTML</summary>
```html
<tui-root>
<tui-combo-box
[ngModel]="selectedProcedure"
[stringify]="stringify"
(searchChange)="onSearchProcedureChange()"
>
Type "1"
<tui-data-list-wrapper
*tuiDataList
[items]="procedures$ | async"
></tui-data-list-wrapper>
</tui-combo-box>
</tui-root>
```
</details>
<details>
<summary>Typescript</summary>
```ts
import { Component } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
@Component({
selector: 'my-app',
templateUrl: './app.component.html',
})
export class ExampleComponent {
procedures$ = new BehaviorSubject<any[]>([]);
selectedProcedure: any = null;
onSearchProcedureChange(): void {
this.procedures$.next([
{ id: '1', …
```
> fix(kit): `ComboBox` throws `ExpressionChangedAfterItHasBeenCheckedError`

- projects/kit/components/calendar-month/calendar-month.component.ts
- projects/kit/components/calendar-month/calendar-month.template.html
- projects/kit/components/calendar-month/test/calendar-month.component.spec.ts
- projects/kit/components/input-month/input-month.component.ts
- projects/kit/components/input-month/input-month.template.html
- projects/kit/components/input-month/test/input-month.component.spec.ts
> fix(kit): `InputMonth` reopen calendar with year of the selected value

- projects/demo-integrations/cypress/support/visit.ts
- projects/demo-integrations/cypress/tests/kit/input-range/input-range.spec.ts
- projects/kit/components/input-range/input-range.component.ts
- projects/kit/components/input-range/input-range.template.html
- projects/kit/components/range/range-change.directive.ts
1. Use real mobile device
2. Focus text input on any side of `InputRange`
3. Try interact with `Range`
**Actual behaviour:**
https://user-images.githubusercontent.com/35179038/170229324-85663bb7-250f-46a7-a6f7-3a63b3591348.MP4
**Expected behaviour:**
Keyboard should not disappear after range interactions.
It should behaves in the same way as `InputSlider`.
Also, there is problem with focus ring in our proprietary demo:
https://user-images.githubusercontent.com/35179038/170229777-960612c0-67f0-44e2-aaea-0191d0378db3.mov
Fix all mentioned problem.
https://user-images.githubusercontent.com/35179038/170230507-c007a7ef-1634-4bff-b16a-57d04307c5b7.MP4
> fix(kit): `InputRange` problem with range interactions on mobile devices

- projects/core/components/data-list/option/option.style.less
> fix(core): `DataList` missing paddings inside `Option` (multiline text problem)

- angular.json
To run schematics tests we need to run:
```sh
nx build cdk & nx test-schematics cdk 
```
Nx knows that before testing of schematics it should build `cdk`-package.
Now to test schematics we should just run
```sh
nx test-schematics cdk 
```
> chore: target `cdk:test-schematics` dependsOn `cdk:build`

- .github/PULL_REQUEST_RELEASE_TEMPLATE.md
- .github/workflows/create-release.yml
> ci: content must be escaped to preserve newlines

- projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts
- projects/demo/src/modules/components/input-number/examples/1/index.html
- projects/demo/src/modules/components/input-number/examples/1/index.less
- projects/demo/src/modules/components/input-number/examples/1/index.ts
- projects/demo/src/modules/components/input-number/input-number.component.ts
- projects/demo/src/modules/components/input-number/input-number.module.ts
- projects/demo/src/modules/components/input-number/input-number.template.html
**Possible reproduction:**
If any textfield-component projected via `<ng-content />` (and this content projection is attached by some async logic), these lines
https://github.com/Tinkoff/taiga-ui/blob/3c7c53b6a707718c9d4441f447991dd79b4f4bba/projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts#L34-L38
calculates `offsetWidth` as zero (because the component was initialized but it is not attached to the DOM yet). 
Closes #1862
> fix(kit): `InputNumber` prefix is overlapped by value

- .eslintrc.js
- projects/demo/src/modules/charts/legend-item/examples/2/index.ts
- projects/kit/utils/mask/create-date-mask.ts
- projects/kit/utils/mask/create-time-mask.ts
They work the same, but new should be preferred for consistency with other constructors.
This rule is fixable, except new String(), new Number(), and new Boolean(), [they return wrapped object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#String_primitives_and_String_objects).
> ci: support `new-for-builtins`

- .eslintrc.js
- projects/demo/src/modules/components/input-tag/examples/4/index.ts
Disallow using the this argument in array methods
✅ This rule is part of the [recommended](https://github.com/sindresorhus/eslint-plugin-unicorn#recommended-config) config.
🔧💡 This rule is [auto-fixable](https://eslint.org/docs/user-guide/command-line-interface#fixing-problems) and provides [suggestions](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions).
The rule disallows using the thisArg argument in array methods:
If the callback is an arrow function or a bound function, the thisArg won't affect it.
If you intent to use a custom this in the callback, it's better to use the variable directly or use callback.bind(thisArg).
This rule checks following …
> ci: support `no-array-method-this-argument`

- package-lock.json
- projects/cdk/package.json
It just the temporary solution to fix the bug with rxjs-types:
We should investigate this problem and try to find better solution!
This solution fixes `cdk` package but breaks schematics (see [PR](https://github.com/Tinkoff/taiga-ui/pull/1880)):
> fix: problem with invalid rxjs-types

- projects/cdk/directives/auto-focus/autofocus.options.ts
All stackblitz examples do not work.
Error description: https://angular.io/errors/NG0203
The problem appeared in 2.48. Maybe because of this https://github.com/Tinkoff/taiga-ui/pull/1813 (or maybe not; let's check 😄 ).
In 2.47.0 everything works fine.
After new release it can be fixed.
> chore: fix stackblitz `NG0203`-error (maybe not)

- projects/kit/components/pdf-viewer/pdf-viewer.component.ts
Closes #1700
It's possible to close a PdfViewer component on esc key.
> feat(kit): add document:keydown.esc listener to close a pdf viewer

- projects/addon-doc/src/components/navigation/navigation.component.ts
- projects/addon-doc/src/directives/scroll-into-view/scroll-into-view.directive.ts
- projects/addon-doc/src/public-api.ts
- projects/addon-doc/src/tokens/page-loaded.ts
- projects/demo-integrations/cypress/tests/addon-doc/navigation.spec.ts
- projects/demo/src/modules/app/app.component.ts
- projects/demo/src/modules/app/utils/ready-to-scroll-factory.ts
* Try go to https://taiga-ui.dev/components/input#table
* It should scroll to example "Table" 
* **But**:
https://user-images.githubusercontent.com/35179038/176679073-aa4593f1-a902-4bc7-a202-c00dd7e49f4c.mov
https://user-images.githubusercontent.com/35179038/176679218-3d12725c-b9a7-4cf8-b53c-478c615ef4ad.mov
**You can try by yourself:**
https://taiga-ui--pr2031-fix-scroll-to-exampl-50r2a996.web.app/components/input#table
**Screenshot diff:**
> feat(addon-doc): new token `TUI_DOC_PAGE_LOADED` to fix anchor links (scroll to examples)

- projects/demo-integrations/cypress/support/visit.ts
- projects/demo-integrations/cypress/tests/addon-icons/customization-icons.spec.ts
- projects/demo/src/modules/app/app.component.ts
Sometimes page can be scrolled before all page's content is ready.
It can produce this flaky screenshots:
____
Also, fix the following flaky test:
⏬
> chore(demo-integrations): page should be loaded before scroll+screenshot

- projects/demo/src/modules/components/input-files/input-files.template.html
Output is `reject` while in the documentation it's `onReject`.
Rename `onReject` to `reject`
> docs(kit): rename documentation property name `onReject` to `reject` for InputFiles

- projects/demo-integrations/cypress/support/wait-code-highlight.ts
Successful runs of `E2E tests / addon-doc` - job:
> chore: fix flaky cypress test

- projects/demo/src/modules/components/input-range/input-range.component.ts
- projects/demo/src/modules/components/input-slider/examples/3/index.ts
- projects/demo/src/modules/components/input-slider/input-slider.component.ts
- projects/demo/src/modules/components/range/range.component.ts
- projects/kit/components/input-slider/input-slider.component.ts
- projects/kit/components/input-slider/input-slider.template.html
- projects/kit/components/range/range.component.ts
- projects/kit/components/slider/helpers/slider-key-steps.directive.ts
- projects/kit/types/key-steps.ts
- projects/kit/types/test/key-steps.spec.ts
- projects/kit/utils/math/key-steps.ts
```ts
export type TuiKeySteps = Array<[number, number]>;
```
```ts
export type TuiKeySteps = [[0, number], ...Array<[number, number]>, [100, number]];
```
> feat(kit)!: `Slider` | `InputSlider` | `Range` | `InputRange` use strict version of `TuiKeySteps`

- projects/demo-integrations/cypress/tests/kit/input-slider/input-slider.spec.ts
- projects/kit/components/input-slider/input-slider.component.ts
- projects/kit/components/input-slider/input-slider.template.html
- projects/kit/components/input-slider/test/input-slider-new.component.spec.ts
- projects/kit/components/input-slider/test/input-slider.component.spec.ts
> fix(kit): `InputSlider` props `[prefix]`/`[postfix]` + `[valueContent]` overlaps each other on blur

- projects/demo-integrations/cypress/tests/core/hint/hint.spec.ts
- projects/demo-integrations/cypress/tests/core/primitive-textfield/primitive-textfield.spec.ts
```
1) TuiHint
Manual hint works:
AssertionError:
Timed out retrying after 10000ms:
expected 
'http://localhost:3333/?tuiMode=null&tuiManualHintShow=true'
to include
'/directives/manual-hint/API?tuiMode=null&tuiManualHintShow=true'
at Context.eval (http://localhost:3333/__cypress/tests?p=cypress/support/e2e.ts:1156:22)
```
> chore: fix cypress tests (`hint-manual` error)

- projects/demo/src/modules/app/app.const.ts
An IconButton link on a Button page navigates to `https://taiga-ui.dev/`.
An IconButton link is removed from SEE_ALSO_GROUPS array.
> docs: remove IconButton from SEE_ALSO_GROUPS

- commitlint.config.js
- package.json
See [default preset](https://github.com/conventional-changelog/conventional-changelog/blob/bfe3bf1c49d4a125474b398b2d304749fd3b56c7/packages/conventional-changelog-conventionalcommits/writer-opts.js#L179-L192):
```js
[
{ type: 'feat', section: 'Features' },
{ type: 'feature', section: 'Features' },
{ type: 'fix', section: 'Bug Fixes' },
{ type: 'perf', section: 'Performance Improvements' },
{ type: 'revert', section: 'Reverts' },
{ type: 'docs', section: 'Documentation', hidden: true },
{ type: 'style', section: 'Styles', hidden: true },
{ type: 'chore', section: 'Miscellaneous Chores', hidden: true },
{ type: 'refactor', section: 'Code Refactoring', hidden: true },
{ type: 'test', …
```
> chore: `Changelog` add section `Deprecations`

- projects/cdk/schematics/ng-update/constants/templates.ts
- projects/demo-integrations/cypress/tests/kit/input-tag/input-tag.spec.ts
- projects/demo/src/modules/components/input-tag/examples/5/index.less
- projects/demo/src/modules/components/input-tag/examples/6/index.less
- projects/demo/src/modules/components/input-tag/examples/7/index.html
- projects/demo/src/modules/components/input-tag/examples/7/index.ts
- projects/demo/src/modules/components/input-tag/input-tag.component.ts
- projects/demo/src/modules/components/input-tag/input-tag.module.ts
- projects/demo/src/modules/components/input-tag/input-tag.template.html
Deprecate property`[allowSpaces]`.
Use property `[separator]` to forbid spaces.
New screenshot test produces:
> deprecate(kit): `InputTag` deprecate property `[allowSpaces]`

- projects/cdk/constants/browser.ts
- projects/cdk/utils/browser/index.ts
- projects/cdk/utils/browser/is-ie.ts
- projects/cdk/utils/browser/test/browsers.spec.ts
- projects/core/components/svg/svg.component.ts
- projects/demo/src/modules/app/customization/customization.component.ts
- projects/demo/src/modules/app/customization/customization.template.html
- projects/demo/src/modules/info/browsers/browsers.template.html
- projects/demo/src/modules/utils/browser/examples/1/index.ts
- projects/demo/src/modules/utils/browser/examples/import/import-component.md
- projects/kit/components/progress/progress-bar/progress-color-segments.directive.ts
- projects/kit/components/progress/progress-circle/progress-circle.component.ts
- projects/kit/components/slider/slider.component.ts
> feat!: drop support of legacy not-chromium Edge (EdgeHTML)

- projects/addon-table/components/table/th/th.template.html
…orting state.
The sorting chevron is reversed, pointing down for asc and up for desc.
Closes https://github.com/Tinkoff/taiga-ui/issues/2265
The sorting chevron points up for asc, down for desc.
> fix(addon-table): sort chevron direction to correctly match the sorting state

- projects/kit/components/text-area/text-area.style.less
On Safari 13+ versions label is not aligned with inner textarea  
Closes #2291 
Now it's broken only on 13.0 – 13.3 ios versions (Safari 13.0). All other versions Safari 10+ is working perfectly. Label is aligned with inner textarea
> fix(kit): `tui-text-area` label alignment on IOS

- scripts/nx/decorate-angular-cli.ts
1. Execute
```sh
rm -rf node_modules/
npm ci
```
2. It throws error:
```sh
(node:5768) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/n.barsukov/WebstormProjects/taiga-ui/scripts/nx/decorate-angular-cli.ts:23
import { execSync } from 'child_process';
^^^^^^
SyntaxError: Cannot use import statement outside a module
at Object.compileFunction (node:vm:352:18)
at wrapSafe (node:internal/modules/cjs/loader:1033:15)
at Module._compile (node:internal/modules/cjs/loader:1069:27)
at Module.m._compile (/Users/n.barsukov/WebstormProjects/taiga-ui/node_modules/ts-node/s …
```
> ci: `npm ci` error `SyntaxError: Cannot use import statement outside a module`

- projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts
- projects/cdk/schematics/ng-update/index.ts
- projects/cdk/schematics/ng-update/steps/migrate-taiga-proprietary-icons.ts
- projects/cdk/schematics/utils/angular-json-manipulations.ts
```console
An error occured:
Error: Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]
at Object.readJsonWorkspace (/Users/n.barsukov/WebstormProjects/taiga-ui/node_modules/@angular-devkit/core/src/workspace/json/reader.js:31:15)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async Object.readWorkspace (/Users/n.barsukov/WebstormProjects/taiga-ui/node_modules/@angular-devkit/core/src/workspace/core.js:90:25)
at async /Users/n.barsukov/WebstormProjects/taiga-ui/node_modules/@schematics/angular/utility/workspace.js:39:35
```
> chore(cdk): `schematics` error-handling for not-supported angular.json

- projects/addon-doc/src/components/demo/demo.template.html
- projects/cdk/schematics/ng-update/constants/templates.ts
- projects/cdk/schematics/ng-update/tests/schematic-replace-html.spec.ts
- projects/core/components/expand/expand-content.directive.ts
- projects/core/components/expand/expand.component.ts
- projects/core/components/expand/expand.module.ts
- projects/core/components/expand/index.ts
- projects/core/components/expand/test/expand.component.spec.ts
- projects/demo/src/modules/components/expand/examples/1/index.html
- projects/demo/src/modules/components/expand/examples/import/insert-template.md
- projects/demo/src/modules/components/expand/expand.template.html
- projects/kit/components/accordion/accordion-item/accordion-item.template.html
Closes #2497
```html
<tui-expand [expanded]="expanded">
Hello world
</tui-expand>
<tui-expand [expanded]="expanded">
<ng-template>Hello world</ng-template>
</tui-expand>
```
> feat(core)!: remove `tuiExpandContent` directive

- CHANGELOG.md
- Update to Angular 12 ([#2080](https://github.com/tinkoff/taiga-ui/issues/2080),
[#2097](https://github.com/tinkoff/taiga-ui/issues/2097), [#2110](https://github.com/tinkoff/taiga-ui/issues/2110)).
Enable `Ivy` by default ([#2076](https://github.com/tinkoff/taiga-ui/issues/2076)). Drop legacy `View Engine`-support.
- Migrate to [Polymorpheus](https://github.com/Tinkoff/ng-polymorpheus) 4.x.x
([#2165](https://github.com/tinkoff/taiga-ui/issues/2165)).
- Update supported browser versions. Drop support of legacy not-chromium Edge (EdgeHTML)
([#2318](https://github.com/tinkoff/taiga-ui/issues/2318)). Bump supported `Safari` to `12.1+`
([#2391](https://github.com/tinkoff/taiga-ui/issues/2391)).
- All exported entities without `tui`-prefix was renamed to the same one with prefix: functions, …
> chore(demo): `Changelog` update description of `3.0.0`-release

- projects/testing/core/button/button.harness.ts
- projects/testing/utils/helpers.ts
If we use static method `with` on `TuiButtonHarness`, it loses type information. e.g:
```
const harness = await loader.getHarness(TuiButtonHarness); // TuiButtonHarness
const harness = await loader.getHarness(TuiButtonHarness.with({selector:'.class'})); //  ComponentHarness
```
then we can not read methods defined in `TuiButtonHarness`.
If `TuiButtonHarnes` is extended from `TuiComponentHarness` class, type safety is there and no monkey-patching is needed using decorators.
> feat(testing): introduce more type safety for harness

- projects/demo/project.json
Run `npm start`.
```console
Build at: 2022-09-02T14:03:58.693Z - Hash: 0ff811a357f41cb99c07 - Time: 87906ms
./projects/demo/src/modules/app/app.providers.ts:103:15-106:50 -
Error: Module not found:
Error: Can't resolve 'dist/i18n/esm2015/languages' in '/Users/n.barsukov/WebstormProjects/taiga-ui/projects/demo/src/modules/app'
** Angular Live Development Server is listening on localhost:3333, open your browser on http://localhost:3333/ **
✖ Failed to compile.
```
https://github.com/Tinkoff/taiga-ui/pull/2567
> chore: fix `npm start`-command

- package-lock.json
- projects/cdk/package.json
Closes #2569
`parse5` & `ng-morph` can be dropped now via this command:
```console
npm ci --no-optional
```
> fix(cdk): `parse5` & `ng-morph` move `dependencies` => `optionalDependencies`

- projects/demo/src/modules/app/stackblitz/project-files/configs.md
- projects/demo/src/modules/app/stackblitz/project-files/src/app/@stackblitz/README.md
- projects/demo/src/modules/app/stackblitz/project-files/src/app/app.module.ts.md
- projects/demo/src/modules/app/stackblitz/stackblitz-resources-loader.ts
- projects/demo/src/modules/app/stackblitz/stackblitz.service.ts
- projects/demo/src/modules/app/stackblitz/utils.ts
Unfortunately, previous [stackblitz-hack](https://github.com/Tinkoff/taiga-ui/blob/main/projects/demo/src/modules/app/stackblitz/project-files/src/app/app.module.ts.md) does not works:
```ts
function tuiPropagateModules<T>(entryPoint: T) {
const modules = [];
for (const name in entryPoint) {
if (name.endsWith('Module')) {
modules.push(entryPoint[name]);
}
}
return modules;
}
```
It causes error:
```console
Error in src/app/app.module.ts (19:17)
Value at position 1 in the NgModule.declarations of AppModule is not a reference
Value could not be determined statically.
```
See this issue https://github.com/angular/angular/issues/42550
New hack :)
> fix(demo): make `Stackblitz` to be compatible with `Taiga UI 3.0`

- projects/core/components/primitive-textfield/textfield/textfield.component.ts
- projects/core/components/primitive-textfield/textfield/textfield.style.less
- projects/core/styles/mixins/textfield.less
- projects/demo-integrations/cypress/tests/kit/input/input.spec.ts
- projects/demo/src/modules/components/input/input.component.ts
- projects/demo/src/modules/components/input/input.template.html
> fix(core): support `text-overflow` in `tuiTextfield`

- .github/workflows/create-release.yml
- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/kit/components/calendar-range/calendar-range.template.html
- projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
- projects/kit/internal/primitive-calendar-range/primitive-calendar-range.component.ts
> feat(kit): `InputDateRange` navigate months in sync, cancel unfinished range on esc

- projects/demo/src/404.html
- projects/demo/src/modules/app/abstract.app.ts
(cherry picked from commit 7dfc227af1aa74c8e469a2e3559ce3257b91d113)
> ci: replace only `next` or `v.x` subpath of route (#2691)

- projects/demo-integrations/cypress/support/commands.ts
- projects/demo-integrations/cypress/support/set-language.ts
- projects/demo-integrations/cypress/tests/kit/input-files/input-files.spec.ts
- projects/i18n/languages/dutch/kit.ts
- projects/i18n/languages/italian/kit.ts
- projects/kit/components/input-files/input-files.component.ts
- projects/kit/components/input-files/input-files.module.ts
- projects/kit/components/input-files/input-files.template.html
- projects/kit/components/input-files/max-size-rejection-error.pipe.ts
Closes #2709
You can dynamically change language of error messages for rejected files.
> fix(kit): `InputFlies` new value of i18n-token `TUI_INPUT_FILE_TEXTS` triggers text changes

- nx.json
See this issue: https://github.com/Tinkoff/taiga-ui/issues/2617
Solution is copied from this PR: https://github.com/Tinkoff/taiga-ui/pull/2620
> chore: broken `npm start`-command

- projects/core/components/primitive-textfield/textfield/textfield.style.less
- projects/core/styles/mixins/textfield.less
- projects/demo-integrations/cypress/tests/kit/input/input.cy.ts
Revertion of https://github.com/Tinkoff/taiga-ui/pull/2657
Before changes => After changes
> fix(core): `PrimitiveTextfield` drop wrong `text-overflow: ellipsis` (horizontal scroll bug)

- projects/eslint-plugin/no-deep-imports.js
Windows has file paths like this:
```
C:\\Users\\nsbarsukov\\WebstormProjects\\taiga-ui\\projects\\core\\directives\\hint\\hint.component.ts
```
I know, it looks terrible :peka:
> fix(eslint-plugin): `no-deep-imports` add `Windows`-OS support

- projects/core/components/primitive-textfield/test/primitive-textfield.component.spec.ts
- projects/testing/core/index.ts
- projects/testing/core/primitive-textfield.harness.ts
- projects/testing/core/primitive-textfield/primitive-textfield.harness.ts
> feat(testing): add component harness test for primitive-textfield component

- projects/addon-doc/src/components/example/example.component.ts
- projects/addon-doc/src/components/example/example.module.ts
- projects/addon-doc/src/components/example/example.template.html
Closes #2766
An `Edit on` link is not visible for examples without HTML or TypeScript files.
An `Edit on` link doesn't work in the linked issue since the example doesn't have a TypeScript property, but `TuiStackblitzService.edit` method requires it. The possible solution is just to add this missing property to the example object. But there are other examples where the `Edit on` feature also doesn't work, e.g. [variables](https://taiga-ui.dev/variables). I guess that we can't force to use HTML & TypeScript properties all the time. So I implemented logic to hide an `Edit on ...` link if an example has neither HTML nor TypeScript properties. Otherwise, the button is visible but an example …
> docs: add flag to show edit button only if TS & HTML exist

- projects/addon-commerce/components/input-card/input-card.component.ts
- projects/addon-commerce/components/input-card/test/input-card.component.spec.ts
- projects/demo/src/modules/components/input-card/input-card.template.html
Card icon displayed according to payment system card detection, and supports only string type customisations.
Closes  #2752 
If you want to override icon handled by payment system with custom card icon, you can do it with `cardSrc` input. Now It works also for templates and custom icons.
> feat: extend custom icon type to `PolymorpheusContent`

- projects/addon-editor/components/editor-socket/editor-socket.component.less
- projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts
> fix(addon-editor): normalize h1-h6 heading in editor socket

- projects/styles/basic/main.less
> fix(styles): pseudo elements `:after` aren't removed in Safari 16

- projects/demo-integrations/cypress/tests/kit/input/input.cy.ts
Closes #2656 
valid url for using long text as custom content
> chore: `tuiTextfieldCustomContent` fix e2e

- projects/addon-table/components/table/directives/direction-order.directive.ts
- projects/addon-table/components/table/directives/test/direction-order.directive.spec.ts
- projects/addon-table/components/table/index.ts
- projects/addon-table/components/table/table.module.ts
To specify sort direction one needs to pass direction as 1 or -1 which is a bit confusing.
Closes # https://github.com/Tinkoff/taiga-ui/issues/2266
Allows user to specify direction in terms of order e.g "asc" or "desc" instead of 1 or -1.
> feat(addon-table): add directive to sort by order

- projects/demo/src/locale/messages.xlf
Fixed Typo in the description of the tuiTextfieldMaxLength attribute, i.e., `with with` to `work with`
Closes #2873
> chore(demo): fix typo in the description of the `tuiTextfieldMaxLength`

- projects/demo/src/modules/app/stackblitz/project-files/configs.md
Open Stackblitz of any example from this list:
* https://taiga-ui.dev/components/line-days-chart#base
* https://taiga-ui.dev/components/dialog#data
* https://taiga-ui.dev/components/progress-bar#basic
* https://taiga-ui.dev/components/progress-bar#multicolor
* https://taiga-ui.dev/components/progress-bar#label
* https://taiga-ui.dev/components/progress-circle#basic
* https://taiga-ui.dev/components/progress-circle#label
All these examples throw:
```console
Property 'X' is used before its initialization.
```
It happens because we use DI-entity to create another property in constructor.
But we use this technique in many places of our libraries, and it works!
It depends on ts-configs …
> chore(demo): `Stackblitz` error `Property 'X' is used before its initialization`

- projects/kit/components/tag/test/tag.component.spec.ts
- projects/testing/core/index.ts
- projects/testing/core/svg.harness.ts
- projects/testing/core/tag.harness.ts
> feat(testing): add harness tests for tag component

- projects/styles/markup/tui-island.less
Closes #2909
`tui-island_transparent` has precedence over `tui-island_hoverable`.
> fix(kit): put tui-island_transparent after tui-island_hoverable

- projects/addon-doc/src/components/navigation/navigation.style.less
- projects/core/styles/mixins/mixins.less
- projects/kit/components/stepper/stepper.style.less
Accessibility concerns [#](https://gomakethings.com/how-to-animate-scrolling-to-anchor-links-with-one-line-of-css/#accessibility-concerns)
Animations can cause issues for users who suffer from motion sickness and other conditions.
Fortunately, Windows, macOs, iOS, and Android all provide a way for users to specify that they prefer reduced motion. And all modern browsers (but not IE) provide a way to check for that setting in both CSS and JavaScript.
When using scroll-behavior, you should add a @media check for preders-reduced-motion: reduce, and revert to the default auto.
This prevents animated scrolling when users have specified that they’d prefer reduced motion.
> feat(core): disable smooth scrolling when users have prefers-reduced-motion enabled

- .eslintrc.js
- projects/eslint-plugin/no-deep-imports.js
The script gets the absolute path of the file, so if another folder (except for our Taiga `projects` folder) in that path was named `projects` the script would incorrectly resolve the package name to that folders child name.
Now we check for the regex match only relative to our working directory.
> fix(eslint-plugin): fix incorrect project name search

- projects/addon-mobile/components/mobile-dialog/index.ts
- projects/addon-mobile/components/mobile-dialog/mobile-dialog.service.ts
- projects/addon-mobile/components/mobile-dialog/mobile-dialog.template.html
- projects/addon-mobile/components/mobile-dialog/mobile-dialog.tokens.ts
- projects/addon-mobile/components/mobile-dialog/test/mobile-dialog.component.spec.ts
- projects/core/components/dialog/dialog.service.ts
- projects/core/components/dialog/dialog.tokens.ts
- projects/core/components/dialog/index.ts
- projects/core/components/dialog/test/dialog.component.spec.ts
- projects/kit/components/pdf-viewer/index.ts
- projects/kit/components/pdf-viewer/pdf-viewer.service.ts
- projects/kit/components/pdf-viewer/pdf-viewer.template.html
- projects/kit/components/pdf-viewer/pdf-viewer.tokens.ts
- projects/kit/components/pdf-viewer/test/pdf-viewer.component.spec.ts
- projects/kit/components/push/index.ts
- projects/kit/components/push/push.options.ts
- projects/kit/components/push/push.service.ts
- projects/kit/components/push/push.template.html
- projects/kit/components/push/push.tokens.ts
- projects/kit/components/push/test/push.component.spec.ts
Does not exist.
Closes https://github.com/Tinkoff/taiga-ui/issues/2267
A token is provided so that the user can configure all dialogs, without the need to provide the same configuration each time a new dialog is opened.
> feat: add tokens for customizing different dialogs that extend `AbstractTuiDialogService`

- projects/core/components/primitive-textfield/primitive-textfield.template.html
- projects/demo/src/modules/components/select/examples/11/index.html
- projects/demo/src/modules/components/select/examples/11/index.ts
- projects/demo/src/modules/components/select/select.component.ts
- projects/demo/src/modules/components/select/select.module.ts
- projects/demo/src/modules/components/select/select.template.html
- projects/kit/components/select/index.ts
- projects/kit/components/select/native-select/native-select-group.component.ts
- projects/kit/components/select/native-select/native-select-group.template.html
- projects/kit/components/select/native-select/native-select.component.ts
- projects/kit/components/select/native-select/native-select.style.less
- projects/kit/components/select/native-select/native-select.template.html
- projects/kit/components/select/native-select/native-select.ts
- projects/kit/components/select/select.component.ts
- projects/kit/components/select/select.module.ts
- projects/kit/components/select/select.template.html
#1358
https://user-images.githubusercontent.com/46284632/198043254-7152da74-a7df-4c65-bc20-fc268bf37a77.mov
> feat(kit): `Select` add ability to use native select on mobile

- projects/eslint-plugin/no-deep-imports.js
Same problem as here:
https://github.com/Tinkoff/taiga-ui/pull/2741
> fix(eslint-plugin): broken `no-deep-imports` on `Windows`-OS

- projects/cdk/pipes/index.ts
- projects/cdk/pipes/is-present/index.ts
- projects/cdk/pipes/is-present/is-present.module.ts
- projects/cdk/pipes/is-present/is-present.pipe.ts
- projects/cdk/pipes/is-present/ng-package.json
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/pipes/is-present/examples/1/component.ts
- projects/demo/src/modules/pipes/is-present/examples/1/style.less
- projects/demo/src/modules/pipes/is-present/examples/1/template.html
- projects/demo/src/modules/pipes/is-present/examples/import/import-module.md
- projects/demo/src/modules/pipes/is-present/examples/import/insert-template.md
- projects/demo/src/modules/pipes/is-present/is-present.component.ts
- projects/demo/src/modules/pipes/is-present/is-present.module.ts
- projects/demo/src/modules/pipes/is-present/is-present.template.html
> feat(cdk): implement `tuiIsPresent` pipe

- projects/kit/components/avatar/tests/avatar.component.spec.ts
- projects/testing/core/avatar.harness.ts
- projects/testing/core/index.ts
Introduces ComponentHarness for card component.
> feat(testing): avatar harness test

- projects/demo/src/modules/app/stackblitz/stackblitz-deps.constants.ts
Open https://taiga-ui.dev/next/stackblitz
Stackblitz throws error
```
ERROR NullInjectorError: R3InjectorError(AppModule
[InjectionToken [TUI_IS_MOBILE]:
Mobile browser detection ->
InjectionToken An abstraction over window.navigator.userAgent object ->
InjectionToken An abstraction over window.navigator.userAgent object ->
InjectionToken An abstraction over window.navigator.userAgent object]: 
NullInjectorError: No provider for InjectionToken An abstraction over window.navigator.userAgent object!
at NullInjector.get (provider_collection.ts:36:1)
at R3Injector.get (r3_injector.ts:276:19)
at R3Injector.get (r3_injector.ts:276:19)
at R3Injector.get (r3_injector.ts:276:19)
at …
```
> chore(demo): `Stackblitz` uses fixed dep-versions from `cdk` & `kit` packages

- projects/demo/src/modules/components/avatar/avatar.template.html
- projects/kit/components/avatar/avatar.component.ts
- projects/kit/components/avatar/avatar.template.html
- projects/kit/directives/lazy-loading/lazy-loading.directive.ts
- projects/kit/directives/lazy-loading/lazy-loading.service.ts
If `SafeResourceUrl` is provided via the input the component breaks. 
Closes #3047 
Works correctly and can use `SafeResourceUrl`
> feat(kit): avatar now accepts `SafeResourceUrl` as `avatarUrl`

- projects/addon-table/components/table/directives/table.directive.ts
- projects/addon-table/components/table/directives/test/direction-order.directive.spec.ts
- projects/addon-table/components/table/th/th.template.html
> fix(addon-table): don't update direction order when updating sorter programmatically

- projects/i18n/languages/dutch/kit.ts
Current texts are in Norwegian (I guess?) instead of Dutch.
Now the texts are correctly translated.
> fix(i18n): fix dutch translations for `multiSelectTexts`

- projects/cdk/services/resize.service.ts
- projects/demo/src/modules/app/abstract.app.ts
- projects/demo/src/modules/app/app.component.ts
- projects/demo/src/modules/app/utils/ready-to-scroll-factory.ts
Many events are generated every second
> fix(cdk): share a single subscription to the underlying source observable between multiple subscribers

- projects/demo/src/modules/app/stackblitz/utils.ts
- projects/demo/src/modules/components/combo-box/combo-box.template.html
- projects/demo/src/modules/components/multi-select/multi-select.template.html
- projects/demo/src/modules/components/select/select.template.html
- projects/demo/src/modules/tables/table/table.template.html
Open Stackblitz example of https://taiga-ui.dev/components/multi-select#virtual:
```
Can't bind to 'itemSize' since it isn't a known property of 'cdk-virtual-scroll-viewport'.
1. If 'cdk-virtual-scroll-viewport' is an Angular component and it has 'itemSize' input, then verify that it is part of this module.
2. If 'cdk-virtual-scroll-viewport' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```
No stackblitz error.
Also, improved documentation:
* https://taiga-ui.dev/components/multi-select#virtual
* …
> chore(demo): fix broken stackblitz examples with virtual scroll

- projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts
I found that reopening happens when we click on the submenu item faster than [this debounceTime](https://github.com/Tinkoff/taiga-ui/blob/main/projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts#L139) in `DataListDropdownManager`. The child data list recreates when parent data-list already closed. 
Closes #3249 
takeUntil stops the stream when the parent data-list closes
> fix(kit): fix reopening nested dropdown

- projects/demo-integrations/cypress/tests/desktop/core/dialogs/dialog-browser-back.cy.ts
- projects/demo/src/modules/app/app.providers.ts
1. Open https://taiga-ui.dev/next/components/dialog#string
2. Press button to open dialog
3. Close dialog
The page is redirected to `https://taiga-ui.dev/next/#string`.
> chore(demo): `TUI_DIALOG_CLOSES_ON_BACK` enable for Cypress tests only

- projects/core/directives/dropdown/dropdown-options.directive.ts
- projects/core/directives/dropdown/dropdown-position-sided.directive.ts
- projects/core/directives/dropdown/dropdown-position.directive.ts
- projects/core/directives/dropdown/dropdown.component.ts
- projects/demo/src/modules/app/autogenerated-code-hints/autogenerated-code-hints.component.ts
- projects/demo/src/modules/components/abstract/control.ts
- projects/demo/src/modules/components/abstract/dropdown-documentation/dropdown-documentation.template.html
- projects/demo/src/modules/components/abstract/dropdown.ts
- projects/demo/src/modules/components/combo-box/combo-box.template.html
- projects/demo/src/modules/components/hosted-dropdown/hosted-dropdown.template.html
- projects/demo/src/modules/components/input-phone-international/input-phone-international.template.html
- projects/demo/src/modules/components/input-phone/input-phone.template.html
- projects/demo/src/modules/components/input-tag/input-tag.template.html
- projects/demo/src/modules/components/input-time/input-time.template.html
- projects/demo/src/modules/components/input/input.template.html
- projects/demo/src/modules/components/multi-select/multi-select.template.html
- projects/demo/src/modules/components/select/select.template.html
- projects/demo/src/modules/directives/dropdown-context/dropdown-context.component.html
- projects/demo/src/modules/directives/dropdown-hover/dropdown-hover.template.html
- projects/demo/src/modules/directives/dropdown-selection/dropdown-selection.template.html
- projects/demo/src/modules/directives/dropdown/dropdown.template.html
In different design systems, the `tui-data-list` may contain paddings other than `4px`, which are set by the `TUI_DROPDOWN_OFFSET` constant. I would like to do this as an injection token so that the dropdown does not cover the content.
> feat(core): replace `TUI_DROPDOWN_OFFSET` with injection token

- projects/demo/src/modules/app/app.providers.ts
```console
[HLJS]  ReferenceError: window is not defined
at Object.52013 (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/52013.js:354:4)
at __webpack_require__ (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:280663:42)
at Function.__webpack_require__.t (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:280699:38)
at _ZoneDelegate.invoke (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:202914:26)
at Object.onInvoke (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:80705:33)
at _ZoneDelegate.invoke (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:202913:52)
at Zone.run …
```
> chore(demo): fix SSR `[HLJS]  ReferenceError: window is not defined`

- package-lock.json
- package.json
- projects/addon-charts/package.json
- projects/addon-commerce/package.json
- projects/addon-doc/package.json
- projects/addon-editor/package.json
- projects/addon-mobile/package.json
- projects/addon-preview/package.json
- projects/addon-table/package.json
- projects/addon-tablebars/package.json
- projects/core/package.json
- projects/i18n/package.json
- projects/icons/package.json
- projects/kit/package.json
- projects/taiga-schematics/package.json
- projects/testing/package.json
```
WARNING in [DedupeModuleResolvePlugin]: /builds/prm/prm-ui/node_modules/@taiga-ui/cdk/node_modules/tslib/tslib.es6.js -> /builds/prm/prm-ui/node_modules/@taiga-ui/addon-tablebars/node_modules/tslib/tslib.es6.js
Error: [DedupeModuleResolvePlugin]: /builds/prm/prm-ui/node_modules/@taiga-ui/cdk/node_modules/tslib/tslib.es6.js -> /builds/prm/prm-ui/node_modules/@taiga-ui/addon-tablebars/node_modules/tslib/tslib.es6.js
at addWarning (/builds/prm/prm-ui/node_modules/@angular-devkit/build-angular/src/utils/webpack-diagnostics.js:13:31)
at /builds/prm/prm-ui/node_modules/@angular-devkit/build-angular/src/webpack/plugins/dedupe-module-resolve-plugin.js:65:58
at Hook.eval [as callAsync] …
```
> feat: `tslib` should be a transitive dependency from `@taiga/cdk`

- projects/core/interfaces/data-list-host.ts
- projects/kit/components/combo-box/combo-box.component.ts
- projects/kit/components/multi-select-option/multi-select-option.component.ts
- projects/kit/components/multi-select/multi-select.component.ts
- projects/kit/components/select-option/select-option.component.ts
> fix(kit): `MultiSelect` fix dropdown for various `updateOn` options

- projects/kit/components/slider/slider.style.less
In 3.x we dropped `normalize.less`.
But Firefox has the following default styles:
`/components/input-slider/API`
before => after
> fix(kit): `Slider` has wrong height of the progress in Firefox

- projects/addon-doc/src/utils/coerce-value.ts
- projects/addon-doc/src/utils/test/coerce-value.spec.ts
> fix(addon-doc): prevent convert invalid number to `NaN`

- projects/core/components/dialog/dialog.providers.ts
Closes https://github.com/Tinkoff/taiga-ui/issues/2223
Now `event.composedPath()[0]` used to detect target, because this will always show actual element inside shadowDom. In case of shadowDom, `event.target` is ShadowRoot
> fix(core): fix TUI_DIALOG_CLOSE_STREAM event targets 

- projects/addon-doc/src/components/example/example.component.ts
- projects/cdk/utils/miscellaneous/index.ts
- projects/cdk/utils/miscellaneous/object-from-entries.ts
- projects/demo/src/modules/app/home/home.component.ts
- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/kit/constants/max-day-range-length-mapper.ts
- projects/testing/project.json
- projects/testing/tsconfig.build.json
- tsconfig.build.json
- tsconfig.json
Developer can mistakenly use ES-features which are not supported by all required browsers.
And there will be no error!
See https://taiga-ui.dev/browser-support
Read section "Feature summary":
https://caniuse.com/?search=es2016
Read section "Feature summary":
https://caniuse.com/?search=es2017
User can't use not-supported features.
Typescript throws error for them:
> ci: `tsconfig.json` update `compilerOptions.lib`

- projects/core/directives/dropdown/dropdown.component.ts
- projects/core/directives/dropdown/dropdown.style.less
- projects/core/directives/hint/hint.style.less
Closes #3514 
`TuiHintComponent` & `TuiDropdownComponent` are initially hidden until they have position.
`TuiDropdownComponent` set an initial width in the component constructor to calculate the initial position.
> fix(core): visible incorrect initial position from `TuiDropdownComponent` & `TuiHintComponent` without animation & ngZoneEventCoalescing

- projects/addon-editor/components/editor/portal/editor-portal.directive.ts
- projects/core/abstract/rect-accessor.ts
- projects/core/directives/dropdown/dropdown-position-sided.directive.ts
- projects/core/directives/dropdown/dropdown-position.directive.ts
- projects/core/directives/hint/hint-position.directive.ts
- projects/core/tokens/index.ts
- projects/core/tokens/viewport.ts
> feat(core): `TUI_VIEWPORT` add new token

- scripts/shared/get-all-versions.ts
See https://github.com/Tinkoff/maskito/actions/runs/4183887175/jobs/7248819428
```
/home/runner/work/maskito/maskito/scripts/helpers/get-last-major-version.ts:2
return Math.max(...versions.map(x => parseInt(x)), currentMajor);
^
TypeError: versions.map is not a function
at Object.getLastMajorVersion (/home/runner/work/maskito/maskito/scripts/helpers/get-last-major-version.ts:2:33)
at makeTag (/home/runner/work/maskito/maskito/scripts/npm-publish.ts:37:[29](https://github.com/Tinkoff/maskito/actions/runs/4183887175/jobs/7248819428#step:5:30))
at /home/runner/work/maskito/maskito/scripts/npm-publish.ts:27:17
at Generator.next (<anonymous>)
at fulfilled …
```
> ci: script `getAllVersions` should always return array

- projects/demo/src/modules/app/app.providers.ts
1. Open https://taiga-ui.dev/v2/components/field-error
2. Click on source code button
Github returns `404`
> chore(demo): source code button for `2.x`-demo should open `v2.x`-branch

- projects/cdk/package.json
Run `nx migrate @taiga-ui/cdk` or `ng update @taiga-ui/cdk`:
> ci: `ng update @taiga-ui/cdk` doesn't update all Taiga's packages

- projects/addon-editor/components/editor-socket/editor-socket.component.less
After that PR: https://github.com/Tinkoff/taiga-ui/pull/3994
> fix(addon-editor): overflow `tui-editor-socket` only inside `tui-editor`

- projects/addon-editor/components/edit-link/edit-link.component.ts
- projects/addon-editor/constants/default-link-options-handler.ts
- projects/addon-editor/constants/index.ts
- projects/addon-editor/tokens/editor-options.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts
- projects/demo-integrations/cypress/tests/addon-editor/editor-links.cy.ts
> feat(addon-editor): use `https` by default for links in editor

- projects/addon-doc/src/components/main/main.component.ts
- projects/addon-doc/src/components/main/main.template.html
- projects/addon-doc/src/services/theme-night.options.ts
- projects/addon-doc/src/services/theme-night.service.ts
if we do not want to include styles
out of the box for the dark theme we can turn it off
> feat(addon-doc): add `TUI_USE_DEFAULT_NIGHT_THEME` token for ignore dark theme styles

- projects/demo/src/modules/components/stepper/examples/3/index.html
- projects/demo/src/modules/components/stepper/examples/3/index.less
- projects/demo/src/modules/components/stepper/examples/3/index.ts
- projects/demo/src/modules/components/stepper/stepper.component.ts
- projects/demo/src/modules/components/stepper/stepper.module.ts
- projects/demo/src/modules/components/stepper/stepper.template.html
- projects/kit/components/stepper/stepper.component.ts
Closes #3629
There is a chromium bug with `element.scrollIntoView` https://bugs.chromium.org/p/chromium/issues/detail?id=833617
Autoscroll doesn't work if there is more then one stepper on the page
With `TuiScrollService` scroll works correctly
> fix(kit): `Stepper` use `TuiScrollService` instead of scrollIntoView

- projects/cdk/directives/auto-focus/handlers/ios.handler.ts
- projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.html
- projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts
Closes #4129
MacOS safari
https://user-images.githubusercontent.com/12021443/230723010-f16bfe0b-7fe8-4564-b4b6-766da65c282d.mov
<br>
iOS safari:
<br>
https://user-images.githubusercontent.com/12021443/230723120-7754aa92-4e11-4a8d-a9d3-fd36a35ec8f9.MOV
> fix(cdk): support `autofill` values when trigger autofocus on `iOS`

- projects/addon-doc/src/components/page/page.component.ts
- projects/addon-doc/src/components/page/page.module.ts
- projects/addon-doc/src/components/page/page.template.html
- projects/cdk/pipes/index.ts
- projects/cdk/pipes/replace/index.ts
- projects/cdk/pipes/replace/ng-package.json
- projects/cdk/pipes/replace/replace.module.ts
- projects/cdk/pipes/replace/replace.pipe.ts
- projects/cdk/pipes/replace/test/replace.pipe.spec.ts
Using `getRouterLink` or `@tuiPure getRouterLink` results in frequent calls to `replace` on strings
https://user-images.githubusercontent.com/12021443/230497337-fe5490e2-947d-4ead-acdb-db6d6e4d11c1.mov
https://user-images.githubusercontent.com/12021443/230497453-1cc16b69-e2e3-4c41-a746-11ffde91d82f.mov
> feat(cdk): `Replace` add new pipe

- projects/eslint-plugin/rules/no-assert-without-ng-dev-mode.js
- projects/eslint-plugin/utils/get-node-by-name-from-logical-expression.js
1. Add console as a default option
2. Create a getNodeByNameFromLogicalExpression shared function
3. Replace hardcoded ngDevMode strings with a variable
Closes #4150 
The rule is refactored according to the comments from the previous PR
> refactor(eslint-plugin): refactor no-assert-without-ng-dev-mode rule

- projects/addon-charts/components/line-chart/line-chart-hint.directive.ts
- projects/addon-charts/components/line-chart/line-chart.component.ts
- projects/demo/src/modules/charts/line-chart/examples/1/index.html
- projects/demo/src/modules/charts/line-chart/examples/1/index.ts
> fix(addon-charts): `LineDaysChart` fix hint circle not disappearing, fix wrong hover index

- projects/kit/components/input-phone-international/tokens/countries-masks.ts
Closes #4185
allow input 9-digit number
> fix(kit): `InputPhoneInternational` change Cameroon phone pattern

- projects/demo/src/modules/components/input-phone-international/examples/1/index.ts
- projects/kit/components/input-phone-international/index.ts
- projects/kit/components/input-phone-international/input-phone-international.component.ts
- projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
- projects/kit/components/input-phone-international/utils/not-kz-region.ts
> fix(kit): correct detect iso code for `Kazakhstan` when phone number start with `+7`

- projects/core/components/primitive-textfield/primitive-textfield.component.ts
- projects/demo-integrations/cypress/tests/core/primitive-textfield/primitive-textfield.cy.ts
> fix(core): `PrimitiveTextfield` label should not be visible when filler used and input focused

- projects/addon-editor/directives/tiptap-editor/utils/is-empty-paragraph.ts
> fix(addon-editor): use `paragraph` type for correct detect empty

- projects/cdk/services/static-request.service.ts
- projects/cdk/services/test/static-request.service.spec.ts
Replace legacy `XMLHttpRequest` with modern `fetch`.
See https://caniuse.com/fetch
> refactor(cdk): `TuiStaticRequestService` use `fetch` instead of `XMLHttpRequest`

- projects/demo/src/modules/components/app-bar/examples/import/insert-template.md
The example HTML code for tui-app-bar is missing the closing tag for tui-app-bar.
Here's a link to the documentation: https://taiga-ui.dev/navigation/app-bar/Setup
The missing tag is at the end of step 2: 'Add to the template'
This PR adds the missing closing tag for tui-app-bar in the example code, so that the example code is valid.
> docs: add missing closing tag in app-bar docs

- projects/addon-editor/extensions/tiptap-node-view/node-view-render.ts
- projects/cdk/tokens/index.ts
- projects/cdk/tokens/is-stackblitz.ts
- projects/demo/src/environments/environment.prod.ts
- projects/demo/src/modules/app/stackblitz/project-files/configs.md
- projects/demo/src/modules/app/stackblitz/utils.ts
- projects/demo/src/modules/components/editor/images/preview/editor-preview-images.component.ts
- projects/demo/src/modules/components/editor/images/preview/examples/1/index.ts
- projects/demo/src/modules/components/editor/images/resizable/examples/1/index.ts
- projects/demo/src/modules/components/editor/images/upload/editor-upload-images.component.ts
- projects/demo/src/modules/components/editor/images/upload/examples/1/imgbb.service.ts
- projects/demo/src/modules/components/editor/images/upload/examples/1/index.ts
- projects/demo/src/modules/components/editor/upload-files/examples/1/filesio.service.ts
> fix(addon-editor): class constructor `NodeView` cannot be invoked without `new`

- projects/addon-doc/components/example/example-options.ts
- projects/addon-doc/components/example/example.component.ts
- projects/addon-doc/components/example/example.template.html
**angular-logo.component.ts**
```ts
@Component({
selector: `angular-logo`,
template: `
<tui-svg [src]="link"></tui-svg>
`,
changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AngularLogoComponent {
readonly link = `https://taiga-ui.dev/assets/images/angular.svg`;
}
export const ANGULAR_LOGO = new PolymorpheusComponent(AngularLogoComponent);
```
**app.providers.ts**
```ts
tuiDocExampleOptionsProvider({
tabTitles: new Map<string, PolymorpheusContent>([
[`index.ts`, TYPESCRIPT_LOGO],
[`app.component.ts`, ANGULAR_LOGO],
[`index.tsx`, REACT_LOGO],
]),
}),
```
> feat(addon-doc): add new parameter `tabTitles` to `TUI_DOC_EXAMPLE_OPTIONS`

- projects/core/directives/dropdown/dropdown-options.directive.ts
- projects/core/directives/dropdown/dropdown-position-sided.directive.ts
- projects/core/directives/dropdown/dropdown-position.directive.ts
- projects/core/types/dropdown-align.ts
- projects/core/types/index.ts
- projects/demo/src/modules/components/abstract/control.ts
- projects/demo/src/modules/components/abstract/dropdown-documentation/dropdown-documentation.template.html
- projects/demo/src/modules/components/abstract/dropdown.ts
Does not align dropdown to center
Closes # [3704](https://github.com/Tinkoff/taiga-ui/issues/3704)
Aligns dropdown to center
> feat(core): add ability to align dropdown to center

- projects/core/components/svg/svg.component.ts
- projects/core/constants/cache-basting-payload.ts
- projects/core/constants/index.ts
- projects/core/pipes/flag/flag.pipe.ts
- projects/core/utils/miscellaneous/icons-path-factory.ts
https://www.keycdn.com/support/what-is-cache-busting
> feat(core): support cache busting for `tuiIcon...` icons

- projects/demo/src/modules/components/line-clamp/examples/5/index.html
- projects/demo/src/modules/components/line-clamp/examples/5/index.less
- projects/demo/src/modules/components/line-clamp/examples/5/index.ts
- projects/demo/src/modules/components/line-clamp/line-clamp.component.ts
- projects/demo/src/modules/components/line-clamp/line-clamp.module.ts
- projects/demo/src/modules/components/line-clamp/line-clamp.template.html
Closes #4392
Added a few examples of how to show custom content in `tui-line-clamp`
> docs: add custom content example to line-clamp

- projects/demo-integrations/cypress/tests/kit/slider/slider.cy.ts
See https://github.com/Tinkoff/taiga-ui/actions/runs/4947701579/jobs/8847563984?pr=4427
```
Slider
✓ correctly displays values with float percentage progress (13903ms)
✓ correctly sets control value on input change (using TuiSliderKeyStepsDirective) (17823ms)
✓ with `min` > 0 (3592ms)
✓ with `min` < 0 && `max` > 0  (3250ms)
programmatically change value
ngModel
(Attempt 1 of 2) decrease value by 1 step
1) decrease value by 1 step
✓ increase value by 1 step (3556ms)
(Attempt 1 of 2) increase value by 2 step
2) increase value by 2 step
formController
✓ => 0 (4163ms)
✓ => 500 (3638ms)
✓ => 750 (3605ms)
✓ => 1000 (3498ms)
9 passing (1m)
2 failing
1) Slider
programmatically change value
ngModel
decrease value by 1 step:
AssertionError: Timed out …
```
> chore(demo-integrations): fix cypress tests for `Slider`

- projects/cdk/schematics/ng-update/v3/constants/constants.ts
- projects/cdk/schematics/ng-update/v3/constants/templates.ts
- projects/cdk/schematics/ng-update/v3/interfaces/attribute-to-directive.ts
- projects/cdk/schematics/ng-update/v3/interfaces/removable-input.ts
- projects/cdk/schematics/ng-update/v3/interfaces/replaceable-attribute-value.ts
- projects/cdk/schematics/ng-update/v3/interfaces/replaceable-attribute.ts
- projects/cdk/schematics/ng-update/v3/interfaces/replaceable-tag.ts
- projects/cdk/schematics/ng-update/v3/steps/migrate-templates.ts
- projects/cdk/schematics/ng-update/v3/steps/replace-styles.ts
- projects/cdk/schematics/ng-update/v3/tests/schematic-replace-html.spec.ts
- projects/cdk/schematics/utils/templates/elements.ts
part of #4242 
`TuiPreviewService`, `TuiPreviewModule`, `tui-preview-pagination[lastIndex]`
breakpoints global
`ngProjectAs="tuiOverNotifications"`
`tui-tooltip[direction]`
`--tui-color-link` to `--tui-link`
> fix(cdk): `Schematics` add some missed migrations

- projects/addon-commerce/components/input-cvc/input-cvc.component.ts
- projects/addon-commerce/components/input-cvc/input-cvc.module.ts
- projects/addon-commerce/components/input-cvc/input-cvc.template.html
- projects/addon-commerce/components/input-cvc/test/input-cvc.component.spec.ts
- projects/addon-commerce/components/input-expire/input-expire.component.ts
- projects/addon-commerce/components/input-expire/input-expire.module.ts
- projects/addon-commerce/components/input-expire/input-expire.template.html
- projects/addon-commerce/components/input-expire/test/input-expire.component.spec.ts
- projects/demo-integrations/cypress/tests/addon-commerce/input-expire.cy.ts
> feat(addon-commerce): `InputExpire` & `InputCVC` use `Maskito` instead of legacy `text-mask`

- projects/cdk/interfaces/index.ts
- projects/cdk/interfaces/safe-html.ts
- projects/cdk/utils/svg/svg-linear-gradient-processor.ts
- projects/core/components/svg/svg-options.ts
- projects/core/components/svg/svg.component.ts
- projects/core/components/svg/test/svg-options.component.spec.ts
- projects/core/tokens/svg-content-processor.ts
- projects/core/tokens/svg-src-processor.ts
- projects/demo/src/modules/components/avatar/avatar.component.ts
- projects/demo/src/modules/markup/icons/customization/customization-icons.component.ts
- projects/kit/components/avatar/avatar.component.ts
in proprietary repo
```ts
{
provide: TUI_SVG_SRC_PROCESSOR,
useFactory:
(base: string): TuiStringHandler<string> =>
src =>
tuiIsString(src) && src.startsWith(`tuiIconTds`)
? `${base}/${src}.svg`
: src,
deps: [TUI_ICONS_PLACE],
},
```
the main problem is that your users can overwrite default behavior
```ts
tuiSvgSrcInterceptors((src: TuiSafeHtml) =>
String(src).startsWith(`icons8::`)
? `assets/icons8/${String(src).replace(`icons8::`, ``)}.svg`
: src,
),
tuiSvgSrcInterceptors((src: TuiSafeHtml) =>
String(src).startsWith(`tuiIconTds`)
? `assets/design-tokens/${String(src)}.svg`
: src,
)
// ...
```
> feat(core): add `tuiSvgSrcInterceptors` for multiple source processing

- jest.config.ts
Run any Jest test-file via Webstorm GUI:
It throws
```
Error: Jest: Failed to parse the TypeScript config file /Users/n.barsukov/WebstormProjects/taiga-ui/jest.config.ts
Error: Cannot find module '/Users/n.barsukov/WebstormProjects/taiga-ui/projects/kit/tsconfig.json'
```
No error
> ci: cannot run Jest tests via IDE Webstorm

- projects/addon-editor/components/editor/editor.component.html
- projects/addon-editor/components/editor/editor.component.ts
@waterplea sorry, but `mousedown` fixed focus, but now it doesn't respond at all
https://taiga-ui.dev/next/editor/API
> fix(addon-editor): focus should trigger only for outside contenteditable area

- projects/demo-integrations/cypress/tests/kit/input-time/input-time.cy.ts
- projects/kit/components/input-time/input-time.component.ts
- projects/kit/components/input-time/input-time.module.ts
- projects/kit/components/input-time/input-time.template.html
- projects/kit/components/input-time/test/input-time.component.spec.ts
- projects/kit/utils/mask/create-auto-corrected-time-pipe.ts
- projects/kit/utils/mask/create-time-mask.ts
> feat(kit): `InputTime` uses `Maskito` instead of legacy `text-mask`

- projects/demo-integrations/cypress/tests/kit/input-date/input-date.cy.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/cypress/cypress.component.ts
- projects/demo/src/modules/cypress/cypress.module.ts
- projects/demo/src/modules/cypress/cypress.template.html
- projects/demo/src/modules/cypress/examples/1-input-date-initialization/index.html
- projects/demo/src/modules/cypress/examples/1-input-date-initialization/index.ts
- projects/kit/components/input-date/input-date.component.ts
- projects/kit/components/input-date/input-date.module.ts
- projects/kit/components/input-date/input-date.template.html
- projects/kit/components/input-date/test/input-date.component.spec.ts
- projects/kit/constants/date-mode-maskito-adapter.ts
- projects/kit/constants/index.ts
- projects/kit/utils/mask/create-auto-corrected-date-pipe.ts
- projects/kit/utils/mask/create-date-mask.ts
> feat(kit): `InputDate` uses `Maskito` instead of legacy `text-mask`

- projects/addon-doc/components/example/example.template.html
- projects/addon-doc/components/internal/source-code/source-code.template.html
- projects/addon-doc/components/main/main.template.html
> fix(addon-doc): anchor and theme mode buttons get proper size of svg icons

- projects/demo/src/modules/components/line-clamp/line-clamp.template.html
this commit add missing "overflownChange" output in API of line-clamp
fixes #3857
API is missing overflownChange property in line-clamp.
Closes #3857
API wont be missing overflownChange property in line-clamp.
> docs(demo): add overflownChange output event

- projects/core/styles/mixins/textfield.less
- projects/demo/src/modules/components/input/input.template.html
- projects/demo/src/modules/components/text-area/text-area.component.ts
- projects/demo/src/modules/components/text-area/text-area.template.html
- projects/kit/components/text-area/text-area.component.ts
- projects/kit/components/text-area/text-area.style.less
- projects/kit/components/text-area/text-area.template.html
> feat(kit): `TextArea` enable icons

- projects/demo-integrations/cypress/tests/kit/input-date-range/input-date-range.cy.ts
- projects/kit/components/input-date-range/input-date-range.component.ts
- projects/kit/components/input-date-range/input-date-range.module.ts
- projects/kit/components/input-date-range/input-date-range.template.html
- projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
- projects/kit/utils/mask/create-auto-corrected-date-range-pipe.ts
- projects/kit/utils/mask/create-date-range-mask.ts
> feat(kit): `InputDateRange` uses `Maskito` instead of legacy `text-mask`

- projects/core/components/primitive-textfield/primitive-textfield.template.html
- projects/kit/components/input-slider/input-slider.template.html
- projects/kit/components/range/range.template.html
- projects/kit/components/slider/helpers/slider-key-steps.directive.ts
- projects/kit/directives/mask/legacy-mask.ts
Closes #4536
there was a [breaking change](https://angular.io/guide/update-to-version-15#setdisabledstate-is-always-called-when-a-controlvalueaccessor-is-attached) in angular 15 
in ng15 we can't use `ngModel` and `[arrt.disabled]` together https://github.com/angular/angular/issues/48737
> fix(core): `PrimitiveTextfield` fix input disabled state [ng 15+]

- projects/addon-commerce/constants/card-holder-mask.ts
- projects/addon-commerce/constants/tests/card-holder-mask.spec.ts
- projects/core/utils/mask/create-correction-mask.ts
> deprecate(addon-commerce): use new `TUI_CARD_HOLDER_MASK` instead of deprecated `cardHolderMask`

- projects/kit/internal/primitive-calendar-range/primitive-calendar-range.template.html
> fix(kit): `InputDateRange` fix showing same month twice when `min` is later than given month

- projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.component.ts
- projects/addon-mobile/components/sheet/components/sheets-host/sheets-host.template.html
- projects/cdk/components/alert-host/alert-host.component.ts
- projects/cdk/components/alert-host/alert-host.template.html
- projects/cdk/components/dialog-host/dialog-host.component.ts
- projects/cdk/components/dialog-host/dialog-host.template.html
- projects/core/components/hints-host/hints-host.component.ts
- projects/core/components/hints-host/hints-host.template.html
> fix: hosts of portals can throw `ExpressionChangedAfterItHasBeenCheckedError`

- projects/core/components/svg/svg-options.ts
- projects/core/components/svg/svg.component.ts
- projects/core/tokens/icon-place.ts
> feat(core): svg source interceptor should accept svg global options

- projects/cdk/components/dialog-host/dialog-host.component.ts
- projects/kit/components/pdf-viewer/test/pdf-viewer.component.spec.ts
After fixing  [ExpressionChangedAfterItHasBeenCheckedError](https://github.com/Tinkoff/taiga-ui/pull/4533#top) one of internal project ran into another issue - mismatch between dialogs in array and view. Temporarily return markForCheck()
Closes #
> fix(cdk): fix change detection issue in `DialogHost`

- projects/core/components/svg/svg.component.ts
> fix(core): clear `cache string` when checking `source` path is `url` path

- projects/kit/components/input-date-range/input-date-range.component.ts
- projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
> fix(kit): `InputDateRange` freezes UI if `[minLength]`/`[maxLength]` are ommited

- projects/kit/components/input-inline/input-inline.style.less
> fix(kit): prevent overflow first character inside `InputInlineComponent`

- projects/kit/components/rating/rating.component.ts
Closes #4657 
Do not select a star if the selection value is less than the minimum value
> fix(kit): prevent min rate star selection

- projects/addon-editor/components/editor/editor.component.html
- projects/addon-editor/components/editor/editor.component.ts
- projects/addon-editor/components/editor/editor.module.ts
- projects/addon-editor/tokens/editor-options.ts
- projects/demo/src/modules/components/editor/starter/editor-starter.template.html
> feat(addon-editor): support `translate/spellcheck` option in editor DI

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
- projects/demo-integrations/cypress/tests/addon-commerce/input-card-grouped.cy.ts
- projects/demo/src/modules/components/input-card-grouped/examples/5/index.ts
> fix(addon-commerce): expired field should be clickable after reset of prefilled value

- projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts
> fix(addon-mobile): `PullToRefresh` properly disable when no component was provided

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
Part of #4752 
https://github.com/Tinkoff/taiga-ui/assets/12021443/db8ef4b6-7c36-4fcd-85c9-f3b70039fdad
> fix(addon-commerce): hide input filler in dark mode

- projects/addon-editor/components/color-selector/color-edit/color-edit.component.ts
- projects/addon-editor/components/color-selector/color-edit/color-edit.module.ts
- projects/addon-editor/components/color-selector/color-edit/color-edit.template.html
- projects/kit/directives/mask/legacy-mask.ts
> feat(addon-editor): `ColorSelector` uses `Maskito` instead of legacy `text-mask`

- projects/cdk/services/static-request.service.ts
- projects/demo/src/modules/icons/icons.component.ts
- projects/demo/src/modules/icons/icons.template.html
> fix(cdk): `TuiStaticRequestService` should be throw error when response code is not `200`

- projects/demo/src/modules/pipes/format-number/format-number.template.html
Not aligned value on format-number pipe demo slider
> fix(demo): added tuiTextfieldLabelOutside for format-number demo slider

- projects/addon-commerce/enums/currency-code.ts
- projects/addon-commerce/enums/currency.ts
- projects/addon-editor/components/toolbar-tools/table-row-column-manager/table-row-column-manager.component.ts
- projects/addon-editor/enums/editor-tool.ts
- projects/cdk/enums/day-of-week.ts
- projects/cdk/enums/month-number.ts
- projects/cdk/observables/drag-and-drop-from.ts
- projects/core/enums/appearance.ts
- projects/core/enums/dropdown-animation.ts
- projects/core/enums/interactive-state.ts
- projects/core/enums/notification.ts
- projects/core/enums/range-state.ts
- projects/demo/src/modules/components/dialog/examples/9/helpers/models.ts
- projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts
- projects/i18n/enums/country-iso-code.ts
- scripts/eslint/no-restricted-syntax.js
> ci: add eslint rules for declare enums

- projects/demo/src/modules/pipes/field-error/examples/1/index.html
- projects/demo/src/modules/pipes/field-error/examples/1/index.ts
- projects/demo/src/modules/utils/miscellaneous/examples/6/index.html
- projects/demo/src/modules/utils/miscellaneous/examples/6/index.ts
- projects/demo/src/modules/utils/miscellaneous/miscellaneous.component.ts
- projects/demo/src/modules/utils/miscellaneous/miscellaneous.module.ts
- projects/demo/src/modules/utils/miscellaneous/miscellaneous.template.html
Closes #4321
* Added **MarkControlAsTouchedAndValidate** section to utils/miscellaneous docs page
* Updated **FieldError** first example, added link to **MarkControlAsTouchedAndValidate** and added `distinctUntilChanged` to `valueChanges` subscription (as mentioned in #4321)
> docs: add documentation about tuiMarkControlAsTouchedAndValidate

- projects/core/components/data-list/data-list.style.less
- projects/core/components/data-list/mixin.style.less
- projects/core/components/data-list/option/option.style.less
Extracted `tuiOption` styles into a separate `mixin.style.less` file. Imported into `tuiOption` and `tuiDataList` style files respectively.
Added appropriate text and margin/padding/size styles to the `.t-empty` selector to respect the size of the `tuiDataList`. 
Adding `tuiOption` and replacing `<div>` with either `<a>` or `<button>` would also work, but then custom content provided with polymorpheus could be broken, so decided to reuse styles instead.
Closes #4803
Size of `.t-empty` inside `data-list.template.html` was not respecting `tuiDataList`'s `size`.
Size of `tuiDataList` is used to determine text size of `.t-empty` selector.
> fix(core): reuse `tuiOption` styles inside `tuiDataList`

- projects/kit/components/input-inline/input-inline.component.ts
- projects/kit/components/input-inline/input-inline.template.html
> fix(kit): `InputInline` fix width calculation

- projects/kit/components/input-files/input-files.directive.ts
> feat(kit): fix circular dependency error `TuiInputFilesDirective` and `TuiInputFilesComponent` with UMD bundle

- scripts/publish-dev-builds.ts
Nx cannot parse `x.y.z-{dev}-{shortSha}`
It should be `x.y.z-{dev}.{shortSha}`
> ci: fix name version for nightly builds

- projects/demo-integrations/cypress/tests/kit/input-date-time/input-date-time.cy.ts
- projects/kit/components/input-date-time/input-date-time.component.ts
> fix(kit): `InputDateTime` should place caret before time after selection of a new date via calendar

- projects/kit/components/input-year/input-year.component.ts
- projects/kit/components/input-year/input-year.template.html
> refactor(kit): `InputYear` uses `min` property from `Number` (`Maskito` built-in mask)

- .devcontainer/devcontainer.json
- README.md
- scripts/cspell/software.json
> ci: support `github codespaces` instead of `codeflow`

- projects/kit/components/input-range/input-range.style.less
- projects/kit/components/input-range/input-range.template.html
- projects/kit/components/input-range/test/input-range.component.spec.ts
https://github.com/Tinkoff/taiga-ui/blob/8f7798644d18a00ed0390d254363932d3c2fd181/projects/kit/components/input-range/input-range.template.html#L67-L74
> refactor(kit): `InputRange` uses `tuiTextfieldPostfix` for the right text input

- projects/demo/src/modules/components/progress-circle/progress-circle.component.ts
- projects/kit/components/progress/progress-circle/progress-circle.component.ts
- projects/kit/components/progress/progress-circle/progress-circle.style.less
https://taiga-ui.dev/components/progress-circle/API?max=0&value=0&size=xl
https://github.com/Tinkoff/taiga-ui/assets/35179038/d8c39f9d-0ec1-4158-bff9-fd3d9aed4600
> fix(kit): `ProgressCircle` should show empty circle if `max=0`

- projects/demo/src/modules/app/stackblitz/utils.ts
```
Error in src/app/app.component.html (10:13)
Can't bind to 'maskito' since it isn't a known property of 'tui-input'.
1. If 'tui-input' is an Angular component and it has 'maskito' input, then verify that it is part of this module.
2. If 'tui-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```
> chore(demo): fix Stakblitz for masked input example

- projects/i18n/languages/french/countries.ts
There are 2 Belgium in the countries file for the French translation, the one with the iso code 'BG' should be Bulgarie 
Closes # 
Change the country with 'BG'code to Bulgarie from Belgique
> fix(i18n): incorrect french translation for Bulgaria country name

- projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts
- scripts/combine-playwright-failed-screenshots.ts
- tsconfig.json
Possible file structure of `projects/demo-playwright/tests-results`:
```
├── tests-demo-demo-Demo-charts-line-days-chart-chromium
│   └── charts-line-days-chart
│       ├── 1-actual.png
│       ├── 1-diff.png
│       └── 1-expected.png
├── tests-demo-demo-Demo-charts-line-days-chart-chromium-retry1
│   ├── charts-line-days-chart
│   │   ├── 1-actual.png
│   │   ├── 1-diff.png
│   │   └── 1-expected.png
│   └── trace.zip
├── tests-demo-demo-Demo-components-input-files-chromium
│   └── components-input-files
│       ├── 3-actual.png
│       ├── 3-diff.png
│       └── 3-expected.png
├── tests-demo-demo-Demo-components-input-files-chromium-retry1
│   ├── components-input-files
│   │   ├── 3-actual.png
│   │   ├── 3-diff.png
│   │   └── …
```
> ci: fix `combine-playwright-failed-screenshots.ts` script for nested folders

- .github/workflows/e2e.yml
See [example](https://github.com/taiga-family/taiga-ui/actions/runs/5937843573/job/16101102552):
```bash
Downloading Chromium 116.0.5845.82 (playwright build v1076) from https://playwright.azureedge.net/builds/chromium/1076/chromium-linux.zip
|                                                                                |   0% of 148.1 Mb
|■■■■■■■■                                                                        |  10% of 148.1 Mb
|■■■■■■■■■■■■■■■■                                                                |  20% of 148.1 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 148.1 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 148.1 Mb …
```
> ci: install only chrome browser for `Playwright` tests

- projects/cdk/schematics/ng-update/steps/remove-module.ts
- projects/cdk/schematics/ng-update/steps/rename-types.ts
- projects/cdk/schematics/ng-update/steps/replace-enums.ts
- projects/cdk/schematics/ng-update/steps/replace-services.ts
```
🚀 Your packages will be updated to @taiga-ui/*@^3.42.1
[...]
⚡️ replacing services...
> replacing TuiPortalService...
> replacing TuiNotificationsService...
Attempted to get information from a node that was removed or forgotten.
Node text: TuiNotificationsService
/Users/n.barsukov/WebstormProjects/sme-deposits-front/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
throw err;
```
> fix(cdk): schematic error `Attempted to get information from a node that was removed or forgotten`

- projects/addon-doc/components/example/example.template.html
https://maskito.dev/frameworks/vue#example
> fix(addon-doc): `Example` should not show tabs if there is only default one (preview)

- projects/core/components/notification/notification.style.less
> fix(core): break words in notification

- projects/cdk/schematics/ng-update/utils/replace-text.ts
- projects/cdk/schematics/ng-update/v3-35/constants/icons.ts
- projects/cdk/schematics/ng-update/v3-35/index.ts
- projects/cdk/schematics/ng-update/v3-35/tests/schematic-migrate-icons.spec.ts
> fix(schematics): replace whole icon name instead of substring

- projects/addon-mobile/components/mobile-calendar/mobile-calendar.style.less
> fix(addon-mobile): remove shadow background in mobile calendar header

- projects/cdk/directives/hovered/hovered.service.ts
- projects/demo/src/modules/components/dialog/examples/6/index.html
Closes #5197
https://github.com/taiga-family/taiga-ui/assets/12021443/394a9808-4838-40cf-8388-9d964e3bbccc
> fix(core): onmouseout events don't trigger when objects move under mouse in Safari

- projects/demo-playwright/tests/core/primitive-textfield/primitive-textfield.spec.ts
I've tried to reproduce this flaky behaviour locally via
```ts
const client = await (page.context() as ChromiumBrowserContext).newCDPSession(
page,
);
await client.send(`Emulation.setCPUThrottlingRate`, {rate: 5});
```
and 
```
nx e2e demo-playwright -- primitive-textfield.spec.ts --repeat-each=50
```
Unfortunately, I can't achieve it on my local machine :(
This PR is **an attempt** to improve test stability.
> chore(demo-playwright): `TuiPrimitiveTextfield` spec has flaky test

- projects/addon-doc/components/navigation/navigation.style.less
- projects/addon-doc/components/navigation/navigation.template.html
- projects/addon-doc/interfaces/page.ts
- projects/demo/src/modules/app/pages.ts
> feat(addon-doc): support icons inside menu

- projects/experimental/components/avatar/avatar.style.less
Open
* https://taiga-ui.dev/experimental/avatar/API?src=https:%2F%2Favatars.githubusercontent.com%2Fu%2F11832552&round=true&size=s
Parent container (with no styles) has more height than `<tui-avatar />`.
**Learn more:**
* https://dev.to/christiankaindl/the-strange-img-gap-in-html
* https://stackoverflow.com/questions/5804256/image-inside-div-has-extra-space-below-the-image
* https://stackblitz.com/edit/img-inside-div-angular?file=src%2Fglobal_styles.css,src%2Fmain.ts
> fix(experimental): `Avatar` with image has redundant gap below itself

- .cspell.json
- projects/core/styles/mixins/mixins.less
- projects/core/styles/mixins/textfield.less
- projects/demo-playwright/tests/kit/textarea/textarea.spec.ts
- projects/demo/src/modules/components/textarea/textarea.component.ts
- projects/demo/src/modules/components/textarea/textarea.template.html
- projects/kit/components/textarea/textarea.style.less
> fix(kit): `Textarea` has character descenders problems

- projects/addon-doc/components/navigation/navigation.template.html
> fix(addon-doc): icon should be paste from subPage

- .github/workflows/auto-approve.yml
> chore: invalid token

- projects/core/directives/dropdown/dropdown-hover.directive.ts
- projects/core/directives/dropdown/dropdown.component.ts
- projects/demo/src/modules/directives/dropdown-hover/dropdown-hover.component.ts
- projects/demo/src/modules/directives/dropdown-hover/dropdown-hover.module.ts
- projects/demo/src/modules/directives/dropdown-hover/dropdown-hover.template.html
- projects/demo/src/modules/directives/dropdown-hover/examples/3/index.html
- projects/demo/src/modules/directives/dropdown-hover/examples/3/index.less
- projects/demo/src/modules/directives/dropdown-hover/examples/3/index.ts
> fix(core): `DropdownHover` fix unexpected closing when using nested dropdown

- projects/demo/src/modules/components/tooltip/examples/1/index.html
- projects/demo/src/modules/components/tooltip/examples/1/index.less
https://github.com/taiga-family/taiga-ui/blob/main/projects/demo/src/modules/components/tooltip/examples/1/index.html
> docs(demo): add an example for wrapping tooltip

- projects/cdk/directives/hovered/hovered.service.ts
- projects/core/directives/dropdown/dropdown-hover.directive.ts
- projects/core/directives/hint/hint-hover.directive.ts
- projects/core/directives/hint/hint.component.ts
https://github.com/taiga-family/taiga-ui/issues/5395#issuecomment-1743010657
closes #5197
> fix(core): `DropdownHover` fix dropdown closing after child transition

- projects/addon-doc/components/code/code.style.less
- projects/addon-doc/components/code/code.template.html
- projects/addon-doc/components/code/tests/code.component.spec.ts
- projects/addon-doc/components/example/example.style.less
- projects/addon-doc/components/example/example.template.html
> fix(addon-doc): use code actions together

- package-lock.json
- package.json
- projects/addon-commerce/utils/get-currency-symbol.ts
- projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts
- projects/core/components/primitive-year-picker/primitive-year-picker.component.ts
- projects/demo/src/modules/components/badged-content/examples/2/index.ts
- projects/demo/src/modules/components/multi-select/examples/8/index.ts
- projects/demo/src/modules/components/select/examples/10/index.ts
- projects/kit/utils/math/test/key-steps.spec.ts
> ci: add sonar

- .github/workflows/e2e.yml
See https://github.com/taiga-family/taiga-ui/actions/runs/6471836415/job/17575507890
```
> nx run demo-cypress:e2e --folder addon-charts
It looks like this is your first time using Cypress: 13.3.0
[STARTED] Task without title.
[SUCCESS] Task without title.
Opening Cypress...
DevTools listening on ws://127.0.0.1:39273/devtools/browser/be250f9e-a0ac-[43](https://github.com/taiga-family/taiga-ui/actions/runs/6469026495/job/17562735941?pr=5588#step:7:44)6d-b11d-b76c4ca65d71
Can't run because no spec files were found.
We searched for specs matching this glob pattern:
> /home/runner/work/taiga-ui/taiga-ui/**/addon-charts/**/*.cy.ts
Warning: run-commands command "npx cypress run --env ci=true --browser chrome --headless --project …
```
> ci: drop redundant `E2E / addon-charts` job (Cypress)

- projects/addon-mobile/directives/mobile-tabs/mobile-tabs.component.ts
- projects/addon-mobile/directives/ripple/ripple-styles.component.ts
- projects/cdk/directives/autofilled/autofilled-style.component.ts
- projects/core/components/group/group-styles.component.ts
- projects/experimental/components/button/button.directive.ts
- projects/experimental/directives/fade/fade.component.ts
- projects/experimental/directives/sensitive/sensitive.component.ts
- projects/experimental/directives/surface/surface.component.ts
Developers that are using Angular 16 currently are facing an issue having an NG0912 compilation warning.
Closes #5606 
Styles components now use host.class to insure that there will be no similar metadata for two different components. The additional side-effect, a bonus, of this approach is that the IDE won't suggest these components to use in the template.
> fix: migrate styles-components from using selectors

- projects/core/directives/dropdown/dropdown-position.directive.ts
Closes https://github.com/taiga-family/tui-editor/issues/201
> fix(core): use correct host portal viewport for dropdown position

- projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.component.ts
- projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/components/input-date-multi/examples/1/index.html
- projects/demo/src/modules/components/input-date-multi/examples/1/index.ts
- projects/demo/src/modules/components/input-date-multi/examples/import/declare-form.md
- projects/demo/src/modules/components/input-date-multi/examples/import/import-module.md
- projects/demo/src/modules/components/input-date-multi/examples/import/insert-template.md
- projects/demo/src/modules/components/input-date-multi/input-date-multi.component.ts
- projects/demo/src/modules/components/input-date-multi/input-date-multi.module.ts
- projects/demo/src/modules/components/input-date-multi/input-date-multi.template.html
- projects/kit/components/index.ts
- projects/kit/components/input-date-multi/index.ts
- projects/kit/components/input-date-multi/input-date-multi.component.ts
- projects/kit/components/input-date-multi/input-date-multi.module.ts
- projects/kit/components/input-date-multi/input-date-multi.template.html
- projects/kit/components/input-date-multi/ng-package.json
- projects/kit/components/input-tag/input-tag.component.ts
- projects/kit/utils/date/index.ts
- projects/kit/utils/date/ng-package.json
- projects/kit/utils/date/update.ts
- projects/kit/utils/index.ts
> feat(kit): add `InputMultiDate`

- projects/cdk/utils/dom/retarget-boundary-crossing.ts
> fix(cdk): don't use `layerX` and `layerY` for detect retargated element

- projects/cdk/directives/for-async/for-async.directive.ts
- projects/cdk/directives/for-async/for-async.module.ts
- projects/demo/src/modules/icons/icons-group/icons-group.module.ts
- projects/demo/src/modules/icons/icons-group/icons-group.template.html
- projects/demo/src/modules/icons/icons.component.ts
- projects/demo/src/modules/icons/icons.module.ts
- projects/demo/src/modules/icons/icons.style.less
- projects/demo/src/modules/icons/icons.template.html
> chore(demo): improve icons demonstration

- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/experimental/icon/examples/1/index.html
- projects/demo/src/modules/experimental/icon/examples/1/index.ts
- projects/demo/src/modules/experimental/icon/examples/2/index.html
- projects/demo/src/modules/experimental/icon/examples/2/index.less
- projects/demo/src/modules/experimental/icon/examples/2/index.ts
- projects/demo/src/modules/experimental/icon/examples/3/index.html
- projects/demo/src/modules/experimental/icon/examples/3/index.less
- projects/demo/src/modules/experimental/icon/examples/3/index.ts
- projects/demo/src/modules/experimental/icon/examples/import/import-module.md
- projects/demo/src/modules/experimental/icon/examples/import/insert-template.md
- projects/demo/src/modules/experimental/icon/icon.component.ts
- projects/demo/src/modules/experimental/icon/icon.module.ts
- projects/demo/src/modules/experimental/icon/icon.style.less
- projects/demo/src/modules/experimental/icon/icon.template.html
- projects/experimental/components/icon/icon.component.ts
- projects/experimental/components/icon/icon.module.ts
- projects/experimental/components/icon/icon.pipe.ts
- projects/experimental/components/icon/icon.style.less
- projects/experimental/components/icon/index.ts
- projects/experimental/components/icon/ng-package.json
- projects/experimental/components/index.ts
> feat(experimental): `Icon` add new component

- projects/demo/src/modules/experimental/amount/amount.template.html
- projects/demo/src/modules/experimental/cell/cell.template.html
- projects/demo/src/modules/experimental/surface/surface.template.html
- projects/demo/src/modules/experimental/title/title.template.html
Click on `Source code` button on these pages:
* https://taiga-ui.dev/next/experimental/amount
* https://taiga-ui.dev/next/experimental/cell
* https://taiga-ui.dev/next/experimental/surface
* https://taiga-ui.dev/next/experimental/title
It navigates to 404 page error.
> chore(demo): fix `Source code` links for `@taiga-ui/experimental` documentatation

- projects/addon-table/components/table/td/td.style.less
- projects/addon-table/components/table/th/th.style.less
Part of [#5645 ](https://github.com/taiga-family/taiga-ui/issues/5645)
So we remove `transform: translate3d(0, 0, 0)` for `filter: opacity(1)` because experiments shows that this fixes the borders dissapearing, except the borders inside of tables header with `position: sticky`
> fix(addon-table): `Table` disappearing borders

- projects/demo/src/modules/components/progress-bar/examples/7/index.html
- projects/demo/src/modules/components/progress-bar/examples/7/index.less
- projects/demo/src/modules/components/progress-bar/examples/7/index.ts
- projects/demo/src/modules/components/progress-bar/progress-bar.component.html
- projects/demo/src/modules/components/progress-bar/progress-bar.component.ts
- projects/demo/src/modules/components/progress-bar/progress-bar.module.ts
- projects/kit/components/progress/progress-bar/progress-bar.component.less
**index.html:**
```html
<progress
new
tuiProgressBar
[max]="100"
[value]="50"
></progress>
```
**index.less:**
```less
[tuiProgressBar][tuiProgressBar] {
border-radius: 0;
}
```
> feat(kit): round corners of progress can be toggled off in new version of `ProgressBar`

- projects/kit/components/combo-box/combo-box.component.ts
- projects/kit/components/combo-box/test/combo-box.component.spec.ts
- projects/kit/components/input-tag/input-tag.component.ts
- projects/kit/components/multi-select/multi-select.component.ts
- projects/kit/components/multi-select/test/multi-select.component.spec.ts
Closes #5598
A combox dropdown is not opened on value reset
> feat(kit): prevent combobox dropdown opening on value reset

- projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts
- projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts
Currently, running `nx g taiga-ui:ng-add` with animations selected creates the wrong imports: 
`providerAnimation` instead of [`provideAnimations`](https://angular.io/guide/animations#step-1-enabling-the-animations-module).
```diff
- providerAnimation
+ provideAnimations
```
The update fixes the typo
> fix(schematics): typo in provideAnimations for animations

- projects/demo/src/modules/components/toggle/examples/import/define-options.md
The docs list the wrong import path for `TuiToggleModule` as `ToggleModule`:
Fixed the correct import path
> docs: fix import in docs

- projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
- projects/demo-playwright/utils/page-objects/calendar.po.ts
- projects/demo-playwright/utils/page-objects/index.ts
- projects/demo-playwright/utils/page-objects/input-date-range.po.ts
- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/kit/components/input-date-range/input-date-range.component.ts
> fix(kit): `InputDateRange` can have empty control value after selecting something from `[items]`

- projects/addon-charts/components/axes/axes.style.less
- projects/demo/src/modules/charts/axes/axes.component.ts
- projects/demo/src/modules/charts/axes/axes.module.ts
- projects/demo/src/modules/charts/axes/axes.template.html
- projects/demo/src/modules/charts/axes/examples/3/index.html
- projects/demo/src/modules/charts/axes/examples/3/index.less
- projects/demo/src/modules/charts/axes/examples/3/index.ts
Closes  #4886
```
[axisXLabels]=[
' ', // first label
'25%',
'50%',
'75%',
' ', // last label
]
```
```
[axisXLabels]=[
'One ',  // first label
'Two',
'Three' // last label
]
```
New docs example added
> feat(addon-charts): `Axes` allows to add label for the end of axisX

- projects/demo/src/modules/components/accordion/accordion.component.ts
- projects/demo/src/modules/components/accordion/accordion.module.ts
- projects/demo/src/modules/components/accordion/accordion.template.html
- projects/demo/src/modules/components/accordion/examples/5/index.html
- projects/demo/src/modules/components/accordion/examples/5/index.ts
- projects/kit/components/accordion/accordion-item/accordion-item.style.less
> fix(kit): preventing hover from being transmitted to nested accordion item

- projects/kit/components/radio/radio.component.ts
- projects/kit/components/radio/radio.style.less
- projects/kit/components/radio/radio.template.html
Closes #5946
Just replace `tuiSlideAnimation` with CSS animation.
> fix(kit): `.t-mark` in `Radio` disappears after toggling `Expand`

- projects/cdk/abstract/portal-service.ts
The second call of the destroy method on the same hostView does not destroy the parent component.
If hostView is already destroyed, the destroy method does not call.
> fix(cdk): add checks before destroying hostView and viewRef

- projects/core/styles/mixins/appearance.less
Open ANY stackblitz example (e.g. https://taiga-ui.dev/next/components/input-date#base)
It throws
```
Error in turbo_modules/@taiga-ui/core@3.55.0-canary.17e839c/styles/mixins/appearance.less (1:0)
Could not import mixins from /~/src/styles.less
```
> chore(demo): fix all Stackblitz examples

- projects/addon-table/components/table/directives/sort-by.directive.ts
- projects/addon-table/components/table/directives/sortable.directive.ts
- projects/addon-table/components/table/th/th.component.ts
> fix(addon-table): fix sorting on table with dynamic columns

- projects/core/components/expand/expand.style.less
- projects/kit/components/tiles/tiles.style.less
> fix(core): `Expand` fix for disabled animation

- projects/core/directives/dropdown/dropdown-open.directive.ts
- projects/core/directives/dropdown/dropdown.directive.ts
> fix(core): `Dropdown` fix for initial open state

- README.md
- package.json
> chore: update README.md

- projects/addon-doc/components/documentation/documentation-property-connector.directive.ts
- projects/demo/src/modules/components/calendar-month/calendar-month.component.ts
- projects/demo/src/modules/components/calendar-month/calendar-month.template.html
- projects/demo/src/modules/components/calendar/calendar.component.ts
- projects/demo/src/modules/components/calendar/calendar.template.html
- projects/demo/src/modules/components/filter/filter.component.ts
- projects/demo/src/modules/components/filter/filter.template.html
- projects/demo/src/modules/components/input-card-grouped/input-card-grouped.component.ts
- projects/demo/src/modules/components/input-card-grouped/input-card-grouped.template.html
- projects/demo/src/modules/components/input-card/input-card.component.ts
- projects/demo/src/modules/components/input-card/input-card.template.html
- projects/demo/src/modules/components/input-files/input-files.template.html
- projects/demo/src/modules/components/line-clamp/line-clamp.template.html
- projects/demo/src/modules/components/mobile-calendar/mobile-calendar.template.html
- projects/demo/src/modules/components/push/push.component.ts
- projects/demo/src/modules/components/push/push.template.html
- projects/demo/src/modules/components/tag/tag.template.html
- projects/demo/src/modules/tables/table-pagination/table-pagination.template.html
`@Output` is not shown (flashing) in the demo.
`@Output` is shown (flashed) in the demo. The alert is also displayed, except for `(focusedChange)`.
> feat(addon-doc): display emission in `@Output` wherever possible

- projects/demo-playwright/tests/kit/input-phone/input-phone.spec.ts
- projects/kit/components/input-phone/input-phone.component.ts
- projects/kit/components/input-phone/test/input-phone.component.spec.ts
> fix(kit): `InputPhone` should erase value on blur if it's just country code

- projects/layout/components/block-status/block-status.directive.ts
- projects/layout/components/block-status/block-status.template.html
Only `a` and `button` elements are currently templated into the action container.
Elements with the directive `tuiSlot='action'` are also templated into the action container.
> feat(layout): add tuiSlot `action` to be able to template any element into the action container of BlockStatus

- projects/addon-doc/utils/index.ts
- projects/addon-doc/utils/provide-route-page-tab.ts
> feat(addon-doc): support standalone route in addon-doc

- projects/kit/components/combo-box/combo-box.component.ts
Possible solution for [#6166](https://github.com/taiga-family/taiga-ui/issues/6166)
We shouldn't check strict matcher for empty string, so it's impossible to choose empty string by typing empty string for now, but maybe it's an expected behavior
> fix(kit): `ComboBox` fix empty string option incorrect behavior

- projects/demo/src/modules/components/combo-box/combo-box.component.ts
- projects/demo/src/modules/components/combo-box/combo-box.module.ts
- projects/demo/src/modules/components/combo-box/combo-box.template.html
- projects/demo/src/modules/components/combo-box/examples/8/index.html
- projects/demo/src/modules/components/combo-box/examples/8/index.ts
Closes # 
The documentation currently lacks an example demonstrating the usage of a combo box that returns and accepts an ID to locate an item
This pull request introduces a new example in the documentation, showcasing the implementation of a combo box. The added example illustrates how to use the combo box to interact with items by returning and accepting an ID. Users can refer to this example to better understand how to integrate similar functionality into their projects.
> chore(demo): add example for combo-box ID only

- .gitignore
- package.json
> ci: drop ngcc

- projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
- projects/addon-mobile/components/mobile-calendar/mobile-calendar.style.less
> fix(addon-mobile): add smooth opacity change for `MobileCalendar` to hide blinking initial view

- projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.component.ts
- projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.style.less
- projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.template.html
- projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.module.ts
Open stackblitz https://taiga-ui.dev/components/pull-to-refresh#android
Pull to see loader:
https://github.com/taiga-family/taiga-ui/assets/35179038/cb185ffa-6f94-4c40-81a6-7dcb1808c7bb
This component use animations from `Loader`
https://github.com/taiga-family/taiga-ui/blob/b30552dfca7b78dcb102a94b31ae2db8e28ceec1/projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.style.less#L42
https://github.com/taiga-family/taiga-ui/blob/b30552dfca7b78dcb102a94b31ae2db8e28ceec1/projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.style.less#L49
But it does not import these animations to its `.less`-file!
this branch <=> main branch
https://github.com/taiga-family/taiga-ui/assets/35179038/63833926-94a3-4a25 …
> refactor(addon-mobile): use `TuiLoaderModule` inside `TUI_ANDROID_LOADER`

- projects/demo/src/modules/experimental/avatar/avatar.component.ts
- projects/demo/src/modules/experimental/avatar/avatar.module.ts
- projects/demo/src/modules/experimental/avatar/avatar.template.html
- projects/demo/src/modules/experimental/avatar/examples/6/index.html
- projects/demo/src/modules/experimental/avatar/examples/6/index.less
- projects/demo/src/modules/experimental/avatar/examples/6/index.ts
- projects/experimental/components/avatar-labelled/avatar-labeled.component.ts
- projects/experimental/components/avatar-labelled/avatar-labeled.module.ts
- projects/experimental/components/avatar-labelled/avatar-labeled.styles.less
- projects/experimental/components/avatar-labelled/index.ts
- projects/experimental/components/avatar-labelled/ng-package.json
- projects/experimental/components/index.ts
> feat(experimental): add `tui-avatar-labeled`

- projects/cdk/observables/control-value.ts
> fix(cdk): when the consumer unsubscribes, clean up data ready for next subscription

- projects/core/components/loader/loader.style.less
1. Use Safari
2. Open https://taiga-ui.dev/next/components/loader
3. Loader is not displayed
> chore(core): `Loader` uses `em` units for `<circle />` (Safari workaround)

- projects/core/utils/miscellaneous/to-animation-options.ts
I have a problem in tui-editor
> chore: export `TUI_ANIMATIONS_DEFAULT_DURATION`

- projects/cdk/services/scroll.service.ts
Closes #6551
https://rxjs.dev/api/operators/endWith
> fix(cdk): `endWith` should be pass after `takeUntil`

- projects/core/components/loader/loader.component.ts
- projects/core/components/loader/loader.style.less
- projects/core/components/loader/loader.template.html
- projects/demo/src/modules/components/loader/examples/5/index.html
- projects/demo/src/modules/components/loader/examples/5/index.less
- projects/demo/src/modules/components/loader/examples/5/index.ts
- projects/demo/src/modules/components/loader/loader.component.ts
- projects/demo/src/modules/components/loader/loader.module.ts
- projects/demo/src/modules/components/loader/loader.template.html
> feat(core)!: `Loader` has new algorithm to calculate `stroke-width`

- projects/demo/src/modules/experimental/avatar/examples/3/index.html
- projects/demo/src/modules/experimental/avatar/examples/3/index.less
> chore(demo): check that icons are resized on e2e screenshots

- projects/demo-cypress/cypress.config.ts
Before
After (increases speed)
> ci: add `experimentalSingleTabRunMode`

- projects/demo-cypress/src/tests/elastic-sticky.cy.ts
> chore: flaky again

- jest.config.ts
- package-lock.json
- projects/addon-commerce/components/input-card-grouped/test/input-card-grouped.component.spec.ts
- projects/testing/package.json
- tsconfig.spec.json
See
https://github.com/taiga-family/taiga-ui/blob/51187c72afc7b4e12e64718c4cdb806656521ded/projects/testing/package.json#L11-L12
But `jest-preset-angular@12` is incompatible with `jest@29`.
See this [line](https://github.com/thymikee/jest-preset-angular/blob/c2b55a82816ea2a49759656c7ce5b3fac013452e/package.json#L61) of `peerDependencies`.
Relates to:
* https://github.com/taiga-family/taiga-ui/pull/6774
> chore(deps): bump `jest-preset-angular` to `v13`

- projects/core/components/root/root.component.ts
> fix(core): fix `:active` state of interactive elements in Safari

- projects/core/components/scrollbar/scrollbar.component.ts
- projects/core/components/scrollbar/scrollbar.style.less
- projects/core/components/scrollbar/scrollbar.template.html
- projects/experimental/components/badge-notification/badge-notification.style.less
- projects/i18n/languages/english/kit.ts
> chore: small changes

- projects/demo/src/modules/info/browsers/browsers.component.ts
- projects/demo/src/modules/info/browsers/browsers.style.less
- projects/demo/src/modules/info/browsers/browsers.template.html
| Browser name         | Before  | After | Description                                                             |
|-----------------|-------|-------|-------------------------------------------------------------------------|
| Chrome Mobile   | 90+   | 88+   |                                                                         |
| Chrome Desktop  | 74+   | 88+   |                                                                         |
| Edge Desktop    | 74+   | 88+   |                                                                         |
| Yandex Desktop  | 19+   | 21.2+ | 21.2 uses Chromium 88                                             |
| Yandex Mobile   | 19+   | 21.2+ | 21.2 uses Chromium 88                                             |
| Opera Desktop   | 62+   | 74+ …
> feat!: new browser support

- projects/demo/src/modules/components/stepper/stepper.template.html
`state` has been renamed to `stepState` to avoid
collision with `routerLink`'s `state` input.
> chore(demo): update step state input name

- projects/demo/src/modules/experimental/navigation/examples/1/index.html
- projects/demo/src/modules/experimental/navigation/examples/2/index.html
- projects/experimental/components/navigation/aside.style.less
- projects/experimental/components/navigation/header.component.ts
- projects/experimental/components/navigation/header.style.less
- projects/experimental/components/navigation/index.ts
- projects/experimental/components/navigation/logo.component.ts
- projects/experimental/components/navigation/logo.style.less
- projects/experimental/components/navigation/main.style.less
- projects/experimental/components/navigation/nav.style.less
- projects/experimental/components/navigation/navigation.module.ts
- projects/experimental/directives/fade/fade.directive.ts
- projects/experimental/directives/fade/fade.style.less
- projects/experimental/directives/header/header.component.ts
- projects/experimental/directives/header/header.directive.ts
- projects/experimental/directives/header/header.module.ts
> feat(experimental): `Fade` enable scrolling

- projects/demo-playwright/tests/kit/input-date-time/input-date-time.spec.ts
- projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
- projects/demo-playwright/utils/page-objects/index.ts
- projects/demo-playwright/utils/page-objects/input-date-time.po.ts
- projects/kit/components/input-date-time/input-date-time.component.ts
1. Open https://taiga-ui.dev/components/input-date-time/API?timeMode=HH:MM:SS
2. Select new value for `[timeMode]`
3. Focus textfield
> fix(kit): `InputDateTime` does not change filler on dynamic change of `[timeMode]` prop

- projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
**Relates:**
* [`defaultEditorExtensions` => `TUI_EDITOR_DEFAULT_EXTENSIONS`](https://github.com/taiga-family/tui-editor/pull/808/files#diff-13726f73f8debda3b3b6201e956971dbc57dc3d996346ef1fbb53bb1bebea613)
* [`defaultEditorTools` => `TUI_EDITOR_DEFAULT_TOOLS`](https://github.com/taiga-family/tui-editor/pull/808/files#diff-f16b54a2a21fdc42e1aa8feb6f9c7bb03378a01a248805fcc2e230c21fbaf925)
> chore(schematics): add migrations for renamed editor's entities

- projects/kit/components/routable-dialog/routable-dialog.component.ts
- projects/kit/components/routable-dialog/test/routable-dialog.component.spec.ts
Closes https://github.com/taiga-family/taiga-ui/issues/6636
> fix(kit): prevent navigation to parent page if navigation occurs from dialog

- projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts
Open https://taiga-ui.dev/next/stackblitz
```
Error in turbo_modules/@angular/core@17.2.3/fesm2022/core.mjs
The entrypoint for '@angular/core' could not successfully be resolved. The file '/turbo_modules/@angular/core@15.2.10/primitives/signals' does not exist. Please log an issue with the package author or check for an updated version of the package.
```
It works
> chore: fix stackblitz starter

- projects/demo-cypress/src/tests/static-request.cy.ts
> chore: cypress flaky

- projects/demo/src/modules/pipes/format-number/format-number.template.html
Open https://taiga-ui.dev/next/pipes/format-number/API
> chore(demo): fix `API` section of documentation page `FormatNumber`

- projects/cdk/schematics/ng-update/v4/index.ts
- projects/cdk/schematics/ng-update/v4/steps/index.ts
- projects/cdk/schematics/ng-update/v4/steps/migrate-destroy-service.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-destroy-service.spec.ts
* https://angular.io/api/core/rxjs-interop/takeUntilDestroyed
* https://taiga-ui.dev/services/destroy-service
> chore(cdk): migrations for `TuiDestroyService` => `takeUntilDestroyed`(`@angular/core/rxjs-interop`)

- package-lock.json
- projects/cdk/package.json
- projects/cdk/schematics/utils/templates/elements.ts
1. Manually run migration
```shell
nx build cdk
schematics ./dist/cdk:updateToV3 --allow-private --dry-run true
```
It throws:
```shell
command not found: schematics
```
2. Add `@angular-devkit/schematics-cli` to `projects/package.json`.
3. Manually run migration again
```shell
schematics ./dist/cdk:updateToV3 --allow-private --dry-run true
```
it throws:
```shell
An error occured:
Error [ERR_REQUIRE_ESM]: require() of ES Module
/<path>/taiga-ui/dist/cdk/fesm2022/taiga-ui-cdk.mjs
not supported.
Instead change the require of 
/<path>/taiga-ui/dist/cdk/fesm2022/taiga-ui-cdk.mjs
to a dynamic import() which is available in all CommonJS modules.
```
```shell
➜ schematics ./dist/cdk:updateToV3 --allow-private --dry-run true
Debug mode enabled by default for local collections.
🚀 Your packages …
```
> chore(schematics): fix possibility to manually run migration schematics

- projects/demo/src/modules/components/accordion/accordion.template.html
- projects/demo/src/modules/components/expand/expand.template.html
- projects/demo/src/modules/components/input-card-grouped/input-card-grouped.template.html
- projects/demo/src/modules/components/input-card/input-card.template.html
- projects/demo/src/modules/icons/icons.template.html
- projects/demo/src/modules/pipes/format-number/format-number.template.html
- projects/demo/src/modules/pipes/format-phone/format-phone.template.html
- projects/demo/src/modules/services/scroll/scroll.template.html
- projects/demo/src/styles.less
Remove global class 
https://github.com/taiga-family/taiga-ui/blob/e64eab50057f1fd11b5acee10b76eb8d082a69d9/projects/demo/src/styles.less#L27-L29
> chore(demo): remove global class `b-full-width`

- projects/cdk/schematics/collection.json
- projects/cdk/schematics/ng-update/v4/schema.json
- projects/cdk/schematics/ng-update/v4/steps/migrate-destroy-service.ts
- projects/cdk/schematics/ng-update/v4/steps/migrate-legacy-mask.ts
- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badged-content.ts
- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-money.ts
- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-prevent-default.ts
Relates #5808
1. Manually run migration for `4.0.0`
```shell
nx build cdk
schematics ./dist/cdk:updateToV4 --allow-private --dry-run true
```
it throws:
```shell
Debug mode enabled by default for local collections.
An error occured:
Error: Schematic "updateToV4" not found in collection "./dist/cdk".
```
2. Add `projects/cdk/schematics/ng-update/v4/schema.json` and update `projects/cdk/schematics/collection.json`
3. Manually run migration for `4.0.0`
```shell
nx build cdk --skip-nx-cache
schematics ./dist/cdk:updateToV4 --allow-private --dry-run true
```
It throws:
```shell
An error occured:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]:
Package subpath './schematics' is not defined by "exports" in
/Users/n.barsukov/WebstormProjects/taiga-ui/dist/cdk/package.json imported
from …
```
> chore(schematics): enable possibility to manually run migration for `4.0.0`

- .github/workflows/schematics.yml
- projects/cdk/project.json
- projects/cdk/schematics/ng-update/v4/index.ts
Relates to #5808
```shell
➜ schematics ./dist/cdk:updateToV4 --allow-private --dry-run true
Debug mode enabled by default for local collections.
🚀 Your packages will be updated to @taiga-ui/*@^3.59.0
⚡️ replacing identifiers...
An error occured:
TypeError: Cannot read properties of null (reading 'getSourceFiles')
at getSourceFiles (/Users/n.barsukov/WebstormProjects/taiga-ui/node_modules/ng-morph/source-file/helpers/get-source-files.js:6:45)
at /Users/n.barsukov/WebstormProjects/taiga-ui/node_modules/ng-morph/imports/helpers/get-imports.js:7:58
at getDeclaration (/Users/n.barsukov/WebstormProjects/taiga-ui/node_modules/ng-morph/utils/helpers/get-declaration-getter.js:7:16)
at getNamedImportReferences (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/cdk/schematics/utils/get-named-import-re …
```
> chore: fix `v4` migration `TypeError: Cannot read properties of null (reading 'getSourceFiles')`

- projects/cdk/schematics/utils/get-named-import-references.ts
```shell
> nx run cdk:schematics --v=4
Debug mode enabled by default for local collections.
🚀 Your packages will be updated to @taiga-ui/*@^3.59.0
⚡️ replacing identifiers...
✅  identifiers replaced 
⚡️ removing modules...
✅  modules removed 
⚡️ updating TuiMapper typing to the typed version
⚡️ renaming TuiTypedMapper to TuiMapper
🏆 successfully migrated 
⚡️ updating TuiMatcher typing to the typed version
⚡️ renaming TuiTypedMatcher to TuiMatcher
🏆 successfully migrated 
⚡️ migrating legacy mask utils...
⚡️ tuiMaskedMoneyValueIsEmpty
⚡️ tuiMaskedNumberStringToNumber
🏆 successfully migrated 
⚡️ migrating TuiDestroyService => takeUntilDestroyed ...
🏆 successfully migrated 
⚡️ migrating templates...
✅  templates migrated 
🏆 We migrated packages to @taiga-ui/*@^3.59.0 in 484.62 sec. 
UPDATE …
```
> chore(schematics): optimize `getNamedImportReferences` utility

- projects/demo-playwright/tests/kit/tabs/tabs.spec.ts
- projects/kit/components/tabs/tab/tab.style.less
> fix(kit): `TasbWithMore` fix redundant left margin for single element

- projects/demo/src/emulate/ng-zone-options.ts
- projects/kit/components/input-files/input-files.component.ts
> fix(kit): `InputFiles` fix drag over detection when zone.js event coalescing is enabled

- projects/cdk/schematics/ng-update/v4/steps/migrate-destroy-service.ts
- projects/cdk/schematics/ng-update/v4/tests/migrate-destroy-service/schematic-migrate-destroy-service.spec.ts
> chore(cdk): fix duplicating property problem in `TuiDestroyService => takeUntilDestroyed` migration

- projects/addon-doc/components/doc-tab/doc-tab.component.html
- projects/addon-doc/components/doc-tab/doc-tab.component.less
- projects/addon-doc/components/doc-tab/doc-tab.module.ts
- projects/core/components/link/link.module.ts
- projects/core/components/link/link.style.less
- projects/core/components/link/link.template.html
- projects/demo/src/modules/app/app.style.less
Run `nx serve-ssr` and open `/getting-started` page
```shell
Assertion failed: Failed to load external SVG assets/images/github.svg
Assertion failed: Failed to load external SVG assets/icons/telegram.svg
Assertion failed: Failed to load external SVG assets/icons/discord.svg
Assertion failed: Failed to load external SVG assets/icons/stackblitz.svg
Assertion failed: Failed to load external SVG assets/icons/angular.svg
Assertion failed: Failed to load external SVG assets/icons/angular.svg
Assertion failed: Failed to load external SVG assets/icons/angular.svg
Assertion failed: Failed to load external SVG assets/icons/angular.svg
Assertion failed: Failed to load external SVG assets/icons/nx.svg
Assertion failed: Failed to load external SVG assets/icons/nx.svg
Assertion failed: Failed to load …
```
> refactor(core): `Link` uses `Icon` instead of legacy `Svg`

- projects/demo/tsconfig.server.json
Run `nx serve-ssr` and open `/getting-started`.
It throws:
```shell
Warning: /Users/n.barsukov/WebstormProjects/taiga-ui/projects/demo-playwright/utils/common.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
Warning: /Users/n.barsukov/WebstormProjects/taiga-ui/projects/demo-playwright/utils/goto.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
Warning: /Users/n.barsukov/WebstormProjects/taiga-ui/projects/demo-playwright/utils/hide-element.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```
and 
```shell
TypeScript compiler …
```
> chore(demo): fix some warning logs during `nx serve-ssr`

- projects/experimental/components/navigation/main.style.less
Run `npm start`.
It throws warning:
```shell
./projects/experimental/components/navigation/main.style.less?ngResource -
Warning: Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
(47:3) from "autoprefixer" plugin:
You should write display: flex by final spec instead of display: box
Code:
display: box
```
---
Open http://localhost:3333/experimental/navigation#expansive
---
Open `projects/experimental/components/navigation/main.style.less`
> chore(experimental): fix invalid value of property `display`

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
- projects/addon-commerce/components/input-card-grouped/input-card-grouped.options.ts
- projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
- projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
- projects/addon-commerce/components/input-cvc/input-cvc.component.ts
- projects/addon-commerce/components/input-cvc/input-cvc.style.less
- projects/addon-commerce/components/input-cvc/input-cvc.template.html
Closes https://github.com/taiga-family/taiga-ui/issues/7052
Add flag to hide cvc code in InputCard, InputCardGrouped
> feat(addon-commerce): add flag hide cvc code in InputCard, InputCardGrouped

- projects/demo/src/modules/components/progress-bar/examples/1/index.ts
- projects/demo/src/modules/components/progress-bar/examples/2/index.ts
- projects/demo/src/modules/components/progress-bar/examples/4/index.ts
- projects/demo/src/modules/components/progress-circle/examples/1/index.ts
- projects/demo/src/modules/components/progress-circle/examples/3/index.ts
- projects/demo/src/modules/components/progress-circle/examples/5/index.ts
- projects/demo/src/modules/components/progress-circle/examples/6/index.ts
Run `nx serve-ssr` and open `/components/progress-bar` or `/components/progress-cicle`.
They will be never loaded.
> chore(demo): documentation pages `ProgressBar` & `ProgressCircle` have infinite SSR

- projects/kit/components/files/file/file.component.ts
Run `nx serve-ssr` and open `/components/input-files`.
Node.js throws:
```ts
ReferenceError: File is not defined
at createPreview (webpack:///projects/kit/components/files/file/file.component.ts:150:29)
at patched (webpack:///projects/cdk/decorators/pure.ts:141:38)
at preview (webpack:///projects/kit/components/files/file/file.component.ts:81:34)
at templateFn (webpack:///projects/kit/components/files/file/file.template.html:47:10)
at executeTemplate (webpack:///node_modules/@angular/core/fesm2022/core.mjs:12003:13)
at refreshView (webpack:///node_modules/@angular/core/fesm2022/core.mjs:13498:13)
at detectChangesInView (webpack:///node_modules/@angular/core/fesm2022/core.mjs:13663:9)
at detectChangesInEmbeddedViews (webpack:///node_modules/@angular/core/fesm2022/core.mjs:13606:13)
at …
```
> fix(kit): `File` throws SSR error `ReferenceError: File is not defined`

- projects/demo/src/modules/directives/dropdown/examples/3/index.html
- projects/demo/src/modules/directives/dropdown/examples/3/index.ts
Run `nx serve-ssr` and open `/directives/dropdown`.
This page will never be loaded.
> chore(demo): documentation page `Dropdown` has infinite SSR

- projects/kit/components/tiles/tile.component.ts
- projects/kit/components/tiles/tile.service.ts
- projects/kit/components/tiles/tiles.style.less
Run `nx serve-ssr` and open `/components/reorder`.
Node.js throws:
```shell
TypeError: element.getBoundingClientRect is not a function
at setPosition (webpack:///projects/kit/components/tiles/tile.service.ts:87:30)
at offset (webpack:///projects/kit/components/tiles/tile.service.ts:35:22)
at next (webpack:///node_modules/rxjs/dist/cjs/internal/Subscriber.js:161:21)
at _next (webpack:///node_modules/rxjs/dist/cjs/internal/Subscriber.js:101:26)
at next (webpack:///node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
at onNext (webpack:///node_modules/rxjs/dist/cjs/internal/operators/map.js:10:24)
at _next (webpack:///node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
at next (webpack:///node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
at onNext …
```
> fix(kit): `Tile` throws SSR error `TypeError: element.getBoundingClientRect is not a function`

- projects/addon-table/components/table-pagination/table-pagination.template.html
I figured that it is not necessary to output `tuiDropdown` at `total === 0`
Closes #7025
> fix(addon-table): added a check that `total` is zero

- projects/kit/components/stepper/stepper.component.ts
> fix(kit): remove pure getNativeElements

- projects/cdk/directives/media/media.directive.ts
Run `nx serve-ssr` and open `/directives/media`.
Node.js throws:
```shell
TypeError: this.el.pause is not a function
at TuiMediaDirective.set paused (webpack:///projects/cdk/directives/media/media.directive.ts:50:21)
at writeToDirectiveInput (webpack:///node_modules/@angular/core/fesm2022/core.mjs:12889:34)
at setInputsForProperty (webpack:///node_modules/@angular/core/fesm2022/core.mjs:13123:9)
at elementPropertyInternal (webpack:///node_modules/@angular/core/fesm2022/core.mjs:12414:9)
at ɵɵproperty (webpack:///node_modules/@angular/core/fesm2022/core.mjs:16255:9)
at TuiMediaExample1_Template (webpack:///projects/demo/src/modules/directives/media/examples/1/index.html:6:34)
at executeTemplate (webpack:///node_modules/@angular/core/fesm2022/core.mjs:12003:13)
at refreshView …
```
> fix(cdk): `Media` throws SSR error `TypeError: this.el.pause is not a function`

- projects/demo/src/modules/components/carousel/examples/1/index.html
- projects/demo/src/modules/components/carousel/examples/1/index.ts
Run `nx serve-ssr` and open `/components/carousel`.
This page will never be loaded.
> chore(demo): documentation page `Carousel` has infinite SSR

- .github/workflows/e2e-playwright.yml
- package.json
- projects/demo/server.ts
- projects/demo/src/main.server.ts
- projects/demo/src/modules/app/server-error-handler.ts
> ci: any playwright test should fail on any uncaught SSR error

- projects/kit/tokens/countries-masks.ts
This PR introduces a new provider `tuiCountriesMasksProvider` that allows overriding or extending the default country masks for phone number formatting.
Usage example:
```js
providers: [
tuiCountriesMasksProvider({
[TuiCountryIsoCode.VN]: '+84#########' // Overriding the mask for Vietnam
})
],
```
> feat(kit): add `tuiCountriesMasksProvider`

- projects/kit/components/input-date/input-date.component.ts
> fix(kit): `InputDate` fix opening mobile calendar in read-only mode

- projects/cdk/directives/active-zone/active-zone.directive.ts
> fix(cdk): `ActiveZone` fix event handling for IOS Safari

- projects/addon-doc/components/demo/demo.template.html
- projects/demo/src/modules/app/demo-routes.ts
- projects/demo/src/modules/components/input/examples/5/index.html
- projects/demo/src/modules/components/input/input.component.ts
- projects/demo/src/modules/components/input/input.template.html
- projects/demo/src/modules/components/theme-night/theme-night.component.ts
- projects/demo/src/modules/components/theme-night/theme-night.template.html
- projects/demo/src/modules/customization/wrapper/index.html
- projects/demo/src/modules/customization/wrapper/index.ts
> chore(demo): fix broken link for documentation page `Mode`

- projects/demo/src/modules/app/app.routes.ts
Closes https://github.com/taiga-family/taiga-ui/issues/7213
1. Changed route path from `Demo.Present` to `Demo.IsPresent`
> chore(demo): changed route path for `IsPresent` docs page

- projects/kit/components/textarea/textarea.style.less
1. Use Safari / Firefox Desktop
2. Open https://taiga-ui.dev/components/textarea/API?expandable=true&maxLength=97&tuiTextfieldLabelOutside=true&sandboxWidth=243
3. Paste the following text inside textfield
```
Lorem Ipsum is simply dummy text of the printing and typesetting industry. https://my-site.abc.qwertyuiop.com/group1/group2/3921234
```
According to [MDN specifications](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#values) about "word-break":
`normal` (default value) and `keep-all` should work in the same way for Non-CJK!
It is true for Chrome, yep. However, there is difference for some browsers (i.e. Safari & FF).
Explore this stackblitz (use Safari or FF):
https://stackblitz.com/edit/normal-and-keep-all-diff?file=styles.css,index.html
Before this fix, `<textarea>` …
> fix(kit): `Textarea` incorrectly highlights extra characters for long words with hyphen in Safari/FF

- projects/cdk/schematics/ng-update/v4/index.ts
- projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts
- projects/cdk/schematics/ng-update/v4/steps/migrate-option-providers.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-providers.spec.ts
- projects/cdk/schematics/utils/insert-todo.ts
- projects/demo/src/modules/components/input-number/examples/6/index.ts
- projects/kit/components/input-number/input-number.options.ts
> refactor!: remove `precision`, `decimal` options from `InputNumberOptions`, add migration

- tsconfig.json
1. Locally run playwright tests (it will produce `projects/demo-playwright/tests-report` folder)
2. Change any another file
3. Try to create commit
4. Pre-commit hooks run (it triggers also `npm run typecheck`)
It throws
```sh
Found 8252 errors in 11 files.
Errors  Files
2910  projects/demo-playwright/tests-report/trace/assets/codeMirrorModule-ITBVLGwz.js:1
4008  projects/demo-playwright/tests-report/trace/assets/testServerConnection-Dj8RHZjQ.js:1
52  projects/demo-playwright/tests-report/trace/index.64QeAVuG.js:1
910  projects/demo-playwright/tests-report/trace/sw.bundle.js:1
339  projects/demo-playwright/tests-report/trace/uiMode.Bug1KrYi.js:1
[...]
```
> chore: add `projects/demo-playwright/tests-report` to `exclude` of root `tsconfig.json`

- projects/demo-playwright/tests/kit/input-phone/input-phone.spec.ts
```
1) [firefox] › tests/kit/input-phone/input-phone.spec.ts:21:13 › InputPhone › API page › Don't duplicate Code 52 When Inputting Digit '2' After Clearing 
Error: Timed out 5000ms waiting for expect(locator).toHaveValue(expected)
Locator: locator('#demo-content').locator('tui-input-phone').getByRole('textbox')
Expected string: "+52 (52"
Received string: "+52 "
```
> chore(demo-playwright): make `InputPhone` tests be compatible both Chromium & Firefox

- projects/demo-playwright/tests/kit/dropdown-context/dropdown-context.spec.ts
Relates to:
* https://github.com/microsoft/playwright/issues/30793
> chore(demo-playwright): make `DropdownContext` tests be compatible both Chromium & Firefox

- projects/demo-playwright/tests/core/primitive-textfield/primitive-textfield.spec.ts
Run the following test
https://github.com/taiga-family/taiga-ui/blob/10dffbf9e3b8b52cd649f5afec1f0c0caea6a638/projects/demo-playwright/tests/core/primitive-textfield/primitive-textfield.spec.ts#L7-L20
Chrome ✅ 
Firefox ❌
```shell
1 failed
[firefox] › tests/core/primitive-textfield/primitive-textfield.spec.ts:7:9 › TuiPrimitiveTextfield › Tooltip in primitive-textfield works 
105 passed (9.1m)
Error:   1) [firefox] › tests/core/primitive-textfield/primitive-textfield.spec.ts:7:9 › TuiPrimitiveTextfield › Tooltip in primitive-textfield works 
Error: Timed out 5000ms waiting for expect(locator).toBeAttached()
Locator: locator('tui-hint')
Expected: attached
Received: <element(s) not found>
Call log:
- expect.toBeAttached with timeout 5000ms
- waiting for locator('tui-hint')
16 |         await …
```
> chore(demo-playwright): make `TuiPrimitiveTextfield` tests compatible with both Chromium & Firefox

- .github/renovate.json
- package-lock.json
- package.json
- projects/icons/package.json
Approximately 3 weeks ago (mid-April) our screenshot tests became too flaky.
The main problem – font rendering.
See some examples:
1. Sometimes it **incorrectly** applies the **font-weight**
2. **Flaky font-kerning** 
1. Open dev tools
2. Open network tab => filter by font type
3. Open https://taiga-ui.dev/next/getting-started
At different time opening of this page produces different results:
Open history of `main`-branch:
Revert
* https://github.com/taiga-family/taiga-ui/pull/7261
1. Run `nx build demo`
5. Open `dist/demo/browser/index.html`
1. Run `nx build demo`
2. Open `dist/demo/browser/index.html`
> chore(deps): revert `rollup` version to stabilize playwright tests

- projects/demo-playwright/utils/goto.ts
1. Replace this file https://github.com/taiga-family/taiga-ui/blob/main/projects/demo-playwright/stubs/manrope-fonts.ttf with any another font
2. Run playwright tests
> chore(demo-playwright): `tuiGoto` should mock both `.ttf` and `.woff2` fonts

- package-lock.json
- projects/cdk/package.json
- projects/legacy/LICENSE
- projects/legacy/README.md
- projects/legacy/components/index.ts
- projects/legacy/components/ng-package.json
- projects/legacy/index.ts
- projects/legacy/ng-package.json
- projects/legacy/package.json
- projects/legacy/project.json
- tsconfig.json
> feat: create new package `@taiga-ui/legacy`

- projects/legacy/components/input-range/test/input-range.component.spec.ts
- projects/testing/utils/native-input.page-object.ts
**index.html:**
```html
<div tuiGroup>
<tui-primitive-textfield #countrySelect />
<tui-input #actualTextfield />
</div>
```
Not it is impossible to query nested `<input />` from `<tui-input />` without adding `automation-id`.
**New behavior:**
```ts
const inputPO = new TuiNativeInputPO(
fixture,
fixture.debugElement.query(By.css('tui-input input')),
);
```
> refactor(testing): improve flexibility of `TuiNativeInputPO`

- projects/core/directives/dropdown/dropdown.component.ts
- projects/core/directives/hint/hint.component.ts
> fix(core): close `Hint` and `Dropdown` when host is detached from dom

- projects/core/components/textfield/textfield.style.less
Open https://taiga-ui.dev/next/components/textfield#dropdown
```html
<tui-textfield
tuiChevron
>
<select
tuiTextfield
[(ngModel)]="value"
></select>
</tui-textfield>
```
https://github.com/taiga-family/taiga-ui/assets/35179038/95a9834f-43b7-4147-ab84-4c3519f3d6d7
https://github.com/taiga-family/taiga-ui/assets/35179038/5dc7403f-89c1-4fe4-a3e3-b12d321a21fd
___
Relates to:
* https://github.com/taiga-family/taiga-ui/pull/7580#discussion_r1622728628
> chore(core): add `cursor: pointer` for `<select tuiTextfield />`

- projects/core/directives/hint/hint.component.ts
> chore: close `Hint` and `Dropdown` when host is detached from dom

- projects/core/components/textfield/textfield.component.ts
Imagine that you develop any custom input using new `Textfield`.
**your-component.template.html:**
```html
<tui-textfield>
<input tuiTextfield />
<label tuiLabel><ng-content /></label>
</tui-textfield>
```
Public API of your component:
```html
<your-custom-input>
<strong>Awesome label</strong>
</your-custom-input>
<your-custom-input/>
```
> refactor(core): `Textfield` should not shift all content if empty `label[tuiLabel]` is passed

- projects/core/directives/dropdown/dropdown-open.directive.ts
```ts
@Component({
standalone: true,
imports: [TuiButtonDirective, TuiActiveZoneDirective, TuiDropdownModule],
template: `
<button
tuiButton
type="button"
[tuiDropdown]="'ANY CONTENT DROPDOWN'"
[(tuiDropdownOpen)]="open"
(tuiActiveZoneChange)="(0)"
>
Button
</button>
`,
})
export default class ExampleComponent {
protected open = false;
}
```
It will throw:
```shell
Error: NG0309:
Directive TuiActiveZoneDirective matches multiple times on the same element.
Directives can only match an element once.
```
> chore: include inputs/outputs of host directive `ActiveZone` in `DropdownOpen`'s API

- projects/legacy/components/input-number/input-number.style.less
> fix(legacy): fix `InputNumber` buttons styles priority for Safari

- projects/kit/components/input-tag/input-tag.component.ts
> fix(kit): `InputTag` fix scrolling to input

- projects/core/directives/dropdown/dropdown-selection.directive.ts
- projects/demo-playwright/tests/core/dropdown/dropdown.spec.ts
> fix(core): `DropdownSelection` fix selection error in textarea (#7626)

- projects/demo-playwright/tests/kit/input-date-time/input-date-time.spec.ts
- projects/legacy/components/input-date-time/input-date-time.component.ts
Closes https://github.com/taiga-family/taiga-ui/issues/7638
> fix(legacy): InputDateTime should format textfield value on blur in the same way as InputTime

- projects/core/directives/hint/hint.style.less
- projects/demo-playwright/tests/kit/input-date-time/input-date-time.spec.ts
- projects/kit/components/input-date-time/input-date-time.component.ts
Closes https://github.com/taiga-family/taiga-ui/issues/7638
> fix(kit): `InputDateTime` should format textfield value on blur 

- projects/kit/components/input-date/input-date.component.ts
- projects/kit/components/input-date/input-date.template.html
> fix(kit): ignore native calendar for desktop

- projects/core/directives/dropdown/dropdown-open.directive.ts
- projects/core/directives/dropdown/dropdown.component.ts
- projects/core/directives/dropdown/dropdown.directive.ts
- projects/core/directives/dropdown/dropdown.template.html
- projects/demo/src/modules/components/card-large/examples/7/index.html
- projects/demo/src/modules/components/cell/examples/6/index.html
- projects/demo/src/modules/components/data-list/examples/2/index.html
- projects/demo/src/modules/components/data-list/examples/2/index.ts
- projects/demo/src/modules/components/data-list/examples/5/index.html
- projects/demo/src/modules/components/data-list/examples/5/index.ts
- projects/demo/src/modules/components/data-list/index.html
- projects/demo/src/modules/components/input-date/examples/2/index.html
- projects/demo/src/modules/components/input-date/examples/2/index.ts
- projects/demo/src/modules/components/line-clamp/examples/4/index.html
- projects/demo/src/modules/components/line-clamp/examples/4/index.ts
- projects/demo/src/modules/components/tabs/examples/3/index.html
- projects/demo/src/modules/components/tabs/examples/3/index.ts
- projects/demo/src/modules/directives/dropdown-context/examples/3/index.html
- projects/demo/src/modules/directives/dropdown-context/examples/import/template.md
- projects/demo/src/modules/directives/dropdown-hover/examples/3/index.html
- projects/demo/src/modules/directives/dropdown-hover/examples/3/index.ts
- projects/demo/src/modules/directives/dropdown-open/examples/1/index.html
- projects/demo/src/modules/directives/dropdown-open/examples/2/index.html
- projects/demo/src/modules/directives/dropdown-open/examples/2/index.less
- projects/demo/src/modules/directives/dropdown-open/examples/2/index.ts
BREAKING CHANGE: `ActiveZone` is removed from context in favor of close method
Closes #
> fix(core)!: nested `Dropdown` no longer needs manual active zone

- projects/cdk/schematics/ng-update/v3/steps/migrate-templates.ts
- projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
- projects/core/components/error/error.component.ts
- projects/demo/src/modules/components/error/examples/1/index.ts
- projects/demo/src/modules/components/error/examples/import/import.md
- projects/demo/src/modules/components/error/index.ts
- projects/demo/src/modules/components/group/examples/1/index.ts
- projects/demo/src/modules/components/input-card-grouped/examples/1/index.ts
- projects/demo/src/modules/components/input-card-grouped/examples/3/index.ts
- projects/demo/src/modules/components/input-card/examples/1/index.ts
- projects/demo/src/modules/components/input-date/examples/1/index.ts
- projects/demo/src/modules/components/input-files/examples/2/index.ts
- projects/demo/src/modules/components/input-tag/examples/4/index.ts
- projects/demo/src/modules/components/island/examples/3/index.ts
- projects/demo/src/modules/components/textarea/examples/4/index.ts
- projects/demo/src/modules/components/utils/miscellaneous/examples/5/index.ts
- projects/demo/src/modules/markup/form/examples/1/index.ts
- projects/demo/src/modules/pipes/field-error/examples/1/index.ts
- projects/demo/src/modules/pipes/field-error/examples/2/index.ts
- projects/demo/src/modules/pipes/field-error/examples/3/index.ts
- projects/demo/src/modules/pipes/field-error/examples/4/index.ts
- projects/demo/src/modules/pipes/field-error/examples/5/index.ts
> refactor: rename `TuiErrorComponent` to `TuiError`

- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-money.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-money.spec.ts
- projects/core/directives/number-format/number-format.directive.ts
- projects/demo/src/modules/components/abstract/number-format-documentation/index.html
- projects/demo/src/modules/components/dialog/examples/4/index.ts
- projects/demo/src/modules/components/input-number/examples/3/index.ts
- projects/demo/src/modules/components/input-number/examples/5/index.ts
- projects/demo/src/modules/components/input-number/index.ts
- projects/demo/src/modules/components/input-range/index.ts
- projects/demo/src/modules/components/input-slider/index.ts
- projects/demo/src/modules/components/select/examples/9/account/index.ts
- projects/demo/src/modules/components/utils/math/examples/1/index.ts
- projects/demo/src/modules/directives/number-format/examples/1/index.ts
- projects/demo/src/modules/directives/number-format/examples/import/import.md
- projects/demo/src/modules/pipes/amount/examples/2/index.ts
- projects/legacy/components/input-number/test/input-number-format.spec.ts
- projects/legacy/components/input-number/test/input-number.component.spec.ts
- projects/legacy/components/input-range/input-range.module.ts
- projects/legacy/components/input-slider/input-slider.module.ts
> refactor: rename `TuiNumberFormatDirective` to `TuiNumberFormat`

- projects/addon-charts/components/arc-chart/arc-chart.component.ts
- projects/addon-charts/components/axes/axes.component.ts
- projects/addon-charts/components/bar-chart/bar-chart.component.ts
- projects/addon-charts/components/bar-set/bar-set.component.ts
- projects/addon-charts/components/bar/bar.component.ts
- projects/addon-charts/components/legend-item/legend-item.component.ts
- projects/addon-charts/components/line-chart/line-chart-hint.directive.ts
- projects/addon-charts/components/line-chart/line-chart.component.ts
- projects/addon-charts/components/line-chart/line-chart.options.ts
- projects/addon-charts/components/line-days-chart/line-days-chart-hint.directive.ts
- projects/addon-charts/components/line-days-chart/line-days-chart.component.ts
- projects/addon-charts/components/pie-chart/pie-chart.component.ts
- projects/addon-charts/components/pie-chart/pie-chart.directive.ts
- projects/addon-charts/components/ring-chart/ring-chart.component.ts
- projects/addon-charts/types/line-chart-hint-context.ts
- projects/addon-charts/utils/control-point.ts
- projects/addon-charts/utils/describe-sector.ts
- projects/addon-charts/utils/draw-curve.ts
- projects/addon-charts/utils/draw.ts
- projects/addon-charts/utils/line-angle.ts
- projects/addon-charts/utils/line-length.ts
> refactor(addon-charts): use deep entry points for imports of other Taiga packages

- projects/addon-doc/components/navigation/navigation.template.html
> fix(addon-doc): `Navigation` fix invalid two-way binding error in Angular v18

- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/kit/components/calendar-range/test/calendar-range.component.spec.ts
Closes #7781 
Problem: on item select, control value hold **only range**, not considering name/content
```
onItemSelect(item: TuiDayRangePeriod | string): void {
if (typeof item !== 'string') {
this.updateValue(item.range.dayLimit(this.min, this.max));
return;
}
if (this.activePeriod !== null) {
this.updateValue(null);
}
}
```
And when it attemps to get current active period, in finds only by range  
```
private get activePeriod(): TuiDayRangePeriod | null {
return (
this.items.find(item =>
tuiNullableSame<TuiDayRange>(
this.value,
item.range,
(a, b) =>
a.from.daySame(b.from.dayLimit(this.min, this.max)) &&
a.to.daySame(b.to.dayLimit(this.min, this.max)),
),
) || null
);
}
```
Solutions:
1. To hold current item index
2. To hold TuiDayRangePeriod separately
3. To hold TuiDayRangePeriod in …
> fix(kit): `CalendarRange` should not distinguish ranges with same dates and different names

- projects/cdk/schematics/ng-update/steps/index.ts
- projects/cdk/schematics/ng-update/steps/replace-package-name.ts
- projects/cdk/schematics/ng-update/v3-36/index.ts
- projects/cdk/schematics/ng-update/v4/index.ts
- projects/cdk/schematics/ng-update/v4/tests/migrate-destroy-service/utils.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-all-country-iso-codes.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-enums.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-hosted-dropdown.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-legacy-mask.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-package-names.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-progress-segmented.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-providers.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-restore-tui-mapper.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-restore-tui-matcher.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
1. Use `main` branch of https://github.com/taiga-family/maskito
2. Run 
```
nx migrate @taiga-ui/cdk@next
```
```
npm_config_legacy_peer_deps=false nx migrate --run-migrations
```
```
npm start
```
It throws
```
Error: projects/demo/src/pages/stackblitz/stackblitz.service.ts:7:37[[39m0m - error TS2307: Cannot find module '@tinkoff/ng-polymorpheus' or its corresponding type declarations.
import {PolymorpheusComponent} from '@tinkoff/ng-polymorpheus';
~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> chore(cdk): migrations for `@taiga-ui/polymorpheus` & `@taiga-ui/event-plugins`

- projects/demo-playwright/tests/core/error/error.spec.ts
> chore(demo-playwright): improve screenshot test for `Error`

- projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
- projects/demo-playwright/utils/page-objects/input-date-range.po.ts
- projects/demo/src/modules/components/input-date-range/examples/5/index.ts
- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/legacy/components/input-date-range/input-date-range.component.ts
- projects/legacy/components/input-date-range/test/input-date-range.component.spec.ts
> fix(legacy): `InputDateRange` should not distinguish ranges with same dates and different names

- projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
- projects/demo-playwright/utils/page-objects/input-date-range.po.ts
- projects/demo/src/modules/components/input-date-range/examples/5/index.ts
- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/kit/components/input-date-range/input-date-range.component.ts
- projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
> fix(kit): `InputDateRange` should not distinguish ranges with same dates and different names

- projects/cdk/schematics/ng-update/v4/migrate-icons/index.ts
- projects/cdk/schematics/ng-update/v4/migrate-icons/rename-proprietary-icons.ts
- projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
- projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-icons.spec.ts
> chore: add proprieraty-icons migration

- projects/addon-doc/components/page/page.component.ts
- projects/addon-doc/components/page/page.template.html
- projects/demo/src/modules/experimental/appearance/appearance.template.html
> feat(addon-docs): support custom tags

- projects/cdk/schematics/ng-update/v4/index.ts
- projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-replace.ts
- projects/cdk/schematics/ng-update/v4/steps/utils/replace-modules-with-providers.ts
- projects/cdk/schematics/ng-update/v4/tests/replace-modules-with-providers.spec.ts
Closes #5808
Not sure if `replaceModulesWithProviders` and it's interface with moving to `ng-update/steps` from `ng-update/v4/steps`
> chore(cdk): migrate TuiMobileCalendarDialogModule to provider

- scripts/publish-canary.ts
- scripts/publish.ts
- scripts/shared/bump-version.ts
- scripts/shared/get-all-tags.ts
- scripts/shared/get-last-major-version.ts
- scripts/shared/parse-version.ts
Closes https://github.com/taiga-family/taiga-ui/issues/8015
> ci: publish latest version as well

- projects/kit/components/badge/badge.style.less
> fix(kit): `Badge` fix img width in Safari

- projects/experimental/components/badge/badge.style.less
> fix(experimental) `Badge` fix img width in Safari

- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-avatar.ts
- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-money.ts
- projects/cdk/schematics/ng-update/v4/steps/templates/toggles/common.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-action.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badged-content.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-money.spec.ts
> chore: fix money migration, add avatar size migration

- projects/experimental/directives/cell/cell.styles.less
- projects/kit/components/progress/index.ts
- projects/kit/components/progress/progress-bar/progress-bar.component.less
- projects/kit/components/progress/progress-bar/progress-bar.component.ts
- projects/kit/components/progress/progress-circle/progress-circle.component.ts
- projects/kit/components/progress/progress.options.ts
> feat(kit): `Progress` add options with DI

- projects/kit/directives/button-group/button-group.style.less
> fix(kit): correct border-radius for `ButtonGroup` with only child

- projects/experimental/directives/button-group/button-group.style.less
> fix(experimental): correct border-radius for `ButtonGroup` with only child

- projects/legacy/components/textarea/textarea.style.less
> fix(legacy): `Textarea` displays emoji in Safari

- projects/kit/components/textarea/textarea.style.less
> fix(kit): `Textarea` displays emoji in Safari

- projects/kit/components/checkbox-block/checkbox-block.style.less
> fix(kit): correct paddings for `RadioBlock`, `CheckboxBlock`

- projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
- projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
- projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts
- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badge.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-identifiers.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-package-names.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
- projects/cdk/schematics/utils/get-named-import-references.ts
> chore: some migration fixes

- projects/cdk/schematics/ng-update/steps/replace-package-name.ts
- projects/cdk/schematics/ng-update/v4/steps/migrate-styles.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-package-names.spec.ts
Use any project **WITHOUT** `legacy-peer-deps`.
For example: https://github.com/taiga-family/maskito
This project does not install `@taiga-ui/polymorpheus` directly (this dependency is installed automatically because it is peer dependency of `@taiga-ui/cdk`  package).
This project after schematic migrations:
> chore(schematics): migrate `@tinkoff/{ng-polymorpheus|ng-event-plugins}` even if they are not installed directly

- projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
- projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.style.less
- projects/core/components/root/root.style.less
- projects/core/directives/dropdown/dropdown-open-legacy.directive.ts
- projects/core/directives/dropdown/dropdown-open.directive.ts
- projects/core/directives/dropdown/dropdown.ts
- projects/core/directives/dropdown/index.ts
- projects/demo/src/modules/directives/dropdown/examples/6/index.html
- projects/demo/src/modules/directives/dropdown/examples/6/index.ts
- projects/legacy/components/combo-box/combo-box.component.ts
- projects/legacy/components/input-phone/input-phone.component.ts
- projects/legacy/components/input-tag/input-tag.component.ts
- projects/legacy/components/input/input.component.ts
- projects/legacy/components/multi-select/multi-select.component.ts
- projects/legacy/components/select/select.component.ts
- projects/legacy/directives/legacy-dropdown-open-monitor/legacy-dropdown-open-monitor.ts
> fix(addon-mobile): `DropdownMobile` fix some issues

- projects/addon-doc/package.json
- projects/demo/src/modules/info/changelog/index.less
Use the following import inside any external project (e.g. Maskito):
```less
@import '@taiga-ui/addon-doc/styles/index';
```
Try to build project – it'll throw:
```shell
./projects/demo/src/pages/documentation/changelog/changelog.style.less?ngResource - Error: Module build failed (from ./node_modules/less-loader/dist/cjs.js):
@import '@taiga-ui/addon-doc/styles/index';
^
Less resolver error:
'@taiga-ui/addon-doc/styles/index' wasn't found. Tried -
/maskito/projects/demo/src/pages/documentation/changelog/@taiga-ui/addon-doc/styles/index.less,
npm://@taiga-ui/addon-doc/styles/index,
npm://@taiga-ui/addon-doc/styles/index.less,
@taiga-ui/addon-doc/styles/index.less
Webpack resolver error details:
undefined
Webpack resolver error missing:
undefined
Error in …
```
> chore(addon-doc): add `./styles/*` to `exports` config of `package.json`

- projects/demo/src/modules/app/stackblitz/project-files/src/main.ts.md
https://taiga-ui.dev/next/components/accordion#base
> chore(demo): fix icons in StackBlitz

- projects/demo/src/modules/directives/textfield-controller/examples/import/import.md
To import `TuiTextfieldControllerModule` from `@taiga-ui/legacy` instead of `@taiga-ui/core`
> chore: import `TuiTextfieldControllerModule` from `@taiga-ui/legacy`

- projects/cdk/utils/focus/set-native-mouse-focused.ts
- projects/cdk/utils/focus/tests/set-native-mouse-focused.spec.ts
Closes https://github.com/taiga-family/taiga-ui/issues/7377
> fix(cdk): provided double value is non-finite

- projects/demo/src/modules/app/stackblitz/project-files/src/main.ts.md
See `main.ts` tab in this step:
* https://taiga-ui.dev/next/getting-started#root
> chore(demo): enable `NG_EVENT_PLUGINS` in StackBlitz starter

- projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
- projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts
> chore(schematics): migrations for `TuiButtonGroupModule` & `TuiButtonVerticalModule` & `TuiIconsModule`

- projects/cdk/schematics/ng-update/interfaces/replacement-type.ts
- projects/cdk/schematics/ng-update/steps/rename-types.ts
- projects/cdk/schematics/ng-update/v4/steps/constants/types.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-money.spec.ts
Relates to:
* https://github.com/taiga-family/taiga-ui/pull/7904
1. Run migration schematics in Maskito repo
2. Run `nx build`
The following lines 
```ts
protected readonly textareaExample1: Record<string, Promise<unknown> | string> = {
[DocExamplePrimaryTab.MaskitoOptions]: import('./examples/1-latin/mask.ts?raw'),
};
```
throws
```
Error: projects/demo/src/pages/recipes/textarea/textarea-doc.template.html:33:10 - 
error TS2322: 
Type 'Record<string, string | Promise<unknown>>' is not assignable to type 'Record<string, TuiRawLoaderContent>'.
33         [content]="textareaExample1"
~~~~~~~
```
> chore(schematics): fix migration for `TuiDocExample`

- projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.component.ts
- projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.template.html
- projects/experimental/components/thumbnail-card/index.ts
- projects/experimental/components/thumbnail-card/thumbnail-card.component.ts
- projects/experimental/components/thumbnail-card/thumbnail-card.options.ts
- projects/experimental/components/thumbnail-card/thumbnail-card.template.html
> feat(experimental): `ThumbnailCard` add DI options

- projects/core/components/dialog/dialog.component.ts
- projects/core/components/dialog/dialog.template.html
- projects/demo/src/modules/components/dialog/examples/8/index.ts
https://taiga-ui.dev/components/dialog#prompt
https://github.com/taiga-family/taiga-ui/blob/8f071226dcb9e4893b2d2a4bcf23fd6490e01456/projects/core/components/dialog/dialog.interfaces.ts#L22
Closes #8204
> fix(core): `Dialog` should hide close icon if `closeable` equals to `Observable<false>`

- projects/cdk/schematics/ng-update/steps/replace-identifier.ts
`replace Identifiers` can be a too long step, we need to add progress indicator
> chore: add progress log for identifiers migration

- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
```html
<tui-checkbox-labeled [(ngModel)]="value">Content</tui-checkbox-labeled>
```
⬇️ 
```html
<label tuiLabel>
<input tuiCheckbox type="checkbox" [(ngModel)]="value">Conten
</label>t
```
> chore(schematics): fix migration for one line usage of `<tui-checkbox-labeled />` / `<tui-radio-labeled />`

- projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
> chore(schematics): migration for `<tui-radio-block [item]="1" />` => `<input tuiRadio type=radio [value]="1" />`

- projects/cdk/schematics/ng-update/v4/steps/constants/types.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
Relates:
- https://github.com/taiga-family/taiga-ui/issues/8162
> chore(schematics): migrations for proprietary `TuiOperationIcon` & `TuiIllustrationName` types

- projects/legacy/components/input-date/input-date.component.ts
- projects/legacy/components/input-date/input-date.template.html
Problem reproduction:
https://stackblitz.com/edit/angular-gfcprx?file=src%2Fapp%2Fapp.component.ts
> chore(legacy): `Date` should support native date picker even without providing of `TUI_MOBILE_CALENDAR`

- projects/kit/components/input-date/input-date.component.ts
- projects/kit/components/input-date/input-date.template.html
Problem reproduction:
https://stackblitz.com/edit/angular-gfcprx?file=src%2Fapp%2Fapp.component.ts
> fix(kit): `Date` should support native date picker even without importing of `TuiMobileCalendarDialogModule`

- projects/i18n/types/language.ts
> refactor: use tuple names

- projects/kit/components/input-password/input-password.component.ts
Closes https://github.com/taiga-family/taiga-ui/issues/7281
> fix(kit): reuse cursor position after showing password

- projects/core/components/dialog/dialogs.style.less
Closes https://github.com/taiga-family/taiga-ui/issues/8166
> fix(core): it's not possible to scroll container elements on safari

- projects/legacy/components/input-tag/input-tag.style.less
- projects/legacy/components/input-tag/input-tag.template.html
https://github.com/taiga-family/taiga-ui/issues/8233
> fix(legacy): placeholder in multiselect disappears while hovering options

- projects/addon-doc/components/code/index.less
> refactor: small improves

- projects/core/styles/mixins/mixins.less
Closes https://github.com/taiga-family/taiga-ui/issues/8339
> fix(core): ios menu is not triggered

- projects/addon-preview/package.json
- projects/addon-tablebars/package.json
Use project **WITHOUT** `--legacy-peer-deps` config.
```
nx migrate @taiga-ui/cdk@next
npm i
```
it throws
```
~/WebstormProjects/twfm-ui-2 git:[test-taiga-migrations]
npm i
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: twfm@0.0.0
npm error Found: @taiga-ui/cdk@4.0.0-rc.8
npm error node_modules/@taiga-ui/cdk
npm error   @taiga-ui/cdk@"4.0.0-rc.8" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @taiga-ui/cdk@"^3.83.0" from @taiga-ui/addon-tablebars@3.83.0
npm error node_modules/@taiga-ui/addon-tablebars
npm error   @taiga-ui/addon-tablebars@"3.83.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or …
```
> chore: use less strict dep constraints for deprecated `@taiga-ui/{addon-preview,addon-tablebars}`

- CHANGELOG.md
- projects/core/components/dialog/dialog.component.ts
- projects/core/components/dialog/dialog.template.html
- projects/demo/src/modules/components/dialog/examples/8/index.ts
Revert:
* https://github.com/taiga-family/taiga-ui/pull/8206
> Revert "fix(core): `Dialog` should hide close icon if `closeable` equals to `Observable<false>` (#8206)"

- projects/demo/src/modules/components/cell/examples/8/index.html
- projects/demo/src/modules/components/cell/examples/8/index.less
- projects/demo/src/modules/components/cell/examples/8/index.ts
- projects/demo/src/modules/components/cell/index.ts
- projects/demo/src/modules/components/stepper/examples/4/index.html
- projects/demo/src/modules/components/stepper/examples/4/index.ts
- projects/demo/src/modules/components/stepper/index.ts
- projects/kit/directives/connected/connected.directive.ts
- projects/kit/directives/connected/connected.style.less
- projects/kit/directives/connected/index.ts
- projects/kit/directives/connected/ng-package.json
- projects/kit/directives/index.ts
- projects/layout/components/cell/cell.directive.ts
> feat(kit): add `tuiConnected` directive for `Stepper` and `Cell`

- projects/kit/components/stepper/step.style.less
Closes #
**As Is:** 
**To Be:**
> chore(kit): `Stepper` left text align

- projects/kit/components/stepper/step/step.style.less
Closes #
**As Is:**
**To Be:**
> chore(kit): `Stepper` text and icon align

- projects/cdk/date-time/time.ts
Closes https://github.com/taiga-family/taiga-ui/issues/8372
> fix(cdk): redundant assert log if hours are greater than 23

- projects/core/components/textfield/textfield.template.html
При обнулении значения в textfield, происходит submit формы. Добавил type="button", чтобы этого не происходило
> fix(core): add `type=button` to `textfield` for ignore submit event

- projects/cdk/date-time/time.ts
- projects/demo-playwright/tests/kit/input-time/input-time.spec.ts
- projects/legacy/components/input-time/input-time.component.ts
> fix(legacy): `InputTime` has missing zero padding on blur for `HH:MM` mode

- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/kit/components/calendar-range/calendar-range.template.html
- projects/kit/internal/primitive-calendar-range/test/primitive-calendar-range.component.spec.ts
Closes #8331 
When set input [defaultViewedMonth]:
**As Is:** 
**To Be:**
> fix(kit): `CalendarRange` defaultViewedMonth shows correct calendars months

- projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
- projects/kit/components/calendar-range/calendar-range.component.ts
Closes https://github.com/taiga-family/taiga-ui/issues/3708
> feat(kit): prevent disabled date selection for calendar-range

- projects/i18n/types/language-names.ts
More information: https://github.com/microsoft/TypeScript/issues/29729
> feat(i18n): improve literal string union

- projects/kit/components/input-number/input-number.component.ts
Closes [#8528](https://github.com/taiga-family/taiga-ui/issues/8528). Same as [this PR](https://github.com/taiga-family/taiga-ui/pull/8568)
> fix(kit): prevent add/remove suffixes while InputNumber is readonly

- projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
- projects/addon-mobile/components/mobile-calendar/mobile-calendar.style.less
- projects/addon-mobile/components/mobile-calendar/mobile-calendar.template.html
- projects/demo-cypress/src/tests/mobile-calendar.cy.ts
- projects/demo/src/modules/components/mobile-calendar/examples/6/index.html
- projects/demo/src/modules/components/mobile-calendar/examples/6/index.less
- projects/demo/src/modules/components/mobile-calendar/examples/6/index.ts
- projects/demo/src/modules/components/mobile-calendar/index.html
- projects/demo/src/modules/components/mobile-calendar/index.ts
> feat(addon-mobile): possibility drop mobile calendar header

- projects/addon-doc/components/code/index.less
> fix(addon-doc): strange behavior on safari

- projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.service.ts
> fix(addon-mobile): `PullToRefresh` do not trigger pulled if dialog is inside

- projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.service.ts
> fix(addon-mobile): PullToRefresh do not trigger pulled if dialog is inside

- projects/demo/src/modules/directives/dropdown-hover/examples/4/index.html
**Before:**
https://github.com/user-attachments/assets/48bc4c34-124c-43b6-97c1-e5e945dd4973
**After:**
https://github.com/user-attachments/assets/5c55dcee-6d2c-497a-bda4-c29be7d79018
> chore(demo): add missing `tuiDropdownHost` reference to example

- projects/kit/components/calendar-range/calendar-range.component.ts
> fix(kit): fix `CalendarRange` typing and checks `otherDateText` in `mapper` function

- projects/cdk/tokens/active-element.ts
> fix(cdk): `ActiveZone` do not exit zone when scrollable container becomes non-scrollable

- projects/cdk/tokens/active-element.ts
> fix(cdk): `ActiveZone` do not exit zone when scrollable container becomes non-scrollable (#8631)

- projects/legacy/components/textarea/textarea.style.less
> fix(legacy): `Textarea` use balance text-wrap in safari

- projects/addon-doc/components/copy/index.html
- projects/addon-doc/components/copy/index.less
- projects/addon-doc/components/copy/index.ts
- projects/demo/src/modules/markup/colors/examples/table/index.html
- projects/demo/src/modules/markup/colors/examples/table/index.less
- projects/demo/src/modules/markup/colors/examples/table/index.ts
- projects/demo/src/modules/markup/colors/index.ts
> chore(demo): improve color table for mobile

- projects/kit/components/calendar-range/calendar-range.component.ts
> fix(kit): `CalendarRange` delete code for `availableRange` property

- projects/kit/components/textarea/textarea.style.less
(cherry picked from commit cbaac1b1c87b884cb692f979b44094ebb583ef1a)
Close #8608
> fix(kit): `Textarea` use balance text-wrap in safari (#8666)

- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/legacy/components/input-date-range/input-date-range.component.ts
- projects/legacy/components/input-date-range/input-date-range.template.html
Relates:
* https://github.com/taiga-family/taiga-ui/pull/7959
Closes #8652
> fix(legacy): `InputDateRange` triggers cyclic change detection ticks

- projects/kit/components/avatar/avatar.style.less
> fix(kit): contain width for img in avatar

- projects/addon-charts/components/pie-chart/pie-chart.directive.ts
- projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts
- projects/cdk/directives/obscured/obscured.service.ts
- projects/cdk/observables/zone.ts
- projects/core/components/scrollbar/scroll-controls.component.ts
- projects/core/components/scrollbar/scrollbar.directive.ts
- projects/core/components/scrollbar/scrollbar.service.ts
- projects/core/directives/dropdown/dropdown-hover.directive.ts
- projects/core/directives/dropdown/dropdown.directive.ts
- projects/core/directives/hint/hint-describe.directive.ts
- projects/core/services/breakpoint.service.ts
- projects/kit/components/items-with-more/items-with-more.service.ts
- projects/kit/components/progress/progress-bar/progress-color-segments.directive.ts
- projects/kit/components/segmented/segmented.component.ts
- projects/kit/components/tabs/tabs-horizontal.directive.ts
- projects/kit/directives/fade/fade.directive.ts
- projects/kit/directives/fluid-typography/fluid-typography.directive.ts
- projects/kit/directives/sensitive/sensitive.directive.ts
- projects/layout/components/app-bar/app-bar.component.ts
- projects/layout/components/search/search-filters.component.ts
https://github.com/user-attachments/assets/b7fc0841-c23e-4746-9399-0d501bfd2f36
https://github.com/user-attachments/assets/a9fd6b0c-b96c-4559-ac27-85dd36e73d80
Close #8725
> fix(core): `Dropdown` triggers change detection too frequently

- projects/kit/components/items-with-more/items-with-more.service.ts
Relates:
* https://github.com/taiga-family/taiga-ui/pull/8738
> refactor(kit): `ItemsWithMore` change detection optimization

- projects/core/components/button/test/button.directive.spec.ts
- projects/testing/core/button.harness.ts
Partially implements https://github.com/taiga-family/taiga-ui/issues/476
> feat(testing): adds size harness for button

- projects/core/components/textfield/select.directive.ts
- projects/core/components/textfield/textfield.component.ts
- projects/core/components/textfield/textfield.directive.ts
> fix(core): `Textfield` fix expression change error

- projects/core/components/data-list/data-list.component.ts
- projects/core/components/data-list/data-list.template.html
https://github.com/user-attachments/assets/28f1a9a1-be92-43dd-b646-427758831d47
https://github.com/user-attachments/assets/81772ae1-cc00-4fe1-b0b7-de5c823fb280
> fix(core): show empty content in correct detect changes cycle

- projects/addon-table/components/table/directives/table.directive.ts
- projects/addon-table/components/table/directives/table.style.less
TuiTableDirective caused error when adding Content Security Policy with NONCE value.
Error itself:
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src....". Either the 'unsafe-inline' keyword, a hash ('sha256-uprzIeY8iAGlQbI25hI6vVEMS+1jDt6N6C2veKnb2dA='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
> fix(addon-table): TuiTableDirective Content Security Policy error v4

- projects/addon-table/components/table/directives/table.directive.ts
- projects/addon-table/components/table/directives/table.style.less
TuiTableDirective caused error when adding Content Security Policy with NONCE value.
Error itself:
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src....". Either the 'unsafe-inline' keyword, a hash ('sha256-uprzIeY8iAGlQbI25hI6vVEMS+1jDt6N6C2veKnb2dA='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
> fix(addon-table): TuiTableDirective Content Security Policy error

- projects/kit/components/input-inline/input-inline.style.less
> fix(kit): fix styles for input-inline when spellcheck marks word incorrect

- projects/demo/src/modules/components/card-large/index.html
- projects/demo/src/modules/components/card-medium/index.html
> chore(demo): fix source code links for cards

- projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts
Partially solved #8839 
`Missing migration for tuiHintAppearance="onDark". Should be replaced with tuiHintAppearance="dark"`
> chore: add migration for `tuiHintAppearance`

- projects/layout/components/card/card.styles.less
Fixes `tuiLabel` title font weight in the following case:
```html
<div
tuiCardLarge
tuiSurface="elevated"
>
<label tuiLabel>
<span tuiTitle>
<span tuiSubtitle>Foo</span>
Bar
</span>
</label>
</div>
```
> fix(layout): `Card` fix `tuiLabel` title font weight when `tuiLabel` is placed inside a card

- projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts
- projects/cdk/schematics/ng-update/v4/steps/templates/index.ts
- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-active-zone.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-active-zone.spec.ts
> chore: add migration for active zone parent

- projects/addon-mobile/styles/common/card-large.less
Close #8939
The mobile paddings now look good in the demo. Not sure if they are applied correctly IRL on mobile device.
> fix(addon-mobile): `Card` fix paddings on mobile devices

- projects/demo/src/modules/pipes/filter-by-input/examples/2/index.ts
- projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts
> fix(kit): add overload for `TuiFilterByInputPipe`

- projects/addon-doc/components/api/api-item.component.ts
- projects/addon-doc/components/api/api-item.style.less
- projects/addon-doc/components/api/api-item.template.html
- projects/addon-doc/components/api/api.component.ts
- projects/addon-doc/components/api/api.style.less
- projects/addon-doc/components/api/api.template.html
- projects/addon-doc/components/index.ts
- projects/addon-doc/index.ts
- projects/addon-doc/tokens/i18n.ts
- projects/cdk/constants/used-icons.ts
- projects/core/components/textfield/textfield.component.ts
- projects/core/components/textfield/textfield.directive.ts
- projects/core/components/textfield/textfield.template.html
- projects/core/styles/components/textfield.less
- projects/demo/src/components/appearance/index.html
- projects/demo/src/components/appearance/index.ts
- projects/demo/src/components/icons/index.html
- projects/demo/src/components/icons/index.ts
- projects/demo/src/modules/components/block/index.html
- projects/demo/src/modules/components/block/index.ts
- projects/demo/used-icons.ts
- tsconfig.json
> feat(addon-doc): `API` add new component

- projects/demo/src/modules/components/cell/examples/8/index.html
- projects/demo/src/modules/components/cell/examples/8/index.ts
- projects/kit/directives/connected/connected.style.less
- projects/layout/components/cell/cell.styles.less
> fix(kit): `Connected` work with `CardLarge`

- projects/addon-commerce/components/input-card-group/input-card-group.component.ts
- projects/addon-commerce/components/input-card-group/input-card-group.style.less
- projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts
- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-button-appearance.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button-appearance.spec.ts
- projects/core/components/textfield/select.directive.ts
- projects/core/components/textfield/textfield.component.ts
- projects/core/components/textfield/textfield.directive.ts
- projects/core/directives/appearance/appearance.bindings.ts
- projects/core/directives/appearance/appearance.directive.ts
- projects/core/directives/appearance/with-appearance.ts
- projects/core/styles/components/appearance.less
- projects/core/styles/components/group.less
- projects/core/styles/components/textfield.less
- projects/core/styles/theme/appearance/outline.less
- projects/core/styles/theme/appearance/primary.less
- projects/core/styles/theme/appearance/secondary.less
- projects/core/styles/theme/appearance/status.less
- projects/core/styles/theme/appearance/textfield.less
- projects/demo/src/components/appearance/index.html
- projects/demo/src/components/appearance/index.ts
- projects/demo/src/modules/components/block/index.html
- projects/demo/src/modules/components/button/examples/2/index.html
- projects/demo/src/modules/components/filter/examples/4/index.html
- projects/demo/src/modules/directives/dropdown-open/examples/4/index.html
- projects/kit/components/input-phone-international/input-phone-international.template.html
> feat(core): `Appearance` allow multiple modes

- projects/kit/components/line-clamp/line-clamp.style.less
When user set `white-space: nowrap` it doesn't work
> fix(kit): do not override white-space for children of line-clamp

- package.json
- projects/demo/src/modules/components/compass/examples/2/index.ts
> refactor: enable `arguments-order`

- projects/core/directives/appearance/appearance.directive.ts
- projects/core/styles/components/appearance.less
- projects/demo/src/modules/components/navigation/examples/1/index.html
- projects/layout/components/navigation/aside-item.directive.ts
> fix(core): `Appearance` remove initial transition

- projects/legacy/styles/mixins/textfield.less
Close #7443
when trying to focus with a tab (or programmatically) on a readonly input with the `-webkit-user-select: none` property, desktop safari unexpectedly resets the scroll
https://stackblitz.com/edit/vitejs-vite-drvcag?file=index.html,style.css,main.js&terminal=dev
> fix(legacy): fix scroll jumping on readonly input focusing in safari

- projects/demo-cypress/src/tests/lazy-loading.cy.ts
- projects/demo/src/modules/app/landing/index.html
- projects/demo/src/modules/app/landing/index.ts
- projects/demo/src/modules/directives/lazy-loading/examples/1/index.html
- projects/demo/src/modules/directives/lazy-loading/examples/import/template.md
- projects/demo/src/modules/directives/lazy-loading/index.html
- projects/kit/components/avatar/avatar.component.ts
- projects/kit/components/avatar/avatar.template.html
- projects/kit/directives/lazy-loading/lazy-loading.directive.ts
> feat(kit): improve IDEA auto import for `TuiImageLoading`

- projects/cdk/directives/auto-focus/autofocus.options.ts
- projects/cdk/directives/auto-focus/handlers/abstract.handler.ts
- projects/cdk/directives/auto-focus/handlers/default.handler.ts
- projects/cdk/directives/auto-focus/handlers/ios.handler.ts
- projects/cdk/directives/auto-focus/test/auto-focus.directive.spec.ts
- projects/cdk/utils/di/create-options.ts
- projects/cdk/utils/miscellaneous/create-token.ts
> feat(cdk): support provide custom query selector for auto focus directive

- projects/addon-doc/README.md
- projects/addon-doc/components/navigation/navigation.component.ts
- projects/addon-doc/components/navigation/navigation.style.less
- projects/addon-doc/components/navigation/navigation.template.html
- projects/addon-doc/tokens/i18n.ts
- projects/demo/src/modules/app/app.config.ts
> feat(addon-doc): add ability to disable default search-bar

- projects/cdk/constants/used-icons.ts
- projects/demo-playwright/tests/kit/like/like.spec.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/demo-routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/components/like/examples/1/index.html
- projects/demo/src/modules/components/like/examples/1/index.ts
- projects/demo/src/modules/components/like/examples/2/index.html
- projects/demo/src/modules/components/like/examples/2/index.ts
- projects/demo/src/modules/components/like/examples/3/index.html
- projects/demo/src/modules/components/like/examples/3/index.ts
- projects/demo/src/modules/components/like/examples/4/index.html
- projects/demo/src/modules/components/like/examples/4/index.ts
- projects/demo/src/modules/components/like/examples/5/index.html
- projects/demo/src/modules/components/like/examples/5/index.ts
- projects/demo/src/modules/components/like/examples/import/import.md
- projects/demo/src/modules/components/like/examples/import/template.md
- projects/demo/src/modules/components/like/index.html
- projects/demo/src/modules/components/like/index.ts
- projects/demo/used-icons.ts
- projects/kit/components/index.ts
- projects/kit/components/like/index.ts
- projects/kit/components/like/like.component.ts
- projects/kit/components/like/like.options.ts
- projects/kit/components/like/ng-package.json
- projects/kit/styles/components/like.less
> feat(kit): `Like` add new component

- projects/demo/src/modules/components/card-large/examples/13/index.html
- projects/demo/src/modules/components/card-large/examples/13/index.ts
- projects/demo/src/modules/components/card-large/examples/8/index.html
- projects/demo/src/modules/components/card-large/examples/8/index.ts
- projects/demo/src/modules/components/card-large/examples/9/index.html
- projects/demo/src/modules/components/card-large/examples/9/index.less
- projects/demo/src/modules/components/card-large/examples/9/index.ts
- projects/demo/src/modules/components/card-large/index.ts
- projects/layout/components/card/card.styles.less
Close #9077 
Just add
```
&:last-of-type {
margin-bottom: -0.5rem;
}
```
Add new example with `Cell` headless
And changed demo examples order:
New example 13th -> 8th, 
8th -> 9th, 9th -> 13th
> fix(layout): `CardLarge` with headless `Cell` list

- projects/demo-playwright/tests/kit/multi-select/multi-select.spec.ts
- projects/kit/components/input-tag/input-tag.component.ts
- projects/kit/components/input-tag/input-tag.style.less
- projects/kit/components/input-tag/input-tag.template.html
> fix(kit): `MultiSelect` empty line when non empty `placeholder` and `valueContent`

- projects/demo-playwright/tests/kit/multi-select/multi-select.spec.ts
- projects/legacy/components/input-tag/input-tag.component.ts
- projects/legacy/components/input-tag/input-tag.style.less
- projects/legacy/components/input-tag/input-tag.template.html
> fix(legacy): `MultiSelect` empty line when non empty `placeholder` and `valueContent`

- projects/demo/src/modules/app/app.component.ts
1. main portal creating twice when navigating to somewhere except landing-page route
2. main-portal unexpected creating on landing-page route
> chore(demo): fix re-creating main portal twice

- projects/demo/src/modules/experimental/card-large/card-large.component.ts
- projects/demo/src/modules/experimental/card-large/card-large.module.ts
- projects/demo/src/modules/experimental/card-large/card-large.template.html
- projects/demo/src/modules/experimental/card-large/examples/13/index.html
- projects/demo/src/modules/experimental/card-large/examples/13/index.ts
- projects/demo/src/modules/experimental/card-large/examples/8/index.html
- projects/demo/src/modules/experimental/card-large/examples/8/index.less
- projects/demo/src/modules/experimental/card-large/examples/9/index.html
- projects/demo/src/modules/experimental/card-large/examples/9/index.less
- projects/experimental/directives/card/card.styles.less
> fix(experimental): `CardLarge` with headless `Cell` list

- projects/core/styles/components/textfield.less
- projects/core/styles/theme/appearance/textfield.less
- projects/kit/components/input-phone-international/input-phone-international.style.less
- projects/kit/components/input-phone-international/input-phone-international.template.html
- projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
> chore(core): `Textfield` remove border

- projects/addon-doc/components/main/main.template.html
> feat(addon-doc): add aria-label for dark mode button

- projects/addon-doc/components/example/example.template.html
> feat(addon-doc): heading elements are not in a sequentially-descending order

- package-lock.json
- package.json
- projects/addon-charts/package.json
- projects/addon-commerce/package.json
- projects/addon-doc/package.json
- projects/addon-mobile/package.json
- projects/addon-preview/package.json
- projects/addon-table/package.json
- projects/addon-tablebars/package.json
- projects/cdk/package.json
- projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts
- projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts
- projects/cdk/schematics/ng-update/utils/get-file-system.ts
- projects/cdk/schematics/ng-update/v3/steps/migrate-polymorpheus.ts
- projects/cdk/schematics/ng-update/v3/steps/migrate-textfield-controller.ts
- projects/cdk/schematics/utils/templates/ng-component-input-manipulations.ts
- projects/cdk/schematics/utils/templates/template-resource.ts
- projects/core/package.json
- projects/demo/package.json
- projects/experimental/package.json
- projects/i18n/package.json
- projects/kit/package.json
- projects/layout/package.json
> feat: upgrade peer dependencies

- projects/demo/src/modules/app/search/index.less
> chore(demo): hide default scrollbar

- projects/demo/src/components/appearance/index.html
- projects/demo/src/components/appearance/index.ts
- projects/demo/src/components/dropdown/index.html
- projects/demo/src/components/dropdown/index.ts
- projects/demo/src/modules/directives/dropdown/index.html
- projects/demo/src/modules/directives/dropdown/index.ts
> chore(demo): `Dropdown` add reuse component & migrate example to new approach

- projects/cdk/pipes/index.ts
- projects/cdk/pipes/repeat-times/index.ts
- projects/cdk/pipes/repeat-times/ng-package.json
- projects/cdk/pipes/repeat-times/test/repeat-times.pipe.spec.ts
- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/demo-routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/pipes/repeat-times/examples/1/index.html
- projects/demo/src/modules/pipes/repeat-times/examples/1/index.ts
- projects/demo/src/modules/pipes/repeat-times/examples/import/import.md
- projects/demo/src/modules/pipes/repeat-times/examples/import/template.md
- projects/demo/src/modules/pipes/repeat-times/index.html
- projects/demo/src/modules/pipes/repeat-times/index.ts
@waterplea I want to use `@for` in Angular 18 and I don't want use `*tuiRepeatTimes`
I can happy with it
+ strict types
> feat(cdk): add `TuiRepeatTimes` pipe

- projects/kit/components/checkbox/checkbox.component.ts
- projects/kit/components/radio/radio.component.ts
- projects/kit/components/switch/switch.component.ts
> fix(kit): remove appearance input for radio, switch and checkbox

- projects/core/components/textfield/textfield.component.ts
- projects/core/components/textfield/textfield.directive.ts
- projects/core/components/textfield/textfield.template.html
> fix(core): `Textfield` has change detection problems for `[filler]`

- projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less
> chore(addon-commerce): `InputCardGroup` rollback unnecessary fix for older Safari

- projects/cdk/utils/miscellaneous/is-valid-url.ts
- projects/cdk/utils/miscellaneous/test/is-valid-url.spec.ts
> fix(cdk): support any query string inside URL

- projects/cdk/schematics/ng-update/v4/migrate-css-vars/palette.ts
- projects/cdk/schematics/ng-update/v4/migrate-css-vars/rename-css-vars.ts
- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-label.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-css-vars.spec.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-label.spec.ts
part of https://github.com/taiga-family/taiga-ui/issues/8839
> chore: fix label migration and css shadow migration

- projects/addon-mobile/styles/common/header.less
- projects/addon-mobile/styles/taiga-ui-mobile.less
- projects/layout/components/header/header.styles.less
> fix(layout): `Header` fix subtitile padding on mobile

- projects/core/directives/dropdown/dropdown-context.directive.ts
> fix(core): fix open DropdownContext after single touch on iOS

- projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.style.less
- projects/cdk/classes/control.ts
- projects/core/styles/mixins/mixins.less
- projects/core/styles/mixins/mixins.scss
- projects/demo/src/modules/components/breadcrumbs/examples/3/index.html
- projects/demo/src/modules/components/breadcrumbs/examples/3/index.less
- projects/demo/src/modules/components/breadcrumbs/examples/3/index.ts
- projects/demo/src/modules/components/breadcrumbs/index.ts
- projects/kit/components/breadcrumbs/breadcrumbs.component.ts
- projects/kit/components/breadcrumbs/breadcrumbs.style.less
- projects/kit/components/breadcrumbs/breadcrumbs.template.html
- projects/legacy/classes/control.ts
> fix(cdk): `Control` react to `markAsTouched` on Angular 18+

- projects/demo/src/modules/app/search/index.less
> chore(demo): small changes in header

- projects/addon-doc/components/demo/index.html
- projects/addon-doc/components/demo/index.ts
https://github.com/user-attachments/assets/a1194883-4bbb-4d1d-a3eb-abd5d1b06c32
https://github.com/user-attachments/assets/8c6a0eb8-3336-47ed-abbb-4bd2b9758587
> fix(addon-doc): glitch width content between value from DOM and sandbox width from url

- projects/core/components/textfield/select.directive.ts
- projects/core/components/textfield/textfield.directive.ts
- projects/demo-cypress/src/tests/textfield.cy.ts
**textfield.cy.ts-[filler]-initial-value_23:.png**
**textfield.cy.ts-[filler]-initial-value_23:.png**
> fix(core): `Textfield` with initial value has change detection problems with `filler`

- projects/demo-cypress/src/tests/textfield.cy.ts
> chore(demo-cypress): delete forbidden character `:` from snapshot names

- projects/core/components/root/root.component.ts
- projects/core/components/root/root.style.less
- projects/core/components/scrollbar/scroll-controls.component.ts
- projects/core/components/scrollbar/scroll-controls.template.html
- projects/core/components/scrollbar/scrollbar.component.ts
- projects/core/components/scrollbar/scrollbar.options.ts
- projects/core/components/scrollbar/scrollbar.template.html
- projects/demo/src/modules/components/scrollbar/examples/8/index.html
- projects/demo/src/modules/components/scrollbar/examples/8/index.less
- projects/demo/src/modules/components/scrollbar/examples/8/index.ts
- projects/demo/src/modules/components/scrollbar/index.ts
> feat(core): support using native scrollbar

- projects/addon-table/components/table/th-group/th-group.component.ts
- projects/addon-table/components/table/tr/tr.component.ts
- projects/core/components/expand/expand.component.ts
> fix(addon-table): hydration error while configuring table

- projects/core/tokens/icon-resolver.ts
I want pass empty icons for screenshot testing
```ts
tuiIconsProvider({
'@tui.heart': ''
})
```
> fix(core): support provide empty icon value

- projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts
- projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
- projects/demo-playwright/utils/page-objects/calendar-sheet.po.ts
- projects/demo-playwright/utils/page-objects/index.ts
- projects/demo-playwright/utils/page-objects/input-date-range.po.ts
- projects/demo-playwright/utils/page-objects/mobile-calendar.po.ts
Relates:
* https://github.com/taiga-family/taiga-ui/pull/8265/files#diff-0cce1811277c4e753fd5df47a281d07366b8fa48a46c1dbf8bd54de38d457a34L221-R248
Fixes #9351
> fix(addon-mobile): `InputDateRange` throws error on single date selection

- projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
- projects/demo-playwright/tests/core/surface/surface.spec.ts
- projects/demo/src/modules/components/surface/index.html
> chore: add test

- projects/addon-doc/components/api/api-item.component.ts
- projects/demo/src/modules/components/input-card/index.html
- projects/demo/src/modules/components/input-card/index.ts
> chore(demo): `InputCard` add `API` page

- projects/kit/components/input-phone-international/input-phone-international.component.ts
> fix(kit): `InputPhoneInternational` signal `countries`

- projects/core/components/expand/expand.component.ts
- projects/kit/components/accordion/accordion-item.template.html
> fix(kit): `Accordion` fix hydration issue

- projects/addon-table/components/table/th-group/th-group.component.ts
- projects/addon-table/components/table/th-group/th-group.template.html
- projects/addon-table/components/table/tr/tr.component.ts
- projects/addon-table/components/table/tr/tr.template.html
relates https://github.com/taiga-family/taiga-ui/issues/9278
> fix(addon-table): `tr`, `thGroup` fix hydration issues

- projects/legacy/components/input-date-time/input-date-time.directive.ts
> fix(legacy): `InputDateTime` fix native option for empty value

- .cspell.json
- package-lock.json
- projects/core/directives/dropdown/dropdown-context.directive.ts
> feat(core): migrate to longtap event

- .github/CODEOWNERS
Github support can helped me figure it out, now it will work as it should
auto assignee
> chore: enable core team

- projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
If you really need to skip type checking, you can use something that Typescript 3.0 introduced: the unknown type. Unlike any, unknown is safer to use in the sense that before actually doing something with data of this type, we must do some sort of checking, whereas any has no restrictions.
https://dev.to/arikaturika/typescript-why-to-use-unknown-instead-of-any-41i8
> refactor: use `unknown` instead of `any` for `isMultiValue` util

- projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dropdown.component.ts
> fix(addon-mobile): `InputDateRange` + `MobileCalendar` throw error on single date selection

- projects/addon-doc/components/code/index.html
- projects/addon-doc/components/code/tests/code.component.spec.ts
> feat(addon-doc): improve active zone for copy button

- projects/demo/src/modules/app/metrika/metrika.service.ts
- projects/demo/src/modules/components/abstract/control.ts
- projects/demo/src/modules/components/radio/examples/2/index.ts
- projects/demo/src/utils/component.pipe.ts
If you really need to skip type checking, you can use something that Typescript 3.0 introduced: the unknown type. Unlike any, unknown is safer to use in the sense that before actually doing something with data of this type, we must do some sort of checking, whereas any has no restrictions.
https://dev.to/arikaturika/typescript-why-to-use-unknown-instead-of-any-41i8
> chore(demo): drop `any`

- projects/legacy/components/input-time/native-time/native-time.component.ts
Open https://taiga-ui.dev/next/components/input-time#native using any mobile device
Also, there is error inside console:
```
ERROR TypeError: Cannot read properties of undefined (reading 'length')
at get value (native-time.component.ts:46:58)
at TuiNativeTimeComponent_HostBindings (native-time.component.ts:34:15)
at processHostBindingOpCodes (core.mjs:11853:21)
at refreshView (core.mjs:13544:9)
at detectChangesInView (core.mjs:13663:9)
at detectChangesInEmbeddedViews (core.mjs:13606:13)
at refreshView (core.mjs:13522:9)
at detectChangesInView (core.mjs:13663:9)
at detectChangesInEmbeddedViews (core.mjs:13606:13)
at refreshView (core.mjs:13522:9)
```
https://github.com/taiga-family/taiga-ui/blob/968e4178dc21e030e443fefdddd91702a842292e/projects/legacy/components/input-time/input-time.templa …
> fix(legacy): `InputTime` has broken support of native date picker

- projects/addon-commerce/components/input-card-group/input-card-group.component.ts
> fix(addon-commerce): `InputCardGroup` safari autofill focus

- projects/addon-doc/components/code/index.less
> chore: drop redundant code for mobile

- projects/cdk/utils/miscellaneous/is-valid-url.ts
- projects/cdk/utils/miscellaneous/test/is-valid-url.spec.ts
> fix(cdk): support `:` inside path segment in  url

- projects/addon-mobile/styles/taiga-ui-mobile.less
1. Open https://taiga-ui.dev/next/stackblitz
2. Add this line to `global_styles.less`:
```less
@import '@taiga-ui/addon-mobile/styles/taiga-ui-mobile.less';
```
It throws
```
Error in turbo_modules/@taiga-ui/addon-mobile@4.8.1-canary.852a9d9/styles/taiga-ui-mobile.less (35:4)
Could not import ./common/segmented from /~/src/global_styles.less
```
> chore(addon-mobile): improve StackBlitz support for `taiga-ui-mobile.less`

- projects/addon-mobile/styles/taiga-ui-mobile.less
1. Open https://taiga-ui.dev/stackblitz
2. Add this line to `global_styles.less`:
```less
@import '@taiga-ui/addon-mobile/styles/taiga-ui-mobile.less';
```
It throws:
```
Error in turbo_modules/@taiga-ui/addon-mobile@4.12.0/styles/taiga-ui-mobile.less (37:4)
Could not import ./common/header.less from /~/src/global_styles.less
```
Actually, I am not sure. It is just an assumption.
It based on another file (it works in StackBlitz):
https://github.com/taiga-family/taiga-ui/blob/e659f788f71069d77cd9e3eb91ea53d085918840/projects/core/styles/taiga-ui-theme.less#L1-L5
Relates to:
* https://github.com/taiga-family/taiga-ui/pull/9557
> chore(addon-mobile): stackblitz error for import of `taiga-ui-mobile.less`

- projects/core/directives/hint/hint-options.directive.ts
- projects/core/directives/hint/hint.style.less
- projects/kit/directives/tooltip/index.ts
- projects/kit/directives/tooltip/tooltip.directive.ts
- projects/kit/directives/tooltip/tooltip.options.ts
- projects/kit/directives/tooltip/tooltip.style.less
- projects/legacy/components/tooltip/tooltip.component.ts
> feat(kit): `Tooltip` add DI options

- projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
- projects/demo-playwright/tests/kit/input-date/input-date.spec.ts
- projects/demo-playwright/utils/page-objects/calendar-sheet.po.ts
- projects/demo-playwright/utils/page-objects/calendar.po.ts
- projects/demo-playwright/utils/page-objects/index.ts
- projects/demo-playwright/utils/page-objects/input-date.po.ts
- projects/kit/components/input-date/input-date.component.ts
- projects/kit/components/input-date/input-date.template.html
> fix(kit): `InputDate` click any day after `Until today` selected

- projects/demo-playwright/tests/legacy/input-date/input-date.spec.ts
- projects/demo-playwright/utils/page-objects/calendar.po.ts
- projects/demo-playwright/utils/page-objects/index.ts
- projects/demo-playwright/utils/page-objects/input-date.po.ts
- projects/legacy/components/input-date/input-date.template.html
> chore(demo-playwright): `InputDate` add test click any day after `Until today`

- projects/core/classes/driver.ts
- projects/core/components/dialog/dialog.style.less
- projects/core/components/dialog/dialog.template.html
- projects/core/directives/dropdown/dropdown.driver.ts
- projects/demo/src/modules/app/app.style.less
- projects/legacy/directives/legacy-dropdown-open-monitor/legacy-dropdown-open-monitor.ts
> fix(core): `DropdownOpen` fix initial open state

- projects/kit/styles/components/badge.less
> fix(kit): `Badge` fix font size on desktop

- projects/addon-commerce/components/thumbnail-card/thumbnail-card.style.less
https://taiga-ui.dev/next/components/thumbnail-card#backgrounds
https://taiga-previews--pr9604-thumbnail-card-blur-41buasuc.web.app/components/thumbnail-card#backgrounds
> fix(addon-commerce): `ThumbnailCard` with blur effect should keep its initial border-radius

- projects/kit/styles/components/switch.less
> fix(kit): `Switch` should have dark knob for the dark theme in web platform

- projects/kit/internal/primitive-calendar-range/primitive-calendar-range.component.ts
- projects/kit/internal/primitive-calendar-range/test/primitive-calendar-range.component.spec.ts
Close #8494 
**As Is:**
https://github.com/user-attachments/assets/9d1798af-8125-4f7d-98d3-c2bc93e92c5f
**To Be:**
https://github.com/user-attachments/assets/65c967e3-45f9-4c65-8853-0c7645e4c178
> fix(kit): `CalendarRange` shows actual `defaultViewedMonth`

- projects/core/components/root/root.component.ts
- projects/core/components/root/root.template.html
> fix(core): do not hide scrollbars on desktop when dialog is open

- projects/core/directives/hint/hint-options.directive.ts
- projects/core/directives/hint/hint-position.directive.ts
- projects/demo-playwright/tests/core/hint/hint.spec.ts
- projects/demo/src/modules/components/abstract/control.ts
- projects/demo/src/modules/components/abstract/hint-controller-documentation/index.html
- projects/demo/src/modules/components/abstract/hint.ts
- projects/demo/src/modules/components/abstract/inherited-documentation/index.html
- projects/demo/src/modules/components/abstract/inherited-documentation/index.ts
> feat(core): tuiHintDirection priority list

- projects/kit/components/stepper/stepper.component.ts
Fixes #9632 
The first time, when the query list is empty yet, indexOf for all steps returns `-1`
If we set `-1` to the `[activeItemIndex]` input of the stepper, it will cause the styles to flash since all steps are active for a millisecond.
https://github.com/user-attachments/assets/308f054e-abae-4457-8d02-18a0b1316cf6
> fix(kit): `Stepper` fix flashing styles

- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/kit/components/calendar-range/test/calendar-range.component.spec.ts
Fixes #9608 
When `defaultViewedMonth` updated (or other input), it transmit value to directly to the calendar (regardless of  `ngOnChanges` existence and it's logic). For others changing properties need not trigger logic inside `ngOnChanges`, when value is selected
_**calendar-range.component.ts**_
```
@Input()
public defaultViewedMonth: TuiMonth = TuiMonth.currentLocal();
```
**_calendar-range.template.ts_**
```
tui-calendar
...
[maxViewedMonth]="items.length ? null : (defaultViewedMonth | tuiMapper: monthOffset : -1)"
[month]="defaultViewedMonth"
...
/>
<tui-calendar
...
[minViewedMonth]="defaultViewedMonth | tuiMapper: monthOffset : 1"
[month]="defaultViewedMonth | tuiMapper: monthOffset : 1"
...
/>
```
So we need **not to update month**, if it comes new input and anyone value is …
> fix(kit): `CalendarRange` switch months if any input updated, when date range selected

- projects/core/constants/regexp.ts
- projects/demo-cypress/tsconfig.json
- projects/demo-playwright/tests/kit/input-date/input-date.spec.ts
- projects/kit/components/input-date/input-date.component.ts
Relates to #9582 
When textfield has initial control `value` (less than `min` or more than `max`), mask triggered and value transformed to min/max, what shouldn't be according to https://github.com/taiga-family/maskito/issues/1189#issuecomment-2394981669
> fix(kit): `InputDate` hold initial value with min/max defined

- projects/cdk/constants/regexp.ts
- projects/demo-playwright/tests/legacy/input-date/input-date.spec.ts
- projects/legacy/components/input-date/input-date.component.ts
- projects/legacy/components/input-date/test/input-date.component.spec.ts
When `value.length === DATE_FILLER_LENGTH (10)`, value may contain not only date string, but also letters string. 
```
this.value =
value.length !== DATE_FILLER_LENGTH
? null
: TuiDay.normalizeParse(value, this.dateFormat.mode);
```
This was not taken into account and as a result, an attempt was made to parse the date from the string and the value `01.01.0000` was obtained 
https://github.com/user-attachments/assets/92334503-3034-4294-b132-fc2bf195819c
> fix(legacy): `InputDate` incorrect value after backspace

- .github/workflows/e2e.yml
- projects/demo-playwright/project.json
Part of https://github.com/taiga-family/taiga-ui/pull/9554
> chore: explicit run e2e type check

- .github/workflows/e2e.yml
> ci: add shard matrix

- projects/demo-playwright/tests/kit/calendar-range/calendar-range.pw.spec.ts
- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/kit/components/calendar-range/test/calendar-range.component.spec.ts
Calendar not switch month with selected value
https://github.com/user-attachments/assets/b6243fc4-9b71-4ec0-9838-0f9e9f6d3fb0
> fix(kit): `CalendarRange` not switch month with selected value

- package.json
- projects/demo/src/modules/components/textfield/examples/5/index.html
- projects/demo/src/modules/components/textfield/examples/5/index.ts
- projects/demo/src/modules/components/textfield/index.html
- projects/demo/src/modules/components/textfield/index.ts
> chore(demo): update `Textfield` + `Maskito` example

- projects/core/components/dialog/dialog.component.ts
- projects/core/components/dialog/dialog.style.less
- projects/core/components/dialog/dialog.template.html
- projects/demo/src/modules/components/dialog/dialog.component.ts
- projects/demo/src/modules/components/dialog/examples/8/index.ts
> feat(core): `Dialog` move close button inside dialog

- projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
- projects/legacy/components/input-date-range/input-date-range.component.ts
- projects/legacy/components/input-date-range/test/input-date-range.component.spec.ts
Fixes #7960 
After press backspace:
**Before (main) ← Diff → After (local)**
> fix(legacy): `InputDateRange` double backspace to clear textfield

- projects/layout/components/block-status/block-status.style.less
Removed useless margin for empty t-block-image
Fix UIKIT-7696
> fix(layout): tui-block-status remove margins for empty t-block-image

- projects/demo-playwright/tests/kit/tabs/tabs.pw.spec.ts
> chore(demo-playwright): improve stability of `tabs.pw.spec.ts` for proprietary repo

- projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.template.html
- projects/core/directives/dropdown/dropdown-hover.directive.ts
- projects/demo-playwright/tests/kit/dropdown-hover/dropdown-hover.pw.spec.ts
- projects/demo-playwright/utils/page-objects/index.ts
- projects/demo-playwright/utils/page-objects/mobile-dropdown.po.ts
- projects/demo/src/modules/directives/dropdown-hover/examples/5/index.html
- projects/demo/src/modules/directives/dropdown-hover/examples/5/index.ts
- projects/demo/src/modules/directives/dropdown-hover/index.html
> fix(addon-mobile): `DropdownMobile` is not compatible with `DropdownHover`

- projects/addon-doc/components/documentation/documentation-property-connector.directive.ts
- projects/demo-playwright/tests/core/hint/hint.pw.spec.ts
> feat(addon-doc): use only one property on route for expose input prop value

- projects/core/directives/hint/hint-unstyled.component.ts
- projects/demo-playwright/tests/core/hint/hint.pw.spec.ts
- projects/demo/src/modules/directives/hint/examples/2/index.html
> fix(core): fix custom hint

- projects/legacy/package.json
The same logic as inside `@taiga-ui/core`
https://github.com/taiga-family/taiga-ui/blob/dc916bc9a5e6efe81b9943e6d075cf6220ef4a81/projects/core/package.json#L17-L19
> fix(legacy): add `styles` entrypoint to `exports` of `package.json`

- projects/demo-cypress/src/support/component-index.html
**textfield.cy.ts-[filler]-initial-value_2.png:**
**textfield.cy.ts-[filler]-initial-value_2.png:**
> chore(demo-cypress): hide caret for screenshot component testing

- projects/cdk/utils/miscellaneous/directive-binding.ts
> fix(cdk): Angular v19 `allowSignalWrites` warning

- projects/demo-playwright/tests/legacy/input-date-time/input-date-time.pw.spec.ts
- projects/demo/src/modules/components/input-date-time/examples/7/index.html
- projects/demo/src/modules/components/input-date-time/examples/7/index.ts
- projects/demo/src/modules/components/input-date-time/index.html
- projects/legacy/components/input-date-time/input-date-time.component.ts
> fix(legacy): `InputDateTime` validators not triggered when value change

- package-lock.json
- projects/demo/package.json
Open https://taiga-ui.dev/v3/stackblitz
It throws:
```
Error in turbo_modules/dompurify@3.2.2/dist/purify.cjs.d.ts (434:15)
',' expected.
```
Relates:
* https://github.com/taiga-family/ng-dompurify/pull/596
> chore: make StackBlitz great again for `v3` documentation

- projects/kit/components/carousel/carousel.component.ts
- projects/kit/components/carousel/carousel.style.less
- projects/kit/components/carousel/carousel.template.html
> fix(kit): `Carousel` fix dragging in chrome

- nx.json
- projects/testing/setup-jest/index.ts
> chore: update jest preset

- nx.json
- projects/legacy/components/input-date-range/test/input-date-range.component.spec.ts
> chore(legacy): `InputDateRange` test fix

- projects/core/directives/dropdown/dropdown.style.less
- projects/demo-playwright/tests/core/dropdown/dropdown.pw.spec.ts
Fixes #9683
el.getBoundingClientRect() returns wrong initial width
https://github.com/taiga-family/taiga-ui/blob/a28e79b34814f312ad1ef8398ebe5070e0120ed5/projects/core/services/position.service.ts#L25
because of this `left` is not calculated correctly
> fix(core): `Dropdown` fix initial width

- projects/core/components/hosted-dropdown/dropdown-open-monitor.directive.ts
Fixes #9666
1. Open https://taiga-ui.dev/v3
2. Focus search textfield 
3. Enter `acc`
4. Press Backspace
5. Type `c` again
**Expected behavior**: dropdown is shown
**Actual behavior**: you will never see dropdown again
```ts
import { Component } from '@angular/core';
import { FormControl } from '@angular/forms';
@Component({
selector: `my-app`,
template: `
<tui-root>
<tui-input [formControl]="control">
Enter 3 characters
<ng-container *ngIf="control.value.length > 2">
<tui-data-list *tuiDataList> Blah blah </tui-data-list>
</ng-container>
</tui-input>
</tui-root>
`,
})
export class AppComponent {
readonly control = new FormControl('');
}
```
1. Enter any 3 characters
7. Press Backspace
8. Insert any number of additional characters
**Expected behavior**: dropdown is shown
**Actual …
> fix(core): `Input` with `DataList` never shows dropdown after its 1st closing

- projects/core/directives/dropdown/dropdown-open.directive.ts
- projects/demo-cypress/src/support/component.ts
- projects/demo-cypress/src/tests/input-with-datalist.cy.ts
```html
<tui-input [formControl]="control">
Enter 3 characters
@if (control.value.length > 2) {
<tui-data-list *tuiDataList> Blah blah </tui-data-list>
}
</tui-input>
```
Enter `123`
**Expected behavior**: dropdown appears
**Actual behavior**: no dropdown
Explore more:
https://stackblitz.com/edit/input-with-datalist-v4-bug?file=src%2Fapp%2Fapp.template.html
> fix(core): `DropdownOpen` has CD problems after switching of `tuiDropdownEnabled` (`false`=>`true`)

- projects/core/styles/components/icon.less
- projects/kit/directives/icon-badge/icon-badge.style.less
autoprefixer adds `-webkit-mask-composite: source-in, xor` as a fallback for safari 14 and older, it only works when applying two masks
`mask-composite: intersect` works the same way in safari 15. (only when applying two masks)
use `mask-composite: intersect` only when we have two masks on ::after element - in `icon-badge` directive
> fix(core): `Icon` fix for old safari

- projects/kit/components/action-bar/action-bar.style.less
Fixes https://github.com/taiga-family/taiga-ui/issues/9700
Removed space at the start of button
> fix(kit): removed redundant space

- projects/legacy/classes/control.ts
- projects/legacy/components/multi-select/multi-select-group/multi-select-group.directive.ts
- projects/legacy/components/primitive-textfield/textfield/textfield.style.less
- projects/legacy/components/select-option/select-option.component.ts
> fix(legacy): `MultiSelect` fix pristine and updateOn: blur issues

- projects/core/components/expand/expand.style.less
- projects/demo/src/modules/components/tree/examples/8/index.html
- projects/demo/src/modules/components/tree/examples/8/index.less
- projects/demo/src/modules/components/tree/examples/8/index.ts
- projects/demo/src/modules/components/tree/index.html
Fixes #5619 
https://github.com/user-attachments/assets/d7180f9e-112b-4f1a-9386-5b632dbcbbb5
> fix(core): transform breaks fixed position in tiles

- projects/core/styles/mixins/textfield.less
> feat(core): add margin right for left icons in small textfield

- projects/kit/components/segmented/segmented.style.less
> fix(kit): `Segmented` fix shadow clipping in Safari

- projects/demo/src/modules/components/input-time/index.html
- projects/demo/src/modules/components/input-time/index.ts
- projects/legacy/components/input-time/input-time.component.ts
> feat(legacy): add `itemsHidden` prop to `tui-input-time`

- projects/demo/src/modules/components/input-inline/examples/4/index.html
- projects/demo/src/modules/components/input-inline/examples/4/index.less
- projects/demo/src/modules/components/input-inline/examples/4/index.ts
- projects/demo/src/modules/components/input-inline/index.ts
- projects/kit/components/input-inline/input-inline.component.ts
- projects/kit/components/input-inline/input-inline.style.less
- projects/kit/components/input-inline/input-inline.template.html
> fix(kit): `InputInline` has broken scroll in Safari & Firefox

- projects/kit/components/tabs/tab.directive.ts
- projects/kit/components/tabs/test/tabs.component.spec.ts
> fix(kit): `Tabs` fix multiple emitting of activeItemIndexChange

- .github/workflows/test.yml
- projects/legacy/components/input-date-range/test/input-date-range.component.spec.ts
- projects/testing/setup-jest/index.ts
> chore: mock date in jest

- projects/kit/components/tree/misc/tree.service.ts
The node loading engine should not cancel the previous request, because these requests are for different nodes. If switchMap cancels a request, then the loading for the cancelled node is always running.
https://t.me/taiga_ui/7924/25725
> fix(kit): fix parallel lazy loading tree nodes

- projects/addon-table/components/table/directives/direction-order.directive.ts
- projects/addon-table/components/table/directives/table.directive.ts
- projects/addon-table/components/table/directives/test/direction-order.directive.spec.ts
- projects/addon-table/components/table/pipes/table-sort.pipe.ts
- projects/addon-table/components/table/table.options.ts
- projects/addon-table/components/table/th/th.component.ts
> fix(addon-table): sort icons are reversed

- projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
- projects/demo-playwright/tests/legacy/input-date-time/input-date-time.pw.spec.ts
- projects/demo-playwright/tests/legacy/input-date/input-date.pw.spec.ts
- projects/demo-playwright/utils/page-objects/input-date-range.po.ts
- projects/demo-playwright/utils/page-objects/input-date.po.ts
- projects/legacy/components/input-date-range/input-date-range.component.ts
- projects/legacy/components/input-date-range/test/input-date-range.component.spec.ts
- projects/legacy/components/input-date-time/input-date-time.component.ts
- projects/legacy/components/input-date-time/test/input-date-time.component.spec.ts
- projects/legacy/components/input-date/input-date.component.ts
- projects/legacy/components/input-date/input-date.directive.ts
- projects/legacy/components/input-date/test/input-date.component.spec.ts
> fix(legacy): `InputDate{Range|Time}` + `input[tuiTextfieldLegacy]` + `tuiTextfieldFiller` has CD problems

- projects/demo/src/modules/components/multi-select/examples/1/index.ts
- projects/demo/src/modules/pipes/filter-by-input/examples/3/index.ts
- projects/legacy/components/input-tag/input-tag.style.less
> feat(legacy): limit `tui-tag` width to `80%` to avoid wrapping in selects

- projects/kit/components/tiles/tile-handle.directive.ts
> fix(kit): strange behavior in Safari when working with tiles

- projects/addon-commerce/components/thumbnail-card/thumbnail-card.component.ts
- projects/addon-commerce/components/thumbnail-card/thumbnail-card.options.ts
- projects/addon-commerce/components/thumbnail-card/thumbnail-card.style.less
- projects/addon-commerce/components/thumbnail-card/thumbnail-card.template.html
- projects/demo-playwright/tests/addon-commerce/thumbnail-card.pw.spec.ts
- projects/demo/src/modules/components/thumbnail-card/examples/1/index.ts
- projects/demo/src/modules/components/thumbnail-card/index.html
- projects/demo/src/modules/components/thumbnail-card/index.ts
Fixes TUIPRJ-251
**TODO** for proprietary repo (file `overrides.less`):
* Set new value for `--t-logo-height`
* Overrides `bottom` property for `.t-logo` & `.t-content`
> feat(addon-commerce): `ThumbnailCard` has new `xs` size

- projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
- projects/demo/src/modules/components/input-date-range/examples/5/index.html
- projects/demo/src/modules/components/input-date-range/examples/5/index.ts
- projects/legacy/components/input-date-range/input-date-range.component.ts
> fix(legacy): reset cached active period in `tui-input-date-range`

- projects/demo/src/modules/components/thumbnail-card/examples/3/index.html
- projects/demo/src/modules/components/thumbnail-card/index.ts
Proprietary repo provides its own value for `TUI_PAYMENT_SYSTEM_ICONS` token
> chore(demo): use `TUI_PAYMENT_SYSTEM_ICONS` token for documentation page `ThumbnailCard`

- .cspell.json
- projects/cdk/utils/math/round.ts
- projects/core/utils/format/test/format-number.spec.ts
- projects/demo-playwright/tests/legacy/input-number/input-number.pw.spec.ts
- projects/legacy/components/input-number/input-number.component.ts
1. Open https://taiga-ui.dev/components/input-number/API?thousandSeparator=_&precision=2
2. Paste 
```
123_456_789_012_345.67
```
3. Blur
**Previous behavior:** `123_456_789_012_345.69`
**New behavior:** `123_456_789_012_345.67`
Fixes #9970
> fix(kit): `InputNumber` has rounding problems on blur with float large numbers

- projects/demo/src/modules/directives/swipe/examples/2/index.ts
Fixes [#9977](https://github.com/taiga-family/taiga-ui/issues/9977)
Just forgot to import tuiSidebar during migration process
It's strange but in development mode console have clear errors about import absent
> chore(demo): added forgotten import

- projects/core/directives/dropdown/dropdown-open-legacy.directive.ts
- projects/legacy/directives/legacy-dropdown-open-monitor/legacy-dropdown-open-monitor.ts
Fixes #9609
Description : 
1. We used `Subject` because we are concerned about the latest value compared to maintaining the last state.
2. Created the `emitOpenChange` method to centralize & handle responsibility for emitting values.
3. Replaced previous value emission logic with the currently integrated flow.
> fix(core): emit tuiDropdownOpenChange on distinct values

- projects/demo/src/modules/components/sheet-dialog/examples/4/index.less
Fixes https://github.com/taiga-family/taiga-ui/issues/9995
> chore(demo): fix gap

- projects/kit/components/stepper/stepper.component.ts
> feat(kit): safety change active index in stepper

- .cspell.json
- projects/addon-table/components/table/th/th.component.ts
- projects/demo/src/modules/components/table/examples/8/index.html
- projects/demo/src/modules/components/table/examples/8/index.ts
- projects/demo/src/modules/components/table/index.ts
Fixes https://github.com/taiga-family/taiga-ui/issues/5105
https://github.com/user-attachments/assets/61595f87-8b1f-4a32-a608-ff54cddbc091
> feat(addon-table): allow resize more than 100% width of table

- projects/core/components/dialog/dialog.interfaces.ts
- projects/core/components/dialog/dialog.style.less
- projects/core/components/dialog/dialog.template.html
> fix(core): dialog has padding for close button event when not closeable

- projects/cdk/observables/index.ts
- projects/cdk/observables/untracked-scheduler.ts
- projects/cdk/utils/focus/focused-in.ts
- projects/cdk/utils/focus/tests/focused-in.spec.ts
> fix(cdk): fix tuiFocusedIn error when focus events happened in reactive context

- projects/addon-doc/components/documentation/documentation.style.less
- projects/addon-doc/components/documentation/documentation.template.html
Fixes #9966 
1. Fixes type column overlapping.
2. Fixes Name & description column overlapping (This one we found while unit testing, fixed it within the same PR).
> #9966 - Fix documentation Name & Description, Type columns overlapping.

- projects/addon-mobile/components/mobile-calendar/mobile-calendar.style.less
- projects/addon-mobile/components/mobile-calendar/mobile-calendar.template.html
- projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
Fixes #9662
https://github.com/user-attachments/assets/b81ab78d-2aea-40d0-9e50-f90b118e9d40
https://github.com/user-attachments/assets/efc138c5-780e-4b8a-9818-e787dd7b20ef
> fix(addon-mobile): virtual-scroll flickers during scroll in zoneless mode

- projects/legacy/components/arrow/arrow.component.ts
- projects/legacy/components/arrow/arrow.template.html
- projects/legacy/components/input-tag/input-tag.component.ts
> fix(legacy): `TuiMultiSelect` fix arrow

- projects/cdk/schematics/ng-update/v4/index.ts
- projects/cdk/schematics/ng-update/v4/steps/migrate-providers-from.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-tinkoff-editor.spec.ts
> chore(schematics): drop redundant editor providers

- projects/kit/components/line-clamp/line-clamp.component.ts
> fix(kit): `LineClamp` fix initial transition

- projects/cdk/date-time/test/time.spec.ts
- projects/cdk/date-time/time.ts
> fix(cdk): `TuiTime.shift` doesn't shift higher order units

- projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts
Fixes #9834 
Changes Description:-
1. Consider trimming the number with `trimCountryPrefix` in [`tuiCreateCompletePhoneInsertionPreprocessor`](https://github.com/taiga-family/taiga-ui/blob/main/projects/legacy/components/input-phone/utils/complete-phone-insertion-preprocessor.ts)  when the pasted phone number is with country code.
> fix(legacy): `InputPhone` incorrectly parses paste of the shorten phone number

- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badged-content.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badged-content.spec.ts
> chore(schematics): valid migration for badged content

- projects/demo/src/modules/components/accordion/index.html
- projects/demo/src/modules/components/accordion/index.ts
Fixes #9057 
- Migrate Accordion API docs to the new API.
> #9057 - Migrate `tui-accordion` API docs to new API

- projects/core/directives/dropdown/with-dropdown-open.directive.ts
- projects/demo/src/components/dropdown/index.html
- projects/demo/src/components/dropdown/index.ts
- projects/demo/src/modules/components/input-phone-international/index.html
- projects/demo/src/modules/directives/dropdown/index.html
> feat(core): added `tuiDropdownEnabled` to exposed inputs of `TuiWithDropdownOpen`

- projects/kit/components/confirm/confirm.style.less
> fix(kit): fix text overflow in Confirm component

- projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
> chore(schematics): valid migration for `tui-primitive-textfield`

- projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-error.spec.ts
> chore(schematics): valid migration for error pipe module

- projects/cdk/schematics/ng-update/v4/steps/templates/migrate-expandable.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-expandable.spec.ts
> chore(schematics): valid migration for expandable in template

- projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-scrollbar.spec.ts
> chore(schematics): valid migration for scrollbar

- projects/demo/src/modules/components/bar/index.html
- projects/demo/src/modules/components/bar/index.ts
Fixes #9057 
- Migrate bar chart docs api to new api.
> #9057 - Migrate `tui-bar-chart` docs API to new API

- projects/demo/src/modules/components/badge-notification/index.html
- projects/demo/src/modules/components/badge-notification/index.ts
> #9057 - Migrate `tui-badage-notification` docs API to new API

- projects/demo/src/modules/components/arc-chart/index.html
- projects/demo/src/modules/components/arc-chart/index.ts
Fixes #9057 
- Migrate arc chart api doc to new API.
> #9057 - Migrate `tui-arc-chart` API docs to new API

- projects/demo/src/modules/components/badge/index.html
- projects/demo/src/modules/components/badge/index.ts
> #9057 - Migrate `tui-badge` docs API to new API

- projects/demo/src/modules/components/input-number/examples/1/index.html
- projects/demo/src/modules/components/input-number/examples/2/index.html
- projects/demo/src/modules/components/input-number/examples/3/index.html
- projects/demo/src/modules/components/input-number/examples/4/index.html
- projects/demo/src/modules/components/input-number/examples/5/index.html
https://github.com/taiga-family/taiga-ui/blob/9244f1a1f24cc28049e1b8ed0e7731e22ae8ebda/projects/kit/components/input-number/input-number.component.ts#L119-L125
> chore(demo): remove redundant `inputmode=decimal` from documentation examples of new `InputNumber`

- projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts
- projects/cdk/schematics/ng-update/v4/steps/constants/inputs-to-remove.ts
- projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
> chore(schematics): valid migration for anchor

- projects/kit/components/input-phone-international/input-phone-international.component.ts
- projects/legacy/components/input-date/input-date.component.ts
- projects/legacy/components/input-phone/input-phone.component.ts
- projects/legacy/components/input-time/input-time.component.ts
- projects/legacy/components/input-year/input-year.component.ts
Learn more (read body description of this PR):
* https://github.com/taiga-family/taiga-ui/pull/10168
> fix(kit,legacy): all textfield controls should handle initial `ngModel` phantom `null` value

- projects/kit/components/input-number/input-number.component.ts
https://github.com/taiga-family/taiga-ui/blob/1171fbc3807ece6ec0b5baefa57b3535ebed2b9e/projects/addon-table/components/table/td/td.component.ts#L10-L16
> fix(kit): new version of `InputNumber` should provide `TuiControl` for DI

- projects/demo/src/modules/components/avatar/index.html
- projects/demo/src/modules/components/avatar/index.ts
Part of #9057 
- Migrate avatar docs API to new API.
> #9057 - chore(demo): Migrate `tui-avatar` docs API to new API

- projects/demo/src/modules/components/accordion/examples/1/index.html
- projects/demo/src/modules/components/accordion/examples/1/index.ts
- projects/experimental/components/accordion/accordion.component.ts
- projects/experimental/components/accordion/accordion.directive.ts
- projects/experimental/components/expand/expand.component.ts
> fix(experimental): `Accordion` fix error with dynamic items

- projects/core/components/dialog/dialog.factory.ts
- projects/core/components/dialog/test/dialog.factory.spec.ts
> fix(core): fix tuiDialog typings for classes with constructor parameters

- projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
- projects/demo/src/modules/components/line-clamp/examples/3/index.html
- projects/demo/src/modules/components/line-clamp/examples/3/index.ts
- projects/demo/src/modules/components/line-clamp/index.html
- projects/kit/components/line-clamp/line-clamp.component.ts
> fix(kit): debounce `overflownChange` event

- projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.style.less
- projects/core/components/data-list/data-list.style.less
- projects/demo-playwright/playwright.options.ts
- projects/demo-playwright/tests/addon-mobile/mobile-dropdown/mobile-dropdown-with-textfield.pw.spec.ts
- projects/demo-playwright/tests/kit/action-bar/action-bar.mobile.pw.spec.ts
- projects/demo-playwright/tests/kit/dropdown-hover/dropdown-hover.pw.spec.ts
- projects/demo-playwright/tests/kit/input-phone-international/phone-i18n-with-mobile-dropdown.pw.spec.ts
- projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
- projects/demo-playwright/tests/legacy/select/select.mobile.pw.spec.ts
- projects/demo-playwright/utils/page-objects/textfield-with-data-list.po.ts
- projects/demo/src/modules/components/sheet-dialog/examples/6/index.less
Fixes UIKIT-7690
<div>
=>
</div>
___
<div>
=>
</div>
> fix(addon-mobile): `DataList` inside `DropdownMobile` should not have built-in horizontal indent

- projects/addon-table/components/table/directives/table.style.less
- projects/core/components/data-list/data-list.style.less
- projects/demo/src/modules/components/pulse/examples/1/index.html
- projects/demo/src/modules/components/pulse/examples/1/index.ts
- projects/demo/src/modules/components/pulse/examples/2/index.less
- projects/kit/components/pulse/pulse.component.ts
- projects/kit/components/pulse/pulse.style.less
> feat(core): `DataList` update labels design according to specs

- projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts
- projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
- projects/addon-mobile/components/mobile-calendar/mobile-calendar.template.html
- projects/cdk/date-time/day-range.ts
- projects/cdk/date-time/test/day-range.spec.ts
- projects/core/components/calendar/calendar-sheet.component.ts
- projects/core/components/calendar/calendar-sheet.options.ts
- projects/core/components/calendar/index.ts
- projects/demo-playwright/tests/kit/calendar-range/calendar-range.pw.spec.ts
- projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
- projects/demo-playwright/utils/page-objects/calendar-range.po.ts
- projects/demo-playwright/utils/page-objects/calendar-sheet.po.ts
- projects/demo-playwright/utils/page-objects/calendar.po.ts
- projects/demo/src/modules/components/mobile-calendar/examples/2/index.html
- projects/demo/src/modules/components/mobile-calendar/examples/2/index.ts
- projects/demo/src/modules/components/mobile-calendar/examples/import/template.md
- projects/demo/src/modules/components/mobile-calendar/index.html
- projects/demo/src/modules/components/mobile-calendar/index.less
- projects/kit/components/calendar-range/calculate-disabled-item-handler.ts
- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/kit/components/calendar-range/day-caps-mapper.ts
Fixes #7550
Low-level component `TuiCalendarSheet` decides if user completes selection of range period or not:
https://github.com/taiga-family/taiga-ui/blob/031f55054aec8f856f61f37461d7690ef1aaca99/projects/core/components/calendar/calendar-sheet.component.ts#L38-L39
https://github.com/taiga-family/taiga-ui/blob/031f55054aec8f856f61f37461d7690ef1aaca99/projects/core/components/calendar/calendar-sheet.component.ts#L124-L125
`TuiCalendarSheet` is dumb and does not have any internal state – it only depends on input property `this.value` 
https://github.com/taiga-family/taiga-ui/blob/031f55054aec8f856f61f37461d7690ef1aaca99/projects/core/components/calendar/calendar-sheet.component.ts#L57-L58
and emits output event `dayClick` on any day click …
> fix(kit): `CalendarRange` should not require extra click to start new range after same day range

- projects/kit/components/input-number/input-number.style.less
Open StackBlitz of this documentation example:
https://taiga-ui.dev/next/components/input-number#step
Use Cypress Component Testing with `TuiInputNumber`:
> fix(kit): increase css-specificity for step button's styles inside `TuiInputNumber`

- projects/demo-playwright/tests/legacy/input-date/input-date.pw.spec.ts
- projects/demo/src/modules/components/input-date/examples/1/index.html
- projects/demo/src/modules/components/input-date/examples/1/index.ts
> chore(legacy): `InputDate` add test show actual min/max in `Calendar`

- projects/core/directives/dropdown/dropdown-context.directive.ts
Fixes #9797
https://github.com/user-attachments/assets/c1d6c5cb-a176-44cd-b5cd-1c1e3613487c
https://github.com/user-attachments/assets/cf242d93-7a50-440f-ab2b-2f497ed519f1
> fix(core): `tuiDropdownContext` menu remains open after long tap

- projects/kit/components/input-tag/input-tag.component.ts
- projects/kit/components/input-tag/test/input-tag.component.spec.ts
> feat(kit): input tag converts the last element to tag after paste event

- projects/legacy/components/input-tag/input-tag.component.ts
- projects/legacy/components/input-tag/test/input-tag.component.spec.ts
> feat(legacy): input tag converts the last element to tag after paste event

- projects/layout/components/search/search.styles.less
> fix(layout): allow `textfield` customization via `[tuiSearchField]`

- projects/demo-playwright/tests/kit/input-date-time/input-date-time.spec.ts
- projects/demo/src/modules/components/input-date-time/examples/1/index.html
- projects/demo/src/modules/components/input-date-time/examples/1/index.ts
- projects/kit/components/input-date-time/input-date-time.component.ts
> fix(kit): `InputDateTime` not reset initial value to min/max and show actual in calendar

- projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
- projects/demo/src/modules/components/input-date-range/examples/1/index.ts
> chore(demo-playwright): `InputDateRange` add test not reset initial value to min/max and show actual in calendar

- projects/addon-doc/components/api/api-item.component.ts
Add the following code to any API documentation page:
```ts
protected debug = signal('');
```
```html
<tr
name="[debug]"
tuiDocAPIItem
type="string"
[value]="debug()"
(valueChange)="debug.set($event)"
>
DEBUG
</tr>
```
Open http://localhost:3333/components/any/API?debug=42
It throws
```
ERROR Error: ASSERTION ERROR: Updating a signal during template or host binding execution is not allowed. [Expected=> null != null <=Actual]
at throwError (core.mjs:328:11)
at assertDefined (core.mjs:324:9)
at Object.consumerMarkedDirty (core.mjs:11722:13)
at consumerMarkDirty (core.mjs:2547:29)
at producerNotifyConsumers (core.mjs:2529:17)
at signalValueChanged (core.mjs:2837:5)
at Function.signalSetFn [as set] (core.mjs:2847:9)
at Page_ng_template_2_Template_tr_valueChange_11_listener (index.html:40:32) …
```
> fix(addon-doc): `DocAPIItem` throws error for signal-based output handlers

- projects/demo/src/modules/components/cell/examples/4/index.html
- projects/demo/src/modules/components/cell/examples/9/index.html
- projects/demo/src/modules/components/cell/examples/9/index.less
- projects/demo/src/modules/components/cell/examples/9/index.ts
- projects/demo/src/modules/components/cell/index.ts
- projects/layout/components/cell/cell.styles.less
> feat(layout): `Cell` add disabled state

- projects/demo/src/modules/components/dialog/examples/import/custom-dialog.md
> chore(demo): fix setup documentation for Dialog

- projects/demo/src/modules/components/legend-item/examples/1/index.ts
This PR fixed error , when hover in `TuiLegendItem` set false , activeItemIndex set 0 
[link to Docs](https://taiga-ui.dev/charts/legend-item#ring)
https://github.com/user-attachments/assets/0cc82c20-1384-4033-bcb2-f6906cd2bbe3
> chore(demo): `TuiLegendItem` change activeItemIndex when unhover legend item

- projects/demo-playwright/utils/is-flaky-examples.ts
> chore: flaky bottom-sheet e2e

- projects/experimental/components/search-results/search-results.component.ts
- projects/layout/components/navigation/subheader.component.ts
> fix(experimental): `SearchResults` fix focusing hidden tabs

- projects/legacy/components/input-date-range/input-date-range.component.ts
- projects/legacy/components/input-date-time/input-date-time.component.ts
- projects/legacy/components/input-date/input-date.component.ts
- projects/legacy/components/input-date/test/input-date.component.spec.ts
> fix(legacy): `InputDate` ignore null value if internal value is already null

- projects/demo-cypress/src/tests/input-phone-international.cy.ts
- projects/experimental/components/input-phone-international/input-phone-international.component.ts
> fix(experimental): `InputPhoneInternational` detects `countryIsoCode` on control update with complete phone

- projects/legacy/components/input-date-multi/input-date-multi.component.ts
- projects/legacy/components/input-date-multi/test/input-date-range.component.spec.ts
> fix(legacy): `InputDateMulti` include first/last date as valid

- projects/demo/src/modules/components/data-list/examples/4/custom-list/index.html
- projects/demo/src/modules/components/data-list/examples/4/custom-list/index.less
- projects/demo/src/modules/components/data-list/examples/4/custom-list/index.ts
Custom data list now has sticky search bar like [input-phone-international](https://taiga-ui.dev/components/input-phone-international#countries) example.
> docs: add sticky search bar to custom data list

- projects/cdk/utils/dom/value-binding.ts
- projects/demo-playwright/tests/kit/input-number/input-number.pw.spec.ts
- projects/kit/components/input-number/input-number.component.ts
https://github.com/user-attachments/assets/372c3a9c-eded-4b68-8d32-1ba6cd656cbe
https://github.com/user-attachments/assets/ec0aca34-3c84-4ddc-9b28-c15d77ba7f3b
> fix(kit): improve caret management for `InputNumber` on step action

- projects/core/directives/dropdown/dropdown.component.ts
> fix(core): fix dropdown when host is svg element

- projects/demo-cypress/src/tests/mobile-calendar.cy.ts
See failed jobs in other PRs.
For example: https://github.com/taiga-family/taiga-ui/actions/runs/13586033007/job/37981123699?pr=10480
> chore(demo-cypress): mock current date for `MobileCalendar` tests

- projects/addon-commerce/components/input-card-group/input-card-group.style.less
- projects/core/styles/theme/appearance/textfield.less
> fix(addon-commerce): `InputCardGroup` should remove browser autofill styles for Chrome on IOS

- projects/demo-playwright/tests/legacy/input-number/input-number.pw.spec.ts
Relates:
* https://github.com/taiga-family/taiga-ui/pull/10485
```
1) [chromium] › projects/demo-playwright/tests/legacy/input-number/input-number.pw.spec.ts:451:17 › InputNumber › API › value formatting on blur › text field does not contain any digit (only prefix + postfix) => clear text field's value on blur 
Error: Timed out 5000ms waiting for expect(locator).toHaveValue(expected)
Locator: locator('#demo-content').getByTestId('tui-primitive-textfield__native-input')
Expected string: "$ kg"
Received string: "$432 kg"
Call log:
- expect.toHaveValue with timeout 5000ms
- waiting for locator('#demo-content').getByTestId('tui-primitive-textfield__native-input')
9 × locator resolved to <input tabindex="0" maxlength="23" inputmode="decimal" aria-invalid="false" _ngcontent-ng-c2766531456="" …
```
> chore(demo-playwright): fix invalid order of actions for `InputNumber` test

- projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
- projects/addon-mobile/components/sheet-dialog/sheet-dialog.options.ts
- projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
- projects/addon-mobile/components/sheet-dialog/sheet-dialog.template.html
- projects/demo/src/modules/components/sheet-dialog/examples/7/index.html
- projects/demo/src/modules/components/sheet-dialog/examples/7/index.less
- projects/demo/src/modules/components/sheet-dialog/examples/7/index.ts
- projects/demo/src/modules/components/sheet-dialog/index.html
- projects/demo/src/modules/components/sheet-dialog/index.ts
`SheetDialog` add `fullscreen` option, add example and update API page
> feat(addon-mobile): `SheetDialog` add `fullscreen`

- projects/demo-playwright/tests/legacy/input-number/input-number.pw.spec.ts
Relates:
- https://github.com/taiga-family/taiga-ui/pull/10485
> chore(demo-playwright): fix invalid order of actions for `InputNumber` test (again)

- projects/core/components/data-list/data-list.style.less
Fixes #10456 
`attr()` not correct working when `data-label` is not defined since Chrome 133
https://developer.chrome.com/blog/advanced-attr
```
&::before {
content: attr(data-label);
...
}
```
> fix(core): `TuiDataList` attr(data-label) not correct working in Chrome

- projects/demo/src/modules/components/icon/examples/10/index.html
- projects/demo/src/modules/components/icon/examples/10/index.ts
- projects/demo/src/modules/components/icon/index.html
Add new example
```
<tui-icon [icon]="icon" />
```
```
protected readonly icon = `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(
'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 7-7 7 7"/><path d="M12 19V5"/></svg>',
)}`;
```
> chore(demo): `Icon` add example inline svg

- scripts/generate-demo-routes-file.ts
Open:
* https://taiga-ui.dev/legacy/input-number/API
* https://taiga-ui.dev/legacy/input-number/Setup
See console logs
> ci(demo): fix prerender of `API` & `Setup` pages of legacy components

- projects/layout/components/block-status/block-status.style.less
> fix(layout): `BlockStatus` fix margin when description block is empty

- projects/demo/src/modules/components/input-month-legacy/index.html
- projects/demo/src/modules/components/input-number-legacy/index.html
Open:
* https://taiga-ui.dev/legacy/input-number
* https://taiga-ui.dev/legacy/input-month
It opens 404 page
> chore(demo): fix source link for legacy `InputNumber` & `InputMonth`

- projects/demo-cypress/src/tests/accordion.cy.ts
- projects/experimental/components/accordion/accordion.component.ts
> fix(experimental): use valid content children from template into `tui-accordion`

- projects/addon-charts/components/arc-chart/arc-chart.template.html
- projects/addon-charts/components/bar-set/bar-set.template.html
- projects/addon-charts/components/bar/bar.template.html
- projects/addon-charts/components/pie-chart/pie-chart.template.html
Fixes https://github.com/taiga-family/taiga-ui/issues/10674
change "'var(--tui-chart-categorical-0' + index + ')'" to"'var(--tui-chart-categorical-' + index.toString().padStart(2, '0')+ ')'" 
Now bar color work good
> fix(addon-charts): bar color

- projects/cdk/utils/miscellaneous/create-token.ts
https://stackblitz.com/edit/option-content-with-skip-self
`TUI_OPTION_CONTENT` is projected content via `polymorpheusOutlet` (legacy approach) / `createComponent` (modern approach). Both approaches attach parent injector to this projected component.
**Previous behavior:**
`inject(TUI_OPTION_CONTENT, {skipSelf: true))` looks inside local injectors and get default `undefined` (from token factory). Stop exploring DI hierarchy (do not explore "parent" injectors).
**New behavior:**
`inject(TUI_OPTION_CONTENT, {skipSelf: true))` is not found inside "local" injectors - we reach "local" `NullInjector` => Got to "parent" inejctors.
> fix(cdk): `tuiCreateToken` with no arguments should not create token with default `undefined`-value

- projects/demo/src/modules/app/app.routes.ts
- projects/demo/src/modules/app/demo-routes.ts
- projects/demo/src/modules/app/pages.ts
- projects/demo/src/modules/components/pager/examples/1/index.html
- projects/demo/src/modules/components/pager/examples/1/index.ts
- projects/demo/src/modules/components/pager/examples/2/index.html
- projects/demo/src/modules/components/pager/examples/2/index.ts
- projects/demo/src/modules/components/pager/examples/3/index.html
- projects/demo/src/modules/components/pager/examples/3/index.less
- projects/demo/src/modules/components/pager/examples/3/index.ts
- projects/demo/src/modules/components/pager/examples/import/import.md
- projects/demo/src/modules/components/pager/examples/import/template.md
- projects/demo/src/modules/components/pager/index.html
- projects/demo/src/modules/components/pager/index.ts
- projects/demo/used-icons.ts
- projects/kit/components/index.ts
- projects/kit/components/pager/index.ts
- projects/kit/components/pager/ng-package.json
- projects/kit/components/pager/pager.component.html
- projects/kit/components/pager/pager.component.ts
- projects/kit/components/pager/pager.styles.less
- projects/kit/components/slider/slider.style.less
- projects/kit/styles/components/progress-bar.less
Fixes #10588 
https://github.com/user-attachments/assets/60d85667-3b26-4497-8f50-095304f7e728
https://github.com/user-attachments/assets/e7fc6f55-e72c-4eed-ac1e-831025d2b3ba
https://github.com/user-attachments/assets/bccac78f-32da-4e50-b34f-21839f23bbea
> feat: add `tui-pager`

- projects/addon-mobile/components/sheet-dialog/index.ts
- projects/addon-mobile/components/sheet-dialog/sheet-dialog-close.directive.ts
- projects/addon-mobile/components/sheet-dialog/sheet-dialog.module.ts
- projects/addon-mobile/components/sheet-dialog/sheet-dialog.template.html
Add `tuiSheetDialogClose` directive to listen such events from sheet content:
```
elements.dispatchEvent(
new CustomEvent(TUI_SHEET_DIALOG_CLOSE, {bubbles: true}),
);
```
> feat(addon-mobile): `SheetDialog` add close directive to listen close events

- projects/legacy/components/input-time/input-time.template.html
> fix(legacy): `InputTime` should hide icon if it equals to empty string

- projects/core/utils/miscellaneous/is-editing-key.ts
- projects/core/utils/miscellaneous/test/is-editing-key.spec.ts
Add a default parameter value to `tuiIsEditingKey` to handle cases where `key` might be an `undefined` (e.g., from autofill events). This prevents potential runtime errors.
Added unit tests to verify:
- Handling of `undefined` and empty string inputs.
- Correct true for single-character keys.
- Correct true for `tuiEditingKeys` values.
> fix(core): `tuiIsEditingKey` safe argument for autofill empty key

- projects/kit/components/input-time/input-time.template.html
> fix(kit): `InputTime` should hide icon if it equals to empty string

- projects/core/components/textfield/select-like.directive.ts
https://taiga-ui.dev/components/input-month
> fix(core): `InputMonth` should hide Android text select handle

- projects/kit/directives/chevron/chevron.style.less
> fix(core): `Textfield` has invalid width for `[tuiChevron]`'s icon

- projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts
> fix(cdk): `ng-add` fix wrapping with tui-root for `UTF-8 with BOM` templates

- projects/addon-doc/components/example/example.component.ts
- projects/addon-doc/components/example/example.template.html
> feat(addon-doc): hide fullscreen button when device doesn't support fullscreen API

- projects/addon-commerce/components/input-card/input-card.component.ts
- projects/experimental/components/input-phone-international/input-phone-international.component.ts
- projects/kit/components/input-month/native-month-picker/native-month-picker.component.ts
- projects/kit/components/input-number/step/input-number-step.component.ts
- projects/kit/components/input-password/input-password.component.ts
- projects/kit/components/input-pin/input-pin.component.ts
- projects/layout/components/input-search/input-search.component.ts
https://angular.dev/guide/hydration#valid-html-structure
```
ERROR RuntimeError:
NG0502: During hydration, Angular expected an element to be present at this location.
<input
id="tui_41744089732122"
_ngcontent-ng-c2887981911=""
data-appearance="textfield"
data-focus="false"
formcontrolname="country"
ng-reflect-countries-value="AF,AX,AL,DZ,AS,AD,AO,AI,AG,AR,"
ng-reflect-country-search="true"
ng-reflect-iso-code="RU"
ng-reflect-name="country"
tuiappearance=""
tuiinputphoneinternational=""
type="tel"
value="******"
class="tui-appearance-initializing"
/>
…
<-- AT THIS LOCATION
…
</input>
To fix this problem:
* check corresponding component for hydration-related issues
* check to see if your template has valid HTML structure
* or skip hydration by adding the `ngSkipHydration` attribute to its …
```
> fix: add `ngSkipHydration` for `<input/>`-s with template inside (to prevent SSR hydration error)

- projects/demo/src/modules/markup/typography/index.html
On https://taiga-ui.dev/typography have litle discrepancy in heading list. In  font-weight column value stated as 'normal', but in variables.less it has 'bold'
> chore(demo): in typography change to bold font-weight on font-heading

- projects/kit/components/stepper/stepper.component.ts
> fix(kit): navigate to active element after first render for `tuiStepper`

- projects/demo/src/modules/directives/highlight/index.html
Fixes #10765
Due to the specifics of ResizeObserver, it does not track changes to inline elements.  
For a simple solution, you can use inline-block. This applies to both v3 and v4.
I added a notification about this to the documentation.
> chore(demo): update information about tuiHighlight directive (#10765)

- projects/core/styles/components/textfield.less
> fix(core): use child combinator for all selectors inside non-encapsulated `Textfield` styles

- projects/core/directives/dropdown/dropdown-open.directive.ts
- projects/kit/components/input-number/step/input-number-step.component.ts
> chore(core): `DropdownOpen` ignore key events when there's no dropdown content

- projects/demo/src/modules/components/textfield/examples/5/index.ts
- projects/kit/components/input-number/input-number.directive.ts
- projects/legacy/components/input-number/input-number.component.ts
Relates:
* https://github.com/taiga-family/maskito/pull/2022
> refactor: replace deprecated params of `Number`-mask by new alternatives

- projects/demo-cypress/src/tests/slider/slider-with-ng-model.cy.ts
- projects/kit/components/slider/slider.component.ts
(use `0.5` playback speed)
https://github.com/user-attachments/assets/c01a3ed6-e320-42fc-a816-cc59573ca63c
`00:03`:
https://github.com/user-attachments/assets/40a91e7d-027c-43e8-ba00-323486524bb8
> fix(kit): `Range` has change detection problems with active state of thumb

- projects/demo/src/modules/components/block-status/examples/5/index.html
- projects/layout/components/block-status/block-status.style.less
> fix(addon-mobile): support block status without image

- projects/kit/components/input-number/input-number.component.ts
https://taiga-ui.dev/v3/components/input-number/API?precision=2&tuiTextfieldPostfix=руб
Impossible to enter decimal digits
> fix(kit): `InputNumber` rejects decimal part (even if `precision > 0`) if affixes include decimal pseudo separator

- projects/demo/src/modules/components/cell/examples/7/index.html
- projects/demo/src/modules/components/cell/examples/7/index.ts
- projects/layout/components/cell/cell.styles.less
Relates:
* https://github.com/taiga-family/taiga-ui/pull/10856/files#diff-8a26e7207cb79e383127969f7e7c47355702d5425cd5cd92c478407f97b2c616
> chore(layout): `Cell` inside `Select` has overflown last character

- projects/demo-playwright/tests/kit/input-files/input-files.pw.spec.ts
- projects/kit/components/files/file/file.component.ts
Uploading a file without an extension causes a period to be appended before the file's name. This fix gets rid of the period.
Fixes #10878
> fix(kit): get rid of dot before extension-less files

- projects/core/directives/hint/hint-hover.directive.ts
- projects/core/directives/hint/hint.component.ts
Previously, the complete handler of subscription was triggering `false`, which caused related hints to close prematurely.
This PR introduces a new close method to handle the case where a hint needs to be closed without notifying the parent.
Fixes #10492
> fix(core): fixed parent closing when nested hint is closed

- projects/core/components/dialog/dialogs.style.less
> fix(core): `Dialogs` fix long words wrapping

- projects/core/components/dialog/dialogs.style.less
> fix(core): `Dialogs` fix overlay scrolling out of viewport

- projects/addon-charts/components/arc-chart/arc-chart.template.html
> fix(addon-charts): `ArcChart` fix zoom in Safari

- projects/kit/components/calendar-range/calendar-range.component.ts
- projects/kit/components/calendar-range/test/calendar-range.component.spec.ts
changes the order from valueChange -> itemChange to itemChange -> valueChange
Fixes #9878
> fix(kit): calendar-range fire itemChange before valueChange

- projects/cdk/classes/control.ts
```ts
import { Component, Directive, effect, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { TuiControl } from '@taiga-ui/cdk';
import {
TuiTextfield,
TuiTextfieldDirective,
TuiWithTextfield,
} from '@taiga-ui/core';
@Directive({
standalone: true,
selector: 'input[myInput]',
hostDirectives: [TuiWithTextfield],
})
class MyControl extends TuiControl<object> {
private readonly textfield = inject(TuiTextfieldDirective);
onChangeEffect = effect(
() => {
const theOnlyEffectDepedency = this.textfield.value();
// Never changed but effect will be infinitely triggering
console.log({ theOnlyEffectDepedency });
this.onChange({ ref: 'object-with-new-ref-every-time' });
},
{ allowSignalWrites: true }
);
}
@Component({
standalone: true,
selector: 'app',
template: ` …
```
> fix(cdk): `TuiControl` should use `untracked` for signals inside `onChange`

- projects/addon-table/components/table/th/th.style.less
Allow aligning to the right when sortable th.
There is no possibility to align table header through css text-align inside component.
> fix(addon-table): `Th` allow aligning to the right when sortable

- projects/core/styles/components/textfield.less
Fixed: reduce the distance between top border and label by design
Before:
After:
> fix(core): `Textfield` label offset em to rem

- projects/kit/components/progress/progress-segmented/index.ts
- projects/kit/components/progress/progress-segmented/ng-package.json
```bash
projects/kit/components/progress
├── progress-bar # no index.ts & no ng-package.json
├── progress-circle # no index.ts & no ng-package.json
├── progress-label # no index.ts & no ng-package.json
├── progress-segmented
│   ├── index.ts # why???
│   ├── ng-package.json # why???
│   └──  progress-segmented.directive.ts
├── index.ts
├── progress.ts
└── ng-package.json
```
https://github.com/taiga-family/taiga-ui/blob/ca81b5cb599a509ea106cf50993f253cfad508c7/projects/kit/components/progress/index.ts#L8
> chore: remove redundant entry point

- projects/cdk/schematics/collection.json
> chore(schematics): remove unused schema for `migrateTuiLet` schematic

- projects/layout/components/form/form.directive.ts
- projects/layout/components/form/form.options.ts
- projects/layout/components/form/index.ts
Added default values ​​and a provider to override directive `tuiForm` parameters at a global or more local level. This way we can define the required size once and not specify it every time in the templates.
Fixes #11010
> feat(layout): `Form` add default options

- projects/i18n/languages/arabic/kit.ts
The main branch has broken `build`-job:
```
------------------------------------------------------------------------------
Building entry point '@taiga-ui/i18n/languages/arabic'
------------------------------------------------------------------------------
- Compiling with Angular sources in Ivy partial compilation mode.
✖ Compiling with Angular sources in Ivy partial compilation mode.
projects/i18n/languages/arabic/kit.ts:13:5 - error TS2739: Type '{ 'MM:SS': string; 'HH:MM': string; 'HH:MM AA': string; 'HH:MM:SS': string; 'HH:MM:SS AA': string; 'HH:MM:SS.MSS': string; 'HH:MM:SS.MSS AA': string; }' is missing the following properties from type '{ 'MM:SS': string; 'HH:MM': string; 'HH:MM AA': string; 'HH:MM:SS': string; 'HH:MM:SS AA': string; 'HH:MM:SS.MSS': string; 'HH:MM:SS.MSS AA': …
```
> chore(i18n): add missing time fillers for Arabic language

- projects/addon-doc/components/main/main.component.ts
- projects/addon-doc/components/main/main.style.less
- projects/addon-doc/components/main/main.template.html
- projects/addon-doc/tokens/doc-icons.ts
- projects/cdk/constants/used-icons.ts
- projects/demo/src/modules/app/app.config.ts
- projects/demo/src/modules/app/app.style.less
- projects/demo/src/modules/app/app.template.html
- projects/demo/used-icons.ts
Easily test functionality directly within the documentation
> feat(addon-doc): support for switching text direction in documentation

- projects/kit/components/pdf-viewer/pdf-viewer.style.less
> feat(kit): `PdfViewer` support safe-area top/bottom

- projects/kit/components/preview/preview.style.less
> feat(kit): `Preview` support safe-area top/bottom

- projects/core/components/textfield/textfield-multi/textfield-multi.template.html
- projects/core/components/textfield/textfield.component.ts
- projects/core/components/textfield/textfield.template.html
```html
<tui-textfield tuiChevron>
<input
tuiComboBox
[(ngModel)]="value"
(input)="search$.next($event.target.value)"
/>
<tui-data-list-wrapper
*tuiTextfieldDropdown
[items]="items$ | async"
/>
</tui-textfield>
```
https://taiga-ui.dev/components/combo-box#server-side-filtering
> feat(core): `Textfield` dispatches `(input)` event on cleaner click

- projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
- projects/core/components/dialog/dialog.style.less
- projects/demo/src/modules/components/dialog/examples/4/index.less
- projects/kit/components/floating-container/floating-container.less
Partially solved #10963 
1. **SheetDialog** bottom padding
2. **Dialog** close button padding (only in fullscreen & page)
3. **Dialog** example button bottom padding
4. **FloatingContainer** buttons bottom padding
> feat: improve safe-area support for WebView

- projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
Partially solved #10963 
**SheetDialog**
> feat(addon-mobile): `SheetDialog` improve safe-area support (for WebView)

- projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts
> refactor: add typesafe for runtime in `tui-dropdown-mobile`

- projects/core/components/textfield/index.ts
- projects/core/components/textfield/with-native-picker.directive.ts
- projects/kit/components/input-date-time/input-date-time.component.ts
- projects/kit/components/input-date/input-date.component.ts
- projects/kit/components/input-date/input-date.directive.ts
- projects/kit/components/input-month/input-month.component.ts
- projects/kit/components/input-month/input-month.directive.ts
- projects/kit/components/input-time/input-time.component.ts
- projects/kit/components/input-time/input-time.directive.ts
> fix(kit): `InputTime`, `InputDate`, `InputMonth` with native picker ignore initial form control value

- projects/demo-cypress/src/tests/textfield/textfield-form-reset.cy.ts
- projects/kit/components/input-date/input-date.directive.ts
> fix(kit): `InputDate` & `InputDateRange` fail to clear value on `formControl.reset()`

- projects/core/directives/dropdown/dropdown-position-sided.directive.ts
- projects/demo-playwright/tests/core/dropdown/dropdown.pw.spec.ts
tuiDropdownSided doesn't adjust its height when it hits the edge of the screen. Because of that, it should change its position when the actual dropdown height exceeds the available height — not when the minimum possible height exceeds it.
before: 
https://github.com/user-attachments/assets/0f40ef6e-22e5-494e-b571-55803428d21c
---
after: 
https://github.com/user-attachments/assets/39d577cb-4577-4f9f-a1ae-94931ef727c7
Fixes #11507
> fix(core): `DropdownSided` change position depending on height instead of min-height

- projects/demo/src/modules/app/search/index.ts
- projects/demo/src/modules/customization/dialogs/index.html
Currently, it's impossible to find the Dialogs page via search.
First, this change increases the number of visible search results to seven, which makes it possible for the Dialogs page to appear.
Second, it updates the titles of custom dialogs to lower their search ranking, so the main Dialogs page is prioritized.
---
Before:
After:
> chore(demo): improve dialog search

- projects/core/directives/dropdown/dropdown-selection.directive.ts
- projects/core/utils/dom/get-word-range.ts
- projects/demo-playwright/tests/kit/dropdown-selection/dropdown-selection.pw.spec.ts
- projects/demo/src/modules/directives/dropdown-selection/examples/2/index.html
- projects/kit/components/textarea/textarea.style.less
To fix the issue while maintaining compatibility with both the new and old textarea implementations, we now render the `ghost` inside the textarea's `ghost` element — if it exists.
Additionally, this PR fixes a bug where the dropdown wouldn’t appear after a newline character.
Fixes #11071 
Fixes #11286
> fix(core): `DropdownSelection` fix position inside new textarea

- projects/demo-playwright/tests/kit/input-number/input-number.pw.spec.ts
- projects/demo-playwright/tests/kit/input-slider/input-slider.pw.spec.ts
- projects/demo/src/modules/components/input-number/examples/9/index.html
- projects/demo/src/modules/components/input-number/examples/9/index.ts
- projects/demo/src/modules/components/input-number/index.html
- projects/demo/src/modules/components/input-number/index.ts
- projects/demo/src/modules/components/input-slider/examples/5/index.html
- projects/demo/src/modules/components/input-slider/examples/5/index.ts
- projects/demo/src/modules/components/input-slider/index.html
- projects/demo/src/modules/components/input-slider/index.ts
- projects/kit/components/input-number/index.ts
- projects/kit/components/input-number/input-number.directive.ts
- projects/kit/components/input-number/input-number.ts
- projects/kit/components/input-number/quantum.directive.ts
- projects/kit/components/input-slider/input-slider.directive.ts
This PR implements missing feature for refactored new controls.
Explore legacy controls:
* https://taiga-ui.dev/legacy/input-slider/API?max=100&quantum=10
* https://taiga-ui.dev/legacy/input-range/API?max=100&quantum=10
> feat(kit): `InputNumber` & `InputSlider` support `quantum` property

- projects/kit/components/files/file/file.style.less
> fix(kit): fixes file container size for prevent overflow extension of file

- projects/core/components/textfield/textfield-multi/textfield-multi.component.ts
- projects/core/components/textfield/textfield.component.ts
fixes https://github.com/taiga-family/taiga-ui/issues/11662
Problem
Textfield components throw an unhandled error when [showPicker()](vscode-file://vscode-app/c:/Users/anees/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) is called from cross-origin iframes (like StackBlitz examples):
Solution
Added try/catch blocks around [showPicker()](vscode-file://vscode-app/c:/Users/anees/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) calls in files:
```
textfield.component.ts
textfield.multicomponent.ts
```
The catch blocks include debug logging to help with troubleshooting while allowing the application to continue working normally.
✅ Result
✅ Fixes error when …
> fix(core): add `try/catch` around `showPicker()` to handle cross-origin iframe errors

- projects/kit/components/textarea/textarea.style.less
> fix(kit): `Textarea` increase style specificity for safari 15

- projects/core/components/textfield/textfield-multi/textfield-item.style.less
This pull request makes a small update to the styling of the `textfield-item` component to improve its text display behavior. Refer this issue TuiInputChip moves long values to a new string (https://github.com/taiga-family/taiga-ui/issues/11665)
* Changed the `white-space` property from `pre-wrap` to `nowrap` in `textfield-item.style.less`, causing text to remain on a single line and overflow with an ellipsis instead of wrapping.
> fix(styles): change white-space property to nowrap

- projects/kit/components/textarea/textarea.template.html
This pull request introduces a minor update to the `projects/kit/components/textarea/textarea.template.html` file. The change adds a click event handler to prevent the default behavior when the scroll controls are clicked.
refer this #11475 issue
> fix: prevent default click behavior on scroll controls in textarea

- projects/cdk/tokens/removed-element.ts
Use a regular Subject instead of a BehaviorSubject in TUI_REMOVED_ELEMENT so that the last removed element is not stored on the heap.
> feat(cdk): use `Subject` in `TUI_REMOVED_ELEMENT` instead of `BehaviorSubject`

- projects/core/directives/dropdown/dropdown-context.directive.ts
Remove host-listeners from `TuiDropdownContext` that work outside the zone.
Zoneless host-listeners still force marking `lView` as dirty, and do this on every click on absolutely any place. On the next tick, all this will be processed, and in most cases there will be no need for this.
Replace host-listeners with subscription via RxJS using `tuiZonefree`, which will not lead to marking `lView` as dirty.
> feat(core): migrate from Angular events to observables in `DropdownContext`

- projects/core/components/loader/loader.style.less
> chore(core): `Loader` remove extra space around icon

- projects/demo-playwright/tests/kit/input-slider/input-slider.pw.spec.ts
- projects/kit/components/input-slider/input-slider.directive.ts
Update according to the latest design specs
Partially solves #11826
> feat(kit): `InputSlider` hides slider for non-interactive state

- projects/core/styles/theme/appearance/textfield.less
> fix(core): ensure box-shadow works in Safari 26 for `tuiAppearance`

- projects/demo-playwright/tests/performance/scrollbar.stress.pw.spec.ts
> chore(demo-playwright): scrollbar.stress eslint-disable playwright/no-conditional-in-test
