taiga-family/taiga-ui

projects/testing/setup-jest/index.ts
=> ci: force resolve `jest` types in IDEA

projects/demo/src/modules/components/input-time/examples/6/index.html, projects/demo/src/modules/components/input-time/examples/6/index.ts, projects/demo/src/modules/components/input-time/input-time.component.ts, projects/demo/src/modules/components/input-time/input-time.module.ts, projects/demo/src/modules/components/input-time/input-time.template.html, projects/kit/components/input-time/index.ts, projects/kit/components/input-time/input-time-options.ts, projects/kit/components/input-time/input-time.component.ts, projects/kit/components/input-time/input-time.directive.ts, projects/kit/components/input-time/input-time.module.ts, projects/kit/components/input-time/input-time.template.html, projects/kit/components/input-time/native-time/native-time.component.ts, projects/kit/components/input-time/native-time/native-time.style.less
=> feat(kit): `InputTime` add ability to use native picker on mobile

package.json
=> ci: skip linting by eslint for `less,json` files

projects/demo-integrations/cypress/support/commands/snapshot.ts
=> ci: change `diffDirection`

.github/screenshot-bot.config.toml
=> chore: update screenshot-bot.config.toml

projects/demo/src/modules/pipes/field-error/examples/2/index.ts, projects/kit/pipes/field-error/field-error-pipe.ts
=> feat(kit): catch `Observable` instead of `PolymorpheusPrimitive` from `PolymorpheusHandler` in `fieldError`

scripts/compile-icons.ts
=> ci: reuse `projectPath` for include svg files

.github/actions/nodejs/action.yml
=> ci: pin node.js

projects/demo/src/modules/components/card/examples/3/index.less, projects/demo/src/modules/components/tag/examples/3/index.html, projects/demo/src/modules/components/tag/examples/3/index.ts, projects/demo/src/modules/components/tag/tag.component.ts, projects/demo/src/modules/components/tag/tag.template.html, projects/kit/components/tag/tag.component.ts, projects/kit/components/tag/tag.style.less
=> feat(kit): `Tag` add button selector

projects/demo/src/modules/components/input-card-grouped/examples/5/index.html, projects/demo/src/modules/components/input-card-grouped/examples/5/index.ts, projects/demo/src/modules/components/input-card-grouped/input-card-grouped.component.ts, projects/demo/src/modules/components/input-card-grouped/input-card-grouped.module.ts, projects/demo/src/modules/components/input-card-grouped/input-card-grouped.template.html
=> chore(demo): `InputCardGrouped` add example with custom labels

projects/cdk/schematics/constants/file-globs.ts, projects/cdk/schematics/ng-add/constants/modules.ts, projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts, projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts, projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts, projects/cdk/schematics/utils/add-import-to-component.ts, projects/cdk/schematics/utils/get-component-from-identifier.ts, projects/cdk/schematics/utils/get-named-import-references.ts, projects/cdk/schematics/utils/get-standalone-bootstrap-function.ts, projects/cdk/schematics/utils/push-to-array-property.ts
=> feat(cdk): `ng-add` support apps bootstrapped using a standalone component

projects/demo/src/modules/markup/icons/icons-group/icons-group.template.html, projects/demo/src/modules/markup/icons/icons.component.ts, projects/demo/src/modules/markup/icons/icons.style.less, projects/demo/src/modules/markup/icons/icons.template.html
=> chore(demo): improve icons markup

projects/addon-editor/components/edit-link/edit-link.component.ts, projects/addon-editor/components/edit-link/index.ts, projects/addon-editor/components/edit-link/test/edit-link-parse.spec.ts, projects/addon-editor/components/edit-link/utils/edit-link-parse-url.ts, projects/addon-editor/constants/default-link-options-handler.ts, projects/cdk/utils/miscellaneous/index.ts, projects/cdk/utils/miscellaneous/is-valid-url.ts, projects/cdk/utils/miscellaneous/test/is-valid-url.spec.ts
Closes https://github.com/Tinkoff/taiga-ui/issues/4264
https://user-images.githubusercontent.com/12021443/233443162-8a780ef5-c58a-43bb-b76f-78162ae859c8.mov
=> feat(addon-editor): support any protocols in `link` component

projects/kit/components/combo-box/combo-box.component.ts
=> fix(kit): `Combobox` fix immediate reset after value change

projects/demo/src/modules/components/avatar/avatar.component.ts, projects/demo/src/modules/components/avatar/avatar.module.ts, projects/demo/src/modules/components/avatar/avatar.template.html, projects/demo/src/modules/components/avatar/examples/6/index.html, projects/demo/src/modules/components/avatar/examples/6/index.less, projects/demo/src/modules/components/avatar/examples/6/index.ts, projects/kit/components/avatar/avatar.component.ts, projects/kit/components/avatar/avatar.template.html
=> feat(kit): support `fallback` for `avatar` when img not found by `avatarUrl`

projects/addon-doc/index.ts
=> chore: forgot add `language` secondary entry point

projects/demo/webpack.config.ts
=> chore: remove redundant logs

projects/core/services/breakpoint.service.ts, projects/demo/src/modules/app/pages.ts
=> fix(core): expose `TuiBreakpointMediaKey`

projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts, projects/addon-commerce/components/input-card-grouped/input-card-grouped.providers.ts
=> feat(addon-commerce): add `TUI_INPUT_CARD_GROUPED_OPTIONS` token

README.md
=> chore: try to fix readme table

.bundlemonrc.json, .github/workflows/bundle-size-tracking.yml
=> ci: include `styles.[hash].css` in bundle size tracking

projects/kit/components/input-date-time/input-date-time.component.ts
=> fix(kit): `InputDateTime` fix value setting when using valueTransformer

projects/addon-commerce/components/input-card-grouped/input-card-grouped.module.ts, projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
=> fix(addon-commerce): `InputCardGrouped` fix incorrect initial value display

.github/actions/auto-push/action.yml, .github/actions/nodejs/action.yml, .github/workflows/auto-rebase.yml, .github/workflows/auto-remove-label.yml, .github/workflows/auto-update-deps-renovate.yml, .github/workflows/auto-update-icons.yml, .github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-dev.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml, renovate.json
=> ci: decompose renovate.json by some groups

.github/workflows/snapshots.yml
=> ci: improve logs

.github/workflows/e2e.yml
=> ci: cleanup `e2e.yml`

.github/workflows/publish.yml, scripts/publish.ts
=> ci: skip announce when every packages are already published

projects/addon-commerce/components/input-card/test/input-card.component.spec.ts, projects/addon-commerce/utils/test/get-currency-symbol.spec.ts
=> test: improve `addon-commerce` specs

projects/addon-preview/components/preview-dialog/preview-dialog.service.ts, projects/core/components/root/root.component.ts, projects/demo/src/modules/components/preview/examples/4/index.html, projects/demo/src/modules/components/preview/examples/4/index.less, projects/demo/src/modules/components/preview/examples/4/index.ts, projects/demo/src/modules/components/preview/examples/import/component.md, projects/demo/src/modules/components/preview/preview.component.ts, projects/demo/src/modules/components/preview/preview.module.ts, projects/demo/src/modules/components/preview/preview.template.html
=> fix(core): `Preview` add missed providers, `Root` fix display extra scrollbar

projects/addon-editor/extensions/iframe-editor/iframe-editor.extension.ts, projects/addon-editor/extensions/image-editor/image-editor.extension.ts, projects/addon-editor/extensions/tiptap-node-view/node-view-render.ts, projects/demo/src/modules/app/stackblitz/project-files/configs.md
=> chore(addon-editor): class constructor `NodeView` cannot be invoked without `new`

projects/addon-commerce/components/input-card/abstract-input-card.ts
=> chore: fix tests

projects/core/components/dialog/dialog.style.less, projects/core/components/dialog/dialog.template.html, projects/demo-integrations/cypress/tests/core/dialogs/dialogs.cy.ts
=> fix(core): `Dialog` fix closing fullscreen dismissible dialog

projects/addon-editor/components/edit-link/utils/edit-link-parse-url.ts
=> refactor(addon-editor): post review

projects/demo/src/modules/components/avatar/examples/1/index.html, projects/eslint-plugin/rules/no-assert-without-ng-dev-mode.js, scripts/cspell/common.json
=> refactor: post review

projects/core/styles/taiga-ui-fonts.less
=> fix(core): skip import if cannot load fonts from `googleapis.com`

projects/core/components/svg/svg-options.ts
```
Assertion failed: tuiIconFrameLargeOutline is deprecated, use undefined/Large instead
```
=> fix(core): improve message about deprecated icons

projects/kit/components/multi-select/multi-select.component.ts
=> fix(kit): `Multiselect` update dropdown on search

projects/demo/src/modules/components/block-status/block-status.template.html, projects/demo/src/modules/components/block-status/examples/import/insert-template.md
=> chore(demo): `BlockStatus` add tuiSlot to api-page

projects/kit/components/tag/tag.style.less
=> feat(kit): set dark text color for autocolored tags regardless of theme

projects/demo/src/modules/components/input-date-range/examples/5/index.html, projects/demo/src/modules/components/input-date-range/examples/5/index.ts, projects/demo/src/modules/components/input-date-range/input-date-range.component.ts, projects/demo/src/modules/components/input-date-range/input-date-range.module.ts, projects/demo/src/modules/components/input-date-range/input-date-range.template.html, projects/kit/classes/day-range-period.ts, projects/kit/components/input-date-range/input-date-range.component.ts, projects/kit/components/input-date-range/input-date-range.style.less, projects/kit/components/input-date-range/input-date-range.template.html
=> feat(kit): `InputDateRange` allow to use custom value content when using period

projects/addon-commerce/components/input-card/input-card.component.ts, projects/addon-commerce/components/input-card/input-card.module.ts, projects/addon-commerce/components/input-card/input-card.template.html, projects/addon-commerce/components/input-card/test/input-card.component.spec.ts, projects/addon-commerce/package.json
=> feat(addon-commerce): `InputCard` uses `Maskito` instead of legacy `text-mask`

projects/cdk/utils/dom/get-element-obscurers.ts, projects/core/components/hosted-dropdown/hosted-dropdown.template.html
=> fix(core): `Dropdown` fix initial open state

.github/workflows/test.yml, projects/cdk/components/dropdown-host/test/dropdown-portal.service.spec.ts, projects/cdk/date-time/test/day.spec.ts, projects/cdk/observables/test/control-value.spec.ts, projects/testing/mocks/index.ts, projects/testing/mocks/switch-ng-dev-mode.ts, setup-jest.ts
=> ci: emulate production mode for jest

projects/demo/src/modules/components/tag/examples/6/index.html, projects/demo/src/modules/components/tag/examples/6/index.ts, projects/demo/src/modules/components/tag/tag.component.ts, projects/demo/src/modules/components/tag/tag.module.ts, projects/demo/src/modules/components/tag/tag.template.html, projects/kit/components/tag/tag.style.less
=> fix(kit): `Tag` remove mixin messing with background

.github/workflows/auto-dependency-review.yml
=> ci: dependency review by Github

.github/workflows/auto-dependency-review.yml
=> ci: support Apache 2.0 License

projects/addon-table/directives/table-filters/table-filter.directive.ts
=> fix(addon-table): `TableFilters` fix registering when using structural directives

.github/workflows/test.yml, jest.config.ts
Closes https://github.com/Tinkoff/taiga-ui/issues/4352
=> ci: invalid coverage

projects/demo/src/modules/components/group/examples/4/index.html, projects/demo/src/modules/components/group/examples/4/index.less, projects/demo/src/modules/components/group/examples/4/index.ts, projects/demo/src/modules/components/group/group.component.ts, projects/kit/components/checkbox-block/checkbox-block.style.less, projects/kit/components/checkbox-block/checkbox-block.template.html, projects/kit/components/radio-block/radio-block.template.html
=> fix(kit): `RadioBlock`, `CheckboxBlock` properly align in `Group`

projects/cdk/abstract/control.ts
=> fix(core): `Control` refresh subscription after control change

projects/addon-editor/components/editor-socket/styles/list.less, scripts/cspell/web-keywords.json
=> fix(addon-editor): vertical alignment of content in a list

projects/cdk/abstract/tests/abstract-control-no-control.spec.ts, projects/cdk/abstract/tests/abstract-control-with-control.spec.ts, projects/cdk/abstract/tests/abstract-tui-controller.spec.ts, projects/cdk/abstract/tests/as-control-util.spec.ts, projects/cdk/decorators/test/debounce.spec.ts, projects/cdk/directives/active-zone/tests/active-zone.directive.spec.ts, projects/cdk/directives/checked/checked.directive.ts, projects/cdk/directives/checked/tests/checked.directive.spec.ts, projects/cdk/utils/calendar/tests/date-clamp.spec.ts, projects/cdk/utils/dom/is-element-editable.ts, projects/cdk/utils/dom/test/can-scroll.spec.ts, projects/cdk/utils/dom/test/contains-or-after.spec.ts, projects/cdk/utils/dom/test/element-checks.spec.ts, projects/cdk/utils/dom/test/get-element-obscurers.spec.ts, projects/cdk/utils/dom/test/get-selected-text.spec.ts, projects/cdk/utils/dom/test/inside-iframe.spec.ts, projects/cdk/utils/dom/test/is-element-editable.spec.ts, projects/cdk/utils/dom/test/point-to-client-rect.spec.ts, projects/cdk/utils/focus/tests/set-native-mouse-focused.spec.ts, projects/cdk/utils/miscellaneous/test/default-sort.spec.ts, projects/cdk/utils/miscellaneous/test/object-from-entries.spec.ts
Bump coverage from `61%` to `70%`
=> test: improve cdk coverage

projects/kit/components/badge/badge.component.ts, projects/kit/components/badged-content/badged-content.component.ts, projects/kit/components/badged-content/badged-content.template.html
=> fix(kit): downgrade type of value in badge

projects/demo-integrations/cypress/tests/core/dialogs/dialogs.cy.ts, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/prompt/examples/1/index.html, projects/demo/src/modules/components/prompt/examples/1/index.ts, projects/demo/src/modules/components/prompt/examples/import/import-module.md, projects/demo/src/modules/components/prompt/examples/import/service.md, projects/demo/src/modules/components/prompt/prompt.component.ts, projects/demo/src/modules/components/prompt/prompt.module.ts, projects/demo/src/modules/components/prompt/prompt.template.html, projects/kit/components/prompt/prompt.component.ts, projects/kit/components/prompt/prompt.style.less
=> fix(kit): `Prompt` wrap buttons to the new line if they do not fit

CHANGELOG.md
=> chore: fix spelling in CHANGELOG.md

projects/demo/src/modules/components/data-list-wrapper/data-list-wrapper.module.ts, projects/demo/src/modules/components/data-list-wrapper/examples/2/index.html
=> chore(demo): fix example field type

.github/PULL_REQUEST_TEMPLATE.md
=> ci: remove redundant section about breaking changes

.github/workflows/snapshots.yml
=> ci: fix bad idea

projects/addon-editor/components/editor/editor.component.html, projects/addon-editor/components/editor/editor.component.less, projects/addon-editor/components/editor/editor.component.ts, projects/demo/src/modules/components/abstract/control.ts, projects/demo/src/modules/components/editor/starter/editor-starter.template.html
Closes #4426
https://github.com/Tinkoff/taiga-ui/assets/12021443/7871ba82-b183-4ad9-92fb-f461b8611467
=> feat(addon-editor): support focus on editable area

.github/actions/nodejs/action.yml, .github/actions/variables/action.yml, .github/workflows/auto-add-to-project.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-dependency-review.yml, .github/workflows/auto-label.yml, .github/workflows/auto-rebase.yml, .github/workflows/auto-remove-label.yml, .github/workflows/auto-update-deps-renovate.yml, .github/workflows/auto-update-icons.yml, .github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-dev.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml
=> ci: provide variable action

projects/addon-doc/components/code/tests/code.component.spec.ts, projects/addon-doc/utils/parse-code-block.ts, projects/addon-doc/utils/test/try-parse-markdown.spec.ts
=> feat(addon-doc): remove redundant empty spaces after parse markdown

.github/PULL_REQUEST_TEMPLATE.md
=> ci: add tests section in pull request template

projects/addon-doc/utils/test/transliterate-keyboard-layout.spec.ts
=> test: add spec for `tuiTransliterateKeyboardLayout`

projects/addon-doc/utils/test/generate-routes.spec.ts
=> test: add spec for `tuiGenerateRoutes`

projects/addon-doc/utils/test/inspect.spec.ts
=> test: add spec for `tuiInspectAny`

projects/addon-doc/components/page/tests/page.component.spec.ts
=> test: add spec for `TuiDocPageComponent`

.github/actions/nodejs/action.yml, .github/actions/variables/action.yml
=> ci: `CYPRESS_CACHE_FOLDER` should be important inside node.js action

projects/addon-doc/components/navigation/navigation.style.less
=> fix(addon-doc): increasing css cascade priority for active state

.github/actions/variables/action.yml, README.md
=> ci: forgot export `$REPO` variable

projects/addon-doc/components/main/main.style.less, projects/cdk/utils/focus/get-native-focused.ts, projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/core/components/primitive-textfield/primitive-textfield.template.html, projects/core/components/tooltip/tooltip.style.less, projects/core/directives/textfield-controller/textfield-options.ts, projects/demo/src/modules/components/primitive-textfield/examples/2/index.html, projects/demo/src/modules/components/primitive-textfield/examples/2/index.ts, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/input-tag/input-tag.template.html, projects/kit/components/text-area/text-area.component.ts, projects/kit/components/text-area/text-area.template.html
=> feat(core): `Textfield` allow showing hints for disabled control

projects/kit/components/input-tag/input-tag.style.less
=> fix(kit): `InputTag` fix vertical jumps on multi line size="m" and label inside

projects/kit/components/input-tag/input-tag.style.less
=> fix(kit): `MultiSelect` properly react to height variables change

projects/demo/src/modules/components/color-picker/color-picker.component.ts, projects/demo/src/modules/components/color-picker/color-picker.module.ts, projects/demo/src/modules/components/color-picker/color-picker.template.html, projects/demo/src/modules/components/color-picker/examples/4/index.html, projects/demo/src/modules/components/color-picker/examples/4/index.less, projects/demo/src/modules/components/color-picker/examples/4/index.ts, projects/demo/src/styles.less
=> chore: add native InputColor example

projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less, projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/core/components/primitive-textfield/textfield/textfield.style.less, projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less, projects/core/components/primitive-textfield/value-decoration/value-decoration.template.html, projects/core/styles/mixins/textfield.less, projects/core/styles/mixins/textfield.scss, projects/kit/components/input-tag/input-tag.style.less
=> fix(kit): `MultiSelect` fix placeholder in dark mode

projects/i18n/languages/russian/addon-editor.ts
=> fix(addon-editor): fix typo in the description of toolbar tool `justifyCenter`

projects/demo/src/modules/components/select/examples/11/index.html, projects/demo/src/modules/components/select/examples/11/index.ts, projects/kit/abstract/abstract-native-select.ts, projects/kit/components/select/native-select/native-select-group.component.ts, projects/kit/components/select/native-select/native-select-group.template.html, projects/kit/components/select/native-select/native-select.component.ts, projects/kit/components/select/native-select/native-select.template.html, projects/kit/components/select/select.directive.ts, projects/kit/components/select/select.module.ts
=> feat(kit): `Select` add ability to use objects in native select

projects/core/types/point.ts
=> chore(core): remove `TuiPoint` type description

projects/addon-mobile/components/pull-to-refresh/index.ts, projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.component.ts, projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.style.less, projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.template.html, projects/addon-mobile/components/pull-to-refresh/loader-ios/loader-ios.component.ts, projects/addon-mobile/components/pull-to-refresh/loader-ios/loader-ios.style.less, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.module.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.providers.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.service.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.style.less, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.template.html, projects/addon-mobile/index.ts, projects/addon-mobile/tokens/index.ts, projects/addon-mobile/tokens/loaded.ts, projects/addon-mobile/tokens/ng-package.json, projects/demo/src/modules/components/pull-to-refresh/examples/1/index.ts, projects/demo/src/modules/components/pull-to-refresh/examples/2/index.ts, projects/demo/src/modules/components/pull-to-refresh/pull-to-refresh.template.html
=> feat(addon-mobile): `PullToRefresh` allow customization

projects/addon-charts/components/bar-chart/bar-chart.component.ts
=> fix(addon-charts): `BarChart` fix hover effect

projects/kit/components/input-number/input-number.component.ts
=> fix(kit): `InputNumber` fix cutting by min value

projects/kit/components/line-clamp/line-clamp.component.ts
=> fix(kit): `LineClamp` fix `overflownChange` false positives

projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts, projects/core/components/scroll-controls/scroll-controls.component.ts, projects/core/components/scroll-controls/scrollbar.directive.ts, projects/core/tokens/scroll-ref.ts
=> fix(core): `TUI_SCROLL_REF` fallback to `documentElement`

projects/addon-mobile/components/tab-bar/tab-bar-item.component.ts, projects/addon-mobile/components/tab-bar/tab-bar-item.style.less, projects/addon-mobile/directives/sidebar/sidebar.component.ts, projects/addon-tablebars/components/table-bars-host/table-bars-host.component.ts, projects/cdk/services/parents-scroll.service.ts, projects/cdk/tokens/removed-element.ts, projects/core/animations/animations.ts, projects/core/components/alert/alert.component.ts, projects/core/components/error/error.component.ts, projects/core/components/scroll-controls/scroll-controls.component.ts, projects/core/directives/dropdown/dropdown.component.ts, projects/core/directives/dropdown/dropdown.directive.ts, projects/core/directives/hint/hint.component.ts, projects/core/enums/dropdown-animation.ts, projects/core/services/position.service.ts, projects/core/tokens/animation-options.ts, projects/kit/components/pdf-viewer/pdf-viewer.component.ts, projects/kit/components/push/push-alert.component.ts, projects/kit/components/radio/radio.component.ts
=> fix(core): `PositionService` eliminate memory leak

projects/addon-mobile/components/sheet/sheet.service.ts
=> fix(addon-mobile): `Sheet` remove focus from under sheet with overlay

projects/kit/components/tabs/tab/tab.style.less, projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less
=> fix(kit): `Tabs` align dropdown design with datalist

projects/core/utils/format/format-phone.ts, projects/demo-integrations/cypress/support/constants/index.ts, projects/demo-integrations/cypress/support/constants/real-events-support.ts, projects/demo-integrations/cypress/tests/kit/input-date-time/input-date-time.cy.ts, projects/demo-integrations/cypress/tests/kit/input-phone/input-phone.cy.ts, projects/kit/components/input-phone/input-phone.component.ts, projects/kit/components/input-phone/input-phone.directive.ts, projects/kit/components/input-phone/input-phone.module.ts, projects/kit/components/input-phone/input-phone.template.html, projects/kit/components/input-phone/test/complete-phone-insertion-preprocessor.spec.ts, projects/kit/components/input-phone/test/input-phone.component.spec.ts, projects/kit/components/input-phone/utils/complete-phone-insertion-preprocessor.ts, projects/kit/components/input-phone/utils/create-phone-mask-expression.ts, projects/kit/components/input-phone/utils/index.ts, scripts/cspell/software.json
=> feat(kit): `InputPhone` uses `Maskito` instead of legacy `text-mask`

projects/kit/components/progress/progress-circle/progress-circle.style.less
=> feat(kit): `ProgressCircle` design improvements

SECURITY.md
=> chore: update `Taiga UI` and `Angular` version compatibility matrix in `SECURITY.md`

projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts
=> fix(addon-editor): prevent paste redundant break line

projects/addon-editor/components/toolbar/toolbar.component.ts
=> fix(addon-editor): immediately unsubscribe streams when toolbar is destroyed

scripts/cspell/angular.json, scripts/eslint/off.js
=> chore: ignore redundant rule

.github/actions/nodejs/action.yml, jest.config.ts, package-lock.json, projects/testing/package.json, projects/testing/setup-jest/index.ts
=> fix(testing): support node.js 18.16, jest 26+ ships jsdom out of the box

projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts, projects/core/components/scroll-controls/scroll-controls.component.ts, projects/core/components/scroll-controls/scrollbar.directive.ts, projects/core/tokens/scroll-ref.ts
=> fix(core): `TUI_SCROLL_REF` fallback to documentElement

projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.style.less, projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.template.html, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.module.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.service.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.style.less, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.template.html, projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts, projects/cdk/observables/index.ts, projects/cdk/observables/scroll-from.ts, projects/core/components/scroll-controls/scrollbar.directive.ts, projects/demo/src/modules/components/pull-to-refresh/examples/1/index.html, projects/demo/src/modules/components/pull-to-refresh/examples/2/index.html, projects/demo/src/modules/components/pull-to-refresh/pull-to-refresh.component.ts, projects/demo/src/modules/components/pull-to-refresh/pull-to-refresh.module.ts, projects/demo/src/modules/components/pull-to-refresh/pull-to-refresh.style.less, projects/demo/src/modules/components/pull-to-refresh/pull-to-refresh.template.html
cherry-pick #4571
Closes #3979
=> feat(addon-mobile): `PullToRefresh` use `TUI_SCROLL_REF`

projects/cdk/schematics/ng-update/steps/replace-const.ts, projects/cdk/schematics/ng-update/v3-30/index.ts, projects/cdk/schematics/ng-update/v3-30/steps/replace-imports.ts
=> fix(cdk): fix icons migration, improve performance

projects/addon-editor/extensions/default-editor-extensions.ts
=> feat(addon-editor): support all heading levels by default

projects/kit/components/input-count/input-count.component.ts, projects/kit/components/input-count/input-count.module.ts, projects/kit/components/input-count/input-count.template.html
=> refactor(kit): drop redundant code inside `InputCount`

projects/demo-integrations/cypress/support/helpers/demo-paths.ts, projects/demo-integrations/cypress/tests/demo/demo.cy.ts
=> ci: add timeout for icons page

projects/demo-integrations/cypress/tests/addon-editor/editor-api.cy.ts, projects/demo/src/modules/components/editor/images/resizable/examples/1/index.html
=> chore: small refactor for PR #4605

package-lock.json, projects/kit/package.json
=> chore: revert maskito

projects/cdk/components/alert-host/alert-host.component.ts, projects/cdk/components/alert-host/alert-host.template.html
=> fix(cdk): using trackBy for re-order animations

projects/addon-editor/components/edit-link/edit-link.component.ts
=> fix(addon-editor): prevent paste `undefined` in url

projects/kit/components/checkbox-block/checkbox-block.style.less
=> fix(kit): pack items around the center in checkbox

projects/addon-editor/components/edit-link/edit-link.template.html
=> feat(addon-editor): use `icon` for preview type of links in edit mode

projects/core/utils/format/format-number.ts
=> fix(core): `NumberFormat` fix assertion warning

projects/core/components/data-list/data-list.style.less, projects/demo-integrations/cypress/tests/kit/multi-select/multi-select.cy.ts, projects/demo/src/modules/components/multi-select/examples/5/index.html, projects/kit/components/multi-select/multi-select-group/multi-select-group.component.ts, projects/kit/components/multi-select/multi-select-group/multi-select-group.style.less
=> fix(kit): `MultiSelectGroup` fix padding when used without label

.cspell.json, scripts/cspell/ignore.json
=> ci: ignore CHANGELOG in cspell

projects/addon-commerce/components/input-card-grouped/test/input-card-grouped.component.spec.ts, projects/addon-editor/components/editor/editor.component.ts, projects/cdk/directives/auto-focus/autofocus.directive.ts, projects/cdk/directives/auto-focus/autofocus.options.ts, projects/cdk/directives/auto-focus/handlers/abstract.handler.ts, projects/cdk/directives/auto-focus/handlers/ios.handler.ts, projects/core/tokens/animations-duration.ts, projects/demo/src/modules/components/editor/starter/editor-starter.module.ts, projects/demo/src/modules/components/editor/starter/editor-starter.template.html, projects/demo/src/modules/directives/auto-focus/auto-focus.component.ts, projects/demo/src/modules/directives/auto-focus/auto-focus.template.html, projects/demo/src/modules/directives/auto-focus/examples/import/insert-component.md
=> feat(cdk): support `TUI_AUTOFOCUS_OPTIONS`

projects/demo/src/index.html
https://www.cdnplanet.com/blog/faster-google-webfonts-preconnect
=> chore(demo): preloading Google Fonts

projects/demo/src/modules/app/app.providers.ts, projects/demo/src/modules/components/color-picker/color-picker.template.html
=> docs: color picker documentation page returns 404

projects/addon-doc/components/navigation/navigation.component.ts, projects/addon-doc/components/navigation/navigation.template.html, projects/addon-doc/interfaces/page.ts
=> feat(addon-doc): support `fragment` in navigation links

projects/kit/components/multi-select/multi-select-group/multi-select-group.style.less
=> fix(kit): `MultiSelectGroup` fix label alignment

.github/actions/variables/action.yml, .github/screenshot-bot.config.toml, .github/workflows/e2e-summary.yml, .github/workflows/e2e.yml
=> ci: use summary report for between playwright and cypress jobs

.github/workflows/auto-cleanup-caches.yml
=> ci: force deleting cache entries by branch

projects/demo/src/modules/components/abstract/inherited-documentation/inherited-documentation.component.ts, projects/demo/src/modules/components/abstract/inherited-documentation/inherited-documentation.template.html, projects/demo/src/modules/components/checkbox-block/checkbox-block.template.html, projects/demo/src/modules/components/checkbox-labeled/checkbox-labeled.template.html, projects/demo/src/modules/components/checkbox/checkbox.template.html, projects/demo/src/modules/components/radio-block/radio-block.template.html, projects/demo/src/modules/components/radio-labeled/radio-labeled.template.html, projects/demo/src/modules/components/radio-list/radio-list.template.html, projects/demo/src/modules/components/radio/radio.template.html
=> docs: hide unnecessary block for `Radio` and `Checkbox` (#4691)

.github/actions/nodejs/action.yml
=> ci: do not check cypress in main branch

projects/kit/components/progress/progress-circle/progress-circle.component.ts, projects/kit/components/progress/progress-circle/progress-circle.style.less, projects/kit/components/progress/progress-circle/progress-circle.template.html
=> fix(kit): `ProgressCircle` fix initial animation

projects/addon-commerce/enums/currency-code.ts, projects/addon-commerce/enums/currency.ts, projects/cdk/enums/day-of-week.ts, projects/cdk/enums/month-number.ts, projects/cdk/observables/drag-and-drop-from.ts, projects/core/components/expand/expand.component.ts, projects/core/enums/appearance.ts, projects/core/enums/dropdown-animation.ts, projects/core/enums/interactive-state.ts, projects/core/enums/notification.ts, projects/core/enums/range-state.ts
=> refactor: switch from const enums to regular enums

projects/core/components/dialog/dialog.style.less
https://taiga-ui.dev/components/dialog#prompt
https://github.com/Tinkoff/taiga-ui/assets/12021443/ad30837b-90ed-41c1-9a0d-5afa70bccdc4
=> feat(cdk): do not overlap close buttons in nested dialogs

projects/kit/components/progress/progress-circle/progress-circle.component.ts, projects/kit/components/progress/progress-circle/progress-circle.style.less, projects/kit/components/progress/progress-circle/progress-circle.template.html
cherry-pick https://github.com/Tinkoff/taiga-ui/pull/4682
Closes https://github.com/Tinkoff/taiga-ui/issues/4511
=> fix(kit): ProgressCircle fix initial animation

projects/addon-editor/components/editor/editor.component.less
=> fix(addon-editor): fix distance between toolbar and content without label

projects/core/components/root/root.component.ts, projects/demo/src/modules/components/input-month/examples/3/index.html, projects/demo/src/modules/components/input-month/examples/3/index.ts, projects/demo/src/modules/components/input-month/input-month.component.ts, projects/demo/src/modules/components/input-month/input-month.module.ts, projects/demo/src/modules/components/input-month/input-month.template.html, projects/kit/components/input-month/input-month.component.ts, projects/kit/components/input-month/input-month.module.ts, projects/kit/components/input-month/input-month.style.less, projects/kit/components/input-month/input-month.template.html
=> feat(kit): `InputMonth` add ability to use native picker on mobile

projects/demo/src/modules/components/input-month/examples/3/index.html, projects/demo/src/modules/components/input-month/examples/3/index.ts, projects/kit/components/input-month/input-month.component.ts, projects/kit/components/input-month/input-month.template.html
=> chore: add min/max

projects/demo/src/modules/components/select/examples/9/account/my-account.component.less, projects/kit/components/data-list-wrapper/data-list-wrapper.style.less
=> fix(kit): `DataListWrapper` extend content to full width

default.json
=> ci: small refactor `default.json`

projects/addon-mobile/directives/mobile-tabs/mobile-tabs.style.less
=> fix(addon-mobile): `MobileTabs` update iOS design

scripts/cspell/ci-cd.json
=> ci: cspell fix

default.json
=> ci: revert

projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less, projects/core/styles/mixins/textfield.less, projects/core/styles/theme/variables.less, projects/demo/src/modules/markup/typography/typography.template.html, projects/styles/markup/tui-list.less
=> fix(core): `Textfield` fix label font size

.github/actions/variables/action.yml
=> ci: fix e2e cache key

projects/demo/src/modules/components/abstract/textfield-controller-documentation/textfield-controller-documentation.template.html, projects/demo/src/modules/directives/textfield-controller/textfield-controller.template.html, projects/demo/src/modules/icons/icons-mapping/icons-mapping.template.html, projects/demo/src/modules/icons/icons.template.html
=> chore: fix links

projects/addon-editor/directives/tiptap-editor/tiptap-editor.service.ts, projects/addon-editor/extensions/starter-kit/starter-kit.ts, projects/demo-integrations/cypress/tests/addon-editor/editor-toolbar.cy.ts, projects/demo/src/modules/components/editor/font/examples/3/font-size-tool/font-size-tool.component.ts
Closes #4293 
Closes #4290 
Closes #4602
=> fix(addon-editor): prevent erasing history on empty value

projects/demo/src/modules/components/editor/starter/editor-starter.component.ts, projects/demo/src/modules/components/editor/starter/editor-starter.template.html
=> ci: skip flaky e2e test

projects/core/directives/dropdown/dropdown.directive.ts
=> fix(core): `Dropdown` fix cyclic freeze

projects/demo/src/main.browser.ts
=> chore(demo): immediate bootstrap because it does not respect for SSR in Angular 12+

projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts
=> fix(addon-mobile): `MobileCalendar` fix initial view

projects/demo/src/modules/components/multi-select/examples/10/index.html, projects/demo/src/modules/components/multi-select/examples/10/index.ts, projects/kit/components/multi-select/multi-select.component.ts, projects/kit/components/multi-select/multi-select.directive.ts, projects/kit/components/multi-select/multi-select.module.ts, projects/kit/components/multi-select/native-multi-select/native-multi-select-group.component.ts, projects/kit/components/multi-select/native-multi-select/native-multi-select-group.template.html, projects/kit/components/multi-select/native-multi-select/native-multi-select.component.ts, projects/kit/components/multi-select/native-multi-select/native-multi-select.template.html, projects/kit/components/multi-select/native-multi-select/native-multi-select.ts
=> feat(kit): `Multiselect` add ability to use objects in native select

projects/addon-charts/components/line-chart/line-chart.component.ts, projects/addon-charts/components/pie-chart/pie-chart.component.ts, projects/addon-charts/utils/prepare-external-url.ts
=> fix(addon-charts): `RingChart` fix mask url

projects/cdk/decorators/pure.ts
=> chore(cdk): partial revert `@tuiPure`

projects/addon-mobile/components/app-bar/app-bar.directive.ts, projects/layout/components/block-status/block-status.directive.ts
=> fix: `tuiSlot` extend type with a string

projects/core/utils/mask/create-auto-corrected-money-pipe.ts, projects/core/utils/mask/create-number-mask.ts, projects/core/utils/mask/enable-auto-correct-decimal-symbol.ts, projects/core/utils/mask/masked-money-value-is-empty.ts, projects/core/utils/mask/masked-number-string-to-number.ts, projects/demo-integrations/cypress/tests/addon-table/table-pagination/table-pagination.cy.ts, projects/demo-integrations/cypress/tests/kit/input-number/input-number.cy.ts, projects/demo-integrations/cypress/tests/kit/input-range/input-range.cy.ts, projects/demo-integrations/cypress/tests/kit/input-slider/input-slider.cy.ts, projects/kit/components/input-count/input-count.component.ts, projects/kit/components/input-count/test/input-count-options.component.spec.ts, projects/kit/components/input-count/test/input-count.component.spec.ts, projects/kit/components/input-number/input-number.component.ts, projects/kit/components/input-number/input-number.module.ts, projects/kit/components/input-number/input-number.template.html, projects/kit/components/input-number/test/input-number-format.spec.ts, projects/kit/components/input-number/test/input-number.component.spec.ts, projects/kit/components/input-range/test/input-range.component.spec.ts, projects/kit/components/input-slider/test/input-slider.component.spec.ts
Closes #4540
Closes #3664
Closes #4341
Closes #120
=> feat(kit): `InputNumber` uses `Maskito` instead of legacy `text-mask`

projects/addon-table/components/table/th/th.style.less
=> fix(addon-table): fix z-index for 2-dimensional sticky tables

projects/demo/src/modules/customization/i18n/app.esbuild.module.md, projects/demo/src/modules/customization/i18n/i18n.component.ts, projects/demo/src/modules/customization/i18n/i18n.template.html
=> docs: setting up dynamic language switch

projects/kit/constants/group-class-names.ts
=> chore: mark `GROUP_CLASS_NAMES` as deprecated

projects/kit/components/checkbox-block/checkbox-block.component.ts, projects/kit/components/checkbox-block/checkbox-block.module.ts, projects/kit/components/checkbox-block/checkbox-block.template.html, projects/kit/components/checkbox-labeled/checkbox-labeled.component.ts, projects/kit/components/radio-block/radio-block.component.ts, projects/kit/components/radio-block/radio-block.module.ts, projects/kit/components/radio-block/radio-block.template.html, projects/kit/components/radio-labeled/radio-labeled.component.ts
=> fix(kit): `Checkbox`/`Radio` properly react to mode

projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.template.html
=> fix(addon-mobile): `PullToRefresh` remove transform CSS

projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.template.html
(cherry picked from commit 26bc6aa0db23dd6698e97ad1adbfd719ba8ba7bf)
Closes #
=> fix(addon-mobile): `PullToRefresh` remove transform CSS (#4799)

projects/addon-mobile/components/sheet/directives/sheet-close/sheet-close.directive.ts
=> fix(addon-mobile): `Sheet` fix premature closing

package-lock.json
=> ci: update lock

projects/kit/components/toggle/toggle-options.ts, projects/kit/components/toggle/toggle.component.ts
Closes https://github.com/Tinkoff/taiga-ui/issues/4765
=> feat(kit): add `appearances` for toggle component options

projects/addon-table/directives/table-filters/table-filter.directive.ts, projects/cdk/types/index.ts, projects/cdk/types/values-of.ts, projects/cdk/utils/miscellaneous/uniq-by.ts, projects/core/components/expand/expand.component.ts, projects/demo/src/modules/components/filter/examples/4/index.ts
=> chore(cdk): add `TuiValuesOf`

default.json
=> ci: add `nx` scope for renovate bot

projects/demo/src/modules/components/tree/tree.template.html, projects/kit/components/tree/components/tree/tree.component.ts, projects/kit/components/tree/components/tree/tree.template.html
=> feat(kit): `Tree` add trackBy input (#4626)

projects/demo/src/modules/app/pages.ts
=> chore: add some keywords

projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
=> fix(core): `DropdownHover` allow nested `HostedDropdown`

projects/kit/components/input-tag/input-tag.style.less, projects/kit/components/input-tag/input-tag.template.html, projects/kit/components/multi-select/multi-select.style.less, projects/kit/components/multi-select/multi-select.template.html
=> fix(kit): `MultiSelect` fix `valueContent` overflow

projects/kit/components/tabs/tabs-with-more/tabs-with-more.providers.ts, projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less
=> fix(kit): `Tabs` fix dropdown styles

projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.component.ts, projects/cdk/abstract/dialog.directive.ts, projects/core/components/alert/alert.directive.ts, projects/core/components/alert/alert.module.ts, projects/core/components/alert/index.ts, projects/demo/src/modules/services/alerts/alerts.component.ts, projects/demo/src/modules/services/alerts/alerts.module.ts, projects/demo/src/modules/services/alerts/alerts.template.html, projects/demo/src/modules/services/alerts/examples/6/index.html, projects/demo/src/modules/services/alerts/examples/6/index.ts
=> feat(core): `Alert` add new directive

projects/addon-editor/constants/index.ts
=> chore: fix eslint

.github/ISSUE_TEMPLATE/1-bug-report.yml
=> chore: cleanup

tsconfig.build.json
=> chore: remove redundant pattern

projects/testing/cypress/index.ts
=> fix(testing): export `tuiAddSnapshotPlugin` by default

projects/demo/src/modules/app/app.style.less, projects/demo/src/modules/app/app.template.html, projects/demo/src/modules/app/version-manager/version-manager.component.ts, projects/demo/src/modules/app/version-manager/version-manager.style.less, projects/demo/src/modules/app/version-manager/version-manager.template.html, projects/i18n/switch/language-switcher.service.ts
=> chore: update selects in demo navigation

projects/demo-integrations/cypress.config.ts, projects/demo-integrations/cypress/cypress.options.ts
=> ci: add `blockHosts` for private VPN

projects/cdk/abstract/theme-switcher.ts, projects/core/styles/mixins/picker.less, projects/core/styles/mixins/picker.scss, projects/kit/components/input-inline/input-inline.style.less
=> chore: refactor picker

.github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e-summary.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-dev.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, nx.json
=> ci: nx repair

projects/core/components/hosted-dropdown/hosted-dropdown.style.less, projects/core/components/hosted-dropdown/hosted-dropdown.template.html, projects/core/components/root/root.template.html, projects/kit/components/tag/tag.style.less
=> feat(kit): `Tag` update styles

projects/demo/src/assets/site.webmanifest
=> chore(demo): fix assets path

projects/kit/components/input-phone/input-phone.component.ts
=> refactor(kit): `InputPhone` uses `maskitoCaretGuard` for non-removable country prefix

projects/core/styles/theme/wrapper/icon.less, projects/kit/components/input-copy/index.ts, projects/kit/components/input-copy/input-copy.component.ts, projects/kit/components/input-copy/input-copy.options.ts, projects/kit/components/input-copy/input-copy.style.less, projects/kit/components/input-copy/input-copy.template.html
=> feat(kit): `InputCopy` add DI options

projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts, projects/core/components/primitive-textfield/value-decoration/value-decoration.style.less, projects/core/components/root/root.style.less
=> fix(core): `Root` set body background

projects/cdk/schematics/migration.json, projects/cdk/schematics/ng-add/schema.json, projects/cdk/schematics/ng-update/utils/replace-text.ts, projects/cdk/schematics/ng-update/v3-30/index.ts, projects/cdk/schematics/ng-update/v3-35/index.ts, projects/cdk/schematics/ng-update/v3-36/index.ts, projects/cdk/schematics/ng-update/v3-36/tests/schematic-migrate-editor.spec.ts, projects/demo/src/modules/app/home/examples/addons.md
=> feat(cdk): add schematics for migrate `@taiga-ui/addon-editor` to `@tinkoff/tui-editor`

projects/core/components/svg/svg.component.ts
=> feat(core): support nullability in `src` property

projects/cdk/schematics/ng-update/v3-35/constants/icons.ts, projects/cdk/schematics/ng-update/v3-35/tests/schematic-migrate-icons.spec.ts
=> fix(cdk): fix some icons in icon migration

projects/cdk/services/scroll.service.ts
=> fix(cdk): `ScrollService` fix final position

projects/addon-commerce/components/input-card-grouped/input-card-grouped.options.ts, projects/addon-table/components/table-pagination/table-pagination.options.ts, projects/core/components/primitive-checkbox/checkbox.options.ts, projects/core/directives/textfield-controller/textfield.options.ts, projects/eslint-plugin/rules/injection-token-description.js
=> chore: fix prettier

projects/cdk/schematics/ng-update/v3-36/index.ts
=> fix(schematics): `@tinkoff/tui-editor` should be installed after migration

projects/kit/components/line-clamp/line-clamp.template.html
=> fix(kit): `LineClamp` recalculate size on hover

projects/addon-preview/components/preview/preview.component.ts, projects/addon-preview/components/preview/preview.template.html
=> fix(addon-preview): fix centering when zooming with slider

projects/cdk/schematics/ng-update/v3-35/constants/icons.ts
=> chore: add missed icon

package-lock.json, projects/addon-preview/package.json, projects/eslint-plugin/package.json, projects/i18n/package.json, projects/icons/package.json, projects/layout/package.json, projects/styles/package.json, projects/taiga-schematics/package.json
=> chore: fix peerDependencies

.github/workflows/auto-update-deps-renovate.yml, .github/workflows/publish-dev.yml, default.json
=> ci: correct time for cron relative Moscow

projects/kit/components/files/files.component.html
=> fix(kit): change button appearance for `Files`

projects/demo/src/modules/components/input/examples/3/index.html, projects/demo/src/modules/components/input/examples/3/index.ts, projects/demo/src/modules/components/input/input.module.ts, projects/demo/src/modules/components/input/input.template.html
=> chore(demo): rewrite input example with maskito

projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/core/components/primitive-textfield/primitive-textfield.template.html, projects/core/components/scroll-controls/scroll-controls.style.less, projects/core/styles/mixins/textfield.less, projects/core/styles/mixins/textfield.scss, projects/core/utils/miscellaneous/get-border.ts, projects/core/utils/miscellaneous/test/get-border.spec.ts, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/input-tag/input-tag.style.less, projects/kit/components/input-tag/input-tag.template.html, projects/kit/components/text-area/text-area.component.ts, projects/kit/components/text-area/text-area.style.less, projects/kit/components/text-area/text-area.template.html
Don't merge yet, let's see how hard it breaks screenshots.
=> fix(core): `Textfield` straighten up icons spacings

projects/eslint-plugin/configs/ng.json, projects/eslint-plugin/configs/off.json
=> fix(eslint-plugin): disable `@angular-eslint/component-selector` rule

projects/demo/src/modules/components/progress-segmented/examples/1/index.html, projects/demo/src/modules/components/progress-segmented/examples/1/index.less, projects/demo/src/modules/components/progress-segmented/examples/1/index.ts, projects/demo/src/modules/components/progress-segmented/examples/2/index.html, projects/demo/src/modules/components/progress-segmented/examples/2/index.less, projects/demo/src/modules/components/progress-segmented/examples/3/index.html, projects/demo/src/modules/components/progress-segmented/examples/3/index.less, projects/demo/src/modules/components/progress-segmented/examples/3/index.ts, projects/demo/src/modules/components/progress-segmented/progress-segmented.component.ts
https://taiga-ui.dev/next/components/progress-segmented
=> chore(demo): improve documentation page of `ProgressSegmented`

projects/core/components/button/button.style.less
=> chore(core): `Button` fix icon paddings

projects/core/directives/dropdown/dropdown.style.less, projects/core/directives/hint/hint.style.less
=> chore: use proper CSS variable for dropdown and hint background

projects/eslint-plugin/configs/ng.json, projects/eslint-plugin/configs/off.json
=> fix(eslint-plugin): disable `@angular-eslint/use-component-selector` rule

projects/cdk/schematics/ng-update/v3-35/constants/icons.ts
=> chore(cdk): add old aliases in migration

projects/demo-integrations/cypress.config.ts, projects/demo-integrations/cypress/tests/deep/deep.cy.ts, projects/demo-integrations/cypress/tests/demo/demo.cy.ts
=> ci: support override specs in `demo.cy.ts`, `deep.cy.ts`

default.json
=> ci: add `cspell` group

projects/demo-integrations/cypress/tests/kit/input-number/input-number.cy.ts, projects/demo/src/modules/components/input-number/examples/5/index.html, projects/kit/components/input-number/input-number.component.ts, projects/kit/components/input-number/input-number.template.html, projects/kit/components/input-range/test/input-range.component.spec.ts, projects/kit/components/input-slider/test/input-slider.component.spec.ts
Closes #3823
Closes #4832
Closes #2959
=> refactor(kit): `InputNumber` uses `prefix` / `postfix` from `Maskito`

projects/addon-commerce/components/input-card/input-card.component.ts, projects/addon-commerce/components/input-cvc/input-cvc.component.ts, projects/addon-commerce/components/input-expire/input-expire.component.ts, projects/cdk/services/scroll.service.ts, projects/kit/components/combo-box/combo-box.component.ts, projects/kit/components/input-copy/input-copy.component.ts, projects/kit/components/input-count/input-count.style.less, projects/kit/components/input-date-range/input-date-range.component.ts, projects/kit/components/input-date-time/input-date-time.component.ts, projects/kit/components/input-date/input-date.component.ts, projects/kit/components/input-month-range/input-month-range.component.ts, projects/kit/components/input-month/input-month.component.ts, projects/kit/components/input-number/input-number.component.ts, projects/kit/components/input-number/input-number.style.less, projects/kit/components/input-password/input-password.component.ts, projects/kit/components/input-password/input-password.template.html, projects/kit/components/input-password/test/input-password.component.spec.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-phone/input-phone.component.ts, projects/kit/components/input-time/input-time.component.ts, projects/kit/components/input-year/input-year.component.ts, projects/kit/components/input/input.component.ts, projects/kit/components/select/select.component.ts
=> chore: expose size for controls

README.md
Replaced old link with a new one
=> chore(readme): replace old link

package-lock.json, package.json, projects/demo/src/modules/icons/icons.component.ts, projects/demo/src/modules/icons/icons.module.ts, projects/demo/src/modules/icons/icons.style.less, projects/demo/src/modules/icons/icons.template.html
=> chore(demo): customize icon color on demo

projects/addon-commerce/utils/is-expire-valid.ts, projects/addon-commerce/utils/test/is-expire-valid.spec.ts
=> fix(addon-commerce): correct comparison of months for expiry date

projects/core/package.json, projects/taiga-schematics/package.json
=> fix(core): pinned `i18n` dependency

projects/demo/src/modules/tables/table-pagination/table-pagination.template.html
=> chore(demo): `TablePagination` deprecate "page" and "size" properties

projects/cdk/schematics/constants/file-globs.ts
=> feat(schematics): include `*.sass,scss,css` files for replace string

.npmrc
=> ci: disable strict `ssl`

projects/addon-mobile/components/tab-bar/tab-bar-item.style.less
=> fix(kit): align center badge content display

.github/actions/variables/action.yml, .github/workflows/auto-approve.yml, default.json, scripts/cspell/ci-cd.json
=> ci: support automerge for PRs of tinkoff-bot

projects/demo-integrations/cypress/tests/kit/input-files/input-files.cy.ts, projects/i18n/languages/chinese/kit.ts, projects/i18n/languages/dutch/kit.ts, projects/i18n/languages/english/kit.ts, projects/i18n/languages/french/kit.ts, projects/i18n/languages/german/kit.ts, projects/i18n/languages/italian/kit.ts, projects/i18n/languages/polish/kit.ts, projects/i18n/languages/portuguese/kit.ts, projects/i18n/languages/russian/kit.ts, projects/i18n/languages/spanish/kit.ts, projects/i18n/languages/turkish/kit.ts, projects/i18n/languages/vietnamese/kit.ts, projects/kit/components/input-files/input-files.component.ts, projects/kit/utils/files/format-size.ts, projects/kit/utils/files/test/format-size.spec.ts
=> feat(i18n): switch to power of 2 for file size display

projects/core/directives/hint/hint.component.ts
=> fix(core): `Hint` fix positioning near the right edge of the viewport

.github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e-summary.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-dev.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml
=> chore: revert

projects/cdk/schematics/utils/is-ci.ts, projects/cdk/schematics/utils/progress.ts
=> chore: ignore progress for CI

.github/workflows/publish-canary.yml, scripts/publish-canary.ts
=> ci: use `canary` tag instead of `dev`

.github/workflows/auto-approve.yml
=> ci: fix approve

projects/cdk/package.json
=> fix(cdk): include `tds` packages for update

projects/demo/src/modules/components/input-range/examples/6/index.html, projects/demo/src/modules/components/input-range/examples/6/index.ts, projects/demo/src/modules/components/input-range/examples/6/transformer.ts, projects/demo/src/modules/components/input-range/input-range.component.ts, projects/demo/src/modules/components/input-range/input-range.module.ts, projects/demo/src/modules/components/input-range/input-range.template.html, projects/kit/components/input-number/input-number.component.ts
=> feat(kit): `InputNumber` add value transformer token

projects/eslint-plugin/configs/naming-convention.json
=> fix(eslint-plugin): ignore naming convention for apps directory

.npmrc, package-lock.json
=> chore: remove redundant option `lockfileVersion`

.github/workflows/auto-author-assign.yml, .github/workflows/auto-label.yml, .github/workflows/auto-update-icons.yml, .github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml, projects/demo-cypress/cypress/plugins/index.ts
=> ci: support outputs in setup-node

.github/workflows/e2e.yml, projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts
=> ci: fix screenshot test reports

.github/workflows/auto-author-assign.yml, .github/workflows/auto-label.yml, .github/workflows/auto-update-icons.yml, .github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml, projects/eslint-plugin/configs/naming-convention.json
=> ci: exclude cache directory in node_modules

.github/workflows/lint.yml
=> chore: need investigate

.github/workflows/auto-author-assign.yml, .github/workflows/auto-label.yml, .github/workflows/auto-update-icons.yml, .github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml
=> ci: correct dist

.github/workflows/snapshots.yml
=> ci: restore snapshot v3.x

.github/workflows/auto-add-to-project.yml, .github/workflows/auto-approve.yml, .github/workflows/auto-update-deps-renovate.yml, .github/workflows/auto-update-icons.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/lint.yml, .github/workflows/snapshots.yml
=> ci: use `TAIGA_FAMILY_BOT_PAT` secret

.github/workflows/auto-author-assign.yml, .github/workflows/auto-label.yml, .github/workflows/auto-update-icons.yml, .github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml
=> ci: update actions

projects/demo/src/modules/icons/icons-bundled/icons-bundled.template.html, projects/demo/src/modules/info/related/related.template.html
=> chore(demo): fix Github Pages links of Taiga Family products

projects/addon-commerce/utils/create-auto-corrected-expire-pipe.ts, projects/core/utils/format/format-phone.ts, projects/core/utils/mask/create-auto-corrected-money-pipe.ts, projects/core/utils/mask/create-correction-mask.ts, projects/core/utils/mask/create-number-mask.ts, projects/core/utils/mask/enable-auto-correct-decimal-symbol.ts, projects/core/utils/mask/masked-money-value-is-empty.ts, projects/core/utils/mask/masked-number-string-to-number.ts, projects/demo/src/modules/components/input/input.template.html, projects/demo/src/modules/components/tag/examples/6/index.html, projects/kit/components/input-phone/utils/create-phone-mask-expression.ts, projects/kit/constants/masks.ts, projects/kit/utils/mask/create-auto-corrected-date-pipe.ts, projects/kit/utils/mask/create-auto-corrected-date-range-pipe.ts, projects/kit/utils/mask/create-auto-corrected-date-time-pipe.ts, projects/kit/utils/mask/create-auto-corrected-time-pipe.ts, projects/kit/utils/mask/create-date-mask.ts, projects/kit/utils/mask/create-date-range-mask.ts, projects/kit/utils/mask/create-time-mask.ts
=> chore: fix `Maskito` documentation link

package-lock.json, package.json
=> chore: fixate `Playwright` version

projects/demo-playwright/tests/example.spec.ts
=> chore(demo-playwright): update test to be compatible with proprietary repo

.github/workflows/publish-canary.yml
=> ci: I forgot build before publish

projects/addon-mobile/components/tab-bar/tab-bar.component.ts, projects/addon-mobile/components/tab-bar/tab-bar.module.ts, projects/addon-mobile/components/tab-bar/tab-bar.style.less, projects/addon-mobile/components/tab-bar/tab-bar.template.html, projects/core/components/root/root.style.less, projects/demo/src/modules/components/tab-bar/examples/4/index.html, projects/demo/src/modules/components/tab-bar/examples/4/index.ts, projects/demo/src/modules/components/tab-bar/tab-bar.component.ts, projects/demo/src/modules/components/tab-bar/tab-bar.module.ts, projects/demo/src/modules/components/tab-bar/tab-bar.template.html, projects/styles/basic/keyframes.less
=> feat(addon-mobile): `TabBar` add skeletons for empty state

.github/workflows/auto-add-to-project.yml, .github/workflows/auto-approve.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-cleanup-caches.yml, .github/workflows/auto-dependency-review.yml, .github/workflows/auto-label.yml, .github/workflows/auto-remove-label.yml, .github/workflows/auto-update-icons.yml, .github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml, renovate.json
=> ci: fix some yml files

projects/demo-cypress/cypress/tests/kit/input-year/input-year.cy.ts, projects/kit/components/input-year/input-year.component.ts
=> fix(kit): `InputYear` should update text field value after selection from dropdown

projects/eslint-plugin/project.json, projects/prettier-config/project.json, projects/stylelint-config/project.json
=> ci: don't publish linters

.github/workflows/publish-canary.yml, .github/workflows/publish.yml
=> ci: use `TAIGA_UI_SCOPE_NPM_TOKEN`

.github/screenshot-bot.config.toml, .github/workflows/e2e.yml, package-lock.json, package.json, projects/demo-playwright/tests/nested-folder/nested-folder-example.spec.ts, projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts, scripts/combine-playwright-failed-screenshots.ts
=> ci: combine screenshots of failed Playwright tests into a single image

.github/workflows/auto-approve.yml
=> ci: add approver token

projects/addon-preview/index.ts
=> fix(addon-preview): export tokens as public api

projects/demo/src/modules/components/textarea/examples/2/index.html, projects/kit/components/textarea/textarea.style.less, projects/kit/components/textarea/textarea.template.html
=> fix(kit): `Textarea` fix wrong expansion with new line, fix paddings

projects/demo-playwright/tests/example.spec.ts, projects/demo-playwright/tests/nested-folder/nested-folder-example.spec.ts, projects/demo-playwright/utils/goto.ts, projects/demo-playwright/utils/index.ts, projects/demo-playwright/utils/mock-date.ts, projects/demo-playwright/utils/wait-for-fonts.ts
=> chore(demo-playwright): new utility `tuiGoto` (mock date + wait for fonts)

projects/demo/src/modules/app/pages.ts
=> chore(demo): improve typings

.github/workflows/auto-add-to-project.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-rebase-v3.yml, .github/workflows/auto-rebase.yml, .github/workflows/create-release.yml, .github/workflows/lint.yml, .github/workflows/snapshots.yml, projects/addon-mobile/directives/mobile-tabs/mobile-tabs.style.less
cherry-pick 77a03fe
Closes #5107
=> fix(addon-mobile): `MobileTabs` update iOS design (#4722)

projects/addon-editor/constants/default-editor-styles.ts, projects/addon-editor/constants/tiptap-editor-styles.ts, projects/addon-editor/styles/editor-socket.css
=> feat(addon-editor): change margin for list

projects/cdk/utils/color/hex-to-rgba.ts, projects/cdk/utils/color/index.ts, projects/cdk/utils/color/rgba-to-hex.ts, projects/cdk/utils/color/test/hex-to-rgba.spec.ts, projects/cdk/utils/color/test/rgba-to-hex.spec.ts
=> feat(cdk): support parsing hex to rgba

.github/workflows/create-release.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml
=> ci: use configure npm action

package-lock.json, package.json
=> chore(deps): upgrade editor to 1.4

package-lock.json, package.json
=> ci: support cspell 7

projects/demo/src/index.html
=> ci: ignore preload fonts

.github/workflows/e2e.yml, projects/demo-cypress/cypress/support/helpers/demo-paths.ts, projects/demo-playwright/tests/demo/demo.spec.ts, projects/demo-playwright/tests/demo/get-demo-paths.ts, projects/demo-playwright/tests/demo/is-flaky-examples.ts
=> chore(demo-playwright): `demo.spec.ts`

.github/workflows/auto-cleanup-caches.yml
=> ci: cleanup cache from main branch

package-lock.json, package.json
=> chore: upgrade tui-editor

projects/cdk/schematics/ng-update/v3/index.ts, projects/cdk/schematics/ng-update/v3/steps/replace-styles.ts, projects/cdk/schematics/ng-update/v3/tests/schematic-replace-styles.spec.ts
=> fix(schematics): fix global style migration

projects/demo-playwright/playwright.config.ts, projects/demo-playwright/tests/demo/demo.spec.ts, projects/demo-playwright/tests/demo/get-demo-paths.ts
Part of https://github.com/taiga-family/taiga-ui/issues/4912
=> chore(demo-playwright): use `process.env` to parameterize `demo.spec.ts` tests

projects/demo-playwright/playwright.config.ts
=> ci(demo-playwright): replace absolute path import with relative one

projects/demo-playwright/tests/demo/get-demo-paths.ts, projects/demo-playwright/tests/demo/is-flaky-examples.ts
=> chore(demo-playwright): include some examples from `Carousel` to `demo.spec.ts`

projects/cdk/directives/index.ts, projects/cdk/directives/platform/index.ts, projects/cdk/directives/platform/ng-package.json, projects/cdk/directives/platform/platform.directive.ts, projects/cdk/directives/platform/platform.module.ts, projects/cdk/tokens/index.ts, projects/cdk/tokens/platform.ts, projects/cdk/types/index.ts, projects/cdk/types/platform.ts
=> feat(cdk): `Platform` add new token and directive

package-lock.json, projects/i18n/README.md, projects/i18n/package.json, projects/i18n/tokens/language-storage-key.ts, projects/i18n/tokens/language.ts
1. Create new angular project
2. Install NOT latest deps (according to [Getting Started](https://taiga-ui.dev/getting-started)):
```console
npm i @taiga-ui/{cdk,core,kit,icons}@3.39.0
```
3. It throws:
```console
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @taiga-ui/i18n@3.41.1
npm ERR! Found: @taiga-ui/cdk@3.[39]
npm ERR! node_modules/@taiga-ui/cdk
npm ERR!   @taiga-ui/cdk@"3.39.0" from the root project
npm ERR!   peer @taiga-ui/cdk@">=3.39.0" from @taiga-ui/addon-commerce@3.39.0
npm ERR!   node_modules/@taiga-ui/addon-commerce
npm ERR!     @taiga-ui/addon-commerce@"3.39.0" from the root project
npm ERR!   7 more (@taiga-ui/addon-mobile, @taiga-ui/addon-tablebars, ...)
npm ERR! 
npm ERR! Could …
```
=> fix(i18n): `Conflicting peer dependency` error

projects/demo/src/modules/info/related/related.style.less, projects/demo/src/modules/info/related/related.template.html
=> chore(demo): update some links

projects/addon-commerce/components/money/money.component.ts, projects/addon-commerce/components/money/money.module.ts, projects/addon-commerce/components/money/money.options.ts, projects/addon-commerce/components/money/money.style.less, projects/addon-commerce/components/money/money.template.html, projects/demo/src/modules/components/money/examples/5/index.html, projects/demo/src/modules/components/money/money.component.ts, projects/demo/src/modules/components/money/money.template.html
=> feat(addon-commerce): `Money` add currencyAlign property

.env, projects/cdk/schematics/ng-update/v3-35/constants/icons.ts
=> fix(schematics): small fixes

projects/cdk/schematics/ng-update/v3-35/constants/icons.ts
=> fix(schematics): migrate wysiwyg icons

projects/addon-doc/components/internal/source-code/source-code.component.ts, projects/addon-doc/components/internal/source-code/source-code.template.html
=> feat(addon-doc): support remote url for code source

projects/demo-playwright/utils/goto.ts
See https://github.com/taiga-family/taiga-ui/actions/runs/6012566372/job/16308400768?pr=5229:
```
1) [chromium] › tests/kit/input-slider/input-slider.spec.ts:187:17 › InputSlider › [min] prop › if [min]-property equals to [max]-property › pressing ArrowUp does not change value 
Error: Timed out 5000ms waiting for expect(received).toHaveClass(expected)
Expected pattern: /_loaded/
Received string:  ""
Call log:
- expect.toHaveClass with timeout 5000ms
- waiting for locator('app')
-   locator resolved to <app></app>
-   unexpected value ""
-   locator resolved to <app></app>
-   unexpected value ""
-   locator resolved to <app></app>
-   unexpected value ""
-   locator resolved to <app></app>
-   unexpected value ""
-   locator resolved to …
```
=> chore(demo-playwright): improve tests stability

projects/demo-playwright/utils/goto.ts
Part of https://github.com/taiga-family/taiga-ui/issues/4912
=> chore(demo-playwright): hide documentation header during tests

projects/demo-playwright/tests/demo/is-flaky-examples.ts
=> chore(demo-playwright): exclude flaky example from `demo.spec.ts`

package-lock.json, package.json
=> chore: upgrade eslint plugin

package-lock.json, package.json
=> ci: upgrade cspell

projects/demo-playwright/tests/addon-charts/pie-chart/pie-chart.spec.ts, projects/demo-playwright/tests/core/primitive-textfield/primitive-textfield.spec.ts, projects/demo-playwright/tests/demo/demo.spec.ts, projects/demo-playwright/tests/example.spec.ts, projects/demo-playwright/tests/kit/input-slider/input-slider.spec.ts, projects/demo-playwright/tests/kit/slider/slider.spec.ts, projects/demo-playwright/tests/nested-folder/nested-folder-example.spec.ts, tsconfig.json
See:
* https://github.com/taiga-family/taiga-ui/pull/5226#discussion_r1308699242
=> chore(demo-playwright): add `@demo-playwright/utils` path alias

projects/demo-playwright/tests/addon-charts/pie-chart/pie-chart.spec.ts
See https://github.com/taiga-family/taiga-ui/actions/runs/6022356301/job/16337232901?pr=5166
```
2) [chromium] › tests/addon-charts/pie-chart/pie-chart.spec.ts:6:9 › PieChart › should be show hints on charts 
Error: expect.toBeAttached: Error: strict mode violation: locator('tui-hint') resolved to 2 elements:
1) <tui-hint _nghost-tui-demo-c119="" data-appearance="onDark…>…</tui-hint> aka getByText('12 367 ₽Cafe')
2) <tui-hint _nghost-tui-demo-c119="" data-appearance="onDark…>…</tui-hint> aka getByText('10 172 ₽Open Source')
=========================== logs ===========================
expect.toBeAttached with timeout 5000ms
waiting for locator('tui-hint')
============================================================
16 |         for (const [i, …
```
=> chore(demo-playwright): improve test stability in `pie-chart.spec.ts`

package-lock.json, package.json
=> ci: upgrade cypress

.cspell.json, scripts/combine-playwright-failed-screenshots.ts
See:
* https://github.com/taiga-family/taiga-ui/actions/runs/6035768066/job/16377003998
```
/home/runner/work/taiga-ui/taiga-ui/node_modules/canvas/lib/image.js:94
SetSource.call(img, src)
^
Error: Unsupported image type
at setSource (/home/runner/work/taiga-ui/taiga-ui/node_modules/canvas/lib/image.js:94:13)
at Image.set (/home/runner/work/taiga-ui/taiga-ui/node_modules/canvas/lib/image.js:65:9)
at /home/runner/work/taiga-ui/taiga-ui/node_modules/canvas/index.js:34:15
at new Promise (<anonymous>)
at loadImage (/home/runner/work/taiga-ui/taiga-ui/node_modules/canvas/index.js:23:10)
at Array.map (<anonymous>)
at /home/runner/work/taiga-ui/taiga-ui/scripts/combine-playwright-failed-screenshots.ts:34:50
at Generator.next (<anonymous>)
at …
```
=> chore: fix CI

.github/workflows/create-release.yml
=> ci: correct get last tags

.github/workflows/auto-approve.yml
=> ci: improve workflows

SECURITY.md
To update the active `v3.0.0` version use the following [migration guide](https://github.com/taiga-family/taiga-ui/releases/tag/v3.0.0#migration):
**Angular CLI:**
```
ng update @taiga-ui/cdk
```
**Nx CLI:**
```
nx migrate @taiga-ui/cdk
nx migrate --run-migrations=migrations.json
```
=> chore: `v2` major version reached End of Life

projects/kit/components/range/range.style.less, projects/kit/components/slider/slider.style.less
https://taiga-ui.dev/components/slider#segments
=> fix(kit): update ticks color for `Slider` & `Range`

projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/demo/src/modules/components/input/examples/2/index.html
=> fix(core): overlapped by placeholder in autocomplete mode

package-lock.json, package.json, projects/addon-commerce/validators/luhn.validator.ts, projects/addon-doc/components/code/tests/code.component.spec.ts, projects/addon-doc/components/navigation/navigation.providers.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.providers.ts, projects/addon-mobile/components/sheet/components/sheet/sheet.providers.ts, projects/addon-mobile/directives/ripple/ripple.providers.ts, projects/cdk/components/dialog-host/dialog-host.component.ts, projects/cdk/schematics/ng-add/steps/add-taiga-icons.ts, projects/cdk/schematics/ng-update/v3/steps/migrate-taiga-proprietary-icons.ts, projects/core/observables/smart-search.ts, projects/demo-cypress/cypress/support/helpers/deep-paths.ts, projects/demo-cypress/cypress/support/helpers/visit.ts, projects/demo-cypress/cypress/tests/core/dialogs/dialog-browser-back.cy.ts, projects/demo/src/modules/app/stackblitz/utils.ts, projects/demo/src/modules/components/input-files/examples/2/index.ts, projects/demo/src/modules/components/input-month-range/examples/3/index.ts, projects/demo/src/modules/components/input-time/input-time.component.ts, projects/demo/src/modules/components/multi-select/examples/9/index.html, projects/demo/src/modules/components/multi-select/examples/9/index.ts, projects/demo/src/modules/pipes/field-error/examples/5/index.ts, projects/kit/components/input-phone/utils/complete-phone-insertion-preprocessor.ts, projects/kit/components/tabs/tabs-with-more/tabs-with-more.providers.ts, projects/kit/providers/month-formatter.provider.ts, projects/testing/setup-jest/index.ts
=> ci: upgrade eslint

projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
=> fix(addon-commerce): add `automation-id` for cleaner and dropdown buttons

projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts, projects/addon-mobile/components/sheet-dialog/sheet-dialog.module.ts, projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less, projects/addon-mobile/components/sheet-dialog/sheet-dialog.template.html, projects/demo/src/modules/components/sheet-dialog/examples/3/index.html, projects/demo/src/modules/components/sheet-dialog/examples/3/index.less, projects/demo/src/modules/components/sheet-dialog/examples/4/index.html, projects/demo/src/modules/components/sheet-dialog/examples/4/index.less, projects/demo/src/modules/components/sheet-dialog/examples/4/index.ts, projects/demo/src/modules/components/sheet-dialog/sheet-dialog.component.ts, projects/demo/src/modules/components/sheet-dialog/sheet-dialog.module.ts, projects/demo/src/modules/components/sheet-dialog/sheet-dialog.template.html
=> fix(addon-mobile): `SheetDialog` fix scrolling flicker

projects/cdk/tokens/window-height.ts, projects/demo/src/modules/components/sheet-dialog/examples/4/index.html, projects/demo/src/modules/components/sheet-dialog/examples/4/index.less, projects/demo/src/modules/components/sheet-dialog/examples/4/index.ts
=> chore(demo): improve example

projects/demo-playwright/tests/demo/get-demo-paths.ts
=> chore(demo-playwright): exclude `Sheet` & `SheetDialog` pages from `demo.spec.ts`

projects/cdk/utils/svg/svg-linear-gradient-processor.ts
=> fix(cdk): compatibility svg processor with SSR

projects/demo/src/modules/components/dialog/examples/9/index.html, projects/kit/components/input-number/input-number.directive.ts, projects/kit/components/input-number/test/input-number.component.spec.ts
=> fix(kit): `InputNumber` ignores native attribute `maxlength`

projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts, projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts, projects/cdk/schematics/utils/push-to-array-property.ts
=> fix(schematics): do not provide `BrowserAnimationsModule` for standalone application

projects/demo/src/modules/components/hosted-dropdown/examples/3/index.less
=> chore(demo): fix layout in example

projects/addon-doc/tokens/scroll-behavior.ts, projects/cdk/utils/miscellaneous/create-token.ts, projects/core/tokens/animations-duration.ts, projects/core/tokens/index.ts, projects/core/tokens/reduced-motion.ts, projects/demo/src/modules/app/app.providers.ts
=> feat(core): add `TUI_REDUCED_MOTION`

projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less, projects/core/styles/mixins/mixins.less, projects/core/styles/mixins/mixins.scss, projects/core/styles/mixins/textfield.less, projects/core/styles/mixins/textfield.scss, projects/core/styles/theme/wrapper/icon.less, projects/kit/components/input-files/input-files.style.less, projects/kit/components/radio-list/radio-list.style.less
=> chore: remove redundant rule

projects/addon-charts/components/bar-set/bar-set.component.ts
=> fix(addon-charts): `BarSet` fix case with all bars negative

projects/cdk/tokens/index.ts, projects/cdk/tokens/window-height.ts, projects/cdk/tokens/window-size.ts, projects/core/services/breakpoint.service.ts, projects/demo/src/modules/services/breakpoint/examples/1/component.ts, projects/demo/src/modules/services/breakpoint/examples/1/template.html, projects/kit/components/tiles/tile-handle.directive.ts, projects/kit/components/tiles/tile.component.ts
=> fix(cdk): `BreakpointService` properly react to window resize

projects/demo-playwright/utils/page-objects/index.ts, projects/demo-playwright/utils/page-objects/input-tag.po.ts, projects/demo-playwright/utils/page-objects/input-time.po.ts, projects/demo-playwright/utils/page-objects/textfield-with-data-list.po.ts
Part of https://github.com/taiga-family/taiga-ui/issues/4912
=> refactor(demo-playwright): base class `TuiTextfieldWithDataListPO`

projects/demo/src/modules/icons/icons-group/icons-group.component.ts, projects/demo/src/modules/icons/icons-group/icons-group.module.ts, projects/demo/src/modules/icons/icons-group/icons-group.template.html
=> chore(demo): support search icons by query params

projects/core/tokens/reduced-motion.ts
=> fix(core): matchMedia is not a function in SSR

projects/core/components/dialog/dialog-close.service.ts, projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
=> fix(core): the order of the escape event is important in the dialog service

projects/demo-cypress/cypress/tests/kit/tree/tree.cy.ts, projects/demo/src/modules/components/tree/examples/4/index.html, projects/demo/src/modules/components/tree/examples/4/index.ts, projects/kit/components/tree/components/tree-item/tree-item.component.ts
=> fix(kit): fix tree programmatic control

jest.config.ts
=> ci: ignore playwright path in jest

projects/addon-commerce/components/money/money.template.html, projects/addon-commerce/components/money/test/money.component.spec.ts, projects/demo/src/modules/components/money/examples/1/index.html, projects/demo/src/modules/components/money/examples/5/index.html
=> fix(addon-commerce): `Money` causes an extra space

projects/core/components/primitive-textfield/primitive-textfield.style.less, projects/demo/src/modules/components/input/examples/2/index.html
=> fix(core): don't hide placeholder for input size m

.github/workflows/e2e.yml
=> ci: enable shard for playwright

projects/demo/src/modules/app/app.providers.ts
=> chore(demo): NoopAnimations for E2E by default

package-lock.json, scripts/postbump.ts
=> ci: ignore bump release version for taiga-ui config packages

.prettierignore, package.json
=> ci: remove redundant prettier ignore file

.firebaserc
=> ci: remove redundant firebaserc

projects/addon-doc/components/main/main.style.less, projects/core/components/notification/notification.style.less, projects/demo/src/modules/experimental/avatar/avatar.component.ts, projects/demo/src/modules/experimental/avatar/avatar.module.ts, projects/demo/src/modules/experimental/avatar/avatar.template.html, projects/demo/src/modules/experimental/avatar/examples/2/index.html, projects/demo/src/modules/experimental/avatar/examples/3/index.html, projects/demo/src/modules/experimental/avatar/examples/3/index.less, projects/demo/src/modules/experimental/avatar/examples/4/index.html, projects/demo/src/modules/experimental/avatar/examples/4/index.ts, projects/experimental/components/avatar-stack/avatar-stack.style.less, projects/experimental/components/avatar/avatar.component.ts, projects/experimental/components/avatar/avatar.module.ts, projects/experimental/components/avatar/avatar.style.less, projects/experimental/components/avatar/avatar.template.html
=> chore(experimental): `Avatar` finalize

projects/demo/src/modules/components/progress-segmented/examples/3/index.html, projects/demo/src/modules/components/progress-segmented/examples/3/index.less, projects/kit/components/progress/progress-bar/progress-bar.component.less, projects/kit/components/progress/progress-bar/progress-bar.component.ts, projects/kit/components/progress/progress-circle/progress-circle.component.ts, projects/kit/components/progress/progress-circle/progress-circle.style.less, projects/kit/components/progress/progress-segmented/progress-segmented.component.ts, projects/kit/components/progress/progress-segmented/progress-segmented.style.less
=> fix(kit): `Progress` fix colors and mode

projects/demo/src/modules/components/progress-bar/progress-bar.component.html
https://taiga-ui.dev/components/progress-bar/API?size=xxl
=> chore(demo): update API documentation page about `ProgressBar`

projects/kit/components/tabs/tabs-with-more/tabs-with-more.component.ts
Closes #4918
https://github.com/taiga-family/taiga-ui/assets/12021443/931e7a14-a56c-473a-9cb7-3d9800000cf4
=> fix(kit): update a tab when the active index has changed

projects/core/components/notification/notification.style.less
=> fix(core): don't use hyphens in notification

projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/tag/tag.template.html
Closes #5029
https://github.com/taiga-family/taiga-ui/assets/12021443/36a57ec7-592e-41c2-ab17-08edde3f7e2f
=> fix(kit): prevent focusing when remove item from multi-select

projects/core/components/notification/notification.style.less, projects/demo/src/modules/components/checkbox-block/checkbox-block.component.ts, projects/demo/src/modules/components/checkbox-block/checkbox-block.template.html, projects/demo/src/modules/components/checkbox-block/examples/1/index.html, projects/demo/src/modules/components/checkbox-block/examples/1/index.ts, projects/demo/src/modules/components/filter/filter.component.ts, projects/demo/src/modules/components/radio-block/examples/1/index.html, projects/demo/src/modules/components/radio-block/radio-block.component.ts, projects/demo/src/modules/components/radio-block/radio-block.template.html, projects/kit/components/checkbox-block/checkbox-block.component.ts, projects/kit/components/checkbox-block/checkbox-block.style.less, projects/kit/components/filter/filter.component.ts, projects/kit/components/filter/filter.style.less, projects/kit/components/radio-block/radio-block.component.ts
=> feat(kit): `CheckboxBlock`/`RadioBlock` add new size

projects/experimental/components/button/button.style.less
=> chore: add disabled state to mobile buttons

projects/demo-playwright/utils/page-objects/select.po.ts
=> chore(demo-playwright): use relative path for import of PO inside another PO

projects/addon-doc/components/navigation/navigation.component.ts
=> feat(addon-doc): improve search

projects/kit/components/select/select.component.ts
=> chore: `select` rewrite bad code

projects/cdk/directives/active-zone/active-zone.directive.ts
=> refactor(cdk): small changes in active-zone

projects/cdk/schematics/tsconfig.schematics.json
=> chore: has problem with spec ts files inside submodule on Github

projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/experimental/badge-alert/badge-alert.component.ts, projects/demo/src/modules/experimental/badge-alert/badge-alert.module.ts, projects/demo/src/modules/experimental/badge-alert/badge-alert.template.html, projects/demo/src/modules/experimental/badge-alert/examples/1/index.html, projects/demo/src/modules/experimental/badge-alert/examples/1/index.less, projects/demo/src/modules/experimental/badge-alert/examples/1/index.ts, projects/demo/src/modules/experimental/badge-alert/examples/2/index.html, projects/demo/src/modules/experimental/badge-alert/examples/2/index.less, projects/demo/src/modules/experimental/badge-alert/examples/2/index.ts, projects/demo/src/modules/experimental/badge-alert/examples/import/import-module.md, projects/demo/src/modules/experimental/badge-alert/examples/import/insert-template.md, projects/experimental/components/badge-alert/badge-alert.component.ts, projects/experimental/components/badge-alert/badge-alert.module.ts, projects/experimental/components/badge-alert/badge-alert.style.less, projects/experimental/components/badge-alert/index.ts, projects/experimental/components/badge-alert/ng-package.json, projects/experimental/components/badge/badge.component.ts, projects/experimental/components/badge/badge.module.ts, projects/experimental/components/index.ts
=> feat(experimental): `BadgeAlert` add new component

projects/addon-doc/components/main/main.style.less
=> feat(addon-doc): improve ui for code links

.github/workflows/e2e.yml, package-lock.json, package.json, projects/demo-cypress/cypress.config.ts, projects/demo-cypress/project.json
=> ci: remove cy2

projects/kit/components/input-phone/input-phone.component.ts
=> fix(kit): `InputPhone` fix initial value

projects/core/styles/theme/wrapper/base.less
=> chore(core): `Wrapper` hide focus in Safari for the time being

projects/kit/components/combo-box/combo-box.component.ts
=> fix(kit): `Combobox` return null support for strict matcher

projects/core/components/alert/alert.style.less
Closes https://github.com/taiga-family/taiga-ui/issues/5457
=> fix(core): add break word in alert

projects/kit/components/radio-labeled/radio-labeled.style.less, projects/kit/components/radio-list/radio-list.style.less
=> feat(kit): allow customize vertical align of `Radio` inside `RadioList`

projects/demo/src/modules/components/input-files/examples/import/native-input-inside-input-files.md, projects/demo/src/modules/components/input-files/input-files.component.ts, projects/demo/src/modules/components/input-files/input-files.template.html
=> chore(demo): update API documentation page of `InputFiles`

.github/workflows/lint.yml
=> ci: simplify lint job

.github/workflows/lint.yml
=> ci: checkout before global variables

projects/addon-charts/components/line-chart/line-chart-hint.directive.ts, projects/addon-charts/components/line-chart/line-chart.component.ts, projects/addon-charts/components/line-chart/line-chart.template.html, projects/addon-charts/components/line-days-chart/line-days-chart-hint.directive.ts, projects/addon-charts/components/line-days-chart/line-days-chart.component.ts, projects/addon-charts/components/line-days-chart/line-days-chart.template.html, projects/core/directives/hint/hint-describe.directive.ts, projects/demo/src/modules/charts/line-days-chart/examples/2/index.ts
=> fix(addon-charts): `LineDaysChart` fix performance leak

projects/core/tokens/common-icon.ts, projects/demo/src/modules/components/sheet-dialog/examples/4/index.html, projects/demo/src/modules/components/sheet-dialog/examples/4/index.less, projects/demo/src/modules/components/sheet-dialog/examples/4/index.ts, projects/demo/src/modules/components/sheet-dialog/sheet-dialog.module.ts
=> chore: add partial

projects/addon-table/components/table/th/th.style.less
=> fix(addon-table): `table` controls do not work in heading

projects/cdk/tokens/fonts-ready.ts, projects/cdk/tokens/index.ts, projects/core/components/primitive-textfield/value-decoration/value-decoration.component.ts
=> fix(core): `PrimitiveTextfield` with prefix/postfix has CD problem after delayed fonts loading

projects/addon-doc/components/code/code.module.ts, projects/addon-doc/components/code/code.style.less, projects/addon-doc/components/code/code.template.html, projects/addon-doc/components/code/tests/code.component.spec.ts, projects/addon-doc/components/example/example.template.html
=> feat(addon-doc): add copy button out-of-the-box

projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/experimental/badged-content/badged-content.component.ts, projects/demo/src/modules/experimental/badged-content/badged-content.module.ts, projects/demo/src/modules/experimental/badged-content/badged-content.template.html, projects/demo/src/modules/experimental/badged-content/examples/1/index.html, projects/demo/src/modules/experimental/badged-content/examples/1/index.less, projects/demo/src/modules/experimental/badged-content/examples/1/index.ts, projects/demo/src/modules/experimental/badged-content/examples/2/index.html, projects/demo/src/modules/experimental/badged-content/examples/2/index.less, projects/demo/src/modules/experimental/badged-content/examples/2/index.ts, projects/demo/src/modules/experimental/badged-content/examples/3/index.html, projects/demo/src/modules/experimental/badged-content/examples/3/index.less, projects/demo/src/modules/experimental/badged-content/examples/3/index.ts, projects/demo/src/modules/experimental/badged-content/examples/import/import-module.md, projects/demo/src/modules/experimental/badged-content/examples/import/insert-template.md, projects/experimental/components/badge/badge.style.less, projects/experimental/components/badged-content/badged-content.component.ts, projects/experimental/components/badged-content/badged-content.directive.ts, projects/experimental/components/badged-content/badged-content.module.ts, projects/experimental/components/badged-content/badged-content.style.less, projects/experimental/components/badged-content/badged-content.template.html, projects/experimental/components/badged-content/index.ts, projects/experimental/components/badged-content/ng-package.json, projects/experimental/components/index.ts
=> feat(experimental): `BadgedContent` add new component

projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/experimental/compass/compass.component.ts, projects/demo/src/modules/experimental/compass/compass.module.ts, projects/demo/src/modules/experimental/compass/compass.template.html, projects/demo/src/modules/experimental/compass/examples/1/index.ts, projects/demo/src/modules/experimental/compass/examples/2/index.ts, projects/demo/src/modules/experimental/compass/examples/import/import-module.md, projects/demo/src/modules/experimental/compass/examples/import/insert-template.md, projects/experimental/components/compass/compass.component.ts, projects/experimental/components/compass/compass.module.ts, projects/experimental/components/compass/compass.style.less, projects/experimental/components/compass/index.ts, projects/experimental/components/compass/ng-package.json, projects/experimental/components/index.ts
=> feat(experimental): add compass

projects/cdk/utils/dom/index.ts, projects/cdk/utils/dom/retarget-boundary-crossing.ts, projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/core/components/primitive-textfield/primitive-textfield.template.html, projects/demo/src/modules/components/combo-box/examples/2/index.html, projects/demo/src/modules/components/data-list-wrapper/data-list-wrapper.module.ts, projects/demo/src/modules/components/data-list-wrapper/examples/2/index.html, projects/demo/src/modules/components/multi-select/examples/2/index.html, projects/demo/src/modules/components/select/examples/3/index.html, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/input-tag/input-tag.template.html
=> feat(core): should only be focusing on element when navigate from label

projects/cdk/schematics/ng-update/steps/replace-services.ts
=> chore(cdk): `migrations` fix services replacing

projects/addon-doc/components/example/example.style.less
=> fix(addon-doc): example should enclose inner content

projects/addon-table/components/table/pipes/table-sort.pipe.ts
=> fix(addon-table): improve typings for `tuiTableSort`

.github/workflows/create-release.yml
=> ci: add telegram announce

.github/workflows/publish.yml
=> chore: remove hardcoded prefix inside action

.github/workflows/auto-add-to-project.yml, .github/workflows/auto-approve.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-cleanup-caches.yml, .github/workflows/auto-dependency-review.yml, .github/workflows/auto-label.yml, .github/workflows/auto-remove-label.yml, .github/workflows/auto-update-icons.yml, .github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml
=> ci: decomposition action tree

projects/cdk/components/dialog-host/dialog-host.style.less
=> fix(cdk): `Dialog` fix animation in safari

.github/workflows/auto-approve.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-cleanup-caches.yml, .github/workflows/auto-dependency-review.yml, .github/workflows/auto-label.yml, .github/workflows/auto-remove-label.yml, .github/workflows/auto-update-icons.yml, .github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml
=> ci: use own checkout action

package-lock.json, package.json, projects/addon-commerce/utils/test/get-currency-symbol.spec.ts, projects/addon-commerce/utils/test/is-expire-valid.spec.ts, projects/cdk/date-time/test/day.spec.ts, projects/cdk/schematics/ng-update/v3/tests/schematic-migrate-tds.spec.ts, projects/cdk/services/test/static-request.service.spec.ts, projects/cdk/utils/dom/test/point-to-client-rect.spec.ts, projects/cdk/utils/focus/tests/move-focus.spec.ts, projects/cdk/utils/math/test/normalize-to-int-number.spec.ts, projects/core/utils/format/test/get-fractional-part-padded.spec.ts, projects/demo-cypress/cypress/tests/core/dialogs/dialog-browser-back.cy.ts, projects/kit/components/badge/test/badge.component.spec.ts, projects/kit/components/breadcrumbs/test/breadcrumbs.component.spec.ts, projects/kit/components/calendar-month/test/calendar-month.component.spec.ts, projects/kit/components/calendar-range/test/range-calendar.component.spec.ts, projects/kit/components/input-number/test/input-number-format.spec.ts, projects/kit/components/input-number/test/input-number.component.spec.ts, projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts, projects/kit/components/input-time/test/input-time.component.spec.ts, projects/kit/components/textarea/test/text-area.component.spec.ts, projects/kit/components/textarea/test/textarea.component.spec.ts
=> ci: add jest eslint rules

.github/workflows/auto-approve.yml, .github/workflows/build.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/test.yml
=> ci: wait job status before bot approve

.github/workflows/auto-approve.yml, .github/workflows/publish.yml, .github/workflows/validate-tag.yml
=> ci: ignore automerge for release branch

.env
=> chore: remove redundant env

.github/workflows/auto-approve.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-cleanup-caches.yml, .github/workflows/auto-dependency-review.yml, .github/workflows/auto-label.yml, .github/workflows/auto-remove-label.yml, .github/workflows/auto-update-icons.yml, .github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml, projects/cdk/components/scroll-controls/scroll-controls.style.less, projects/cdk/components/scroll-controls/scrollbar.directive.ts, projects/core/components/scroll-controls/scroll-controls.style.less, projects/core/components/scroll-controls/scrollbar.directive.ts
=> fix(core): scrollbar behaviour inside iframe

.github/workflows/auto-approve.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-cleanup-caches.yml, .github/workflows/auto-dependency-review.yml, .github/workflows/auto-label.yml, .github/workflows/auto-remove-label.yml, .github/workflows/auto-update-icons.yml, .github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml
=> ci: use custom actions

projects/core/components/primitive-calendar/primitive-calendar.template.html
=> refactor: indexed expression can be null or undefined

projects/addon-charts/components/bar-chart/bar-chart.component.ts, projects/addon-doc/components/documentation/documentation.component.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/cdk/components/alert-host/alert-host.component.ts, projects/cdk/pipes/filter/filter.pipe.ts, projects/cdk/pipes/filter/test/filter.pipe.spec.ts, projects/cdk/pipes/mapper/mapper.pipe.ts, projects/cdk/pipes/mapper/test/mapper.pipe.spec.ts, projects/cdk/types/mapper.ts, projects/cdk/types/matcher.ts, projects/core/components/calendar/calendar.component.ts, projects/demo/src/modules/charts/line-days-chart/examples/2/index.ts, projects/demo/src/modules/pipes/mapper/examples/2/component.ts, projects/kit/components/calendar-range/calendar-range.component.ts, projects/kit/components/calendar-range/calendar-range.template.html, projects/kit/components/input-date-range/input-date-range.component.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/multi-select/multi-select.component.ts, projects/kit/components/multi-select/native-multi-select/native-multi-select.ts, projects/kit/constants/max-day-range-length-mapper.ts, projects/kit/internal/primitive-calendar-range/primitive-calendar-range.component.ts
=> feat(core): introduces `TypedTuiMapper`

projects/core/components/loader/loader.template.html, projects/demo/src/modules/experimental/button/button.template.html, projects/demo/src/modules/experimental/button/examples/4/index.html, projects/demo/src/modules/experimental/button/examples/4/index.ts, projects/experimental/components/button/button.component.ts, projects/experimental/components/button/button.style.less, projects/experimental/components/button/button.template.html
=> feat(experimental): `Button` improve loading accessibility

package-lock.json, package.json, projects/addon-doc/components/code/code.component.ts, projects/addon-doc/components/documentation/documentation-property-connector.directive.ts, projects/addon-doc/interfaces/page.ts, projects/addon-doc/utils/raw-load.ts, projects/core/tokens/ordered-short-week-days.ts, projects/demo/src/modules/components/avatar/avatar.component.ts, projects/demo/src/modules/components/rating/rating.component.ts, projects/demo/src/modules/components/tag/tag.component.ts, projects/demo/src/modules/experimental/avatar/avatar.component.ts, projects/demo/src/modules/experimental/badge-alert/badge-alert.component.ts, projects/demo/src/modules/experimental/badge/badge.component.ts, projects/demo/src/modules/experimental/badged-content/badged-content.component.ts, projects/demo/src/modules/experimental/button/button.component.ts, projects/demo/src/modules/experimental/compass/compass.component.ts, projects/demo/src/modules/experimental/fade/fade.component.ts, projects/demo/src/modules/experimental/sensitive/sensitive.component.ts, projects/kit/pipes/filter-by-input/filter-by-input-with.pipe.ts, projects/kit/pipes/filter-by-input/filter-by-input.base.ts, projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts
=> ci: require `Tui` prefix for type alias

projects/demo/src/modules/pipes/filter-by-input/examples/3/index.html, projects/demo/src/modules/pipes/filter-by-input/examples/3/index.ts, projects/demo/src/modules/pipes/filter-by-input/filter-by-input.component.ts, projects/demo/src/modules/pipes/filter-by-input/filter-by-input.module.ts, projects/demo/src/modules/pipes/filter-by-input/filter-by-input.template.html, projects/kit/components/multi-select/multi-select.module.ts, projects/kit/pipes/filter-by-input/filter-by-input-with.pipe.ts, projects/kit/pipes/filter-by-input/filter-by-input.base.ts, projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts
=> fix(kit): `FilterByInput` do not reset list on match in multiselect

projects/addon-commerce/enums/currency-code.ts
=> fix(addon-commerce): invalid descriptions in currency code dictionary

projects/demo/src/modules/app/app.providers.ts
=> chore(demo): change `tuiSwipe` options

.github/workflows/create-release.yml, .github/workflows/publish.yml
=> ci: add fetch-depth 0

projects/cdk/directives/value-changes/value-changes.directive.ts
=> fix(cdk): `ValueChanges` add `distinctUntilChanged`

.cspell.json, projects/core/components/loader/loader.style.less, projects/core/styles/mixins/browsers.less, projects/core/styles/mixins/browsers.scss, projects/core/styles/mixins/textfield.less, projects/core/styles/mixins/textfield.scss, projects/core/styles/taiga-ui-local.less, projects/core/styles/taiga-ui-local.scss, projects/core/styles/theme/wrapper/base.less
=> feat(core): add browser specific style mixins

projects/core/components/svg/svg.style.less
=> fix(core): invalid svg alignments in safari

projects/core/components/calendar/calendar.component.ts, projects/core/components/primitive-calendar/primitive-calendar.component.ts, projects/core/components/primitive-year-picker/primitive-year-picker.component.ts, projects/demo/src/modules/components/calendar/calendar.component.ts, projects/demo/src/modules/components/calendar/calendar.module.ts, projects/demo/src/modules/components/calendar/calendar.template.html, projects/demo/src/modules/components/calendar/examples/6/index.html, projects/demo/src/modules/components/calendar/examples/6/index.ts
Closes #3624
https://github.com/taiga-family/taiga-ui/assets/12021443/d21ca214-58a5-4971-845c-bc50ea2f7bd7
=> feat(core): support `readonly TuiDay[]` in `calendar`

projects/demo/src/modules/experimental/surface/examples/7/index.ts
=> chore: fix prettier/eslint conflict

projects/cdk/components/dialog-host/dialog-host.component.ts, projects/core/components/root/root.style.less
=> fix(cdk): prevent page scrolling when a modal is open

projects/experimental/directives/fade/fade.directive.ts, projects/experimental/directives/fade/fade.style.less
=> fix(experimental): `Fade` fix line height issue

package.json
=> chore: include all files for prettier

projects/core/components/svg/svg.style.less
=> fix(core): prevent override height for svg

projects/core/components/svg/svg.style.less
=> chore(revert): revert to previous svg in v3.48

projects/addon-table/components/table/th/th.component.ts, projects/addon-table/components/table/th/th.template.html
Closes [#5064](https://github.com/taiga-family/taiga-ui/issues/5064)
=> feat(addon-table): table column direction reset on third click

projects/demo/src/modules/experimental/badge-alert/examples/2/index.less, projects/demo/src/modules/experimental/badged-content/examples/1/index.html, projects/experimental/components/badge-alert/badge-alert.style.less
=> chore(demo): fix `BadgedContent`, `BadgeAlert` example

projects/demo-cypress/cypress/tests/kit/input-tag/input-tag.cy.ts, projects/demo/src/modules/components/multi-select/examples/11/index.html, projects/demo/src/modules/components/multi-select/examples/11/index.less, projects/demo/src/modules/components/multi-select/examples/11/index.ts, projects/demo/src/modules/components/multi-select/multi-select.component.ts, projects/demo/src/modules/components/multi-select/multi-select.module.ts, projects/demo/src/modules/components/multi-select/multi-select.template.html, projects/kit/components/input-tag/input-tag.style.less, projects/kit/components/input-tag/input-tag.template.html, projects/kit/components/multi-select/multi-select.style.less
=> fix(kit): `MultiSelect` fix incorrect height with multiline value content

projects/kit/components/input-date-range/input-date-range.component.ts, projects/kit/components/input-date-time/input-date-time.component.ts, projects/kit/components/input-date/input-date.component.ts, projects/kit/components/input-number/input-number.component.ts, projects/kit/components/input-time/input-time.component.ts
=> refactor: use nullish coalescing

scripts/publish-canary.ts
=> ci: `TUI_VERSION` must be shipped with the canary release

projects/demo-playwright/tests/kit/multi-select/multi-select.spec.ts, projects/kit/components/input-tag/input-tag.style.less, projects/kit/components/input-tag/input-tag.template.html
=> fix(kit): `Multiselect` fix broken template in non-editable mode

package-lock.json, package.json, projects/addon-charts/components/line-chart/line-chart.component.ts, projects/testing/core/toggle.harness.ts
=> refactor: restrict underscore prefix in class properties

projects/kit/components/multi-select/multi-select.style.less
=> fix(kit): `Multiselect` fix line height in value content

package-lock.json, package.json, projects/demo/tsconfig.server.json, tsconfig.json, tsconfig.spec.json
=> ci: add sharable `@taiga-ui/tsconfig` config

projects/demo/src/modules/components/input-tag/examples/9/index.html, projects/demo/src/modules/components/input-tag/examples/9/index.ts, projects/demo/src/modules/components/input-tag/input-tag.component.ts, projects/demo/src/modules/components/input-tag/input-tag.module.ts, projects/demo/src/modules/components/input-tag/input-tag.template.html
=> chore: add example with maskito and input-tag

projects/addon-commerce/components/thumbnail-card/index.ts, projects/addon-commerce/components/thumbnail-card/thumbnail-card.directive.ts, projects/addon-commerce/components/thumbnail-card/thumbnail-card.module.ts, projects/addon-commerce/components/thumbnail-card/thumbnail-card.providers.ts, projects/demo-cypress/cypress/tests/kit/input/input.cy.ts, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/input/examples/3/index.html, projects/demo/src/modules/components/input/examples/3/index.ts, projects/demo/src/modules/components/input/input.module.ts, projects/demo/src/modules/components/input/input.template.html, projects/demo/src/modules/components/thumbnail-card/examples/4/index.html, projects/demo/src/modules/components/thumbnail-card/examples/4/index.less, projects/demo/src/modules/components/thumbnail-card/examples/4/index.ts, projects/demo/src/modules/components/thumbnail-card/thumbnail-card.component.ts, projects/demo/src/modules/components/thumbnail-card/thumbnail-card.module.ts, projects/demo/src/modules/components/thumbnail-card/thumbnail-card.template.html, projects/kit/components/input/input.component.ts, projects/kit/directives/index.ts, projects/kit/directives/unmask-handler/index.ts, projects/kit/directives/unmask-handler/ng-package.json, projects/kit/directives/unmask-handler/unmask-handler.directive.ts, projects/kit/directives/unmask-handler/unmask-handler.module.ts
=> feat(kit): `UnmaskHandler` add new directive

projects/demo/src/index.html
=> chore(demo): improve accessibility

projects/experimental/components/checkbox/checkbox.options.ts, projects/experimental/components/toggle/toggle.options.ts, projects/kit/directives/unmask-handler/unmask-handler.directive.ts
=> chore: fix merge conflicts

projects/cdk/abstract/portal-host.ts, projects/core/directives/dropdown/dropdown-position.directive.ts, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/customization/viewport/examples/1/index.html, projects/demo/src/modules/customization/viewport/examples/1/index.less, projects/demo/src/modules/customization/viewport/examples/1/index.ts, projects/demo/src/modules/customization/viewport/examples/2/index.html, projects/demo/src/modules/customization/viewport/examples/2/index.ts, projects/demo/src/modules/customization/viewport/examples/2/portal-host.ts, projects/demo/src/modules/customization/viewport/examples/import/providers.md, projects/demo/src/modules/customization/viewport/viewport.component.ts, projects/demo/src/modules/customization/viewport/viewport.module.ts, projects/demo/src/modules/customization/viewport/viewport.template.html
=> chore(demo): add example about viewport and dropdown

projects/demo/src/modules/components/tab-bar/examples/1/index.html, projects/demo/src/modules/components/tab-bar/examples/1/index.less, projects/demo/src/modules/components/tab-bar/examples/1/index.ts
=> chore(demo): add `env(safe-area-inset-bottom)`

.github/workflows/e2e.yml
=> chore: remove invalid path on e2e

scripts/publish-canary.ts
=> ci: incorrect canary version

projects/cdk/constants/used-icons.ts, projects/demo/used-icons.ts, scripts/generate-used-icons.ts
=> chore: generate used icons as const

projects/core/components/notification/notification.style.less
=> fix(core): auto break words in notification

projects/demo-cypress/cypress/tests/addon-table/table-pagination/table-pagination.cy.ts, projects/demo-cypress/cypress/tests/core/data-list/data-list.cy.ts, projects/demo-playwright/tests/addon-mobile/mobile-calendar/mobile-calendar.spec.ts
=> chore: add some timeouts for prevent flaky

projects/demo-cypress/cypress/tests/core/dropdown/dropdown.cy.ts, projects/demo-playwright/tests/kit/slider/slider.spec.ts
=> chore: fix proprietary e2e

projects/core/components/root/root.style.less
=> chore: revert small fixes

.cspell.json, projects/addon-commerce/utils/payment-system-icons.ts, projects/cdk/constants/used-icons.ts, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/experimental/thumbnail-card/examples/1/index.html, projects/demo/src/modules/experimental/thumbnail-card/examples/1/index.less, projects/demo/src/modules/experimental/thumbnail-card/examples/1/index.ts, projects/demo/src/modules/experimental/thumbnail-card/examples/2/index.html, projects/demo/src/modules/experimental/thumbnail-card/examples/2/index.less, projects/demo/src/modules/experimental/thumbnail-card/examples/2/index.ts, projects/demo/src/modules/experimental/thumbnail-card/examples/3/index.html, projects/demo/src/modules/experimental/thumbnail-card/examples/3/index.less, projects/demo/src/modules/experimental/thumbnail-card/examples/3/index.ts, projects/demo/src/modules/experimental/thumbnail-card/examples/import/customize-styles.md, projects/demo/src/modules/experimental/thumbnail-card/examples/import/import-module.md, projects/demo/src/modules/experimental/thumbnail-card/examples/import/insert-template.md, projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.component.ts, projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.module.ts, projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.template.html, projects/demo/used-icons.ts, projects/experimental/components/index.ts, projects/experimental/components/thumbnail-card/index.ts, projects/experimental/components/thumbnail-card/ng-package.json, projects/experimental/components/thumbnail-card/thumbnail-card.component.ts, projects/experimental/components/thumbnail-card/thumbnail-card.module.ts, projects/experimental/components/thumbnail-card/thumbnail-card.style.less, projects/experimental/components/thumbnail-card/thumbnail-card.template.html, projects/experimental/package.json
=> feat(experimental): `ThumbnailCard` add new component

projects/core/components/root/root.component.ts, projects/core/providers/is-mobile-resolution.provider.ts, projects/core/services/breakpoint.service.ts
=> feat(core): use `TuiBreakpointService` instead of `TUI_IS_MOBILE_RES`

projects/addon-charts/components/bar-chart/bar-chart.component.ts, projects/addon-doc/components/documentation/documentation.component.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/addon-table/components/table/tbody/tbody.component.ts, projects/cdk/components/alert-host/alert-host.component.ts, projects/cdk/pipes/filter/filter.pipe.ts, projects/cdk/pipes/filter/test/filter.pipe.spec.ts, projects/cdk/pipes/mapper/mapper.pipe.ts, projects/cdk/pipes/mapper/test/mapper.pipe.spec.ts, projects/cdk/types/mapper.ts, projects/cdk/types/matcher.ts, projects/core/components/calendar/calendar.component.ts, projects/demo/src/modules/charts/line-days-chart/examples/2/index.ts, projects/demo/src/modules/pipes/mapper/examples/2/component.ts, projects/experimental/components/checkbox/checkbox.options.ts, projects/experimental/components/toggle/toggle.options.ts, projects/kit/components/calendar-range/calendar-range.component.ts, projects/kit/components/input-date-range/input-date-range.component.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/multi-select/multi-select.component.ts, projects/kit/components/multi-select/native-multi-select/native-multi-select.ts, projects/kit/constants/max-day-range-length-mapper.ts, projects/kit/directives/unmask-handler/unmask-handler.directive.ts, projects/kit/internal/primitive-calendar-range/primitive-calendar-range.component.ts
=> fix(cdk): revert breaking changes with `TuiMapper`

nx.json
=> ci: add new nx token

scripts/publish-canary.ts
=> chore: revert changes for canary release

projects/demo-playwright/tests/demo/get-demo-paths.ts
=> chore(demo): fix e2e problem

projects/core/components/dialog/test/dialog.component.spec.ts, projects/testing/core/dialog.harness.ts, projects/testing/core/index.ts
=> feat(testing): adds harness for dialog

projects/addon-mobile/components/sheet/sheet-options.ts, projects/addon-mobile/components/sheet/sheet.directive.ts, projects/addon-mobile/components/sheet/sheet.module.ts, projects/addon-mobile/components/sheet/sheet.service.ts, projects/addon-mobile/components/sheet/sheet.ts, projects/demo/src/modules/components/sheet/sheet.template.html
=> chore(demo): deprecated sheet

projects/demo-playwright/utils/mock-images.ts
=> chore: add stub

projects/demo/src/modules/app/landing/landing.component.ts
=> chore(demo): prevent multiple observe intersection targets

package-lock.json, projects/icons/package.json
=> chore: remove redundant deps

package-lock.json, projects/addon-doc/package.json, projects/cdk/package.json, projects/cdk/schematics/ng-add/index.ts, projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts, projects/cdk/schematics/ng-add/steps/wrap-with-tui-root.ts, projects/cdk/schematics/ng-update/v3-36/index.ts, projects/cdk/schematics/ng-update/v3/index.ts, projects/cdk/schematics/ng-update/v3/steps/migrate-taiga-proprietary-icons.ts, projects/cdk/schematics/utils/get-projects.ts
=> chore: npm dedupe schematics packages

README.md, SECURITY.md
=> chore: refactor README.md

projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/index.ts, projects/cdk/schematics/ng-update/v4/steps/templates/toggles/common.ts, projects/cdk/schematics/ng-update/v4/steps/templates/toggles/index.ts, projects/cdk/schematics/ng-update/v4/steps/templates/toggles/migrate-checkbox.ts, projects/cdk/schematics/ng-update/v4/steps/templates/toggles/migrate-radio.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-checkbox.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-radio.spec.ts
=> chore: add checkbox and radio migration

projects/demo/src/modules/components/dialog/dialog.component.ts
Appearance setting in the demo do nothing
Appearance setting in the demo passed to the dialog
=> chore(demo): fixed passing appearance to the dialog

projects/kit/components/toggle/toggle.style.less
[related](https://github.com/taiga-family/taiga-ui/pull/5460/files#diff-f529784f4d87c84303121b5104af2daee1e7ee9c77bb5c63b8bf6a3942a13ab5R47)
=> fix(kit): `Toggle` fix loader position

projects/demo/src/modules/info/related/related.template.html
=> chore: fixup link

projects/cdk/schematics/ng-update/interfaces/html-comment.ts, projects/cdk/schematics/ng-update/interfaces/index.ts, projects/cdk/schematics/ng-update/utils/templates/index.ts, projects/cdk/schematics/ng-update/utils/templates/template-comments.ts, projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/index.ts, projects/cdk/schematics/ng-update/v4/steps/constants/inputs-to-remove.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/toggles/index.ts, projects/cdk/schematics/ng-update/v4/steps/templates/toggles/migrate-toggle.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-toggle.spec.ts
=> chore: add toggle migration

projects/core/components/notification/test/notification.component.spec.ts, projects/core/components/primitive-calendar/test/primitive-calendar.component.spec.ts, projects/kit/components/input-date/test/input-date.component.spec.ts, projects/kit/components/toggle/test/toggle.component.spec.ts
=> refactor: require only one top level describe

projects/cdk/schematics/ng-update/interfaces/index.ts, projects/cdk/schematics/ng-update/interfaces/replacement-attribute-to-directive.ts, projects/cdk/schematics/ng-update/utils/templates/replace-attrs-by-directives.ts, projects/cdk/schematics/ng-update/v3/constants/templates.ts, projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/index.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-textfield-controller.spec.ts, projects/cdk/schematics/utils/add-import-to-closest-module.ts, projects/cdk/schematics/utils/angular/is-standalone-component.ts
=> chore(cdk): `schematics` add prefix, postfix, filler migration

package-lock.json, projects/cdk/package.json
=> fix(cdk): remove redundant dependencies

projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
Closes #5798
Closes https://github.com/taiga-family/taiga-ui/issues/4788
=> fix(core): expression has changed after it was checked

projects/demo-playwright/tests/demo/is-flaky-examples.ts
=> chore(demo-playwright): exclude `experimental/icon#duo` example from playwright tests

projects/demo/src/index.html, projects/demo/src/modules/app/landing/landing.component.ts, projects/demo/src/modules/app/landing/landing.template.html
=> chore(demo): improve LCP for Google Speed test

projects/core/directives/dropdown/dropdown.component.ts
=> chore: small refactor

projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/progress-segmented/progress-segmented.template.html, projects/demo/src/modules/experimental/progress-segmented/examples/1/index.html, projects/demo/src/modules/experimental/progress-segmented/examples/1/index.ts, projects/demo/src/modules/experimental/progress-segmented/examples/2/index.html, projects/demo/src/modules/experimental/progress-segmented/examples/2/index.less, projects/demo/src/modules/experimental/progress-segmented/examples/2/index.ts, projects/demo/src/modules/experimental/progress-segmented/examples/3/index.html, projects/demo/src/modules/experimental/progress-segmented/examples/3/index.less, projects/demo/src/modules/experimental/progress-segmented/examples/3/index.ts, projects/demo/src/modules/experimental/progress-segmented/examples/4/index.html, projects/demo/src/modules/experimental/progress-segmented/examples/4/index.less, projects/demo/src/modules/experimental/progress-segmented/examples/4/index.ts, projects/demo/src/modules/experimental/progress-segmented/examples/import/import-module.md, projects/demo/src/modules/experimental/progress-segmented/examples/import/insert-template.md, projects/demo/src/modules/experimental/progress-segmented/progress-segmented.component.ts, projects/demo/src/modules/experimental/progress-segmented/progress-segmented.module.ts, projects/demo/src/modules/experimental/progress-segmented/progress-segmented.template.html, projects/experimental/directives/index.ts, projects/experimental/directives/progress-segmented/index.ts, projects/experimental/directives/progress-segmented/ng-package.json, projects/experimental/directives/progress-segmented/progress-segmented.component.ts, projects/experimental/directives/progress-segmented/progress-segmented.directive.ts, projects/experimental/directives/progress-segmented/progress-segmented.module.ts, projects/experimental/directives/progress-segmented/progress-segmented.style.less, projects/kit/components/progress/progress-bar/progress-bar.component.less, projects/kit/components/progress/progress-segmented/progress-segmented.component.ts
```html
<tui-progress-segmented
[max]="5"
[value]="3"
></tui-progress-segmented>
```
```html
<progress
tuiProgressBar
[max]="5"
[segments]="5"
[value]="3"
></progress>
```
=> feat(experimental): new version of `ProgressSegmented`

projects/demo/src/modules/components/sheet/examples/4/index.html, projects/demo/src/modules/directives/sidebar/examples/1/index.html, projects/demo/src/modules/info/ssr/ssr.template.html
=> chore(demo): fix links

projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts
=> fix(cdk): add Angular 17 support for schematic `ng add taiga-ui`

projects/cdk/utils/focus/is-native-focused-in.ts, projects/cdk/utils/focus/is-native-focused.ts
https://github.com/taiga-family/taiga-ui/assets/12021443/efa3f516-6346-41e4-92cc-c0a0ac4125e0
Part of #5845
https://github.com/taiga-family/taiga-ui/assets/12021443/85a8aa50-704c-45c0-babd-0084f2b1f9b0
=> feat(cdk): check document has focus after leave iframe

package-lock.json, package.json
=> chore: support web types autocompletion in IDEA

projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts, projects/demo/src/modules/tables/table-pagination/table-pagination.template.html
=> chore(cdk): `TablePagination` add migration, fix api doc

projects/styles/project.json, scripts/postbump.ts, scripts/publish-canary.ts, scripts/shared/bump-tui-deps.ts, scripts/shared/ignorable-packages.ts, scripts/shared/is-tui-package-name.ts, scripts/shared/sync-versions.ts, scripts/shared/update-package-json-structure.ts
=> ci: sync canary release with dependencies

projects/demo/src/modules/app/home/examples/app-standalone.md, projects/demo/src/modules/app/home/examples/main-standalone-optional.md, projects/demo/src/modules/app/home/examples/main-standalone.md, projects/demo/src/modules/components/push/examples/import/import-module.md, projects/demo/src/modules/components/push/push.template.html
=> chore(demo): improve documentation for standalone components

projects/demo/src/modules/icons/icons-group/icons-group.component.ts, projects/demo/src/modules/icons/icons-group/icons-group.template.html, projects/demo/src/modules/icons/icons.component.ts, projects/demo/src/modules/icons/icons.style.less, projects/demo/src/modules/icons/icons.template.html
=> chore(demo): add debounce

package.json, projects/addon-table/directives/table-filters/generic-filter.directive.ts, projects/cdk/schematics/ng-update/steps/replace-identifier.ts, projects/demo/src/modules/tables/table/examples/4/index.ts, projects/demo/src/modules/tables/table/examples/5/index.ts
=> ci: add `functional` eslint plugin

projects/kit/components/line-clamp/line-clamp.component.ts, projects/kit/components/select-option/select-option.component.ts
=> ci: enable `@angular-eslint/sort-lifecycle-methods`

projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts, projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
=> fix(addon-mobile): `SheetDialog` add missing label divider

projects/demo/src/modules/icons/icons-group/icons-group.style.less, projects/demo/src/modules/icons/icons.style.less
=> chore(demo): correct icon size on demo

projects/kit/components/input-tag/input-tag.component.ts
=> fix(kit): expression has changed in inputTag

projects/demo/src/modules/app/landing/landing.component.ts, projects/demo/src/modules/app/landing/landing.template.html
=> chore(demo): improve UX for landing page

.github/workflows/bundle-size-tracking.yml, .github/workflows/snapshots.yml, projects/demo/project.json, projects/demo/webpack.config.ts, projects/demo/webpack.server.config.ts
=> ci: enable prerender for production build

.env, .github/workflows/auto-add-to-project.yml, .github/workflows/auto-approve.yml, .github/workflows/auto-author-assign.yml, .github/workflows/auto-cleanup-caches.yml, .github/workflows/auto-dependency-review.yml, .github/workflows/auto-label.yml, .github/workflows/auto-remove-label.yml, .github/workflows/auto-update-icons.yml, .github/workflows/build.yml, .github/workflows/bundle-size-tracking.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-release.yml, .github/workflows/deploy-gh-pages.yml, .github/workflows/deploy-preview.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/publish-canary.yml, .github/workflows/publish.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, .github/workflows/validate-tag.yml
=> ci: correct node environments for CI

projects/demo/src/modules/app/app.providers.ts, projects/demo/src/modules/icons/icons-group/icons-group.style.less, projects/demo/src/modules/icons/icons-group/icons-group.template.html
=> chore(demo): align text

package-lock.json, package.json, projects/experimental/directives/progress-segmented/progress-segmented.style.less, projects/kit/components/progress/progress-bar/progress-bar.component.less
=> chore: drop some redundant `stylelint-disable meowtec/no-px`

projects/demo/src/modules/experimental/progress-segmented/examples/5/index.html, projects/demo/src/modules/experimental/progress-segmented/examples/5/index.less, projects/demo/src/modules/experimental/progress-segmented/examples/5/index.ts, projects/demo/src/modules/experimental/progress-segmented/progress-segmented.component.ts, projects/demo/src/modules/experimental/progress-segmented/progress-segmented.module.ts, projects/demo/src/modules/experimental/progress-segmented/progress-segmented.template.html, projects/experimental/directives/progress-segmented/progress-segmented.style.less
=> feat(experimental): `ProgressSegmented` can be customized to have no round corners

projects/demo/project.json
=> chore(demo): remove redundant scripts

projects/demo-playwright/tests/core/primitive-textfield/primitive-textfield.spec.ts, projects/demo-playwright/tests/kit/tree/tree.spec.ts
**01-hint.png:**
<br/>
**01-programmatic-control.png:**
<br/>
<br/>
**01-hint.png:**
**01-programmatic-control.png:**
=> chore(demo-playwright): small screenshot tests refactor

projects/demo/src/modules/components/progress-circle/examples/5/index.html, projects/demo/src/modules/components/progress-circle/examples/5/index.less, projects/demo/src/modules/components/progress-circle/examples/5/index.ts, projects/demo/src/modules/components/progress-circle/progress-circle.component.ts, projects/demo/src/modules/components/progress-circle/progress-circle.module.ts, projects/demo/src/modules/components/progress-circle/progress-circle.template.html
=> chore(demo): add example how to customize `ProgressCircle` to have anti-clockwise direction

projects/demo/src/modules/components/progress-circle/examples/2/index.html, projects/demo/src/modules/components/progress-circle/examples/2/index.less, projects/demo/src/modules/components/progress-circle/examples/2/index.ts, projects/demo/src/modules/components/progress-circle/progress-circle.module.ts, projects/demo/src/modules/components/progress-circle/progress-circle.template.html, projects/kit/components/progress/progress-circle/progress-circle.component.ts, projects/kit/components/progress/progress-circle/progress-circle.style.less
=> feat(kit): `ProgressCircle` has new sizes (add `new` attribute to enable them)

package.json
=> ci: fix integration problem

projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/experimental/button-vertical/button-vertical.component.ts, projects/demo/src/modules/experimental/button-vertical/button-vertical.module.ts, projects/demo/src/modules/experimental/button-vertical/button-vertical.template.html, projects/demo/src/modules/experimental/button-vertical/examples/1/index.html, projects/demo/src/modules/experimental/button-vertical/examples/1/index.less, projects/demo/src/modules/experimental/button-vertical/examples/1/index.ts, projects/demo/src/modules/experimental/button-vertical/examples/2/index.html, projects/demo/src/modules/experimental/button-vertical/examples/2/index.less, projects/demo/src/modules/experimental/button-vertical/examples/2/index.ts, projects/demo/src/modules/experimental/button-vertical/examples/import/import-module.md, projects/demo/src/modules/experimental/button-vertical/examples/import/insert-template.md, projects/experimental/components/button/button.style.less, projects/experimental/directives/button-vertical/button-vertical.component.ts, projects/experimental/directives/button-vertical/button-vertical.directive.ts, projects/experimental/directives/button-vertical/button-vertical.module.ts, projects/experimental/directives/button-vertical/button-vertical.style.less, projects/experimental/directives/button-vertical/index.ts, projects/experimental/directives/button-vertical/ng-package.json, projects/experimental/directives/index.ts, projects/experimental/directives/sensitive/sensitive.module.ts
=> feat(experimental): `ButtonVertical` add new directive

projects/kit/components/badged-content/badged-content.component.ts
=> refactor: use const

projects/demo/src/modules/app/landing/landing.component.ts, projects/demo/src/modules/app/landing/landing.style.less, projects/demo/src/modules/app/landing/landing.template.html
=> chore(demo): small changes on landing page

projects/addon-mobile/ng-package.json, projects/addon-mobile/styles/android/toggle.less, projects/addon-mobile/styles/ios/toggle.less, projects/addon-mobile/styles/taiga-ui-mobile.less, projects/cdk/directives/platform/platform.directive.ts, projects/demo/src/modules/app/app.style.less, projects/demo/src/modules/experimental/toggle/examples/1/index.html, projects/experimental/components/toggle/toggle.component.ts, projects/experimental/components/toggle/toggle.style.less
=> feat(addon-mobile): initial mobile theme

projects/demo/src/modules/components/progress-circle/examples/5/index.less, projects/demo/src/modules/components/progress-circle/examples/5/index.ts, projects/demo/src/modules/components/progress-circle/examples/6/index.html, projects/demo/src/modules/components/progress-circle/examples/6/index.less, projects/demo/src/modules/components/progress-circle/examples/6/index.ts, projects/demo/src/modules/components/progress-circle/progress-circle.component.ts, projects/demo/src/modules/components/progress-circle/progress-circle.module.ts, projects/demo/src/modules/components/progress-circle/progress-circle.template.html
=> chore(demo): add `Dynamic color` example for `ProgressCircle`

projects/demo/src/modules/experimental/icon/examples/import/insert-template.md
=> chore: fix icon doc

projects/demo/src/modules/components/input-files/input-files.component.ts, projects/demo/src/modules/components/input-files/input-files.template.html, projects/kit/components/files/file/file.component.ts, projects/kit/components/files/file/file.style.less
=> feat(kit): change `showDelete` type to `boolean | 'always'` in tui-file

projects/demo/src/modules/components/progress-circle/examples/4/index.less, projects/demo/src/modules/components/progress-circle/examples/7/index.html, projects/demo/src/modules/components/progress-circle/examples/7/index.less, projects/demo/src/modules/components/progress-circle/examples/7/index.ts, projects/demo/src/modules/components/progress-circle/progress-circle.component.ts, projects/demo/src/modules/components/progress-circle/progress-circle.module.ts, projects/demo/src/modules/components/progress-circle/progress-circle.template.html
=> chore(demo): add `Thickness` example for `ProgressCircle`

projects/demo/src/modules/app/landing/landing.style.less
https://github.com/taiga-family/taiga-ui/assets/12021443/6bf628b0-94eb-4eb4-a949-b6540dbca6cd
https://github.com/taiga-family/taiga-ui/assets/12021443/85191f29-a1d7-4b78-8007-3b3501676467
=> chore(demo): don't use Manrope font for heading on landing page

projects/demo-playwright/tests/kit/combo-box/combobox.spec.ts, projects/demo/src/modules/components/combo-box/combo-box.component.ts, projects/demo/src/modules/components/combo-box/combo-box.module.ts, projects/demo/src/modules/components/combo-box/combo-box.template.html, projects/demo/src/modules/components/combo-box/examples/7/index.html, projects/demo/src/modules/components/combo-box/examples/7/index.ts, projects/kit/components/select-option/select-option.component.ts
=> fix(kit): don't allow disabled options to be selected

projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
=> refactor: scroll-blocking

projects/experimental/components/button/button.style.less
=> chore: icon size fix

projects/addon-doc/components/code/code.style.less, projects/addon-doc/components/code/code.template.html, projects/addon-doc/components/code/tests/code.component.spec.ts, projects/addon-doc/components/example/example.style.less, projects/demo/src/modules/app/stackblitz/starter/stackblitz-edit-button.component.less, projects/demo/src/modules/app/stackblitz/starter/stackblitz-edit-button.component.ts, projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.module.ts
=> feat(addon-doc): improve code block

projects/demo/src/modules/icons/icons.tokens.ts
=> chore(demo): fix runtime error

.github/workflows/snapshots.yml
=> chore: manual update main snapshots

projects/cdk/utils/svg/svg-linear-gradient-processor.ts
=> chore: mark deprecated

projects/demo/src/index.html, projects/demo/src/modules/app/app.tabs.ts, projects/demo/src/modules/components/data-list/examples/1/index.ts, projects/demo/src/modules/components/dialog/dialog.template.html, projects/demo/src/modules/directives/auto-focus/auto-focus.template.html, projects/demo/src/modules/markup/colors/colors.constants.ts, projects/demo/src/modules/services/breakpoint/breakpoint.template.html, projects/demo/src/polyfills.ts
=> chore(demo): remove unused polyfills

projects/cdk/package.json
=> fix(cdk): add `@taiga-ui/experimental` to ng-update package group

projects/demo/src/modules/experimental/badge/badge.template.html, projects/demo/src/modules/experimental/badge/examples/3/index.html, projects/demo/src/modules/experimental/badge/examples/4/index.html, projects/demo/src/modules/experimental/badge/examples/5/index.html, projects/experimental/components/badge/badge.module.ts, projects/experimental/components/badge/badge.style.less, projects/experimental/components/button/button.directive.ts, projects/experimental/components/button/button.module.ts, projects/experimental/components/button/button.style.less, projects/experimental/components/icon/icon.style.less, projects/experimental/directives/icons/icons.component.ts, projects/experimental/directives/icons/icons.directive.ts, projects/experimental/directives/icons/icons.module.ts, projects/experimental/directives/icons/icons.styles.less, projects/experimental/directives/icons/index.ts, projects/experimental/directives/icons/ng-package.json, projects/experimental/directives/index.ts
=> feat(experimental): `Icons` add new directive

projects/demo-playwright/tests/addon-table/table-pagination/table-pagination.spec.ts, projects/demo-playwright/utils/page-objects/documentation-page.po.ts, projects/demo-playwright/utils/page-objects/table-pagination-page.po.ts
Relates to https://github.com/taiga-family/taiga-ui/pull/5664
=> chore(demo-playwright): refactor `table-pagination.spec.ts`

projects/demo-cypress/cypress/tests/kit/input-files/input-files.cy.ts
=> chore(demo-cypress): improve test for `InputFiles`

projects/cdk/schematics/ng-update/v3/constants/warnings.ts
=> chore(cdk): fix schematic warning for legacy `TuiInputSearchModule`

projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
=> chore: fix member-ordering by eslint

projects/demo/src/modules/icons/icons-group/icons-group.component.ts
=> chore: don't use share for icons group sections

.cspell.json, projects/core/styles/mixins/slider.less, projects/kit/components/input-slider/input-slider.style.less, projects/kit/components/range/range.style.less, projects/kit/components/slider/helpers/slider-thumb-label/slider-thumb-label.component.ts, projects/kit/components/slider/slider.component.ts, projects/kit/components/slider/slider.style.less
=> feat(kit): `Slider` new design

projects/demo-cypress/cypress/tests/kit/input-number/input-number.cy.ts, projects/demo-cypress/cypress/tests/kit/input-range/input-range.cy.ts, projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts, projects/demo-playwright/tests/kit/input-slider/input-slider.spec.ts
=> chore: remove redundant lines

scripts/combine-playwright-failed-screenshots.ts
=> chore: remove eslint-disable

projects/core/components/theme-night/theme-night.style.less, projects/core/styles/mixins/mixins.less, projects/core/styles/theme/variables.less
=> feat(core): add shadow css variables

projects/addon-doc/components/internal/header/header.style.less
https://github.com/taiga-family/taiga-ui/assets/12021443/b3fd1ddb-22f4-4200-9c0d-961b10a53e53
=> feat(addon-doc): add ios beauty effect for header component

projects/addon-doc/components/copy/copy.style.less
=> fix(addon-doc): add border radius for copy element

nx.json, projects/cdk/constants/test/handler.spec.ts
=> ci: trouble with nx cache for spec/cy files

jest.config.ts, package-lock.json, projects/cdk/observables/test/is-alive.spec.ts, projects/cdk/project.json, projects/cdk/schematics/tsconfig.schematics.json, projects/cdk/schematics/tsconfig.spec.json, projects/testing/package.json, projects/testing/utils/input/cleaner.unit-common.ts, tsconfig.spec.json
Schematic tests are running separately via jasmine
Schematic tests are running together with cdk tests via jest. Jasmine dependency dropped.
=> fix(testing): remove jasmine dependency

projects/demo-playwright/tests/kit/input-phone/input-phone.spec.ts, projects/demo-playwright/utils/page-objects/index.ts, projects/demo-playwright/utils/page-objects/input-phone.po.ts, projects/kit/components/input-phone/input-phone.component.ts, projects/kit/components/input-phone/test/input-phone.component.spec.ts
=> fix(kit): prevent clear country code prefix

projects/experimental/components/tooltip/tooltip.component.ts
=> chore: `Tooltip` add TODO about turning to directive

projects/demo/src/modules/app/stackblitz/starter/files/index.html.md
=> chore(demo): small fix

projects/addon-doc/components/main/main.style.less
=> feat(addon-doc): add color for attrs

projects/addon-mobile/styles/common/badge.less, projects/core/styles/mixins/mixins.less, projects/core/styles/mixins/mixins.scss, projects/core/styles/theme/appearance/icon.less, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/experimental/badge/badge.component.ts, projects/demo/src/modules/experimental/badge/examples/1/index.html, projects/demo/src/modules/experimental/badge/examples/1/index.less, projects/demo/src/modules/experimental/chip/chip.module.ts, projects/demo/src/modules/experimental/sensitive/examples/1/index.html, projects/demo/src/modules/experimental/sensitive/examples/1/index.less, projects/demo/src/modules/experimental/sensitive/examples/1/index.ts, projects/demo/src/modules/experimental/sensitive/examples/2/index.html, projects/demo/src/modules/experimental/sensitive/examples/2/index.less, projects/demo/src/modules/experimental/sensitive/examples/2/index.ts, projects/demo/src/modules/experimental/sensitive/sensitive.component.ts, projects/demo/src/modules/experimental/sensitive/sensitive.template.html, projects/experimental/components/badge/badge.directive.ts, projects/experimental/components/badge/badge.style.less, projects/experimental/components/button/button.style.less, projects/experimental/components/chip/chip.directive.ts, projects/experimental/components/chip/chip.style.less, projects/experimental/directives/button-vertical/button-vertical.style.less, projects/experimental/directives/icons/icons.styles.less, projects/experimental/directives/sensitive/sensitive.style.less
=> chore: fix gaps in safari

projects/core/directives/hint/hint-driver.directive.ts, projects/core/directives/hint/hint-hover.directive.ts, projects/core/directives/hint/hint-position.directive.ts, projects/core/directives/hint/hint-unstyled.component.ts, projects/core/directives/hint/hint.component.ts, projects/core/directives/hint/hint.directive.ts, projects/core/directives/hint/hint.module.ts, projects/core/directives/hint/index.ts, projects/demo/src/modules/app/app.template.html, projects/demo/src/modules/directives/hint/examples/2/index.html, projects/demo/src/modules/directives/hint/examples/2/index.less, projects/demo/src/modules/directives/hint/examples/2/index.ts, projects/demo/src/modules/directives/hint/hint.component.ts, projects/demo/src/modules/directives/hint/hint.module.ts, projects/demo/src/modules/directives/hint/hint.template.html, projects/experimental/components/chip/chip.style.less
=> feat(core): `*tuiHint` add new directive for customizing hint bubble

projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.component.ts, projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.template.html, projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.template.html, projects/demo-playwright/tests/addon-mobile/mobile-calendar/input-date.spec.ts, projects/i18n/interfaces/language.ts, projects/i18n/languages/chinese/kit.ts, projects/i18n/languages/dutch/kit.ts, projects/i18n/languages/english/kit.ts, projects/i18n/languages/french/kit.ts, projects/i18n/languages/german/kit.ts, projects/i18n/languages/italian/kit.ts, projects/i18n/languages/kazakh/kit.ts, projects/i18n/languages/polish/kit.ts, projects/i18n/languages/portuguese/kit.ts, projects/i18n/languages/russian/kit.ts, projects/i18n/languages/spanish/kit.ts, projects/i18n/languages/turkish/kit.ts, projects/i18n/languages/ukrainian/kit.ts, projects/i18n/languages/vietnamese/kit.ts, projects/kit/components/input-date-multi/input-date-multi.component.ts, projects/kit/components/input-date-range/input-date-range.component.ts, projects/kit/components/input-date/input-date.component.ts, projects/kit/interfaces/mobile-calendar-data.ts, projects/kit/utils/date/update.ts
=> fix(kit): correct resolve date range in mobile calendar

projects/addon-doc/tokens/scroll-behavior.ts, projects/core/components/root/root.component.ts, projects/core/styles/mixins/mixins.less, projects/demo-cypress/cypress/plugins/index.ts, projects/demo-cypress/cypress/support/helpers/visit.ts, projects/demo-playwright/playwright.config.ts, projects/demo/src/modules/app/app.providers.ts, projects/demo/src/modules/app/cypress.less, projects/demo/src/modules/components/tabs/examples/9/index.less, projects/kit/components/input-tag/input-tag.style.less
=> ci: reduce motion on e2e by default

projects/addon-doc/components/main/main.style.less
=> chore(demo): improve hljs color for properties

projects/addon-doc/components/page/page.style.less
=> feat(addon-doc): use white color for deprecated tag

projects/demo/src/modules/info/related/related.style.less
=> chore(demo): invalid styles on dark theme

nx.json, package.json
=> ci: enable some Nx options

projects/addon-doc/components/doc-tab/doc-tab.component.ts
=> chore: lint

projects/demo/src/modules/components/push/push.component.ts, projects/demo/src/modules/components/push/push.template.html, projects/kit/components/push/push.component.ts, projects/kit/components/push/push.options.ts, projects/kit/components/push/push.template.html
=> feat(kit): `Push` allow string in timestamp for custom formatting

projects/addon-commerce/utils/get-payment-system.ts, projects/addon-commerce/utils/test/get-payment-system.spec.ts
=> fix(addon-commerce): treat US Diners as Mastercard internationally

projects/demo/src/modules/components/tabs/examples/5/index.html, projects/demo/src/modules/components/tabs/examples/5/index.ts, projects/demo/src/modules/components/tabs/tabs.module.ts, projects/kit/components/tabs/tabs-with-more/tabs-with-more.style.less, projects/kit/components/tabs/tabs-with-more/tabs-with-more.template.html
=> chore(demo): fix example

projects/addon-doc/components/documentation/documentation.style.less, projects/addon-doc/components/documentation/documentation.template.html, projects/addon-doc/components/main/main.style.less, projects/demo/src/modules/components/notification/examples/1/index.html
=> feat(addon-doc): improve code block ui

projects/core/directives/dropdown/dropdown-selection.directive.ts
Closes https://github.com/taiga-family/tui-editor/issues/580
=> fix(core): use immutable range for trigger stream in Safari

projects/demo/src/modules/components/mobile-calendar/examples/4/index.html, projects/demo/src/modules/components/mobile-calendar/examples/4/index.less, projects/demo/src/modules/components/mobile-calendar/examples/4/index.ts, projects/demo/src/modules/components/mobile-calendar/examples/5/index.html, projects/demo/src/modules/components/mobile-calendar/examples/5/index.less, projects/demo/src/modules/components/mobile-calendar/examples/5/index.ts, projects/demo/src/modules/components/mobile-calendar/mobile-calendar.component.ts, projects/demo/src/modules/components/mobile-calendar/mobile-calendar.module.ts, projects/demo/src/modules/components/mobile-calendar/mobile-calendar.template.html, projects/kit/utils/date/update.ts
=> feat(kit): support null in `tuiImmutableUpdateInputDateMulti`

projects/addon-doc/components/example/example.style.less, projects/addon-doc/components/main/main.style.less, projects/addon-doc/components/navigation/navigation.component.ts, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/styles.less
Part of https://github.com/taiga-family/taiga-ui/pull/6077
=> feat(addon-doc): use `anchorScrolling` by default

projects/kit/components/files/file/file.style.less
=> fix(kit): prevent stretching to full height

package.json
=> chore: small backport from v4.x

projects/demo/src/modules/info/changelog/changelog.component.ts, projects/demo/src/modules/info/changelog/changelog.style.less, projects/demo/src/modules/info/changelog/changelog.template.html, projects/demo/src/modules/markup/typography/typography.style.less
=> chore(demo): change styles

projects/kit/components/input-tag/input-tag.template.html
=> fix(kit): don't hide input if search isn't empty

projects/addon-doc/utils/type-reference-parser.ts
Reducing noise in large PR viewing
Part of https://github.com/taiga-family/taiga-ui/pull/6186
=> chore(addon-doc): small backport from v4.x

projects/core/tokens/number-format-observable.ts
Reducing noise in large PR viewing
Part of https://github.com/taiga-family/taiga-ui/pull/6186
=> chore(core): small backport from v4.x

projects/kit/pipes/field-error/field-error-pipe.ts
Reducing noise in large PR viewing
Part of https://github.com/taiga-family/taiga-ui/pull/6186
=> chore(kit): small backport from v4.x

projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/components/button/examples/1/index.html
Reducing noise in large PR viewing
Part of https://github.com/taiga-family/taiga-ui/pull/6186
=> chore(demo): small backport from v4.x

package-lock.json, package.json, projects/cdk/coercion/coerce-boolean-property.ts, projects/cdk/schematics/ng-update/v3/index.ts, projects/cdk/schematics/utils/get-projects.ts, projects/cdk/schematics/utils/push-to-array-property.ts, projects/cdk/utils/miscellaneous/is-number.ts, projects/cdk/utils/miscellaneous/is-object.ts, projects/cdk/utils/miscellaneous/is-string.ts, projects/demo/webpack.config.ts, projects/icons/scripts/process-icons.ts
=> chore: remove redundant eslint rules

projects/demo/src/modules/app/version-manager/version-manager.providers.ts
=> chore(demo): invalid selected version on next page

projects/addon-doc/components/main/main.style.less, projects/demo/src/styles.less
=> chore(demo): prevent overflow body when height is auto

projects/demo/src/modules/components/thumbnail-card/thumbnail-card.template.html
- [x ] Documentation content changes
Doc page with deprecated module name (_TuiCardModule_)
Doc page with current module name (_TuiThumbnailCardModule_)
=> docs(demo): renamed deprecated module

projects/demo-cypress/cypress/tests/core/data-list/data-list.cy.ts
=> chore: fix datalist e2e

package-lock.json, projects/addon-preview/package.json, projects/addon-table/package.json, projects/cdk/package.json, projects/core/components/primitive-calendar/primitive-calendar.component.ts, projects/core/components/primitive-calendar/primitive-calendar.template.html, projects/core/package.json, projects/kit/package.json
=> fix(core): `Calendar` properly react to markers change

projects/addon-table/components/table/th-group/th-group.template.html, projects/addon-table/components/table/tr/tr.template.html
=> chore: fix runtime error

projects/core/components/root/root.style.less
=> fix(core): page scrolling jumps to top in Iframe when modal is opened

CONTRIBUTING.md
Fix for [#6302](https://github.com/taiga-family/taiga-ui/issues/6302)
=> chore: wrong link in contribution guide

projects/cdk/services/directive-styles.service.ts
=> fix(cdk): `DirectiveStylesService` fix ssr memory leak

projects/demo-playwright/tests/core/breakpoint-service/breakpoint-service.spec.ts
=> ci: add additional screenshots

projects/kit/components/combo-box/combo-box.component.ts
=> fix(kit): `ComboBox` fix empty string option incorrect behavior

projects/demo-playwright/tests/deep/deep.spec.ts
=> chore: wait until there are no network connections

projects/cdk/tokens/window-size.ts, projects/core/services/test/breakpoint.service.spec.ts
=> fix(cdk): respect client size in `TUI_WINDOW_SIZE`

.github/workflows/auto-approve.yml, .github/workflows/test.yml
=> ci: simplify unit tests job

projects/demo-playwright/tests/kit/multi-select/multi-select.spec.ts, projects/demo/src/modules/components/group/examples/1/index.html, projects/demo/src/modules/components/input-date-multi/input-date-multi.component.ts, projects/demo/src/modules/components/input-date-multi/input-date-multi.template.html, projects/demo/src/modules/components/input-tag/input-tag.component.ts, projects/demo/src/modules/components/input-tag/input-tag.template.html, projects/demo/src/modules/components/multi-select/examples/2/index.html, projects/demo/src/modules/components/multi-select/examples/5/index.html, projects/demo/src/modules/components/multi-select/examples/9/index.html, projects/demo/src/modules/components/multi-select/multi-select.component.ts, projects/demo/src/modules/components/multi-select/multi-select.template.html, projects/kit/components/input-date-multi/input-date-multi.component.ts, projects/kit/components/input-date-multi/input-date-multi.template.html, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/multi-select/multi-select.component.ts, projects/kit/components/multi-select/multi-select.options.ts, projects/kit/components/multi-select/multi-select.template.html
remove `expandable` property in favor of the `rows`
=> feat(kit)!: `InputTag`, `Multiselect`, `InputDateMulti` remove `expandable` property

projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/index.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-expandable.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-expandable.spec.ts
=> chore: add `expandable` migration

.github/workflows/test.yml, jest.config.ts
=> ci: improve unit tests logs on CI

projects/addon-doc/components/demo/demo.style.less, projects/addon-doc/components/demo/demo.template.html
=> ci: improve demo content for E2E

projects/demo-playwright/tests/deep/deep.spec.ts
=> chore: fixup

projects/demo/src/modules/components/combo-box/combo-box.template.html, projects/demo/src/modules/components/combo-box/examples/8/index.ts
=> chore: fix lint

.github/workflows/e2e.yml, projects/demo-playwright/tests/deep/deep.spec.ts, projects/demo-playwright/utils/mock-images.ts, projects/demo/src/modules/charts/axes/axes.template.html, projects/demo/src/modules/components/expand/expand.template.html
=> chore: fix flaky

.github/workflows/e2e.yml, projects/demo-playwright/tests/deep/deep.spec.ts
=> chore: full deep examples

projects/demo/src/modules/directives/hint-describe/hint-describe.template.html, projects/demo/src/modules/directives/hint-manual/hint-manual.template.html, projects/demo/src/modules/directives/hint-pointer/examples/import/import-module.md, projects/demo/src/modules/directives/hint-pointer/hint-pointer.template.html
=> chore(demo): change template for example `HintPointer` and update link to source code

projects/cdk/schematics/ng-add/constants/versions.ts
=> fix(cdk): `ng-add` use actual dompurify version

projects/demo-playwright/tests/core/data-list/data-list.spec.ts
=> chore(e2e): fix flaky

projects/demo-playwright/tests/deep/deep-select.spec.ts, projects/demo-playwright/tests/deep/deep-toggle.spec.ts, projects/demo-playwright/utils/goto.ts, projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts, projects/demo-playwright/utils/page-objects/documentation-page.po.ts, projects/demo-playwright/utils/wait-for-fonts.ts
=> chore: refactor e2e

projects/addon-doc/pipes/markdown/markdown.pipe.ts, projects/addon-doc/styles/mixins/changelog.less, projects/demo/src/modules/info/changelog/changelog.component.less
=> fix(addon-doc): remove hardcoded styles and add mapper

projects/demo-playwright/tests/core/dialogs/dialog-browser-back.spec.ts
=> chore: fix for proprietary e2e

projects/demo/tsconfig.app.json, tsconfig.json
=> chore: hide warnings

projects/kit/components/input-year/input-year.module.ts, projects/kit/components/input-year/input-year.style.less, projects/kit/components/input-year/input-year.template.html, projects/kit/internal/primitive-calendar-range/test/primitive-calendar-range.component.spec.ts
=> fix(kit): `InputYear` fix dropdown paddings

projects/kit/components/input-year/input-year.style.less
=> chore(kit): `InputYear` fix max-height

projects/demo-playwright/tests/deep/deep-select.spec.ts, projects/kit/internal/primitive-calendar-range/test/primitive-calendar-range.component.spec.ts
=> chore: revert previous solution

projects/demo-playwright/tests/deep/deep-select.spec.ts, projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
=> chore: revert previous solution (#6432)

projects/demo-playwright/tests/addon-commerce/input-card-grouped.spec.ts, projects/demo-playwright/tests/addon-commerce/input-expire.spec.ts, projects/demo-playwright/tests/addon-preview/preview.spec.ts, projects/demo-playwright/tests/icons/icons-customization.spec.ts, projects/demo-playwright/tests/kit/input-date-time/input-date-time.spec.ts, projects/demo-playwright/tests/kit/input-month-range/input-month-range.spec.ts, projects/demo-playwright/tests/kit/input-month/input-month.spec.ts, projects/demo-playwright/tests/kit/input-phone/input-phone.spec.ts, projects/demo-playwright/tests/kit/multi-select/multi-select.spec.ts, projects/demo-playwright/tests/kit/select/select.spec.ts
=> chore(e2e): unified code

projects/demo-playwright/tests/kit/multi-select/multi-select.spec.ts
=> chore: fix

.github/workflows/e2e.yml
=> chore: remove redundant job

package-lock.json, package.json, projects/cdk/schematics/ng-update/steps/show-warnings.ts, projects/cdk/schematics/ng-update/v3/steps/migrate-templates.ts, projects/cdk/schematics/utils/get-named-import-references.ts, projects/cdk/schematics/utils/templates/elements.ts, projects/cdk/types/injection-token-type.ts, projects/demo/src/modules/charts/line-days-chart/examples/1/index.ts, projects/demo/src/modules/charts/line-days-chart/line-days-chart.component.ts, projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts, projects/kit/pipes/filter-by-input/filter-by-input.base.ts
=> ci: support prettier 3.2

.github/workflows/auto-approve.yml
=> chore: update

projects/kit/tokens/countries-masks.ts
=> fix(kit): `InputPhoneInternational` change Brazilian mask pattern

package-lock.json, package.json, projects/demo/project.json
=> ci: correct works with base-href ./ on e2e

.github/workflows/e2e.yml
=> chore: skip cypress job

.github/workflows/e2e.yml
=> chore: fixup e2e.yml

projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
=> chore: improve for proprietary

projects/demo-playwright/tests/kit/input-range/input-range.spec.ts
=> chore: fix test for proprietary

projects/kit/components/radio-list/radio-list.template.html
=> fix(kit): radio list identity matcher overriding fixing

projects/demo-cypress/cypress/support/helpers/visit.ts, projects/demo/src/modules/app/abstract.app.ts, projects/demo/src/modules/app/app.component.ts, projects/demo/src/modules/app/app.style.less, projects/demo/src/modules/app/cypress.less
=> refactor: not necessary styles

package-lock.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-mobile/package.json, projects/addon-preview/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/cdk/package.json, projects/core/package.json, projects/experimental/package.json, projects/i18n/package.json, projects/kit/package.json, projects/layout/package.json
=> chore: replace `>=12.0.0` with `>=15.0.0` for all `@angular/*`-deps

projects/core/components/root/root.style.less
Closes [#6473](https://github.com/taiga-family/taiga-ui/issues/6473)
=> fix(core): prevent TuiRoot from applying CSS syles to the body element without Taiga UI context - v3

.cspell.json, projects/demo-playwright/tests/core/dialogs/dialog-browser-back.spec.ts, projects/demo-playwright/tests/deep/deep-select.spec.ts, projects/demo-playwright/tests/deep/deep-toggle.spec.ts, projects/demo-playwright/tests/kit/dropdown-context/dropdown-context.spec.ts, projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
=> ci: add `networkidle` for stable flaky tests

projects/demo/project.json
the `--next` flag is not used anywhere
=> chore(demo): remove `next` configuration

.github/workflows/snapshots.yml
=> ci: fix snapshots deploy

CHANGELOG.md
=> chore: cleanup CHANGELOG.md

projects/demo-playwright/tests/deep/deep-select.spec.ts, projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts
=> chore: refactor

projects/kit/components/radio-list/radio-list.template.html
=> fix(kit): fix radio list identity matcher overriding

package-lock.json, package.json, projects/demo/src/modules/icons/icons-group/icons-group.component.ts, projects/demo/src/modules/icons/icons.component.ts, projects/demo/src/modules/icons/icons.module.ts, projects/demo/src/modules/icons/icons.style.less, projects/demo/src/modules/icons/icons.template.html
=> chore(demo): remove editor package

projects/demo-playwright/tests/kit/dropdown-context/dropdown-context.spec.ts
=> chore: remove scrollIntoViewIfNeeded

projects/core/components/hosted-dropdown/hosted-dropdown.component.ts
=> fix(core): `HostedDropdown` fix binding error in test environment

projects/demo/src/modules/experimental/avatar/avatar.component.ts, projects/demo/src/modules/experimental/avatar/avatar.module.ts, projects/demo/src/modules/experimental/avatar/avatar.template.html, projects/demo/src/modules/experimental/avatar/examples/6/index.html, projects/demo/src/modules/experimental/avatar/examples/6/index.less, projects/demo/src/modules/experimental/avatar/examples/6/index.ts, projects/experimental/components/avatar-labeled/avatar-labeled.component.ts, projects/experimental/components/avatar-labeled/avatar-labeled.styles.less, projects/experimental/components/avatar-labeled/index.ts, projects/experimental/components/avatar-labeled/ng-package.json, projects/experimental/components/index.ts
=> feat(experimental): add `tui-avatar-labeled`

projects/core/components/loader/loader.style.less, projects/core/components/loader/loader.template.html
=> feat(core): `Loader` has new animation

projects/core/components/root/root.component.ts, projects/core/components/root/root.style.less
=> feat(core): applies styles only inside taiga context

projects/layout/components/block-status/block-status.style.less
=> feat(layout): `BlockStatus` update mobile paddings

projects/demo/src/modules/app/app.routes.ts, projects/experimental/directives/surface/surface.style.less
=> fix(experimental): `Surface` fix styles priority

projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/components/push/push.component.ts, projects/demo/src/modules/components/push/push.template.html, projects/kit/components/push/push.component.ts, projects/kit/components/push/push.style.less
=> feat(kit): `Push` add setting the number of lines of text

projects/demo/src/modules/app/app.routes.ts, projects/kit/components/push/push-alert.template.html
=> fix(kit): `Push` fix directive change detection

projects/cdk/schematics/ng-update/v4/index.ts, projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts, projects/cdk/schematics/ng-update/v4/steps/index.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-legacy-mask.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-legacy-mask.spec.ts
Relates to
* https://github.com/taiga-family/taiga-ui/pull/6668
=> chore(cdk): schematics for legacy mask utils

projects/core/styles/mixins/textfield.less
=> fix(core): `PrimitiveTextfield` fix memory leak (#6697)

projects/kit/components/combo-box/combo-box.template.html
feat(kit): hide dropdown if datalist template not provided
=> feat(kit): hide dropdown if datalist template not provided

projects/core/directives/dropdown/dropdown-position.directive.ts
Closes #4130 
before: 
https://github.com/taiga-family/taiga-ui/assets/46284632/615472a3-0e51-47f6-aa29-60ae05fc02fb
---
after: 
https://github.com/taiga-family/taiga-ui/assets/46284632/8eb17feb-fe22-489f-9829-5c4fc8555db6
=> fix(core): `Multiselect` fix dropdown shaking

projects/core/directives/dropdown/dropdown-position.directive.ts
=> fix(core): Multiselect fix dropdown shaking

.cspell.json, projects/cdk/schematics/ng-update/steps/index.ts, projects/cdk/schematics/ng-update/v4/index.ts, projects/cdk/schematics/ng-update/v4/steps/constants/index.ts, projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/index.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-prevent-default.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-prevent-default.spec.ts
=> chore: `tuiPreventDefault` add migration

projects/core/directives/dropdown/dropdown.component.ts
=> fix(core): `Dropdown` fix max height

package-lock.json, projects/demo/project.json, projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts, projects/kit/package.json
=> feat(kit)!: remove `text-mask-core` from `dependencies` of `@taiga-ui/kit`

projects/core/components/notification/notification.component.ts, projects/core/components/notification/notification.style.less, projects/core/components/notification/notification.template.html, projects/demo/src/modules/components/notification/examples/1/index.html, projects/demo/src/modules/components/notification/examples/1/index.less, projects/demo/src/modules/components/notification/examples/1/index.ts, projects/demo/src/modules/components/notification/notification.module.ts
=> feat(core): add interactive mode for notification

projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/experimental/button-group/button-group.component.ts, projects/demo/src/modules/experimental/button-group/button-group.module.ts, projects/demo/src/modules/experimental/button-group/button-group.template.html, projects/demo/src/modules/experimental/button-group/examples/1/index.html, projects/demo/src/modules/experimental/button-group/examples/1/index.less, projects/demo/src/modules/experimental/button-group/examples/1/index.ts, projects/demo/src/modules/experimental/button-group/examples/2/index.html, projects/demo/src/modules/experimental/button-group/examples/2/index.less, projects/demo/src/modules/experimental/button-group/examples/2/index.ts, projects/demo/src/modules/experimental/button-group/examples/3/index.html, projects/demo/src/modules/experimental/button-group/examples/3/index.less, projects/demo/src/modules/experimental/button-group/examples/3/index.ts, projects/demo/src/modules/experimental/button-group/examples/import/import-module.md, projects/demo/src/modules/experimental/button-group/examples/import/insert-template.md, projects/demo/used-icons.ts, projects/experimental/directives/button-group/button-group.component.ts, projects/experimental/directives/button-group/button-group.directive.ts, projects/experimental/directives/button-group/button-group.module.ts, projects/experimental/directives/button-group/button-group.style.less, projects/experimental/directives/button-group/index.ts, projects/experimental/directives/button-group/ng-package.json, projects/experimental/directives/index.ts
=> feat(experimental): add `tuiButtonGroup`

projects/kit/components/carousel/carousel.component.ts
=> fix(kit): scroll over carousel items

projects/demo/src/modules/experimental/avatar/avatar.component.ts, projects/demo/src/modules/experimental/avatar/examples/3/index.html, projects/demo/src/modules/experimental/avatar/examples/4/index.ts, projects/demo/src/modules/experimental/button-vertical/examples/1/index.html, projects/demo/src/modules/experimental/button/examples/3/index.html, projects/experimental/components/avatar/avatar.component.ts, projects/experimental/components/avatar/avatar.options.ts, projects/experimental/components/avatar/avatar.style.less, projects/experimental/components/chip/chip.directive.ts
=> feat(experimental): `Avatar` shift sizes to match buttons and controls

projects/core/components/scrollbar/scrollbar.component.ts, projects/core/components/scrollbar/scrollbar.style.less, projects/core/components/scrollbar/scrollbar.template.html, projects/experimental/components/badge-notification/badge-notification.style.less, projects/i18n/languages/english/kit.ts
=> chore: small changes (#6800)

projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
=> chore: `Resize` add migration

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/index.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-money.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-money.spec.ts, projects/cdk/schematics/utils/templates/inputs.ts
=> chore: `Money` add migration

projects/demo/src/modules/experimental/navigation/examples/1/index.html, projects/demo/src/modules/experimental/navigation/navigation.style.less
=> chore: improve demo

projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts, projects/core/components/primitive-textfield/primitive-textfield.component.ts, projects/demo-playwright/tests/core/primitive-textfield/primitive-textfield.spec.ts, projects/demo-playwright/tests/kit/input-number/input-number.spec.ts, projects/demo-playwright/tests/kit/input-slider/input-slider.spec.ts, projects/demo/src/modules/components/input-number/input-number.template.html, projects/demo/src/modules/components/input-slider/input-slider.template.html, projects/demo/src/modules/components/input-time/examples/4/index.html, projects/demo/src/modules/components/input-time/examples/4/index.ts, projects/demo/src/modules/components/primitive-textfield/primitive-textfield.template.html, projects/kit/components/input-number/input-number.component.ts, projects/kit/components/input-slider/input-slider.component.ts, projects/kit/components/input-slider/test/input-slider.component.spec.ts, projects/kit/components/input-time/input-time.component.ts, projects/kit/components/input-time/input-time.options.ts, projects/kit/components/input-time/input-time.template.html
=> refactor(core,kit): remove deprecated `filler`, `postfix`, `prefix` inputs

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/directives/present/examples/import/import-module.md, projects/demo/src/modules/directives/present/present.module.ts, projects/demo/src/modules/directives/present/present.template.html, projects/kit/directives/present/index.ts, projects/kit/directives/present/present.directive.ts, projects/kit/directives/present/present.module.ts
=> chore: `Present` refactor

projects/core/directives/dropdown/dropdown.component.ts
=> fix(core): fix nested sided dropdown height

.github/workflows/e2e-playwright.yml, projects/core/components/scroll-controls/scrollbar.service.ts, projects/demo-playwright/tests/core/dropdown/dropdown.spec.ts
=> fix(core): take into account scrollbar in active zone

projects/core/components/dialog/dialogs.component.ts
=> refactor: incorrect inferable type

projects/kit/components/radio-labeled/radio-labeled.style.less
=> fix(kit): `RadioLabeled` fix line-height

projects/demo/src/modules/components/badge/badge.component.ts, projects/demo/src/modules/components/badge/badge.module.ts, projects/demo/src/modules/components/badge/badge.template.html, projects/demo/src/modules/experimental/card-large/card-large.component.ts, projects/demo/src/modules/experimental/card-large/card-large.module.ts, projects/demo/src/modules/experimental/card-large/card-large.template.html, projects/demo/src/utils/example.pipe.ts, projects/demo/src/utils/index.ts
=> chore(demo): add `Example` pipe

projects/experimental/components/button/button.style.less, projects/experimental/directives/fade/fade.style.less
=> fix(experimental): `Fade` fix artifacts in Chrome

projects/styles/markup/tui-list.less
=> fix(styles): `List` fix line height

projects/addon-table/components/reorder/reorder.style.less, projects/addon-table/components/reorder/reorder.template.html
Closes #6902 https://github.com/taiga-family/taiga-ui/issues/6902
=> fix(addon-table): eyes not draggable

.github/workflows/e2e-cypress.yml, projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/core/components/hosted-dropdown/hosted-dropdown.component.ts, projects/demo-cypress/src/tests/mobile-calendar.cy.ts, projects/demo-cypress/src/tests/pan.cy.ts, projects/demo-cypress/src/tests/range.cy.ts, projects/demo-cypress/src/tests/swipe.cy.ts, projects/demo-cypress/src/tests/tabs.cy.ts, projects/demo-cypress/src/tests/zoom.cy.ts
=> refactor: fix typecheck in cypress files

.github/workflows/e2e-playwright.yml, projects/demo-playwright/tests/addon-commerce/input-expire.spec.ts, projects/demo-playwright/utils/page-objects/calendar.po.ts, projects/demo-playwright/utils/page-objects/documentation-api-page.po.ts, projects/demo-playwright/utils/page-objects/documentation-page.po.ts, projects/demo-playwright/utils/page-objects/input-card-grouped.po.ts, projects/demo-playwright/utils/page-objects/input-card.po.ts, projects/demo-playwright/utils/page-objects/input-date-range.po.ts, projects/demo-playwright/utils/page-objects/input-date-time.po.ts, projects/demo-playwright/utils/page-objects/input-month-range.po.ts, projects/demo-playwright/utils/page-objects/input-month.po.ts, projects/demo-playwright/utils/page-objects/input-phone.po.ts, projects/demo-playwright/utils/page-objects/input-range.po.ts, projects/demo-playwright/utils/page-objects/input-slider.po.ts, projects/demo-playwright/utils/page-objects/input-tag.po.ts, projects/demo-playwright/utils/page-objects/multi-select.po.ts, projects/demo-playwright/utils/page-objects/range.po.ts, projects/demo-playwright/utils/page-objects/slider.po.ts, projects/demo-playwright/utils/page-objects/table-pagination-page.po.ts, projects/demo-playwright/utils/page-objects/textfield-with-data-list.po.ts, tsconfig.playwright.json
=> refactor: fix typecheck in playwright files

projects/styles/markup/tui-list.less
=> fix(styles): `List` fix line height (#6880)

projects/demo/src/modules/experimental/navigation/examples/1/index.html, projects/demo/src/modules/experimental/navigation/examples/2/index.html, projects/experimental/components/button/button.style.less, projects/experimental/components/navigation/aside.style.less, projects/experimental/components/navigation/header.component.ts, projects/experimental/components/navigation/header.style.less, projects/experimental/components/navigation/index.ts, projects/experimental/components/navigation/logo.component.ts, projects/experimental/components/navigation/logo.style.less, projects/experimental/components/navigation/main.style.less, projects/experimental/components/navigation/nav.style.less, projects/experimental/components/navigation/navigation.module.ts, projects/experimental/directives/cell/cell.styles.less, projects/experimental/directives/fade/fade.directive.ts, projects/experimental/directives/fade/fade.style.less, projects/experimental/directives/header/header.component.ts, projects/experimental/directives/header/header.directive.ts
=> chore: cherry picks

projects/addon-doc/components/navigation/navigation.template.html
=> chore: support rel property for links

package-lock.json, package.json, projects/cdk/package.json, projects/core/package.json
=> chore: update ng-event-plugins

projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/index.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
=> chore: `tui-checkbox-labeled`, `tui-radio-labeled` add migration

projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badge.ts, projects/cdk/schematics/ng-update/v4/steps/templates/toggles/common.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badge.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-toggle.spec.ts
=> chore: fix migration self-closing tags

projects/core/directives/hint/hint-hover.directive.ts, projects/demo/src/modules/charts/pie-chart/examples/2/index.ts
=> fix(core): disable isObscured check for `HintPointer`

package-lock.json, package.json
=> chore: bump tui-editor

projects/addon-doc/components/main/main.component.ts, projects/addon-doc/components/main/main.template.html, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/experimental/skeleton/examples/1/index.html, projects/demo/src/modules/experimental/skeleton/examples/1/index.less, projects/demo/src/modules/experimental/skeleton/examples/1/index.ts, projects/demo/src/modules/experimental/skeleton/examples/2/index.html, projects/demo/src/modules/experimental/skeleton/examples/2/index.ts, projects/demo/src/modules/experimental/skeleton/examples/import/import.md, projects/demo/src/modules/experimental/skeleton/examples/import/insert.md, projects/demo/src/modules/experimental/skeleton/skeleton.component.ts, projects/demo/src/modules/experimental/skeleton/skeleton.module.ts, projects/demo/src/modules/experimental/skeleton/skeleton.template.html, projects/experimental/directives/index.ts, projects/experimental/directives/skeleton/index.ts, projects/experimental/directives/skeleton/ng-package.json, projects/experimental/directives/skeleton/skeleton.component.ts, projects/experimental/directives/skeleton/skeleton.directive.ts, projects/experimental/directives/skeleton/skeleton.module.ts, projects/experimental/directives/skeleton/skeleton.style.less
=> feat(experimental): `Skeleton` add new directive

projects/cdk/directives/native-validator/native-validator.directive.ts
=> chore: ssr problem in editor demo

projects/addon-table/components/table/directives/head.directive.ts, projects/addon-table/components/table/th/th.component.ts, projects/addon-table/directives/table-filters/table-filter.directive.ts
=> fix(addon-table): key type check

projects/core/styles/theme/appearance/outline.less, projects/demo/src/modules/experimental/button/examples/2/index.html
=> feat(experimental): `Button` add manual :checked appearance

projects/demo/src/modules/components/avatar/examples/4/index.html
=> ci: eslint `no-duplicate`

projects/core/components/notification/notification.style.less, projects/demo/src/modules/components/notification/examples/3/index.html
Closes https://github.com/taiga-family/taiga-ui/issues/7043
=> fix(core): set text-align on host notification

projects/cdk/schematics/ng-update/v4/steps/migrate-destroy-service.ts, projects/cdk/schematics/ng-update/v4/tests/migrate-destroy-service/schematic-migrate-destroy-service.spec.ts
Relates to https://github.com/taiga-family/taiga-ui/issues/5808
=> chore(cdk): fix 'no code comments'-problem in `TuiDestroyService => takeUntilDestroyed` migration

projects/addon-charts/components/pie-chart/pie-chart.style.less, projects/addon-charts/components/ring-chart/ring-chart.component.ts, projects/addon-charts/components/ring-chart/ring-chart.style.less, projects/addon-charts/components/ring-chart/ring-chart.template.html, projects/demo/src/modules/charts/ring-chart/ring-chart.component.ts, projects/demo/src/modules/charts/ring-chart/ring-chart.template.html, projects/experimental/components/checkbox/checkbox.component.ts
=> feat(addon-charts): `RingChart` add xs size

projects/addon-charts/components/pie-chart/pie-chart.style.less, projects/addon-charts/components/ring-chart/ring-chart.component.ts, projects/addon-charts/components/ring-chart/ring-chart.style.less, projects/addon-charts/components/ring-chart/ring-chart.template.html, projects/demo/src/modules/charts/ring-chart/ring-chart.component.ts, projects/demo/src/modules/charts/ring-chart/ring-chart.template.html, projects/experimental/components/checkbox/checkbox.component.ts
=> feat(addon-charts): `RingChart` add xs size (#7077)

projects/demo/src/modules/components/tooltip/examples/1/index.html, projects/demo/src/modules/components/tooltip/examples/1/index.ts, projects/demo/src/modules/components/tooltip/tooltip.module.ts
Run `nx serve-ssr` and open `/components/tooltip`.
This page will never be loaded.
=> chore(demo): documentation page `Tooltip` has infinite SSR

projects/demo/src/modules/experimental/tooltip/examples/1/index.html, projects/demo/src/modules/experimental/tooltip/examples/1/index.ts, projects/demo/src/modules/experimental/tooltip/tooltip.module.ts
The same as
* https://github.com/taiga-family/taiga-ui/pull/7090
=> chore(demo): experimental documentation page `Tooltip` has infinite SSR

projects/core/components/expand/expand.component.ts
=> fix(core): `Expand` do not react to transition on pseudo element

projects/kit/components/stepper/stepper.component.ts
=> fix(kit): v3.x remove pure getNativeElements

projects/demo/src/modules/app/stackblitz/starter/stackblitz-edit-button.component.less, projects/demo/src/modules/app/stackblitz/starter/stackblitz-edit-button.component.ts, projects/demo/src/modules/app/stackblitz/starter/stackblitz-starter.module.ts
Run `nx serve-ssr` and open ANY page with examples
```shell
Assertion failed: Failed to load external SVG assets/icons/stackblitz.svg
```
Relates to #2332
=> chore(demo): fix SSR error for `Edit on Stackblitz` button

projects/kit/components/input-date-multi/input-date-multi.component.ts, projects/kit/components/input-date-multi/input-date-multi.template.html
=> fix(kit): correct update model for `tui-input-date-multi`

projects/core/components/primitive-textfield/textfield/textfield.component.ts
=> fix(core): `Textfield` fix next button on virtual keyboard

projects/kit/components/checkbox/checkbox.component.ts
=> chore: fix proprietary build for feed-item

projects/core/directives/dropdown/dropdown-selection.directive.ts
Part of https://github.com/taiga-family/tui-editor/issues/16
I need to override behavior at some points
=> feat(core): support override dropdown selection

projects/kit/components/input-date/input-date.component.ts
=> fix(kit): `InputDate` fix opening mobile calendar in read-only mode

projects/demo/src/modules/components/tabs/examples/1/index.html, projects/demo/src/modules/components/tabs/examples/2/index.html, projects/demo/src/modules/components/tabs/examples/3/index.html, projects/demo/src/modules/components/tabs/examples/4/index.html, projects/demo/src/modules/components/tabs/examples/4/index.less, projects/demo/src/modules/components/tabs/examples/5/index.html, projects/demo/src/modules/components/tabs/tabs.module.ts, projects/demo/src/modules/directives/dropdown-hover/dropdown-hover.module.ts, projects/demo/src/modules/directives/dropdown-hover/examples/2/index.html, projects/kit/components/tabs/tab.directive.ts, projects/kit/components/tabs/tabs-with-more.component.ts, projects/kit/components/tabs/tabs-with-more.template.html, projects/kit/components/tabs/tabs.style.less
=> refactor(kit): `Tabs` use `Icons`

projects/demo/src/modules/directives/let/examples/1/index.ts
Relates to:
* https://github.com/taiga-family/taiga-ui/pull/7180
=> chore(demo): documentation page `Let` has infinite SSR

.github/workflows/create-release.yml
=> chore: specify the branch for action

.cspell.json, LICENSE
Add **Acpekt** PLC as a new license holder
=> chore: update LICENSE holder

projects/core/components/primitive-spin-button/primitive-spin-button.component.ts, projects/core/components/primitive-spin-button/primitive-spin-button.template.html, projects/core/components/primitive-spin-button/test/primitive-spin-button.component.spec.ts, projects/kit/components/accordion/accordion-item/accordion-item.component.ts, projects/kit/components/accordion/accordion-item/accordion-item.style.less, projects/kit/components/accordion/accordion-item/accordion-item.template.html, projects/kit/components/pagination/pagination.component.ts, projects/kit/components/pagination/pagination.module.ts, projects/kit/components/pagination/pagination.template.html
=> refactor(cdk): deprecate `Interactive`

projects/kit/components/checkbox-labeled/checkbox-labeled.style.less
=> fix(kit): `CheckboxLabeled` fix line-height

projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less, projects/addon-commerce/components/input-card-grouped/input-card-grouped.template.html
=> fix(addon-commerce): fix hidden card

projects/demo/src/modules/components/carousel/examples/4/index.ts, projects/kit/components/carousel/carousel.component.ts, projects/kit/components/carousel/carousel.style.less, projects/kit/components/carousel/carousel.template.html
=> fix(kit): `Carousel` fix dragging in chrome

projects/demo/src/modules/components/input-card/examples/1/index.html, projects/demo/src/modules/components/input-card/input-card.template.html
=> chore(demo): `InputCard` fix example

projects/demo/src/modules/animations/examples/fade-in/index.ts, projects/demo/src/modules/pipes/format-date/examples/1/service.ts
Relates to:
* https://github.com/taiga-family/taiga-ui/pull/7180
=> chore(demo): documentation pages `FormatDate` & `Animations` have infinite SSR

package-lock.json, package.json, projects/demo/package.json, projects/demo/project.json
Angular 15 was incompatible with this builder.
It threw the following error:
```
The "buildOptimizer" option is supported from Angular >= 16.0.0. You are currently using "15.2.10".
You can resolve this error by removing the "buildOptimizer" option.
```
___
Angular 16 works okey.
=> chore(demo): use `@nx/angular:webpack-server` instead of `@angular-builders/custom-webpack:server`

projects/demo/src/modules/components/input-tag/input-tag.component.ts, projects/demo/src/modules/components/input-tag/input-tag.template.html, projects/demo/src/modules/components/multi-select/multi-select.component.ts, projects/demo/src/modules/components/multi-select/multi-select.template.html, projects/kit/components/input-tag/input-tag.component.ts, projects/kit/components/input-tag/input-tag.options.ts, projects/kit/components/input-tag/input-tag.template.html, projects/kit/components/multi-select/multi-select.component.ts, projects/kit/components/multi-select/multi-select.template.html
=> feat(kit): add `autoColor` to `InputTag` and `MultiSelect`

projects/demo/src/modules/app/app.providers.ts
=> chore(demo): fix source code links

projects/core/components/icon/icon.pipe.ts, projects/core/components/icon/index.ts, projects/demo/src/modules/components/icon/examples/1/index.html, projects/demo/src/modules/components/icon/examples/1/index.less, projects/demo/src/modules/components/icon/examples/1/index.ts, projects/demo/src/modules/components/icon/icon.module.ts
Closes https://github.com/taiga-family/taiga-ui/issues/7237
=> feat(core): add `tuiIcon` pipe

projects/demo-playwright/tests/demo/is-flaky-examples.ts
=> chore(demo-playwright): flaky example exclusion works again

.cspell.json, .github/CODEOWNERS
Add @mdlufy to codeowners to auto-assigning in approvers
=> chore(all): update CODEOWNERS

projects/cdk/components/dialog-host/dialog-host.component.ts, projects/cdk/components/dialog-host/dialog-host.style.less
=> fix(cdk): `Dialog` fix jumping to top on closing

package-lock.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-mobile/package.json, projects/addon-preview/package.json, projects/addon-table/package.json, projects/addon-tablebars/package.json, projects/core/package.json, projects/experimental/package.json, projects/i18n/package.json, projects/icons/package.json, projects/kit/package.json, projects/layout/package.json, projects/styles/package.json, projects/taiga-schematics/package.json, projects/testing/package.json
Closes https://github.com/taiga-family/taiga-ui/issues/7267
=> fix: non strict peer dependencies

projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts, projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.directive.ts, projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.module.ts, projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.style.less, projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.template.html, projects/demo/src/modules/directives/dropdown/dropdown.module.ts, projects/demo/src/modules/directives/dropdown/dropdown.template.html, projects/demo/src/modules/directives/dropdown/examples/2/index.html, projects/demo/src/modules/directives/dropdown/examples/5/index.html, projects/demo/src/modules/directives/dropdown/examples/5/index.ts, projects/experimental/directives/title/title.style.less
=> feat(addon-mobile): `DropdownMobile` add sheet view

projects/addon-table/components/reorder/reorder.component.ts, projects/addon-table/components/reorder/reorder.module.ts, projects/addon-table/components/reorder/reorder.template.html
=> feat(addon-table): reorder add possibility to transfer a template

projects/core/styles/theme/variables.less, projects/kit/components/accordion/accordion-item/accordion-item.component.ts, projects/kit/components/accordion/accordion-item/accordion-item.style.less, projects/kit/components/accordion/accordion-item/accordion-item.template.html
Done: redesign focus to :focus-visible
Fix case with focusing after switch between tabs
=> fix(kit): redesign focus to focus-visible in `TuiAccordion`

projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts
=> feat(addon-mobile): reduce zone.js in `tuiElasticSticky`

projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-action.spec.ts, projects/layout/directives/header/header.styles.less
=> chore: `MarkerIcon`, `Action` add migrations

projects/cdk/schematics/ng-update/interfaces/removable-input.ts, projects/cdk/schematics/ng-update/utils/templates/remove-inputs.ts, projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/inputs-to-remove.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-styles.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-links.spec.ts
=> chore: `link` add migration

.github/renovate.json, package-lock.json, projects/demo-playwright/package.json
After this bump of `@playwright/test` version 
* https://github.com/taiga-family/taiga-ui/pull/7269
Many tests became flaky!
[See example of failed job](https://github.com/taiga-family/taiga-ui/actions/runs/8829064811/job/24240106712?pr=7320)
<details>
<summary>See long logs of this job</summary>
```shell
./total/playwright/tests-kit-input-phone-inpu-b91d8--Backspace-x2-7-912-345-67--chromium/02-input-phone-1.diff.png
./total/playwright/tests-demo-demo-Demo-navigation-app-bar-chromium/navigation-app-bar-1.diff.png
./total/playwright/tests-demo-demo-Demo-components-thumbnail-card-chromium/components-thumbnail-card-1.diff.png
./total/playwright/tests-kit-input-phone-inpu-bb0b6-ackspace-x2-7-912-345-67-89-chromium/11-input-phone.diff.png …
```
=> ci(demo-playwright): fix flaky screenshot tests

projects/cdk/schematics/ng-update/interfaces/replacement-attribute-value.ts, projects/cdk/schematics/ng-update/utils/templates/replace-attr-values.ts, projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/index.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts, projects/cdk/schematics/utils/templates/elements.ts
=> chore: `Button` add migration

projects/core/components/error/error.module.ts, projects/core/components/error/error.template.html
=> fix(core): fix loading defaultErrorMessage for tui-error (#7303)

.github/renovate.json, package-lock.json, projects/demo-playwright/package.json
Revert https://github.com/taiga-family/taiga-ui/pull/7325
Playwright tests are still flaky :(((
=> ci: revert disabling of playwright bumps for renovate bot

projects/demo-cypress/cypress/tests/kit/input-files/input-files.cy.ts
=> chore: remove failing test

projects/demo/src/modules/components/alert/alert.component.ts, projects/demo/src/modules/components/alert/alert.template.html, projects/demo/src/modules/components/alert/examples/7/index.html, projects/demo/src/modules/components/alert/examples/7/index.ts
Relates to
* https://github.com/taiga-family/taiga-ui/pull/7351
=> chore(demo): add example `Concurrency limit` to documentation page `Alert`

projects/kit/components/tabs/tabs.directive.ts, projects/kit/components/tabs/test/tabs.component.spec.ts
Before:
https://github.com/taiga-family/taiga-ui/assets/42899726/df7c4d8f-1602-4ea7-bb45-4a84dd548042
After:
https://github.com/taiga-family/taiga-ui/assets/42899726/26623e9e-4e42-40bf-9a20-72b427e1aef8
=> fix(core): active tab does not have class _active

projects/kit/components/input-slider/input-slider.style.less
(cherry picked from commit 38929d641cc19083f56f925d746fd63b9e1bd46a)
=> fix(kit): fix compatibility tuiGroup & tui-input-slider (#7363)

projects/cdk/directives/native-validator/native-validator.directive.ts, projects/cdk/observables/index.ts, projects/cdk/observables/take-until-destroyed.ts, projects/core/services/position.service.ts, projects/demo/src/modules/directives/appearance/appearance.template.html, projects/demo/src/modules/services/table-bar/table-bar.component.ts
=> feat(cdk): add `tuiTakeUntilDestroyed` helper

projects/layout/directives/card/card.styles.less
Done: fix `tuiTitle` bold inside `tuiCell`
=> fix(layout): fix `tuiTitle` bold inside `tuiCell`

projects/cdk/services/destroy.service.ts
=> fix(cdk): `Destroy` fix post-destroy subscriptions

projects/experimental/directives/card/card.styles.less
Done: fix `tuiTitle` bold inside `tuiCell`
=> fix(experimental): fix `tuiTitle` bold inside `tuiCell`

projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts, projects/demo/src/modules/directives/dropdown/examples/5/index.html
=> fix(addon-mobile): `DropdownMobile`  fix cleaner buttons

projects/addon-mobile/components/mobile-calendar-dialog/index.ts, projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dialog.module.ts, projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dropdown.component.ts, projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dropdown.style.less, projects/addon-mobile/components/mobile-calendar-dialog/mobile-calendar-dropdown.template.html, projects/core/animations/animations.ts, projects/core/styles/mixins/mixins.less, projects/core/styles/mixins/mixins.scss, projects/core/styles/mixins/textfield.less, projects/core/styles/mixins/textfield.scss, projects/demo-playwright/tests/addon-mobile/mobile-calendar/input-date.spec.ts, projects/demo/src/modules/components/input-date/examples/2/index.html, projects/demo/src/modules/components/input-date/input-date.module.ts, projects/kit/components/accordion/accordion.style.less, projects/kit/components/input-date-multi/input-date-multi.component.ts, projects/kit/components/input-date-multi/input-date-multi.template.html, projects/kit/components/input-date-range/input-date-range.component.ts, projects/kit/components/input-date-range/input-date-range.template.html, projects/kit/components/input-date/input-date.component.ts, projects/kit/components/input-date/input-date.template.html, projects/kit/components/input-tag/input-tag.style.less
=> feat(addon-mobile): `MobileCalendar` switch to dropdown

projects/core/styles/mixins/mixins.less, projects/core/styles/mixins/mixins.scss
=> fix(core): stackblitz compatibility

projects/core/components/group/group.style.less
=> fix(core): fix tuiGroup styles

projects/cdk/utils/miscellaneous/with-styles.ts
=> refactor: skip annoying warning

.github/workflows/e2e-playwright.yml
1. Open https://github.com/microsoft/playwright/issues/new/choose
2. Select `Bug Report`
3. Scroll to down
=> ci: add `npx envinfo --preset playwright` to `e2e-playwright.yml`

projects/kit/components/tree/components/tree-item-content/tree-item-content.component.ts, projects/kit/components/tree/components/tree-item-content/tree-item-content.template.html
Closes #6834
I just copied the change detection logic from the TreeItem component and at least it works.
=> fix(kit): `Tree` fix control chevron rotation programmatically

projects/kit/components/avatar/avatar.style.less
=> feat(kit): add `box-sizing:border-box` to nested `TuiAvatar` elements

projects/core/directives/hint/hint-position.directive.ts, projects/core/directives/hint/hint.directive.ts, projects/demo/src/modules/experimental/navigation/examples/1/index.html, projects/demo/src/modules/experimental/navigation/navigation.module.ts, projects/experimental/components/navigation/hint-aside.directive.ts, projects/experimental/components/navigation/index.ts, projects/experimental/components/navigation/navigation.module.ts, projects/icons/all.ts, projects/icons/src/tuiIconCheckCircleOutline.svg
=> feat(experimental): `HintAside` add automatic hint directive for navigation

projects/cdk/components/scroll-controls/scrollbar.directive.ts
=> fix(cdk): `Scrollbar` fix scroll behaviour

projects/kit/components/textarea/textarea.style.less
=> fix(kit): set nullish border in `tui-textarea`

projects/demo/src/modules/components/textarea/examples/4/index.html, projects/kit/components/textarea/textarea.style.less
=> fix(kit): set nullish border in `tui-textarea` and add example

projects/demo/src/modules/components/textarea/examples/4/index.html, projects/legacy/components/textarea/textarea.style.less
=> fix(legacy): set nullish border in `tui-textarea`

projects/kit/components/input-date-time/input-date-time.component.ts
=> fix(kit): `InputDateTime` with `[min]` / `[max]` distorts value on click

projects/cdk/classes/signal-control.ts, projects/cdk/directives/hovered/hovered.service.ts, projects/core/components/textfield/textfield.directive.ts, projects/core/components/textfield/textfield.style.less, projects/core/styles/theme/appearance/textfield.less
=> refactor(core): `Appearance` switch to data-mode 

projects/kit/components/input-number/input-number.style.less
=> fix(kit): fix `InputNumber` buttons styles priority for Safari

projects/core/directives/hint/hint.component.ts
=> fix(core): fix text selection in nested hint

projects/core/directives/dropdown/dropdown-selection.directive.ts, projects/demo-playwright/tests/core/dropdown/dropdown.spec.ts
=> fix(core): `DropdownSelection` fix selection error in textarea

projects/core/directives/hint/hint-hover.directive.ts, projects/core/directives/hint/hint.component.ts, projects/demo/src/modules/directives/hint/examples/3/index.html, projects/demo/src/modules/directives/hint/examples/3/index.ts, projects/demo/src/modules/directives/hint/index.html
=> feat(core): add ability to use nested hints (#7647)

projects/core/directives/hint/hint.style.less
=> fix(core): `Hint` fix content vertical centering with reduced line-height

projects/legacy/components/input-copy/input-copy.component.ts
Closes  [#7073](https://github.com/taiga-family/taiga-ui/issues/7073)
=> fix(core): fix incorrect copy hint in inputCopy

projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts, projects/addon-commerce/components/input-card-grouped/input-card-grouped.style.less, projects/cdk/utils/miscellaneous/directive-binding.ts, projects/cdk/utils/miscellaneous/directive-listener.ts, projects/core/components/data-list/data-list.component.ts, projects/core/components/data-list/data-list.tokens.ts, projects/core/components/data-list/index.ts, projects/core/components/data-list/option.component.ts, projects/core/components/data-list/with-data-list.directive.ts, projects/core/components/label/label.directive.ts, projects/core/components/textfield/textfield.component.ts, projects/core/components/textfield/textfield.style.less, projects/core/tokens/index.ts, projects/legacy/components/combo-box/combo-box.component.ts, projects/legacy/components/input-phone/input-phone.component.ts, projects/legacy/components/input-tag/input-tag.component.ts, projects/legacy/components/input-time/input-time.component.ts, projects/legacy/components/input/input.component.ts, projects/legacy/components/multi-select/multi-select.component.ts, projects/legacy/components/select/select.component.ts
=> feat(core): `WithDataList` add host directive

projects/cdk/schematics/ng-update/v4/steps/templates/migrate-focusable.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-focusable.spec.ts
=> chore: improve focusable migration

projects/demo/src/modules/components/icon/index.html, projects/demo/src/modules/components/icon/index.ts
=> chore(demo): add `API` section for documentation page `Icon`

projects/kit/components/carousel/carousel.component.ts
=> fix(kit): `Carousel` fix scrolling with touchpad when itemsCount more than 1

projects/addon-doc/components/documentation/documentation.template.html, projects/demo/src/modules/pipes/flag/examples/1/index.html, projects/demo/src/modules/pipes/flag/examples/1/index.ts, projects/demo/src/modules/pipes/flag/examples/import/import.md, projects/demo/src/modules/pipes/flag/index.html, projects/demo/src/modules/pipes/flag/index.ts
[Try new version documentation page](https://taiga-ui--pr7708-improve-flag-doc-uymxceso.web.app/pipes/flag)
=> chore(demo): improve documentation page `Flag`

projects/demo/src/modules/app/pages.ts
=> chore: correct link

projects/core/components/textfield/select.directive.ts, projects/core/components/textfield/textfield.style.less
=> chore(core): `Select` fix for ios

projects/cdk/components/scroll-controls/scroll-controls.component.ts, projects/cdk/components/scroll-controls/scroll-controls.template.html
=> fix(cdk): visible control for `tui-scroll-controls` on iOS
