taiga-family/taiga-ui

projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/addon-mobile/directives/touchable/touchable.directive.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo/src/modules/directives/touchable/examples/1/index.ts, projects/demo/src/modules/directives/touchable/examples/import/import.md
=> refactor: rename `TuiTouchableDirective` to `TuiTouchable`

projects/cdk/directives/zoom/zoom.directive.ts, projects/cdk/directives/zoom/zoom.service.ts, projects/cdk/directives/zoom/zoom.types.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo-cypress/src/tests/zoom.cy.ts, projects/demo/src/modules/directives/zoom/examples/1/index.ts, projects/demo/src/modules/directives/zoom/examples/import/import.md, projects/kit/components/preview/preview.component.ts
=> refactor: rename `TuiZoomDirective` to `TuiZoom`

projects/addon-doc/components/code/tests/highlight.spec.ts
=> chore: rename test

projects/addon-charts/components/arc-chart/arc-chart.component.ts, projects/addon-charts/components/axes/axes.component.ts, projects/addon-charts/components/pie-chart/pie-chart.component.ts, projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.component.ts, projects/addon-mobile/components/pull-to-refresh/loader-ios/loader-ios.component.ts, projects/addon-mobile/components/tab-bar/tab-bar.component.ts, projects/cdk/directives/repeat-times/repeat-times.directive.ts, projects/cdk/directives/repeat-times/test/repeat-times.directive.spec.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/core/components/calendar/calendar-sheet.component.ts, projects/core/components/calendar/calendar-year.component.ts, projects/demo/src/modules/app/landing/index.ts, projects/demo/src/modules/components/badge/examples/1/index.ts, projects/demo/src/modules/components/breadcrumbs/examples/2/index.ts, projects/demo/src/modules/components/card-large/examples/4/index.ts, projects/demo/src/modules/components/card-large/examples/5/index.ts, projects/demo/src/modules/components/card-large/examples/6/index.ts, projects/demo/src/modules/components/card-large/examples/7/index.ts, projects/demo/src/modules/components/carousel/index.ts, projects/demo/src/modules/components/chip/examples/3/index.ts, projects/demo/src/modules/components/elastic-container/examples/3/index.ts, projects/demo/src/modules/components/experimental/navigation/examples/1/index.ts, projects/demo/src/modules/components/experimental/navigation/examples/2/index.ts, projects/demo/src/modules/components/experimental/navigation/examples/3/index.ts, projects/demo/src/modules/components/progress-circle/examples/7/index.ts, projects/demo/src/modules/components/surface/examples/5/index.ts, projects/demo/src/modules/components/tag/examples/2/index.ts, projects/kit/components/pagination/pagination.module.ts, projects/kit/components/progress/progress.module.ts, projects/kit/components/rating/rating.component.ts
=> refactor: rename `TuiRepeatTimesDirective` to `TuiRepeatTimes`

projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts, projects/cdk/directives/swipe/swipe.directive.ts, projects/cdk/directives/swipe/swipe.service.ts, projects/cdk/directives/swipe/swipe.types.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo-cypress/src/tests/swipe.cy.ts, projects/demo/src/modules/components/preview/examples/1/index.ts, projects/demo/src/modules/components/preview/examples/2/index.ts, projects/demo/src/modules/components/sheet-dialog/examples/4/index.ts, projects/demo/src/modules/directives/swipe/examples/1/index.ts, projects/demo/src/modules/directives/swipe/examples/2/index.ts, projects/demo/src/modules/directives/swipe/examples/import/import.md, projects/kit/components/carousel/carousel.component.ts
=> refactor: rename `TuiSwipeDirective` to `TuiSwipe`

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/core/components/tooltip/tooltip.module.ts, projects/demo/src/modules/components/block/examples/3/index.ts, projects/demo/src/modules/components/tooltip/examples/1/index.ts, projects/demo/src/modules/components/tooltip/examples/3/index.ts, projects/demo/src/modules/components/tooltip/examples/4/index.ts, projects/demo/src/modules/components/tooltip/index.ts, projects/demo/src/modules/directives/hint-describe/examples/1/index.ts, projects/legacy/components/input-tag/input-tag.module.ts, projects/legacy/components/primitive-textfield/primitive-textfield.module.ts, projects/legacy/components/textarea/textarea.module.ts
=> refactor: rename `TuiTooltipModule` to `TuiTooltip`

projects/kit/components/input-number/input-number.component.ts
=> fix(kit): `InputNumber` fix lost value

projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts, projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.component.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.strategy.ts, projects/addon-mobile/components/mobile-dialog/mobile-dialog.component.ts, projects/addon-mobile/components/mobile-dialog/mobile-dialog.service.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo-cypress/src/tests/mobile-calendar.cy.ts, projects/demo/src/modules/components/input-date-multi/index.ts, projects/demo/src/modules/components/input-date-range/index.ts, projects/demo/src/modules/components/mobile-calendar/examples/1/index.ts, projects/demo/src/modules/components/mobile-calendar/examples/2/index.ts, projects/demo/src/modules/components/mobile-calendar/examples/3/index.ts, projects/demo/src/modules/components/mobile-calendar/examples/4/index.ts, projects/demo/src/modules/components/mobile-calendar/examples/5/index.ts, projects/demo/src/modules/components/mobile-calendar/examples/import/import.md, projects/demo/src/modules/components/mobile-calendar/index.ts
=> refactor: rename `TuiMobileCalendarComponent` to `TuiMobileCalendar`

projects/addon-doc/components/page/page.component.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo/src/modules/components/chip/examples/1/index.ts, projects/demo/src/modules/components/chip/examples/2/index.ts, projects/demo/src/modules/components/chip/examples/3/index.ts, projects/demo/src/modules/components/chip/examples/4/index.ts, projects/demo/src/modules/components/chip/examples/import/import.md, projects/demo/src/modules/components/items-with-more/examples/1/index.ts, projects/demo/src/modules/components/items-with-more/index.ts, projects/demo/src/modules/components/table/examples/2/index.ts, projects/demo/src/modules/directives/skeleton/examples/1/index.ts, projects/kit/components/chip/chip.directive.ts
=> refactor: rename `TuiChipDirective` to `TuiChip`

projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts, projects/addon-mobile/components/swipe-action/swipe-actions-auto-close.directive.ts, projects/addon-mobile/components/swipe-action/swipe-actions.component.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo/src/modules/components/pull-to-refresh/examples/1/index.ts, projects/demo/src/modules/components/pull-to-refresh/examples/2/index.ts, projects/demo/src/modules/components/pull-to-refresh/examples/import/import.md, projects/demo/src/modules/components/swipe-action/examples/1/index.ts, projects/demo/src/modules/components/swipe-action/examples/2/index.ts, projects/demo/src/modules/components/swipe-action/examples/3/index.ts, projects/demo/src/modules/components/swipe-action/examples/4/index.ts, projects/demo/src/modules/components/swipe-action/examples/5/index.ts
=> refactor: rename `TuiPullToRefresh`, `TuiSwipeActions`, `TuiSwipeActionsAutoClose`

projects/addon-doc/components/navigation/navigation.component.ts, projects/addon-doc/directives/scroll-into-view/scroll-into-view.directive.ts, projects/cdk/schematics/ng-update/v3/constants/types.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
=> refactor: rename `TuiScrollIntoViewLinkDirective` to `TuiScrollIntoViewLink`

projects/cdk/directives/platform/platform.directive.ts, projects/cdk/tokens/environment.ts, projects/cdk/types/index.ts, projects/cdk/types/platform.ts, projects/demo/src/modules/components/app-bar/examples/1/index.ts, projects/demo/src/modules/components/app-bar/examples/3/index.ts, projects/demo/src/modules/components/badge-notification/examples/1/index.ts, projects/demo/src/modules/components/badge/examples/3/index.ts, projects/demo/src/modules/components/block-status/examples/5/index.ts, projects/demo/src/modules/components/card-large/examples/1/index.ts, projects/demo/src/modules/components/card-large/examples/12/index.ts, projects/demo/src/modules/components/card-large/examples/2/index.ts, projects/demo/src/modules/components/checkbox/examples/1/index.ts, projects/demo/src/modules/components/radio/examples/1/index.ts, projects/demo/src/modules/components/radio/examples/2/index.ts, projects/demo/src/modules/components/switch/examples/1/index.ts, projects/experimental/components/tooltip/tooltip.options.ts
=> refactor: rename `TuiPlatformDirective` to `TuiPlatform`

projects/addon-doc/components/navigation/navigation.component.ts, projects/cdk/directives/auto-focus/autofocus.directive.ts, projects/cdk/directives/auto-focus/test/auto-focus.directive.spec.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/core/components/dialog/dialog.module.ts, projects/demo/src/modules/app/landing/index.ts, projects/demo/src/modules/components/data-list/examples/4/custom-list/index.ts, projects/demo/src/modules/components/dialog/examples/2/dialog-example/dialog-example.component.ts, projects/demo/src/modules/components/dialog/examples/6/index.ts, projects/demo/src/modules/components/dialog/examples/7/search-example/search-dialog-example.component.ts, projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts, projects/demo/src/modules/components/icons/icons-group/icons-group.component.ts, projects/demo/src/modules/components/input-inline/examples/2/index.ts, projects/demo/src/modules/components/select/examples/3/index.ts, projects/demo/src/modules/directives/auto-focus/examples/1/index.ts, projects/demo/src/modules/directives/auto-focus/examples/import/import.md, projects/kit/components/confirm/confirm.component.ts
=> refactor: rename `TuiAutoFocusDirective` to `TuiAutoFocus`

projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.component.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/addon-mobile/components/mobile-dialog/mobile-dialog.component.ts, projects/addon-mobile/directives/ripple/ripple.directive.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo/src/modules/components/card-medium/examples/7/index.ts, projects/demo/src/modules/directives/ripple/examples/1/index.ts, projects/demo/src/modules/directives/ripple/examples/2/index.ts, projects/demo/src/modules/directives/ripple/examples/import/import.md
=> refactor: rename `TuiRippleDirective` to `TuiRipple`

.idea/icon.svg
=> chore: add project icon (`.idea/icon.svg`)

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo/src/modules/components/input/examples/3/index.ts, projects/demo/src/modules/components/input/index.html, projects/kit/directives/unmask-handler/unmask-handler.directive.ts
=> refactor: rename `TuiUnmaskHandlerDirective` to `TuiUnmaskHandler`

projects/addon-charts/components/axes/axes.component.ts, projects/addon-charts/components/axes/test/axes.component.spec.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo/src/modules/components/axes/examples/1/index.ts, projects/demo/src/modules/components/axes/examples/2/index.ts, projects/demo/src/modules/components/axes/examples/3/index.ts, projects/demo/src/modules/components/axes/examples/import/import.md, projects/demo/src/modules/components/axes/index.ts, projects/demo/src/modules/components/bar-chart/examples/1/index.ts, projects/demo/src/modules/components/bar-chart/examples/2/index.ts, projects/demo/src/modules/components/line-chart/examples/1/index.ts, projects/demo/src/modules/components/line-chart/examples/2/index.ts, projects/demo/src/modules/components/line-chart/examples/3/index.ts, projects/demo/src/modules/components/line-chart/examples/4/index.ts, projects/demo/src/modules/components/line-chart/examples/5/index.ts, projects/demo/src/modules/components/line-chart/index.ts, projects/demo/src/modules/components/line-days-chart/examples/1/index.ts, projects/demo/src/modules/components/line-days-chart/examples/2/index.ts, projects/demo/src/modules/components/line-days-chart/index.ts
=> refactor: rename `TuiAxesComponent` to `TuiAxes`

projects/addon-charts/components/arc-chart/arc-chart.component.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo/src/modules/components/arc-chart/examples/1/index.ts, projects/demo/src/modules/components/arc-chart/examples/2/index.ts, projects/demo/src/modules/components/arc-chart/examples/import/import.md, projects/demo/src/modules/components/arc-chart/index.ts
=> refactor: rename `TuiArcChartComponent` to `TuiArcChart`

projects/core/directives/date-format/date-format.directive.ts, projects/demo/src/modules/directives/date-format/examples/1/index.ts, projects/demo/src/modules/directives/date-format/examples/import/import.md
=> refactor: rename `TuiDateFormatDirective` to `TuiDateFormat`

projects/kit/components/preview/pagination/preview-pagination.component.ts, projects/kit/components/preview/preview-action/preview-action.directive.ts, projects/kit/components/preview/preview.component.ts, projects/kit/components/preview/preview.module.ts, projects/kit/components/preview/title/preview-title.component.ts, projects/kit/components/preview/zoom/preview-zoom.component.ts
=> refactor: groupped inside TuiPreview

projects/cdk/directives/control/control.directive.ts, projects/cdk/directives/control/test/control.directive.spec.ts
=> refactor: rename `TuiControlDirective` to `TuiNgControl`

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo/src/modules/components/data-list/examples/2/index.ts, projects/demo/src/modules/components/data-list/examples/5/index.ts, projects/demo/src/modules/components/data-list/index.html, projects/demo/src/modules/components/line-clamp/examples/4/index.ts, projects/demo/src/modules/directives/dropdown-context/examples/2/index.ts, projects/kit/directives/data-list-dropdown-manager/data-list-dropdown-manager.directive.ts
=> refactor: rename `TuiDataListDropdownManagerDirective` to `TuiDataListDropdownManager`

projects/kit/components/input-number/input-number.component.ts
Reverts:
* https://github.com/taiga-family/taiga-ui/pull/7751
Closes #7079
=> fix(kit): `InputNumber` should emit form control change if value is less/more than `min`/`max`

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo/src/modules/components/card-large/examples/1/index.ts, projects/demo/src/modules/components/card-large/examples/10/index.ts, projects/demo/src/modules/components/card-large/examples/11/index.ts, projects/demo/src/modules/components/card-large/examples/12/index.ts, projects/demo/src/modules/components/card-large/examples/2/index.ts, projects/demo/src/modules/components/card-large/examples/3/index.ts, projects/demo/src/modules/components/card-large/examples/4/index.ts, projects/demo/src/modules/components/card-large/examples/5/index.ts, projects/demo/src/modules/components/card-large/examples/6/index.ts, projects/demo/src/modules/components/card-large/examples/7/index.ts, projects/demo/src/modules/components/card-large/examples/8/index.ts, projects/demo/src/modules/components/card-large/examples/9/index.ts, projects/demo/src/modules/components/experimental/navigation/examples/1/index.ts, projects/demo/src/modules/components/experimental/navigation/examples/2/index.ts, projects/demo/src/modules/components/experimental/navigation/examples/3/index.ts, projects/demo/src/modules/components/sheet/examples/3/index.ts, projects/demo/src/modules/directives/header/examples/1/index.ts, projects/demo/src/modules/directives/header/examples/2/index.ts, projects/demo/src/modules/directives/header/examples/3/index.ts, projects/demo/src/modules/directives/header/examples/import/import-module.md, projects/demo/src/modules/directives/skeleton/examples/1/index.ts, projects/layout/directives/header/header.directive.ts
=> refactor: rename `TuiHeaderDirective` to `TuiHeader`

projects/demo-playwright/tests/kit/input-number/input-number.spec.ts, projects/demo/src/modules/components/input-number/examples/8/index.html, projects/demo/src/modules/components/input-number/examples/8/index.ts, projects/demo/src/modules/components/input-number/index.html, projects/legacy/components/input-number/input-number.component.ts
=> fix(legacy): `InputNumber` has change detection problems when value is less/more than `min`/`max`

projects/demo/src/modules/components/avatar/examples/1/index.ts
=> chore: fix avatar example

.github/workflows/deploy-preview.yml
=> chore: switch preview account

projects/addon-doc/components/demo/index.ts, projects/addon-doc/components/documentation/documentation.component.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-toggle.spec.ts, projects/demo/src/modules/components/block/examples/3/index.ts, projects/demo/src/modules/components/cell/examples/2/index.ts, projects/demo/src/modules/components/data-list/examples/3/index.ts, projects/demo/src/modules/components/error/examples/1/index.ts, projects/demo/src/modules/components/experimental/navigation/examples/2/index.ts, projects/demo/src/modules/components/input-time/examples/5/index.ts, projects/demo/src/modules/components/island/examples/2/index.ts, projects/demo/src/modules/components/label/examples/3/index.ts, projects/demo/src/modules/components/swipe-action/examples/2/index.ts, projects/demo/src/modules/components/switch/examples/1/index.ts, projects/demo/src/modules/components/switch/examples/2/index.ts, projects/demo/src/modules/components/switch/examples/import/import.md, projects/demo/src/modules/components/table-filters/examples/1/index.ts, projects/demo/src/modules/directives/dropdown-hover/examples/2/index.ts, projects/demo/src/modules/directives/dropdown/examples/2/index.ts, projects/demo/src/modules/directives/dropdown/examples/3/index.ts, projects/demo/src/modules/directives/dropdown/examples/4/index.ts, projects/demo/src/modules/directives/dropdown/examples/5/index.ts, projects/demo/src/modules/directives/sensitive/examples/1/index.ts, projects/demo/src/modules/directives/sensitive/examples/2/index.ts, projects/demo/src/modules/directives/skeleton/examples/1/index.ts, projects/demo/src/modules/directives/skeleton/examples/2/index.ts, projects/demo/src/modules/directives/theme/examples/1/index.ts, projects/kit/components/switch/switch.component.ts
=> refactor: rename `TuiSwitchComponent` to `TuiSwitch`

projects/cdk/directives/element/element.directive.ts, projects/cdk/directives/resizer/resizeable.directive.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/demo/src/modules/components/services/scroll-service/examples/1/index.ts, projects/demo/src/modules/directives/element/examples/1/index.ts, projects/demo/src/modules/directives/element/examples/import/import.md, projects/kit/components/data-list-wrapper/data-list-group-wrapper.component.ts, projects/kit/components/data-list-wrapper/data-list-wrapper.component.ts
=> refactor: rename `TuiElementDirective` to `TuiElement`

projects/demo/src/modules/components/block/examples/1/index.ts, projects/demo/src/modules/components/block/examples/2/index.ts, projects/demo/src/modules/components/block/examples/3/index.ts, projects/demo/src/modules/components/block/examples/import/import.md, projects/demo/src/modules/components/group/examples/3/index.ts, projects/demo/src/modules/components/group/examples/4/index.ts, projects/demo/src/modules/components/items-with-more/examples/2/index.ts, projects/demo/src/modules/markup/form/examples/1/index.ts, projects/kit/components/block/block.directive.ts, projects/kit/components/filter/filter.component.ts
=> refactor: rename `TuiBlockDirective` to `TuiBlock`

projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts, projects/addon-commerce/components/input-card-grouped/input-card-grouped.options.ts, projects/addon-commerce/components/input-card-grouped/input-card-grouped.providers.ts, projects/addon-commerce/components/input-card/input-card.directive.ts, projects/addon-commerce/components/input-card/input-card.options.ts, projects/addon-commerce/components/thumbnail-card/thumbnail-card.component.ts, projects/addon-commerce/constants/default-card-validator.ts, projects/addon-commerce/constants/mask-card.ts, projects/addon-commerce/constants/mask-cvc.ts, projects/addon-commerce/pipes/amount/amount.options.ts, projects/addon-commerce/pipes/amount/amount.pipe.ts, projects/addon-commerce/pipes/amount/amount.types.ts, projects/addon-commerce/pipes/amount/amount.utils.ts, projects/addon-commerce/tokens/i18n.ts, projects/addon-commerce/tokens/payment-system-icons.ts, projects/addon-commerce/utils/format-currency.ts, projects/addon-commerce/utils/is-card-number-valid.ts, projects/addon-commerce/utils/is-expire-valid.ts, projects/addon-commerce/validators/card-expire.validator.ts, projects/addon-commerce/validators/card-number.validator.ts, projects/addon-commerce/validators/luhn.validator.ts
=> refactor(addon-commerce): use deep entry points for imports of other Taiga packages

.github/workflows/deploy-preview.yml, projects/cdk/schematics/migration.json, projects/cdk/schematics/ng-update/v4/icons/rename-icons.ts, projects/cdk/schematics/ng-update/v4/migrate-icons.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-icons.spec.ts, projects/demo/src/modules/directives/dropdown/examples/1/index.html
=> chore: add public icons migration

projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts, projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.component.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.const.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.providers.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.strategy.ts, projects/addon-mobile/components/mobile-dialog/mobile-dialog.component.ts, projects/addon-mobile/components/mobile-dialog/mobile-dialog.options.ts, projects/addon-mobile/components/mobile-dialog/mobile-dialog.service.ts, projects/addon-mobile/components/pull-to-refresh/loader-android/loader-android.component.ts, projects/addon-mobile/components/pull-to-refresh/loader-ios/loader-ios.component.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.providers.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.service.ts, projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts, projects/addon-mobile/components/sheet-dialog/sheet-dialog.directive.ts, projects/addon-mobile/components/sheet-dialog/sheet-dialog.options.ts, projects/addon-mobile/components/sheet-dialog/sheet-dialog.service.ts, projects/addon-mobile/components/swipe-action/swipe-actions-auto-close.directive.ts, projects/addon-mobile/components/tab-bar/tab-bar-item.component.ts, projects/addon-mobile/components/tab-bar/tab-bar-item.directive.ts, projects/addon-mobile/components/tab-bar/tab-bar.component.ts, projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts, projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.directive.ts, projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts, projects/addon-mobile/directives/ripple/ripple.directive.ts, projects/addon-mobile/directives/sidebar/sidebar.component.ts, projects/addon-mobile/directives/sidebar/sidebar.directive.ts, projects/addon-mobile/directives/touchable/touchable.directive.ts, projects/addon-mobile/services/keyboard.service.ts
=> refactor(addon-mobile): use deep entry points for imports of other Taiga packages

projects/addon-table/components/reorder/reorder.component.ts, projects/addon-table/components/reorder/reorder.options.ts, projects/addon-table/components/table-pagination/table-pagination.component.ts, projects/addon-table/components/table-pagination/table-pagination.options.ts, projects/addon-table/components/table/directives/resized.directive.ts, projects/addon-table/components/table/directives/sort-by.directive.ts, projects/addon-table/components/table/directives/stuck.directive.ts, projects/addon-table/components/table/directives/table.directive.ts, projects/addon-table/components/table/pipes/table-sort.pipe.ts, projects/addon-table/components/table/providers/table.provider.ts, projects/addon-table/components/table/table.options.ts, projects/addon-table/components/table/tbody/tbody.component.ts, projects/addon-table/components/table/th-group/th-group.component.ts, projects/addon-table/components/table/th/th.component.ts, projects/addon-table/components/table/tr/tr.component.ts, projects/addon-table/directives/table-filters/generic-filter.directive.ts, projects/addon-table/directives/table-filters/table-filter.directive.ts, projects/addon-table/tokens/i18n.ts, projects/addon-table/types/row-context.ts
Partially solves https://github.com/taiga-family/taiga-ui/issues/6723
=> refactor(addon-table): use deep entry points for imports of other Taiga packages

projects/experimental/components/navigation/aside.component.ts, projects/experimental/components/navigation/header.component.ts, projects/experimental/components/navigation/hint-aside.directive.ts, projects/experimental/components/navigation/nav.component.ts, projects/experimental/components/navigation/navigation.module.ts, projects/layout/components/app-bar/app-bar.component.ts, projects/layout/components/app-bar/app-bar.providers.ts, projects/layout/directives/block-details/block-details.directive.ts, projects/layout/directives/card/card.directive.ts, projects/layout/directives/cell/cell.directive.ts, projects/layout/directives/header/header.directive.ts, projects/testing/core/island.harness.ts, projects/testing/mocks/sanitizer.ts, projects/testing/utils/date.ts, projects/testing/utils/replace-nbsp.ts
Partially solves https://github.com/taiga-family/taiga-ui/issues/6723
=> refactor(experimental,layout,testing): use deep entry points for imports of other Taiga packages

projects/addon-commerce/components/input-card/input-card.directive.ts, projects/core/components/icon/icon.component.ts, projects/core/components/icon/icon.pipe.ts, projects/core/directives/icons/icons.directive.ts, projects/core/tokens/icon-resolver.ts, projects/core/tokens/icons.ts, projects/core/tokens/index.ts, projects/kit/components/checkbox/checkbox.component.ts, projects/kit/components/switch/switch.component.ts
=> feat(core): `Icon` allow bundling named icons

projects/addon-doc/components/demo/index.html, projects/addon-doc/components/demo/index.ts, projects/addon-table/components/table/tbody/tbody.component.ts, projects/addon-table/types/index.ts, projects/addon-table/types/row-context.ts, projects/cdk/directives/resizer/index.ts, projects/cdk/directives/resizer/resizable.directive.ts, projects/cdk/directives/resizer/resizer.directive.ts, projects/core/directives/hint/hint-position.directive.ts, projects/core/directives/hint/hint.directive.ts, projects/demo/src/modules/directives/resizer/examples/1/index.html, projects/demo/src/modules/directives/resizer/examples/1/index.ts, projects/demo/src/modules/directives/resizer/examples/import/import.md, projects/demo/src/modules/directives/resizer/examples/import/template.md
=> refactor: directive rename

.github/workflows/create-release.yml, projects/demo/project.json
=> ci: do not generate release body for prerelease

.github/workflows/e2e-playwright.yml
=> chore: fix e2e matrix status check

projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-phone-international/input-phone-international.template.html
Closes # https://github.com/taiga-family/taiga-ui/issues/7912
=> fix(kit): phone international dropdown open

projects/core/package.json
=> fix(core): add styles to exports

projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-overscroll.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-overscroll.spec.ts, projects/cdk/schematics/utils/templates/elements.ts
=> chore(cdk): migrate tuiOverscroll

projects/cdk/schematics/ng-add/constants/modules.ts, projects/cdk/schematics/ng-add/constants/versions.ts, projects/cdk/schematics/ng-add/index.ts, projects/cdk/schematics/ng-add/schema.json, projects/cdk/schematics/ng-add/schema.ts, projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts, projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts, projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts
=> chore: update ng-add

projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
=> chore: add some name migrations

projects/cdk/schematics/ng-update/interfaces/replacement-type.ts, projects/cdk/schematics/ng-update/steps/rename-types.ts, projects/cdk/schematics/ng-update/v4/index.ts, projects/cdk/schematics/ng-update/v4/steps/constants/types.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-money.spec.ts
=> chore: `TuiDocExample` type add migration

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-option-providers.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-input-count.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-providers.spec.ts
Relates to:
* https://github.com/taiga-family/taiga-ui/issues/5808
=> chore(cdk): add schematic migrations for legacy textfields

package.json, projects/demo-playwright/tests/demo/get-demo-paths.ts
Relates to:
* https://github.com/taiga-family/linters/pull/439
=> chore: use `plugin:@taiga-ui/experience/entry-points`

projects/cdk/schematics/migration.json
=> chore: change migrations version

projects/addon-mobile/styles/common/button.less, projects/cdk/directives/platform/platform.directive.ts, projects/core/components/calendar/calendar-sheet.style.less, projects/core/components/root/root.component.ts, projects/core/styles/taiga-ui-theme.less, projects/core/styles/theme/appearance.less, projects/core/styles/theme/calendar.less, projects/demo/src/modules/app/app.config.ts, projects/demo/src/modules/components/card-large/examples/1/index.ts
=> refactor(core): `Root` use `Platform` directive

projects/addon-doc/components/main/main.style.less, projects/core/styles/theme/appearance/glass.less, projects/core/styles/theme/appearance/opposite.less, projects/core/styles/theme/appearance/textfield.less, projects/core/styles/theme/variables.less, projects/kit/directives/skeleton/skeleton.style.less, projects/legacy/styles/wrapper/icon.less
=> chore: simplify vars

projects/cdk/schematics/ng-update/v4/migrate-css-vars/palette.ts
=> chore: add shadow migration

projects/cdk/schematics/ng-update/utils/templates/template-comments.ts, projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts, projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts, projects/cdk/schematics/ng-update/v4/steps/constants/types.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-mode.spec.ts, projects/cdk/schematics/utils/templates/elements.ts
=> chore: add mode and theme migration

projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
Relates:
* https://github.com/taiga-family/taiga-ui/pull/6983
* https://github.com/taiga-family/taiga-ui/pull/7846
=> chore(cdk): fix migration for `tui-checkbox-labeled` and `tui-radio-labeled`

projects/cdk/schematics/ng-update/v4/steps/constants/enums.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-checkbox.spec.ts, projects/demo/src/modules/components/tabs/examples/import/import.md
=> chore: add TuiNotification, Tabs, TuiRadioLabeledModule migration

projects/cdk/schematics/ng-update/v4/steps/migrate-destroy-service.ts
=> chore: fix TuiDestroyService migration

package-lock.json, package.json, projects/core/styles/theme/appearance/secondary.less, projects/kit/components/input-phone-international/input-phone-international.component.ts
=> chore: fixes

projects/demo/src/modules/markup/colors/index.html, projects/demo/src/modules/markup/colors/index.ts, projects/demo/src/styles/styles.less, projects/demo/used-icons.ts, projects/kit/components/block/block.directive.ts
=> refactor: add colors switch

projects/addon-mobile/components/tab-bar/tab-bar.style.less
=> feat(addon-mobile): update `TabBar` styles

projects/demo/src/index.html, projects/demo/src/polyfills.ts
=> chore(demo): fix security vulnerability

projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.template.html
=> fix(addon-mobile): prevent touchstart after close sheet

projects/addon-commerce/components/input-card-grouped/input-card-grouped.component.ts
close https://github.com/taiga-family/taiga-ui/issues/7893
=> feat(addon-commerce): add `cvcHidden` input property

projects/core/components/button/button.directive.ts, projects/core/components/data-list/option.component.ts, projects/core/components/link/link.directive.ts, projects/core/components/textfield/textfield.component.ts, projects/core/directives/appearance/index.ts, projects/core/directives/appearance/with-appearance.ts, projects/core/directives/icons/index.ts, projects/core/directives/icons/with-icons.ts, projects/core/pipes/flag/flag.pipe.ts, projects/core/pipes/flag/test/flag.pipe.spec.ts, projects/core/tokens/assets-path.ts, projects/core/tokens/icon-resolver.ts, projects/kit/components/avatar/avatar.component.ts, projects/kit/components/badge/badge.directive.ts, projects/kit/components/block/block.directive.ts, projects/kit/components/checkbox/checkbox.component.ts, projects/kit/components/chip/chip.directive.ts, projects/kit/components/files/input-files/input-files.directive.ts, projects/kit/components/radio/radio.component.ts, projects/kit/components/switch/switch.component.ts, projects/kit/components/tabs/tab.directive.ts, projects/kit/directives/tooltip/tooltip.directive.ts
=> refactor: add some host directives

projects/cdk/schematics/ng-update/v4/steps/constants/enums.ts, projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts
=> chore: migrate card-grouped tag, some enums

projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts
=> chore(demo): add missing @taiga-ui/ packages to stackblitz

projects/cdk/schematics/ng-update/v4/migrate-css-vars/palette.ts, projects/cdk/schematics/ng-update/v4/migrate-css-vars/rename-css-vars.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-css-vars.spec.ts
=> chore: fix css chart migration

projects/cdk/schematics/ng-update/v4/migrate-icons/rename-proprietary-icons.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-icons.spec.ts
=> chore: update proprietry-icons migration

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
=> chore: update proprietary migrations

scripts/shared/run-standard-version.ts
=> chore: fix release script

package-lock.json, package.json, projects/addon-charts/package.json, projects/addon-commerce/package.json, projects/addon-doc/package.json, projects/addon-mobile/package.json, projects/addon-table/package.json, projects/cdk/constants/version.ts, projects/cdk/package.json, projects/core/package.json, projects/experimental/package.json, projects/i18n/package.json, projects/icons/package.json, projects/kit/package.json, projects/layout/package.json, projects/legacy/package.json, projects/styles/package.json, projects/taiga-schematics/package.json, projects/testing/package.json, scripts/publish.ts, scripts/shared/run-standard-version.ts
=> 🚀 Release/4.0.0-rc.3

.cspell.json
=> chore: fix cspell lint

projects/cdk/schematics/ng-update/v4/steps/update-packages.ts
=> chore: fix generated exports in cdk package.json

projects/demo/src/modules/experimental/action-bar/action-bar.component.ts, projects/demo/src/modules/experimental/action-bar/examples/1/index.less, projects/demo/src/modules/experimental/action-bar/examples/1/index.ts, projects/experimental/components/action-bar/action-bar.style.less
=> chore: fix action-bar night colors

projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.template.html
=> fix(addon-mobile): dropdown mobile arrow doesn't rotate when click on overlay

projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/demo-routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/badge/examples/1/index.html, projects/demo/src/modules/components/badge/index.html, projects/demo/src/modules/components/badge/index.ts, projects/demo/src/modules/components/status/examples/1/index.html, projects/demo/src/modules/components/status/examples/1/index.ts, projects/demo/src/modules/components/status/examples/import/import.md, projects/demo/src/modules/components/status/examples/import/template.md, projects/demo/src/modules/components/status/index.html, projects/demo/src/modules/components/status/index.ts, projects/kit/components/badge/badge.directive.ts, projects/kit/components/badge/badge.options.ts, projects/kit/components/badge/badge.style.less, projects/kit/components/index.ts, projects/kit/components/progress/progress-bar/progress-bar.component.less, projects/kit/components/status/index.ts, projects/kit/components/status/ng-package.json, projects/kit/components/status/status.directive.ts, projects/kit/components/status/status.style.less
=> feat(kit): `Status` add new component

scripts/shared/ignorable-packages.ts
=> chore: add ignorable packages

projects/addon-table/components/table/directives/table.directive.ts, projects/addon-table/components/table/directives/table.style.less, projects/addon-table/components/table/td/td.component.ts, projects/addon-table/components/table/td/td.style.less, projects/addon-table/components/table/th/th.style.less, projects/demo/src/modules/components/table/examples/2/index.html, projects/demo/src/modules/components/table/examples/2/index.less, projects/demo/src/modules/components/table/examples/2/index.ts
=> feat(addon-table): fix for `Cell` and `Title`

projects/kit/components/progress/progress.options.ts
=> fix(kit): correct `TuiProgressOptions` size types

projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/experimental/badge/badge.component.ts, projects/demo/src/modules/experimental/badge/badge.module.ts, projects/demo/src/modules/experimental/badge/badge.template.html, projects/demo/src/modules/experimental/badge/examples/1/index.html, projects/demo/src/modules/experimental/status/examples/1/index.html, projects/demo/src/modules/experimental/status/examples/1/index.ts, projects/demo/src/modules/experimental/status/examples/import/import.md, projects/demo/src/modules/experimental/status/examples/import/insert.md, projects/demo/src/modules/experimental/status/status.component.ts, projects/demo/src/modules/experimental/status/status.module.ts, projects/demo/src/modules/experimental/status/status.template.html, projects/experimental/components/badge/badge.directive.ts, projects/experimental/components/badge/badge.options.ts, projects/experimental/components/badge/badge.style.less, projects/experimental/components/index.ts, projects/experimental/components/status/index.ts, projects/experimental/components/status/ng-package.json, projects/experimental/components/status/status.component.ts, projects/experimental/components/status/status.directive.ts, projects/experimental/components/status/status.module.ts, projects/experimental/components/status/status.style.less, projects/kit/components/progress/progress-bar/progress-bar.component.less
=> feat(experimental): `Status` add new component

projects/cdk/schematics/ng-update/interfaces/replacement-identifier.ts, projects/cdk/schematics/ng-update/steps/replace-identifier.ts, projects/cdk/schematics/ng-update/v4/index.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-root.ts, projects/cdk/schematics/ng-update/v4/steps/update-packages.ts, projects/cdk/schematics/ng-update/v4/steps/utils/replace-modules-with-providers.ts, projects/cdk/schematics/ng-update/v4/tests/replace-modules-with-providers.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-enums.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-identifiers.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
=> chore: fix migrations

projects/kit/directives/sensitive/sensitive.style.less
=> fix(kit): `Sensitive` set "display" only for inline elements

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/core/components/alert/alert.component.ts, projects/core/components/alert/alert.directive.ts, projects/core/components/alert/alert.service.ts
=> feat(core): rename `TuiAlertDirective` to `TuiAlert`

projects/core/components/dialog/dialog.directive.ts, projects/core/components/dialog/dialog.ts, projects/core/components/dialog/index.ts
=> feat(core): rename `TuiDialogDirective` to `TuiDialog`

projects/cdk/schematics/ng-update/v4/index.ts, projects/cdk/schematics/ng-update/v4/migrate-icons/rename-icons.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/index.ts, projects/cdk/schematics/ng-update/v4/steps/constants/services.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-progress-segmented.spec.ts
=> chore: some migration fixes

.github/workflows/publish.yml
=> chore: disable announce for rc

projects/demo-cypress/src/tests/range.cy.ts, projects/demo/src/modules/components/range/index.html, projects/demo/src/modules/components/range/index.ts, projects/kit/components/range/range.component.ts
=> feat(kit): add margin and limit properties for Range component

projects/demo/src/modules/components/experimental/navigation/examples/1/index.html
=> chore(experimental): `Navigation` fix example

projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts
=> fix(addon-mobile): display mobile calendar range

projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.component.ts, projects/addon-mobile/directives/dropdown-mobile/dropdown-mobile.style.less, projects/core/components/hosted-dropdown/dropdown-open-monitor.directive.ts, projects/core/components/hosted-dropdown/hosted-dropdown.template.html, projects/core/components/root/root.style.less, projects/demo/src/modules/directives/dropdown/examples/5/index.html, projects/demo/src/modules/directives/dropdown/examples/5/index.ts
=> fix(addon-mobile): `DropdownMobile` fix open status report

projects/addon-commerce/components/input-card/input-card.directive.ts, projects/addon-commerce/components/input-cvc/input-cvc.directive.ts, projects/addon-commerce/components/input-expire/input-expire.directive.ts, projects/kit/utils/index.ts, projects/kit/utils/maskito.binding.ts
=> feat: add Maskito binding helper

projects/demo-playwright/tests/deep/deep-select.spec.ts, projects/demo-playwright/tests/kit/input-year/input-year.spec.ts
=> chore: fix flaky e2e

projects/cdk/tokens/environment.ts, projects/core/directives/dropdown/dropdown-context.directive.ts
=> feat(core): `DropdownContext` implement for iOS

projects/legacy/components/color-selector/color-edit/color-edit.module.ts, projects/legacy/components/input-color/input-color.module.ts
Relates:
* https://github.com/taiga-family/maskito/issues/1136
=> chore(legacy): replace import of legacy `MaskitoModule` by `MaskitoDirective`

projects/core/directives/dropdown/dropdown.component.ts, projects/core/directives/hint/hint.component.ts, projects/core/directives/hint/test/hint.directive.spec.ts, projects/core/services/position.service.ts
=> refactor: optimize style calculation

projects/core/components/data-list/data-list.style.less, projects/core/components/data-list/option.component.ts, projects/core/styles/theme/variables.less, projects/demo-playwright/tests/kit/action-bar/action-bar.mobile.spec.ts, projects/demo-playwright/tests/kit/action-bar/action-bar.spec.ts, projects/demo/src/modules/components/block/examples/1/index.html, projects/demo/src/modules/components/block/examples/1/index.less, projects/demo/src/modules/components/block/examples/1/index.ts, projects/demo/src/modules/components/block/examples/3/index.html, projects/demo/src/modules/components/block/examples/3/index.less, projects/demo/src/modules/components/filter/examples/4/index.html, projects/demo/src/modules/components/filter/examples/4/index.less, projects/demo/src/modules/components/filter/examples/4/index.ts, projects/demo/src/modules/components/filter/index.ts, projects/kit/components/block/block.directive.ts, projects/kit/components/block/block.options.ts, projects/kit/components/block/block.style.less, projects/kit/components/filter/filter.component.ts, projects/kit/components/filter/filter.style.less, projects/kit/components/filter/filter.template.html, projects/kit/components/switch/switch.style.less
=> refactor: `Block` update to new specs

projects/core/directives/dropdown/dropdown-open.directive.ts, projects/demo-playwright/tests/kit/input/input.spec.ts
=> chore(legacy): `Input` has broken keyboard navigation

projects/core/styles/taiga-ui-fonts.less
- _(20.01.2023)_ Remove quotes https://github.com/taiga-family/taiga-ui/pull/3469
⬇️ 
- _(30.01.2024)_ Add quotes again https://github.com/taiga-family/taiga-ui/pull/6598
⬇️ 
- _(current PR)_ Remove it again 😄 
* https://github.com/stackblitz/core/issues/2104#issuecomment-1397086512
=> chore(core): remove quotes inside  function in `taiga-ui-fonts.less`

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-identifiers.spec.ts
=> chore: `migrations` spread component arrays inside modules

projects/demo/src/modules/components/select/examples/11/index.html, projects/legacy/classes/abstract-native-select.ts, projects/legacy/components/select/native-select/native-select-group.component.ts, projects/legacy/components/select/native-select/native-select-group.template.html, projects/legacy/components/select/native-select/native-select.component.ts, projects/legacy/components/select/native-select/native-select.template.html
=> fix(legacy): `NativeSelect` add placeholder

projects/kit/components/calendar-range/calendar-range.component.ts, projects/kit/components/calendar-range/test/calendar-range.component.spec.ts
=> chore(kit): change access modifier for property

projects/addon-commerce/components/thumbnail-card/index.ts, projects/addon-commerce/components/thumbnail-card/thumbnail-card.component.ts, projects/addon-commerce/components/thumbnail-card/thumbnail-card.options.ts, projects/addon-commerce/components/thumbnail-card/thumbnail-card.template.html, projects/demo/src/modules/components/thumbnail-card/index.html, projects/demo/src/modules/components/thumbnail-card/index.ts
=> feat(addon-commerce): `ThumbnailCard` add DI options

projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/index.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-button-appearance.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button-appearance.spec.ts
=> chore(cdk): migrate button appearance

projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
=> chore(schematics): migration for `a[tuiIconButton]` & `button[tuiIconButton]`

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
=> chore(schematics): migration for `tuiButtonOptionsProvider` from `@taiga-ui/experimental`

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/legacy/utils/capitalize-first-letter.ts, projects/legacy/utils/index.ts
=> chore: migrate `capitalizeFirstLetter`

projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-svg.spec.ts
relates to:
https://github.com/taiga-family/taiga-ui/issues/8162
=> chore: add icon migration

projects/demo/src/modules/components/multi-select/examples/12/index.html, projects/demo/src/modules/components/multi-select/examples/12/index.ts, projects/demo/src/modules/components/multi-select/index.html
https://taiga-ui--pr8185-multi-select-with-ne-maf97z79.web.app/components/multi-select#nested-datalist
=> chore(demo): new example (`MultiSelect` with nested `DataList`)

projects/demo-playwright/tests/kit/input-year/input-year.spec.ts
=> refactor: use `pressSequentially`

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/templates/toggles/migrate-checkbox.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-checkbox.spec.ts
=> chore(schematics): migration for `PrimitiveCheckbox`

.cspell.json, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-blocked.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
Relates:
See also:
* https://github.com/taiga-family/taiga-ui/issues/5808#issuecomment-1966326575
=> chore(schematics): migrations `<tui-checkbox-block />` & `<tui-radio-block />`

projects/cdk/schematics/ng-update/v4/migrate-icons/rename-icons.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-icons.spec.ts
=> chore: fix icons migration

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
=> chore: spread some consts in modules

projects/core/components/expand/expand.component.ts
Closes https://github.com/taiga-family/taiga-ui/issues/7733
=> fix(core): skip hydration for eager content

projects/cdk/tokens/index.ts, projects/cdk/tokens/is-touch.ts, projects/core/directives/dropdown/dropdown-context.directive.ts
=> fix(core): fix dropdown-context directive on touchscreen laptops

projects/cdk/schematics/ng-update/steps/replace-identifier.ts
https://github.com/user-attachments/assets/af0ee451-9092-4cf9-b596-79dbd8cb62e1
=> chore(schematics): fix progress indicator for `replacing identifiers` step

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
=> chore(schematics): migrations for `TuiInput`,  `TuiButton`, `TuiLineClamp`, `TuiLabel`, `TuiLink` classes

projects/cdk/schematics/ng-update/v4/migrate-icons/rename-proprietary-icons.ts
=> chore: fix proprietary-icons migration

projects/addon-doc/components/code/index.less, projects/core/styles/theme/palette.less, projects/demo/src/modules/app/home/home.style.less
=> chore: fix border color

projects/addon-doc/components/code/tests/code.component.spec.ts, projects/addon-mobile/styles/ios/checkbox.less, projects/core/components/icon/icon.component.ts, projects/core/components/textfield/textfield.style.less, projects/core/directives/icons/icons.directive.ts, projects/core/styles/components/button.less, projects/core/styles/components/icon.less, projects/core/styles/components/icons.less, projects/core/styles/components/link.less, projects/core/styles/mixins/mixins.less, projects/core/styles/mixins/mixins.scss, projects/kit/components/badge/badge.style.less, projects/kit/components/switch/switch.component.ts, projects/kit/components/switch/switch.style.less, projects/kit/components/tabs/tabs.style.less, projects/layout/components/navigation/nav.style.less
=> chore: simplify icons

projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-number-precision.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-number-precision.spec.ts
=> chore: migrate input-number precision and decimal, fix files module migration, add todo

projects/cdk/package.json, projects/cdk/schematics/ng-update/v4/steps/update-packages.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-package-names.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
=> chore: add layout package if needed

projects/cdk/schematics/ng-update/v4/steps/styles/migrate-space-mixins.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
Relates:
* https://github.com/taiga-family/taiga-ui/pull/8269
=> chore(schematics): fix migration for `tui-space` style mixin (it can be used with negative values)

projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/addon-mobile/components/mobile-calendar/mobile-calendar.template.html, projects/demo/src/modules/components/mobile-calendar/examples/6/index.html, projects/demo/src/modules/components/mobile-calendar/examples/6/index.less, projects/demo/src/modules/components/mobile-calendar/examples/6/index.ts, projects/demo/src/modules/components/mobile-calendar/mobile-calendar.component.ts, projects/demo/src/modules/components/mobile-calendar/mobile-calendar.module.ts, projects/demo/src/modules/components/mobile-calendar/mobile-calendar.template.html
=> feat(addon-mobile): possibility drop mobile calendar header

projects/cdk/schematics/ng-update/v4/steps/migrate-alert-service.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-alert-service.spec.ts
=> chore(schematics): migrations for `TuiAlertService` options (`hasIcon`, `hasCloseButton`, `defaultAutoCloseTime`)

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
=> chore(schematics): add migration comment for deleted `TuiIllustrationsModule`

projects/cdk/schematics/ng-update/v4/steps/templates/migrate-avatar.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts
=> chore: migrate avatar autoColor

projects/demo/src/modules/components/action-bar/examples/1/index.ts, projects/demo/src/modules/components/filter/examples/1/index.ts, projects/demo/src/modules/components/filter/examples/2/index.ts, projects/demo/src/modules/components/filter/examples/3/index.ts, projects/demo/src/modules/components/filter/examples/4/index.ts, projects/demo/src/modules/components/filter/index.ts, projects/kit/components/filter/filter.component.ts, projects/kit/components/filter/test/filter.component.spec.ts
=> refactor(kit)!: rename `TuiFilterComponent` to `TuiFilter`

projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/index.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-notification.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-notification.spec.ts
=> chore(schematics): migrations for `<tui-notification />` (`[size]` & `[hideClose]` attributes)

projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/index.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-axes.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-axes.spec.ts
Part of https://github.com/taiga-family/taiga-ui/issues/5808
=> chore(schematics): migrate axes

projects/cdk/schematics/ng-update/v4/steps/templates/migrate-notification.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-notification.spec.ts
=> chore(schematics): wrap all content projection with `<div>` if `<tui-notification>` includes children >= 2

projects/cdk/schematics/ng-update/v3/constants/warnings.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts
=> chore: fix CurrencyPipe, TuiPromptModule migration. Add warning for TUI_ANIMATIONS_DURATION token

projects/cdk/schematics/ng-update/v4/steps/styles/index.ts, projects/cdk/schematics/ng-update/v4/steps/styles/migrate-text-mixins.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
Relates: 
* https://github.com/taiga-family/taiga-ui/issues/5808
=> chore(schematics): migrations for style mixins for texts

projects/cdk/schematics/ng-update/v4/steps/styles/migrate-space-mixins.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
Relates:
* https://github.com/taiga-family/taiga-ui/pull/8269
=> chore(schematics): fix corner case of migration for style mixins `tui-space`

README.md
=> chore: add link to next version

projects/legacy/components/input-number/input-number.style.less
Closes https://github.com/taiga-family/taiga-ui/issues/7190
=> fix(legacy): fix inputnumber component overflowing container in row layout

projects/core/components/scrollbar/index.ts, projects/core/components/scrollbar/scrollbar.component.ts, projects/core/components/scrollbar/scrollbar.options.ts, projects/core/components/scrollbar/scrollbar.style.less, projects/core/components/scrollbar/scrollbar.template.html, projects/demo/src/modules/components/scrollbar/examples/7/index.html, projects/demo/src/modules/components/scrollbar/examples/7/index.less, projects/demo/src/modules/components/scrollbar/examples/7/index.ts, projects/demo/src/modules/components/scrollbar/index.html, projects/demo/src/modules/components/scrollbar/index.ts
=> feat(core): add `mode` for `tui-scrollbar`

projects/kit/components/calendar-range/calendar-range.component.ts, projects/kit/components/calendar-range/test/calendar-range.component.spec.ts
=> fix(kit): `CalendarRange` defaultViewedMonth set to min, if min later than current month

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts
Relates:
* https://github.com/taiga-family/taiga-ui/issues/5808
=> chore(schematics): more identifiers migrations

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/types.ts
Relates:
* https://github.com/taiga-family/taiga-ui/issues/5808
=> chore(schematics): migrations for `TuiDeepPartial` & `TuiMarkerIconMode`

projects/demo/src/modules/components/rating/examples/1/index.ts, projects/demo/src/modules/components/rating/examples/2/index.ts, projects/demo/src/modules/components/rating/examples/3/index.ts, projects/kit/components/rating/rating.component.ts
https://github.com/taiga-family/taiga-ui/blob/7ac37af2f6c6a3fcf670587f8c9db94b10bab2f9/projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts#L696-L701
=> chore(kit): rename `TuiRatingComponent` => `TuiRating`

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badged-content.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badged-content.spec.ts
=> chore: fix badged-content migration, add some identifiers migration

projects/cdk/schematics/ng-update/v4/steps/styles/index.ts, projects/cdk/schematics/ng-update/v4/steps/styles/migrate-shadow-mixins.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
**`v3.x` branch:**
https://github.com/taiga-family/taiga-ui/blob/f3f05f9ad79011567ae6f952bc81407679cda41f/projects/core/styles/mixins/mixins.less#L199-L236
**`main` branch:**
https://github.com/taiga-family/taiga-ui/blob/bc8811bb437ee54cc606d697c7fa975cef58de0c/projects/cdk/schematics/ng-update/v4/migrate-css-vars/palette.ts#L85-L91
Closes #8363
=> chore(schematics): migrations for shadow style mixins

projects/cdk/schematics/ng-update/v4/steps/templates/migrate-notification.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-notification.spec.ts
=> chore(schematics): migration for `[hasIcon]` property of `<tui-notification>` / `[tuiNotification]`

projects/demo/src/modules/components/combo-box/index.html, projects/demo/src/modules/components/input-copy/index.html, projects/demo/src/modules/components/input-date-multi/index.html, projects/demo/src/modules/components/input-date-range/index.html, projects/demo/src/modules/components/input-date-time/index.html, projects/demo/src/modules/components/input-date/index.html, projects/demo/src/modules/components/input-month-range/index.html, projects/demo/src/modules/components/input-month/index.html, projects/demo/src/modules/components/input-number/index.html, projects/demo/src/modules/components/input-password/index.html, projects/demo/src/modules/components/input-phone-international/index.html, projects/demo/src/modules/components/input-phone/index.html, projects/demo/src/modules/components/input-range/index.html, projects/demo/src/modules/components/input-slider/index.html, projects/demo/src/modules/components/input-tag/index.html, projects/demo/src/modules/components/input-time/index.html, projects/demo/src/modules/components/input-year/index.html, projects/demo/src/modules/components/input/index.html, projects/demo/src/modules/components/multi-select/index.html, projects/demo/src/modules/components/select/index.html, projects/demo/src/modules/components/tag/index.html, projects/demo/src/modules/components/tag/index.ts
=> chore(demo): update component packages

projects/cdk/schematics/ng-update/interfaces/replacement-attribute-value.ts, projects/cdk/schematics/ng-update/utils/templates/replace-attr-values.ts, projects/cdk/schematics/ng-update/v3/constants/templates.ts, projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
=> chore: add pseudo-* inputs migration

projects/demo/src/modules/components/navigation/examples/2/index.html, projects/layout/components/navigation/aside.style.less, projects/layout/components/navigation/header.style.less, projects/layout/components/navigation/main.style.less, projects/layout/components/navigation/nav.style.less
=> feat(layout): `Navigation` implement grid

projects/legacy/components/input-password/input-password.template.html
=> fix(legacy): reuse cursor position after showing password

projects/addon-doc/components/documentation/documentation.style.less
=> feat(addon-doc): input switch should be aligned right

projects/cdk/schematics/ng-update/v4/steps/styles/index.ts, projects/cdk/schematics/ng-update/v4/steps/styles/migrate-less-scss-constants.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
=> chore(schematics): migration for style variable `@space` / `$space`

projects/core/components/data-list/data-list.tokens.ts, projects/demo/src/modules/components/input-time/examples/6/index.html, projects/demo/src/modules/components/input-time/examples/6/index.ts, projects/demo/src/modules/components/input-time/examples/7/index.html, projects/demo/src/modules/components/input-time/examples/7/index.ts, projects/demo/src/modules/components/input-time/index.html, projects/kit/tokens/date-inputs-value-transformers.ts, projects/legacy/components/input-time/input-time.component.ts, projects/legacy/components/input-time/test/input-time.component.spec.ts
=> feat(legacy): create `TUI_TIME_VALUE_TRANSFORMER` for `tui-input-time` component

.github/workflows/delete-preview.yml, .github/workflows/deploy-preview.yml
=> chore: switch preview account, delete channel on PR close

projects/demo/src/modules/components/notification/examples/2/index.ts, projects/demo/used-icons.ts
=> chore: icon update

projects/core/components/dialog/dialog.component.ts, projects/core/components/dialog/dialog.template.html, projects/demo/src/modules/components/dialog/examples/8/index.ts, projects/demo/src/modules/components/dialog/index.html
Revert:
* https://github.com/taiga-family/taiga-ui/pull/8205
Relates:
* https://stackblitz.com/edit/angular-uir9k2?file=src%2Fapp%2Fapp.component.ts
=> Revert "fix(core): `Dialog` should hide close icon if `closeable` equals to `Observable<false>` (#8205)"

projects/kit/components/stepper/step.style.less
=> chore(kit): `Stepper` vertical align set to stretch

.github/workflows/delete-preview.yml
=> chore: fix delete-preview workflow

projects/demo/src/modules/components/input-time/index.ts, projects/legacy/components/input-time/input-time.component.ts
Close https://github.com/taiga-family/taiga-ui/issues/8198
=> fix(legacy): correct present of control value from items list for input-time

projects/cdk/services/index.ts, projects/cdk/services/theme-color.service.ts, projects/demo/src/modules/components/dialog/examples/11/index.html, projects/demo/src/modules/components/dialog/examples/11/index.ts, projects/demo/src/modules/components/dialog/index.html
=> feat(cdk): add `TuiThemeColorService`

projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
=> chore: fix pseudo- migration

projects/demo/src/modules/components/notification/examples/2/index.ts
=> chore: small change

projects/cdk/schematics/ng-update/v4/index.ts, projects/cdk/schematics/ng-update/v4/steps/index.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-number-format-settings.ts, projects/cdk/schematics/ng-update/v4/tests/migrate-number-format-settings.spec.ts
=> chore(schematics): migration for `TuiNumberFormatSettings`

projects/cdk/schematics/ng-update/v4/steps/migrate-alert-service.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-alert-service.spec.ts
=> chore(schematics): migration for `TuiAlertOptions`

projects/cdk/schematics/ng-update/v4/index.ts, projects/cdk/schematics/ng-update/v4/steps/index.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-month-context.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-month-context.spec.ts
=> chore(schematics): migration for `TuiMonthContext`

projects/cdk/schematics/ng-update/interfaces/html-comment.ts, projects/cdk/schematics/ng-update/utils/templates/template-comments.ts, projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-number-format-settings.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
Relates:
* https://github.com/taiga-family/taiga-ui/issues/8335
=> chore(schematics): add migration comment for `TuiFormatNumberPipe`

projects/cdk/schematics/ng-update/v4/steps/migrate-root.ts, projects/cdk/schematics/ng-update/v4/tests/replace-modules-with-providers.spec.ts
=> chore: fix root module migration

projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-links.spec.ts
=> chore: fix link icon migration

.github/workflows/deploy-gh-pages.yml, projects/demo/src/modules/app/version-manager/versions.constants.ts
=> chore: switch deploy branches

projects/demo/src/modules/app/pages.ts
https://taiga-ui.dev/components/input-color
=> chore(demo): remove `ColorPicker` item from sidebar navigation of documentation

projects/cdk/date-time/time.ts
Closes # https://github.com/taiga-family/taiga-ui/issues/8372
=> fix(cdk): redundant assert log if hours are greater than 23

projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/index.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-filter-pipe.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-textfield-controller.spec.ts, projects/core/components/textfield/textfield.template.html
=> chore: `filterByInputWith` add missing migration

projects/kit/components/data-list-wrapper/data-list-group-wrapper.component.ts, projects/kit/components/data-list-wrapper/data-list-wrapper.component.ts, projects/kit/components/data-list-wrapper/data-list-wrapper.template.html
=> fix(kit): `TuiDataListGroupWrapperComponent` is not assignable to the same property in base type

projects/core/components/root/root.style.less
=> fix(core): `Root` fix background

projects/addon-doc/components/demo/index.html, projects/core/directives/group/group.directive.ts, projects/core/directives/group/group.options.ts, projects/core/directives/group/group.style.less, projects/core/styles/components/group.less, projects/demo/src/modules/components/group/examples/1/index.html, projects/demo/src/modules/components/group/examples/2/index.html, projects/demo/src/modules/components/group/examples/import/template.md, projects/demo/src/modules/components/group/index.html, projects/demo/src/modules/components/group/index.ts, projects/demo/src/modules/components/items-with-more/examples/2/index.html, projects/demo/src/modules/directives/dropdown-open/examples/2/index.html, projects/kit/components/files/files/files.component.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/legacy/components/color-selector/color-edit/color-edit.module.ts, projects/legacy/components/color-selector/color-edit/color-edit.template.html, projects/legacy/components/input-phone-international/input-phone-international.component.ts, projects/legacy/components/input-phone-international/input-phone-international.template.html
=> chore(core): `Group` move to published styles

CHANGELOG.md
=> chore: add v4.0.0 changelog

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/update-packages.ts
=> chore: fix migration issues

projects/cdk/schematics/ng-update/v4/steps/templates/migrate-blocked.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
=> chore: fix `ngFor` migration for blocked and labeled

projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
=> chore: fix appearance migration

projects/kit/components/calendar-range/calendar-range.component.ts
=> fix(kit): fix calendar range does not update checkbox position

projects/core/styles/theme/wrapper/icon.less, projects/kit/components/input-date-multi/input-date-multi.template.html, projects/kit/components/input-date-range/input-date-range.template.html, projects/kit/components/input-date-time/input-date-time.template.html, projects/kit/components/input-date/input-date.template.html
Closes #8389
Icon on hover:
**As Is:**
**To Be:**
=> fix(kit): icon hover on readonly

projects/core/components/button/button.style.less, projects/demo/src/modules/components/button/examples/1/index.less
Close https://github.com/taiga-family/taiga-ui/issues/8479
=> fix(core): ignore pointer events for disabled button

projects/cdk/schematics/ng-update/v4/steps/templates/migrate-avatar.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts
=> chore: fix auto-color pipe migration

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
=> chore: add `TuiItemDirective` migration

projects/demo/src/modules/components/pdf-viewer/index.html
Close https://github.com/taiga-family/taiga-ui/issues/8182
=> chore: built-in pdf viewer

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/core/directives/group/group.directive.ts, projects/core/styles/components/group.less
=> fix(core): `Group` fix edge overlay

projects/addon-doc/tokens/url-state-handler.ts, projects/demo/src/modules/app/app.config.ts
Relates:
* https://github.com/taiga-family/taiga-ui/issues/8466
=> chore(demo): `DocDemo` generates invalid urls during attempts to patch query params

projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-avatar.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-number-precision.ts, projects/cdk/schematics/ng-update/v4/steps/utils/normalize-attr-value.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-number-precision.spec.ts
TuiStringifiableItem -> legacy
[pseudoInvalid]="condition" -> [attr.data-mode]="condition ? 'invalid' : null"
[decimal]="decimal()" => [tuiNumberFormat]={decimalMode: decimal()}
=> chore: fix some migration issues

projects/cdk/schematics/tsconfig.schematics.json, projects/demo/src/modules/components/combo-box/index.ts, tsconfig.json
Part of https://github.com/taiga-family/taiga-ui/pull/8330
=> ci: add `verbatimModuleSyntax`

projects/cdk/directives/media/media.directive.ts, projects/cdk/directives/resizer/resizer.directive.ts, projects/kit/components/files/file/file.component.ts, projects/kit/components/files/input-files/input-files-validator.directive.ts, projects/kit/components/tiles/tiles.component.ts
Part of https://github.com/taiga-family/taiga-ui/issues/8346
=> refactor: drop decorators

projects/demo/src/modules/components/table/examples/5/index.html
=> chore(demo): use public property of virtual scroll viewport

projects/addon-doc/components/page/page.style.less, projects/demo/src/modules/app/logo/logo.style.less
Closes #8441
Visit https://taiga-ui.dev/ssr
SSR returns:
Visit https://taiga-ui.dev/ssr
SSR returns:
=> chore(addon-doc): improve ssr hydration for `TuiDocPage`

projects/addon-doc/components/code/index.less, projects/addon-doc/components/demo/index.less, projects/addon-doc/components/documentation/documentation.style.less, projects/addon-doc/components/example/example.style.less
Relates:
* https://github.com/taiga-family/taiga-ui/pull/8557
=> refactor(addon-doc): use only CSS media queries for breakpoints

projects/legacy/components/input-number/input-number.component.ts
Closes [#8528](https://github.com/taiga-family/taiga-ui/issues/8528)
=> fix(legacy): prevent add/remove suffixes while InputNumber is readonly

projects/cdk/schematics/ng-update/v4/index.ts, projects/cdk/schematics/ng-update/v4/steps/index.ts, projects/cdk/schematics/ng-update/v4/steps/remove-duplicates.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
=> chore: remove duplicates after migration

projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-money.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-money.spec.ts, projects/cdk/schematics/utils/add-import-to-closest-module.ts
=> chore: fix money migration issue, fix migration for inline-templates

projects/core/components/scrollbar/scroll-controls.template.html
https://github.com/user-attachments/assets/f9c08a31-4d0e-401d-8daa-8f0b0db69641
https://github.com/user-attachments/assets/b1164ffc-65d2-4192-8e67-5590423e8484
@waterplea in iframe it also works as it should
=> fix(core): user selection on safari

projects/demo-cypress/src/tests/input-phone-international.cy.ts, projects/demo/src/modules/components/input-phone-international/index.ts, projects/kit/components/input-phone-international/input-phone-international.options.ts
=> fix(kit): improve tree-shakeability of `InputPhoneInternational`

projects/legacy/components/input-password/input-password.component.ts, projects/legacy/components/input-password/input-password.template.html
=> fix(legacy): display view/hide password button with `readOnly` property

projects/kit/components/input-password/input-password.component.ts, projects/kit/components/input-password/input-password.template.html
=> fix(kit): display view/hide password button with `readOnly` property

projects/demo-cypress/src/tests/input-phone-international.cy.ts
=> chore: fix component-test

projects/core/styles/components/textfield.less, projects/kit/components/checkbox/checkbox.options.ts, projects/kit/components/elastic-container/elastic-container.directive.ts, projects/kit/components/input-phone-international/input-phone-international.style.less, projects/kit/components/items-with-more/items-with-more.service.ts, projects/kit/components/progress/progress-bar/progress-color-segments.directive.ts, projects/kit/components/segmented/segmented.component.ts, projects/kit/components/stepper/stepper.component.ts, projects/kit/components/tabs/tabs-horizontal.directive.ts, projects/kit/directives/fade/fade.directive.ts, projects/kit/directives/fluid-typography/fluid-typography.directive.ts, projects/kit/directives/highlight/highlight.directive.ts, projects/kit/directives/sensitive/sensitive.directive.ts, projects/layout/components/app-bar/app-bar.component.ts
=> fix(kit): `InputPhoneInternational` fix size for `border-box`

projects/demo/src/modules/app/landing/index.ts
=> chore(demo): landing page should be use light palette

projects/legacy/components/tag/tag.style.less, projects/legacy/components/textarea/textarea.style.less
Close https://github.com/taiga-family/taiga-ui/issues/8616
=> fix(legacy): invalid css variable

projects/addon-commerce/components/input-card/input-card.directive.ts, projects/core/tokens/icon-resolver.ts, projects/kit/components/checkbox/checkbox.component.ts, projects/kit/components/switch/switch.component.ts
=> chore: fix resolver name

projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.service.ts, projects/demo/src/modules/components/pull-to-refresh/examples/3/index.html, projects/demo/src/modules/components/pull-to-refresh/examples/3/index.less, projects/demo/src/modules/components/pull-to-refresh/examples/3/index.ts, projects/demo/src/modules/components/pull-to-refresh/index.html
=> fix(addon-mobile): `PullToRefresh` fix scroll ref

projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badge.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badge.spec.ts
Close https://github.com/taiga-family/taiga-ui/issues/8670
=> chore(schematics): close tui-badge

projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-addon-doc.spec.ts, projects/cdk/schematics/utils/add-unique-import.ts
Close https://github.com/taiga-family/taiga-ui/issues/8670
=> chore(schematics): ignore import type

projects/demo/src/styles/styles.less
https://github.com/user-attachments/assets/014cc62e-330b-4faf-904d-25087cc9a1f4
https://github.com/user-attachments/assets/a4fb38fa-7324-41d4-bcd6-d5fca5e25cf0
=> chore(demo): ignore white background

projects/kit/directives/button-close/button-close.directive.ts, projects/kit/directives/button-close/button-close.options.ts, projects/kit/directives/button-close/index.ts
Close https://github.com/taiga-family/taiga-ui/issues/8555
=> fix(kit): correct icon for `tuiButtonClose`

projects/core/components/icon/icon.component.ts, projects/core/styles/components/icon.less, projects/demo/src/modules/components/button-group/examples/1/index.html, projects/demo/src/modules/components/button-group/examples/1/index.less, projects/demo/src/modules/components/button-group/examples/1/index.ts, projects/kit/directives/icon-badge/icon-badge.directive.ts, projects/kit/directives/icon-badge/icon-badge.style.less, projects/kit/directives/icon-badge/index.ts, projects/kit/directives/icon-badge/ng-package.json, projects/kit/directives/index.ts
=> feat(kit): `IconBadge` add new directive

projects/core/tokens/icon-resolver.ts, projects/demo/src/modules/components/icon/examples/5/index.html, projects/demo/src/modules/components/icon/examples/5/index.less, projects/demo/src/modules/components/icon/examples/5/index.ts, projects/demo/src/modules/components/icon/index.html, projects/demo/src/modules/components/icon/index.ts
=> chore: add resolver example

projects/cdk/schematics/ng-update/v4/migrate-icons/index.ts, projects/cdk/schematics/ng-update/v4/migrate-icons/rename-proprietary-icons.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-proprietary.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-root.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-icons.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-proprietary.spec.ts
=> chore: check proprietary using two packages

projects/cdk/schematics/ng-update/v4/steps/remove-duplicates.ts, projects/cdk/schematics/ng-update/v4/tests/replace-modules-with-providers.spec.ts
=> chore: fix removing duplicates after migration

projects/cdk/schematics/ng-add/index.ts, projects/cdk/schematics/ng-update/steps/replace-package-name.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-proprietary.ts, projects/cdk/schematics/ng-update/v4/steps/update-packages.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-resolve-package-type.spec.ts
Close https://github.com/taiga-family/taiga-ui/issues/8670
=> chore(schematics): add new dependencies to the correct section

projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts
=> chore: remove outdated test

projects/cdk/schematics/ng-update/v4/migrate-addon-doc/index.ts
=> fix(cdk): `schematics` fix bad import

projects/demo/src/modules/info/migration-guide/index.html, projects/demo/src/modules/info/migration-guide/index.less
=> chore(demo): add notes about unused imports to `Troubleshooting` section of `Migration Guide`

projects/cdk/schematics/ng-update/v3-35/constants/icons.ts
Part of https://github.com/taiga-family/taiga-ui/issues/8614
=> chore(schematics): invalid proprietary icons

projects/core/styles/components/icon.less
=> fix(core): `Icons` fix mask shorthand

projects/addon-doc/components/example/example.component.ts, projects/addon-doc/components/example/example.style.less, projects/addon-doc/components/example/example.template.html
My idea from google project https://google.github.io/zx/getting-started
=> feat(addon-doc): improve ui for link to sample

projects/addon-commerce/components/input-card-group/input-card-group.style.less, projects/addon-commerce/components/input-card-group/input-card-group.template.html, projects/addon-commerce/components/input-expire/input-expire.directive.ts, projects/core/styles/components/textfield.less, projects/core/styles/theme/appearance/textfield.less, projects/demo/src/modules/components/input-card/examples/1/index.html, projects/kit/components/radio-list/radio-list.component.ts
=> fix(addon-commerce): `InputCard` fix autofill

projects/cdk/schematics/ng-update/v4/steps/migrate-root.ts, projects/cdk/schematics/ng-update/v4/tests/replace-modules-with-providers.spec.ts
=> chore: add root providers in main module

projects/cdk/schematics/ng-update/v4/steps/templates/migrate-avatar.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-avatar.spec.ts
=> chore: do not migrate experimental avatar size

projects/demo/src/modules/components/input-tag/index.html, projects/demo/src/modules/components/input-tag/index.ts, projects/demo/src/modules/components/multi-select/index.html, projects/demo/src/modules/components/multi-select/index.ts, projects/legacy/components/input-tag/input-tag.component.ts, projects/legacy/components/input-tag/input-tag.options.ts, projects/legacy/components/input-tag/input-tag.template.html, projects/legacy/components/multi-select/multi-select.component.ts, projects/legacy/components/multi-select/multi-select.template.html
Close [#8729  ](https://github.com/taiga-family/taiga-ui/issues/8729)
=> fix(legacy): restore `autoColor` for `InputTag` and `MultiSelect`

projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts, projects/kit/components/calendar-range/calendar-range.component.ts
=> fix(kit): `CalendarRange` shows end of range

projects/legacy/components/primitive-textfield/primitive-textfield.component.ts, projects/legacy/components/primitive-textfield/primitive-textfield.style.less
=> fix(legacy): trigger transform placeholder when using autofill

projects/cdk/constants/used-icons.ts, projects/core/components/icon/icon.component.ts, projects/core/directives/dropdown/dropdown.bindings.ts, projects/demo/src/modules/components/navigation/examples/1/index.html, projects/demo/src/modules/components/navigation/examples/1/index.ts, projects/demo/src/modules/components/navigation/index.less, projects/layout/components/navigation/aside-item.directive.ts, projects/layout/components/navigation/drawer.component.ts, projects/layout/components/navigation/drawer.style.less, projects/layout/components/navigation/hint-aside.directive.ts, projects/layout/components/navigation/index.ts, projects/layout/components/navigation/navigation.ts, projects/layout/tokens/common-icons.ts
=> feat(layout): `Navigation` add `Drawer`

projects/layout/components/navigation/aside.style.less
=> fix(layout): `Navigation` fix style specificity for `AsideItem`

projects/addon-commerce/components/thumbnail-card/thumbnail-card.template.html, projects/demo/src/modules/components/thumbnail-card/examples/4/index.html, projects/demo/src/modules/components/thumbnail-card/examples/4/index.less, projects/demo/src/modules/components/thumbnail-card/examples/4/index.ts, projects/demo/src/modules/components/thumbnail-card/index.ts
=> feat(addon-commerce): `ThumbnailCard` add `<img>` support

projects/cdk/schematics/constants/taiga-styles.ts, projects/cdk/schematics/ng-add/index.ts, projects/cdk/schematics/ng-add/schema.json, projects/cdk/schematics/ng-add/schema.ts, projects/cdk/schematics/ng-add/steps/add-taiga-styles.ts, projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts, projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts
=> chore: `ng-add` remove global styles

projects/cdk/schematics/ng-add/index.ts, projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts, projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts, projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts
=> chore: `ng-add` add NG_EVENT_PLUGINS to main module providers, add plugins package

projects/core/components/alert/alert.style.less, projects/core/directives/group/group.directive.ts, projects/core/styles/components/group.less
=> chore: fix some styles

projects/experimental/directives/cell/cell.styles.less
=> feat(experimental): `Cell` add border-radius

projects/layout/components/cell/cell.styles.less
=> feat(layout): `Cell` add border-radius

projects/cdk/directives/native-validator/native-validator.directive.ts, projects/core/components/textfield/textfield.component.ts
=> fix(cdk): `NativeValidator` fix touched state

projects/demo/src/modules/experimental/thumbnail-card/examples/4/index.html, projects/demo/src/modules/experimental/thumbnail-card/examples/4/index.less, projects/demo/src/modules/experimental/thumbnail-card/examples/4/index.ts, projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.component.ts, projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.module.ts, projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.template.html, projects/experimental/components/thumbnail-card/thumbnail-card.template.html
=> feat(experimental): `ThumbnailCard` add external `<img>` support

projects/demo/src/modules/components/thumbnail-card/examples/4/index.html, projects/demo/src/modules/components/thumbnail-card/examples/4/index.ts
=> chore(demo): update url and remove unused import

projects/kit/components/calendar-range/calendar-range.component.ts, projects/kit/components/calendar-range/calendar-range.template.html
Close #8911 
Revert changes https://github.com/taiga-family/taiga-ui/pull/8784
=> fix(kit): `CalendarRange` revert computedMonth changes

projects/demo/src/modules/components/input-files/examples/1/index.ts, projects/demo/src/modules/components/input-files/examples/5/index.html, projects/demo/src/modules/components/input-files/index.html, projects/kit/components/files/input-files/input-files.component.ts, projects/kit/components/files/input-files/input-files.directive.ts, projects/kit/components/files/input-files/input-files.style.less
Close #8840
Close #8841
Close #8842
=> fix(kit): `InputFiles` fix validity and drag states

projects/demo/src/modules/components/card-large/examples/12/index.html, projects/demo/src/modules/components/card-large/index.ts
=> chore(demo): `Card` fix "Paddings and radii" demo

projects/demo/src/modules/app/home/home.template.html
=> chore(demo): add note to ng-add installation

projects/kit/components/input-time/input-time.component.ts, projects/kit/components/input-time/test/input-time.component.spec.ts
Close https://github.com/taiga-family/taiga-ui/issues/8878
=> fix(kit): `InputTime` fix selection of the nearest value from items

package.json, projects/demo/src/modules/components/input-tag/index.ts, projects/legacy/utils/iso-to-country-code.ts
=> refactor: support `single-char-in-character-classes`

package.json, projects/kit/utils/toggle-day.ts, scripts/shared/is-tui-package-name.ts
=> refactor: support `default-param-last`

projects/addon-mobile/components/swipe-action/swipe-actions.component.ts, projects/core/components/textfield/textfield.component.ts, projects/kit/components/preview/preview.component.ts
On motives https://github.com/taiga-family/taiga-ui/issues/8907
=> chore: `ResizeObserver` CD trigger

package.json, projects/addon-charts/components/line-days-chart/line-days-chart.component.ts, projects/core/directives/dropdown/dropdown.directive.ts, projects/legacy/components/input-date-range/input-date-range.component.ts
=> refactor: support `no-import-type-side-effects`

package.json, projects/addon-doc/utils/type-reference-parser.ts, projects/cdk/schematics/ng-add/index.ts, projects/cdk/schematics/ng-update/v4/migrate-icons/rename-proprietary-icons.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-month-context.ts, projects/cdk/services/test/id.service.spec.ts, projects/cdk/utils/color/parse-gradient.ts, projects/cdk/utils/color/rgba-to-hex.ts, projects/demo/src/modules/app/classes/ts-file.parser.ts, projects/demo/src/modules/components/combo-box/index.ts, projects/demo/src/modules/components/multi-select/index.ts, scripts/combine-playwright-failed-screenshots.ts, scripts/generate-demo-routes-file.ts
=> refactor: support `prefer-regexp-exec`

package.json, projects/legacy/components/input-number/input-number.component.ts
=> refactor: support `sonar-max-params`

projects/demo/src/modules/components/combo-box/examples/5/index.html, projects/demo/src/modules/components/multi-select/examples/7/index.html, projects/demo/src/modules/components/pull-to-refresh/examples/3/index.html, projects/demo/src/modules/components/scrollbar/examples/6/index.html, projects/demo/src/modules/components/select/examples/8/index.html, projects/demo/src/modules/components/table/examples/5/index.html
=> chore(demo): fix problem with cdk rendering

projects/cdk/schematics/ng-update/v4/index.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/modules-to-remove.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-providers-from.ts, projects/cdk/schematics/ng-update/v4/tests/replace-modules-with-providers.spec.ts
=> chore(schematics): remove modules from `importProvidersFrom`

package.json, projects/cdk/utils/browser/is-safari.ts, projects/cdk/utils/color/hex-to-rgba.ts, projects/legacy/tokens/is-firefox.ts
=> refactor: support `no-typeof-undefined`

projects/demo/src/modules/components/table-filters/examples/2/index.html, projects/demo/src/modules/components/table-filters/examples/2/index.less, projects/demo/src/modules/components/table-filters/examples/2/index.ts, projects/demo/src/modules/components/table-filters/index.html
An example for FormArray was added to TableFilters(AddonTable)
Close # [3925](https://github.com/taiga-family/taiga-ui/issues/3925)
=> chore(demo): `table-filters` add example with form array

projects/kit/directives/skeleton/skeleton.style.less
=> fix(kit): block user selection in skeleton

package.json, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/components/tabs/examples/8/index.html, projects/demo/src/modules/components/tabs/examples/8/index.ts, projects/demo/src/modules/components/tabs/index.html, projects/demo/src/modules/components/tabs/routes.ts
=> chore: add example with routing and tuiTab

projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.style.less, projects/addon-mobile/components/mobile-calendar-sheet/mobile-calendar-sheet.template.html, projects/addon-mobile/components/mobile-calendar/mobile-calendar.style.less, projects/core/components/calendar/calendar-sheet.component.ts, projects/core/components/calendar/calendar-sheet.style.less, projects/core/components/calendar/calendar-sheet.template.html, projects/core/components/calendar/calendar-year.component.ts, projects/core/components/calendar/calendar-year.style.less, projects/core/components/calendar/calendar-year.template.html, projects/core/components/calendar/test/calendar-sheet.component.spec.ts, projects/core/components/calendar/test/calendar-year.component.spec.ts, projects/core/components/root/root.component.ts, projects/core/styles/mixins/date-picker.less, projects/core/styles/mixins/picker.less, projects/core/styles/mixins/picker.scss, projects/core/styles/taiga-ui-local.less, projects/core/styles/theme/wrapper.less, projects/demo-playwright/tests/addon-mobile/mobile-calendar/input-date.spec.ts, projects/kit/components/calendar-month/calendar-month.component.ts, projects/kit/components/calendar-month/calendar-month.style.less, projects/kit/components/calendar-month/calendar-month.template.html, projects/kit/components/calendar-month/test/calendar-month.component.spec.ts, projects/kit/components/segmented/segmented.style.less, projects/kit/directives/button-group/button-group.style.less, projects/kit/directives/password/password.directive.ts, projects/kit/styles/components/chip.less, projects/testing/core/calendar-sheet.harness.ts, projects/testing/core/calendar-year.harness.ts
=> fix(core): `Calendar` fix visual gaps in range

projects/core/components/root/root.component.ts, projects/demo-cypress/src/tests/mobile-calendar.cy.ts
=> chore: failed test

projects/cdk/schematics/ng-update/v4/index.ts, projects/cdk/schematics/ng-update/v4/steps/update-packages.ts
=> chore: catch migration error

projects/demo/src/modules/components/button/index.html, projects/demo/src/modules/components/button/index.ts
=> chore(demo): `Button` migrate to new approach

projects/addon-mobile/styles/android/app-bar.less, projects/addon-mobile/styles/ios/app-bar.less, projects/addon-mobile/styles/taiga-ui-mobile.less
=> fix(addon-mobile): correct height for `tui-app-bar` on ios/android

package.json, projects/addon-doc/components/page/page-tab.directive.ts, projects/addon-mobile/directives/ripple/ripple.directive.ts, projects/cdk/classes/control.ts, projects/core/pipes/flag/flag.pipe.ts, projects/demo/src/modules/components/icons-group/icons-group.directive.ts, projects/kit/components/badged-content/badged-content.directive.ts, projects/kit/components/routable-dialog/routable-dialog.component.ts, projects/kit/directives/copy/copy.directive.ts, projects/layout/components/app-bar/app-bar.directive.ts, projects/layout/components/block-status/block-status.directive.ts, projects/legacy/classes/control.ts, projects/legacy/directives/wrapper/wrapper.directive.ts
=> refactor: support `no-redundant-type-constituents`

projects/cdk/types/index.ts, projects/cdk/types/loose-union.ts, projects/core/directives/appearance/appearance.options.ts, projects/core/pipes/flag/flag.pipe.ts, projects/i18n/types/language-names.ts, projects/kit/components/badged-content/badged-content.directive.ts, projects/layout/components/app-bar/app-bar.directive.ts, projects/layout/components/block-status/block-status.directive.ts, projects/legacy/directives/wrapper/wrapper.directive.ts
https://x.com/mattpocockuk/status/1821926395380986219
=> feat(cdk): add `TuiLooseUnion`

projects/core/styles/components/textfield.less, projects/demo/src/modules/components/thumbnail-card/examples/5/index.html, projects/demo/src/modules/components/thumbnail-card/examples/5/index.less, projects/demo/src/modules/components/thumbnail-card/examples/5/index.ts, projects/demo/src/modules/components/thumbnail-card/index.ts
Close https://github.com/taiga-family/taiga-ui/issues/9066
=> fix(core): do not override nested tui-icon styles

projects/demo/src/modules/components/button/examples/1/index.ts, projects/demo/src/modules/components/button/examples/2/index.ts
=> chore(demo): `Button` remove unused imports

projects/addon-table/directives/table-filters/table-filters.pipe.ts
=> fix(table): table filters pipe types

projects/demo/src/modules/experimental/segmented/examples/4/index.ts, projects/experimental/components/segmented/segmented.component.ts, projects/experimental/components/segmented/segmented.directive.ts
=> fix(experimental): `Segmented` fix initial radio value

projects/addon-doc/components/navigation/navigation.component.ts, projects/addon-doc/components/navigation/navigation.style.less, projects/addon-doc/components/navigation/navigation.template.html, projects/core/components/data-list/data-list.component.ts, projects/core/components/textfield/textfield-dropdown.directive.ts, projects/core/directives/dropdown/dropdown-open.directive.ts
=> refactor(addon-doc): search input

projects/core/styles/mixins/textfield.less
=> fix(core): fix scroll jumping on readonly input focusing in safari

projects/addon-commerce/components/input-card-group/input-card-group.style.less, projects/kit/components/files/file/file.options.ts
=> fix(addon-commerce): `InputCardGroup` fix for older Safari

projects/demo/src/modules/components/push/examples/1/index.less
=> chore(demo): correct gap between push in basic example

projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts
=> chore: migrate `tuiRow`

projects/addon-commerce/components/input-card/index.ts, projects/addon-commerce/components/input-card/input-card.component.ts, projects/addon-commerce/components/input-card/input-card.style.less, projects/addon-doc/components/navigation/navigation.component.ts, projects/core/components/textfield/textfield.component.ts, projects/core/components/textfield/textfield.template.html, projects/core/styles/components/icons.less, projects/core/styles/components/textfield.less, projects/kit/directives/chevron/chevron.style.less, projects/kit/directives/copy/copy.directive.ts, projects/kit/directives/password/password.directive.ts, projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts
=> chore: fix `InputCard` after borders were removed

projects/demo/src/modules/components/calendar-range/index.ts, projects/demo/src/modules/components/input-date-range/index.ts
=> chore(demo): `CalendarRange`, `InputDateRange` add `API` examples variants

projects/addon-commerce/components/input-card-group/input-card-group.component.ts, projects/addon-commerce/components/input-card-group/input-card-group.style.less, projects/core/styles/components/icons.less, projects/core/styles/components/link.less
=> chore: rollback `InputCardGroup` fix and implement a simpler one

projects/demo-playwright/tests/kit/calendar-range/calendar-range.spec.ts, projects/demo-playwright/tests/kit/input-date-range/input-date-range.spec.ts, projects/kit/components/calendar-range/calendar-range.component.ts, projects/kit/components/calendar-range/test/calendar-range.component.spec.ts
=> fix(kit): `CalendarRange` shows last available month when max and items set

projects/demo-playwright/tests/kit/multi-select/multi-select.spec.ts, projects/demo/src/modules/components/multi-select/examples/13/index.html, projects/demo/src/modules/components/multi-select/examples/13/index.less, projects/demo/src/modules/components/multi-select/examples/13/index.ts, projects/demo/src/modules/components/multi-select/index.html, projects/demo/src/modules/components/multi-select/index.ts, projects/demo/src/utils/example.pipe.ts, projects/kit/components/data-list-wrapper/data-list-wrapper.style.less, projects/legacy/components/multi-select-option/multi-select-option.style.less
=> fix(legacy): `MultiSelect` fix for long items overflowing

projects/kit/directives/password/index.ts
=> fix(kit): export password options

projects/core/directives/dropdown/dropdown-context.directive.ts
=> fix(core): `DropdownContext` fix for Shadow DOM

package-lock.json, projects/core/package.json
Close https://github.com/taiga-family/taiga-ui/issues/9172
=> fix(core): invalid peer dependency

projects/kit/package.json
=> fix(kit): fix tslib version

projects/demo/src/styles/styles.less
=> chore(demo): reset margin for body

projects/experimental/components/chip/chip.style.less
=> fix(kit): `Chip` size

projects/core/directives/dropdown/dropdown.component.ts, projects/core/directives/hint/hint.component.ts, projects/demo-playwright/tests/core/dropdown/dropdown.spec.ts
=> fix(core): close dropdown when dropdown host is hidden via css

projects/demo/src/modules/app/app.style.less, projects/demo/src/modules/app/app.template.html, projects/demo/src/modules/app/version-manager/version-manager.component.ts, projects/demo/src/modules/app/version-manager/version-manager.template.html, projects/demo/src/modules/app/version-manager/versions.constants.ts
=> chore(demo): move version manager to header

projects/addon-commerce/components/input-card-group/input-card-group.component.ts, projects/cdk/classes/control.ts, projects/core/components/textfield/textfield.directive.ts, projects/core/styles/components/textfield.less, projects/core/styles/theme/appearance/textfield.less
=> fix(addon-commerce): `InputCardGroup` fix Safari autofill

projects/kit/components/tabs/tab.directive.ts, projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts, projects/legacy/components/input/input.module.ts
fix(legacy): `MultiSelect` fix `filterByInput` pipe
fix(kit): `TabsWithMore` fix clicks in dropdown
Close #9212
Close #9104
Close #9211
=> fix(legacy): `Input` fix [(tuiDropdownOpen)]

projects/demo/src/modules/app/app.component.ts, projects/demo/src/modules/app/version-manager/version-manager.providers.ts, projects/demo/src/modules/app/version-manager/versions.constants.ts
=> chore(demo): correct version list

projects/demo/src/modules/app/app.config.ts, projects/demo/src/modules/app/app.const.ts
=> chore: proprietary compilation

projects/addon-doc/components/api/api-item.component.ts, projects/addon-doc/components/api/api-item.template.html, projects/demo-playwright/tests/core/button/button.spec.ts
=> chore(demo): `DocAPIItem` value reflect in URL

projects/core/directives/appearance/appearance.options.ts, projects/demo/src/components/appearance/index.ts, projects/demo/src/modules/directives/appearance/examples/4/index.ts
=> chore(demo): `Appearance` add `icon`

projects/cdk/schematics/ng-update/v4/steps/constants/attr-to-directive-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button.spec.ts
=> chore: add secondary-destructive and improve pseudoFocus migration

projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.component.ts, projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.template.html, projects/kit/components/calendar-range/calculate-disabled-item-handler.ts, projects/kit/components/calendar-range/calendar-range.component.ts, projects/kit/components/calendar-range/index.ts
=> fix(addon-mobile): fix minLength and maxLength properties for range in mobile calendar

projects/demo/src/modules/components/calendar/examples/5/index.less
=> chore(demo): add `::before` on `data-type` attribute

projects/kit/styles/components/like.less
=> chore: fix like for stackblitz

projects/core/directives/dropdown/dropdown-context.directive.ts
=> fix(core): fix open DropdownContext after single touch on iOS

projects/addon-doc/components/copy/index.ts
=> chore(demo): invalid initial value

projects/core/animations/animations.ts
=> feat(core): add animation params

projects/demo/src/modules/directives/textfield-controller/index.html
=> chore(demo): `TextfieldController` mark as legacy

.cspell.json, projects/demo/project.json, scripts/generate-sitemap.ts
=> chore(demo): add auto generating sitemap xml

projects/core/directives/hint/hint-unstyled.component.ts, projects/core/directives/hint/hint.component.ts, projects/core/directives/hint/hint.directive.ts, projects/kit/components/line-clamp/line-clamp-box.component.ts
=> fix(core): `Hint` fix change detection when changing content programmatically

projects/cdk/schematics/ng-update/v4/steps/update-packages.ts
=> chore(cdk): fix dompurify version

projects/legacy/components/input-tag/input-tag.component.ts
=> fix(legacy): `InputTag` fix pasting multiple invalid tags

projects/demo-cypress/cypress.config.ts, projects/demo-cypress/project.json
=> chore(demo-cypress): improve Cypress snapshots quality

projects/addon-table/components/table/td/td.component.ts, projects/legacy/classes/control.ts
=> fix(addon-table): drop legacy package dependency

.husky/commit-msg, .husky/pre-commit
Fixes https://github.com/taiga-family/taiga-ui/issues/9372
https://commitlint.js.org/guides/local-setup.html
=> chore: commitlint

package-lock.json, projects/addon-doc/package.json
Fixes for https://github.com/taiga-family/ng-morph/pull/948
=> fix(addon-doc): add `legacy` package as peer dependency

projects/addon-doc/components/demo/index.ts
=> fix(addon-doc): `DocDemo` remove `timer` and `tuiZonefreeScheduler`

projects/legacy/components/select/select.template.html
=> fix(legacy): `Select` fix hydration

projects/core/pipes/fallback-src/fallback-src.pipe.ts
Fixes #
https://stackblitz.com/edit/angular-od933e?file=src%2Fapp%2Fapp.template.html
=> fix(core): support provide empty avatar src

projects/demo/src/modules/components/table/examples/4/index.html, projects/demo/src/modules/components/table/examples/4/index.ts
Fixes https://github.com/taiga-family/taiga-ui/issues/9468
=> chore(demo): sort fix for `page` and `minAge`

projects/cdk/utils/dom/element-checks.ts
=> refactor: stricter checks in `tuiIsHTMLElement`

.github/CODEOWNERS
=> ci: add code owner alias

projects/addon-doc/components/api/api-item.style.less, projects/demo/src/modules/components/input-phone-international/index.html, projects/demo/src/modules/components/input-phone-international/index.ts
=> chore(demo): `InputPhoneInternational` update `API` page

package-lock.json, package.json, projects/demo-playwright/package.json
Fixes problem with playwright on ubuntu 24.04
https://github.com/microsoft/playwright/issues/30368
=> chore(demo-playwright): update `@playwright/test` to `1.48.0`

package.json
=> chore(demo): add alias for start demo with ssl to `package.json`

projects/demo/src/modules/components/chip/examples/3/index.html
Fixes #9501 
https://github.com/user-attachments/assets/3bea2d39-d287-45ae-b163-3daddfebb507
=> fix(demo): `Chip` has interactive text label

projects/legacy/components/primitive-textfield/primitive-textfield.style.less, projects/legacy/components/primitive-textfield/primitive-textfield.template.html
Fixes # 
https://stackblitz.com/edit/taiga-ui-multi-select-arrow-animate-uqfk4n?file=src%2Fapp%2Fchild%2Fchild.component.ts
=> fix(legacy): `InputNumber` fix hydration

.cspell.json, projects/demo/src/modules/app/pages.ts
=> chore(demo): add components metadata

projects/demo/src/modules/app/landing/index.html, projects/demo/src/modules/app/landing/index.less
=> chore(demo): add angular press kit logo

projects/cdk/classes/control.ts, projects/demo/src/modules/components/radio/examples/3/index.html, projects/demo/src/modules/components/radio/examples/3/index.ts
=> fix(cdk): `Control` fix initial status

projects/core/components/dialog/dialog.factory.ts, projects/core/components/dialog/index.ts, projects/core/components/dialog/test/dialog.factory.spec.ts, projects/demo/src/modules/components/dialog/examples/2/dialog-example/dialog-example.component.ts, projects/demo/src/modules/components/dialog/examples/2/index.ts, projects/demo/src/modules/components/dialog/examples/7/index.ts, projects/demo/src/modules/components/dialog/examples/9/index.ts, projects/demo/src/modules/components/dialog/examples/9/pay-modal/pay-modal.component.ts
=> feat(core): add dialog-factory

package-lock.json, projects/cdk/package.json, projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts
=> chore(demo): add deps for stackblitz

projects/demo/src/index.html
=> chore(demo): remove prefetch for non-existent image

projects/demo/src/modules/app/pages.ts
=> chore(demo): change spelling

projects/styles/markup/tui-space.less
=> chore(styles): `tui-space` increase specifity

.github/workflows/cleanup-resources.yml
=> chore: provide github token

projects/addon-doc/components/navigation/navigation.template.html, projects/addon-doc/tokens/i18n.ts, projects/demo/src/modules/app/app.config.ts
=> chore(demo): show default search if algolia is not available

projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less, projects/demo/src/modules/components/sheet-dialog/index.html, projects/demo/src/modules/components/sheet-dialog/index.ts, projects/kit/components/files/files.validators.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-phone-international/input-phone-international.style.less, projects/kit/components/input-phone-international/input-phone-international.template.html, projects/kit/components/rating/rating.options.ts, projects/kit/components/rating/rating.style.less, projects/kit/components/rating/rating.template.html
Fixes #8994
Fixes #9568
Fixes #9563
Fixes #9394
=> fix(kit): `InputPhoneInternational` fix dropdown issues

projects/demo/src/modules/components/navigation/index.less, projects/demo/src/styles/styles.less, projects/layout/components/navigation/drawer.component.ts, projects/layout/components/navigation/drawer.style.less, projects/layout/components/navigation/header.style.less
=> fix(layout): `Navigation` fix drawer positioning

.github/workflows/auto-merge.yml
=> chore: disable squash automerge in release branch

projects/demo/src/modules/app/app.component.ts, projects/demo/src/modules/app/app.template.html
=> chore(demo): hide search button if algolia is not available

projects/demo/src/modules/components/textfield/index.html
=> chore(demo): update description to improve search

projects/addon-mobile/components/mobile-calendar/mobile-calendar.component.ts, projects/cdk/date-time/date-time.ts, projects/cdk/date-time/days.const.ts, projects/core/components/calendar/calendar.component.ts, projects/demo-playwright/tests/legacy/input-date/input-date.spec.ts, projects/legacy/components/input-date/input-date.component.ts
=> feat(core): `Calendar` not switch to large date

projects/addon-mobile/directives/sidebar/sidebar.directive.ts, projects/core/components/root/root.component.ts, projects/core/components/root/root.style.less, projects/core/components/root/root.template.html, projects/core/directives/dropdown/dropdowns.component.ts, projects/core/services/index.ts, projects/core/services/popup.service.ts, projects/demo/src/modules/components/label/examples/1/index.html, projects/demo/src/modules/components/label/examples/1/index.ts, projects/demo/src/styles/styles.less, projects/kit/directives/tooltip/tooltip.style.less
=> feat(core): `Popup` add service for arbitrary portal items

projects/demo/src/modules/components/input-phone-international/examples/5/index.html, projects/demo/src/modules/components/input-phone-international/examples/5/index.ts, projects/demo/src/modules/components/input-phone-international/index.html, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/input-phone-international/input-phone-international.options.ts, projects/kit/components/input-phone-international/test/input-phone-international.component.spec.ts
Closes https://github.com/taiga-family/taiga-ui/issues/9518
=> feat(kit): `TuiInputPhoneInternational` has separator customization

projects/cdk/schematics/ng-update/v4/migrate-css-vars/palette.ts, projects/cdk/schematics/ng-update/v4/migrate-css-vars/rename-css-vars.ts, projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-number-precision.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-css-vars.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-number-precision.spec.ts
part of #8839 
add comment for `TUI_DIALOG_CLOSES_ON_BACK`
fix decimal="never" migration
fix comment for *night variables
=> chore(cdk): fix migration issues

projects/cdk/schematics/ng-update/v4/steps/templates/migrate-labeled.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-labeled.spec.ts
=> chore(cdk): fix labeled migration

projects/demo-playwright/tests/kit/input-files/input-files.spec.ts, projects/demo/src/modules/components/input-files/examples/3/index.html, projects/demo/src/modules/components/input-files/examples/4/index.html, projects/kit/components/files/files/files.styles.less
=> fix(kit): `Files` fix link styles

projects/demo/src/modules/components/block-status/examples/2/index.html, projects/demo/src/modules/components/block-status/examples/6/index.html, projects/demo/src/modules/components/block-status/examples/6/index.ts, projects/demo/src/modules/components/block-status/index.html, projects/demo/src/modules/components/block-status/index.ts, projects/layout/components/block-status/block-status.component.ts, projects/layout/components/block-status/block-status.style.less
=> feat(layout): `BlockStatus` add desktop "m" size

projects/kit/components/files/file/file.component.ts, projects/kit/components/files/file/file.template.html
=> feat(kit): `TuiFile` added tuiHintOverflow for file name

projects/kit/components/stepper/stepper.component.ts
=> fix(kit): `Stepper` fix flashing styles

projects/demo/src/modules/app/pages.ts
=> chore: extend meta for tui-db

projects/demo/src/modules/components/chip/examples/5/index.html, projects/demo/src/modules/components/chip/examples/5/index.less, projects/demo/src/modules/components/chip/examples/5/index.ts, projects/demo/src/modules/components/chip/index.html, projects/demo/src/modules/components/chip/index.ts
=> chore(demo): `Chip` add autocolor example, add api page

.github/workflows/e2e.yml
Part of https://github.com/taiga-family/taiga-ui/pull/9554/files
=> chore: correct inject playwright cache

projects/core/styles/theme/appearance/status.less, projects/layout/components/card/card.styles.less
=> fix: remove default styling from `a` tag in card component

projects/cdk/schematics/ng-update/v4/steps/constants/migration-warnings.ts
=> chore: add migration warnings

projects/layout/components/app-bar/app-bar-back.component.ts
=> feat(layout): `AppBarBack` add ability to use custom appearance

projects/demo/src/modules/components/navigation/index.less, projects/layout/components/navigation/aside.style.less, projects/layout/components/navigation/header.style.less, projects/layout/components/navigation/main.style.less
=> fix(layout): `Navigation` fix various style issues

projects/addon-charts/components/line-chart/line-chart.component.ts
Fixes https://github.com/taiga-family/taiga-ui/issues/9720
=> fix(addon-charts): fix division by zero in LineChart

projects/demo/src/modules/app/pages.ts
=> chore: pagination fix qualified name

projects/addon-charts/project.json, projects/addon-commerce/project.json, projects/addon-doc/project.json, projects/addon-mobile/project.json, projects/addon-table/project.json, projects/cdk/project.json, projects/core/project.json, projects/experimental/project.json, projects/i18n/project.json, projects/icons-fontawesome/project.json, projects/icons-material/project.json, projects/icons/project.json, projects/kit/project.json, projects/layout/project.json, projects/legacy/project.json, projects/styles/project.json, projects/taiga-schematics/project.json, projects/testing/project.json
=> ci: arguments should not be forwarded to other commands

projects/demo/src/modules/app/stackblitz/project-files/src/main.ts.md, projects/demo/src/modules/app/utils/example-content-processor/typescript-processor.ts
=> chore(demo): mock demo routes in examples

projects/addon-mobile/styles/common/block-status.less, projects/layout/components/block-status/block-status.style.less
Fix UIKIT-7696
Same PR for v3 https://github.com/taiga-family/taiga-ui/pull/9742
=> fix(layout): TuiBlockStatus remove margins for empty t-block-image

projects/demo-playwright/tests/kit/tiles/tiles.pw.spec.ts, projects/demo-playwright/utils/goto.ts, projects/kit/components/tiles/tile.component.ts, projects/kit/components/tiles/tiles.component.ts
=> fix(kit): correctly loose box shadow on tile after dragged

.github/workflows/e2e.yml, projects/demo-playwright/playwright.config.ts, projects/demo-playwright/tests/core/hint/hint.pw.spec.ts, projects/demo-playwright/tests/deep/deep-select.pw.spec.ts, projects/demo-playwright/tests/deep/deep-toggle.pw.spec.ts, projects/demo-playwright/tests/demo/demo.pw.spec.ts, projects/demo-playwright/tests/kit/calendar-range/calendar-range.pw.spec.ts, scripts/visual-testing/combine-playwright-failed-screenshots.ts
=> chore: investigate threshold

package-lock.json, projects/cdk/directives/focus-trap/focus-trap.directive.ts, projects/demo-cypress/package.json, projects/demo-cypress/src/support/component.ts, projects/demo-cypress/src/tests/focus-trap.cy.ts
=> fix(cdk): `FocusTrap` has race condition problems

projects/addon-mobile/components/sheet-dialog/sheet-dialog.template.html
Fixes https://github.com/taiga-family/taiga-ui/issues/9796
=> fix(addon-mobile): drop close button for sheet dialog

projects/cdk/schematics/ng-update/v4/steps/styles/index.ts, projects/cdk/schematics/ng-update/v4/steps/styles/migrate-legacy-mixins.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-styles.spec.ts
https://github.com/taiga-family/taiga-ui/blob/e9b43cad124768dd4e3d67025476c9eff4209bb5/projects/legacy/styles/taiga-ui-local.less#L2-L3
=> fix(cdk): missing migration schematic for mixins from `@taiga-ui/legacy/styles/taiga-ui-local`

projects/addon-mobile/styles/common/button.less
=> fix(addon-mobile): update font of large buttons on mobile

projects/demo/src/modules/components/icon/index.html, projects/demo/src/modules/components/icon/index.ts, projects/demo/used-icons.ts
=> chore(demo): improve icon API page with shape elements

projects/addon-charts/project.json, projects/addon-commerce/project.json, projects/addon-doc/project.json, projects/addon-mobile/project.json, projects/addon-table/project.json, projects/cdk/project.json, projects/core/project.json, projects/experimental/project.json, projects/i18n/project.json, projects/kit/project.json, projects/layout/project.json, projects/legacy/project.json, projects/taiga-schematics/project.json, projects/testing/project.json
https://github.com/taiga-family/taiga-ui/actions/runs/12038359284/job/33563859547
=> ci: do not forward params by default

projects/demo-playwright/tests/kit/input-date-time/input-date-time.spec.ts, projects/demo/src/modules/components/input-date-time/examples/6/index.html, projects/demo/src/modules/components/input-date-time/examples/6/index.ts, projects/demo/src/modules/components/input-date-time/input-date-time.component.ts, projects/demo/src/modules/components/input-date-time/input-date-time.module.ts, projects/demo/src/modules/components/input-date-time/input-date-time.template.html, projects/kit/components/input-date-time/input-date-time.component.ts
=> fix(kit): `InputDateTime` validators not triggered when value change

projects/experimental/components/navigation/aside.style.less
=> fix(layout): `Navigation` fix aside width according to spec

projects/legacy/components/input-date-range/test/input-date-range.component.spec.ts
=> chore: exclude broken unit test

projects/demo/src/modules/components/animations/examples/3/index.ts
Fixes # [9704](https://github.com/taiga-family/taiga-ui/issues/9704)
=> chore(demo): fix `tuiFadeIn` in demo

.gitignore, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.component.ts, projects/addon-mobile/components/pull-to-refresh/pull-to-refresh.template.html, projects/kit/components/carousel/carousel.component.ts, projects/kit/components/carousel/carousel.template.html, projects/legacy/components/sheet/components/sheet-bar/sheet-bar.template.html
=> refactor: drop `ngStyle`

projects/demo/src/modules/components/thumbnail-card/examples/3/index.less
Update according recent design specs
=> chore(demo): `ThumbnailCard` with `blur` effect should have semi-transparent white overlay

projects/addon-mobile/styles/common/card-large.less, projects/demo/src/modules/experimental/card-large/card-large.template.html, projects/demo/src/modules/experimental/card-large/examples/12/index.html
=> fix(addon-mobile): `Card` fix paddings on mobile devices

projects/kit/components/avatar/avatar.style.less, projects/layout/components/navigation/aside.style.less, projects/layout/components/navigation/header.style.less
=> chore(layout): `Navigation` prepare for proprietary new year theme

projects/demo/src/modules/components/multi-select/examples/5/index.html, projects/demo/src/modules/components/multi-select/examples/6/index.html, projects/legacy/components/multi-select-option/multi-select-option.style.less, projects/legacy/components/multi-select-option/multi-select-option.template.html
=> feat(legacy): `MultiSelect` allow checkbox on the right side

projects/demo/src/modules/components/input-time/input-time.component.ts, projects/demo/src/modules/components/input-time/input-time.template.html, projects/kit/components/input-time/input-time.component.ts
=> feat(kit): add `itemsHidden` prop to `tui-input-time`

projects/demo-playwright/tests/core/breakpoint-service/breakpoint-service.pw.spec.ts, projects/demo-playwright/tests/core/dialogs/dialogs.pw.spec.ts, projects/demo-playwright/tests/core/hint/hint.pw.spec.ts, projects/demo-playwright/tests/deep/deep-select.pw.spec.ts, projects/demo-playwright/tests/deep/deep-toggle.pw.spec.ts, projects/demo-playwright/tests/kit/calendar-range/calendar-range.pw.spec.ts, projects/demo-playwright/tests/kit/input-table/input-table.pw.spec.ts, projects/demo-playwright/tests/kit/line-clamp/line-clamp.pw.spec.ts, projects/demo-playwright/tests/kit/range/range.pw.spec.ts, projects/demo-playwright/tests/kit/slider/slider.pw.spec.ts, projects/demo-playwright/tests/legacy/input-time/input-time.pw.spec.ts
=> chore: rename screenshots

tsconfig.spec.json
https://github.com/user-attachments/assets/f72c93d2-9307-4815-99be-697b585fde89
=> chore: enable IDE breakpoints for jest tests

projects/kit/components/tiles/tile-handle.directive.ts
=> fix(kit): strange behavior in Safari when working with tiles

projects/addon-table/components/table-pagination/table-pagination.component.ts, projects/demo/src/modules/components/table-pagination/index.html, projects/demo/src/modules/components/table-pagination/index.ts
=> fix(addon-table): fix calculating start page

projects/experimental/directives/fade/fade.style.less
=> fix(experimental): `Fade` fix mask-position

projects/kit/components/carousel/carousel.style.less
=> fix(kit): `Carousel` fix scrolling page on mobile devices

projects/addon-mobile/styles/common/button.less
=> chore(addon-mobile): fix disable button appearance on mobile

projects/core/components/dialog/dialog.style.less, projects/core/components/dialog/dialog.template.html
=> fix(core): dialog has padding for close button event when not closeable

projects/demo/src/modules/components/form/examples/2/index.html, projects/demo/src/modules/components/form/examples/2/index.less, projects/demo/src/modules/components/form/examples/2/index.ts, projects/demo/src/modules/components/form/index.ts
=> chore(demo): improve form example

.cspell.json, projects/cdk/schematics/ng-update/v4/steps/constants/tags-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-blocked.spec.ts
=> chore: fix block migration

projects/demo/src/modules/experimental/thumbnail-card/thumbnail-card.component.ts, projects/experimental/components/thumbnail-card/thumbnail-card.component.ts, projects/experimental/components/thumbnail-card/thumbnail-card.options.ts, projects/experimental/components/thumbnail-card/thumbnail-card.style.less, projects/experimental/components/thumbnail-card/thumbnail-card.template.html
Cherry-picks:
* https://github.com/taiga-family/taiga-ui/pull/9969
Closes #10043
=> feat(experimental): `ThumbnailCard` has new `xs` size

projects/demo/src/modules/components/table/examples/8/index.html, projects/demo/src/modules/components/table/examples/8/index.ts, projects/legacy/components/primitive-textfield/primitive-textfield.component.ts
=> fix(legacy): wrong prefix placement in table context

projects/experimental/directives/button-vertical/button-vertical.style.less
=> fix(experimental): `ButtonVertical` fix style priority

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-pagination.spec.ts
=> chore(schematics): valid migration for addon-table

projects/kit/components/checkbox/checkbox.component.ts, projects/kit/components/radio/radio.component.ts, projects/kit/components/switch/switch.component.ts
=> fix(kit): fix change detection in `Radio`, `Checkbox` and `Switch`

projects/core/components/textfield/textfield-content.directive.ts, projects/core/styles/components/textfield.less, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/demo-routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/input-pin/examples/1/index.html, projects/demo/src/modules/components/input-pin/examples/1/index.ts, projects/demo/src/modules/components/input-pin/examples/2/index.html, projects/demo/src/modules/components/input-pin/examples/2/index.ts, projects/demo/src/modules/components/input-pin/examples/3/index.html, projects/demo/src/modules/components/input-pin/examples/3/index.ts, projects/demo/src/modules/components/input-pin/examples/import/import.md, projects/demo/src/modules/components/input-pin/examples/import/template.md, projects/demo/src/modules/components/input-pin/index.html, projects/demo/src/modules/components/input-pin/index.ts, projects/kit/components/index.ts, projects/kit/components/input-pin/index.ts, projects/kit/components/input-pin/input-pin.component.ts, projects/kit/components/input-pin/input-pin.style.less, projects/kit/components/input-pin/input-pin.template.html, projects/kit/components/input-pin/ng-package.json
=> feat(kit): `InputPin` add new component

projects/kit/components/prompt/prompt.style.less
=> fix(kit): fix text overflow in Prompt component

projects/cdk/schematics/ng-update/v4/steps/constants/attr-with-values-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-textfield-controller.spec.ts
=> chore(schematics): valid migration for size of `tui-data-list-wrapper`

projects/cdk/schematics/ng-update/v4/migrate-icons/rename-icons.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-icons.spec.ts
=> chore(schematics): valid migration for icons

projects/cdk/schematics/ng-update/v4/steps/constants/attrs-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-resizer.spec.ts
=> chore(schematics): valid migration for resizable module

projects/layout/components/block-status/block-status.style.less
=> fix(layout): `BlockStatus` fix image height

projects/experimental/directives/header/header.styles.less
=> fix(experimental): `Header` fix subtitle padding on mobile

projects/demo/src/modules/components/badged-content/index.html, projects/demo/src/modules/components/badged-content/index.ts
Fixes #9057 
- Migrate badged content doc api to new api.
=> #9057 - Migrate `tui-badged-content` doc API to new API

projects/addon-commerce/pipes/amount/amount.pipe.ts, projects/demo/src/modules/pipes/amount/examples/2/index.html
Fixes [#10127](https://github.com/taiga-family/taiga-ui/issues/10127)
=> fix(addon-commerce): tuiAmount hiding negative sign when value is zero

projects/cdk/schematics/ng-update/v4/steps/constants/types.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-identifiers.spec.ts
=> chore(schematics): valid migration for `TuiStepState`

projects/core/utils/miscellaneous/to-animation-options.ts, projects/demo/src/modules/components/card-large/examples/14/index.html, projects/demo/src/modules/components/card-large/examples/14/index.ts
=> chore(demo): add animation

projects/cdk/schematics/ng-update/v4/migrate-addon-doc/index.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-doc.spec.ts
=> chore(schematics): valid migration for tuiProvideRoutePageTab

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-legacy-textfields.spec.ts
=> chore(schematics): valid migration for legacy

projects/experimental/components/swipe-action/swipe-actions.style.less
=> fix(experimental): `SwipeActions` fix actions in IOS safari

projects/demo/src/modules/components/navigation/examples/1/index.html, projects/demo/src/modules/components/navigation/examples/1/index.ts, projects/layout/components/navigation/hint-aside.directive.ts
Fixes #10111
https://github.com/user-attachments/assets/03bf0361-eecd-4378-8ee7-64dda3299693
https://github.com/user-attachments/assets/a6ec8ce4-517b-40b4-9e9c-231e8fe969f4
=> fix(layout): get view only on demand in `tuiAsideItem`

package-lock.json, projects/addon-doc/package.json
=> fix(addon-doc): pin "ngx-highlightjs" peer dependency version

projects/demo/src/modules/components/axes/index.html, projects/demo/src/modules/components/axes/index.ts
Fixes #9057 
Changes Description :-
- Migrate axes chart docs API to new API
=> #9057 - chore(demo): Migrate `tui-axes-chart` docs API to new API

projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/steps/templates/dropdown-ref-comment.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-hosted-dropdown.spec.ts
=> chore(schematics): valid migration for hosted dropdown

projects/legacy/components/color-selector/flat-picker/flat-picker.style.less, projects/legacy/components/color-selector/linear-multi-picker/linear-multi-picker.style.less, projects/legacy/components/color-selector/linear-picker/linear-picker.style.less
=> fix(legacy): fixed color picker pointer

projects/addon-mobile/styles/android/checkbox.less, projects/addon-mobile/styles/ios/checkbox.less, projects/demo/src/modules/components/checkbox/examples/1/index.html, projects/demo/src/modules/components/checkbox/examples/1/index.less, projects/demo/src/modules/components/checkbox/examples/1/index.ts, projects/kit/styles/components/checkbox.less
=> feat(addon-mobile): new android/ios icon behaviour for checkbox

projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts
=> chore(cdk): fix `Scrollbar` migration

projects/addon-mobile/styles/common/header.less, projects/demo/src/modules/components/header/examples/1/index.html, projects/demo/src/modules/components/header/examples/2/index.html, projects/demo/src/modules/components/header/examples/2/index.less, projects/demo/src/modules/components/header/examples/2/index.ts, projects/demo/src/modules/components/header/examples/3/index.html, projects/layout/components/header/header.directive.ts, projects/layout/components/header/header.styles.less
=> feat(layout): `Header` add body-l and body-m sizes

projects/demo/src/modules/components/checkbox/index.html, projects/demo/src/modules/components/radio/examples/1/index.html, projects/demo/src/modules/components/radio/examples/1/index.less, projects/demo/src/modules/components/radio/examples/1/index.ts, projects/kit/styles/components/checkbox.less, projects/kit/styles/components/radio.less, projects/kit/styles/components/switch.less
=> fix(kit): regression style in radio button

projects/demo/src/modules/components/button/examples/7/index.html, projects/demo/src/modules/components/button/examples/7/index.less, projects/demo/src/modules/components/button/examples/7/index.ts, projects/demo/src/modules/components/button/index.ts
=> feat(demo): `Button` add example with two labels

projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts, projects/demo/src/modules/components/sheet-dialog/index.html
=> fix(addon-mobile): background blackout do not disappear on mobile after longtap event

projects/demo/src/modules/components/icon/index.html
=> chore(demo): fix typo

projects/core/directives/hint/hint.component.ts, projects/core/directives/hint/hint.style.less, projects/demo/src/modules/markup/colors/constants.ts, projects/legacy/components/textarea/textarea.style.less
=> fix(core): `Hint` fix dark mode colors

projects/kit/directives/connected/connected.style.less
=> fix(kit): `Connected` make compatible with `Chevron`

projects/layout/components/card/card.styles.less
=> fix(layout): `CardLarge` fix title boldness

projects/demo/src/modules/components/ring-chart/index.html
Fixes #9057 
- Migrate ring chart api doc to new API.
=> chore(demo): migrate ring-chart docs to new api

projects/demo/src/modules/components/bar-chart/index.html
Fixes #9057 
- Migrate bar chart api doc to new API.
=> chore(demo): migrate bar-chart docs to new api

projects/demo/src/modules/components/pie-chart/index.html
Fixes #9057 
- Migrate Pie Chart API docs to the new API.
=> chore(demo): migrate pie-chart docs to new api

projects/demo/src/modules/components/filter/index.html
#9057
- Migrate bar chart api doc to new API
=> chore(demo): migrate filter api docs to new api

projects/demo/src/modules/components/legend-item/index.html
#9057 
- Migrate legend item api doc to new API.
=> chore(demo): migrate legend-item api docs to new api

projects/demo/src/modules/components/group/index.html
#9057 
- Migrate group api doc to new API.
=> chore(demo): migrate group api docs to new api

projects/demo-playwright/tests/legacy/input-date-time/input-date-time.pw.spec.ts, projects/demo/src/modules/components/input-date-time/examples/1/index.html, projects/demo/src/modules/components/input-date-time/examples/1/index.ts
=> chore(demo-playwright): `InputDateTime` add test show actual min/max

projects/demo/src/modules/components/carousel/examples/1/index.html, projects/demo/src/modules/components/carousel/examples/1/index.ts, projects/kit/components/carousel/carousel.directive.ts
=> fix(kit): `Carousel` fix autoscroll in ssr

CHANGELOG.md, projects/kit/components/input-pin/input-pin.style.less
=> chore: fix changelog

projects/addon-mobile/directives/elastic-sticky/elastic-sticky.service.ts, projects/demo/src/modules/directives/elastic-sticky/examples/1/index.less, projects/demo/src/modules/directives/elastic-sticky/examples/2/index.html, projects/demo/src/modules/directives/elastic-sticky/examples/2/index.ts, projects/demo/src/modules/directives/elastic-sticky/index.html
=> fix(addon-mobile): `ElasticSticky` recalculates offsetTop if host content was changed

projects/demo-playwright/tests/legacy/input-date/input-date.pw.spec.ts, projects/demo/src/modules/components/input-date/examples/3/index.ts, projects/demo/src/modules/components/input-date/index.ts
=> chore(demo): `InputDate` fix example with items

projects/core/components/calendar/calendar-sheet.component.ts, projects/demo-playwright/tests/legacy/input-date-range/input-date-range.pw.spec.ts
Reopen https://github.com/taiga-family/taiga-ui/issues/3708
=> fix(core): regression of selecting day when used min length

projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
=> feat(addon-mobile): `SheetDialog` content inherit border-radius

projects/core/directives/icons/icons.directive.ts, projects/demo/src/modules/components/avatar/examples/2/index.html, projects/kit/components/avatar/avatar.component.ts, projects/kit/components/avatar/avatar.style.less, projects/kit/components/avatar/avatar.template.html
=> fix(kit): `Avatar` fix icon color for appearances

package-lock.json, projects/addon-mobile/package.json
=> feat(addon-mobile): `@taiga-ui/layout` should be peer dependency

.github/workflows/e2e.yml, .github/workflows/test.yml
=> chore: `actions/upload-artifact` update from 3.1.3 to 4.6.0

projects/experimental/components/avatar/avatar.component.ts
=> fix(experimental): `Avatar` colored icon object-fit

projects/core/styles/mixins/mixins.less, projects/demo/src/modules/components/tabs/examples/7/index.html, projects/demo/src/modules/components/tabs/examples/7/index.less, projects/demo/src/modules/components/tabs/examples/7/index.ts, projects/demo/src/modules/components/tabs/index.html, projects/demo/src/modules/components/tabs/index.ts, projects/kit/components/tabs/tabs-with-more.component.ts, projects/kit/components/tabs/tabs-with-more.style.less, projects/kit/components/tabs/tabs.style.less
=> fix(kit): `Tabs` properly inherit font styles

projects/demo/src/modules/components/chip/examples/6/index.html, projects/demo/src/modules/components/chip/examples/6/index.less, projects/demo/src/modules/components/chip/examples/6/index.ts, projects/demo/src/modules/components/chip/index.html, projects/demo/src/modules/components/chip/index.ts, projects/demo/used-icons.ts, projects/kit/styles/components/chip.less
=> feat(kit): `Chip` add default rules for fade

projects/addon-table/components/table/directives/sort-by.directive.ts, projects/addon-table/components/table/directives/sortable.directive.ts, projects/addon-table/components/table/directives/table.directive.ts, projects/addon-table/components/table/table.options.ts, projects/demo/src/modules/components/table/examples/4/index.html, projects/demo/src/modules/components/table/examples/4/index.ts
Fixes https://github.com/taiga-family/taiga-ui/issues/3915
=> feat(addon-table): add new output event with sort and direction changes

projects/experimental/tokens/icon-resolver.ts
=> fix(experimental): `TUI_ICON_RESOLVER` fix default path to respect base href

projects/core/directives/dropdown/dropdown-context.directive.ts
=> fix(core): check tuiDropdownContext activeZone only when dropdown is open

projects/addon-table/components/table/th/th.style.less, projects/cdk/directives/font-size/font-size.directive.ts, projects/core/components/data-list/data-list.style.less, projects/core/styles/components/appearance.less, projects/core/styles/components/button.less, projects/core/styles/components/textfield.less, projects/core/styles/mixins/mixins.less, projects/core/styles/theme/appearance/primary.less, projects/core/styles/theme/variables.less, projects/core/utils/miscellaneous/font-scaling.ts, projects/core/utils/miscellaneous/index.ts, projects/demo/src/modules/app/app.config.ts, projects/demo/src/modules/app/app.style.less, projects/demo/src/modules/app/stackblitz/project-files/src/global_styles.less.md, projects/demo/src/modules/components/bottom-sheet/examples/3/index.ts, projects/demo/src/modules/components/bottom-sheet/index.less, projects/demo/src/modules/components/bottom-sheet/index.ts, projects/demo/src/modules/components/input-search/examples/1/index.less, projects/kit/styles/components/chip.less, projects/layout/components/navigation/drawer.component.ts, projects/layout/components/navigation/header.style.less
=> feat(core): add font scaling option

projects/core/components/button/button.style.less
=> fix(core): enable pointer-events on disabled button

projects/kit/directives/unfinished-validator/unfinished-validator.directive.ts, projects/legacy/directives/unfinished-validator/unfinished-validator.directive.ts
=> feat(kit): `UnfinishedValidator` allow dynamic messages

projects/kit/components/files/files/files.styles.less
=> fix(kit): `Files` hide element when empty

projects/core/styles/components/appearance.less, projects/core/styles/mixins/mixins.less, projects/core/styles/mixins/mixins.scss, projects/demo-playwright/tests/addon-commerce/input-card-group.pw.spec.ts, projects/demo/src/modules/components/button/examples/2/index.html
=> fix(core): enable pointer events on disabled button

projects/kit/components/action-bar/action-bar.component.ts, projects/kit/components/action-bar/action-bar.style.less
=> fix(kit): `ActionBar` fix background color

projects/layout/components/card/card.styles.less
=> fix(layout): `Card` add default background color

projects/kit/components/checkbox/checkbox.component.ts, projects/kit/components/radio/radio.component.ts, projects/kit/components/switch/switch.component.ts
=> fix(kit): `Checkbox`, `Radio`, `Switch` return the lost appearance mode

projects/demo/src/modules/components/icon/examples/9/index.html, projects/demo/src/modules/components/icon/examples/9/index.less, projects/demo/src/modules/components/icon/examples/9/index.ts, projects/demo/src/modules/components/icon/index.html
=> chore(demo): add example

projects/demo/src/modules/components/header/examples/import/import.md, projects/demo/src/modules/components/header/index.html
=> fix(demo): `TuiHeader` add `TuiTitle` to import example

projects/demo/src/modules/components/form/examples/2/index.html, projects/demo/src/modules/components/form/examples/2/index.less, projects/layout/components/form/form.styles.less
=> feat(layout): `Form` simplify columns

projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
=> feat(addon-mobile): `TuiSheetDialog` provide `TUI_SCROLL_REF`

projects/demo/src/modules/components/navigation/examples/1/index.html, projects/layout/components/navigation/header.style.less
=> feat(layout): `Navigation` update according to specs

projects/kit/pipes/filter-by-input/filter-by-input.pipe.ts
=> fix(kit): add additional overload to `tuiFilterByInput` pipe

projects/core/styles/theme/appearance/action.less
=> chore: fix appearance

projects/demo/src/modules/components/icon/index.html
Fixes #9057
- Migrate icon api doc to new API.
=> chore(demo): migrate icon api docs to new api

projects/demo/src/modules/components/carousel/index.html
Fixes #9057
- Migrate carousel api doc to new API.
=> chore(demo): migrate carousel api docs to new api

projects/demo-cypress/src/tests/input-number/maxlength.cy.ts, projects/kit/components/input-number/input-number.directive.ts
=> fix(kit): `InputNumber` should support `[attr.maxLength]`

projects/demo/src/modules/components/bar-set/index.html
#9057 
- Migrate bar-set api doc to new API.
=> chore(demo): migrate bar set api docs to new api

projects/demo/src/modules/components/input-color/index.html
#9057 
- Migrate ring chart api doc to new API.
=> chore(demo): migrate input-color api docs to new api

projects/core/components/data-list/data-list.component.ts, projects/layout/components/navigation/aside-item.directive.ts
=> fix(core): `DataList` fix empty content

projects/demo-cypress/cypress.config.ts
Sometimes we have a problem inside cypress job
=> chore: disable experimental mode

projects/demo/src/modules/components/line-chart/index.html
Fixes #9057
- Migrate line-chart api doc to new API.
=> chore(demo): migrate line-chart api docs to new api

projects/demo/src/modules/components/calendar-month/index.html
Fixes #9057
- Migrate calendar-month api doc to new API.
=> chore(demo): migrate calendar-month api docs to new api

projects/addon-mobile/styles/common/chip.less, projects/addon-mobile/styles/taiga-ui-mobile.less
=> feat(addon-mobile): `Chip` add mobile styles

projects/demo/src/modules/components/checkbox-labeled/checkbox-labeled.component.ts
=> chore(demo): fix checkbox-labeled demo

projects/demo/src/modules/components/combo-box/index.html
Fixes #9057 
- Migrate combo-box api doc to new API.
=> chore(demo): migrate combo-box api docs to new api

projects/demo/src/modules/components/calendar/index.html
Fixes #9057
- Migrate calendar api doc to new API.
=> chore(demo): migrate calendar docs to new api

projects/kit/styles/components/comment.less
=> fix(kit): `Comment` add min-width

projects/kit/directives/skeleton/skeleton.style.less
Fixes UIKIT-7777
part of #10508
=> fix: skeleton view without animation

.github/workflows/build.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/schematic.yml, .github/workflows/snapshots.yml, .github/workflows/test.yml, nx.json
feat(nx-cloud): setup nx cloud workspace
This commit sets up Nx Cloud for your Nx workspace, enabling distributed caching and the Nx Cloud GitHub integration for fast CI and improved developer experience.
You can access your Nx Cloud workspace by going to
https://cloud.nx.app/orgs/65378c51c41da457dd03ebfc/workspaces/67c8563891c060baed5637e6
**Note:** This commit attempts to maintain formatting of the nx.json file, however you may need to correct formatting by running an nx format command and committing the changes.
=> feat(nx-cloud): set up nx workspace

projects/demo/src/modules/components/input-color/index.html, projects/demo/src/modules/components/textarea/index.html
=> chore(demo): change package tag

projects/demo/src/modules/components/sheet-dialog/examples/7/index.html, projects/demo/src/modules/components/sheet-dialog/examples/7/index.ts
=> chore(demo): `SheetDialog` fullsize example remove unnesessary tuiRepeatTimes pipe

projects/demo/src/modules/components/input-month/examples/1/index.html, projects/demo/src/modules/components/input-month/examples/5/index.html, projects/demo/src/modules/components/input-month/examples/5/index.ts, projects/demo/src/modules/components/input-month/examples/import/template.md, projects/demo/src/modules/components/input-month/index.html, projects/kit/components/input-month/input-month.directive.ts, projects/kit/components/input-month/native-month-picker/native-month-picker.component.ts, projects/kit/components/input-month/native-month-picker/native-month-picker.template.html
Relates:
- https://github.com/taiga-family/taiga-ui/pull/10345
=> chore(kit): refactor `min` / `max` logic for new `InputMonth`

projects/demo/src/modules/components/push/index.html, projects/demo/src/modules/components/push/index.ts, projects/kit/components/push/push.component.ts, projects/kit/components/push/push.style.less
=> fix(kit): support customizing number of visible lines in `tui-push`

projects/core/components/data-list/option/option.component.ts, projects/core/components/data-list/option/option.style.less
=> fix(core): focus option by mousemove only in dropdown manager

projects/legacy/components/textarea/textarea.style.less
Fixed https://github.com/taiga-family/taiga-ui/issues/10518
=> fix(legacy): textarea flickering when type space

projects/addon-table/components/table/directives/direction-order.directive.ts, projects/addon-table/components/table/directives/sort-by.directive.ts, projects/addon-table/components/table/directives/table.directive.ts, projects/addon-table/components/table/table.options.ts, projects/demo/src/modules/components/table/examples/4/index.html, projects/demo/src/modules/components/table/examples/4/index.ts
=> fix(addon-table): improve `tuiSortChange` event

projects/addon-mobile/styles/common/block-status.less, projects/demo/src/modules/components/block-status/examples/8/index.html, projects/demo/src/modules/components/block-status/examples/8/index.less, projects/demo/src/modules/components/block-status/examples/8/index.ts, projects/demo/src/modules/components/block-status/index.ts, projects/layout/components/block-status/block-status.style.less
=> fix(layout): `BlockStatus` fix margin when description block is empty

projects/kit/styles/components/block.less
Fixes # add isolation:isolate for tuiBlock
=> fix(kit): fix style for tui-block

projects/core/styles/theme/variables.less
=> chore: fix fonts on stackblitz

package-lock.json, projects/testing/package.json
Part of https://github.com/taiga-family/taiga-ui/issues/10470
=> chore(testing): add peer dependency

projects/cdk/schematics/ng-update/v4/migrate-icons/index.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-templates.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-icons.spec.ts
Part of https://github.com/taiga-family/taiga-ui/issues/10396
=> chore(schematics): add padding for large icons

projects/legacy/components/input-month/input-month.component.ts, projects/legacy/components/input-month/input-month.directive.ts, projects/legacy/components/input-month/input-month.module.ts
Relates:
* https://github.com/taiga-family/taiga-ui/pull/10345
=> chore(legacy): mark legacy `InputMonth` as deprecated

projects/demo/src/modules/components/data-list/examples/6/index.html, projects/demo/src/modules/components/data-list/examples/6/index.ts, projects/demo/src/modules/components/notification/examples/4/index.html, projects/demo/src/modules/components/notification/examples/4/index.less, projects/demo/src/modules/components/notification/examples/4/index.ts, projects/demo/src/modules/components/notification/index.ts
=> chore(demo): `Notification` add customization example

projects/kit/styles/components/checkbox.less
=> fix(kit): disabled checkbox must not be interactive

projects/legacy/components/textarea/textarea.style.less
=> fix(legacy): do not expand textarea horizontally for long word

projects/demo-playwright/playwright.config.ts, projects/demo-playwright/tests/demo/demo.pw.spec.ts
=> chore: move axe config to env

projects/kit/components/textarea/textarea.style.less
=> fix(kit): do not expand textarea horizontally for long word

projects/kit/components/multi-select/multi-select.style.less
=> fix(kit): scrollbar in multi-select with data-list-wrapper

projects/addon-table/components/table/directives/table.directive.ts, projects/demo/src/modules/components/table/examples/4/index.html, projects/demo/src/modules/components/table/examples/4/index.ts
=> fix(addon-table): `tuiSortChange` event should emit when `requiredSort` is enabled

projects/addon-table/components/table-pagination/table-pagination.component.ts, projects/demo-playwright/tests/addon-table/table-pagination/table-pagination.pw.spec.ts
=> fix(addon-table): `TablePagination` fix incorrect calculating start page

projects/core/directives/dropdown/dropdown.directive.ts
=> fix(core): synchronize driver's state

projects/addon-charts/components/bar-chart/bar-chart.component.ts, projects/addon-charts/components/bar-chart/bar-chart.template.html, projects/demo/src/modules/components/bar-chart/index.html
=> feat(addon-charts): add `tapColumn` output event in `tui-bar-chart`

projects/cdk/schematics/ng-update/interfaces/html-comment.ts, projects/cdk/schematics/ng-update/utils/templates/template-comments.ts, projects/cdk/schematics/ng-update/v4/steps/constants/html-comments.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-svg.spec.ts
=> chore(schematics): add html comments for colored icons

projects/demo/src/modules/app/pages.ts
=> chore: actualize db

projects/core/components/dialog/dialog.component.ts, projects/demo/src/modules/components/button-group/examples/4/index.html, projects/demo/src/modules/components/button-group/examples/4/index.ts, projects/demo/src/modules/components/button-group/index.ts, projects/kit/components/carousel/carousel.component.ts, projects/kit/directives/button-group/button-group.style.less
https://github.com/user-attachments/assets/97a34a5e-6830-4767-9ef0-89bdb447ac65
https://github.com/user-attachments/assets/0652668c-7451-4cf2-9711-48c699332acc
=> feat(kit): add `shift` output event to `carousel` component

projects/core/components/dialog/dialog.style.less
=> fix(core): `Dialog` content section inherit border-radius

projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts, projects/addon-mobile/components/sheet-dialog/sheet-dialog.options.ts, projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less, projects/addon-mobile/components/sheet-dialog/sheet-dialog.template.html, projects/demo/src/modules/components/sheet-dialog/examples/5/index.html, projects/demo/src/modules/components/sheet-dialog/examples/5/index.less, projects/demo/src/modules/components/sheet-dialog/examples/5/index.ts, projects/demo/src/modules/components/sheet-dialog/sheet-dialog.component.ts, projects/demo/src/modules/components/sheet-dialog/sheet-dialog.module.ts, projects/demo/src/modules/components/sheet-dialog/sheet-dialog.template.html
=> feat(addon-mobile): `SheetDialog` add fullscreen option

projects/demo/src/modules/components/sheet-dialog/index.html
=> chore(demo): `SheetDialog` rename fullsize -> fullscreen

projects/addon-mobile/directives/index.ts, projects/addon-mobile/directives/responsive-dialog/index.ts, projects/addon-mobile/directives/responsive-dialog/ng-package.json, projects/addon-mobile/directives/responsive-dialog/responsive-dialog.directive.ts, projects/addon-mobile/directives/responsive-dialog/responsive-dialog.module.ts, projects/addon-mobile/directives/responsive-dialog/responsive-dialog.service.ts, projects/demo/src/modules/components/sheet-dialog/examples/6/index.html, projects/demo/src/modules/components/sheet-dialog/examples/6/index.less, projects/demo/src/modules/components/sheet-dialog/examples/6/index.ts, projects/demo/src/modules/components/sheet-dialog/sheet-dialog.component.ts, projects/demo/src/modules/components/sheet-dialog/sheet-dialog.module.ts, projects/demo/src/modules/components/sheet-dialog/sheet-dialog.template.html
=> feat(addon-mobile): `SheetDialog` add `tuiResponsiveDialog` directive

projects/demo-playwright/tests/core/dropdown/dropdown.pw.spec.ts, projects/legacy/components/multi-select/multi-select-group/multi-select-group.directive.ts
=> fix(legacy): late init control binding in `tuiMultiSelectGroup`

projects/demo/src/modules/components/items-with-more/examples/4/index.html, projects/demo/src/modules/components/items-with-more/examples/4/index.less, projects/demo/src/modules/components/items-with-more/examples/4/index.ts, projects/demo/src/modules/components/items-with-more/index.html, projects/demo/src/modules/components/items-with-more/index.ts, projects/kit/components/items-with-more/items-with-more.component.ts, projects/kit/components/items-with-more/items-with-more.directive.ts, projects/kit/components/items-with-more/items-with-more.service.ts, projects/kit/components/items-with-more/items-with-more.style.less, projects/kit/components/items-with-more/items-with-more.template.html
=> feat(kit): `ItemsWithMore` add multiline mode

projects/demo-playwright/tests/kit/line-clamp/line-clamp.pw.spec.ts, projects/kit/components/line-clamp/line-clamp-box.component.ts
=> fix(core): add hint marker to custom components

projects/addon-mobile/components/theme-android/theme-android.style.less
=> fix(addon-mobile): `Button` uppercase

projects/addon-doc/components/api/api-item-number.directive.ts, projects/addon-doc/components/api/api-item.component.ts, projects/addon-doc/components/api/api-item.template.html, projects/addon-doc/components/index.ts, projects/addon-doc/index.ts, projects/demo/src/modules/components/pager/index.html
Fixes https://github.com/taiga-family/taiga-ui/issues/10699
=> feat(addon-doc): add `TuiDocAPINumberItem` for configure input api option

projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
=> fix(addon-mobile): use `display: block` on sheet host

projects/core/components/root/root.component.ts, projects/core/components/root/root.template.html, projects/core/directives/popup/index.ts, projects/core/directives/popup/popups.component.ts, projects/demo/src/modules/customization/viewport/examples/3/index.ts
=> feat(core): add `<tui-popups />`

projects/demo/src/modules/components/tiles/examples/3/index.html, projects/demo/src/modules/components/tiles/examples/3/index.less, projects/demo/src/modules/components/tiles/examples/3/index.ts, projects/demo/src/modules/components/tiles/index.html, projects/kit/components/tiles/tile.component.ts, projects/kit/components/tiles/tile.service.ts, projects/kit/components/tiles/tiles.component.ts, projects/kit/components/tiles/tiles.style.less
=> fix(kit): ignore transition directly on tile

projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts
=> feat(addon-mobile): `SheetDialog` pass appearance from context

projects/core/components/dialog/dialog.component.ts, projects/core/components/dialog/dialog.template.html
=> feat(core): `Dialog` add event handler to change close button theme

projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
=> fix(addon-mobile): `SheetDialog` content inherit border-radius

projects/demo-playwright/tests/legacy/input-time/input-time.pw.spec.ts, projects/legacy/components/input-time/input-time.component.ts
=> fix(legacy): do not match value until user is writing value in `InputTime`

projects/layout/components/dynamic-header/dynamic-header.ts
=> fix(layout): `TuiDynamicHeader` import as const

projects/experimental/directives/cell/cell.styles.less
=> fix(experimental): `Cell` increase `tuiCellActions` specificity

projects/demo/src/modules/components/cell/examples/9/index.html, projects/demo/src/modules/components/cell/examples/9/index.less, projects/demo/src/modules/components/cell/examples/9/index.ts, projects/layout/components/cell/cell.styles.less
=> fix(layout): `Cell` increase `tuiCellActions` specificity

scripts/shared/ignorable-packages.ts
=> ci: add `@taiga-ui/eslint-plugin-experience-next` to `IGNORABLE_TAIGA_PACKAGES`

projects/addon-table/components/table/th/th.style.less, projects/core/components/textfield/select-like.directive.ts, projects/core/components/textfield/textfield.template.html, projects/core/styles/components/appearance.less, projects/core/styles/components/textfield.less, projects/core/styles/theme/appearance/table.less
=> fix(core): `Textfield` add vertical padding

projects/cdk/utils/miscellaneous/array-toggle.ts, projects/demo-playwright/tests/legacy/multi-select/multi-select.pw.spec.ts, projects/demo/src/modules/components/multi-select/examples/15/index.html, projects/demo/src/modules/components/multi-select/examples/15/index.ts, projects/demo/src/modules/components/multi-select/index.ts, projects/legacy/components/multi-select/multi-select-group/multi-select-group.directive.ts
=> fix(legacy): reuse `identityMatcher` inside `tuiMultiSelectGroup`

projects/core/components/data-list/data-list.style.less
=> fix: enable pointer events on disabled tuiOption

projects/core/directives/dropdown/dropdown.directive.ts, projects/layout/components/navigation/aside-item.directive.ts, projects/layout/components/navigation/aside.style.less, projects/layout/components/navigation/drawer.component.ts
=> fix(layout): `Navigation` fix aside highlights

projects/core/directives/dropdown/dropdown-open.directive.ts, projects/demo-playwright/tests/core/dropdown/dropdown.pw.spec.ts, projects/demo/src/modules/directives/dropdown-open/index.html
=> fix(core): `DropdownOpen` sync state when changed externally

projects/cdk/utils/miscellaneous/font-size-watcher.ts
=> chore(cdk): fix running font scale watcher multiple times

projects/addon-doc/components/api/api-item.style.less
=> fix(addon-doc): set fixed width for last API column

projects/demo/src/modules/components/input-date-range/examples/5/index.html, projects/demo/src/modules/components/input-date-range/examples/5/index.ts, projects/kit/components/input-date-range/input-date-range.component.ts, projects/kit/components/input-date-range/test/input-date-range.component.spec.ts
=> fix(kit): `InputDateRange` update input value after control value changed

scripts/visual-testing/combine-playwright-failed-screenshots.ts
Fixes https://github.com/taiga-family/taiga-ui/issues/10813
=> ci: correct work from single directory

projects/kit/components/line-clamp/line-clamp.template.html
=> chore(kit): `LineClamp` remove whitespace

projects/demo/src/modules/components/range/index.html, projects/demo/src/modules/components/range/index.ts
https://taiga-ui.dev/components/range/API
=> chore(demo): broken initial state of API page for `Range`

projects/core/components/link/link.directive.ts, projects/core/components/link/link.options.ts, projects/core/styles/components/link.less, projects/demo/src/modules/components/link/examples/3/index.html, projects/demo/src/modules/components/link/examples/3/index.less, projects/demo/src/modules/components/link/examples/3/index.ts, projects/demo/src/modules/components/link/index.ts, projects/demo/used-icons.ts
=> feat(core): update `tuiLink` appearance by spec

projects/addon-doc/components/navigation/navigation.style.less, projects/cdk/schematics/ng-add/steps/add-taiga-modules.ts, projects/cdk/schematics/ng-add/tests/schematic-ng-add-standalone.spec.ts, projects/cdk/schematics/ng-add/tests/schematic-ng-add.spec.ts, projects/cdk/schematics/ng-update/interfaces/replacement-identifier.ts, projects/cdk/schematics/ng-update/steps/replace-identifier.ts, projects/cdk/schematics/ng-update/v4/steps/constants/identifiers-to-replace.ts, projects/cdk/schematics/ng-update/v4/steps/migrate-root.ts, projects/cdk/schematics/ng-update/v4/tests/replace-modules-with-providers.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-package-names.spec.ts, projects/demo/src/modules/app/app.const.ts, projects/demo/src/modules/app/home/examples/main-standalone.md, projects/demo/src/modules/app/home/home.template.html
=> chore: migration `NG_EVENT_PLUGINS` => `provideEventPlugins()`

projects/cdk/directives/native-validator/native-validator.directive.ts, projects/demo/src/modules/components/link/examples/3/index.html, projects/kit/components/carousel/carousel.component.ts, projects/kit/components/textarea/textarea.component.ts, projects/kit/components/textarea/textarea.options.ts, projects/kit/directives/textarea-limit/textarea-limit.directive.ts
=> fix(kit): `Textarea` fix change detection issues

projects/demo/src/modules/components/input-slider-legacy/index.html, projects/demo/src/modules/components/input-slider-legacy/index.ts, projects/demo/src/modules/components/input-slider/index.html, projects/demo/src/modules/components/input-slider/index.ts, projects/demo/src/modules/components/slider/index.html, projects/demo/src/modules/components/slider/index.ts, projects/kit/components/slider/slider.component.ts, projects/kit/components/slider/slider.style.less, projects/legacy/components/input-slider/input-slider.component.ts
=> feat(kit): `Slider` supports not equidistant `segments` order

projects/core/components/link/link.directive.ts, projects/core/components/link/link.options.ts, projects/core/styles/components/link.less, projects/core/styles/mixins/mixins.less, projects/demo/src/modules/components/link/examples/2/index.html, projects/demo/src/modules/components/link/examples/3/index.html, projects/demo/src/modules/directives/dropdown-open/examples/3/index.html, projects/kit/components/breadcrumbs/breadcrumbs.style.less
=> fix(core): `Link` fix `Chevron` not rotating

projects/demo/src/modules/components/floating-container/examples/3/index.html
=> chore(demo): `FloatingContainer` remove commented code

projects/demo/src/modules/directives/fade/examples/4/index.html, projects/demo/src/modules/directives/fade/examples/4/index.less, projects/demo/src/modules/directives/fade/examples/4/index.ts, projects/demo/src/modules/directives/fade/index.html, projects/demo/src/modules/directives/fade/index.ts
=> chore: add hyphens example

projects/core/components/root/root.style.less, projects/core/directives/dropdown/dropdown.component.ts, projects/core/directives/dropdown/dropdown.directive.ts, projects/core/directives/dropdown/dropdowns.component.ts, projects/core/tokens/viewport.ts, projects/demo/src/modules/customization/viewport/examples/1/index.less, projects/demo/src/modules/customization/viewport/examples/2/index.ts
=> fix(core): `Root` fix dropdowns when scrollable

projects/core/components/notification/notification.directive.ts, projects/core/directives/icons/icons.directive.ts, projects/demo-cypress/src/tests/select.cy.ts, projects/layout/components/navigation/drawer.component.ts
=> fix(core): `SelectOption` has change detection problems with checked state

projects/demo/src/modules/components/sheet-dialog/examples/4/index.html, projects/demo/src/modules/components/sheet-dialog/examples/4/index.less, projects/demo/src/modules/components/sheet-dialog/examples/4/index.ts
=> chore(demo): `SheetDialog` remove unnecessary scroll behaviour

projects/addon-charts/components/bar-chart/bar-chart.component.ts, projects/addon-charts/components/bar-chart/bar-chart.template.html
=> fix(addon-charts): hint appearance not passed to bar-chart (#10899)

projects/demo/src/modules/customization/dialogs/examples/2/custom-dialog/custom-dialog.component.ts, projects/demo/src/modules/customization/dialogs/examples/2/custom-dialog/custom-dialog.directive.ts, projects/demo/src/modules/customization/dialogs/examples/2/custom-dialog/custom-dialog.service.ts, projects/demo/src/modules/customization/dialogs/examples/2/custom-dialog/custom-dialog.style.less, projects/demo/src/modules/customization/dialogs/examples/2/index.html, projects/demo/src/modules/customization/dialogs/examples/2/index.ts, projects/demo/src/modules/customization/dialogs/index.html, projects/demo/src/modules/customization/dialogs/index.ts
=> chore(demo): `Dialog` add custom dialog with directive example

projects/demo/src/modules/customization/dialogs/examples/2/custom-dialog/custom-dialog.style.less
=> chore(demo): `Dialog` custom dialog remove unused styles

projects/core/components/data-list/data-list.style.less
=> fix(core): change label font size in data list

projects/core/components/textfield/select.directive.ts, projects/demo/src/modules/components/input-month/examples/3/index.ts, projects/demo/src/modules/directives/skeleton/index.html, projects/kit/components/input-month-range/input-month-range.directive.ts, projects/kit/components/input-month/input-month.directive.ts, projects/kit/components/input-month/input-month.options.ts, projects/kit/tokens/input-date-options.ts, tsconfig.build.json, tsconfig.json
=> chore(kit): `InputMonth` switch to global date token for icon

projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts, projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less
=> fix(addon-mobile): `SheetDialog` add env offset

projects/demo/src/components/items-handlers/index.html, projects/demo/src/components/items-handlers/index.ts, projects/demo/src/modules/components/select/index.html, projects/demo/src/modules/components/select/index.ts
Relates for new `Select` + `Combobox` + `MultiSelect`
=> chore(demo): documentation `ItemsHandlers` for API pages

projects/cdk/schematics/ng-update/v4/migrate-css-vars/palette.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badge.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-badged-content.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-button-appearance.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-expandable.ts, projects/cdk/schematics/ng-update/v4/steps/templates/migrate-overscroll.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badge.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-badged-content.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-button-appearance.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-css-vars.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-expandable.spec.ts, projects/cdk/schematics/ng-update/v4/tests/schematic-migrate-overscroll.spec.ts
=> feat: transform comments of the migration to a single format(#10956)

projects/core/directives/dropdown/dropdown.component.ts
=> fix(core): fix dropdown position on render (#10970)

projects/layout/components/navigation/aside-item.directive.ts
=> fix(layout): `AsideItem` fix `_custom` class

projects/demo/src/modules/directives/appearance/examples/4/index.html, projects/demo/src/modules/directives/appearance/examples/4/index.ts
=> chore(demo): add copy Appearance

projects/core/components/textfield/textfield.template.html, projects/demo/src/modules/components/input-search/examples/1/index.html, projects/demo/src/modules/components/sheet-dialog/examples/6/index.html, projects/demo/src/modules/components/sheet-dialog/examples/6/index.ts, projects/experimental/components/input-phone-international/input-phone-international.template.html, projects/experimental/components/input-phone-international/test/input-phone-international.component.spec.ts, projects/layout/components/input-search/input-search.component.ts
=> fix(layout): `InputSearch` fix setting placeholder

projects/cdk/pipes/index.ts, projects/cdk/pipes/obfuscate/index.ts, projects/cdk/pipes/obfuscate/ng-package.json, projects/cdk/pipes/obfuscate/obfuscate.options.ts, projects/cdk/pipes/obfuscate/obfuscate.pipe.ts, projects/cdk/pipes/obfuscate/test/obfuscate.pipe.spec.ts, projects/cdk/utils/miscellaneous/index.ts, projects/cdk/utils/miscellaneous/obfuscate.ts, projects/cdk/utils/miscellaneous/test/obfuscate.spec.ts, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/demo-routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/pipes/obfuscate/examples/1/index.html, projects/demo/src/modules/pipes/obfuscate/examples/1/index.ts, projects/demo/src/modules/pipes/obfuscate/examples/2/index.html, projects/demo/src/modules/pipes/obfuscate/examples/2/index.ts, projects/demo/src/modules/pipes/obfuscate/examples/3/index.html, projects/demo/src/modules/pipes/obfuscate/examples/3/index.ts, projects/demo/src/modules/pipes/obfuscate/examples/import/import.md, projects/demo/src/modules/pipes/obfuscate/examples/import/template.md, projects/demo/src/modules/pipes/obfuscate/index.html, projects/demo/src/modules/pipes/obfuscate/index.ts
=> feat(cdk): new `Obfuscate` pipe

projects/demo-playwright/tests/kit/calendar-range/calendar-range.pw.spec.ts, projects/demo-playwright/utils/page-objects/calendar-sheet.po.ts, projects/kit/components/calendar-range/day-caps-mapper.ts
=> fix(kit): `CalendarRange` is is not limited by `maxLength`

projects/addon-mobile/components/mobile-calendar-dropdown/mobile-calendar-dropdown.style.less, projects/core/components/dialog/dialog.style.less
=> feat(core): `Dialog` add safe-area support

projects/core/components/root/root.component.ts
Fixes #10942 
Special thanks to @waterplea for helping with this tiny issue
=> feat(core): adding support to fullscreen elements outside the portals

projects/addon-doc/components/theme-switcher/theme-switcher.component.ts, projects/addon-doc/services/theme-dark.service.ts, projects/core/tokens/dark-mode.ts, projects/demo/src/modules/app/abstract.app.ts, projects/demo/src/modules/app/landing/index.ts, projects/demo/src/modules/directives/theme/examples/2/index.ts, projects/experimental/components/search-results/search-history.component.ts, projects/i18n/utils/language-switcher.ts, projects/layout/components/form/form.styles.less
=> fix(core): `DARK_MODE` fix for disabled local storage

projects/cdk/classes/control.ts, projects/cdk/classes/value-transformer.ts, projects/cdk/date-time/types.ts, projects/cdk/directives/validator/validator.directive.ts, projects/core/components/calendar/calendar-sheet.style.less, projects/core/components/calendar/calendar.style.less, projects/core/components/textfield/textfield.component.ts, projects/kit/components/files/input-files/input-files-validator.directive.ts, projects/kit/components/input-month/index.ts, projects/kit/components/input-month/input-month.component.ts, projects/kit/components/input-month/input-month.directive.ts, projects/kit/components/input-month/input-month.style.less, projects/kit/components/input-month/input-month.template.html, projects/kit/components/input-month/input-month.ts, projects/kit/components/input-number/input-number.directive.ts, projects/kit/directives/unfinished-validator/unfinished.validator.ts, projects/kit/pipes/field-error/field-error-pipe.ts, projects/kit/tokens/calendar-date-stream.ts, projects/kit/tokens/date-inputs-value-transformers.ts
=> fix(kit): `FieldError` allow overriding `TuiValidationError` via DI

projects/cdk/components/alert-host/alert-host.style.less, projects/core/components/alert/alert.providers.ts
=> feat(core): `Alert` add safe-area support

projects/kit/components/carousel/carousel.directive.ts
Fixes #10969
https://angular.dev/errors/NG0506
=> fix(kit): `Carousel` fix hydration error `NG0506`

projects/core/directives/dropdown/dropdown.component.ts
=> fix(core): `Dropdown` fix positioning in Firefox

package-lock.json, package.json, projects/cdk/directives/animated/animated.directive.ts, projects/cdk/package.json, projects/core/components/textfield/select-like.directive.ts, projects/core/components/textfield/textfield.component.ts, projects/core/package.json, projects/core/styles/components/group.less, projects/demo/src/modules/components/select/examples/1/index.html, projects/kit/directives/chevron/chevron.style.less
=> fix(core): `Textfield` fix errors and issues with chevron + dropdown

projects/addon-doc/components/example/example.style.less, projects/core/components/calendar/calendar.component.ts, projects/demo/src/modules/components/input-date/examples/5/index.ts, projects/demo/src/modules/components/input-date/examples/7/index.ts, projects/kit/components/calendar-range/calendar-range.component.ts, projects/kit/components/calendar-range/calendar-range.template.html, projects/kit/components/input-date/input-date.directive.ts, projects/kit/components/input-number/input-number.directive.ts
=> chore: refactor `InputDate` to be able to extend it for range

projects/kit/components/segmented/segmented.style.less
=> feat(kit): `Segmented` change active item style according to specs

projects/cdk/directives/active-zone/active-zone.directive.ts, projects/core/components/textfield/textfield.component.ts, projects/core/components/textfield/textfield.template.html, projects/experimental/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/combo-box/combo-box.directive.ts, projects/kit/components/input-date/input-date.directive.ts, projects/kit/components/input-month-range/input-month-range.directive.ts, projects/kit/components/input-month/input-month.directive.ts, projects/kit/components/input-phone-international/input-phone-international.component.ts, projects/kit/components/select/select.directive.ts
=> chore: mark as touched using active zone when possible

projects/core/components/textfield/index.ts, projects/core/components/textfield/textfield-multi/textfield-item.component.ts, projects/core/components/textfield/textfield-multi/textfield-multi.component.ts, projects/core/components/textfield/textfield-multi/textfield-multi.template.html, projects/demo/src/modules/components/input-chip/index.html, projects/kit/components/input-chip/input-chip.component.ts, projects/kit/components/input-chip/input-chip.directive.ts
=> chore: move baseline item and focus movement to textfield multi

.cspell.json, projects/core/components/data-list/data-list.component.ts, projects/core/components/data-list/data-list.tokens.ts, projects/demo-playwright/tests/kit/combo-box/combo-box.pw.spec.ts, projects/demo/src/modules/components/combo-box/index.html, projects/demo/src/modules/components/combo-box/index.ts, projects/kit/components/combo-box/combo-box.directive.ts, projects/kit/components/data-list-wrapper/data-list-wrapper.component.ts
Relates:
* https://github.com/taiga-family/taiga-ui/pull/10980#discussion_r2109058436
Closes #11077
=> fix(kit): `ComboBox` should retrigger value matching on new items in datalist

projects/core/directives/dropdown/dropdown.component.ts, projects/core/directives/dropdown/dropdown.style.less
=> chore: `Dropdown` set max width dependent on viewport

projects/demo/src/modules/components/input-files/index.html
https://github.com/taiga-family/taiga-ui/blob/cdfddf40c4994c97a342125c666725a5d866a854/projects/kit/components/files/input-files/input-files.directive.ts#L48-L51
https://github.com/taiga-family/taiga-ui/blob/cdfddf40c4994c97a342125c666725a5d866a854/projects/kit/components/files/files.utils.ts#L10
=> chore(demo): update `InputFiles` API documentation page

projects/demo/src/modules/directives/let/index.html
Relates:
* https://medium.com/@hatsantos/thank-you-for-this-really-interesting-post-607d6b071d22
=> chore(demo): update `*tuiLet` documentation page

projects/cdk/utils/dom/value.ts
=> fix(core): `Textfield` throws `RuntimeError: NG0600`

projects/addon-table/components/table/table-expand/table-expand.component.ts
=> fix(addon-table): skip hydration for table-expand

projects/addon-mobile/styles/common/button.less
=> fix(addon-mobile): `Card` fix buttons stretching in header

projects/cdk/directives/animated/animated.directive.ts
=> chore: remove class regardless of anything

projects/demo-cypress/src/tests/input-date.cy.ts, projects/kit/components/input-date/input-date.directive.ts
=> fix(kit): `InputDate` fix textfield value after resetting

projects/core/directives/hint/hint.component.ts, projects/kit/components/line-clamp/line-clamp-box.component.ts
=> fix(kit): `LineClamp` fix `TuiAnimated matches multiple times` error

projects/demo/src/modules/components/drawer/index.html, projects/demo/src/modules/components/drawer/index.ts
=> chore(demo): add API tab for drawer

projects/demo/src/modules/components/combo-box/examples/7/index.html, projects/demo/src/modules/components/combo-box/examples/7/index.ts
1. Open https://taiga-ui.dev/components/combo-box#content-customization
2. Select any card from datalist
3. Focus input and press any key
Textfield contains `[object Object]3`
=> chore(demo): improve example `Customize content` of documentation page `ComboBox`

projects/demo/project.json
=> chore(demo): add `llms-full.txt` generation to prerender

projects/addon-mobile/components/bottom-sheet/bottom-sheet.component.ts, projects/addon-mobile/components/bottom-sheet/bottom-sheet.style.less, projects/core/components/textfield/textfield-multi/textfield-multi.style.less, projects/core/styles/components/notification.less, projects/core/styles/components/textfield.less, projects/kit/components/textarea/textarea.style.less, projects/kit/directives/chevron/chevron.style.less
=> fix(kit): `InputChip` fix icons position

projects/core/components/loader/loader.style.less
=> fix(core): loader RTL layout support

projects/core/components/textfield/textfield-multi/textfield-item.component.ts, projects/core/components/textfield/textfield-multi/textfield-multi.component.ts, projects/core/components/textfield/textfield-multi/textfield-multi.style.less, projects/core/components/textfield/textfield-multi/textfield-multi.template.html, projects/core/components/textfield/textfield.component.ts, projects/core/components/textfield/textfield.template.html, projects/core/directives/dropdown/dropdown.directive.ts, projects/core/styles/components/textfield.less, projects/demo/src/modules/components/input-chip/examples/5/index.html, projects/demo/src/modules/components/input-chip/examples/5/index.less, projects/demo/src/modules/components/input-chip/examples/5/index.ts, projects/kit/components/input-chip/input-chip.component.ts, projects/kit/components/input-chip/input-chip.directive.ts, projects/kit/components/input-chip/input-chip.template.html, projects/kit/components/select/select-option/select-option.component.ts, projects/kit/pipes/hide-selected/hide-selected.pipe.ts, projects/kit/pipes/hide-selected/index.ts, projects/kit/pipes/hide-selected/ng-package.json, projects/kit/pipes/hide-selected/test/hide-selected.pipe.spec.ts, projects/kit/pipes/index.ts, projects/kit/tokens/items-handlers.ts
=> feat(kit): `HideSelected` add pipe

projects/cdk/observables/control-value.ts, projects/core/components/data-list/option/option.directive.ts, projects/core/components/textfield/textfield.component.ts, projects/demo/src/modules/components/combo-box/examples/12/option.ts, projects/demo/src/modules/components/input-date/examples/8/index.html, projects/demo/src/modules/components/input-date/examples/8/index.less, projects/demo/src/modules/components/select/examples/10/option.ts, projects/demo/src/modules/components/table/examples/7/index.html, projects/kit/components/combo-box/combo-box.directive.ts, projects/kit/components/input-chip/input-chip.component.ts, projects/kit/components/input-chip/input-chip.directive.ts, projects/kit/components/input-chip/input-chip.template.html, projects/kit/components/input-date-range/input-date-range.directive.ts, projects/kit/components/input-date/input-date.directive.ts, projects/kit/components/input-inline/input-inline.component.ts, projects/kit/components/select/select-option/select-option.component.ts, projects/kit/components/select/select-option/select-option.style.less, projects/kit/components/select/select.directive.ts, projects/kit/directives/button-select/button-select.directive.ts, projects/kit/utils/index.ts, projects/kit/utils/inject-value.ts
=> feat(kit): `InputDate` use `SelectOption`

projects/core/components/textfield/textfield.component.ts, projects/demo-cypress/src/tests/select.cy.ts, projects/kit/components/data-list-wrapper/data-list-group-wrapper.template.html, projects/kit/components/data-list-wrapper/data-list-wrapper.template.html
=> fix(kit): `DataListWrapper` fails to emit `(itemClick)` event

projects/demo/src/modules/app/pages.ts
=> chore: add figma-version in meta

projects/kit/components/multi-select/multi-select.ts
=> fix(kit): `Multiselect` fix export type

projects/cdk/directives/animated/animated.directive.ts
=> chore(cdk): `Animated` fix removal before enter animation finishes

projects/core/styles/mixins/mixins.less, projects/kit/components/line-clamp/line-clamp.style.less, projects/kit/components/push/push.style.less, projects/kit/styles/components/progress-bar.less, projects/layout/components/navigation/main.style.less
Relates:
* https://github.com/taiga-family/toolkit/pull/1098
=> chore: replace some physical css properties with logic alternatives

projects/demo/src/modules/components/textfield/examples/4/index.html, projects/demo/src/modules/components/textfield/examples/4/index.less, projects/demo/src/modules/components/textfield/examples/4/index.ts, projects/demo/src/modules/components/textfield/examples/5/index.html, projects/demo/src/modules/components/textfield/examples/5/index.ts, projects/demo/src/modules/components/textfield/examples/6/index.html, projects/demo/src/modules/components/textfield/examples/6/index.ts, projects/demo/src/modules/components/textfield/index.html, projects/demo/src/modules/components/textfield/index.ts
=> chore: move input-password in separate example

projects/demo/src/modules/components/input-time/examples/4/index.html, projects/demo/src/modules/components/input-time/index.html, projects/demo/src/modules/components/input-time/index.ts, projects/kit/components/input-time/input-time.component.ts, projects/kit/components/input-time/input-time.directive.ts, projects/kit/components/input-time/input-time.options.ts
=> feat(kit): `InputTime` supports `[prefix]` / `[postfix]`

projects/core/components/data-list/data-list.style.less
=> chore: fix datalist

.cspell.json, projects/demo/src/llms.txt, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/demo-routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/directives/shimmer/examples/1/index.html, projects/demo/src/modules/directives/shimmer/examples/1/index.less, projects/demo/src/modules/directives/shimmer/examples/1/index.ts, projects/demo/src/modules/directives/shimmer/examples/2/index.html, projects/demo/src/modules/directives/shimmer/examples/2/index.less, projects/demo/src/modules/directives/shimmer/examples/2/index.ts, projects/demo/src/modules/directives/shimmer/examples/import/import.md, projects/demo/src/modules/directives/shimmer/examples/import/template.md, projects/demo/src/modules/directives/shimmer/index.html, projects/demo/src/modules/directives/shimmer/index.less, projects/demo/src/modules/directives/shimmer/index.ts, projects/kit/directives/index.ts, projects/kit/directives/shimmer/index.ts, projects/kit/directives/shimmer/ng-package.json, projects/kit/directives/shimmer/shimmer.directive.ts, projects/kit/directives/shimmer/shimmer.style.less
=> feat(kit): `Shimmer` add directive

projects/kit/components/input-number/step/input-number-step.style.less
=> fix(kit): `InputNumber` support for RTL

projects/core/styles/theme/appearance/table.less, projects/demo/src/modules/components/input-chip/examples/9/index.html, projects/demo/src/modules/components/input-chip/examples/9/index.less, projects/demo/src/modules/components/input-chip/examples/9/index.ts, projects/demo/src/modules/components/input-chip/index.ts
=> fix(core): support invalid highlight inside `tuiTable`

projects/kit/components/input-date/input-date.directive.ts
=> fix(kit): `InputDate` fix closing parent dropdown

projects/cdk/schematics/collection.json, projects/cdk/schematics/migration.json, projects/cdk/schematics/ng-update/v5/index.ts, projects/cdk/schematics/ng-update/v5/schema.json, projects/cdk/schematics/ng-update/v5/steps/migrate-tokens.ts, projects/cdk/schematics/ng-update/v5/steps/migrate-tokens/migrate-tokens.ts, projects/cdk/schematics/ng-update/v5/steps/migrate-tokens/update-tsconfig.ts, projects/cdk/schematics/ng-update/v5/tests/migrate-tokens/schematic-migrate-tokens.spec.ts, projects/cdk/schematics/ng-update/v5/tests/migrate-tokens/schematic-update-tsconfig.spec.ts, projects/cdk/schematics/ng-update/v5/tests/migrate-tokens/utils.ts
Relates to https://github.com/taiga-family/taiga-ui/issues/10688
=> chore(cdk): add schematic for migration to InjectionToken

projects/core/components/textfield/textfield-multi/textfield-multi.template.html, projects/core/components/textfield/textfield.component.ts, projects/core/components/textfield/textfield.template.html, projects/demo-cypress/src/tests/combo-box/combo-box-non-strict.cy.ts, projects/demo-playwright/tests/core/textfield/textfield-cleaner.pw.spec.ts, projects/kit/components/combo-box/combo-box.directive.ts, projects/kit/components/input-time/input-time.directive.ts
=> fix(kit): `ComboBox` / `InputTime` has broken cleaner

projects/demo/src/modules/components/badged-content/examples/4/index.html, projects/demo/src/modules/components/badged-content/examples/4/index.less, projects/demo/src/modules/components/badged-content/examples/4/index.ts, projects/demo/src/modules/components/badged-content/index.ts, projects/kit/components/badged-content/badged-content.component.ts, projects/kit/components/badged-content/badged-content.style.less, projects/kit/components/badged-content/badged-content.template.html
=> feat(kit): `BadgedContent` add border when using image

projects/kit/components/avatar/avatar.style.less
=> fix(kit): `Avatar` fix 404 in safari

projects/core/components/textfield/textfield.component.ts, projects/demo-playwright/tests/core/textfield/textfield.pw.spec.ts, projects/demo-playwright/utils/get-pseudo-element.ts
=> fix(kit): correct open dropdown in textfield

projects/core/components/textfield/textfield-multi/textfield-multi.template.html, projects/core/components/textfield/textfield.template.html, projects/demo-cypress/src/tests/textfield-disabled-select.cy.ts
=> fix(core): add fine-grained reactivity update in textfield

projects/demo/src/modules/components/chip/examples/5/index.ts
=> chore(demo): extends example `Auto color` for `Chip`

projects/demo/src/modules/components/dialog/index.html
=> chore(demo): `Dialog` migrate to tuiDocAPI

projects/demo/src/modules/components/input-files/index.html
=> chore(demo): `InputFiles` migrate to tuiDocAPI

projects/demo/src/modules/components/progress-circle/index.html
=> chore(demo):  `ProgressCircle` migrate to tuiDocAPI

projects/demo/src/modules/components/slider/index.html
=> chore(demo): `Slider` migrate to tuiDocAPI

projects/demo/src/modules/components/compass/index.html
=> chore(demo): `Compass` migrate to tuiDocAPI

.github/workflows/screenshot-bot.yml
It is job name
https://github.com/taiga-family/taiga-ui/blob/a1b0e17d93365a2659ca0aac2e871c8e0bd01acf/.github/workflows/e2e.yml#L219
It is workflow name
https://github.com/taiga-family/taiga-ui/blob/3dadfceb29e1dc092500f52209e7116633799e0f/.github/workflows/e2e.yml#L1
=> ci: fix screenshot bot report

projects/demo/src/modules/components/preview/examples/1/index.html, projects/kit/components/preview/preview.component.ts
Fixes #11132 
- Support configuration of initial zoom coefficient value
=> feat(kit): supports configuration of initial zoom coefficient in preview

projects/kit/components/input-date-multi/input-date-multi.ts
=> fix(kit): add value reference to TuiInputDateMulti

projects/demo/src/modules/app/pages.ts
=> chore: add input-chip and multiselect to db

projects/addon-mobile/components/sheet-dialog/sheet-dialog.component.ts, projects/addon-mobile/components/sheet-dialog/sheet-dialog.options.ts, projects/demo/src/modules/components/sheet-dialog/index.html, projects/demo/src/modules/components/sheet-dialog/index.less, projects/demo/src/modules/components/sheet-dialog/index.ts
Description:
- add **required** parameter to sheet dialog options
- add support **required** option in  TuiSheetDialogComponent
- sheet dialog demo update with required option
Closes #11082
=> feat(addon-mobile): add support for required option in sheet dialog

projects/core/components/textfield/textfield.directive.ts
=> chore: add textfield attribute

projects/demo/src/modules/app/stackblitz/stackblitz-deps.service.ts
Relates:
* https://github.com/taiga-family/taiga-ui/issues/11457
=> chore(demo): use Angular 20 for StackBlitz examples

projects/demo/src/modules/components/input-number/examples/7/index.html, projects/demo/src/modules/components/input-number/examples/7/index.ts, projects/kit/directives/fluid-typography/fluid-typography.options.ts
=> fix(kit): `FluidTypography` update default values according to the spec

projects/core/components/textfield/textfield-multi/textfield-multi.style.less, projects/core/styles/components/textfield.less
=> chore(core): `TextfieldMulti` limit height for input

.github/copilot-instructions.md
https://docs.github.com/en/copilot/how-tos/configure-custom-instructions/add-repository-instructions
https://angular.dev/ai/develop-with-ai#custom-prompts-and-system-instructions
=> ci: add copilot instructions

projects/demo/src/modules/pipes/emails/examples/import/import.md
=> chore(demo): `Emails` fix example imports

projects/core/components/data-list/data-list.component.ts
=> fix(legacy): broken backward compatibility for `TUI_OPTION_CONTENT` of legacy `Option` component

projects/demo/src/modules/components/thumbnail-card/index.html, projects/demo/src/modules/components/thumbnail-card/index.ts, projects/demo/used-icons.ts
=> chore(demo): `ThumbnailCard` migrate to tuiDocAPI

projects/demo/src/modules/components/tabs/index.html, projects/demo/src/modules/pipes/flag/index.html
=> chore(demo): add missed headings

projects/demo-playwright/tests/demo/source-code-link.pw.spec.ts
=> chore: remove skip test

projects/core/components/textfield/textfield.component.ts, projects/core/components/textfield/textfield.template.html, projects/demo-cypress/src/tests/select.cy.ts, projects/demo-cypress/src/tests/textfield/textfield-form-reset.cy.ts
=> fix(core): `Textfield` with `[content]` has CD problems on form control value patch

projects/demo/src/modules/components/line-days-chart/index.ts
=> chore(demo): fix line-days-chart page

projects/demo/project.json
=> chore(demo): don't use cache if icon packs have been changed

projects/addon-table/components/table/directives/table.directive.ts, projects/demo-playwright/tests/addon-table/table/table.pw.spec.ts, projects/demo/src/modules/components/table/examples/4/index.html
=> fix(addon-table): properly clear sort

projects/demo-cypress/src/tests/input-number/ng-model-postfix-i18n-plural.cy.ts, projects/kit/components/input-number/input-number.directive.ts
=> fix(kit): `InputNumber` with `[postfix]="value | i18nPlural"` has race condition for `[ngModel]`

projects/demo/src/modules/app/pages.ts, projects/kit/components/avatar/avatar-stack.style.less
=> feat(kit): `AvatarStack` update offset according to specs

projects/addon-commerce/components/thumbnail-card/thumbnail-card.style.less, projects/demo/src/modules/app/pages.ts
=> feat(kit): `ThumbnailCard` update icon size according to specs

projects/demo-playwright/tests/demo/source-code-link.pw.spec.ts, projects/demo/src/modules/components/dialog-experimental/index.html
=> chore(demo-playwright): source code link dynamic branch instead main

.github/workflows/pr-assign-author.yml, .github/workflows/pr-collect-linked-issues.yml
Fixes https://github.com/taiga-family/taiga-ui/issues/11697
=> ci: fix assign from fork

projects/core/components/scrollbar/scroll-controls.style.less
=> fix(core): `Scrollbar` fix bars overflowing container

projects/demo/src/modules/components/tooltip/examples/2/index.html, projects/demo/src/modules/directives/hint/examples/1/index.html, projects/demo/src/modules/directives/hint/examples/2/index.html
=> chore(demo): fix inconsistent rendering between Chromium and WebKit by change from UTF-8 to Emoji symbol

projects/demo/src/modules/components/loader/examples/1/index.less, projects/demo/src/modules/components/loader/examples/2/index.less, projects/demo/src/modules/components/tooltip/examples/2/index.less, projects/demo/src/modules/directives/hint/examples/1/index.less
=> chore(demo): fix inconsistent rendering between Chromium and WebKit by removing negative margins

projects/addon-commerce/components/input-card-group/input-card-group.component.ts, projects/core/components/textfield/textfield.directive.ts
=> fix(core): `Textfield` ensure non-erasable affixes actually deleted

projects/demo/src/modules/components/data-list/examples/6/index.html
=> chore(demo): drop redundant title

projects/addon-mobile/styles/common/notification-middle.less, projects/addon-mobile/styles/taiga-ui-mobile.less, projects/core/components/dialog/dialogs.style.less, projects/core/components/root/animations.less, projects/demo/src/modules/app/app.routes.ts, projects/demo/src/modules/app/demo-routes.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/notification-middle/examples/1/index.html, projects/demo/src/modules/components/notification-middle/examples/1/index.ts, projects/demo/src/modules/components/notification-middle/examples/2/index.html, projects/demo/src/modules/components/notification-middle/examples/2/index.ts, projects/demo/src/modules/components/notification-middle/examples/3/index.html, projects/demo/src/modules/components/notification-middle/examples/3/index.ts, projects/demo/src/modules/components/notification-middle/examples/4/index.html, projects/demo/src/modules/components/notification-middle/examples/4/index.ts, projects/demo/src/modules/components/notification-middle/examples/import/import.md, projects/demo/src/modules/components/notification-middle/examples/import/template.md, projects/demo/src/modules/components/notification-middle/index.html, projects/demo/src/modules/components/notification-middle/index.ts, projects/kit/components/index.ts, projects/kit/components/notification-middle/index.ts, projects/kit/components/notification-middle/ng-package.json, projects/kit/components/notification-middle/notification-middle.component.ts, projects/kit/components/notification-middle/notification-middle.directive.ts, projects/kit/components/notification-middle/notification-middle.service.ts, projects/kit/components/notification-middle/notification-middle.style.less
=> feat(kit): `NotificationMiddle` add new component

projects/kit/styles/components/chip.less
=> feat(kit): improved UX for input chip element

projects/core/components/textfield/textfield-multi/textfield-multi.style.less, projects/demo/src/modules/components/items-with-more/examples/2/index.html, projects/demo/src/modules/components/items-with-more/examples/5/index.html, projects/demo/src/modules/components/items-with-more/examples/5/index.less, projects/demo/src/modules/components/items-with-more/examples/5/index.ts, projects/demo/src/modules/components/items-with-more/index.html, projects/demo/src/modules/components/items-with-more/index.ts, projects/demo/used-icons.ts, projects/kit/components/items-with-more/items-with-more.style.less, projects/kit/components/slider/slider.style.less, projects/kit/directives/copy/copy.style.less
=> chore(demo): `ItemsWithMore` add another example

projects/addon-commerce/components/input-card-group/input-card-group.component.ts
=> fix(addon-commerce): `InputCardGroup` label raised on first focus

projects/demo/src/modules/directives/progress-segmented/index.html
=> chore(demo): `ProgressSegmented` migrate to `tuiDocAPI`

projects/demo/src/modules/components/data-list/index.html
=> chore(demo): `DataList` migrate to `tuiDocAPI`

projects/demo/src/modules/directives/fade/index.html
=> chore(demo): `Fade` migrate to `tuiDocAPI`

projects/demo/src/modules/components/table/index.html
=> chore(demo): `Table` migrate to `tuiDocAPI`

projects/demo/src/modules/components/progress-bar/index.html
=> chore(demo): `ProgressBar` migrate to `tuiDocAPI`

projects/demo/src/modules/components/pagination/index.html
=> chore(demo): `Pagination` migrate to `tuiDocAPI`

projects/demo/src/modules/components/confirm/index.html
=> chore(demo): `Confirm` migrate to `tuiDocAPI`

projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/chip/examples/2/index.html, projects/demo/src/modules/components/chip/examples/2/index.ts, projects/kit/styles/components/badge.less, projects/kit/styles/components/chip.less
=> feat(kit): update the badge margin inside the chip according to the specs

projects/addon-mobile/components/sheet-dialog/sheet-dialog.template.html, projects/demo/src/modules/components/sheet-dialog/examples/1/index.html, projects/demo/src/modules/components/sheet-dialog/examples/1/index.ts
=> feat(addon-mobile): `SheetDialog` add basic HTML support

projects/core/components/fullscreen/fullscreen.component.ts, projects/core/components/fullscreen/fullscreen.style.less
(cherry picked from commit ffa84524081833af83a26bbe1fccc8846dad8809)
Fixes #
=> fix(core): `Fullscreen` add scroll (#11855)

projects/demo/src/modules/components/line-clamp/examples/1/index.html, projects/demo/src/modules/components/line-clamp/examples/1/index.ts, projects/kit/components/line-clamp/line-clamp.component.ts, projects/kit/components/line-clamp/line-clamp.style.less
=> fix(kit): Safari bug where line clamp ellipsis doesn't hide properly

.github/workflows/test.yml
=> ci: missing coverage

.cspell.json, .gitignore, projects/demo/project.json, projects/demo/scripts/llms/llms-full-generate.ts, projects/demo/scripts/llms/utils/escaped-html.ts
=> chore: add llm-full html variant

projects/addon-mobile/styles/ios/switch.less, projects/kit/styles/components/switch.less
=> fix(kit): update switch by correct specification

projects/demo/src/modules/app/pages.ts, projects/kit/components/pager/pager.component.ts, projects/kit/components/pager/pager.styles.less
=> fix(kit): update pager by new specification

projects/demo/src/modules/components/combo-box/examples/import/template.md
=> chore: update example

projects/addon-commerce/components/input-card-group/input-card-group.component.ts, projects/addon-commerce/components/input-card-group/input-card-group.providers.ts, projects/addon-commerce/components/input-card-group/input-card-group.style.less, projects/addon-commerce/components/input-card-group/input-card-group.template.html, projects/cdk/directives/let/let.directive.ts, projects/demo/src/modules/components/input-card-group/examples/2/index.html
=> feat(addon-commerce): `InputCardGroup` add 'm' size

projects/addon-mobile/styles/common/badge.less
=> chore: update badge font weight on mobile according to spec

projects/cdk/directives/let/let.directive.ts
=> chore: deprecate `Let`

projects/core/styles/components/button.less, projects/core/styles/mixins/mixins.less, projects/core/styles/mixins/mixins.scss, projects/kit/components/push/push.template.html, projects/kit/styles/components/pin.less, projects/legacy/components/color-selector/color-selector.module.ts
=> chore: `tui-svg` detach

projects/experimental/components/dialog/appearances/fullscreen.less
=> chore: fix safe area

projects/cdk/directives/animated/animated.directive.ts
=> fix(cdk): `Animated` fix memory leak

projects/addon-mobile/components/sheet-dialog/sheet-dialog.style.less, projects/cdk/directives/active-zone/active-zone.directive.ts, projects/cdk/directives/focus-trap/focus-trap.directive.ts, projects/cdk/directives/obscured/obscured.directive.ts, projects/core/components/dialog/active-zone-adapter.directive.ts, projects/core/components/dialog/dialogs.component.ts, projects/core/components/dialog/dialogs.template.html, projects/core/components/dialog/test/dialog.component.spec.ts, projects/core/components/fullscreen/fullscreen.component.ts, projects/core/components/root/root.component.ts, projects/demo/src/modules/directives/active-zone/examples/2/index.html, projects/demo/src/modules/directives/active-zone/examples/2/index.less, projects/demo/src/modules/directives/active-zone/examples/2/index.ts, projects/demo/src/modules/directives/active-zone/index.html
=> feat(core): `Dialogs` auto attach to current active zone

projects/experimental/components/dialog/dialog.component.ts, projects/experimental/components/dialog/dialog.template.html, projects/kit/components/confirm/confirm.style.less
=> fix(experimental): `Dialog` fix `label`

projects/demo-playwright/tests/kit/input-chip/textfield.pw.spec.ts, projects/kit/components/input-chip/input-chip.directive.ts
Fixes #11938
https://github.com/user-attachments/assets/a559d799-65a7-4080-bde4-570b3c44afd4
=> feat(kit): more intuitive way for users to remove input chips by backspace

projects/demo/src/modules/components/rating/examples/1/index.less, projects/demo/src/modules/components/rating/examples/2/index.less, projects/demo/src/modules/components/rating/examples/3/index.html, projects/demo/src/modules/components/rating/examples/3/index.ts, projects/kit/components/rating/rating.component.ts, projects/kit/components/rating/rating.options.ts, projects/kit/components/rating/rating.style.less, projects/kit/components/rating/rating.template.html
=> feat(kit): `Rating` add `filled` to icon context and allow background customization

projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/input-chip/examples/10/index.html, projects/demo/src/modules/components/input-chip/examples/10/index.less, projects/demo/src/modules/components/input-chip/examples/10/index.ts, projects/demo/src/modules/components/input-chip/index.html, projects/demo/src/modules/components/input-chip/index.ts
=> chore(demo): add virtual scroll example courtesy of Inkin

projects/addon-doc/components/theme-switcher/theme-switcher.component.ts, projects/addon-doc/components/theme-switcher/theme-switcher.template.html
=> chore(addon-doc): `ThemeSwitcher` migrate to ther new `Select`

.cspell.json, projects/cdk/tokens/environment.ts, projects/cdk/tokens/tests/mobile-regexp.spec.ts
=> feat(cdk):  ensure `TUI_MOBILE_REGEXP`

projects/demo-cypress/src/tests/input-slider/input-slider-patch-form-control.cy.ts, projects/demo/src/modules/components/input-number/index.html, projects/demo/src/modules/components/input-number/index.ts, projects/demo/src/modules/components/input-range/index.html, projects/demo/src/modules/components/input-slider/index.html, projects/demo/src/modules/components/input-slider/index.ts, projects/kit/components/input-number/quantum.directive.ts, projects/kit/components/input-range/input-range.component.ts
=> fix(kit): `TuiQuantumValueTransformer` has invalid default value

projects/core/styles/mixins/slider.less, projects/demo-cypress/src/tests/input-slider/slider-ticks.styles.less, projects/kit/components/slider/slider.style.less
Fixes #11759
Update styles according to new design specs:
=> feat(kit): `InputSlider` has new paddings for slider track

projects/demo-playwright/tests/core/data-list/data-list.pw.spec.ts, projects/demo/src/modules/components/data-list/examples/5/index.html, projects/demo/src/modules/components/data-list/examples/5/index.ts, projects/demo/src/modules/components/line-days-chart/examples/1/index.html, projects/demo/src/modules/components/line-days-chart/examples/1/index.ts, projects/demo/src/modules/components/line-days-chart/examples/2/index.html, projects/demo/src/modules/components/line-days-chart/examples/2/index.less, projects/demo/src/modules/components/line-days-chart/examples/2/index.ts
=> chore(demo): `InputDateRange` detach old approach

projects/core/tokens/dark-mode.ts
=> chore(core): `TUI_DARK_MODE` factory untracked only effect

eslint.config.ts, projects/addon-mobile/styles/taiga-ui-mobile.less, projects/cdk/services/popover.service.ts, projects/demo-playwright/utils/wait-icons.ts, projects/demo/scripts/llms/utils/file-system.ts, projects/demo/src/modules/app/pages.ts, projects/demo/src/modules/components/toast/examples/1/index.html, projects/demo/src/modules/components/toast/examples/1/index.less, projects/demo/src/modules/components/toast/examples/1/index.ts, projects/demo/src/modules/components/toast/examples/2/index.html, projects/demo/src/modules/components/toast/examples/2/index.less, projects/demo/src/modules/components/toast/examples/2/index.ts, projects/demo/src/modules/components/toast/examples/3/index.html, projects/demo/src/modules/components/toast/examples/3/index.less, projects/demo/src/modules/components/toast/examples/3/index.ts, projects/demo/src/modules/components/toast/examples/import/template.md, projects/demo/src/modules/components/toast/index.html, projects/demo/src/modules/components/toast/index.ts, projects/kit/components/toast/index.ts, projects/kit/components/toast/toast.component.ts, projects/kit/components/toast/toast.directive.ts, projects/kit/components/toast/toast.options.ts, projects/kit/components/toast/toast.service.ts, projects/kit/components/toast/toast.style.less, projects/kit/components/toast/toast.template.html, projects/kit/components/toast/toast.ts, projects/kit/styles/components/toast.less, projects/testing/utils/replace-nbsp.ts
Fixes TUIPRJ-32
https://github.com/user-attachments/assets/14f40f17-76a0-4252-ab2c-8a19c5da6d63
=> feat(kit): add toast service

projects/layout/components/app-bar/app-bar.component.ts, projects/layout/components/app-bar/app-bar.directive.ts, projects/layout/components/block-status/block-status.component.ts, projects/layout/components/block-status/block-status.directive.ts, projects/layout/components/card/large.directive.ts, projects/layout/components/dynamic-header/dynamic-header-container.directive.ts, projects/layout/components/input-search/input-search.component.html, projects/layout/components/input-search/input-search.component.ts
=> chore: `layout` use signal inputs

projects/layout/components/navigation/aside-group.component.ts, projects/layout/components/navigation/aside-group.template.html, projects/layout/components/navigation/aside.component.ts, projects/layout/components/navigation/drawer.component.ts, projects/layout/components/search/search-filter.component.ts, projects/layout/components/search/search-filters.component.ts, projects/layout/components/search/search-filters.template.html
=> chore: `Navigation`, `SearchFilters` use input signals

projects/demo/src/modules/components/table/examples/8/index.html, projects/demo/src/modules/components/table/examples/8/index.ts
=> chore(demo): `InputTag` migrate to `InputChip`

projects/cdk/utils/dom/get-element-obscurers.ts, projects/cdk/utils/dom/test/get-element-obscurers.spec.ts, projects/demo-playwright/tests/core/dropdown/dropdown.pw.spec.ts
=> fix(cdk): `Obscured` properly handle offscreen case

projects/demo-playwright/tests/kit/input-range/input-range.pw.spec.ts, projects/demo/src/modules/components/input-range/examples/4/index.html, projects/demo/src/modules/components/input-range/index.ts, projects/kit/components/input-range/input-range.component.ts, projects/kit/components/input-range/input-range.style.less, projects/kit/components/input-range/input-range.template.html
=> feat(kit): `InputRange` has new appearance for readonly/disabled state

projects/kit/components/input-slider/input-slider.directive.ts
=> fix(kit): `InputSlider` has broken drag behavior for slider in Firefox

projects/addon-doc/components/navigation/navigation.component.ts, projects/addon-doc/components/navigation/navigation.template.html
=> chore(addon-doc): `Navigation` use drawer instead sidebar

projects/addon-doc/components/demo/index.html, projects/demo-playwright/tests/inputs/update-on.pw.spec.ts, projects/kit/components/data-list-wrapper/data-list-wrapper.template.html
=> chore: temporary add animation-id for tests

projects/demo/src/modules/app/search/index.less, projects/demo/src/modules/app/search/index.ts
=> chore: add debounce for docsearch

projects/demo/src/modules/components/group/examples/1/index.html, projects/demo/src/modules/components/group/examples/1/index.ts, projects/kit/styles/components/chip.less
=> chore(demo): `Group` migrate to `InputChip`

projects/demo/src/modules/pipes/stringify-content/examples/1/index.html, projects/demo/src/modules/pipes/stringify-content/examples/1/index.ts, projects/demo/src/modules/pipes/stringify-content/examples/import/template.md, projects/demo/src/modules/pipes/stringify-content/index.html
=> chore(demo): `StringifyContent` migrate to new `tuiComboBox`

projects/demo/src/modules/pipes/filter-by-input/examples/2/index.html, projects/demo/src/modules/pipes/filter-by-input/examples/2/index.ts
=> chore(demo): `FilterByInput` migrate to new `tuiComboBox`

projects/demo/src/modules/components/data-list-wrapper/examples/2/index.html, projects/demo/src/modules/components/data-list-wrapper/examples/2/index.ts
=> chore(demo): `DataListWrapper` migrate to new `tuiComboBox`

projects/cdk/date-time/day.ts, projects/cdk/date-time/test/day.spec.ts, projects/demo-playwright/tests/kit/calendar-range/calendar-range.pw.spec.ts, projects/demo/src/modules/components/calendar-range/index.ts
=> fix(cdk): `TuiDay` incorrectly appends month in backward direction
